wildfly/wildfly-core

- elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
wildfly-elytron-integration: https://issues.jboss.org/browse/WFCORE-3137
JBEAP: https://issues.jboss.org/browse/JBEAP-12498
> [WFCORE-3137] Server stops when creating new elytron policy with wrong default-policy value

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/elytron/SlaveHostControllerElytronAuthenticationTestCase.java
Reverts wildfly/wildfly-core#2670
Reverting as I just saw a failure: https://ci.wildfly.org/viewLog.html?buildId=70564&buildTypeId=WildFlyCore_PullRequest
@luck3y fyi
> Revert "WFCORE-3120 - fix and reenable SlaveHostControllerElytronAuthenticationTestCase.slaveWithPlainMechanism()"

- pom.xml
https://issues.jboss.org/browse/WFCORE-3154
https://issues.jboss.org/browse/WFCORE-3153
> Upgrades of David's components

- pom.xml
https://issues.jboss.org/browse/WFCORE-3169
https://issues.jboss.org/browse/JBEAP-12390
> [WFCORE-3169] / [WFCORE-3170] WildFly Elytron and Elytron Web Component Upgrades

- pom.xml
https://issues.jboss.org/browse/WFCORE-3163
https://issues.jboss.org/browse/WFCORE-3161
https://issues.jboss.org/browse/WFCORE-3160
> More upgrades of David's components

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
https://issues.jboss.org/browse/WFCORE-3168
https://issues.jboss.org/browse/JBEAP-12642
> [WFCORE-3168] warning when setting or removing secret value for alias

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/AliasResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingImmutableManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ImmutableManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java
- controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
https://issues.jboss.org/browse/WFCORE-3139
This is one of the fixes relevant to https://issues.jboss.org/browse/JBEAP-9326.
> [WFCORE-3139] Optimize ValidateModelStepHandler

- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/ScramPlusMgmtSaslTestCase.java
- testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/ConstantRealmMapper.java
- testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TrustedDomainsConfigurator.java
JIRAs:
* upstream: https://issues.jboss.org/browse/WFCORE-3071
* downstream: https://issues.jboss.org/browse/JBEAP-12176
Add test coverage for Scram PLUS mechanisms. The tests will also serve as regression tests for https://issues.jboss.org/browse/JBEAP-11396.
> [WFCORE-3071] add test coverage for SCRAM-*-PLUS Elytron SASL mechanisms

- core-feature-pack/src/license/core-feature-pack-licenses.xml
- core-feature-pack/src/main/resources/content/docs/licenses/icu license - icu 1.8.1 to icu 57.1.txt
- core-feature-pack/src/main/resources/content/docs/licenses/icu license.html
- core-feature-pack/src/main/resources/content/docs/licenses/licenses.xsl
upstream JIRA: https://issues.jboss.org/browse/WFCORE-3189
> [WFCORE-3189] Fixing wrong ICU License link/text

- pom.xml
https://issues.jboss.org/browse/WFCORE-3158
> [WFCORE-3158] Upgrade to xnio 3.5.0.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3158
> [WFCORE-3158] Upgrade to xnio 3.5.1.Final

- elytron/src/main/resources/subsystem-templates/elytron.xml
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_5.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_5.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_5.java
* Reordering elements so that they appear in the same order after a marshaling.
* Removing the creation of empty lines so that configuration files are not updated with just new empty lines.
Jira: https://issues.jboss.org/browse/WFCORE-3192
JBEAP: https://issues.jboss.org/browse/JBEAP-12768
> [WFCORE-3192]:Remarshaling the default configuration xml files shouldn't change the files

- protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
https://issues.jboss.org/browse/WFCORE-3183
https://issues.jboss.org/browse/JBEAP-12696
> [WFCORE-3183] CallbackKinds restriction for for CLI handler

- pom.xml
https://issues.jboss.org/browse/WFCORE-3198
https://issues.jboss.org/browse/WFCORE-3166
https://issues.jboss.org/browse/WFCORE-3165
https://issues.jboss.org/browse/JBEAP-12595
https://issues.jboss.org/browse/JBEAP-12598
https://issues.jboss.org/browse/JBEAP-12619
> [WFCORE-3166] / [WFCORE-3165] / [WFCORE-3198] Upgrade WildFly Components to .Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3152
> [WFCORE-3152] Upgrade JBoss Invocation to 1.5.0.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3155
Also includes the JBoss Invocation upgrade commit from #2732 in order to let the CI run test the combination.
> [WFCORE-3155] Upgrade JBoss Remoting to 5.0.0.Final

- pom.xml
https://issues.jboss.org/browse/JBEAP-12583
https://issues.jboss.org/browse/WFCORE-3157
> [WFCORE-3157] Upgrade Remoting JMX to 3.0.0.Final

- core-feature-pack/src/license/core-feature-pack-licenses.xml
- core-feature-pack/src/main/resources/content/docs/licenses/gnu lesser general public license v2.1 or later.html
- core-feature-pack/src/main/resources/content/docs/licenses/licenses.xsl
> [WFLY-8418] update licenses

- controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
Follow up to #2433 that removes the remaining deprecated items.
https://issues.jboss.org/browse/WFCORE-2859
> [WFCORE-2859] Remove remaining deprecated ManagementResourceRegistration.Factory items

- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
Pretty much same as https://github.com/jboss-modules/jboss-modules/commit/58cee5d7267310cbaee082cd66e0f58925461cd2
> WFCORE-1374 fix security provider loading on jdk9

- cli/pom.xml
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
- cli/src/main/java/org/jboss/as/cli/impl/Console.java
- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/main/java/org/jboss/as/cli/parsing/DefaultStateWithEndCharacter.java
- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/content/bin/jboss-cli-logging.properties
- core-feature-pack/src/main/resources/modules/system/layers/base/org/aesh/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
- patching/src/test/java/org/jboss/as/patching/cli/LocalPatchInfoPatchIdUnitTestCase.java
- patching/src/test/java/org/jboss/as/patching/cli/PatchInspectUnitTestCase.java
- pom.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/RemoveManagementRealmTestCase.java
- testsuite/patching/src/test/java/org/jboss/as/test/patching/PatchInfoTestCase.java
- testsuite/patching/src/test/java/org/jboss/as/test/patching/PatchStreamsUnitTestCase.java
- testsuite/patching/src/test/java/org/jboss/as/test/patching/RemotePatchInfoPatchIdUnitTestCase.java
- testsuite/patching/src/test/java/org/jboss/as/test/patching/RemotePatchInfoUnitTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessBuilder.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessWrapper.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLITestUtil.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLIWrapper.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliEmbedServerTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FileInputTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/extensions/CliExtCommandHandler.java
These are the first CLI commits for 4.0. Integrates aesh-readline and some fixes too risky for 3.0.
So not to be merged in 3.x.
> CLI bunch of fixes for 4.0

- pom.xml
Upstream PR https://github.com/wildfly/wildfly-core/pull/2739
https://issues.jboss.org/browse/WFCORE-3241
> [WFCORE-3241] Upgrade WildFly Elytron to 1.1.2.CR1

- server/src/main/java/org/jboss/as/server/deployment/integration/Seam2Processor.java
master: https://github.com/wildfly/wildfly-core/pull/2759
> [3.x] WFCORE-3237 Seam integration jar name mismatch

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLIWrapper.java
https://issues.jboss.org/browse/WFCORE-3239
> [WFCORE-3239] CLIWrapper does not allow for use in multinode tests

- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
Master PR: https://github.com/wildfly/wildfly-core/pull/2767
> WFCORE-3226 (core 3.x branch): Legacy slaves can't understand new enum version values

- testsuite/pom.xml
https://issues.jboss.org/browse/WFCORE-3253
> [WFCORE-3253] Upgrade the wildfly-maven-plugin to version 1.2.0.Final

- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
Minor cleanup of stuff accidentally left behind
> [WFCORE-3266] Get rid of noisy debug logging

- pom.xml
Upstream PR https://github.com/wildfly/wildfly-core/pull/2739
https://issues.jboss.org/browse/WFCORE-3279
https://issues.jboss.org/browse/WFCORE-3280
https://issues.jboss.org/browse/WFCORE-3281
> [WFCORE-3279] WildFly Elytron Component Upgrades

- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
https://issues.jboss.org/browse/WFCORE-3273
> [WFCORE-3273] Always wrap using the shared state realm as plug-ins expect a shared state Map in all situations.

- elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
https://issues.jboss.org/browse/WFCORE-3276
> [WFCORE-3276] unignore test in IdentityOperationsTestCase

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/KerberosServerIdentityTestCase.java
https://issues.jboss.org/browse/WFCORE-3277
> [WFCORE-3277] unignore KerberosServerIdentityTestCase

- core-feature-pack/src/main/resources/content/bin/elytron-tool.ps1
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1350
JBEAP: https://issues.jboss.org/browse/JBEAP-12915
> [WFCORE-3299] Wildfly Elytron Tool, Powershell script elytron-tool.ps1 doesn't work with custom credential store implementation.

- logging/src/main/java/org/jboss/as/logging/KnownModelVersion.java
- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_4_0.java
- logging/src/main/java/org/jboss/as/logging/Namespace.java
- logging/src/main/resources/schema/jboss-as-logging_4_0.xsd
- logging/src/main/resources/subsystem-templates/logging.xml
- logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
- logging/src/test/resources/default-subsystem.xml
- logging/src/test/resources/empty-subsystem.xml
- logging/src/test/resources/expressions_3_0.xml
- logging/src/test/resources/logging.xml
- logging/src/test/resources/operations.xml
- logging/src/test/resources/rollback-logging.xml
- logging/src/test/resources/simple-subsystem.xml
https://issues.jboss.org/browse/WFCORE-3303
> [WFCORE-3303] Bump the logging subsystem schema and model versions.

- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/ShutdownFileSystemDeploymentServiceUnitTestCase.java
Some deployment-scanner unit tests from wf-core fail on IBM JDK intermittently.
This is testsuite issue only.
Affected test cases:
* ShutdownFileSystemDeploymentServiceUnitTestCase
* FileSystemDeploymentServiceUnitTestCase
Executors.newSingleThreadExecutor() method returns ExecutorService with finalize method, that shutdown thread executor. Currently ExecutorService instance is not referenced, so IBM JDK calls finalize method. It calls shutdown method and size of thread-pool is decreased to 0 before lockDone.get(...) is called.
JBEAP jira: https://issues.jboss.org/browse/JBEAP-13258
WF-CORE jira: https://issues.jboss.org/browse/WFCORE-3317
EAP 3.0.x PR: https://github.com/jbossas/wildfly-core-eap/pull/433
upstream 3.x PR: https://github.com/wildfly/wildfly-core/pull/2846
> [WFCORE-3317] Deployment-scanner unit tests fail on IBM JDK intermittently

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultCallbackHandler.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestParser.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/HeadersCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/RolloutPlanCompleter.java
- cli/src/main/java/org/jboss/as/cli/parsing/ParserUtil.java
- cli/src/main/java/org/jboss/as/cli/parsing/StateParser.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/SimplifiedOperationParameterFormatTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java
Fixed calls to parser tha tweet not making use of CommandContext. Added unit test.
> Fix for WFCORE-3314, fix some basic ops that don't support variables

- pom.xml
https://issues.jboss.org/browse/WFCORE-3326
> [WFCORE-3326] Upgrade WildFly Elytron to 1.2.0.Beta4

- pom.xml
Upstream PR https://github.com/wildfly/wildfly-core/pull/2854
> [WFCORE-3325] Upgrade to WildFly Elytron 1.1.3.Final

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ClientCompatibilityUnitTestBase.java
https://issues.jboss.org/browse/WFCORE-3294
> [WFCORE-3294] Add more client versions

- server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-3330
> [WFCORE-3330] Use ExtensionRegistryType.SERVER on servers

- io/subsystem/src/main/java/org/wildfly/extension/io/IOExtension.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
- io/subsystem/src/main/resources/org/wildfly/extension/io/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-3333
> [WFCORE-3333] Expose number of busy threads in the task worker thread pool

- pom.xml
https://issues.jboss.org/browse/WFCORE-3344
> [WFCORE-3344] Upgrade WildFly Elytron to 1.2.0.Beta5

- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
The add-identity operation requires `ServiceController<ModifiableSecurityRealm>` service in UP state. In some circumstances, this service controller could require more time to start, generating failures in batch-mode if add-identity is called after adding the file-system-realm.  This patch gives a chance to get the service UP waiting until 500 milliseconds.
Issue: https://issues.jboss.org/browse/WFCORE-3257
JBEAP issue: https://issues.jboss.org/browse/JBEAP-13038
> [WFCORE-3257] add-identity filesystem-realm operation in Elytron subsystem might fail in batch-mode

- controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
- controller/src/main/java/org/jboss/as/controller/remote/OperationMessageHandlerProxy.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/logging/EmbeddedLogger.java
- io/subsystem/src/main/java/org/wildfly/extension/io/OptionAttributeDefinition.java
- patching/src/main/java/org/jboss/as/patching/tool/PatchingHistory.java
- process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
- process-controller/src/main/java/org/jboss/as/process/logging/ProcessLogger.java
Issue: https://issues.jboss.org/browse/JBEAP-12220
Upstream Issue: https://issues.jboss.org/browse/WFCORE-3319
> WFCORE-3319 - There should be replaced stacktrace loggings to stderr with usage of logging

- pom.xml
Upstream PR - https://github.com/wildfly/wildfly-core/pull/2883
https://issues.jboss.org/browse/WFCORE-3357
https://issues.jboss.org/browse/WFCORE-3358
> [WFCORE-3357] / [WFCORE-3358] WildFly Elytron Component Upgrades

- elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/DomainService.java
(to the next release)
depends on https://github.com/wildfly-security/wildfly-elytron/pull/974
https://issues.jboss.org/browse/WFCORE-3216
https://issues.jboss.org/browse/JBEAP-11498
> [WFCORE-3216] security-domain without realms support

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/accesscontrol/BaseAccessRequirement.java
- cli/src/main/java/org/jboss/as/cli/accesscontrol/CLIAccessControl.java
- cli/src/main/java/org/jboss/as/cli/gui/JConsoleCLIPlugin.java
- cli/src/main/java/org/jboss/as/cli/handlers/LsHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/DeploymentItemCompleter.java
- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/CapabilityReferenceCompleter.java
JBEAP: https://issues.jboss.org/browse/JBEAP-4904
upstreams: https://issues.jboss.org/browse/WFCORE-2154, https://issues.jboss.org/browse/WFCORE-1583
> [JBEAP-4904, WFCORE-2154] Enhance CLI logging

- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/resources/help/help.txt
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Adding the "--no-operation-validation" flag.
Jira: https://issues.jboss.org/browse/WFCORE-3324
> [WFCORE-3324]:  Add a commands line flag to disable request validation.

- core-management/core-management-client/src/main/java/org/wildfly/extension/core/management/client/Process.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java
- server/src/main/java/org/jboss/as/server/BootstrapImpl.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/jmx/RunningStateJmx.java
https://issues.jboss.org/browse/WFCORE-3348
> [WFCORE-3348] Minor optimizations in RunningStateJmx registration

- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DeploymentOverlayTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DeploymentTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/SocketBindingGroupTransformers.java
- version/src/main/java/org/jboss/as/version/Version.java
Also, add automatic host-exclude discard transformation for any non-current version.
Update the other domain transformers to use the enum I added to support the host-exclude thing.
> [WFCORE-3309] Bump the kernel management API version.

- pom.xml
Upstream PR https://github.com/wildfly/wildfly-core/pull/2898
https://issues.jboss.org/browse/WFCORE-3370
https://issues.jboss.org/browse/WFCORE-3371
> [WFCORE-3370] / [WFCORE-3371] WildFly Elytron Component Upgrades

- build/pom.xml
- dist/pom.xml
- model-test/pom.xml
- pom.xml
- subsystem-test/framework/pom.xml
- testsuite/client-old-server/pom.xml
- testsuite/client-old-server/server-provisioning.xml
- testsuite/elytron/pom.xml
- testsuite/elytron/server-provisioning.xml
- testsuite/manualmode/pom.xml
- testsuite/manualmode/server-provisioning.xml
- testsuite/patching/pom.xml
- testsuite/rbac/pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessWrapper.java
- testsuite/standalone/pom.xml
- testsuite/standalone/server-provisioning.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
follow up on https://github.com/wildfly/wildfly-core/pull/2880 & https://github.com/wildfly/wildfly-core/pull/2912
> WFCORE-3352 Use thin provisioned server everywhere in testsuite

- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
- elytron/src/main/resources/schema/wildfly-elytron_1_1.xsd
- elytron/src/main/resources/schema/wildfly-elytron_1_2.xsd
- elytron/src/main/resources/schema/wildfly-elytron_2_0.xsd
wildfly-elytron-integration: https://issues.jboss.org/browse/WFCORE-2367
JBEAP: https://issues.jboss.org/browse/JBEAP-7495
> [WFCORE-2367] Misleading description of identity-realm

- cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java
please see example in https://issues.jboss.org/browse/WFCORE-3379
> [WFCORE-3379] log warn message than print stack trace into terminal.

- controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/operations/common/InterfaceAddHandler.java
- controller/src/main/java/org/jboss/as/controller/operations/common/InterfaceCriteriaWriteHandler.java
- server/src/main/java/org/jboss/as/server/services/net/SpecifiedInterfaceResolveHandler.java
https://issues.jboss.org/browse/WFCORE-3392
> [WFCORE-3392] remind user possible alternatives in failure message

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
please see issue https://issues.jboss.org/browse/WFCORE-3347
> [WFCORE-3347] add ability to remove alternatives and remove unnecessary ones in DeploymentAttributes.

- pom.xml
Upstream PR https://github.com/wildfly/wildfly-core/pull/2919
https://issues.jboss.org/browse/WFCORE-3400
https://issues.jboss.org/browse/WFCORE-3401
> [WFCORE-3400] / [WFCORE-3401] WildFly Elytron Component Upgrades

- controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
- controller/src/test/java/org/jboss/as/controller/registry/ExtendWildCardRegistrationUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-3410
> [WFCORE-3410] Don't call into parent MRRs when identifying children to recursively remove. An MRR only removes from its own subregistry anyway.

- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
https://issues.jboss.org/browse/WFCORE-3422
> [WFCORE-3422] Make immutable field final

- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
- pom.xml
https://issues.jboss.org/browse/WFCORE-3427
> [WFCORE-3427] Upgrade WildFly Elytron to 1.2.0.Beta10

- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
issue problem, please see https://issues.jboss.org/browse/WFCORE-3434 
It would have same issue if people use VAULT + security subsystem.
> [WFCORE-3434] update vaultNotInitializedException level to DEBUG

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliVariablesTestCase.java
Remove leading whitespaces from command line received from terminal.
> Fix for WFCORE-3438, remove leading whitespaces

- controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingResource.java
- controller/src/main/java/org/jboss/as/controller/registry/PlaceholderResource.java
- controller/src/main/java/org/jboss/as/controller/registry/Resource.java
- controller/src/main/java/org/jboss/as/controller/registry/ResourceProvider.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanServerPlugin.java
- jmx/src/main/java/org/jboss/as/jmx/model/ObjectNameAddressUtil.java
- jmx/src/main/java/org/jboss/as/jmx/model/RootResourceIterator.java
- jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
- logging/src/main/java/org/jboss/as/logging/LoggingResource.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/LeafPlatformMBeanResource.java
Reverts and replaces the https://issues.jboss.org/browse/WFCORE-3415 work done in #2930. 
That work was incorrectly counting the mbeans because it would count some bogus resources that are in the resource tree but for which there is no type registration. An EE test was detecting this miscount and failing. It would be good to get rid of those bogus resources but that is not simple at all and could be prone to regression.
This PR has the same conceptual solution as the previous one: don't count both JMX domains and drop the RBAC check when counting. It has to iterate the resource tree though. It solves the problem from the other PR by checking each address for validity when iterating.
Since this was reasonably fast but still quite a bit slower than the old PR, I spent quite a bit of effort …
> [WFCORE-3415] Take 2

- cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueCallbackHandler.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ArgumentValueParsingTestCase.java
https://issues.jboss.org/browse/WFCORE-3440
> [WFCORE-3440] CLI incorrectly parses byte literals

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialSecurityFactoryParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_2_0.xsd
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1013
https://issues.jboss.org/browse/WFCORE-3361
https://issues.jboss.org/browse/JBEAP-11055
> [WFCORE-3361] GSSCredential obtaining fail caching for fast fallback

- core-feature-pack/src/main/resources/content/bin/elytron-tool.bat
- core-feature-pack/src/main/resources/content/bin/elytron-tool.ps1
- core-feature-pack/src/main/resources/content/bin/elytron-tool.sh
wildfly-core: https://issues.jboss.org/browse/WFCORE-3412
JBEAP: https://issues.jboss.org/browse/JBEAP-13758
> [WFCORE-3412] elytron-tool.* scripts use SEP variable

- cli/src/main/resources/help/help.txt
> Added help content for WFCORE-2283, CLI completion of required and alternatives

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
wildfly-elytron-integration: https://issues.jboss.org/browse/WFCORE-3398
JBEAP: https://issues.jboss.org/browse/JBEAP-13688
> [WFCORE-3398] Elytron, wrong capabilities registered

- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
https://issues.jboss.org/browse/WFCORE-3461
> [WFCORE-3461] Be able to directly query the root management mbean

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
Added an option to configure the service display name during service install (WFLY-9619)
> [WFCORE3470] Configure service display name

- host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
https://issues.jboss.org/browse/WFCORE-3472
> [WFCORE-3472] Add EAP 7.1 as a KnownRelease

- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
- elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1041
https://issues.jboss.org/browse/WFCORE-3460
> [WFCORE-3460] Update the public packages in the org.wildfly.security.elytron module

- jmx/src/main/java/org/jboss/as/jmx/MBeanServerSignature.java
WFLY: https://issues.jboss.org/browse/WFCORE-3492
EAP 7.2: https://issues.jboss.org/browse/JBEAP-14045
EAP 7.1.z: https://issues.jboss.org/browse/JBEAP-14046
> [WFCORE-3492][JBEAP-14045] - remove notificaition use wrong method name

- cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Renaming 2 tests in ValueTypeCompletionTestCase.
> [WFCORE-3487] ValueTypeCompletionTestCase test renaming

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
Arrow down key to scroll one line. Updated analysis document, manual testing.
> Fix for WFCORE-3507, use arrow Down key to scroll

- ide-configs/eclipse/wildfly-templates.xml
> Evaluate to the current year in code templates.

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ForLoopTestCase.java
This should be merged after #3016 and #3019, because it changes the same files and it may cause conflicts.
> [WFCORE-3511] Improve test coverage of WFCORE-3236

- elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
issue: https://issues.jboss.org/browse/WFCORE-3518
> [WFCORE-3518] Elytron principal-query attribute of jdbc-realm is required but description says false

- elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/CustomComponentDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/RealmDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/RealmMapperDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
Refactoring: removed unnecessary elytron utils, which was deprecated as suggested in
https://github.com/wildfly/wildfly-core/pull/2480#discussion_r119153768
https://issues.jboss.org/browse/WFCORE-2902
> [WFCORE-2902] elytron cleanup: replacing as*IfDefined util by as*OrNull

- cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
- cli/src/main/resources/help/shutdown.txt
Jira issue:
https://issues.jboss.org/browse/WFCORE-3486
> [WFCORE-3486] Avoid the uses of timeout in domain mode shutdown operation

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Add certificate with unique ID. Manual testing.
> Fix for WFCORE-3494, CLI, infinite loop when accepting temporarily SSL certificate

- pom.xml
https://issues.jboss.org/browse/WFCORE-3543
https://issues.jboss.org/browse/WFCORE-3544
> [WFCORE-3543] / [WFCORE-3544] WildFly Elytron Component Upgrades

- request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
Updates the runQueuedTask() method to always check whether there are any
tasks in the task queue. This prevents tasks from getting stuck in the
task queue forever if they were placed in there while the container was
at the max request limit.
Additionally, the changes to the runQueuedTask() method in this commit
ensure that forced tasks do not get lost anymore if the container is
paused and has reached the request limit.
https://issues.jboss.org/browse/WFCORE-3565
> Fix WFCORE-3565: Check task queue for more tasks

- core-feature-pack/src/main/resources/content/docs/licenses/licenses.xsl
> display full version of wildfly core in title in licenses.html

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- patching/src/main/java/org/jboss/as/patching/management/PatchIntegrationFactory.java
https://issues.jboss.org/browse/WFCORE-3586
> WFCORE-3586 - issues with adding jmx to embedded HC started with empty config

- cli/src/main/java/org/jboss/as/cli/handlers/EchoVariableHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/PipeTestCase.java
WFCORE jira: https://issues.jboss.org/browse/WFCORE-3555
> [WFCORE-3555] Pipe with echo commad gives incorrect result

- controller/src/main/java/org/jboss/as/controller/SubsystemRegistration.java
https://issues.jboss.org/browse/WFCORE-3441
> [WFCORE-3441] Undeprecate

- pom.xml
https://issues.jboss.org/browse/WFCORE-3603
> [WFCORE-3603] Update JBoss DMR to 1.5.0.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3599
https://issues.jboss.org/browse/WFCORE-3601
https://issues.jboss.org/browse/WFCORE-3602
> [WFCORE-3599] / [WFCORE-3601] / [WFCORE-3602] WildFly Elytron Component Upgrades

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ClientCompatibilityUnitTestBase.java
https://issues.jboss.org/browse/WFCORE-3391
> [WFCORE-3391] Add client compatibility tests using the 3.0.x client

- pom.xml
https://issues.jboss.org/browse/WFCORE-3626
https://issues.jboss.org/browse/WFCORE-3627
> [WFCORE-3626] / [WFCORE-3627] WildFly Elytron Component Upgrades

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/ServerReload.java
https://issues.jboss.org/browse/WFCORE-3630
> WFCORE-3630 wait 100ms before checking server state on reload

- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerConfigurationPersister.java
https://issues.jboss.org/browse/WFCORE-3629
> [WFCORE-3629] Don't ignore an empty host.xml in the non-embedded case

- host-controller/src/main/java/org/jboss/as/host/controller/Main.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ReadOnlyModeTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Updating the ConfigurationFile.InteractionPolicy for host / domain if the args are --read-only-host-config and --read-only-domain-config.
Jira: https://issues.jboss.org/browse/WFCORE-3633
> [WFCORE-3633]: Read only mode is not properly supported for domain.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
https://issues.jboss.org/browse/WFCORE-3622
Test was calling serverController.start() on a killed controller, assuming that would start the server again to allow a subsequent undeploy op. But the serverController didn't know it was killed, so the 'start()' call did nothing and the undeploy wasn't getting executed.
Use https://github.com/wildfly/wildfly-core/pull/3119/files?w=1 to look at this or the change looks much bigger due to removal of a try/catch/finally surrounding the main part of the test.
> [WFCORE-3622] Fix the SuspendOnSoftKillTestCase cleanup work

- .gitignore
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ReadOnlyModeTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-3642
> [WFCORE-3642]:  Cleaning the domain after the test

- pom.xml
https://issues.jboss.org/browse/WFCORE-3644
https://issues.jboss.org/browse/WFCORE-3645
> [WFCORE-3644] / [WFCORE-3645] WildFly Elytron Component Upgrades

- pom.xml
https://issues.jboss.org/browse/WFCORE-3664
> WFCORE-3664 WildFly OpenSSL 1.0.4.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3660
https://issues.jboss.org/browse/WFCORE-3661
> [WFCORE-3660] / [WFCORE-3661] WildFly Elytron Component Upgrades

- pom.xml
Putting these in one PR as they are both minor and otherwise they will conflict as they are right next to each other in the pom
https://issues.jboss.org/browse/WFCORE-3668
https://issues.jboss.org/browse/WFCORE-3669
> WFCORE-3668 WFCORE-3669 Jandex 2.0.5.Final  Jboss Invocation 1.5.1.Final

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- Guarantee that TerminalConnection thread is put in wait state synchronously. This is good in general (although not fully required, no side effect observed when putting the state asynchronously) except on Cygwin platform on which interacting with the terminal (eg: calling stty -a) while the connection is reading on the terminal gets you a blocking sub process outputstream (that has been reproduced outside any CLI/aesh context).
- Found a left over unrelated to the original issue, set back original attributes.
That is tested by MoreTestCase run on all platforms (Cygwin is used by QE).
> Fix for WFCORE-3647, CLI, Cygwin issue when paging output

- cli/pom.xml
- pom.xml
> WFCORE-3675 make it build and test on JDK 11

- controller/src/main/java/org/jboss/as/controller/registry/LegacyResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-3676
Blocks https://issues.jboss.org/browse/WFLY-9964
> WFCORE-3676 Register wildcard children last so that any override models are not treated as duplicate registrations

- patching/src/main/java/org/jboss/as/patching/management/PatchResourceDefinition.java
This also reduces visibility on a bunch of members of this class just as a cleanup.
https://issues.jboss.org/browse/WFCORE-3433
This is the first commit in #2956 but since that one may take some time to review while this is just a minor cleanup, I went ahead and filed a separate PR.
> [WFCORE-3433] Register patching child resources in registerChildren

- pom.xml
https://issues.jboss.org/browse/WFCORE-3692
https://issues.jboss.org/browse/WFCORE-3693
> [WFCORE-3692] / [WFCORE-3693] WildFly Elytron Component Upgrades

- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
- controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/test/java/org/jboss/as/controller/CapabilityReferenceRecorderTest.java
- controller/src/test/java/org/jboss/as/controller/SimpleAttributeDefinitionUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsTestCase.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCapabilityCompletionTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-3521
This is helpful for provisioning
> [WFCORE-3521]: Display dynamic capabilities with a pattern.

- component-matrix/pom.xml
- pom.xml
https://issues.jboss.org/browse/WFCORE-3721
> [WFCORE-3721] Upgrade build tools to 1.2.10.Final

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractUndeployCommand.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllDomainTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
- testsuite/shared/src/main/java/org/jboss/as/test/deployment/DeploymentInfoUtils.java
JIRA: https://issues.jboss.org/browse/WFCORE-3562
> [WFCORE-3562] Deployment disable-all doesn't correct function at domain

- host-controller/src/main/java/org/jboss/as/host/controller/HostPathManagerService.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
https://issues.jboss.org/browse/WFCORE-3730
> [WFCORE-3730] Register a path for jboss.domain.base.dir

- controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
- controller/src/main/java/org/jboss/as/controller/AbstractRemoveStepHandler.java
- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
- controller/src/main/java/org/jboss/as/controller/ResourceBuilder.java
- controller/src/main/java/org/jboss/as/controller/ResourceBuilderRoot.java
- controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/AliasResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingImmutableManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ImmutableManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java
- controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java
- controller/src/test/java/org/jboss/as/controller/CapabilityReferenceRecorderTest.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsTestCase.java
- elytron/src/main/java/org/wildfly/extension/elytron/BaseAddHandler.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Passing the resource registration address to build the requirement capability pattern.
JIRA: https://issues.jboss.org/browse/WFCORE-3683
> [WFCORE-3683]: Enable a resource to define requirements without binding them to an attribute.

- cli/src/main/java/org/jboss/as/cli/CommandLineMain.java
- cli/src/main/java/org/jboss/as/cli/handlers/DeploymentOverlayHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/HelpSupport.java
- controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/RemoteProxyControllerProtocolTestCase.java
- core-model-test/framework/src/main/java/org/jboss/as/core/model/test/MainKernelServicesImpl.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/access/AccessAuthorizationTransformationTestCase.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/WriteRelativeToAttributeHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/audit/AuditLogLoggerResourceDefinition.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/AssertConsoleBuilder.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelHandlerBase.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandlerWrapper.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerRemoveHandler.java
- io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java
- logging/src/test/java/org/jboss/as/logging/AbstractLoggingSubsystemTest.java
- patching/src/test/java/org/jboss/as/patching/runner/FileTaskTestCase.java
- patching/src/test/java/org/jboss/as/patching/runner/RemoveModifiedFileTaskTestCase.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorAdd.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/ControllerInitializer.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformerAttachmentGrabber.java
Removal of unused variables aka dead local store, using https://issues.jboss.org/browse/WFCORE-3731 as the tracker for these changes.
Focus on main classes, just few tests updated.
Fixing all tests will take some time.
> [WFCORE-3731] removal of unused variables aka dead local store

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/MoreTestCase.java
WFCORE: https://issues.jboss.org/browse/WFCORE-3701
> [WFCORE-3701] CLI multi-page output cannot be quit by capital Q

- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockOperation.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockOperationCandidatesProvider.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockOperationProperty.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/PropertiesCompletionTestCase.java
- cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProviderTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
WFCORE: https://issues.jboss.org/browse/WFCORE-3411
I have encountered another completion issue which I described in first comment of the WFCORE-3411. Following lines are related to the new mentioned issue https://github.com/wildfly/wildfly-core/compare/master...MMarus:WFCORE-3411-CLI_operation_completion_issues?expand=1#diff-b5ac7c9723bb46958c770f161f4759c8R432 . I can move this into separate WFCORE issue and PR if needed.
> [WFCORE-3411] CLI operation completion issues.

- core-feature-pack/src/main/resources/content/bin/common.ps1
Jira: https://issues.jboss.org/browse/WFCORE-3715
> [WFCORE-3715] JBOSS_HOME is unset in powershell scripts

- host-controller/src/main/java/org/jboss/as/host/controller/operations/StartServersHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyModeTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-3760
It fixes a corner case in `StartServersHandler`. We could be returning to a `normal` running mode with restart mode equals to `restart_servers` having servers already started.
> [WFCORE-3760] Avoid start duplicate servers after reloading a HC

- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
https://issues.jboss.org/browse/WFCORE-3481
> [WFCORE-3481] Stop using deprecated OFE constructor

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
- controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
https://issues.jboss.org/browse/WFCORE-3742
> Adding test case for ReadFeatureDescriptionHandler

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java
- host-controller/src/main/java/org/jboss/as/host/controller/descriptions/HostEnvironmentResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/StoppedServerResource.java
- patching/src/main/java/org/jboss/as/patching/management/PatchResourceDefinition.java
- server/src/main/java/org/jboss/as/server/ServerEnvironmentResourceDescription.java
- server/src/main/java/org/jboss/as/server/controller/resources/ModuleLoadingResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-3432
> [WFCORE-3432] Correct issues with ManagementResourceRegistrations not reporting as runtime-only

- core-feature-pack/src/main/resources/configuration/domain/template.xml
- core-feature-pack/src/main/resources/configuration/host/host-master.xml
- core-feature-pack/src/main/resources/configuration/host/host-slave.xml
- core-feature-pack/src/main/resources/configuration/host/host.xml
- elytron/src/main/resources/subsystem-templates/elytron.xml
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_7.java
https://issues.jboss.org/browse/WFCORE-3771
https://issues.jboss.org/browse/WFCORE-3772
https://issues.jboss.org/browse/WFCORE-3773
https://issues.jboss.org/browse/WFCORE-3775
Correct various issues with the legacy configs such that the #3231 change doesn't result in diffs between the galleon build and the legacy build that are due to flaws in legacy.
> WFCORE-3771 WFCORE-3772 WFCORE-3773 WFCORE-3775 Legacy config fixes

- component-matrix/pom.xml
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
https://issues.jboss.org/browse/WFCORE-3752
https://issues.jboss.org/browse/WFCORE-3763
https://github.com/wildfly/wildfly-proposals/pull/49
Brings in support for simplified multi-value services API.
> [WFCORE-3752] Upgrading to MSC 1.4.2.Final - brings support for multi-value services

- component-matrix/pom.xml
https://issues.jboss.org/browse/WFCORE-3794
> WFCORE-3794 Undertow 2.0.5.Final

- component-matrix/pom.xml
https://issues.jboss.org/browse/WFCORE-3608
> [WFCORE-3608] Add core pool size attribute to IO subsystem

- server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
https://issues.jboss.org/browse/WFCORE-3785
> [WFCORE-3785] Use the right package name

- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
Jira: https://issues.jboss.org/browse/WFCORE-3793
> [WFCORE-3793]: Allow for the provisioning of SecurityRealm without a 'running' elytron

- core-galleon-pack/pom.xml
https://issues.jboss.org/browse/WFCORE-3810
> [WFCORE-3810] Use the right name for the galleon pack zip

- controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- server/src/main/java/org/jboss/as/server/deployment/service/SecuredServiceRegistry.java
https://issues.jboss.org/browse/WFCORE-3809
> [WFCORE-3809] Refactoring - use Delegating MSC classes everywhere.

- controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
- domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionRemoveHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/ManagementUtil.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentStatusHandler.java
- server/src/main/java/org/jboss/as/server/services/net/BindingRemoveHandler.java
- server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-3812
> [WFCORE-3812] Eliminating usages of deprecated SC.getSubstate() method.

- cli/src/main/java/org/jboss/as/cli/CliConfig.java
- cli/src/main/java/org/jboss/as/cli/ColorConfig.java
- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/Namespace.java
- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICompletionHandler.java
- cli/src/main/resources/help/help.txt
- cli/src/main/resources/schema/wildfly-cli_3_3.xsd
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockCliConfig.java
- core-feature-pack/src/main/resources/content/bin/jboss-cli.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLITestUtil.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliControllerConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliEmbedServerTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-3577
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/33
EAP feature: https://issues.jboss.org/browse/EAP7-924
> [WFCORE-3577] Add support for coloured output to CLI

- pom.xml
https://issues.jboss.org/browse/WFCORE-3821
> [WFCORE-3821] Upgrade JBoss Modules to 1.8.4.Final

- core-galleon-pack/src/main/resources/packages/org.wildfly.openssl/pm/wildfly/tasks.xml
- pom.xml
https://issues.jboss.org/browse/WFCORE-3814
> [WFCORE-3814] Upgrade to Galleon and plugins 1.0.0.CR1

- io/tests/src/test/java/org/wildfly/extension/io/IOSubsystemTestCase.java
https://issues.jboss.org/browse/WFCORE-3827
A question in case anyone happens to know the answer:
The `workerServiceController.awaitValue()` method is deprecated, but the docs don't say what the replacement is. Is there a similar simple way to wait for the service start or do I have to implement the wait myself?
I decided to ignore the deprecation this time, as the method seems to be widely used still. If it's a problem let me know.
> [WFCORE-3827] Test for thread pool attribute propagation for IO subsystem

- testsuite/embedded/pom.xml
- testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/LoggingTestCase.java
- testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/Log4j2HostControllerTestCase.java
- testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/LogbackHostControllerTestCase.java
- testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/Log4j2StandaloneTestCase.java
- testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/LogbackStandaloneTestCase.java
- testsuite/embedded/src/test/resources/log4j2-test.properties
- testsuite/embedded/src/test/resources/logback-test.xml
- testsuite/shared/pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-3205
Additional tests for https://github.com/wildfly/wildfly-core/pull/3202
> [WFCORE-3205] Added log4j2 and logback tests to embedded TS

- pom.xml
https://issues.jboss.org/browse/WFCORE-3833
> [WFCORE-3833] Upgrade WildFly Common to 1.4.0.Final

- cli/pom.xml
https://issues.jboss.org/browse/WFCORE-3835
> [WFCORE-3835] Make CLI JAR be Multi-Release

- pom.xml
https://issues.jboss.org/browse/WFCORE-3709
> [WFCORE-3709] Upgrade JBoss Remoting to 5.0.7.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3717
> [WFCORE-3717] Upgrade XNIO to 3.6.3.Final

- core-feature-pack/src/main/resources/configuration/standalone/template.xml
- core-galleon-pack/src/main/resources/feature_groups/base-security-realms.xml
- core-galleon-pack/src/main/resources/feature_groups/host-security-realms.xml
https://issues.jboss.org/browse/WFCORE-3823
@darranl Please approve.
> [WFCORE-3823] Add missing skip-group-loading

- pom.xml
https://issues.jboss.org/browse/WFCORE-3834
>  [WFCORE-3834] Upgrade WildFly Discovery to 1.1.1.Final

- core-feature-pack/pom.xml
- core-galleon-pack/pom.xml
- pom.xml
https://issues.jboss.org/browse/WFCORE-3842
Also cleans up a whitespace bug in the root pom.
> [WFCORE-3842] Simplify generation of core-feature-pack-licenses.xml

- pom.xml
https://issues.jboss.org/browse/WFCORE-3848
> [WFCORE-3848] Upgrade JBoss Modules to 1.8.5.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3855
> [WFCORE-3855] Upgrade to Galleon 1.0.0.CR3 and plugins 1.0.0.CR5

- dist-legacy/assembly-src.xml
- dist/assembly-src.xml
> Ensure the .idea/ directory is not included in the source archive.

- embedded/src/main/java/org/wildfly/core/embedded/Configuration.java
https://issues.jboss.org/browse/WFCORE-3862
> [WFCORE-3862] Ensure the modulePath set by the user is used if set.

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
https://issues.jboss.org/browse/WFCORE-3859
> BLOCKER - [WFCORE-3859] Add transformer to transform from version  2.0.0 to 1.2.0 of the Elytron subsystem model.

- cli/src/main/java/org/jboss/as/cli/Util.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-3853
> [WFCORE-3853] CLI prompt contains extra space when colors are enabled

- pom.xml
https://issues.jboss.org/browse/WFCORE-3886
> [WFCORE-3886] Upgrade to WildFly Galleon plugins 1.0.0.CR12

- pom.xml
https://issues.jboss.org/browse/WFCORE-3888
> WFCORE-3888 Undertow 2.0.8.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3894
> WFCORE-3894 Undertow 2.0.9.Final

- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/UninterruptibleCountDownLatch.java
- controller/src/main/java/org/jboss/as/controller/operations/common/ProcessReloadHandler.java
- server/src/main/java/org/jboss/as/server/BootstrapImpl.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
https://issues.jboss.org/browse/WFCORE-3817
> [WFCORE-3817] Eliminating usages of deprecated ServiceListeners.

- cli/pom.xml
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/util/FingerprintGenerator.java
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/security/RealmIdentityManager.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationCallbackHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesCallbackHandler.java
- elytron/src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLContextResource.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLSessionDefinition.java
https://issues.jboss.org/browse/WFCORE-3864
> [WFCORE-3864] Switch to using WildFly Common byte and code point iterators

- logging/src/main/resources/org/jboss/as/logging/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-3896
> [WFCORE-3896] Fix custom-formatter descriptions.

- pom.xml
https://issues.jboss.org/browse/WFCORE-3898
> [WFCORE-3898] Upgrade PicketBox to 5.1.0.Final

- pom.xml
This profile adds the Nexus staging repository group to test the
integration of components that have been staged (but not released yet).
JIRA: https://issues.jboss.org/browse/WFCORE-3922
> [WFCORE-3922] add staged-releases profile

- README.md
JIRA: https://issues.jboss.org/browse/WFCORE-3924
> [WFCORE-3924] Add Apache License v2 to the README

- pom.xml
https://issues.jboss.org/browse/WFCORE-3678
> [WFCORE-3678] Upgrade to picketbox 5.0.3

- pom.xml
https://issues.jboss.org/browse/WFCORE-3928
> [WFCORE-3928] Put exclusion groupId and artifactId in the correct order

- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
https://issues.jboss.org/browse/WFCORE-3897
Try to resolve required server group existence for configured server.
> [WFCORE-3897] set explicitly domain model to available before domain ops boot up.

- controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
Prior MSC 1.2.8 stability monitors were reporting problems if
some transitive dependency wasn't available. This has changed
since MSC 1.2.8 and above. There is no notion of transitive
dependencies in JBoss MSC anymore. If stability monitor detects
a problem it is always immediate dependency of monitored controller.
> [WFCORE-3806] Eliminating dead code.

- core-feature-pack/src/main/resources/content/bin/elytron-tool.sh
jira : https://issues.jboss.org/browse/WFCORE-3941
> [WFCORE-3941] elytron-tool.sh script detects JBOSS_HOME incorrectly

- core-galleon-pack/src/main/resources/packages/misc.common/pm/wildfly/tasks.xml
https://issues.jboss.org/browse/WFCORE-3930
> [WFCORE-3930] Possible file permission issues in .properties files

- remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorChildResource.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorUtils.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/logging/RemotingLogger.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
- remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-cli.xml
- remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-transformers.xml
- remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-with-expressions-and-good-legacy-protocol.xml
- remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-with-expressions.xml
- remoting/tests/src/test/resources/org/jboss/as/remoting/remoting.xml
Jira: https://issues.jboss.org/browse/WFCORE-3908
> [WFCORE-3908] When adding property to remoting check first if it is valid

- deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
Jira: https://issues.jboss.org/browse/WFCORE-3938
> [WFCORE-3938]: Checking target paths when unzipping deployements.

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/NonExistentServerGroupTestCase.java
- testsuite/domain/src/test/resources/host-configs/host-nonexistent-group.xml
Associated JIRA's:
https://issues.jboss.org/browse/WFCORE-3897
This adds test coverage for WFRCORE-3897 - Host starts with server assigned to non-existent server group.
> [WFCORE-3897] Add test coverage

- pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-3957
> [WFCORE-3957] Upgrade JBoss Remoting to 5.0.8.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-3956
> WFCORE-3956 Undertow 2.0.10.Final

- pom.xml
This changes within this PR are just a refactoring to pull some integration code from the Undertow subsystem into the Elytron Web project for the servlet container integration.
https://issues.jboss.org/browse/WFCORE-3591
https://issues.jboss.org/browse/WFCORE-3961
This was discussed with QE this week where we agreed it would be better to get the refactoring merged first before any dependent RFEs.
> [WFCORE-3961] / [WFCORE-3591] Elytron Web Component Upgrade and Additional Module

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_4_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-4.0.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/role-mappers-test.xml
https://issues.jboss.org/browse/WFCORE-3666
requires ELY-1591
https://issues.jboss.org/browse/ELY-1591
> [WFCORE-3666] Provide Elytron alternative to RoleMappingLoginModule

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
WFCORE: https://issues.jboss.org/browse/WFCORE-3711
> [WFCORE-3711] Ctrl-C in CLI multi page output mode kills the whole CLI

- pom.xml
mostly fixes to make maven plugins work on JDK11
> update jboss-parent to 28

- cli/src/main/java/org/jboss/as/cli/CommandContext.java
- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/handlers/EchoDMRHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/resources/help/echo-dmr.txt
- cli/src/test/java/org/jboss/as/cli/EchoDMRTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Add --compact option to echo-dmr command.
JIRA
https://issues.jboss.org/browse/WFCORE-3933
EAP7-1023
Analysis  doc: https://github.com/wildfly/wildfly-proposals/pull/86
No community doc, PR contains documentation via help.
All new tests are contained in PR.
> Fix for WFCORE-3933, compact ouput for echo-dmr

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.jboss.org/browse/WFLY-5550
> WFLY-5550 Add deployment phase priorities for distribute-web subsystem DUPs

- pom.xml
https://issues.jboss.org/browse/WFCORE-4003 incorporates https://issues.jboss.org/browse/WFCORE-3885
> [WFCORE-4003] Upgrade xnio to 3.6.4

- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
https://issues.jboss.org/browse/WFCORE-3993
> [WFCORE-3993] Fix ECPublicKey import

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
This patch tries to address some errors found in CI related to this test. The Changes added were:
- Allow the test pass if we receive UnsuccessfulOperationException reading the SUSPENDED state, indeed looks like that was the original intention since the try/cacth is there even for a RuntimeException. We could get a UnsuccessfulOperationException if the server is stopped in between of the read attribute operation.
- It was using TimeoutUtil.adjust(suspendTimeout) twice in the test
- Added a try / finally to shut down the executor service
Jira issue: https://issues.jboss.org/browse/WFCORE-3768
> [WFCORE-3768] Intermittent failure in SuspendOnSoftKillTestCase

- cli/src/main/java/org/jboss/as/cli/impl/DeploymentItemCompleter.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ExplodedDeploymentTestCase.java
Fixed failing case, added unit test.
> Fix for WFCORE-3942, CLI browse deployment completion with .. crashes

- pom.xml
https://issues.jboss.org/browse/WFCORE-4006
> WFCORE-4006 Undertow 2.0.12.Final

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser3_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser4_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
https://issues.jboss.org/browse/WFCORE-4005
> [WFCORE-4005] Refactor parsing for new elements added to version 4 of the Elytron schema

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4009
> [WFCORE-4009] Upgrade VFS to 3.2.13

- core-galleon-pack/src/main/resources/feature_groups/access-control.xml
- core-galleon-pack/src/main/resources/feature_groups/domain-profile.xml
- core-galleon-pack/src/main/resources/feature_groups/elytron-app.xml
- core-galleon-pack/src/main/resources/feature_groups/elytron-management.xml
- core-galleon-pack/src/main/resources/feature_groups/host-profile.xml
https://issues.jboss.org/browse/WFCORE-4010
> [WFCORE-4010] Adjust provisioning configs to reduce config diff noise

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/operations/PathAddressFilter.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadConfigAsFeaturesOperationHandler.java
- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
- controller/src/test/java/org/jboss/as/controller/test/ReadConfigAsFeaturesTestCase.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/GenericModelDescribeOperationHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainOperationsHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-3991
> [WFCORE-3991] read-config-as-features management operation

- elytron/src/main/java/org/wildfly/extension/elytron/CertificateAuthorityAccountDefinition.java
https://issues.jboss.org/browse/WFCORE-4020
> [WFCORE-4020] Fix the staging URL for the Let's Encrypt certificate-authority

- core-feature-pack/src/main/resources/content/bin/standalone.conf
- core-feature-pack/src/main/resources/content/bin/standalone.conf.bat
- core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
* https://issues.jboss.org/browse/WFCORE-4019
> [WFCORE-4019] Add a line to standalone.conf to enable JDK 11 support for ByteBuddy

- pom.xml
https://issues.jboss.org/browse/WFCORE-4027
> [WFCORE-4027] Upgrade to xnio 3.6.5.Final

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ReadConfigAsFeaturesDomainTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ReadConfigAsFeaturesTestBase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
https://issues.jboss.org/browse/WFCORE-3991
Replaces reverted #3437
> [WFCORE-3991] Fixed test coverage for read-config-as-features

- zanata.xml
Use the correct Zanata version for pushing and pulling localization properties files.
> [i18n] Use the correct Zanata repository version.

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ReadConfigAsFeaturesDomainTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ReadConfigAsFeaturesTestBase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
https://issues.jboss.org/browse/WFCORE-4031
> [WFCORE-4031] Test coverage for read-config-as-features(nested=false)

- pom.xml
https://issues.jboss.org/browse/WFCORE-4037
> WFCORE-4037 Undertow 2.0.13.Final

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/Common.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ErrorContextHandler.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/OperatingSystemDetector.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/logging/HttpServerLogger.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/security/RedirectReadinessHandler.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/security/ServerErrorReadinessHandler.java
https://issues.jboss.org/browse/WFCORE-4045 which is needed to resolve https://issues.jboss.org/browse/WFLY-10861.
If the first three 'housekeeping' commits are too many, they can be squashed
> Wfcore 4045 health error codes

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
https://issues.jboss.org/browse/WFCORE-4051
@mchoma could you please give this one a quick review and if possible test?
> [WFCORE-4051] Also unwrap the TrustManager if in FIPS mode.

- pom.xml
https://issues.jboss.org/browse/WFCORE-4023
> [WFCORE-4023] Upgrade to xerces 2.12.0.SP02

- pom.xml
> Upgrades needed by downstream

- pom.xml
https://issues.jboss.org/browse/WFCORE-4068
> [WFCORE-4068] Upgrade jboss-modules to 1.8.6.Final

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteGitRepositoryTestCase.java
Test is failing if the snapshot date ands the snapshot name are equal.
Jira: https://issues.jboss.org/browse/WFCORE-4025
> [WFCORE-4025]: Intermittent errors on GitRepositoryTestCase.historyAndManagementOperationsTest

- pom.xml
https://issues.jboss.org/browse/WFCORE-4073
> [WFCORE-4073] Upgrade JBoss Marshalling to 2.0.6.Final

- core-feature-pack/src/main/resources/content/bin/common.sh
https://issues.jboss.org/browse/WFCORE-4077
> [WFCORE-4077] Remove the function keyword from the common.sh script.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/InterdependentDeploymentTestCase.java
Proper cleanup of InterdependentDeploymentTestCase
If this test fails, test's deployments needs to be un-deployed.
Basically, this PR wraps deploy code to `try` and undeploy code to `finally`
Jira: https://issues.jboss.org/browse/WFCORE-4075
> [WFCORE-4075] Proper cleanup of InterdependentDeploymentTestCase

- pom.xml
This pull request brings in critical MSC stability fix.
It addresses the following issues:
* https://issues.jboss.org/browse/WFCORE-4074
* https://issues.jboss.org/browse/WFCORE-4107
> [WFCORE-4107][WFCORE-4074] Upgrading MSC to 1.4.5.Final

- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
https://issues.jboss.org/browse/WFCORE-4102
> [WFCORE-4102] Fix configuration file interference between tests

- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
https://issues.jboss.org/browse/WFCORE-4092
> [WFCORE-4092] The class ModifiableKeyStoreDecorator should not be public.

- controller/src/main/java/org/jboss/as/controller/capability/AbstractCapability.java
- controller/src/main/java/org/jboss/as/controller/capability/DynamicNameMappers.java
- controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
Utility class to avoid duplication of lambdas.
Jira: https://issues.jboss.org/browse/WFCORE-4088
> [WFCORE-4088]: Propose several DynamicNameMappers to be reused.

- controller/src/main/java/org/jboss/as/controller/SimpleMapAttributeDefinition.java
https://issues.jboss.org/browse/WFCORE-4098
> [WFCORE-4098] Update SimpleMapAttributeDefinition to record capabilities based on the values.

- cli/src/test/java/org/jboss/as/cli/OperatorsTestCase.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/CommandCompletionTestCase.java
- pom.xml
> Fix for WFCORE-4112, upgrade CLI to aesh 1.8

- core-feature-pack/src/main/resources/content/bin/common.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.bat
- core-feature-pack/src/main/resources/content/bin/standalone.sh
Jira: https://issues.jboss.org/browse/WFCORE-3996
This is follow-up to https://github.com/wildfly/wildfly-core/pull/3496
> [WFCORE-3996] Update GC logging to work on Java 9+ - part II.

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
- Remove support for paging and rely on aesh PagingSupport.
> Fix for WFCORE-4096, CLI replace paging support with aesh one

- logging/src/test/java/org/jboss/as/logging/FormatterOperationsTestCase.java
- logging/src/test/java/org/jboss/as/logging/HandlerLegacyOperationsTestCase.java
- logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
- logging/src/test/java/org/jboss/as/logging/LogFilterTestCase.java
- logging/src/test/java/org/jboss/as/logging/LoggerLegacyOperationsTestCase.java
- logging/src/test/java/org/jboss/as/logging/LoggerOperationsTestCase.java
- logging/src/test/java/org/jboss/as/logging/LoggingOperationsSubsystemTestCase.java
- logging/src/test/java/org/jboss/as/logging/LoggingSubsystemRollbackTestCase.java
- logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
- logging/src/test/java/org/jboss/as/logging/RootSubsystemOperationsTestCase.java
https://issues.jboss.org/browse/WFCORE-4158
> [WFCORE-4158] Ensure the KernelServices are shutdown for logging tests.

- pom.xml
https://issues.jboss.org/browse/WFCORE-4155
> [WFCORE-4155] Upgrade to Galleon and WildFly Galleon Plugins 2.0.1.Final

- core-feature-pack/src/main/resources/content/bin/standalone.bat
- core-feature-pack/src/main/resources/content/bin/standalone.sh
https://issues.jboss.org/browse/WFCORE-4147
This replaces #3542
> [WFCORE-4147] Delete the gc.log after the -version check to see if the GC settings are valid.

- pom.xml
Upstream Issue: https://issues.jboss.org/browse/WFCORE-3473
Issue: https://issues.jboss.org/browse/JBEAP-13801
> Upgrade to http-core 4.4.5 and http-client 4.5.4

- elytron/src/test/java/org/wildfly/extension/elytron/AcmeMockServerBuilder.java
- pom.xml
https://issues.jboss.org/browse/WFCORE-4174
> [WFCORE-4174] Update jackson-databind to 2.9.5 and mockserver-netty to 5.4.1

- server/src/main/java/org/jboss/as/server/deployment/reflect/ClassReflectionIndex.java
https://issues.jboss.org/browse/WFCORE-4116
> [WFCORE-4116] Do not set the accessible value on Object.class types

- cli/src/main/resources/help/reload.txt
- cli/src/main/resources/help/shutdown.txt
https://issues.jboss.org/browse/WFCORE-4182
> [WFCORE-4182] Minor typos in shutdown and reload help descriptions

- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
https://issues.jboss.org/browse/WFCORE-4180
> [WFCORE-4180] Eliminating ServiceBuilder's addInjection() method usages

- controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentCompleteServiceProcessor.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
https://issues.jboss.org/browse/WFCORE-4194
> [WFCORE-4194] Eliminating ServiceBuilder.addDependencies() usages

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
https://issues.jboss.org/browse/WFCORE-4196
I've left this PR with two separate commits as I think it makes sense in this case. Although, I can squash them together if required.
> [WFCORE-4196] SNICombinedWithALPNTestCase fails with IBM JDK

- core-feature-pack/src/main/resources/content/bin/standalone.sh
Jira: https://issues.jboss.org/browse/WFCORE-4148
Following this PR: https://github.com/wildfly/wildfly-core/pull/3496
> [WFCORE-4148] In GC logging for Java8- put back quotes to .sh script

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
JIRA: https://issues.jboss.org/browse/WFCORE-4204
> [WFCORE-4204] Add Phase priorities for MicroProfile extensions

- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
https://issues.jboss.org/browse/WFCORE-4203
> [WFCORE-4203] Eliminating ServiceBuilder.addDependency(ServiceName,Injector) usages

- controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
https://issues.jboss.org/browse/WFCORE-4200
> [WFCORE-4200] Deprecating legacy CapabilityServiceBuilder methods

- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
- controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryService.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementChannelRegistryService.java
- server/src/main/java/org/jboss/as/server/ServerStartTask.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentCompleteServiceProcessor.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
- server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
- server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
- server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
- server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractKernelServicesImpl.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/dependent/RootResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-4201
> [WFCORE-4201] Eliminating ServiceBuilder.addDependency(ServiceName) usages

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ReloadSASLFactoryTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
- Authentication tests need to erase sasl and http factories then restore them.
- Some other tests were relying on ManagementRealm that is not present in this context.
> Fix some CLI tests failing with elytron profile

- remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointService.java
https://issues.jboss.org/browse/WFLY-10997
> [WFLY-10997] Fixing remoting endpoint inconsistency.

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- Do not write attributes when connection is already closed.
- Testing done with debugger to re-produce race.
> Fix for WFCORE-4250, CLI, terminal can be corrupted during Ctrl-C

- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
- server/src/main/java/org/jboss/as/server/DomainServerCommunicationServices.java
- server/src/main/java/org/jboss/as/server/Services.java
- server/src/main/java/org/jboss/as/server/deployment/ContentCleanerService.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java
- server/src/main/java/org/jboss/as/server/deployment/ManagedExplodedContentServitor.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
- server/src/test/java/org/jboss/as/server/AddServerExecutorDependencyTestCase.java
https://issues.jboss.org/browse/WFLY-11488
> [WFLY-11488] Deprecating o.j.a.s.Services.addServerExecutorDependency() method.

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
https://issues.jboss.org/browse/WFCORE-4239
> [WFCORE-4239] WARN if system-property is already set and is being overridden

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-4253
> [WFCORE-4253] - fix file permission in SNICombinedWithALPNTestCase

- pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-4268
> [WFCORE-4268] Upgrade FasterXML 2.9.8

- threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolAdd.java
- threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolMetricsHandler.java
- threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolResourceDefinition.java
- threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolWriteAttributeHandler.java
- threads/src/main/java/org/jboss/as/threads/PoolAttributeDefinitions.java
- threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolAdd.java
- threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolMetricsHandler.java
- threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolResourceDefinition.java
- threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolWriteAttributeHandler.java
- threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolAdd.java
- threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolMetricsHandler.java
- threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolRemove.java
- threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolResourceDefinition.java
- threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolWriteAttributeHandler.java
- threads/src/main/java/org/jboss/as/threads/ThreadFactoryAdd.java
- threads/src/main/java/org/jboss/as/threads/ThreadFactoryResourceDefinition.java
- threads/src/main/java/org/jboss/as/threads/ThreadFactoryService.java
- threads/src/main/java/org/jboss/as/threads/ThreadPoolManagementUtils.java
- threads/src/main/java/org/jboss/as/threads/ThreadPoolMetricsHandler.java
- threads/src/main/java/org/jboss/as/threads/ThreadsServices.java
- threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolAdd.java
- threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolMetricsHandler.java
- threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolRemove.java
- threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolResourceDefinition.java
- threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolService.java
- threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolWriteAttributeHandler.java
* Adding capabilities and registering services with the new names.
JIRA: https://issues.jboss.org/browse/WFCORE-4207
> [WFCORE-4207]: Add capabilities in the Thread subsystem resource definitions.

- pom.xml
Undertow upgrade to 2.0.17.Final
https://issues.jboss.org/browse/WFCORE-4280
> [WFCORE-4280] Undertow upgrade to 2.0.17.Final

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
The test fails sometimes because we could get the suspended state as "suspending" just after unclocking the web application. This patch gives the oportunity to wait a bit longer in that case until getting SUSPENDED or the server already down.
Jira issue: https://issues.jboss.org/browse/WFCORE-4275
This PR supersedes https://github.com/wildfly/wildfly-core/pull/3642
> [WFCORE-4275] SuspendOnSoftKillTestCase fails sometimes

- pom.xml
Issue - https://issues.jboss.org/browse/WFCORE-4285
> WFCORE-4285 Upgrade jboss modules to 1.9.0.Final.

- pom.xml
https://issues.jboss.org/browse/WFCORE-4310
This PR just contains one bug fix: -
https://issues.jboss.org/browse/REMJMX-158
> [WFCORE-4310] Upgrade Remoting JMX to 3.0.1.Final

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/schema/wildfly-elytron_6_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
https://issues.jboss.org/browse/WFCORE-4058
https://issues.jboss.org/browse/WFWIP-153
requires ELY-1650
https://issues.jboss.org/browse/ELY-1650
> [WFCORE-4058] Automatic detection of file based KeyStore types

- cli/src/main/java/org/jboss/as/cli/handlers/BaseOperationCommand.java
- cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestAddress.java
- cli/src/test/java/org/jboss/as/cli/handlers/ShutdownHandlerTestCase.java
- cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestAddressTestCase.java
> CLI, fix for WFCORE-1478 and WFCORE-1698 

- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
- pom.xml
https://issues.jboss.org/browse/WFCORE-4089
> [WFCORE-4089] Introduce the real 7.2.0 legacy test version

- core-galleon-pack/src/main/resources/packages/bin/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.domain.config.history.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.domain.data.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.domain.log.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.domain.servers.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.provisioned.state.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.standalone.config.history.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.standalone.data.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.standalone.log.dir/package.xml
- core-galleon-pack/src/main/resources/packages/cleanup.standalone.tmp.vfs/package.xml
- core-galleon-pack/src/main/resources/packages/docs.licenses.merge/package.xml
- core-galleon-pack/src/main/resources/packages/misc.common/package.xml
- core-galleon-pack/src/main/resources/packages/misc.domain/package.xml
- core-galleon-pack/src/main/resources/packages/misc.standalone/package.xml
- core-galleon-pack/src/main/resources/packages/product.conf/package.xml
https://issues.jboss.org/browse/WFCORE-4321
> [WFCORE-4321] Upgrade XML namespace for Galleon packages from 1.0 to 2.0

- remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractStreamServerService.java
https://issues.jboss.org/browse/WFCORE-4326
> [WFCORE-4326] Use any configured SASL mechanisms when accessing the SaslAuthenticationFactory.

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
- pom.xml
- server/pom.xml
- server/src/main/java/org/jboss/as/server/deployment/ModuleClassFactory.java
https://issues.jboss.org/browse/WFCORE-4340
> [WFCORE-4340] Upgrading JBoss Invocation plus providing utility ModuleClassFactory

- model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformationUtils.java
https://issues.jboss.org/browse/WFCORE-4330
> [WFCORE-4330] Handle model overrides better in the transformer testing

- testsuite/layers/pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
- Layers based servers provisioned as thin-server.
- Convey maven local repo to sub-process.
> Fix for WFCORE-4339, The layers testsuite should use thin servers

- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
- cli/src/main/java/org/jboss/as/cli/parsing/operation/HeaderValueState.java
- cli/src/test/java/org/jboss/as/cli/EchoDMRTestCase.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/CommandHeadersParsingTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LsTestCase.java
- Fixed HeaderState.
- Fixed headers completers to parse full line.
- Added unit tests.
> Fix for WFCORE-4316, CLI, Spaces are not supported in a header value

- pom.xml
https://issues.jboss.org/browse/WFCORE-4366
> Explicitly excluse commons-lang3

- pom.xml
https://issues.jboss.org/browse/WFCORE-4382
> [WFCORE-4382] Upgrade to Byteman 4.0.6

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/cacheddc/CachedDcDomainTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestSupport.java
https://issues.jboss.org/browse/WFCORE-4384
This is quite minor. There's some logic in this test for creating a client and checking status that I hoped to eliminate in favor of standard stuff in DomainLifecycleUtil, but actually that stuff is still needed for some of the unusual cases this test covers. I did switch to the standard stuff where it was usable though.
No longer using DomainTestSupport.stop() when the object will continue to be used is a needed change though. As part of https://issues.jboss.org/browse/WFCORE-4385 I'll make the DTS unusable after stop() is called.
> [WFCORE-4384] Don't call DomainTestSupport.stop() just to stop hosts

- pom.xml
https://issues.jboss.org/browse/WFCORE-4393
> [WFCORE-4393] Upgrade XNIO to 3.7.1.Final

- server/src/main/java/org/jboss/as/server/deployment/DelegatingSupplier.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java
https://issues.jboss.org/browse/WFCORE-4357
> [WFCORE-4357] Introducing DeploymentPhaseContext.requires() method

- server/src/main/java/org/jboss/as/server/deployment/Attachments.java
https://issues.jboss.org/browse/WFCORE-4390
> [WFCORE-4390] Introducing new o.j.a.s.d.Attachments.COMPONENT_JNDI_DEPS key

- logging/src/main/java/org/jboss/as/logging/KnownModelVersion.java
- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_7_0.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemWriter.java
- logging/src/main/java/org/jboss/as/logging/Namespace.java
- logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
- logging/src/main/java/org/jboss/as/logging/handlers/SyslogHandlerResourceDefinition.java
- logging/src/main/resources/org/jboss/as/logging/LocalDescriptions.properties
- logging/src/main/resources/schema/jboss-as-logging_7_0.xsd
- logging/src/main/resources/subsystem-templates/logging.xml
- logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
- logging/src/test/resources/default-subsystem.xml
- logging/src/test/resources/empty-subsystem.xml
- logging/src/test/resources/expressions.xml
- logging/src/test/resources/expressions_6_0.xml
- logging/src/test/resources/logging.xml
- logging/src/test/resources/logging_6_0.xml
- logging/src/test/resources/operations.xml
- logging/src/test/resources/rollback-logging.xml
- logging/src/test/resources/simple-subsystem.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/syslog/SyslogHandlerTestCase.java
JIRA for schema bump: https://issues.jboss.org/browse/WFCORE-4337
JIRA for `named-formatter` addition: https://issues.jboss.org/browse/WFCORE-4332
> [WFCORE-4332] Add the named-formatter attribute to the syslog-handler.

- pom.xml
https://issues.jboss.org/browse/WFCORE-4396
> [WFCORE-4396] Use HTTPS for repository and pluginRepository URLs

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
https://issues.jboss.org/browse/WFCORE-3969
> [WFCORE-3969] ALIAS_FILTER in Elytron trustmanager ignored when crl used

- controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionResource.java
- controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
- controller/src/main/java/org/jboss/as/controller/registry/PlaceholderResource.java
- controller/src/main/java/org/jboss/as/controller/transform/description/TransformationRule.java
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
- network/src/main/java/org/jboss/as/network/SocketBinding.java
- pom.xml
- subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/OtherServicesSubsystemTestCase.java
An aggregation of multiple approved PRs allowing the use of CI automation without requiring manual CI runs.
#3719
https://issues.jboss.org/browse/WFCORE-4392
#3722
https://issues.jboss.org/browse/WFCORE-4399
#3723
https://issues.jboss.org/browse/WFCORE-4401
#3726
https://issues.jboss.org/browse/WFCORE-3296
#3727
https://issues.jboss.org/browse/WFCORE-4403
> An aggregation of PRs 2019-04-08

- pom.xml
Upstream Jira: https://issues.jboss.org/browse/WFCORE-4403
EAP Jira: https://issues.jboss.org/browse/JBEAP-16361
> [WFCORE-4403] Upgrade Undertow to 2.0.20.Final

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/auditlog/AuditLogToTLSSyslogTestCase.java
https://issues.jboss.org/browse/WFCORE-4409
> [WFCORE-4409] Avoid hangs from https://bugs.openjdk.java.net/browse/JDK-8219658

- controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
https://issues.jboss.org/browse/WFCORE-4420
> [WFCORE-4420] Fix check for XMLConstants.NULL_NS_URI

- controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
The ReadFeatureDescriptionHandler is assuming that requestProperties variable is not empty to process the fixed requirements of the registrations capabilities
Jira issue: https://issues.jboss.org/browse/WFCORE-4416
> [WFCORE-4416] Some capabilities requirements are not recorded in features generated by Galleon

- pom.xml
https://issues.jboss.org/browse/WFCORE-4423
https://issues.jboss.org/browse/WFCORE-4424
https://issues.jboss.org/browse/WFCORE-4425
https://issues.jboss.org/browse/WFCORE-4426
> Logging and wildfly-common component upgrades

- model-test/src/main/java/org/jboss/as/model/test/ChildFirstClassLoaderBuilder.java
- model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
- model-test/src/test/java/org/jboss/as/model/test/MavenSettingsTest.java
- model-test/src/test/resources/org/jboss/as/model/test/settings-empty-local-repo.xml
https://issues.jboss.org/browse/WFCORE-4429
> [WFCORE-4429] Default to https when accessing repositories.

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/extension/ParallelExtensionAddHandler.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
- controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- server/src/main/java/org/jboss/as/server/ServerService.java
Reverts wildfly/wildfly-core#2935 as it is causing issues with some Jenkins jobs
> Revert "[WFCORE-3185] Run parallel boot tasks in coarser grained chunks"

- cli/src/main/java/org/jboss/as/cli/embedded/ThreadLocalContextSelector.java
https://issues.jboss.org/browse/WFCORE-4436
> [WFCORE-4436] Ensure the TCCL is not null before doing the equals check.

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4421
> [WFCORE-4421] Upgrade remoting to 5.0.9.Final

- domain-management/src/main/java/org/jboss/as/domain/management/SecurityRealm.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/mgmt/HttpShutdownService.java
- server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
https://issues.jboss.org/browse/WFCORE-4442
> [WFCORE-4442] Migrating UndertowHttpManagementService & HttpShutdownService to new MSC API

- pom.xml
https://issues.jboss.org/browse/WFCORE-4433
> [WFCORE-4433] Update wildfly-discovery-client to 1.2.0.Final

- controller/src/main/java/org/jboss/as/controller/services/path/AbsolutePathService.java
- controller/src/main/java/org/jboss/as/controller/services/path/AbstractPathService.java
- controller/src/main/java/org/jboss/as/controller/services/path/RelativePathService.java
https://issues.jboss.org/browse/WFCORE-4446
> [WFCORE-4446] Migrating AbsolutePathService & RelativePathService to new MSC API

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- pom.xml
- testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/KDCServerAnnotationProcessor.java
https://issues.jboss.org/browse/WFCORE-4451
https://issues.jboss.org/browse/WFCORE-4452
https://issues.jboss.org/browse/WFCORE-4453
> [WFCORE-4451] / [WFCORE-4452] / [WFCORE-4453] JBoss Parent and Checkstyle Config Updates.

- cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java
Issue: https://issues.jboss.org/browse/WFCORE-4460
> [WFCORE-4460] jboss-cli.sh doesn't return json when the output command is 'failed'

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.jboss.org/browse/WFLY-6143
> [WFLY-6143] Server interceptors: add phases

- pom.xml
https://issues.jboss.org/browse/WFCORE-4466
> [WFCORE-4466] Upgrade to Galleon and Plugins 4.0.0.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4492
Full counter-part: https://github.com/wildfly/wildfly/pull/12314
> [WFCORE-4492] Upgrade to component matrix 1.0.3.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4472
> [WFCORE-4472] Upgrade Undertow to 2.0.21.Final

- jmx/src/main/java/org/jboss/as/jmx/MBeanServerService.java
https://issues.jboss.org/browse/WFCORE-4500
> [WFCORE-4500] Withdraw the security identity supplier when MBeanServerService stops

- pom.xml
https://issues.jboss.org/browse/WFCORE-4507
> [WFCORE-4507] Upgrade the Jackson version to 2.9.9

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4526
This PR needs https://github.com/wildfly/wildfly/pull/12364 to pass WildFly tests
> [WFCORE-4526] Upgrade Undertow version to 2.0.22.Final

- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
https://issues.jboss.org/browse/WFCORE-4531
> [WFCORE-4531] Eliminating WildFly naming workaround

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/auditlog/AuditLogToTLSSyslogTestCase.java
https://issues.jboss.org/browse/WFCORE-4352
> [WFCORE-4352] Enabling disabled tests since they started to pass on latest JDK13 ea b 25

- controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
- io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java
- io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolService.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerService.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointService.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/BindingGroupAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingService.java
- server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingService.java
- server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingService.java
- server/src/main/java/org/jboss/as/server/services/net/SocketBindingManagerService.java
- server/src/main/java/org/jboss/as/server/services/net/SocketBindingService.java
This PR migrates all capability providing services to non deprecated MSC API.
https://issues.jboss.org/browse/WFCORE-4477
https://issues.jboss.org/browse/WFCORE-4478
> Capabilities Deprecated MSC API Cleanup

- .gitattributes
Jira
https://issues.jboss.org/browse/WFCORE-4502
WF PR
https://github.com/wildfly/wildfly/pull/12336
> WFCORE-4502 Unify line-endings of bat scripts (regression against WF15)

- core-feature-pack/src/license/core-feature-pack-licenses.xml
- core-galleon-pack/pom.xml
Also WFCORE-4545 -- add missing provided settings for WFCORE-4406
https://issues.jboss.org/browse/WFCORE-4544
https://issues.jboss.org/browse/WFCORE-4545
> [WFCORE-4544] Generate license info for deps newly added in WF Core 9

- controller/src/main/resources/schema/README.md
- controller/src/main/resources/schema/wildfly-credential-reference_1_0.xsd
- elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
- server/src/main/resources/schema/wildfly-config_10_0.xsd
https://issues.jboss.org/browse/WFCORE-4501
> [WFCORE-4501] Provide XML schema for credential-reference

- core-feature-pack/src/license/core-feature-pack-licenses.xml
> Minor license fixes

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4495
> [WFCORE-4495] Upgrade wildfly-openssl to 1.0.7.Final

- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
Issue: [WFCORE-4398](https://issues.jboss.org/browse/WFCORE-4398)
> WFCORE-4398: fix handling of undefined values

- patching/src/main/java/org/jboss/as/patching/tool/PatchOperationTarget.java
https://issues.jboss.org/browse/WFCORE-4559
> [WFCORE-4559] Incorrectly formatted result produced by LocalPatchOperationTarget.info(stream)

- controller/src/main/java/org/jboss/as/controller/audit/InMemoryAuditLogHander.java
- controller/src/main/java/org/jboss/as/controller/audit/JsonAuditLogItemFormatter.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/JmxAuditLogFieldsOfLogTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-4561
> [WFCORE-4561] JMX audit log does not show operation parameters

- controller/src/main/java/org/jboss/as/controller/PathAddress.java
https://issues.jboss.org/browse/WFCORE-4570
> [WFCORE-4570] quote path element if it contains = or /

- controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
https://issues.jboss.org/browse/WFCORE-4593
> WFCORE-4593 Make ServiceRemoveStepHandler(AbstractAddStepHandler) public

- elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosHttpMgmtSaslTestCase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosNativeMgmtSaslTestCase.java
https://issues.jboss.org/browse/WFCORE-4538
> [WFCORE-4538] Disabling SSL & SASL failing tests on JDK14+

- server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
https://issues.jboss.org/browse/WFCORE-3670 
Reproducer in https://issues.jboss.org/browse/JBEAP-14310 shows that a sub-deployment with dependency referenced to module alias name can't be properly loaded.
As spec from jboss-deployment-structure.xml parsed values are unmodifiable, this fix just replace module alias name with found real module identifier, and make sure it will later load that correct module as dependency.
WFLY test case https://github.com/soul2zimate/wildfly/commit/438f85a71316838fe2a8815d772e7886456e3a23
> [WFCORE-3670] load correct additional module with alias name.

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4552
> [WFCORE-4552] Upgrade Undertow to 2.0.24.Final

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4556
> [WFCORE-4556] Upgrade jboss-remoting version to 5.0.14.Final

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4601
> [WFCORE-4601] Upgrade XNIO version to 3.7.3.Final

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
- io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolService.java
Jira: https://issues.jboss.org/browse/WFCORE-4600
> [WFCORE-4600] Resolve problems with ByteBufferSlicePool usage that are affecting memory footprint and causing leaks

- pom.xml
https://issues.jboss.org/browse/WFCORE-4580
> [WFCORE-4580] Upgrade JBoss Marshalling from 2.0.7.Final to 2.0.8.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4606
> [WFCORE-4606] Upgrade Jackson Databind to 2.9.9.3

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4608
> [WFCORE-4608] Upgrade undertow to 2.0.25.Final

- core-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
- core-galleon-pack/src/main/resources/feature_groups/management.xml
- core-galleon-pack/src/main/resources/layers/standalone/core-security-realms/layer-spec.xml
- core-galleon-pack/src/main/resources/layers/standalone/core-server/layer-spec.xml
- core-galleon-pack/src/main/resources/layers/standalone/legacy-management/layer-spec.xml
- core-galleon-pack/src/main/resources/layers/standalone/management/layer-spec.xml
- testsuite/layers/pom.xml
Issue: https://issues.jboss.org/browse/WFCORE-4616
This enhancement is required by https://issues.jboss.org/browse/WFLY-12407 that will make use of core security-realms.
* New core-security-realms layer
* New legacy-management layer secured with core security-realms
* Layers test evolved with the 2 new layers.
* Documentation will come in wildfly admin doc in fix for WFLY-12407
> Fix for WFCORE-4616, Layer for core security-realms and management layer update

- pom.xml
https://issues.jboss.org/browse/WFCORE-4619
> [WFCORE-4619] Upgrade JBoss Marshalling to 2.0.9.Final

- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
- elytron/pom.xml
- elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SimpleSyslogServer.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/syslog-audit-logging.xml
https://issues.jboss.org/browse/WFCORE-4394
https://issues.jboss.org/browse/EAP7-699
Analysis Document: https://github.com/wildfly/wildfly-proposals/pull/184
WildFly Documentation PR: https://github.com/wildfly/wildfly/pull/12422
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1300
> [WFCORE-4394] Enhanced Audit Logging for Elytron - RFC Support and Configuring Reconnects

- elytron/src/main/java/org/wildfly/extension/elytron/AggregateRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-2/f/i/firstUser.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-2/s/e/secondUser.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/security-realms.xml
https://issues.jboss.org/browse/WFCORE-4496
https://issues.jboss.org/browse/EAP7-1220
This also contains the Elytron subsystem changes in #3805
To pass CI, this will require an Elytron upgrade but this is ready for the subsystem changes to be reviewed.
Analysis document: wildfly/wildfly-proposals#209
WildFly PR: wildfly/wildfly#12371
Depends on wildfly-security/wildfly-elytron#1296
> [WFCORE-4496] Adding principal-transformer to aggregate-realm

- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-4617
@jfdenise could you review please?
> [WFCORE-4617] jboss-cli.sh does not error on invalid options

- controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/interfaces/domain.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/interfaces/host.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/interfaces/standalone.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/standalone.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/standalone_legacy.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/security/users-standalone.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/shipped/standalone.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/domain-transform.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/domain.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/host.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/standalone.xml
- server/src/main/java/org/jboss/as/server/parsing/CommonXml.java
- server/src/main/java/org/jboss/as/server/parsing/InterfacesXml.java
- server/src/main/java/org/jboss/as/server/parsing/SocketBindingsXml.java
https://issues.jboss.org/browse/WFCORE-4624
> [WFCORE-4624] Persist interfaces in alphabetical order

- pom.xml
https://issues.jboss.org/browse/WFCORE-4637
> [WFCORE-4637] Upgrade JBoss / Jakarta JACC to 2.0.0.CR2

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4641
> [WFCORE-4641] Upgrade Undertow to 2.0.26.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4644
> [WFCORE-4644] Upgrade JBoss / Jakarta JACC to 2.0.0.CR3

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4651
> [WFCORE-4651] Upgrade WildFly Open SSL to 1.0.8.Final

- pom.xml
There are no code changes in this one but there was a new tag in Eclipse so keeping our releases in sync.
https://issues.jboss.org/browse/WFCORE-4654
> [WFCORE-4654] Upgrade to JBoss / Jakarta JASPI 2.0.0.CR2

- pom.xml
- server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
This component upgrade incorporates fixes:
* https://issues.jboss.org/browse/MSC-245
* https://issues.jboss.org/browse/MSC-251
MSC fixes are addressing these issues:
* https://issues.jboss.org/browse/WFLY-12167
* https://issues.jboss.org/browse/WFLY-12504
> [WFCORE-4663] Upgrade JBoss MSC to 1.4.11.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4664
> [WFCORE-4664] Upgrade wildfly-build-tools to 1.2.12.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4671
> [WFCORE-4671] Upgrade WildFly Elytron to 1.10.2.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4692
> [WFCORE-4692] Upgrade WildFly Common to 1.5.2.Final

- testsuite/standalone/pom.xml
https://issues.jboss.org/browse/WFCORE-4652
> [WFCORE-4652] Do not execute tests that expect default configuration when Elytron is tested

- pom.xml
- testsuite/patching/pom.xml
https://issues.jboss.org/browse/WFCORE-4678
> [WFCORE-4678] Use a more recent version of guava

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.jboss.org/browse/WFCORE-4702
> WFCORE-4702 Add deployment phases for MicroProfile Fault Tolerance

- pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-4708
> [WFCORE-4708] Upgrade XNIO 3.7.6.Final

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerProcessHandlers.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStopHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractHostScopedRolesTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractRbacTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractStandardRolesTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-4683
> [WFCORE-4683] User with Monitor role can stop the servers in domain mode

- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_4.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_5.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_6.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_7.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_8.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_9.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_Legacy.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_4.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_5.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_6.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_7.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_8.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_9.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_Legacy.java
issue: https://issues.jboss.org/browse/WFCORE-4656
Follow up discussion in https://github.com/wildfly/wildfly-core/pull/3950
> WFCORE-4656 port fix parsers for old namespaces

- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
https://issues.jboss.org/browse/WFCORE-4680
> [WFCORE-4680] Redact passwords in the sun.java.command logging

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/ControlledProcessState.java
- controller/src/main/java/org/jboss/as/controller/ControlledProcessStateService.java
- controller/src/main/java/org/jboss/as/controller/ProcessStateNotifier.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerAdd.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/ShutdownFileSystemDeploymentServiceUnitTestCase.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/BootstrapImpl.java
- server/src/main/java/org/jboss/as/server/DomainServerCommunicationServices.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/deployment/ContentCleanerService.java
- server/src/main/java/org/jboss/as/server/deployment/ContentRepositoryCleaner.java
- server/src/main/java/org/jboss/as/server/jmx/RunningStateJmx.java
- server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
https://issues.jboss.org/browse/WFCORE-4594
Also https://issues.jboss.org/browse/WFCORE-4595
If anyone has a better interface name than ProcessStateNotifier, I won't mind. :)
> [WFCORE-4594][WFCORE-4595] Expose a capability to allow tracking of ControllledProcessState.State

- pom.xml
https://issues.jboss.org/browse/WFCORE-4714
> [WFCORE-4714]  Upgrade galleon-plugins to 4.0.4.Final

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.jboss.org/browse/WFCORE-4717
> [WFCORE-4717] Add missing EE Security DUP phases.

- pom.xml
https://issues.jboss.org/browse/WFCORE-4716
> [WFCORE-4716] Upgrade Byteman to 4.0.8

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
https://issues.jboss.org/browse/WFCORE-4419
> [WFCORE-4419] Remove deprecated ParseUtil methods

- pom.xml
https://issues.jboss.org/browse/WFCORE-4721
> [WFCORE-4721] Upgrade test and build dependencies

- pom.xml
https://issues.jboss.org/browse/WFCORE-4726
> [WFCORE-4726] Add exclusion for 'javax.inject:javax.inject'.

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/ControlledProcessStateService.java
- controller/src/test/java/org/jboss/as/controller/AbstractCapabilityResolutionTestCase.java
- controller/src/test/java/org/jboss/as/controller/CompositeOperationHandlerUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/InterleavedSubsystemTestCase.java
- controller/src/test/java/org/jboss/as/controller/MetricsRegistrationTestCase.java
- controller/src/test/java/org/jboss/as/controller/MetricsUndefinedValueUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/OperationTimeoutUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/RemoveNotEsistingResourceTestCase.java
- controller/src/test/java/org/jboss/as/controller/SocketCapabilityOnHostResolutionUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- server/src/main/java/org/jboss/as/server/ServerService.java
https://issues.jboss.org/browse/WFCORE-4713
> [WFCORE-4713] Migrating controller maven module to new MSC API

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
https://issues.jboss.org/browse/WFCORE-4727
> [WFCORE-4727] Remove no longer needed constructors

- pom.xml
https://issues.jboss.org/browse/WFCORE-4734
> [WFCORE-4734] Upgrade Jackson Databind test dep to 2.9.10.1

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4741
EAP Jira: https://issues.jboss.org/browse/JBEAP-17935
Release Notes
Release Notes - Undertow - Version 2.0.28.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1615'>UNDERTOW-1615</a>] -         Remove unused dependencies from benchmark module
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1612'>UNDERTOW-1612</a>] -         Can&#39;t add more than one cookie with the same name and path but different domain
</li>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1614'>UNDERTOW-1614</a>] -         HttpServletRequestImpl#getRequestUrl() returns an invalid URL in case of empty Host header
</li>
</ul>
> [WFCORE-4741] Upgrade Undertow to 2.0.28.Final

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4711
EAP Jira: https://issues.jboss.org/browse/JBEAP-17789
Release notes:
Release Notes - XNIO - Version 3.7.7.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/XNIO-353'>XNIO-353</a>] -         WARN message for rejected connections over Undertow max-connections limit
</li>
</ul>
> [WFCORE-4711] Upgrade XNIO to 3.7.7.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4738
> [WFCORE-4738] Upgrade Galleon from 4.0.4.Final to 4.1.1.Final

- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/Services.java
- server/src/main/java/org/jboss/as/server/deployment/Attachments.java
- server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
- server/src/main/java/org/jboss/as/server/moduleservice/ExternalModule.java
- server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
jira issue: https://issues.jboss.org/browse/WFCORE-4626
WildFly capability added by this PR is documented here: https://github.com/wildfly/wildfly-capabilities/pull/42
> [WFCORE-4626] Expose ExternalModuleService as WildFly capability

- host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
https://issues.jboss.org/browse/WFCORE-4760
> [WFCORE-4760] Add release versions for WF 16-18

- server/src/main/java/org/jboss/as/server/deployment/AttachmentList.java
https://issues.jboss.org/browse/WFCORE-3948
> [WFCORE-3948] Make AttachmentList thread safe

- core-feature-pack/pom.xml
- core-feature-pack/src/license/core-feature-pack-licenses.xml
- core-galleon-pack/pom.xml
Remove licenses for artifacts that are not present in WildFly Core
feature packs.
JIRA: https://issues.jboss.org/browse/WFCORE-4765
> [WFCORE-4765] Remove artifacts licenses

- elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_9_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/AuthenticationClientTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
Will not compile. Requires [ELY-1853](https://issues.jboss.org/browse/ELY-1853)
> [WFCORE-4704] WS integration with WildFly Elytron - AuthenticationClient for Authentication / SSL

- controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
https://issues.jboss.org/browse/WFCORE-4635
> [WFCORE-4635] Introducing new CapabilityServiceBuilder.provides() method

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpManagementConstantHeadersTestCase.java
Jira: https://issues.redhat.com/browse/WFCORE-1110
> [WFCORE-1110] Tests for configuring custom headers

- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheService.java
https://issues.redhat.com/browse/WFCORE-4778
> [WFCORE-4778] Fixing regression - partial revert of WFCORE-4487

- pom.xml
* upgrade org.codehaus.woodstox.stax2-api to 4.2
JIRA: https://issues.redhat.com/browse/WFCORE-4779
> [WFCORE-4779] Upgrade Woodstox to 6.0.3

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-4786
> [WFCORE-4786] Upgrade jandex 2.1.2.Final

- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
https://issues.redhat.com/browse/WFCORE-4790
> [WFCORE-4790] Refactoring DeploymentScannerService to use undeprecated MSC API

- pom.xml
https://issues.redhat.com/browse/WFCORE-4697
https://issues.redhat.com/browse/WFCORE-4796
Release Notes - WildFly Elytron - Version 1.11.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1919'>ELY-1919</a>] -         Release WildFly Elytron 1.11.0.Final
</li>
</ul>
Release Notes - Elytron Web - Version 1.7.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-88'>ELYWEB-88</a>] -         Upgrade WildFly Elytron to 1.11.0.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-87'>ELYWEB-87</a>] -         Release Elytron Web 1.7.0.Final
</li>
</ul>
> [WFCORE-4697] / [WFCORE-4796] WildFly Elytron Component Upgrades

- pom.xml
* Also upgrade httpcomponents:httpcore to 4.4.12
JIRA: https://issues.redhat.com/browse/WFCORE-4788
> [WFCORE-4788] Upgrade httpclient 4.5.10

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.redhat.com/browse/WFLY-11566
The added phase will be used to provide weld with EJB proxy normalizer as in:
https://github.com/tadamski/wildfly/tree/WFLY-11566
> [WFLY-11566] Add EJB hibernate validator phase

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-4797
Galleon upgrade.
> Fix for WFCORE-4797, Upgrade galleon to 4.2.3

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
- server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTest.java
Issue: https://issues.redhat.com/browse/WFCORE-4736
Fix for WFCORE-4736.
> [WFCORE-4736] Vault system property security attribute value is revealed on CLI 'reload' command

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
Jira: https://issues.redhat.com/browse/WFCORE-4791.
> [WFCORE-4791] Fix HttpManagementConstantHeadersTestCase - ensure that tests do proper environment clean up

- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
https://issues.redhat.com/browse/WFCORE-4820
> [WFCORE-4820] Get the CallbackHandlerService before checking it's type.

- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_11.java
Jira issue: https://issues.redhat.com/browse/WFCORE-4822
> [WFCORE-4822] Remove unused imports from StandaloneXml_11

- core-galleon-pack/src/main/resources/feature_groups/application-security-realm.xml
- core-galleon-pack/src/main/resources/feature_groups/base-security-realms.xml
- core-galleon-pack/src/main/resources/feature_groups/management-security-realm.xml
- core-galleon-pack/src/main/resources/feature_groups/standalone-application-security-realm.xml
- core-galleon-pack/src/main/resources/feature_groups/standalone-management-security-realm.xml
- core-galleon-pack/src/main/resources/feature_groups/standalone-security-realms.xml
- core-galleon-pack/src/main/resources/layers/standalone/application-security-realm/layer-spec.xml
- core-galleon-pack/src/main/resources/layers/standalone/core-security-realms/layer-spec.xml
- core-galleon-pack/src/main/resources/layers/standalone/management-security-realm/layer-spec.xml
- testsuite/layers/pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-4854
Provide more flexibility, realms can be excluded from core-security-realms layer.
> Fix for WFCORE-4854, Layers for application and management realms

- pom.xml
Jira: https://issues.redhat.com/browse/WFCORE-4876
Release Notes - JBoss Remoting (3+) - Version 5.0.18.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-355'>REM3-355</a>] -         Upgrade JBoss Remoting Dependencies
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-352'>REM3-352</a>] -         ConnectionInfo.NoShared does not update state when new connection is created
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-356'>REM3-356</a>] -         Upgrade XNIO to 3.7.7.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/REM3-357'>REM3-357</a>] -         Upgrade apacheds to 2.0.0-M24
</li>
<li>[<a …
> [WFCORE-4876] Upgrade JBoss Remoting to 5.0.18.Final

- controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
- controller/src/main/java/org/jboss/as/controller/OperationDescriptor.java
- controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
- controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
https://issues.redhat.com/browse/WFCORE-4819
> WFCORE-4819 Add OperationDefinition generated by default SimpleResourceDefinition logic never contains parameters

- controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
- controller/src/main/java/org/jboss/as/controller/OperationDescriptor.java
- controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
- controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/transform/description/DiscardAttributeChecker.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemTransformers.java
- logging/src/main/java/org/jboss/as/logging/LoggingResourceDefinition.java
https://issues.redhat.com/browse/WFCORE-4814
Requires https://github.com/wildfly/wildfly-core/pull/4069
> WFCORE-4814 Consolidate common instances of DiscardAttributeChecker that discard an attribute set to the default value

- controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
- controller/src/main/java/org/jboss/as/controller/OperationDescriptor.java
- controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
- controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/transform/description/AttributeConverter.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemTransformers.java
https://issues.redhat.com/browse/WFCORE-4812
Requires https://github.com/wildfly/wildfly-core/pull/4069
> WFCORE-4812 Consolidate instances of DefaultValueAttributeConverter

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-4886
Diff to previous upgrade: https://github.com/apache/httpcomponents-client/compare/rel/v4.5.11...rel/v4.5.12
> [WFCORE-4886] Upgrade httpclient 4.5.12

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-4884
Diff to previous upgrade: https://github.com/wildfly/wildfly-common/compare/1.5.2.Final...1.5.4.Final
> [WFCORE-4884] Upgrade wildfly-common 1.5.4.Final

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-4885
Diff to previous upgrade: https://github.com/wildfly/jandex/compare/2.1.2.Final...2.1.3.Final
> [WFCORE-4885] Upgrade Jandex 2.1.3.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-4890
> [11.0.x] [WFCORE-4890] Upgrade WildFly Elytron to 1.11.3.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-4890
> [WFCORE-4890] Upgrade WildFly Elytron to 1.11.3.Final

- controller/src/main/java/org/jboss/as/controller/transform/description/AttributeConverter.java
https://issues.redhat.com/browse/WFCORE-4918
> WFCORE-4918 Optimize MMR logic within DiscardAttributeChecker.DEFAULT_VALUE

- pom.xml
https://issues.redhat.com/browse/WFCORE-4930
> [WFCORE-4930] Upgrade jboss-logmanager to 2.1.15.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-4913
This update is needed for:
https://issues.redhat.com/browse/WFLY-12190
> [WFCORE-4913] Upgrade wildfly-discovery-client to 1.2.1.Final

- controller/src/main/java/org/jboss/as/controller/transform/description/DiscardAttributeChecker.java
https://issues.redhat.com/browse/WFCORE-4941
Follows up on https://github.com/wildfly/wildfly-core/pull/4146
> WFCORE-4941 Optimize MMR logic within DiscardAttributeChecker.DEFAULT_VALUE

- server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
Issue: https://issues.redhat.com/browse/WFCORE-4935
If server is already in suspend mode, don't register any listener, just shut it down. Otherwise, a suspend mode started server won't be shutdown before resuming.
> [WFCORE-4935] if server is already in suspend mode, don't register  any listener, just shut it down.

- model-test/pom.xml
- subsystem-test/framework/pom.xml
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/bridge/impl/ObjectSerializerImpl.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java
- subsystem-test/tests/pom.xml
https://issues.redhat.com/browse/WFCORE-4915
> [WFCORE-4915] Tighten up the dependency tree of subsystem-test

- pom.xml
https://issues.redhat.com/browse/WFCORE-4906
> [WFCORE-4906] Exclude commons-codec dep from httpclient.

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractEnableAuthenticationCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/OptionActivators.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/PropertiesRealmConfiguration.java
- cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/auth/command_resources.properties
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Issue: [WFCORE-4924](https://issues.redhat.com/browse/WFCORE-4924)
> WFCORE-4924: add plain-text option to security command

- pom.xml
https://issues.redhat.com/browse/WFCORE-4946
https://issues.redhat.com/browse/WFCORE-4947
master PR https://github.com/wildfly/wildfly-core/pull/4185
Release Notes - WildFly Elytron - Version 1.11.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1945'>ELY-1945</a>] -         Authentication vulnerable to session fixation attacks
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1954'>ELY-1954</a>] -         Submission for &quot;j_security_check&quot; login does not work if URL has no trailing slash
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1957'>ELY-1957</a>] -         Release WildFly Elytron 1.11.4.Final
</li>
</ul>
Release Notes - Elytron Web - Version 1.7.1.Final …
> [11.0.x] [WFCORE-4946] / [WFCORE-4947] Elytron Component Upgrades

- controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java
- controller/src/main/java/org/jboss/as/controller/ModelOnlyWriteAttributeHandler.java
https://issues.redhat.com/browse/WFCORE-4957
> WFCORE-4957 Reduce heap footprint of single attribute write-attribute handlers

- testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
* Updating the permissions.
Jira: https://issues.redhat.com/browse/WFCORE-4252
> [WFCORE-4252]: JmxControlledStateNotificationsTestCase test cases fail with security manager on Java 11.

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/RegexAttributeDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_10_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/groups.properties
- elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/role-mappers-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/users-clear.properties
- pom.xml
- testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/RegexRoleMapperTest.java
This PR combines two PRs to get the feature into CI along with the component upgrade.
Combination of the following PRs: -
https://github.com/wildfly/wildfly-core/pull/4205
https://github.com/wildfly/wildfly-core/pull/4017
> [WFCORE-4750] Using regex for role in Elytron

- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
https://issues.redhat.com/browse/WFCORE-4982
> [WFCORE-4982] Convert DeploymentUnitPhaseService to use a for loop instead of a stream to capture known subsystem names.

- pom.xml
https://issues.redhat.com/browse/WFCORE-4937
> [WFCORE-4937] Upgrade FasterXML Jackson to 2.10.4

- testsuite/shared/src/main/java/org/jboss/as/test/layers/Scanner.java
Issue: https://issues.redhat.com/browse/WFCORE-4972
Navigate the module aliases to discover referenced modules.
> Fix for WFCORE-4972, LayersTest doesn't follow module aliases

- pom.xml
- testsuite/rbac/pom.xml
- testsuite/standalone/pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-4984
Impact on tests is a change to configure extra content to package in jar
> Fix for WFCORE-4984, Upgrade tests to use wildfly-jar-maven-plugin Alpha3

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5017
----
Tag: https://github.com/eclipse-ee4j/injection-api/releases/tag/1.0.1
Diff to previous integrated release: https://github.com/eclipse-ee4j/injection-api/compare/1.0...1.0.1
> [WFCORE-5017] Upgrade jakarta.inject-api 1.0.1

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5019
---
Tag: https://github.com/jbossas/jboss-invocation/releases/tag/1.5.3.Final
Diff to previous integrated release: https://github.com/jbossas/jboss-invocation/compare/1.5.2.Final...1.5.3.Final
> [WFCORE-5019] Upgrade jboss-invocation 1.5.3.Final

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5018
----
Tag: https://github.com/FasterXML/stax2-api/releases/tag/stax2-api-4.2.1
Diff to previous integrated release: https://github.com/FasterXML/stax2-api/compare/stax2-api-4.2...stax2-api-4.2.1
> [WFCORE-5018] Upgrade woodstox:stax2-api 4.2.1

- pom.xml
Jira issue: https://issues.redhat.com/browse/WFCORE-5012
> [WFCORE-5012] Upgrade Jboss Threads to 2.3.6

- testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
- testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
https://issues.redhat.com/browse/WFCORE-4817
https://issues.redhat.com/browse/WFCORE-5043
https://issues.redhat.com/browse/WFCORE-5045
https://issues.redhat.com/browse/WFCORE-5046
Fixes test failures when environment defines a _JAVA_OPTIONS environment variable.
> WFCORE-4817, WFCORE-5043, WFCORE-5045, WFCORE-5046 Test fixes

- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
Issue: https://issues.redhat.com/browse/WFCORE-5048
Minor change to make tests HTTPSManagementInterfaceTestCase and HTTPSManagementInterfacePKCS12TestCase work with -Delytron. QA team detected this defect testing the new PKCS12 test and the issue happens in both classes. I just changed the test to detect if the TS is running under elytron and setup/reset in a different way.
> [WFCORE-5048] Tests HTTPSManagementInterfaceTestCase/HTTPSManagementInterfacePKCS12TestCase fail with -Delytron

- bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
- bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/RuntimeExtension.java
Issue: https://issues.redhat.com/browse/WFCORE-5054
> Fix for WFCORE-5054, Allow to load bootable JAR provider during boot

- elytron/src/main/java/org/wildfly/extension/elytron/DistributedRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser11_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_11_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-11.0.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
https://issues.redhat.com/browse/WFCORE-4485
requires ELY-1932 https://github.com/wildfly-security/wildfly-elytron/pull/1374
> [WFCORE-4485] Support for multiple security realms - Distributed Identities

- pom.xml
https://issues.redhat.com/browse/WFCORE-5063
> [WFCORE-5063] Upgrade jboss-parent pom to 37

- jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanServerPlugin.java
- jmx/src/main/java/org/jboss/as/jmx/model/TypeConverters.java
- jmx/src/test/java/org/jboss/as/jmx/ComplexRuntimeAttributesExtension.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
- jmx/src/test/java/org/jboss/as/jmx/model/ExpressionTypeConverterUnitTestCase.java
- jmx/src/test/java/org/jboss/as/jmx/model/LegacyTypeConverterUnitTestCase.java
https://issues.redhat.com/browse/WFCORE-5037
> WFCORE-5037 - Handle maps of complex objects in JMX Facade

- pom.xml
https://github.com/jbossas/jboss-invocation/compare/1.5.3.Final...1.6.0.Final
https://issues.redhat.com/browse/WFCORE-4985
> [WFCORE-4985] Upgrade jboss-invocation from 1.5.3.Final to 1.6.0.Final

- embedded/src/main/java/org/wildfly/core/embedded/HostControllerSystemPropertyContext.java
- embedded/src/main/java/org/wildfly/core/embedded/StandaloneSystemPropertyContext.java
- embedded/src/main/java/org/wildfly/core/embedded/SystemPropertyContext.java
- embedded/src/test/java/org/wildfly/core/embedded/StandaloneSystemPropertyContextTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
JIRA: https://issues.redhat.com/browse/WFCORE-5086
> [WFCORE-5086] Embedded mode sets jboss.server.content.dir incorrectly

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
- elytron/src/test/java/org/wildfly/extension/elytron/CredentialStoreUpdatesTestCase.java
https://issues.redhat.com/browse/WFCORE-5088
@jstourac @darranl Please review.
> [WFCORE-5088] Add validation for the credential-reference attribute

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/FailoverRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_11_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-11.0.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
https://issues.redhat.com/browse/WFCORE-4486
requires ELY-1902 https://github.com/wildfly-security/wildfly-elytron/pull/1354
> [WFCORE-4486] Support for multiple security realms - Failover

- bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
- bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
- core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Issue: https://issues.redhat.com/browse/WFCORE-5116
> Fix for WFCORE-5116, Bootable JAR, JMX not properly initialized at boot.

- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
https://issues.redhat.com/browse/WFCORE-5080
> [WFCORE-5080] KeyStoresTestCase fails on IBM Java 8

- pom.xml
https://issues.redhat.com/browse/WFCORE-5117
> [WFCORE-5117] Upgrade to xerces 2.12.0.SP03

- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
https://issues.redhat.com/browse/WFCORE-5010
> [WFCORE-5010] Startup error messages caused by expression where expressions are not allowed are confusing

- bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
Issue: https://issues.redhat.com/browse/WFWIP-355
> Fix for WFWIP-355, Bootable JAR - scripts in bin folder of the server installation directory are not executable

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/RcFileTestCase.java
Issue: https://issues.redhat.com/browse/WFCORE-5132
> Fix for WFCORE-5132, Bootable JAR, some tests require a start of the server

- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
https://issues.redhat.com/browse/WFCORE-5103
> [WFCORE-5103] Adding non existent and not required keystore fails

- jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
Issue: https://issues.redhat.com/browse/WFCORE-5136
> [WFCORE-5136] NPE in ModelControllerMBeanHelper

- testsuite/layers/pom.xml
- testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
Jira issue: https://issues.redhat.com/browse/WFCORE-5135
> [WFCORE-5135] Add a test case to verify that banned modules are not provisioned

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5142
Diff: https://github.com/wildfly/galleon/compare/4.2.5.Final...galleon-parent-4.2.6.Final
> Fix for WFCORE-5142, Upgrade to Galleon 4.2.6.Final

- io/subsystem/src/main/resources/org/wildfly/extension/io/LocalDescriptions.properties
https://issues.redhat.com/browse/WFCORE-5144
> [WFCORE-5144] Improve the IO worker max-pool-size description

- pom.xml
- testsuite/manualmode/pom.xml
* Upgrading JGit
* Using jsch for testing purpose only
Jira; https://issues.redhat.com/browse/WFCORE-4808
> [WFCORE-4808]: Upgrade JGit to 5.9.0.202009080501-r

- logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
- logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
- logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
Issue: [WFCORE-5113](https://issues.redhat.com/browse/WFCORE-5113)
> WFCORE-5113: fix and ensure default formatter is removed

- pom.xml
https://issues.redhat.com/browse/WFCORE-5156
Release Notes:
- https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md
- https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md
> [WFCORE-5156] Upgrade JUnit to 4.13.1.

- pom.xml
https://issues.redhat.com/browse/WFCORE-5158
> [WFCORE-5158] Upgrade Apache HTTP Client to 4.5.13

- security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
https://issues.redhat.com/browse/WFCORE-5163
> [WFCORE-5163] Don't reject EE 9 permissions.xml files

- pom.xml
https://issues.redhat.com/browse/WFCORE-5159
Branch: https://github.com/jbossas/redhat-picketbox/tree/5.0.x
Diff: https://github.com/jbossas/redhat-picketbox/compare/5.0.3.Final-18-g76744137...5.0.3.Final-20-ga35786ce
> [WFCORE-5159] Upgrade PicketBox from 5.0.3.Final-redhat-00006 to 5.0.3.Final-redhat-00007

- pom.xml
https://issues.redhat.com/browse/WFCORE-5161
> [WFCORE-5161] Upgrade slf4j-jboss-logmanager to 1.1.0.Final

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5141
> [WFCORE-5141] upgraded JBoss Marshalling to 2.0.10.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-5157
> [WFCORE-5157] Upgrade Jackson to 2.11.3

- core-feature-pack/galleon-feature-pack/pom.xml
- core-feature-pack/legacy-feature-pack/pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5168
> [WFCORE-5168] Remove wildfly-core-feature-pack-common and wildfly-core-feature-pack-ee-8-api from licenses

- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
https://issues.redhat.com/browse/WFCORE-5174
> [WFCORE-5174] Make the date comparisons more robust to handle differences caused by daylight saving.

- elytron/pom.xml
https://issues.redhat.com/browse/WFCORE-5167
> [WFCORE-5167] Use individual ApacheDS dependencies to avoid beinging in additional shaded content.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CommandTimeoutHandlerTestCase.java
https://issues.redhat.com/browse/WFCORE-5186
> [WFCORE-5186] Increase sleep in test and make it adjustable

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java
https://issues.redhat.com/browse/WFCORE-5187
> [WFCORE-5187] RemoteSshGitRepositoryTestCase does not work with non-localhost hostname

- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
https://issues.redhat.com/browse/WFCORE-5195
> [WFCORE-5195] Update remaining test cases to use SHA256withRSA over SHA1withRSA.

- cli/src/main/java/org/jboss/as/cli/handlers/CommandCommandHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/GenericTypeOperationHandler.java
- cli/src/main/resources/help/command.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
Issue: https://issues.redhat.com/browse/WFCORE-5009
> Fix for WFCORE-5009, Enhance JBoss CLI generic "command" with support for existing resource

- core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-profile.xml
- core-feature-pack/galleon-common/src/main/resources/feature_groups/elytron-app.xml
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser12_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_12_0.xsd
- elytron/src/main/resources/subsystem-templates/elytron.xml
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-12.0.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
https://issues.redhat.com/browse/WFCORE-5095
https://issues.redhat.com/browse/EAP7-1545
This is for WildFly Core 14. This PR also contains the Elytron subsystem bump from https://github.com/wildfly/wildfly-core/pull/4342.
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/332
WildFly PR with documentation and tests: https://github.com/wildfly/wildfly/pull/13596
> [WFCORE-5095] Add the ability to make use of an automatically generated self-signed certificate with Elytron

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5171
> [WFCORE-5171] Upgrade XNIO to 3.8.4.Final

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5188
> [WFCORE-5188] Upgrade JBoss Modules from 1.10.2.Final to 1.11.0.Final

- core-feature-pack/common/src/main/resources/content/bin/common.ps1
- core-feature-pack/common/src/main/resources/content/bin/domain.bat
- core-feature-pack/common/src/main/resources/content/bin/domain.sh
- core-feature-pack/common/src/main/resources/content/bin/standalone.bat
- core-feature-pack/common/src/main/resources/content/bin/standalone.sh
https://issues.redhat.com/browse/WFCORE-3090
> [WFCORE-3090] Make script messages around process restarts consistent

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.redhat.com/browse/WFCORE-5210
> [WFCORE-5210] Add new Phase ID STRUCTURE_EE_DEFAULT_BINDINGS_CONFIG.

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
JIRA: https://issues.redhat.com/browse/WFCORE-5211
> [WFCORE-5211] Add DUP Phases for base metrics & health subsystems

- server/src/main/java/org/jboss/as/server/deployment/DeploymentAddHandler.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
https://issues.redhat.com/browse/WFCORE-5198
> [WFCORE-5198] Ignore deployment failures such as duplicate classes

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser10_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser12_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/PrincipalTransformerDefinitions.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_12_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/users-clear.properties
- testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/CasePrincipalTransformerTest.java
Jira: https://issues.redhat.com/browse/WFCORE-4994
To pass CI, this will require an Elytron upgrade.
Analysis Document: https://github.com/wildfly/wildfly-proposals/pull/315
Requires: https://issues.redhat.com/browse/ELY-1987
Elytron PR with tests: https://github.com/wildfly-security/wildfly-elytron/pull/1418
Wildfly PR with tests and documentation updates: https://github.com/wildfly/wildfly/pull/13379
> [WFCORE-4994] Add the ability to adjust the case of a user name using an Elytron principal transformer

- pom.xml
Fixes [WFCORE-5202](https://issues.redhat.com/browse/WFCORE-5202)
> WFCORE-5202 Update Bouncycastle to 1.67

- core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
- core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
- core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
- core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
https://issues.redhat.com/browse/WFCORE-4294
> [WFCORE-4294] Added java.awt.headless=true into ps1 and bat conf files

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5231
---
Dev tag: https://github.com/apache/httpcomponents-core/releases/tag/rel%2Fv4.4.14
Diff to previous integrated release: https://github.com/apache/httpcomponents-core/compare/rel/v4.4.13...rel/v4.4.14
---
> [WFCORE-5231] Upgrade httpcomponents.httpcore 4.4.14

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5230
---
Dev tag: https://github.com/wildfly/jandex/releases/tag/2.1.4
Diff to previous integrated release: https://github.com/wildfly/jandex/compare/2.1.3.Final...2.1.4
> [WFCORE-5230] Upgrade Jandex 2.1.4.Final

- core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-profile.xml
- core-feature-pack/galleon-common/src/main/resources/feature_groups/elytron-app.xml
- elytron/src/main/resources/subsystem-templates/elytron.xml
https://issues.redhat.com/browse/WFCORE-5238
> [WFCORE-5238] Set default KeyStore type to JKS.

- .github/workflows/dep-diff-pull_request.yml
- .github/workflows/dep-diff-workflow_run.yml
- core-feature-pack/common/pom.xml
- temp.txt
pull_request_target did not work the way I thought, and also is a
potential security risk (see https://securitylab.github.com/research/github-actions-preventing-pwn-requests
for details)
> Split dep checker into pull_request and workflow_run since

- core-feature-pack/common/src/main/resources/content/bin/jboss-cli.sh
- testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
https://issues.redhat.com/browse/WFCORE-5216
> [WFCORE-5216] jboss-cli.sh script should use eval instead of exec

- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
https://issues.redhat.com/browse/WFCORE-5252
> [WFCORE-5252] Log WARN if wildfly.config.url is set on the server.

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/OperationContext.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
https://issues.redhat.com/browse/WFCORE-2687
>  [WFCORE-2687] Addition of getCurrentOperationName() and getCurrentOperationParameter(String name) methods

- core-feature-pack/common/src/main/resources/content/bin/common.ps1
- core-feature-pack/common/src/main/resources/content/bin/domain.bat
- core-feature-pack/common/src/main/resources/content/bin/domain.ps1
https://issues.redhat.com/browse/WFCORE-3825
> [WFCORE-3825] Unify -server option in windows scripts (ps1, bat) for domain mode (and its servers) on all JDKs

- cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/deployment/command_resources.properties
- domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
Jira issue: https://issues.redhat.com/browse/WFCORE-5292
@RanabirChakraborty review if you have a chance, thanks!
> [WFCORE-5292] Remove Java EE References from the i18n strings

- jmx/src/main/java/org/jboss/as/jmx/JMXExtension.java
- jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java
- jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRootResource.java
- jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
- jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
- jmx/src/test/resources/org/jboss/as/jmx/subsystem-with-expressions.xml
https://issues.redhat.com/browse/WFCORE-5288
> [WFCORE-5288] Improve JMX subsystem tests

- remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorRemove.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionWriteHandler.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionWriteHandler.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionWriteHandler.java
https://issues.redhat.com/browse/WFCORE-5253
> [WFCORE-5253] Clean up remoting subsystem OSH use of 'operation'

- pom.xml
- testsuite/manualmode/pom.xml
* Upgrading jgit to the new 5.10.0.202012080955-r version
Jira: https://issues.redhat.com/browse/WFCORE-5276
> [WFCORE-5276]: Upgrade jgit to 5.10.0.202012080955-r

- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
https://issues.redhat.com/browse/WFCORE-5271
> [WFCORE-5271] NullPointerException creating new KeyStore without type

- elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
https://issues.redhat.com/browse/WFCORE-5300
> [WFCORE-5300] Before generating a secret key check if the credential store already contains one under the specified alias.

- elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
https://issues.redhat.com/browse/WFCORE-5302
> [WFCORE-5302] Correct the cast to avoid a ClassCastException.

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5293
Diff: https://github.com/aeshell/aesh-readline/compare/2.0...2.2
> Fix for WFCORE-5293, Upgrade aesh-readline to 2.2

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5317
diff: https://github.com/wildfly/galleon-plugins/compare/5.0.0.Final...5.1.0.Final
> Fix for WFCORE-5317, Upgrade galleon-plugins to 5.1.0

- pom.xml
https://issues.redhat.com/browse/WFCORE-5294
> [WFCORE-5294] Upgrade jandex to 2.2.3.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-5318
> [WFCORE-5318] Upgrading Byteman to 4.0.14

- pom.xml
https://issues.redhat.com/browse/WFCORE-5321
> [WFCORE-5321] Upgrading xalan to 2.7.1.jbossorg-5

- elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
https://issues.redhat.com/browse/WFCORE-5296
https://issues.redhat.com/browse/WFCORE-5298
This also benefits from the following Elytron change although the two can be merged independently:
https://github.com/wildfly-security/wildfly-elytron/pull/1491
> [WFCORE-5296] Improve error reporting for the secret key manipulation operations.

- elytron/src/test/java/org/wildfly/extension/elytron/CredentialStoreTestCase.java
https://issues.redhat.com/browse/WFCORE-5325
Depends on #4495
> [WFCORE-5325] Additional tests for credential stores

- core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
Issue: https://issues.redhat.com/browse/WFCORE-5249
This supersedes https://github.com/wildfly/wildfly-core/pull/4506 to apply changes requested from the review.
> WFCORE-5249: NoClassDefFoundError: Failed to link org/bouncycastle/openpgp/PGPEncryptedDataList: org/bouncycastle/util/Iterable

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveHostControllerAuthenticationTestCase.java
https://issues.redhat.com/browse/WFCORE-5326
> [WFCORE-5326] Extend SlaveHostControllerAuthenticationTestCase with test for Elytron expression resolver

- elytron/pom.xml
- elytron/src/test/java/org/wildfly/extension/elytron/ElytronSubsystem13_0TestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/ResolveExpressionAttributesTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-expressions.xml
https://issues.redhat.com/browse/WFCORE-5283
> [WFCORE-5283] Add tests to the Elytron subsystem for attributes that allow expressions

- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
https://issues.redhat.com/browse/WFCORE-5205
> [WFCORE-5205] Use new Module.findServices() utility method to load security providers

- elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
Issue: https://issues.redhat.com/browse/WFCORE-5272
> [WFCORE-5272] Setting jacc provider to Elytron throws exceptions

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5351
Diff: https://github.com/wildfly/galleon-plugins/compare/5.1.0.Final...5.1.1.Final
> Fix for WFCORE-5351, Upgrade galleon-plugins to 5.1.1

- testsuite/standalone/pom.xml
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
https://issues.redhat.com/browse/WFCORE-4221
> [WFCORE-4221] ReadConfigAsFeaturesStandaloneTestCase fails with Elytron profile

- core-feature-pack/common/src/main/resources/content/bin/common.ps1
- core-feature-pack/common/src/main/resources/content/bin/standalone.bat
- core-feature-pack/common/src/main/resources/content/bin/standalone.ps1
https://issues.redhat.com/browse/WFCORE-4008
> [WFCORE-4008] Unify -server option in windows standalone scripts (ps1, bat)

- core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat
https://issues.redhat.com/browse/WFCORE-5092
> [WFCORE-5092] Added passing NOPAUSE=Y from service.bat to jboss-cli.bat

- pom.xml
https://issues.redhat.com/browse/WFCORE-5360
Diff: https://github.com/apache/logging-log4j2/compare/rel/2.14.0...rel/2.14.1
> [WFCORE-5360] Upgrade log4j2 to 2.14.1.

- core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/README.md
Added notes for SysV vs Systemd distros. Cleaned up Markdown.
[Jira - WFCORE-5352](https://issues.redhat.com/browse/WFCORE-5352)
> [WFCORE-5352] Updated README.md for user contributed init scripts

- .github/workflows/stale.yml
> Increase the stale warning message from 30 to 45 days

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
https://issues.redhat.com/browse/WFCORE-5370
Add `associateIdentity()` call to `ManagementHandler` processing to property associate authenticated user with current request
> [WFCORE-5370] Properly associate authenticated user with current request

- controller/src/main/java/org/jboss/as/controller/ModelControllerLock.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
- controller/src/main/java/org/jboss/as/controller/registry/RuntimePackageDependency.java
- controller/src/main/java/org/jboss/as/controller/security/InetAddressPrincipal.java
- controller/src/main/java/org/jboss/as/controller/services/path/AbstractPathService.java
- controller/src/test/java/org/jboss/as/controller/support/ChannelServer.java
Original PR was too big to verify. It has been splitted up, here: controller
> [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (controller)

- network/src/main/java/org/jboss/as/network/ManagedBinding.java
- network/src/main/java/org/jboss/as/network/NetworkUtils.java
Original PR was too big to verify. It has been splitted up, here: network
> [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (network)

- server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java
* Moving files into an "attic" folder.
* Restoring files in case of git failure.
* Deleting attic files afterwards.
Jira: https://issues.redhat.com/browse/WFCORE-5334
> [WFCORE-5334]: Deleting Configuration Data when Git connection is failed.

- domain-management/src/main/java/org/jboss/as/domain/management/access/RoleMappingRemove.java
https://issues.redhat.com/browse/WFCORE-5370
If the resource to be removed doesn't exist, the operation should fail
> [WFCORE-5373] Fix missing resource handling

- core-model-test/framework/src/main/java/org/jboss/as/core/model/test/LegacyModelInitializerEntry.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
- model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
- patching/src/main/java/org/jboss/as/patching/management/PatchResource.java
- patching/src/main/java/org/jboss/as/patching/tool/PatchOperationTarget.java
- patching/src/main/java/org/jboss/as/patching/tool/PatchingHistory.java
- patching/src/main/java/org/jboss/as/patching/validation/BasicArtifactProcessor.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/ControllerInitializer.java
- testsuite/shared/src/main/java/org/jboss/as/test/deployment/DeploymentInfoUtils.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ManagementClient.java
Original PR was too big to verify. It has been splitted up, here: misc. This is the last one for the WFCORE-5285 series.
> [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (misc)

- controller/src/main/java/org/jboss/as/controller/OperationContext.java
Issue: https://issues.redhat.com/browse/WFCORE-4162
> WFCORE-4162 Incorrect OperationContext.getCapabilityServiceName javadoc

- cli/pom.xml
- controller-client/pom.xml
- controller/pom.xml
- core-feature-pack/common/pom.xml
- core-management/core-management-subsystem/pom.xml
- core-model-test/tests/pom.xml
- domain-http/interface/pom.xml
- domain-management/pom.xml
- elytron/pom.xml
- host-controller/pom.xml
- jmx/pom.xml
- logging/pom.xml
- network/pom.xml
- patching/pom.xml
- platform-mbean/pom.xml
- pom.xml
- process-controller/pom.xml
- protocol/pom.xml
- remoting/subsystem/pom.xml
- security-manager/pom.xml
- server/pom.xml
- subsystem-test/framework/pom.xml
- testsuite/elytron/pom.xml
- testsuite/manualmode/pom.xml
- testsuite/patching/pom.xml
- testsuite/pom.xml
- testsuite/shared/pom.xml
- testsuite/standalone/pom.xml
- testsuite/test-runner/pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5263
> WFCORE-5263 Update all projects with a dependency on wildfly-elytron to use individual modules

- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
https://issues.redhat.com/browse/WFCORE-5185
> [WFCORE-5185] Update ProviderDefinition to use optimised service loading API

- core-feature-pack/common/src/main/resources/content/bin/domain.conf
- core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
- core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
- core-feature-pack/common/src/main/resources/content/bin/standalone.conf
- core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
- core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
https://issues.redhat.com/browse/WFCORE-2925
> [WFCORE-2925] Heap settings separation in standalone and domain conf scripts

- elytron/src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
https://issues.redhat.com/browse/WFCORE-5383
> [WFCORE-5383] Fix test failure in LdapTestCase that happens with openjdk-1.8.0.292

- pom.xml
Dev tag: https://github.com/wildfly/galleon-plugins/releases/tag/5.1.3.Final
Diff to previous release: https://github.com/wildfly/galleon-plugins/compare/5.1.2.Final...5.1.3.Final
JIRA: https://issues.redhat.com/browse/WFCORE-5397
> [WFCORE-5397] Upgrade galleon-plugins 5.1.3.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-5400
Resolve https://issues.redhat.com/browse/WFLY-14779
> WFCORE-5400 Upgrade Mockito to 3.10.0.

- pom.xml
https://issues.redhat.com/browse/WFCORE-5401
> [WFCORE-5401] Upgrade to Byteman 4.0.15

- pom.xml
https://issues.redhat.com/browse/WFCORE-5402
> [WFCORE-5402] Upgrade JBoss Marshalling to 2.0.12.Final

- cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
Issue: https://issues.redhat.com/browse/WFCORE-4324
The random failures (on s390 + openj9) are caused by synchronous future task canceled immediately after having been created (failing test case) that, although canceled, are not throwing an exception when get is called.
This change throws an exception for synchronous tasks that are in timeout.
Multiple runs have been done to validate the fix: https://ci.wildfly.org/buildConfiguration/WildFlyCore_MasterLinuxS390OpenJ911/255600
> Fix for WFCORE-4324, CommandTimeoutHandlerTestCase.testComandExecutor random failure

- controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/util/AbstractControllerTestBase.java
- host-controller/src/test/java/org/jboss/as/host/controller/util/AbstractControllerTestBase.java
- jmx/src/test/java/org/jboss/as/jmx/test/util/AbstractControllerTestBase.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServicesImpl.java
https://issues.redhat.com/browse/WFCORE-5386
> [WFCORE-5386] Increase container shutdown wait time for better CI results stability

- elytron/pom.xml
- pom.xml
https://issues.redhat.com/browse/WFCORE-5410
> [WFCORE-5410] Update elytron subsystem to take modular jdk params into account

- pom.xml
https://issues.redhat.com/browse/WFCORE-5408
> [WFCORE-5408] Update JBoss Classfilewriter to 1.2.5.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-5418
> [WFCORE-5418] Minimal but complete set of modular JDK params needed to build WildFly Core and run its whole test suite

- pom.xml
https://issues.redhat.com/browse/WFCORE-5417
> [WFCORE-5417] Upgrade galleon-plugins to 5.2.0.Alpha1

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/OperationFailuresDuringBootTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/RootResourceDefinition.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/TestExtension.java
- testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/booterror/module.xml
- testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/booterror/org.jboss.as.controller.Extension
https://issues.redhat.com/browse/WFCORE-5368
> [WFCORE-5368] Specifically track operations considered to be part of boot

- elytron/pom.xml
- elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
- elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
- elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
https://issues.redhat.com/browse/WFCORE-5255
https://issues.redhat.com/browse/WFCORE-5169
> [WFCORE-5255] / [WFCORE-5169] Migrate all tests to use Apache DS AM26 and org.apache.directory.api 2.0.0

- elytron/pom.xml
- pom.xml
- testbom/pom.xml
- testsuite/shared/pom.xml
- testsuite/standalone/pom.xml
…testbom
https://issues.redhat.com/browse/WFCORE-5403
> [WFCORE-5403][WFCORE-5405] Control mockserver-netty and xom from testbom

- pom.xml
https://issues.redhat.com/browse/WFCORE-5429
> [WFCORE-5429] Require Java 8 when the deploy lifecycle phase is executed.

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
https://issues.redhat.com/browse/WFCORE-5427
> [WFCORE-5427] Avoid ClassCastException when determining whether or not a self-signed certificate should be automatically generated

- pom.xml
https://issues.redhat.com/browse/WFCORE-5431
Diff: https://github.com/jboss-logging/jboss-logging/compare/3.4.1.Final...3.4.2.Final
> [WFCORE-5431] Upgrade jboss-logging to 3.4.2.Final.

- host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
https://issues.redhat.com/browse/WFCORE-5406
> [WFCORE-5406] Fixing typo

- elytron/pom.xml
- elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
- elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
- elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
https://issues.redhat.com/browse/WFCORE-5255
https://issues.redhat.com/browse/WFCORE-5169
Reverts commits 219f896d77cbedfe2f3b025d0781e7e94e2cb670 and 95ed79c22dc854c0f591e753ea020991c6a9c2b1
Revert caused by https://issues.redhat.com/browse/WFCORE-5432
> [WFCORE-5255] / [WFCORE-5169] Revert WFCORE-5255 and WFCORE-5169

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5448
Dev tag: https://github.com/lemire/javaewah/releases/tag/JavaEWAH-1.1.12
Diff to previous integrated release: https://github.com/lemire/javaewah/compare/JavaEWAH-1.1.8...JavaEWAH-1.1.12
> [WFCORE-5448] Upagde JavaEWAH 1.1.12

- pom.xml
JIRA: https://issues.redhat.com/browse/WFCORE-5446
Dev tag: https://github.com/wildfly/galleon-plugins/releases/tag/5.2.0.Alpha2
Diff to previous integrated release: https://github.com/wildfly/galleon-plugins/compare/5.2.0.Alpha1...5.2.0.Alpha2
> [WFCORE-5446] Upgrade WildFly Galleon Plugons 5.2.0.Alpha2

- deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
- pom.xml
- server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
* upgrading JGit to 5.11.1.202105131744-r
* upgrading Apache SSH to 2.6.0
Jira: https://issues.redhat.com/browse/WFCORE-5409
> [WFCORE-5409]: Upgrade JGit to 5.11.1.202105131744-r

- elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
- pom.xml
https://issues.redhat.com/browse/WFCORE-5452
> [WFCORE-5452] Sync updates to TLS configuration and minor changes for Java 17.

- pom.xml
Issue: https://issues.redhat.com/browse/WFCORE-5447
> Fix for WFCORE-5447, Upgrade galleon-plugins to 5.2.0.Final

- pom.xml
https://issues.redhat.com/browse/WFCORE-5460
https://github.com/wildfly-security/wildfly-elytron/compare/1.16.0.CR1...1.16.0.Final
<details>
<summary>Release Notes - WildFly Elytron - Version 1.16.0.Final</summary>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2088'>ELY-2088</a>] -         Revert Temporary Commit 68c2e952db67da0eebdde9ffcbec513a2af3f682
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2131'>ELY-2131</a>] -         Possible NullPointerException in JwtValidator when validating token with jku claim and SSL is not configured.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2133'>ELY-2133</a>] -         Release WildFly Elytron 1.16.0.Final
</li>
</ul>
</h2>
<ul> …
> [WFCORE-5460] Upgrade WildFly Elytron to 1.16.0.Final

- ide-configs/eclipse/wildfly-cleanup.xml
- ide-configs/eclipse/wildfly-formatter.xml
- ide-configs/eclipse/wildfly-templates.xml
Fixes https://issues.redhat.com/browse/WFCORE-5434
> [WFCORE-5434] Update ide-config to Eclipse 2021-03

- README.md
Issue: https://issues.redhat.com/browse/WFCORE-5471
> WFCORE-5471 Broken links in README

- controller/src/main/java/org/jboss/as/controller/access/constraint/AbstractSensitivity.java
- patching/src/main/java/org/jboss/as/patching/runner/AbstractPatchingTask.java
- patching/src/main/java/org/jboss/as/patching/tool/ContentPolicyBuilderImpl.java
Fixing https://issues.redhat.com/browse/WFCORE-5445
> [WFCORE-5445] Short circuit logic for boolean eval

- jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
multiple (3x) times
Fixes https://issues.redhat.com/browse/WFCORE-5443
> [WFCORE-5443] JMX MBeanInfoFactory OR Statement has same comparision

- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/ManagementDisableSSLCommand.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/ZipCompletionScanner.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHttpHandler.java
- patching/src/main/java/org/jboss/as/patching/runner/PatchModuleInvalidationUtils.java
Fixes https://issues.redhat.com/browse/WFCORE-5442
> [WFCORE-5442] Math operands should be cast before assignment

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/TemporaryModuleLayer.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheService.java
Fixes https://issues.redhat.com/browse/WFCORE-5441
> [WFCORE-5441] Logic in try/finally blocks hides exceptions

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.redhat.com/browse/WFCORE-5217
> [WFCORE-5217] Add Phase constants for MP Reactive Messaging and RSO

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleListAttributeDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
- elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
- host-controller/src/main/java/org/jboss/as/host/controller/discovery/DiscoveryOptionsResourceDefinition.java
- io/subsystem/src/main/java/org/wildfly/extension/io/OptionAttributeDefinition.java
https://issues.redhat.com/browse/WFCORE-5467
Remove props and methods
Delete noinspection comments
Fix lingering uses of deprecated property access
@darranl I'd appreciate a careful look at the Elytron-related changes to make sure I got those correct
> [WFCORE-5467] Remove deprecated properties and methods
