server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

Jira: https://issues.jboss.org/browse/WFCORE-4129
This reduces the side effect in Linux where the symbolic link is used

[WFCORE-4129] WFLYSRV0266: Server home is set to... info msg in domain for RPM installation

---

cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandContainer.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/operation/LegacyCommandContainer.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/operation/OperationCommandContainer.java
pom.xml

Fix for: https://issues.jboss.org/browse/WFCORE-4402 and https://issues.jboss.org/browse/WFCORE-4408
- Aesh release contains jansi upgrade needed to fix dll copy on Windows.
- jansi upgrade to the one expected by aesh.

Fix for WFCORE-4402, Upgrade CLI to use aesh 2.3

---

pom.xml

This component upgrade is just switching to the minor version of Elytron Web also updated to use the modularised version of WildFly Elytron - this specific release does not contain further fixes / enhancements.

[WFCORE-4410] Upgrade Elytron Web to 1.5.0.CR1

---

core-feature-pack/src/main/resources/modules/system/layers/base/javax/api/main/module.xml
core-feature-pack/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml

https://issues.jboss.org/browse/WFCORE-4413

[WFCORE-4413] Fixing javax.api and javax.sql.api modules BC issues

---

controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java

Also fixes a couple minor IDE warns in the file.
https://issues.jboss.org/browse/WFCORE-4418

[WFCORE-4418] Deprecate unused ParseUtil methods.

---

core-feature-pack/src/main/resources/content/bin/common.bat
core-feature-pack/src/main/resources/content/bin/common.ps1
core-feature-pack/src/main/resources/content/bin/common.sh
host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
pom.xml

https://issues.jboss.org/browse/WFCORE-4415
This update brings in the following fixes:
* [MODULES-387] Add JMX operation to get a class location
* [MODULES-386] Fixing Javadoc build issues on JDK11
* [MODULES-375] Check if the artifact was successfully resolved before attempting to create the loader
* [MODULES-372] provide our own "java.se" module on JDK 9+

[WFCORE-4415] Upgrading JBoss Modules from 1.9.0.Final to 1.9.1.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4430

[WFCORE-4430] Upgrade jboss-stdio from 1.0.2.GA to 1.1.0.Final.

---

core-feature-pack/pom.xml
core-feature-pack/src/license/core-feature-pack-licenses.xml
core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
core-galleon-pack/pom.xml
elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
pom.xml

https://issues.jboss.org/browse/WFCORE-4417
This pull request does introduce one new module, however this is just a new sub module within the WildFly Elytron project and not a new dependency.
Release Notes - WildFly Elytron - Version 1.9.0.CR3
** Bug
* [ELY-1761] - Unicode normalization in SASL client breaks some non-ASCII passwords
** Task
* [ELY-1764] - Get all Provider implementations moved to their own module.
* [ELY-1779] - Make 'org.wildfly.security.password.util' public API
* [ELY-1782] - Update the branch for new features and enhancements in the "Contributions" section in the README.md
** Release
* [ELY-1785] - Release WildFly Elytron 1.9.0.CR3

[WFCORE-4417] Upgrade WildFly Elytron to 1.9.0.CR3

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
elytron/src/main/java/org/wildfly/extension/elytron/TrivialAddHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java
io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingGroupAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/SpecifiedInterfaceAddHandler.java

https://issues.jboss.org/browse/WFCORE-4412

[WFCORE-4412] Eliminating CapabilityServiceTarget.addCapability() deprecated method usages

---

logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/StructuredFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java

Issue: [WFCORE-3891](https://issues.jboss.org/browse/WFCORE-3891)

WFCORE-3891: ensure unique names for default formatters

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4432
This component upgrade brings in the following fix:
* [JBMAR-222] Fixed Vector & Stack serialization to prevent ConcurrentModificationException

[WFCORE-4432] Upgrading JBoss Marshalling to 2.0.7.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4443
https://issues.jboss.org/browse/WFCORE-4444
Bug fix / minor maintenance releases.
**Release Notes - WildFly Elytron - Version 1.9.0.CR4**
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1786'>ELY-1786</a>] -         JBoss Logging Component Upgrades
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1787'>ELY-1787</a>] -         Upgrade WildFly Common to 1.5.1.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1793'>ELY-1793</a>] -         Cache JsonProvider in JsonSecurityEventFormatter
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1794'>ELY-1794</a>] -         FORM Authentication should detect FORM …

[WFCORE-4443] / [WFCORE-4444] WildFly Elytron Component Upgrades

---

controller/src/main/java/org/jboss/as/controller/operations/validation/EnumValidator.java

Issue: [WFCORE-3298](https://issues.jboss.org/browse/WFCORE-3298)

WFCORE-3298: do not try to modify protected nodes

---

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java

This fix follows up https://github.com/wildfly/wildfly-core/pull/3699, it disables the console error context handler only for ConsoleMode.NO_CONSOLE. For any other console modes ADMIN_ONLY, SLAVE_HC or CONSOLE, the error context handler is added.
Jira issue: https://issues.jboss.org/browse/WFCORE-4438
FYI @soul2zimate since it is related to the changes in this PR: https://github.com/jbossas/wildfly-core-eap/pull/662

[WFCORE-4438] Disable console error context handler for ConsoleMode.NO_CONSOLE

---

core-galleon-pack/pom.xml
core-galleon-pack/src/main/resources/packages/bin/package.xml
pom.xml

F- ix for https://issues.jboss.org/browse/WFCORE-4406
- Upgrade to galleon 4.0 alpha. Final upgrade is tracked by (https://issues.jboss.org/browse/WFCORE-4422)
- Produces FP with Galleon 4.0, generates and deploy wildfly-core offliner. That is a required step to address: https://issues.jboss.org/browse/WFLY-11989
- Make dependencies provided, it is required to not download all dependencies when building User feature-packs from wildfly feature-packs.

Fix for WFCORE-4406 and Upgrade to Galleon 4.0.0.alpha

---

elytron/pom.xml
elytron/src/main/java/org/wildfly/extension/elytron/DefaultSSLContextService.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

https://issues.jboss.org/browse/WFCORE-4457

[WFCORE-4457] Ensure that any tests that set the JVM wide default SSLContext restore it to the default default.

---

core-feature-pack/pom.xml
core-feature-pack/src/license/core-feature-pack-licenses.xml
core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/event/logger/main/module.xml
core-galleon-pack/pom.xml
event-logger/README.adoc
event-logger/pom.xml
event-logger/src/main/java/org/wildfly/event/logger/AbstractEvent.java
event-logger/src/main/java/org/wildfly/event/logger/AbstractEventLogger.java
event-logger/src/main/java/org/wildfly/event/logger/AsyncEventLogger.java
event-logger/src/main/java/org/wildfly/event/logger/Event.java
event-logger/src/main/java/org/wildfly/event/logger/EventFormatter.java
event-logger/src/main/java/org/wildfly/event/logger/EventLogger.java
event-logger/src/main/java/org/wildfly/event/logger/EventWriter.java
event-logger/src/main/java/org/wildfly/event/logger/JsonEventFormatter.java
event-logger/src/main/java/org/wildfly/event/logger/LazyEvent.java
event-logger/src/main/java/org/wildfly/event/logger/StandardEvent.java
event-logger/src/main/java/org/wildfly/event/logger/StandardEventLogger.java
event-logger/src/main/java/org/wildfly/event/logger/StdoutEventWriter.java
event-logger/src/test/java/org/wildfly/event/logger/AbstractEventLoggerTestCase.java
event-logger/src/test/java/org/wildfly/event/logger/AsyncEventLoggerTestCase.java
event-logger/src/test/java/org/wildfly/event/logger/QueuedJsonWriter.java
event-logger/src/test/java/org/wildfly/event/logger/StandardEventLoggerTestCase.java
pom.xml
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java

JIRA: https://issues.jboss.org/browse/WFCORE-4355
Proposal: https://github.com/wildfly/wildfly-proposals/pull/181
Introduces a simple event logging API into WildFly Core. This will be able to be used for things like access logging, security audit logging, EJB access logging and management audit logging. The purpose of this API for now is to simply have a unified way of formatting a JSON message and writing to `stdout`.

[WFCORE-4355] Introduce a simple event logging API.

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4464
Only small changes although the fix for ELY-1799 is a blocker to get in.
Release Notes - WildFly Elytron - Version 1.9.0.CR5
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1798'>ELY-1798</a>] -         Upgrade jboss-parent to version 35
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1799'>ELY-1799</a>] -         Upgrade WildFly Checkstyle Config to 1.0.8.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1790'>ELY-1790</a>] -         elytron-tool.sh : ClassNotFoundException: org.wildfly.security.password.impl.PasswordFactorySpiImpl
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1801'>ELY-1801</a>] - …

[WFCORE-4464] Upgrade WildFly Elytron to 1.9.0.CR5

---

core-feature-pack/pom.xml
core-feature-pack/src/license/core-feature-pack-licenses.xml
core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
core-galleon-pack/pom.xml
pom.xml

https://issues.jboss.org/browse/WFCORE-4467
https://issues.jboss.org/browse/WFCORE-4468
Release Notes - WildFly Elytron - Version 1.9.0.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1805'>ELY-1805</a>] -         Remove wildfly-elytron-titan module from project
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1807'>ELY-1807</a>] -         Two ElytronMessage definitions in the same package
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1716'>ELY-1716</a>] -         Develop an alternative to &#39;wildfly-elytron-credential-source-deprecated&#39;
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1762'>ELY-1762</a>] -         Ensure JAPICMP Compatibility and enable plug-in for all builds.
</li>
</ul> …

[WFCORE-4467] / [WFCORE-4468] WildFly Elytron Component Upgrades

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4469
Release Notes - Remoting JMX - Version 3.0.2.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/REMJMX-160'>REMJMX-160</a>] -         Every JMXConnectorFactory#connect() creates a new ThreadGroup which is never reclaimed
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/REMJMX-162'>REMJMX-162</a>] -         Release Remoting JMX 3.0.2.Final
</li>
</ul>

[WFCORE-4469] Upgrade Remoting JMX to 3.0.2.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/TrivialAddHandler.java
elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java

Change the initial mode of some of the Security Domain service graph as LAZY to allow configuring them in an embedded server running in admin-mode.
Jira issue: https://issues.jboss.org/browse/WFCORE-4407
CC: @darranl

[WFCORE-4407] Configure Elytron domain services with LAZY initial mode

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4476
Release Notes - WildFly Elytron - Version 1.9.1.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1810'>ELY-1810</a>] -         (Intermittent) stuck start with secmgr after enabling Elytron JACC for undertow/application-security-domain
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1811'>ELY-1811</a>] -         Release WildFly Elytron 1.9.1.Final
</li>
</ul>

[WFCORE-4476] Upgrade Wildfly Elytron to 1.9.1.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4480
Release Notes - Remoting JMX - Version 3.0.3.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/REMJMX-163'>REMJMX-163</a>] -         After unsuccessful connect attempts (Client Side)  the Endpoint is not closed
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/REMJMX-165'>REMJMX-165</a>] -         Release Remoting JMX 3.0.3.Final
</li>
</ul>

[WFCORE-4480] Upgrade Remoting JMX to 3.0.3.Final

---

pom.xml

Jira: https://issues.jboss.org/browse/WFCORE-4491
and https://issues.jboss.org/browse/WFCORE-4490
Notice that WFCORE-4491 blocks WFCORE-4490, so this PR can be merged as an option to https://github.com/wildfly/wildfly-core/pull/3795 followed by https://github.com/wildfly/wildfly-core/pull/3786 if that saves some time for you, @jmesnil 
(the first PR, XNIO upgrade, will have tests passing only after the second PR, jboss remoting upgrade, is merged)

[WFCORE-4490] [WFCORE-4491] Upgrade  JBoss Remoting to 5.0.12.Final and Xnio to 3.7.2.Final

---

core-feature-pack/src/main/resources/content/bin/common.sh

The commit here is a patch borrowed from the JIRA https://issues.jboss.org/browse/WFLY-12126 where the user reports an issue with the server startup when the Java installation contains a space character in its path.

WFLY-12126 Fix issue with Java installations containing a space character

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4506
Incorporates:
* [MSC-242] Ensuring ReadableValueImpl and WritableValueImpl fields visibility
* [MSC-243] Fixing wrong Java SE 8 API docs link
* [MSC-244] Deprecating ServiceBuilder.addAliases(ServiceName...) method

[WFCORE-4506] Upgrade JBoss MSC to 1.4.6.Final.

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4509
Incorporates:
* [MSC-245] Fixed ServiceContainerImpl.registry memory leak
Fixes:
* [WFLY-12167] Memory leak in metrics in standalone-ha configuration

[WFCORE-4509] Upgrade JBoss MSC to 1.4.7.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4528
https://issues.jboss.org/browse/WFCORE-4529
Release Notes - WildFly Elytron - Version 1.10.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1823'>ELY-1823</a>] -         Update SecurityProviderServerMechanismFactory to cache Provider interaction.
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1824'>ELY-1824</a>] -         Provider should cache instances of stateless factories it creates
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1617'>ELY-1617</a>] -         Support SSL Certificate revocation using OCSP
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1797'>ELY-1797</a>] -         Make the certificate authority used by a …

[WFCORE-4528] / [WFCORE-4529] WildFly Elytron Component Upgrades

---

deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentFullReplaceHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ServerGroupDeploymentReplaceHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java

Specifically, it addresses two incorrect behavior 
1. When a deployment is replaced using --force, which translates into `:full-replace-deployment` operation, we were not tracking correctly the references to the replaced content. The problem here is the content could be deleted by the cleanup task.
2. Server group replacement operation was using an incorrect path creating the content reference, instead of /server-group=server-group-name it should be /server-group=server-group-name/deployment=deployment-name. The use of that address is incorrect; if a server group deployment is later removed, then the HC content repository won't be deleted until the HC is reloaded. 
Additionally, added debug trace to follow up the current references of the local content repository, that could help …

[WFCORE-4519] Fix content references management when a deployment is replaced

---

elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java

This is just a small optimisation to reuse a result we are guaranteed to want to use at least once more, if not many times more.
https://issues.jboss.org/browse/WFCORE-4498

[WFCORE-4498] Only obtain the Provider[] once and re-use it.

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4539
Incorporates:
* [MSC-245] Proper fix for ServiceContainerImpl.registry is leaking memory resources

[WFCORE-4539] Upgrade JBoss MSC to 1.4.8.Final

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosHttpMgmtSaslTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosNativeMgmtSaslTestCase.java

https://issues.jboss.org/browse/WFCORE-4538

[WFCORE-4538] Disabling SSL & SASL failing tests for now on JDK13+

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4533
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-255'>LOGMGR-255</a>] -         PeriodicRotatingFileHandler doesn&#39;t rotate log content when using Compression
</li>
</ul>
Please note the 2.1.12.Final release was pushed to Nexus, but was released on the wrong branch which is why it was skipped.

[WFCORE-4533] Upgrade jboss-logmanager from 2.1.11.Final to 2.1.13.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/AcmeAccountService.java
elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
elytron/src/main/java/org/wildfly/extension/elytron/CertificateAuthorityAccountDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/CertificateAuthorityDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-8.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml

This is a follow up PR due to a bug in the GitHub UI https://github.com/wildfly/wildfly-core/pull/3768 - although is no conflict the GitHub UI is unable to regenerate the diff correctly.
Jira issues:
https://issues.jboss.org/browse/WFCORE-4362
https://issues.jboss.org/browse/EAP7-1150
This also contains the Elytron subsystem version bump included in #3777
To pass CI, this will require an Elytron upgrade but this is ready for the subsystem changes to be reviewed.
Requires ELY-1797
Elytron PR: wildfly-security/wildfly-elytron#1280
Capabilities PR: wildfly/wildfly-capabilities#33
documentation PR: wildfly/wildfly#12262

[WFCORE-4362] Make the certificate authority used by a certificate-authority-account configurable

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4546
Release Notes - WildFly Elytron - Version 1.10.0.CR2
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1800'>ELY-1800</a>] -         Enhanced mapping of X509Certificate to the underlying identity
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1830'>ELY-1830</a>] -         Release WildFly Elytron 1.10.0.CR2
</li>
</ul>

[WFCORE-4546] Upgrade WildFly Elytron to 1.10.0.CR2

---

elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/DomainService.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser4_0.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/EvidenceDecoderDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
elytron/src/test/java/org/wildfly/extension/elytron/CustomEvidenceDecoder.java
elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-8.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml

Follow up from https://github.com/wildfly/wildfly-core/pull/3808 resolving merge conflict.
https://issues.jboss.org/browse/WFCORE-4361
https://issues.jboss.org/browse/EAP7-1173
This also contains the Elytron subsystem version bump included in #3777
To pass CI, this will require an Elytron upgrade but this is ready for the subsystem changes to be reviewed.
Analysis document: wildfly/wildfly-proposals#203
Capabilities PR: wildfly/wildfly-capabilities#34
WildFly PR: wildfly/wildfly#12352
Depends on wildfly-security/wildfly-elytron#1294

[WFCORE-4361] Add evidence decoders in the Elytron subsystem

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4566
Release Notes - WildFly Elytron - Version 1.10.0.CR3
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1844'>ELY-1844</a>] -         Upgrade Commons CLI to version 1.4
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-816'>ELY-816</a>] -         Support for masked passwords in client XML config
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-867'>ELY-867</a>] -         Masked password support cryptography usage
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1839'>ELY-1839</a>] -         The schemas are in the wrong location
</li>
</ul>
</h2>
<ul>
<li>[<a …

[WFCORE-4566] Upgrade WildFly Elytron to 1.10.0.CR3

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CliEmbedServerInProcessTestCase.java

https://issues.jboss.org/browse/WFCORE-4550
Note this can be combined with #3843 or will need to be created as a PR and merged after.
@jfdenise I've moved and renamed the `CliEmbeddedServerTestCase` from the standalone test suite to the manualmode test suite as I don't see the reason for the server to be started for these tests as they start an embedded server. Does that seem reasonable to you?

[WFCORE-4550] Create a test to validate the console data from a CLI embedded server reload

---

controller/src/main/java/org/jboss/as/controller/management/BaseHttpInterfaceResourceDefinition.java

The same handler is used to write and read, in case of reads, the model was being retrieved for an update, which acquired the model controller lock unnecessarily.
This patch changes the read of the attribute to use `readResource` instead of `readResourceForUpdate`
Jira issue: https://issues.jboss.org/browse/WFCORE-4557

[WFCORE-4557] Do not acquire the write lock to read http-upgrade-enabled attribute

---

server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java

The commit here fixes the issue reported in https://issues.jboss.org/browse/WFCORE-4560. 
This fix however is more of a workaround to what seems like a (reproducible) issue in JBoss MSC, where the service registry returns null when it is queried by a "provided" name. This results in the `ManagementInterfaceAddStepHandler` failing in its `verify` step here https://github.com/wildfly/wildfly-core/blob/master/controller/src/main/java/org/jboss/as/controller/management/ManagementInterfaceAddStepHandler.java#L85 due to the "missing" service.
I don't have an easy way to add a test for this, but my manual testing with this change, against a patched WildFly instance, for the use case reported in that thread, worked fine.

WFCORE-4560 Allow management interface to be able to use a https socket binding

---

elytron/src/main/java/org/wildfly/extension/elytron/TrivialAddHandler.java

This patch follows up https://github.com/wildfly/wildfly-core/pull/3729
With this patch we are also covering the case, not only when we are configuring Elytron in an embedded server already started, but also, removing the `!context.isBooting()` check, when the embedded server starts from a configuration that activates Elytron services that do not have all the dependencies up at that moment.
I used the existing Jira issue since this was a mistake on that issue.
Jira issue: https://issues.jboss.org/browse/WFCORE-4407
To sum up, before https://github.com/wildfly/wildfly-core/pull/3729 we were unable to do this configuration:
```
embed-server --server-config=standalone-full-ha.xml --std-out=echo
batch
/subsystem=security/security-domain=test-sec-domain:add(cache-type=default) …
```

[WFCORE-4407] Allow TrivialAddHandler applying the initial service mode when the embedded server is starting

---

server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java

The commit here fixes the issue noted in https://issues.jboss.org/browse/WFCORE-4572, by using the correct bind address while creating a `ListenerRegistry.Listener` instance for `https` socket binding.

Fix WFCORE-4572 

---

elytron/src/main/java/org/wildfly/extension/elytron/DefaultAuthenticationContextService.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java

We currently automatically associate this with the class loader of every deployment but we don't register it globally meaning any internal services that also need the default such as XA recovery don't have access to it.
https://issues.jboss.org/browse/WFCORE-4569

[WFCORE-4569] Ensure the AuthenticationContext is also registered as the JVM wide default.

---

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/OperationSlaveStepHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/PrepareStepHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationsResolverHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/StartServersHandler.java
testsuite/domain/pom.xml
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
testsuite/domain/src/test/resources/byteman-scripts/DelayServerRegistrationAndRunningState.btm
testsuite/domain/src/test/resources/host-configs/host-slave-main-three-without-jvm.xml
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java

This patch reduces the time where the HC boot flag is set, so read operations on the HC can success. That helps HAL to be able to display the HC slave nodes and its servers when the servers are still starting after botting up the HC.
There are additional tweaks to do in HAL to allow the console work with domains with non-patched HC servers. @hpehl Maybe you could link this PR with the one required for HAL.
Jira issue: https://issues.jboss.org/browse/WFCORE-4283

[WFCORE-4283] Move the starting of HC servers after cleaning the HC booting flag

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4577
Release Notes - WildFly Elytron - Version 1.10.0.CR4
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1843'>ELY-1843</a>] -         The Digest NonceManager creates a ScheduledThreadPoolExecutor which is never shut down
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1847'>ELY-1847</a>] -         WildFlyElytronProvider Loading wrong class for Bearer
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1849'>ELY-1849</a>] -         WildFlyElytronSaslDigestProvider does not register necessary password factories
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1841'>ELY-1841</a>] -         Update the pre-recorded messages in AcmeClientSpiTest using the latest Boulder …

[WFCORE-4577] Upgrade WildFly Elytron to 1.10.0.CR4

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4590
---
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-258'>LOGMGR-258</a>] -         Safeguard doPrivileged calls by a SecurityManager is null check
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-256'>LOGMGR-256</a>] -         Failure to rotate logfile on Windows system because of already open file lock
</li>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-259'>LOGMGR-259</a>] -         Named filters throw an IllegalArgumentException if they are embedded in an expression
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-257'>LOGMGR-257</a>] -         Create an error manager which asserts some behavior for tests
</li> …

[WFCORE-4590] Upgrade jboss-logmanager from 2.1.13.Final 2.1.14.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4579
---
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/JBLOGGING-140'>JBLOGGING-140</a>] -         Avoid ClassCastException in Slf4jLoggerProvider
</li>
<li>[<a href='https://issues.jboss.org/browse/JBLOGGING-141'>JBLOGGING-141</a>] -         At Logger.getMessageLogger, safeguard the doPrivileged call by a SecurityManager check
</li>
</ul>

[WFCORE-4579] Upgrade jboss-logging from 3.4.0.Final to 3.4.1.Final

---

remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java

Test is failing intermittently on WildFly CI (success rate < 95%)
JIRA: https://issues.jboss.org/browse/WFCORE-4604

[WFCORE-4604] Disable testEndpointConfigurationViaSubsystemRoot

---

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationContextAssociationProcessor.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

This was previously cached in a static, which does not work for
multiple deployments. This uses an empty authentication context
for the default (if it was not explicitly set), then explicitly
sets per-deployment ClassLoader defaults if the relevant file is
present in the deployment.

WFCORE-4599 Handle wildfly-config.xml better for authentication

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentReplaceHandler.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java

* Taking the runtime-name into account when replacing 2 deployments.
Jira: https://issues.jboss.org/browse/WFCORE-4603

[WFCORE-4603]: Replace Deployment --runtime-name option not working.

---

server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java

Spec module services for external modules were not being tracked by the container stability monitor checked after the management operations. Rarely, this was throwing missing service errors.
Using PhaseContext service target we are ensuring the spec services are tracked and then the stability monitor will wait for them until their start.
Jira issue: https://issues.jboss.org/browse/WFCORE-4597

[WFCORE-4597] Use PhaseContext target to start external module spec services being tracked by the stability monitor

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4620
Release Notes - WildFly Elytron - Version 1.10.0.CR5
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1712'>ELY-1712</a>] -         Enhanced Audit Logging - RFC support and Configuring Reconnects
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1804'>ELY-1804</a>] -         Support loading attributes from multiple security realms
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1854'>ELY-1854</a>] -         Add the ability to specify whether or not the AccessControlContext should be captured by using a system property called &quot;wildfly.elytron.capture.access.control.context&quot;
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1855'>ELY-1855</a>] - …

[WFCORE-4620] Upgrade WildFly Elytron to 1.10.0.CR5

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java

Wildfly core changes to allow the uses of an external folder as a module that can be added as a dependency for a deployment.
Basically, it uses an exiting service that creates a module from an external jar file expanding the functionality to scan a directory and create a module spec using all the Jar files found in that directory and subdirectories.
This feature should be still on hold since it is being blocked by https://issues.jboss.org/browse/WFCORE-4597, however, after discussing it, I open the issue to get some early feedback about the feature implementation.
Jira issue: https://issues.jboss.org/browse/WFCORE-4375

[WFCORE-4375] Provide ability to easily apply certain JBoss module libraries to all deployments running in a server

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4634
Release Notes - WildFly Elytron - Version 1.10.0.CR6
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1829'>ELY-1829</a>] -         Need to use principal-transformer in aggregate-realm in between authentication-realm and authorization-realm
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1862'>ELY-1862</a>] -         Fix infinite loop in SecurityEventVisitor#handleSyslogAuditEvent
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1864'>ELY-1864</a>] -         UDP reconnect should not endlessly loop and attempt to resend the message
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1865'>ELY-1865</a>] -         Release …

[WFCORE-4634] Upgrade WildFly Elytron to 1.10.0.CR6

---

server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
server/src/test/java/org/jboss/as/server/moduleservice/PathComparatorTestCase.java

This PR follows up https://github.com/wildfly/wildfly-core/pull/3890, currently is dead code in wildfly core needed by https://github.com/wildfly/wildfly/pull/12489
@tremes and I were chatting today about this and arrived at the conclusion of implementing this specific order loading the jar files. This PR is necessary to make the QE test pass without any additional modification.
@jamezp @bstansberry
This arrives with a bit of delay, but maybe, since it is code that is not being used currently, it could be merged today.
Jira issue: https://issues.jboss.org/browse/WFCORE-4375

[WFCORE-4375] Implement a different comparator loading the jar files

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4638
https://issues.jboss.org/browse/WFCORE-4639
Release Notes - WildFly Elytron - Version 1.10.0.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1870'>ELY-1870</a>] -         Upgrade dependencies to match WildFly Core
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1871'>ELY-1871</a>] -         Release WildFly Elytron 1.10.0.Final
</li>
</ul>
Release Notes - Elytron Web - Version 1.6.0.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELYWEB-63'>ELYWEB-63</a>] -         Upgrade WildFly Elytron to 1.10.0.Final
</li>
<li>[<a href='https://issues.jboss.org/browse/ELYWEB-64'>ELYWEB-64</a>] -         Bring the dependency versions …

[WFCORE-4368] / [WFCORE-4369] WildFly Elytron Component Upgrades

---

elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java

https://issues.jboss.org/browse/WFCORE-4623
Refactoring IdentityOperationsTestCase tests to make them more similar to other tests to see if that has an impact on the intermittent failures

[WFCORE-4623] Intermittent failures in IdentityOperationsTestCase

---

pom.xml

https://issues.jboss.org/projects/WFCORE/issues/WFCORE-4647
Release Notes - WildFly Elytron - Version 1.10.1.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1868'>ELY-1868</a>] -         Fix the infinite reconnect attempts test case for udp syslog audit logging
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1873'>ELY-1873</a>] -         JaccDelegatingPolicy should allow non JACC modifications to pass through.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1867'>ELY-1867</a>] -         Update the syslog audit endpoint to use the current reconnect attempts in the infinite case
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1875'>ELY-1875</a>] -         Release …

[WFCORE-4647] Upgrade WildFly Elytron to 1.10.1.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

https://issues.jboss.org/browse/WFCORE-4659
This is reversion of part of the WFCORE-4599 where global static auth
context was disabled to be set to empty and it was expected
every component will manage the context on its own.
That makes troubles for transaction recovery as it has no such context
and it depended on the the global one workaround.
For the time being this change is to get the workaround to work again
but the proper fix should follow.
/CC @stuartwdouglas @darranl

[WFCORE-4659] reverting change of not defining the static auth context

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4677
The only code change in this release is the following change to use a doPrivileged when required using the StackWalker APIs on Java 11: -
https://github.com/wildfly-security/wildfly-elytron/commit/8b2a9664f901f241004364837ac4aa256f5d08bf

[WFCORE-4677] Upgrade WildFly Elytron to 1.10.3.Final

---

logging/pom.xml
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnHttpTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
testsuite/shared/src/main/java/org/wildfly/test/jmx/JMXListenerDeploymentSetupTask.java

https://issues.jboss.org/browse/WFCORE-4686
https://issues.jboss.org/browse/WFCORE-4690
The commit for [WFCORE-4687](https://issues.jboss.org/browse/WFCORE-4687) just ignores checking the of the GC log until [WFCORE-4688](https://issues.jboss.org/browse/WFCORE-4688) is resolved.
This passed the full test suite locally for me with:
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

Fix Test Suite to Work with Eclipse OpenJ9

---

pom.xml

Jira: https://issues.jboss.org/browse/WFCORE-4689
This is a follow up on JBEAP Jira https://issues.jboss.org/browse/JBEAP-17475 (it does not solve the original problem, but it fixes the configuration of MAX_OUTBOUND_CHANNELS and MAX_INBOUND_CHANNELS in remoting, an issue that was discovered during the investigation of JBEAP-17475) 
Release Notes - JBoss Remoting (3+) - Version 5.0.16.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/REM3-348'>REM3-348</a>] -         Make remoting build in JDK11
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/REM3-346'>REM3-346</a>] -         Remote channels config for max outbound and inbound channels must be equal to min value of both ends
</li>
</ul>

[WFCORE-4689] Upgrade jboss remoting to 5.0.16.Final

---

pom.xml
server/src/main/java/org/jboss/as/server/deployment/Phase.java

Fixes WFCORE-4681, in support of WFLY-12313

[WFCORE-4681] Add MP OpenAPI constants; bump Jandex to current release

---

pom.xml
testsuite/embedded/pom.xml

https://issues.jboss.org/browse/WFCORE-4679
If this mock-server-netty upgrade is a problem, then an alternative approach to getting rid of the annoying vulnerability warns is to fix the logback version to 1.2.3 in the root pom dependencyManagement.

[WFCORE-4679] Update the mock-server-netty dep; specify the logback dep

---

cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java

jboss-cli can read only ISO 8859-1 properties files via --properties arg
this patch fix it

use default charset for cli --properties file

---

pom.xml

JIRA: https://issues.jboss.org/browse/WFCORE-4691
----
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/XNIO-328'>XNIO-328</a>] -         Thread allocation hash can result in only allocating to 50% of IO threads
</li>
<li>[<a href='https://issues.jboss.org/browse/XNIO-350'>XNIO-350</a>] -         xnio.nio.alt-queued-server breaks undertow ssl under load
</li>
<li>[<a href='https://issues.jboss.org/browse/XNIO-351'>XNIO-351</a>] -         Queued executor (v2) can accept into the wrong thread
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/XNIO-343'>XNIO-343</a>] -         Upgrade wildfly-common to 1.5.1.Final
</li>
</ul>
</h2>
<ul>
<li>[<a …

[WFCORE-4691] Upgrade XNIO 3.7.5.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4705
https://issues.jboss.org/browse/WFCORE-4706
Release Notes - WildFly Elytron - Version 1.11.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1885'>ELY-1885</a>] -         Component Version Maintenance
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1886'>ELY-1886</a>] -         Switch to the JBoss / Jakarta Fork for JACC
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1887'>ELY-1887</a>] -         Switch to the JBoss / Jakarta fork for JASPI
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1889'>ELY-1889</a>] -         Release WildFly Elytron 1.11.0.CR1
</li>
</ul>
Release Notes - Elytron Web - Version 1.7.0.CR1
<h2>        Component …

[WFCORE-4705] / [WFCORE-4706] WildFly Elytron Component Upgrades

---

elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java

SecurityCommandsTestCase and SyslogAuditLogTestCase cleanup
https://issues.jboss.org/browse/WFCORE-4701
- SyslogAuditLogTestCase: unused field and method
- SecurityCommandsTestCase: simplified assert thanks to `if (useCaAccount) {` statement on line 229 
https://github.com/wildfly/wildfly-core/blob/master/testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java#L229

WFCORE-4701 SecurityCommandsTestCase and SyslogAuditLogTestCase cleanup

---

pom.xml

Jira: https://issues.jboss.org/browse/WFCORE-4709
Release notes:
Release Notes - Undertow - Version 2.0.27.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1606'>UNDERTOW-1606</a>] -         Output undertow version logging at INFO level on Undertow#start() and Undertow#stop()
</li>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1607'>UNDERTOW-1607</a>] -         Add a test for ByteRange
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1576'>UNDERTOW-1576</a>] -         EMBARGOED - BASIC auth password is output as plain text at DEBUG level logging in BasicAuthenticationMechanism
</li>
<li>[<a href='https://issues.jboss.org/browse/UNDERTOW-1595'>UNDERTOW-1595</a>] - …

[WFCORE-4709] Upgrade Undertow to 2.0.27.Final

---

elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java

https://issues.jboss.org/browse/WFCORE-4723

[WFCORE-4723] Remove 'testZeroReconnectAttemptsBadHost' test as using a bad address for UDP is unreliable.

---

pom.xml

This PR follows up on https://github.com/wildfly/wildfly-core/pull/3995.
It adds javax.inject:javax.inject to the banned dependency list. 
Jira issue: https://issues.jboss.org/browse/WFCORE-4728
FYI @darranl

[WFCORE-4728] Add javax.inject as a banned dependency

---

core-feature-pack/src/main/resources/content/bin/common.ps1
core-feature-pack/src/main/resources/content/bin/standalone.bat
core-feature-pack/src/main/resources/content/bin/standalone.sh
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java

https://issues.jboss.org/browse/WFCORE-4688
- OpenJ9 Linux: https://ci.wildfly.org/viewLog.html?buildId=172762&buildTypeId=WildFlyCore_MasterLinuxOpenJ911
- OpenJ9 Windows: https://ci.wildfly.org/viewLog.html?buildId=172764&buildTypeId=WildFlyCore_MasterWindowsOpenJ911

[WFCORE-4688] Support OpenJ9 GC logging in the standalone scripts.

---

server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java

JIRA: https://issues.jboss.org/browse/WFCORE-4475
@jmesnil could you review this please? I based this on fix for https://issues.jboss.org/browse/WFCORE-3268, but I'm not sure I check the right resource roots on subdeployments.
I've got a WiP test case for the issue in https://github.com/wildfly/wildfly/compare/master...spyrkob:WFCORE-4475

 [WFCORE-4475] jboss-deployment-structure.xml with fails to parse when annotations=true on a sub-deployment module

---

pom.xml

Speaking to @jamezp we were not sure if this would need to target the 10.0.x branch so submitting just in case.
https://issues.jboss.org/browse/WFCORE-4743
Release Notes - WildFly Elytron - Version 1.10.4.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1872'>ELY-1872</a>] -         elytron-tool.sh usage with symbolic links
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1895'>ELY-1895</a>] -         SyslogAuditEndpointTest Failing on later Kernel version
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1899'>ELY-1899</a>] -         Release WildFly Elytron 1.10.4.Final
</li>
</ul>

[WFCORE-4743] Upgrade WildFly Elytron to 1.10.4.Final

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

I found PARSE_TLD_DEPLOYMENT and PARSE_WEB_COMPONENTS were not being used currently, however, they were being used before in Jboss AS 7, I have recovered them updating its priority according to the priorities required by Undertow DUPS:
https://github.com/wildfly/wildfly/blob/master/undertow/src/main/java/org/wildfly/extension/undertow/UndertowSubsystemAdd.java#L135
The other phases are new.
A following up issue on WildFly will be created once we have this one available in WildFly.
Jira issue: https://issues.jboss.org/browse/WFCORE-4744

[WFCORE-4744] Add Phase priorities used by Undertow DUPs

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4295
Incorporates:
* [JBVFS-207] Provide a way to retrieve VirtualFile instance from url.openConnection()

[WFCORE-4295] Upgrading JBoss VFS to 3.2.15.Final

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4751
https://issues.jboss.org/browse/WFCORE-4752
Release Notes - WildFly Elytron - Version 1.11.0.CR2
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1901'>ELY-1901</a>] -         Upgrade JBoss Modules to 1.9.2.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1866'>ELY-1866</a>] -         Broken symbolic link to LICENSE.txt
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1874'>ELY-1874</a>] -         Fix for checking max-cert-path specified in X509RevocationTrustManager
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1876'>ELY-1876</a>] -         Log messages are not logged when KeyStoreCredentialStore is initialized with Provider[]  in …

[WFCORE-4751] / [WFCORE-4752] WildFly Elytron Component Upgrades

---

pom.xml

This update brings in the following fixes:
- MODULES-395 The ModuleSpec builder does not make honor to the builder API documentation without adding AllPermissions by default
- MODULES-392 java.se module doesn't take into account all modules that it "requires"
Jira issue: https://issues.jboss.org/browse/WFCORE-4753
@ropalka This upgrade is necessary for https://github.com/wildfly/wildfly/pull/12489, if you agree with it, could you approve on your side? thanks!

[WFCORE-4753] Upgrade JBoss Modules from 1.9.1.Final to 1.9.2.Final

---

controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/LocalHostControllerInfoImpl.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/RenameHostControllerTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/base/AbstractCliTestBase.java

LocalHostControllerInfoImpl stores information about the environment of the local host controller. When a  Host Controller is reloaded, the current host controller name is kept to allow the embedded host controller to work with fictitious names that are not finally persisted in the host.xml. See https://issues.jboss.org/browse/WFCORE-2933 for more information
The problem is the LocalHostControllerInfoImpl#overrideLocalHostName flag is never cleared when a new name is read from the host.xml. That means, when we rename a host controller and later we reload it, the old name is still taken. This patch fixes this situation.
Jira issue: https://issues.jboss.org/browse/WFCORE-4733

[WFCORE-4733] Rename a Host Controller does not work properly

---

patching/src/main/java/org/jboss/as/patching/management/ElementProviderAttributeReadHandler.java
patching/src/main/java/org/jboss/as/patching/management/PatchAttributeReadHandler.java
patching/src/main/java/org/jboss/as/patching/management/PatchStreamResourceOperationStepHandler.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java

The read operation should not acquire the write lock, I haven't found a useful use case where this could be necessary. This patch prevents that HAL could get stuck clicking on Patching when there is already a write operation in progress.
Jira issue: https://issues.jboss.org/browse/WFCORE-4596

[WFCORE-4596] Do not acquire the write lock reading core-service patching resource

---

core-galleon-pack/wildfly-feature-pack-build.xml
pom.xml

Upgrade to the latest Galleon and WildFly Galleon Plugins that at the moment are at 4.2.1.Final.
https://issues.jboss.org/browse/WFCORE-4759

[WFCORE-4759] Upgrade to Galleon and WFGP 4.2.1.Final

---

io/subsystem/src/main/java/org/wildfly/extension/io/logging/IOLogger.java

Jira issue: https://issues.jboss.org/browse/WFCORE-4768
It's a silly change about the messages for the auto-configured values in the IO subsystem. Current messages seems to be confusing for users. We are using now a more similar similar words to the ones present in the CLI option (`io-threads` => `XX IO threads` and `task-max-threads` => `XX max task threads`). The main problem seems to be the core instead IO. I asked Brad to decide the final message, but if you prefer something different just let me know.

[WFCORE-4768] WFLYIO001: Worker 'default' has auto-configured to 24 core threads should be IO threads

---

pom.xml

https://issues.jboss.org/browse/WFCORE-4769
Release Notes - WildFly Elytron - Version 1.11.0.CR3
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1853'>ELY-1853</a>] -         WS integration with WildFly Elytron - AuthenticationClient for Authentication / SSL
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1908'>ELY-1908</a>] -         Typo in SimpleSecurityEventFormatter
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1900'>ELY-1900</a>] -         Add version 1.5 of the Elytron client schema
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1903'>ELY-1903</a>] -         Emit SecurityEvent when RealmUnavailableException is thrown
</li>
</ul> …

[WFCORE-4769] Upgrade WildFly Elytron to 1.11.0.CR3

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/management/ManagementInterfaceAddStepHandler.java

Addition of an additional error message: -
https://issues.jboss.org/browse/WFCORE-4766
I haven't added loads of detail to the message as in general this is a situation that should not occur but as discovered recently if it does occur we don't log anything to provide a starting point.  With this message we can see the starting point more clearly and at least know where to attach the debugger.

[WFCORE-4766] Report error if triggering rollback due to missing services.

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java

https://issues.jboss.org/browse/WFCORE-2356

[WFCORE-2356] Failure in a step ResultHandler should not always be reported as occurring during rollback

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4771
Release Notes - Elytron Web - Version 1.7.0.CR3
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-80'>ELYWEB-80</a>] -         Upgrade Undertow to 2.0.28.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-81'>ELYWEB-81</a>] -         Upgrade JOSE JWT to 8.2.1
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-83'>ELYWEB-83</a>] -         Upgrade WildFly Elytron to 1.11.0.CR3
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-79'>ELYWEB-79</a>] -         For a root deployment the context-path should be empty string not &quot;/&quot;
</li>
</ul>
</h2>
<ul>
<li>[<a …

[WFCORE-4771] Upgrade Elytron Web to 1.7.0.CR3

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4773
Release Notes - WildFly OpenSSL - Version 1.0.9.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-15'>WFSSL-15</a>] -         Enabling one-way ssl using elytron with key length &lt; 2048 returns non user friendly error message
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-19'>WFSSL-19</a>] -         Implementation of SSLSession returns wrong peer principal
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-23'>WFSSL-23</a>] -         Do not use static opensslv.h for version checking
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-20'>WFSSL-20</a>] -         OpenSSLEngine JDK9 compatibility
</li>
<li>[<a …

[WFCORE-4773] Upgrade WildFly OpenSSL to 1.0.9.Final

---

embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java

Issue: https://issues.redhat.com/browse/WFCORE-4776
Avoid NPE by returning in cases where we don't have a server env and status is normal.

Fix for WFCORE-4776, NPE in EmbeddedServer for version/help arguments

---

controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java

We could have capabilities with circular requirements, e.g. an attribute that adds a capability reference from a parent capability to a child capability when the child capability already requires its parent.
In those cases, when the server is in restart-required and the capability to check is not the one that was recorded as restart-required, a stack overflow exception is thrown.
Jira issue: https://issues.redhat.com/browse/WFCORE-4774

[WFCORE-4774] Avoid circular recursion searching for capability status

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4783
        Release Notes - WildFly Elytron - Version 1.11.0.CR4
        
<h2>        Component Upgrade
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1914'>ELY-1914</a>] -         Upgrade org.jboss.logging tools to 2.2.1.Final
</li>
</ul>
                                                                                                        
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1831'>ELY-1831</a>] -         When manipulating a store the password should only be prompted for once.
</li>
</ul>
        
<h2>        Task
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1884'>ELY-1884</a>] -         Add new elytron-jwt module with SmallRye and MP JWT dependencies
</li>
</ul>
          …

[WFCORE-4783] Upgrade WildFly Elytron to 1.11.0.CR4

---

pom.xml

I believe Flavia was intending to go for JBoss Remoting 5.0.17.Final here https://github.com/wildfly/wildfly-core/pull/4042

[WFCORE-4777] Upgrade JBoss Remoting to 5.0.17.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4784
Release Notes - Undertow - Version 2.0.29.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1616'>UNDERTOW-1616</a>] -         Avoid unnecessary reflection in setUseCipherSuitesOrder now that java8 is required
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1570'>UNDERTOW-1570</a>] -         Websocket messages lost when ClientEndpointConfig provided
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1609'>UNDERTOW-1609</a>] -         New RangeRequestTestCase.testLargeCachedResourceHandler fails on Windows
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1618'>UNDERTOW-1618</a>] - …

Upgrade Undertow to 2.0.29.Final

---

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainProcessor.java
pom.xml
server/src/main/java/org/jboss/as/server/deployment/Phase.java
server/src/main/java/org/jboss/as/server/security/VirtualDomainMarkerUtility.java

https://issues.redhat.com/browse/WFCORE-4700
The changes to WildFly Core to add support for MicroProfile JWT are relatively small.
This adds a dependency on the elytron-jwt module, however this is not used or installed as a module until WildFly.
Additional phases are added for DUPs which will be added to WildFly.
Finally an internal utility is added to define a virtual security domain to be dynamically associated with a deployment - when working with MicroProfile JWT this means configuration can be 100% bundled with the deployment without relying on central security configuration.
This PR depends on (and will fail CI) without https://github.com/wildfly-security/wildfly-elytron/pull/1358

[WFCORE-4700] Adding MicroProfile JWT

---

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpManagementConstantHeadersTestCase.java

This is a follow up PR to https://github.com/wildfly/wildfly-core/pull/4041
Added a new method to iterate the header values to check all expected values are present.
https://issues.redhat.com/browse/WFCORE-4782

[WFCORE-4782] HttpManagementConstantHeadersTestCase doesn't do assertions on headerList.contains

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4793
https://issues.redhat.com/browse/WFCORE-4794
Release Notes - WildFly Elytron - Version 1.11.0.CR5
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1706'>ELY-1706</a>] -         Add support for TLS 1.3
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1754'>ELY-1754</a>] -         Update test for JDK cipher suites cover when TLS 1.3 support is added
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1918'>ELY-1918</a>] -         Release WildFly Elytron 1.11.0.CR5
</li>
</ul>
Release Notes - Elytron Web - Version 1.7.0.CR4
</h2>
<ul>
<li>[<a …

[WFCORE-4793] / [WFCORE-4794] WildFly Elytron Component Upgrades

---

cli/src/main/java/org/jboss/as/cli/Util.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ServerSSLContext.java
elytron/pom.xml
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser9_0.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_9_0.xsd
elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-9.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-8.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml
pom.xml

https://issues.jboss.org/browse/WFCORE-4172
https://issues.jboss.org/browse/WFCORE-4391
https://issues.jboss.org/browse/EAP7-1022
This also contains the Elytron subsystem version bump included in #3777
To pass CI, this will require an Elytron upgrade but this is ready for the subsystem changes to be reviewed.
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/148
WildFly PR with documentation and test updates: https://github.com/wildfly/wildfly/pull/12361
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1295
Also depends on https://issues.jboss.org/browse/WFWIP-160

 [WFCORE-4172] Add support for TLS 1.3

---

security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
server/src/main/java/org/jboss/as/server/deployment/Attachments.java
server/src/main/java/org/jboss/as/server/deployment/module/ExpressionStreamReaderDelegate.java

Enables the property replacements in permissions.xml and jboss-permissions.xml by using a Function passed by wildfly. This function will contain the resolved. We use a function there since all the java classes and code for the resolver resides in wildfly instead of core. 
An alternative approach to avoid pass a function could have been to move all the required dependencies from wildfly to wildfly core, however, the approach of using a function carries fewer modifications and it is enough. 
This is an RFE, tests will be added in wildfly.
Jira issue: https://issues.jboss.org/browse/WFCORE-2147

[WFCORE-2147] Enable property replacements for permissions and jboss-permissions files

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4810
Release Notes - WildFly Elytron - Version 1.11.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1920'>ELY-1920</a>] -         Upgrade Smallrye JWT to 2.0.12
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1922'>ELY-1922</a>] -         Upgrade BouncyCastle to 1.64
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1923'>ELY-1923</a>] -         NPE in AuthenticationConfiguration.toString()
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1924'>ELY-1924</a>] -         EntityTest Failing on OpenJ9
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1925'>ELY-1925</a>] -         Release WildFly Elytron …

[WFCORE-4810] Upgrade WildFly Elytron to 1.11.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4802
This is used within the testsuite and within the server the only module to depend upon it is "org.eclipse.jgit"

[WFCORE-4802] Upgrade httpcomponents httpclient to 4.5.11 and httpcore to 4.4.13.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4818
Release Notes - WildFly Elytron - Version 1.11.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1926'>ELY-1926</a>] -         Move wildfly-elytron-password-impl dependency in client from test scope to compile scope
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1927'>ELY-1927</a>] -         Release WildFly Elytron 1.11.2.Final
</li>
</ul>

[WFCORE-4818] Upgrade WildFly Elytron to 1.11.2.Final

---

host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/OperationCoordinatorStepHandler.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CompositeOperationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/SlowServiceActivator.java

Currently, when a composite operation that is targetted to a single host is being routed via two-phase operation handler, the write lock is acquired in the Domain Controller, even if we also return the routing as a non-multiphase.
In order to facilitate the tasks of the web console reading resources under this scenario, this patch removes the lock acquisition for these operations.
My understanding:
The write lock is acquired to prevent changes in the topology. Under the scenario for this patch, an operation targeting a single slave host, only a change removing the slave could affect to the results if we are not acquiring the write lock. Removing a slave could be as a cause of:
1. User action, the user has requested a host shutdown or reload.
2. The host process crashed and was removed …

[WFCORE-4809] Do not acquire the Dc write lock for composite operations targeting to a single host

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-4823
This upgrade allows to advertise when invalid exclusion of layers occurs.

Fix for WFCORE-4823, Upgrade to Galleon 4.2.4

---

cli/src/main/java/org/jboss/as/cli/impl/BootScriptInvoker.java
cli/src/main/java/org/jboss/as/cli/impl/_private/BootScriptInvokerLogger.java
cli/src/test/java/org/jboss/as/cli/impl/BootScriptInvokerTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-4831
Exception must be thrown if an error has been written to the error file.

Fix for WFCORE-4831, CLI boot, exception not thrown when error printed to error file

---

process-controller/src/main/java/org/jboss/as/process/CommandLineArgumentUsage.java

Fix for: https://issues.redhat.com/browse/WFCORE-4844
Add a new method to CommandLineArgumentUsage for custom usage.

Fix for WFCORE-4844, CommandLineArgumentUsage custom usage

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-4838

[WFCORE-4838] Upgrade slf4j-jboss-logmanager from 1.0.3.GA to 1.0.4.GA

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4824
This update brings in the following fixes and enhancements:
* [MODULES-377] Getting 'IllegalArgumentException: moduleLoader is null' when iterating modules and module.xml contains a permissions markup
* [MODULES-378] Resource in modules.xml that references a directory link ignored when loading a resource bundle with ModuleClassLoader
* [MODULES-393] Make jboss-modules a Java agent and allow other agents to be set as module arguments
* [MODULES-397] Eliminate deprecated -addindex , -modify , -logmodule command line options
* [MODULES-398] Deprecate -jaxpmodule command line option

[WFCORE-4824] Upgrade JBoss Modules from 1.9.2.Final to 1.10.0.Final

---

elytron/pom.xml
pom.xml

[WFCORE-4850] : https://issues.redhat.com/browse/WFCORE-4850
Updating mockserver. Exclusion of a dependency from xom.io7m .

Updating mockserver. Exclusion of dependency from xom.io7m

---

server/src/main/java/org/jboss/as/server/Main.java

This is just to avoid NPE traces printing the usage if git configuration values are incorrect.
Jira issue: https://issues.redhat.com/browse/WFCORE-4862

[WFCORE-4862] Return ServerEnvironmentStatus.ERROR in case of incorrect git server start argument values

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4825
Release notes:
Release Notes - Undertow - Version 2.0.30.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1464'>UNDERTOW-1464</a>] -         Matrix parameters are not properly handled
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1492'>UNDERTOW-1492</a>] -         Respect rfc7230 section-3.3.2
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1611'>UNDERTOW-1611</a>] -         Potential Bug in ProxyPoolConnection in case of unresolvable hostname
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1623'>UNDERTOW-1623</a>] -         Undertow Deadlock
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1629'>UNDERTOW-1629</a>] - …

[WFCORE-4825] Upgrade Undertow to 2.0.30.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4865
Release Notes - Remoting JMX - Version 3.0.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REMJMX-166'>REMJMX-166</a>] -         IllegalThreadStateException after idle jmx connection
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REMJMX-169'>REMJMX-169</a>] -         Release Remoting JMX 3.0.4.Final
</li>
</ul>

[WFCORE-4865] Upgrade Remoting JMX to 3.0.4.Final

---

core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailability.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailabilityService.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
domain-http/interface/src/test/java/org/jboss/as/domain/http/server/ConsoleAvailabilityUnitTestCase.java
domain-http/interface/src/test/java/org/jboss/as/domain/http/server/TestModelControllerService.java
host-controller/pom.xml
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
server/src/main/java/org/jboss/as/server/ApplicationServerService.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java

Basically it adds a service that can be used to check the web console availability and callers can use it to enable it before the DC has transitioned to running.
I temporarily open it as a draft since it will require review HAL with this in.
Jira issue: https://issues.redhat.com/browse/WFCORE-4764

[WFCORE-4764] Enable web console just before starting the managed server when the domain controller is booting up

---

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
domain-management/src/test/java/org/jboss/as/domain/management/security/SecurityRealmServiceUtilTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-4803
Test Issue: https://issues.redhat.com/browse/WFLY-12999
Test PR: https://github.com/wildfly/wildfly/pull/12936
Although there is a test in WFCORE the `SaslLegacyMechanismConfigurationTestCase` in WFLY is also modified to include a DIGEST-MD5 test.

[WFCORE-4803] EJB Client authentication does not work using SASL DIGEST-MD5 and EXTERNAL mechanisms in Legacy security

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4864
This is preferred to #4090 if it passes CI.

[WFCORE-4864] Bump jackson-databind from 2.9.10.1 to 2.10.1

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4878
Release Notes - WildFly OpenSSL - Version 1.0.10.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-21'>WFSSL-21</a>] -         The &#39;enabled-protocols&#39; value in legacy security is not respected if OpenSSL security provider is in use
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-25'>WFSSL-25</a>] -         Don&#39;t use vsnprintf to format messages
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-27'>WFSSL-27</a>] -         Use memmove instead of memcpy
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-30'>WFSSL-30</a>] -         Release WildFly OpenSSL 1.0.10.Final
</li>
</ul>

[WFCORE-4878] Upgrade WildFly OpenSSL to 1.0.10.Final

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorResource.java

This PR allows Remoting subsystem connector elements to be referenced by a common capability reference.
For details, see: https://issues.redhat.com/browse/WFCORE-4875

[WFCORE-4875] Provide common capability for Remoting connectors.

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4881
Release Notes - XNIO - Version 3.8.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-362'>XNIO-362</a>] -         Upgrade XNIO Dependencies
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-258'>XNIO-258</a>] -         No indication of &quot;too many open files&quot; problem in the logs / error messages
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-348'>XNIO-348</a>] -         Enhance XNIO error logging for notifier failure
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-357'>XNIO-357</a>] -         Channels.flushBlocking does not have an overload with a timeout
</li>
<li>[<a …

[WFCORE-4881] Upgrade XNIO to 3.8.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4653
I don't think this is urgent. The lib is available in MRRC so I filed this.

[WFCORE-4653] Upgrade picketbox to 5.0.3.Final-redhat-00005

---

pom.xml

Reverts wildfly/wildfly-core#4092
WildFly Core does not include MRRC in its repository list so we shouldn't use -redhat versions.

Revert "[WFCORE-4653] Upgrade picketbox to 5.0.3.Final-redhat-00005"

---

cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcess.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcessImpl.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java

Expose the current process state to the client and instead of polling for the process state by using management operations, use the exposed value to return when the process state is not starting.
Jira issue: https://issues.redhat.com/browse/WFCORE-4893

[WFCORE-4893] Expose the process state from the embedded server and controller

---

testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java

This avoids HttpClient authentication which depends upon commons-codec.
https://issues.redhat.com/browse/WFCORE-4903

[WFCORE-4903] Manually set BASIC authentication header. 

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4878
master PR: https://github.com/wildfly/wildfly-core/pull/4098

[11.0.x] [WFCORE-4878] Upgrade WildFly OpenSSL to 1.0.10.Final

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-4912
Galleon changes since 4.2.4.Final: https://github.com/wildfly/galleon/compare/4.2.4.Final...wildfly:4.2.5.Final
Galleon plugins changes since 4.2.4.Final: https://github.com/wildfly/galleon-plugins/compare/wildfly-provisioning-parent-4.2.4.Final...wildfly:4.2.6.Final

Fix for WFCORE-4912, Upgrade galleon to 4.2.5.Final

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java

This PR corrects the GAV versions for Wildfly Core in the helper class ModelTestControllerVersion.
For details, see:    https://issues.redhat.com/browse/WFCORE-4909

[WFCORE-4909] Correct GAV versions in ModelTestControllerVersion

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java

This PR corrects the GAV versions for Wildfly Core in the helper class ModelTestControllerVersion.
For details, see: https://issues.redhat.com/browse/WFCORE-4925

[WFCORE-4925] Correct GAV versions in ModelTestControllerVersion

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-4940
---
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/DMR-47'>DMR-47</a>] -         Unicode JSON parsing problem if buffer needs to be filled or whitespace is used in strings
</li>
</ul>

[WFCORE-4940] Upgrade JBoss DMR 1.5.1.Final

---

elytron/pom.xml

org.wildfly.core:wildfly-controller-client is a dependency of
wildfly-elytron-integration. There is no need to duplicate it with a
test scope.

[WFCORE-4943] Remove duplicate dependency to controller-client in wildfly-elytron-integration

---

cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcessImpl.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java

Rollbacks the changes done in https://github.com/wildfly/wildfly-core/pull/4119 for the embedded server and fix the hang reading the process state for the embedded host controller
Jira issue: https://issues.redhat.com/browse/WFCORE-4922

[WFCORE-4922] Fix possible hang starting the embedded host and server

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorResource.java

This PR allows Remoting subsystem connector elements to be referenced by a common capability reference.
For details, see: https://issues.redhat.com/browse/WFCORE-4905

[WFCORE-4905] Provide common capability for Remoting connectors.

---

server/src/main/resources/schema/wildfly-config_13_0.xsd

Issue: https://issues.redhat.com/browse/WFCORE-4882 
Broken 'domain.xml' after migration of <host-scoped-roles> leading to 'Boostrap error' in HAL. 
A broken domain configuration
```
<host-scoped-roles>
<role name="custom-role-name" base-role="Administrator">
</role>
</host-scoped-roles>
```
This broken configuration doesn't bother the old HAL, so user only see the issue from HAL after the migration.
The correct one should be:
```
<host-scoped-roles>
<role name="dbaish" base-role="Administrator">
<host name="master"/>
</role>
</host-scoped-roles>
```
https://github.com/wildfly/wildfly-core/blob/11.0.0.Final/server/src/main/resources/schema/wildfly-config_9_0.xsd#L4567 show minOccurs="1"
~~Attribute `host` list should be required, thus a server boot error can be logged during migration~~ …

WFCORE-4882 correct minOccurts value for host element in XSD

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorResource.java

Reverts wildfly/wildfly-core#4132
Sorry did not see this was against 11.0.x - the original PR should have been against master.

Revert "[WFCORE-4905] Provide common capability for Remoting connectors."

---

pom.xml

1.1.x PR: https://github.com/wildfly/wildfly-core/pull/4168
Jira: https://issues.redhat.com/browse/WFCORE-4934
Release Notes - Undertow - Version 2.1.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1675'>UNDERTOW-1675</a>] -         Upgrade Undertow Dependencies
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-649'>UNDERTOW-649</a>] -         XNIO should only configure the SSLContext and Engine if configuration options are provided.
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1672'>UNDERTOW-1672</a>] -         Unable to find the resource: /META-INF/BenchmarkList 
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1699'>UNDERTOW-1699</a>] - …

[WFCORE-4934] Upgrade Undertow to 2.1.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4946
https://issues.redhat.com/browse/WFCORE-4947
Release Notes - WildFly Elytron - Version 1.11.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1945'>ELY-1945</a>] -         Authentication vulnerable to session fixation attacks
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1954'>ELY-1954</a>] -         Submission for &quot;j_security_check&quot; login does not work if URL has no trailing slash
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1957'>ELY-1957</a>] -         Release WildFly Elytron 1.11.4.Final
</li>
</ul>
Release Notes - Elytron Web - Version 1.7.1.Final
</h2>
<ul>
<li>[<a …

[WFCORE-4946] / [WFCORE-4947] Elytron Component Upgrades

---

pom.xml

This experimental PR reverts the revert of https://issues.redhat.com/browse/WFCORE-4653 and adds the necessary maven.repository.redhat.com repository needed to allow it to work.
This is just to test as avoiding the use of MRRC would be good.

Restore WFCORE-4653

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java

Additionally, prepare the EAP 7.2.0 variants to be used by wildfly-legacy-test
Jira issue: https://issues.redhat.com/browse/WFCORE-4958

[WFCORE-4958] Create the ModelTestModelControllerService variants for the EAP 7.3.0 controllers

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4953
The included feature request is pre-checked, however it will be handled under PR https://github.com/wildfly/wildfly-core/pull/4024 after this component upgrade is merged.
Release Notes - WildFly Elytron - Version 1.12.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1931'>ELY-1931</a>] -         Upgrade SmallRye JWT to 2.0.13
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1943'>ELY-1943</a>] -         Upgrade WildFly Common 1.5.4.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1894'>ELY-1894</a>] -         Make IP address of remote EJB client accessible to the developer from within app authentication code
</li>
</ul>
<h2> …

[WFCORE-4953] Upgrade WildFly Elytron to 1.12.0.CR1

---

core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
pom.xml

Add EAP 7.3.0 controllers for EAP 7.3.0 transforming tests.
Jira issue: https://issues.redhat.com/browse/WFCORE-4954

[WFCORE-4954] Add legacy controller for EAP 7.3

---

request-controller/src/main/java/org/wildfly/extension/requestcontroller/ControlPointTask.java
request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java

JIRA: https://issues.redhat.com/browse/WFCORE-4949
The proposed fix allows the caller of request controller to have access to the original task submitted to the request controller, in order to gain more context data that is otherwise hidden by the wrapper Runnable used in request controller `QueuedTask`.
This change is needed for fixing
WFLY-13357 Execution of concurrent batch jobs containg partitioned steps causes deadlock

WFCORE-4949 Expose the original task in RequestController.QueuedTask

---

bootable-jar/boot/pom.xml
bootable-jar/pom.xml
bootable-jar/runtime/pom.xml

Versions got state after merging. This throws an error building wildfly-core.
Jira issue: https://issues.redhat.com/browse/WFCORE-4895
FYI @jmesnil

[WFCORE-4895] Fix bootable jar maven module versions

---

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfacePKCS12TestCase.java
testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/config/realm/RealmKeystore.java

Fix for https://issues.redhat.com/browse/WFCORE-4965.
Just setting the correct references but duplicating a test to check a ssl security-realm configuration with PKCS12 certificates too.

[WFCORE-4965] Error loading a PKCS12 keystore inside a security-realm when using a credential-reference

---

elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/DomainService.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser10_0.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
elytron/src/main/java/org/wildfly/extension/elytron/RoleDecoderDefinitions.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_10_0.xsd
elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-10.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
elytron/src/test/resources/org/wildfly/extension/elytron/users-roles.properties
testsuite/elytron/configure-elytron.cli
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AuthenticationWithSourceAddressRoleDecoderMatchTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AuthenticationWithSourceAddressRoleDecoderMismatchTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AggregateRoleDecoder.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimplePermissionMapper.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleSecurityDomain.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SourceAddressRoleDecoder.java

https://issues.jboss.org/browse/WFCORE-4725
To pass CI, this will require both an Elytron upgrade and a Remoting upgrade but this is ready for the subsystem changes to be reviewed.
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/254
WildFly PR with tests and documentation updates: https://github.com/wildfly/wildfly/pull/12825
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/1355
Depends on https://github.com/jboss-remoting/jboss-remoting/pull/225
Depends on https://github.com/wildfly/wildfly-core/pull/4018

[WFCORE-4725] Add the ability to make use of the IP address of a remote client when making authorization decisions

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4968
https://github.com/wildfly-security/wildfly-elytron/compare/1.12.0.CR1...1.12.0.CR2
Release Notes - WildFly Elytron - Version 1.12.0.CR2
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1961'>ELY-1961</a>] -         Upgrade jboss-logmanager to 2.1.15.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1962'>ELY-1962</a>] -         Upgrade JBoss Threads to 2.3.4.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1952'>ELY-1952</a>] -         SSLConfigurator ignores some of the SSLParameters passed in via setSSLParameters method
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1953'>ELY-1953</a>] -         Elytron tool command execution …

[WFCORE-4968] Upgrade to WildFly Elytron 1.12.0.CR2

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4942
(fixes CVE-2020-10719)
Release Notes - Undertow - Version 2.1.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1710'>UNDERTOW-1710</a>] -         Upgrade Netty to 4.1.50.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1706'>UNDERTOW-1706</a>] -         Maven Enforcer Rule Dependency Convergency fails for Undertow 2.1.0.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1197'>UNDERTOW-1197</a>] -         Response not reused when processing async request
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1419'>UNDERTOW-1419</a>] -         bumpTimeout method usage in …

[WFCORE-4942] Upgrade Undertow to 2.1.1.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4969
Release Notes - XNIO - Version 3.8.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-372'>XNIO-372</a>] -         NPE happens on ByteBufferSlicePool.clean() for non-direct buffers
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-374'>XNIO-374</a>] -         ByteBufferSlicePool FREE_DIRECT_BUFFERS is always empty
</li>
</ul>

[WFCORE-4969] Upgrade XNIO to 3.8.1.Final

---

core-feature-pack/feature-pack-build.xml
core-feature-pack/pom.xml
core-feature-pack/src/license/core-feature-pack-licenses.xml
core-galleon-pack/pom.xml
core-galleon-pack/src/main/resources/packages/org.wildfly.openssl/pm/wildfly/tasks.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-4966
https://issues.redhat.com/browse/WFCORE-4730
Note the minor version bump just indicates the evolution of the wildfly-openssl build process.
Release Notes - WildFly OpenSSL - Version 1.1.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-31'>WFSSL-31</a>] -         Add the ability to make use of the &#39;jboss.modules.os-name&#39; property when building on RHEL platforms
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-33'>WFSSL-33</a>] -         Release WildFly OpenSSL 1.1.0.Final
</li>
</ul>

[WFCORE-4966] / [WFCORE-4730] Upgrade WildFly OpenSSL to 1.1.0.Final and include the linux-s390x binding

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4971
https://github.com/wildfly-security/wildfly-elytron/compare/1.12.0.CR2...1.12.0.CR3
Release Notes - WildFly Elytron - Version 1.12.0.CR3
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1909'>ELY-1909</a>] -         Introduce regex mapper for security roles in Elytron
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1967'>ELY-1967</a>] -         Release WildFly Elytron 1.12.0.CR3
</li>
</ul>

[WFCORE-4971] Upgrade WildFly Elytron to 1.12.0.CR3

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
elytron/src/main/java/org/wildfly/extension/elytron/RegexAttributeDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_10_0.xsd
elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/groups.properties
elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
elytron/src/test/resources/org/wildfly/extension/elytron/role-mappers-test.xml
elytron/src/test/resources/org/wildfly/extension/elytron/users-clear.properties
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/RegexRoleMapperTest.java

Jira: [WFCORE-4750](https://issues.jboss.org/browse/WFCORE-4750)
Requires [ELY-1909](https://issues.jboss.org/browse/ELY-1909)

[WFCORE-4750] Using regex for role in Elytron

---

protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/ElytronModelControllerClientTestCase.java

https://issues.redhat.com/browse/WFCORE-4976

[WFCORE-4976] Ensure the supplied CallbackHandler is used for the username, password, and realm.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4986
https://github.com/wildfly-security/wildfly-elytron/compare/1.12.0.CR3...1.12.0.Final
Release Notes - WildFly Elytron - Version 1.12.0.CR4
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1968'>ELY-1968</a>] -         Update error message returned by AcmeClientSpi#getLocation
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1973'>ELY-1973</a>] -         Release WildFly Elytron 1.12.0.Final
</li>
</ul>

[WFCORE-4986] Upgrade WildFly Elytron to 1.12.0.Final

---

domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionManagerService.java
domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java

Issue: https://issues.redhat.com/browse/WFCORE-4950
Test PR in wildfly: https://github.com/wildfly/wildfly/pull/13249
Fix for WFCORE-4950. The final problem is a ClassNotFoundException of the class "com.sun.jndi.ldap.LdapCtxFactory" from module "org.wildfly.extension.io". So I added "sun.jdk" to that module. If you see something better to do just let me know. 
Tested with ibm jdk -8 too (just in case).
Tests included in issue WFLY-13358, I'll attach the PR for wildfly asap.

[WFCORE-4950] Regression: Legacy Ldap Realm securing EJB with JDK8 not working

---

pom.xml

Takes the component commit from https://github.com/wildfly/wildfly-core/pull/4131
@jamezp FYI I have just pulled out your component upgrade commit, this still keeps coming up on the components upgrade report.  For WildFly Core we are quite on top of that report.

[WFCORE-4899] Upgrade jboss-modules to 1.10.1.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4988
Release Notes - Undertow - Version 2.1.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1713'>UNDERTOW-1713</a>] -         Calling isReady may start async IO too early
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1716'>UNDERTOW-1716</a>] -         Allow colon in the request cookie value regardless of setting ALLOW_HTTP_SEPARATORS_IN_V0
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1717'>UNDERTOW-1717</a>] -         Return 416 Range Not Satisfiable when first-byte-pos of Range request header is equal to the content-length
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1719'>UNDERTOW-1719</a>] -         Handling of path parameters can set incorrect …

[WFCORE-4988] Upgrade Undertow to 2.1.2.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-4990
Release Notes - Undertow - Version 2.1.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1726'>UNDERTOW-1726</a>] -         Check Java version in the JDK9AlpnProvider
</li>
</ul>

[WFCORE-4990] Upgrade Undertow to 2.1.3.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4989
https://github.com/wildfly-security/wildfly-elytron/compare/1.12.0.Final...1.12.1.Final
Release Notes - WildFly Elytron - Version 1.12.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1979'>ELY-1979</a>] -         Elytron needs to deal with JEPS 244 in the org.wildfly.security.ssl package
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1981'>ELY-1981</a>] -         SSL Module missing plugin configuration to assemble multi-version jar
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1980'>ELY-1980</a>] -         Release WildFly Elytron 1.12.1.Final
</li>
</ul>

[WFCORE-4989] Upgrade WildFly Elytron to 1.12.1.Final

---

pom.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/LoggingServiceActivator.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/handlers/RotatingFileHandlerTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/AbstractRotatingFileHandlerTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/PeriodicSizeRotatingFileHandlerTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/SizeRotatingFileHandlerTestCase.java

The second commit are tests for https://issues.redhat.com/browse/LOGMGR-277. The deployment is required to trigger a rotation with the security manager running to test this issue. We could skip the tests when the security manager is not present, however the tests ran fast enough that I wasn't too concerned with.
https://issues.redhat.com/browse/WFCORE-4991
https://issues.redhat.com/browse/WFCORE-4992
<h1>Release Notes for JBoss Log Manager - Version 2.1.16.Final</h1>
<hr />
<h2>Bug</h2>
<ul>
<li>[ <a href="https://issues.redhat.com/browse/LOGMGR-209">LOGMGR-209</a> ] NoSuchAlgorithmException in SocketHandlerTests on IBM JDK</li>
<li>[ <a href="https://issues.redhat.com/browse/LOGMGR-276">LOGMGR-276</a> ] NPE is triggered if an previous error occur in rollOver</li>
<li>[ <a …

[WFCORE-4991] Upgrade jboss-logmanager from 2.1.15.Final to 2.1.16.Final.

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-4996

[WFCORE-4996] Upgrade WildFly Galleon Plugins from 4.2.6.Final to 4.2.8.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5001
Release Notes - WildFly Elytron - Version 1.13.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1970'>ELY-1970</a>] -         The service descriptors in the wildfly-elytron module do not correctly combine the other modules.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1974'>ELY-1974</a>] -         Correct class names in ProviderFactory
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1976'>ELY-1976</a>] -         Elytron provider not being used with credential store and SASL authentication on the Client Side
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1975'>ELY-1975</a>] -         Update AcmeClientSpi#obtainCertificate so that it obtains the …

[WFCORE-5001] Upgrade WildFly Elytron to 1.13.0.CR1

---

core-feature-pack/pom.xml
core-feature-pack/src/license/core-feature-pack-licenses.xml
core-galleon-pack/pom.xml

artifact wildfly-jar-boot jar is not present in WildFly distribution
JIRA: https://issues.redhat.com/browse/WFCORE-5011

[WFCORE-5011] Remove wildfly-jar-boot license

---

testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java

This PR does the following:
- adds host name information to HostController start and started log messages to allow differentiating between multiple HostController instances on the same host, which often arises in domain test cases. 
More details: https://issues.redhat.com/browse/WFCORE-5006

[WFCORE-5006] Improve readability of domain host controller server logs in tests

---

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/SSLTruststoreUtil.java

Issue: https://issues.redhat.com/browse/WFCORE-944
I just used @darranl 's fix (https://github.com/wildfly/wildfly-core/pull/3841) but a manual test that used PKCS12 was modified to include this use-case. Indeed the test is better now. Previously the provider was not specified in the configuration (server-identity/ssl or authentication/truststore) and that seems to work in openjdk but fails in other implementations (IBM for example). So we are killing two birds with one stone.

[WFCORE-944] truststore path is ignored if provider is not JKS

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java

https://issues.redhat.com/browse/WFCORE-5004

[WFCORE-5004] TlsTestCase#testReloadTrustManager fails on IBM Java 8

---

testsuite/embedded/pom.xml

This component is only used when the embedded test suite is run.
JIRA: https://issues.redhat.com/browse/WFCORE-5034

[WFCORE-5034] Upgrade log4j to 2.13.3

---

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java

https://issues.redhat.com/browse/WFCORE-4973

[WFCORE-4973] Increasing LongOutputTestCase timeout from 10 to 20 seconds

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
controller/src/test/java/org/jboss/as/controller/test/ReadResourceWithRuntimeResourceTestCase.java

https://issues.jboss.org/browse/WFCORE-3682
`Stage.Runtime` failure description does not roll back to final response in `Stage.Model` for read-resource operation with `include-runtime` flag.
This attaches failure description into context in case process is rolling back, and adds it to outermost `DefaultPrepareStepHandler` response in case its failure description is undefined after rolling back.

[WFCORE-3682] try to add other stage failure description in a RollbackHandler from context attachment.

---

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/AuthenticationWithSourceAddressRoleDecoderMatchTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/AuthenticationWithSourceAddressRoleDecoderMismatchTestCase.java

https://issues.redhat.com/browse/WFCORE-5007
To pass CI, this will require an Elytron upgrade that contains https://github.com/wildfly-security/wildfly-elytron/pull/1415 but this can be reviewed in the meantime.

[WFCORE-5007] Make use of the SocketAddressCallbackServerMechanismFactory to set the peer address during HTTP authentication

---

pom.xml
testsuite/elytron/pom.xml
testsuite/rbac/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5059
Upgraded plugin release, updated tests plugin configuration to use cli-sessions.

Fix for WFCORE-5059, Upgrade bootable testsuite to use 2.0.0.Alpha6 maven plugin

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5050
Release Notes - WildFly OpenSSL - Version 1.1.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-34'>WFSSL-34</a>] -         libwfssl is not detected by EAP automatically -&gt; cannot use OpenSSL security provider
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-35'>WFSSL-35</a>] -         Release WildFly OpenSSL 1.1.1.Final
</li>
</ul>

[WFCORE-5050] Upgrade WildFly OpenSSL to 1.1.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-4863
Branch: https://github.com/jbossas/redhat-picketbox/tree/5.0.x
Diff: https://github.com/jbossas/redhat-picketbox/compare/5.0.3.Final-16-g4e49f86c...5.0.3.Final-18-g76744137

[WFCORE-4863] Upgrade PicketBox from 5.0.3.Final-redhat-00005 to 5.0.3.Final-redhat-00006

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/SecurityMetaDataProcessor.java
elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainNameProcessor.java
server/src/main/java/org/jboss/as/server/deployment/Phase.java
server/src/main/java/org/jboss/as/server/security/SecurityMetaData.java

A WildFly PR will follow for the WildFly side of the changes but this initial change is required within WildFly Core first.
https://issues.redhat.com/browse/WFCORE-4962
https://issues.redhat.com/browse/WFCORE-4963
https://issues.redhat.com/browse/WFCORE-4981
Overall the intent is to transition to a point a complete security policy is defined before entering Phase.INSTALL so all DUP installation activities can refer to a common policy that has been collaboratively established without repeating resolution activities (possibly with different results) in different subsystems.
One remaining issue is the web services deployment unit processors don't convert the deployment to a web application until later in the INSTALL phase, other than for web services Phase.INSTALL_WEB_RESOLVE_SECURITY_DOMAIN …

[WFCORE-4962] / [WFCORE-4963] / [WFCORE-4981] DUP Refactoring to share service name of resolved SecurityDomain.

---

domain-management/src/main/java/org/jboss/as/domain/management/security/FileTrustManagerService.java

Issue: https://issues.redhat.com/browse/WFCORE-5064
Just changing to use the correct default trust-manager algorithm defined at JDK level (right now it's using the KeyManagerFactory default, the default value `SunX509` also exists for TrustManagerFactory and it's valid). I'm not adding any tests because the final https availability for the realm is tested for example in HTTPSManagementInterfaceTestCase. We can add a test similar to the steps I added to reproduce it in the JIRA if you really think it is needed.

[WFCORE-5064] Incorrect use of KeyManagerFactory.getDefaultAlgorithm instead of TrustManagerFactory

---

server/src/main/java/org/jboss/as/server/deployment/transformation/DeploymentTransformer.java

Issue: https://issues.redhat.com/browse/WFCORE-5071
@wildfly/mergers-full Issue with WFCORE-5065 make the build fail because of the check-style. Just removing that line.

[WFCORE-5071] Extra spaces in DeploymentTransformer.java produces error at build

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5057
Tag: https://github.com/jbossas/jboss-threads/releases/tag/2.4.0.Final
Diff: https://github.com/jbossas/jboss-threads/compare/2.3.6.Final...2.4.0.Final

[WFCORE-5057] Upgrade jboss-threads to 2.4.0.Final

---

elytron/pom.xml
pom.xml
testsuite/standalone/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5023
It's just a downgrade of the mock-server to 5.8.1 and adding the BC dependency (test scope) to all the places that the mock-server is used. I also upgraded the BC to the same version that wildfly-elytron is using right now. BC and mock-server are only used for testing. This way the mock-server issue is solved and it works using IBM jdk and openjdk8 and 11 (`KeyStoresTestCase.java` still fails with IBM but it's the same issue than in WFCORE-5004, we need a follow-up issue for that test, but I didn't want to mix both things in the same PR). 
If you prefer any other approach just let me know. @fjuma is aware of this change, maybe she can review the PR.

[WFCORE-5023] A few tests don't work using IBM JDK because of mock-server 5.9.0

---

.github/workflows/stale.yml

This is a test workflow for closing stale PRs. A comment is left after 30 days indicating there has been no activity, and the PR is closed after 90 with no activity. It is based on the github supplied action here: https://github.com/actions/starter-workflows/blob/main/automation/stale.yml
(No JIRA, yet, this is more for discussion.)

Add workflow action for closing stale PRs

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5074
Release Notes - JBoss Modules - Version 1.10.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/MODULES-400'>MODULES-400</a>] -         Automatically set the os.name if the -Djboss.modules.os-name property has not already been specified when running on RHEL platforms
</li>
</ul>

[WFCORE-5074] Upgrade JBoss Modules to 1.10.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5075
Release Notes - WildFly OpenSSL - Version 1.1.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-39'>WFSSL-39</a>] -         Update the OS-version-specific category that&#39;s added to the native search path to match the format used by JBoss Modules
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-40'>WFSSL-40</a>] -         Update the directory names that are used for the RHEL natives
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-41'>WFSSL-41</a>] -         Release WildFly OpenSSL 1.1.2.Final
</li>
</ul>

[WFCORE-5075] Upgrade WildFly OpenSSL to 1.1.2.Final

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

Issue: https://issues.redhat.com/browse/WFLY-10879 
This adds a new phase constant required by wildfly/wildfly#11711.
Is it OK to use the WFLY issue for this or should I create a separate WFCORE ticket?

[WFLY-10879] Adding new EE deployment phase constant

---

core-feature-pack/galleon-common/src/main/resources/layers/standalone/remoting/layer-spec.xml
core-feature-pack/galleon-feature-pack/src/main/resources/layers/standalone/legacy-remoting/layer-spec.xml
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
testsuite/layers/pom.xml

https://issues.redhat.com/browse/WFCORE-5076
This is the simplest fix for the issue, a missing dependencies error is now reported:
```
17:02:54,850 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
("subsystem" => "remoting"),
("http-connector" => "http-remoting-connector")
]) - failure description: {
"WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.core.management.security.realm.OtherRealm"],
"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.remoting.remoting-http-upgrade-service.http-remoting-connector is missing [org.wildfly.core.management.security.realm.OtherRealm]"]
}
```
This service does not have it's own dependants so I don't really see a justification …

[WFCORE-5076] The "remoting-http-upgrade-service" should be ACTIVE.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5090
Release Notes - WildFly Elytron - Version 1.13.0.CR4
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2013'>ELY-2013</a>] -         Upgrade to JBoss Threads 2.4.0.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1902'>ELY-1902</a>] -         Support for multiple security realms - Failover
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1949'>ELY-1949</a>] -         Adjust Security Manager behaviour when alternative Security Manager installed.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2015'>ELY-2015</a>] -         Release WildFly Elytron 1.13.0.CR4 …

[WFCORE-5090] Upgrade WildFly Elytron to 1.13.0.CR4

---

bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/BootablePolicy.java
bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml

This approach is borrowed from JBoss Modules which follows a similar pattern of being started from a "java -jar" command before performing the rest of the bootstrap process.
https://issues.redhat.com/browse/WFCORE-5087
Unlike JBoss Modules this does not support alternative security managers as we only support WildFlySecurityManager with the running server.
The following example update makes use of the new -secmgr command line argument:
https://github.com/wildfly-extras/wildfly-jar-maven-plugin/pull/46

[WFCORE-5087] Add support for the -secmgr command line argument,

---

core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml

Issue: https://issues.redhat.com/browse/WFCORE-5100

[WFCORE-5100] Add missing distribution repo in core-feature-pack-common-licenses.xml license file

---

bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Constants.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-5097
Add a new option to bootable JAR runtime to display the galleon provisioning.xml that reflects the provisioned server. The provisioning.xml file is added by the maven plugin (starting 2.0.0.Beta2).

Fix for WFCORE-5097, Add an option to the bootable JAR to display the Galleon config

---

bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-5110
Replace JAXP factories with the proper implementations.

Fix for WFCORE-5110, Bootable JAR doesn't setup the JAXP factories at boot

---

pom.xml
subsystem-test/framework/pom.xml

https://issues.redhat.com/browse/WFCORE-5111 
This component upgrade brings in:
* [MSC-252] Removing double word of service in the thrown exception ServiceNotFoundException
* [MSC-255] Deprecating StabilityMonitor & StabilityStatistics

[WFCORE-5111] Upgrading JBoss MSC from 1.4.11.Final to 1.4.12.Final

---

bootable-jar/runtime/pom.xml
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Arguments.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableEnvironment.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Constants.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/PropertyUpdater.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Server.java
bootable-jar/runtime/src/test/java/org/wildfly/core/jar/runtime/ArgumentsTestCase.java
bootable-jar/runtime/src/test/resources/test-system.properties

- https://issues.redhat.com/browse/WFCORE-5115
- https://issues.redhat.com/browse/WFCORE-5109
Use a hard-coded boot-config.properties to load system properties in the bootable JAR entry point. This properties file is generated by the wildfly-jar-maven-plugin. It's used at boot to configure properties required by the log manager during initialization.
Minor follow up to the bootable JAR module. Actually throw the exception when a shutdown failure occurs.
Ensure the configurator is attached to the root logger. This means the logging subsystem will not reconfigure resources that do not need to be reconfigured.

Bootable JAR Logging Updates

---

pom.xml
testsuite/elytron/pom.xml
testsuite/manualmode/pom.xml
testsuite/rbac/pom.xml
testsuite/standalone/pom.xml

Issue:https://issues.redhat.com/browse/WFCORE-5112
In addition to the upgrade, the plugin configuration has been simplified, inherit-configs has been removed. inherit-packages is false by default.

Fix for WFCORE-5112, Upgrade bootable jar maven plugin to 2.0.0.Beta4

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-5119
Remove useless dependency on elytron-private.
@darranl FYI.

Fix for WFCORE-5119, Bootable JAR - Remove dependency on elytron-private

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5056
Release Notes - XNIO - Version 3.8.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-376'>XNIO-376</a>] -         Improve WorkerThreadFactory to make a created thread execute tasks on thread exits
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-378'>XNIO-378</a>] -         Throw specific exception when connection is closed early in http upgrade
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-377'>XNIO-377</a>] -         Invoke selectorThreadLocal.remove() to clean up temporary selector on task worker thread exits
</li>
</ul>

[WFCORE-5056] Upgrade XNIO to 3.8.2.Final

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
pom.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java

Note that this PR depends on the upcoming Undertow component upgrade PR.
https://issues.redhat.com/browse/WFCORE-5091 
https://issues.redhat.com/browse/WFCORE-5127
https://issues.redhat.com/browse/WFCORE-5128
Release Notes - WildFly Elytron - Version 1.13.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1921'>ELY-1921</a>] -         HTTP External Security Not Supported by Elytron
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1851'>ELY-1851</a>] -         Elytron ldaps realm fails if a referral is returned inside a search
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-1995'>ELY-1995</a>] -         AggregateRealm is failing in authentication with token-realm
</li>
</ul> …

[WFCORE-5091] / [WFCORE-5127] / [WFCORE-5128] Elytron Component Upgrades

---

pom.xml

Jira: https://issues.redhat.com/projects/WFCORE/issues/WFCORE-5102
Release Notes - Undertow - Version 2.1.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1755'>UNDERTOW-1755</a>] -         Doubled definition of :path and other HttpStrings
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1662'>UNDERTOW-1662</a>] -         [GSS][7.2.2] HTTP External Security Not Supported by Elytron
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1762'>UNDERTOW-1762</a>] -         Error page for custom exception-type is not is not displayed in jsp development mode
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1774'>UNDERTOW-1774</a>] - …

[WFCORE-5102] Upgrade Undertow to 2.2.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5123
https://issues.redhat.com/browse/WFCORE-5124
https://issues.redhat.com/browse/WFCORE-5125
Release Notes - WildFly OpenSSL - Version 2.1.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-36'>WFSSL-36</a>] -         Add jdk.min.version property and set it to JDK 11
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-47'>WFSSL-47</a>] -         Release WildFly OpenSSL 2.1.0.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-48'>WFSSL-48</a>] -         Update WildFly OpenSSL Natives to 2.1.0.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-49'>WFSSL-49</a>] -         Update the pom.xml files to add version properties for the various binaries
</li>
<li>[<a …

[WFCORE-5123] / [WFCORE-5124] / [WFCORE-5125] WildFly OpenSSL Component Upgrades

---

elytron/pom.xml
elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml

https://issues.redhat.com/browse/WFCORE-4842
https://issues.redhat.com/browse/EAP7-1414
To pass CI, this will require a WildFly OpenSSL upgrade but this is ready to be reviewed.
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/288
WildFly PR with documentation: https://github.com/wildfly/wildfly/pull/13414
Depends on: https://github.com/wildfly-security/wildfly-openssl/pull/81

[WFCORE-4842] Add tests for TLS 1.3 that make use of the OpenSSL TLS provider

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-5137
Revert of https://issues.redhat.com/browse/WFCORE-5119

Fix for WFCORE-5137, Bootable JAR - Security manager is not found

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5138
Release Notes - JBoss Remoting (3+) - Version 5.0.19.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-370'>REM3-370</a>] -         ClientConnectionOpenListener can throw BufferOverflowException when sending sasl response
</li>
</ul>

[WFCORE-5138] Upgrade JBoss Remoting to 5.0.19.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/core-management/main/module.xml
core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java
core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
testsuite/shared/src/main/java/org/wildfly/test/events/provider/TestListener.java

Issue: https://issues.redhat.com/browse/WFCORE-5118
I have added just a try/finally to add the TCCL to the one in the module specified. I have used the `WildFlySecurityManager` class to do that which needs to add that dependency in the `module.xml`. If you prefer to add a helper class or something different just let me know (I think that it's better to not repeat the code).

[WFCORE-5118] Cannot get resources from ContextClassLoader with Server Lifecycle Events

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml

* Adding missing dependency in bcpkix module.
Jira: https://issues.redhat.com/browse/WFCORE-5143
https://issues.redhat.com/browse/WFLY-13903

[WFCORE-5143]: Bouncycastle - Failing tests in RESTEasy TS.

---

pom.xml
testsuite/elytron/pom.xml
testsuite/manualmode/pom.xml
testsuite/pom.xml
testsuite/rbac/pom.xml
testsuite/standalone/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5139
Changes since last upgrade: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/2.0.0.Beta4...2.0.0.Beta8
In addition to the upgrade, the plugin version has been removed from parent pom.xml and moved in ts.bootable profile defined in testsuite/pom.xml.

Fix for WFCORE-5139, Upgrade Bootable JAR Maven plugin to 2.0.0.Beta8

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5153
Release Notes - Undertow - Version 2.2.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1788'>UNDERTOW-1788</a>] -         %r and %U in access log still output forwarded URL if forwarded URL is then dispatched to error page
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1795'>UNDERTOW-1795</a>] -         Sort both request &amp; response cookies
</li>
</ul>
Release Notes - Undertow - Version 2.2.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1796'>UNDERTOW-1796</a>] -         Change the default value of the io.undertow.protocols.alpn.jdk8 to true
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1800'>UNDERTOW-1800</a>] …

[WFCORE-5153] Upgrade Undertow to 2.2.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5152
Release Notes - WildFly Elytron - Version 1.13.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2026'>ELY-2026</a>] -         UnsupportedOperationException in SSLEngine using jdk 251+
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2027'>ELY-2027</a>] -         Release WildFly Elytron 1.13.1.Final
</li>
</ul>

[WFCORE-5152] Upgrade WildFly Elytron to 1.13.1.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java

WFCORE-5150 PolicyDefinitions#registerHandler uses double-check of the same thing
https://issues.redhat.com/browse/WFCORE-5150

WFCORE-5150 PolicyDefinitions#registerHandler uses double-check of the same thing

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5148
Release notes: https://www.bouncycastle.org/releasenotes.html

[WFCORE-5148] Upgrade Bouncy Castle to 1.66

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5165
Changes since Beta8: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/2.0.0.Beta8...2.0.1.Final

Fix for WFCORE-5165, Upgrade Bootable JAR Maven plugin to 2.0.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5176
Release Notes - WildFly OpenSSL - Version 2.1.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-56'>WFSSL-56</a>] -         Invalidate the removed session
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-58'>WFSSL-58</a>] -         Release WildFly OpenSSL 2.1.1.Final
</li>
</ul>

[WFCORE-5176] Upgrade WildFly OpenSSL to 2.1.1.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java

There may be a follow up PR as we are also discussing an API in JBoss Modules to optimise it but this covers the initial issue we have been seeing on some Java 11 installations:
https://issues.redhat.com/browse/WFCORE-5183

[WFCORE-5183] Ensure the Provider instance was loaded using a ModuleClassLoader.

---

server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/main/java/org/jboss/as/server/controller/git/ElytronClientCredentialsProvider.java
server/src/main/java/org/jboss/as/server/controller/git/ElytronClientSshdSessionFactory.java
server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java

https://issues.redhat.com/browse/WFCORE-5147
The RemoteSshGitRepositoryTestCase test case was quite unstable on a resource constrained environment, the test was dependent on monitoring the server.log for an error message but it appears the git integration may log the error in a separate thread so I believe the process can be terminated before the message is logged.
Attempting to debug the issue I realised the test case was not properly restoring the default server configuration between test as attempts to add additional logging categories were being overridden.
Finally we were not logging useful information ourselves, although log and throw can be a bad practice at the moment the uncaught exception only made it's way to System.err - the problem with this was if you are reliant on the …

[WFCORE-5147] Adjusting git integration logging and stability of RemoteSshGitRepositoryTestCase

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java

https://issues.redhat.com/browse/WFCORE-5194

[WFCORE-5194] Update TLS tests to use the SHA256withRSA signature algorithm.

---

testsuite/scripts/pom.xml

Jira with more details: https://issues.redhat.com/browse/WFCORE-5191
This PR enforce reuseForks to true in Scripts module of TS, because reuseForks=false doesn't work on Scripts module of TS

[WFCORE-5191] Enforce reuseForks to true in Scripts module of TS

---

testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java

Jira: https://issues.redhat.com/browse/WFCORE-5193
Details from the description of the jira:
So far, this IS_J9_JVM variable is defined by "java.vendor" system property:
```java
IS_J9_JVM = System.getProperty("java.vendor").contains("OpenJ9") || IS_IBM_JVM;
```
But this detection fails on Eclipse OpenJ9 VM AdoptOpenJDK (where "java.vendor" is "AdoptOpenJDK"). Which leads to the fail of JmxControlledStateNotificationsTestCase testcase in domain module on this JDK.
I suggest to add "java.vm.vendor" property to the previous detection ("java.vm.vendor" property is "Eclipse OpenJ9" on Eclipse OpenJ9 VM AdoptOpenJDK)
You can also see some CI runs on WFCORE-5193 jira.
Originally, IS_J9_JVM was introduced in https://issues.redhat.com/browse/WFCORE-4690

[WFCORE-5193] Make IS_J9_JVM variable in TS more robust

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5197
https://github.com/wildfly-security/wildfly-elytron/compare/1.13.1.Final...1.13.2.Final
Release Notes - WildFly Elytron - Version 1.13.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2023'>ELY-2023</a>] -         Elytron ClientCertAuthenticationMechanism does not work when using a web proxy
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2025'>ELY-2025</a>] -         Resource leak in ElytronXmlParser.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2028'>ELY-2028</a>] -         Resource leak in JaspiAuthenticationContext
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2029'>ELY-2029</a>] -         Checking String equality using != in SimpleDirContextFactoryBuilder
</li>
<li>[<a …

[WFCORE-5197] Upgrade WildFly Elytron to 1.13.2.Final

---

controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
controller/src/test/java/org/jboss/as/controller/parsing/ParseUtilsTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5181

[WFCORE-5181] Expression properties with trailing whitespaces are resolved to a trimmed value

---

server/src/main/resources/schema/wildfly-config_15_0.xsd

The 15.0 XSD is missing the WildFly20.0 and WildFly21.0 values in the
host-release enums while they were properly set in the Java
HostExcludeResourceDefinition.KnownRelease enum.
JIRA: https://issues.redhat.com/browse/WFCORE-5207

[WFCORE-5207] Add missing enums to host-release type

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5208
https://github.com/wildfly-security/wildfly-openssl/compare/2.1.1.Final...2.1.2.Final
Release Notes - WildFly OpenSSL - Version 2.1.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-60'>WFSSL-60</a>] -         Issues with wildfly openssl and client certificates when used on the client side
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-61'>WFSSL-61</a>] -         Avoid NPE if SSL_get_cipher returns &quot;(NONE)&quot;
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-62'>WFSSL-62</a>] -         Fix initial value for minProtocolIndex in OpenSSLEngine#setEnabledProtocols
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-64'>WFSSL-64</a>] - …

[WFCORE-5208] Upgrade WildFly OpenSSL to 2.1.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5209
https://github.com/wildfly-security/wildfly-elytron/compare/1.13.2.Final...1.14.0.Final
Release Notes - WildFly Elytron - Version 1.14.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1987'>ELY-1987</a>] -         Add the ability to adjust the case of a user name using an Elytron principal transformer
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2042'>ELY-2042</a>] -         ElytronXMLParser is not configuring maximum-cert-path in X509RevocationTrustManager
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2045'>ELY-2045</a>] -         Widespread test failures on Fedora 33 with Fedora distribution of OpenJDK 11
</li>
</ul> …

[WFCORE-5209] Upgrade WildFly Elytron to 1.14.0.Final

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-5204
Tag: https://github.com/eclipse-ee4j/injection-api/releases/tag/1.0.3
Diff to previous integrated release: https://github.com/eclipse-ee4j/injection-api/compare/1.0.1...1.0.3
The main reason is to properly set the Automatic-Module-Name to java.inject, instead of jakarta.inject

[WFCORE-5204] Upgrade jakarta.inject-api from 1.0.1 to 1.0.3

---

elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java

Issue: https://issues.redhat.com/browse/WFCORE-5151
In [ELY-1637](https://issues.redhat.com/browse/ELY-1637)/[WFCORE-3971](https://issues.redhat.com/browse/WFCORE-3971) the values for the `referral-mode` were changed to be in lower case to match the documentation and XSD. This PR is just to also change the allowed values and the default value (they now keep using `name()` instead `toString()` and are upper case). QA team filed the issue to be consistent. The real value for the attribute is case insensitive since the beginning so I think nothing more is needed (no transformer) and the change is just cosmetic.

[WFCORE-5151] dir-contexts referral-mode attribute upper/lower case discrepancy

---

request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
request-controller/src/test/java/org/wildfly/extension/requestcontroller/WFCORE4967_TestCase.java

solves: https://issues.redhat.com/browse/WFCORE-4967
findForcedTask method implementation could be improved but synchronization is fine from my point of view when server is paused anyway.

WFCORE-4967 fix: RequestController drops queued tasks randomly during server start.

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
core-feature-pack/galleon-common/src/main/resources/packages/org.wildfly.openssl/pm/wildfly/tasks.xml
core-feature-pack/legacy-feature-pack/feature-pack-build.xml
elytron/pom.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-5013
Note that a [proposal](https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/thread/7W5B2K4C2QXWBVVSZPHDBXDY3CW4JRA4/) for removing these natives was sent to the WildFly Dev mailing list a few weeks ago. We haven't received any concerns so we are going to proceed with removing them. Anyone running on these platforms who needs these natives will still be able to build and make use of them on their own. I've created a PR against WildFly that adds documentation on how to do this:
https://github.com/wildfly/wildfly/pull/13667

[WFCORE-5013] Remove the WildFly OpenSSL linux-i386, windows-i386, and solaris-x86_64 natives

---

controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFilePersistenceResource.java
controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationPersister.java
server/src/main/java/org/jboss/as/server/ServerEnvironment.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java

This PR supersedes https://github.com/wildfly/wildfly-core/pull/4104
WildFly proposal can be found here: wildfly/wildfly-proposals#304. It allows to start the server if we are using --read-only-server-config and the server configuration directory is a read-only directory. Only in that case, the history root directory falls back to the server temporal directory.
Jira issue: https://issues.redhat.com/browse/WFCORE-4135

[WFCORE-4135] Support for read only server configuration directory

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5218
Release Notes - JBoss Remoting (3+) - Version 5.0.20.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-373'>REM3-373</a>] -         Upgrade JUnit to 4.13.1
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-371'>REM3-371</a>] -         Channel is not closed when one of the peers cancels the connection
</li>
</ul>

[WFCORE-5218] Upgrade JBoss Remoting to 5.0.20.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5173
Release Notes - Undertow - Version 2.2.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1792'>UNDERTOW-1792</a>] -         ServletPrintWriter.println uses LF instead of CRLF
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1802'>UNDERTOW-1802</a>] -         Improve FormEncodedDataDefinition to handle chars in configured encoding
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1810'>UNDERTOW-1810</a>] -         Provide valid Servlet major version responses if undertow-servlet has been transformed to use jakarta.* Servlet APIs
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1821'>UNDERTOW-1821</a>] -         Keep the order of matched parameters by …

[WFCORE-5173] Upgrade Undertow to 2.2.3.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-5220
IBM JDK has classes in com.ibm.jsse and com.ibm.jsse2 that are not included in the ibm.jdk module.
This cause ClassNotFoundException if someone refer to JSSE socket factory provider in IBM JDK.

WFCORE-5220 ibm.jdk module misses jsse and jsse2 paths

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java

Issue: https://issues.redhat.com/browse/WFCORE-5206
Removed reflection calls to access ModuleLoader.installMBeanServer that is now public.

Fix for WFCORE-5206, Remove workaround to access ModuleLoader.installMBeanServer

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-5212
This PR can only be merged after https://github.com/wildfly/wildfly/pull/13744 is merged to WildFly to remove the use of this ID.

[WFCORE-5212] Remove Phase ID 'PARSE_EE_DEFAULT_BINDINGS_CONFIG' as it is replaced by 'STRUCTURE_EE_DEFAULT_BINDINGS_CONFIG'.

---

pom.xml

Issues:
https://issues.redhat.com/browse/WFCORE-5223
https://issues.redhat.com/browse/WFCORE-5227
Galleon upgrade: 
https://github.com/wildfly/galleon/compare/galleon-parent-4.2.6.Final...4.2.7.Final
Galleon-plugin upgrade to latest master than incorporates support for EE9 transformation.
https://github.com/wildfly/galleon-plugins/compare/4.2.8.Final...5.0.0.Final

Fix for WFCORE-5223 and WFCORE-5227, Galleon upgrades

---

model-test/pom.xml
pom.xml

Fixing [WFCORE-5302](https://issues.redhat.com/browse/WFCORE-5203) Updates Google Guava to 30.1-jre.
This patch will fail in integration tests, please find analysis and discussion under [https://github.com/wildfly/wildfly/pull/13788](https://github.com/wildfly/wildfly/pull/13788). This pull request supersedes 4406.
@jamezp Could you please review this PR as precondition of 13788.

WFCORE-5302 Update Google guava 30.1-jre

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5236
https://github.com/wildfly-security/wildfly-elytron/compare/1.14.0.Final...1.14.1.Final
Release Notes - WildFly Elytron - Version 1.14.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2050'>ELY-2050</a>] -         Update bouncycastle to 1.67
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2049'>ELY-2049</a>] -         Add trace capability to o.w.s.m.WildFlySecurityManager findAccessDenial
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2057'>ELY-2057</a>] -         No acceptedIssuers is sent when CRLs are configured
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2058'>ELY-2058</a>] - …

[WFCORE-5236] Upgrade WildFly Elytron to 1.14.1.Final

---

cli/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5199
Did manual testing with bootable JAR, cli fat jar (with both jakarta8 and jakarata9).

Fix for WFCORE-5199, CLI, shaded jar can't start embedded when logging json formater configured

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5244
Diff with previous release:
https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/2.0.1.Final...3.0.0.Final

Fix for WFCORE-5244, Upgrade tests to bootable JAR 3.0.0.Final

---

pom.xml

Fixes [WFCORE-5237](https://issues.redhat.com/browse/WFCORE-5237)
Please find releasenotes and diff in the Jira ticket.

[WFCORE-5237] Upgrade bouncycastle to 1.68

---

server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_16.java

fix console-enabled attribute in http interface so it is resolved as expression
https://issues.redhat.com/browse/WFCORE-5256

[WFCORE-5256] fix console-enabled attribute in http interface

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5266
https://github.com/wildfly-security/wildfly-openssl/compare/2.1.2.Final...2.1.3.Final
Release Notes - WildFly OpenSSL - Version 2.1.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-63'>WFSSL-63</a>] -         Unable to build WildFly SSL on Fedora 33
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-65'>WFSSL-65</a>] -         Issues with wildfly openssl and client certificates when used on the client side with Jetty
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-66'>WFSSL-66</a>] -         Add a new GitHub workflow to trigger CI for pull requests
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-67'>WFSSL-67</a>] -         Refactor some tests …

[WFCORE-5266] Upgrade WildFly OpenSSL to 2.1.3.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5251
Release Notes - Undertow - Version 2.2.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1406'>UNDERTOW-1406</a>] -         WebSocketClient13TestCase gets stuck with JDK-11 early build 28
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1824'>UNDERTOW-1824</a>] -         CVE-2020-27782 AJP handler must send AJP responses for bad requests &amp; internal server errors
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1827'>UNDERTOW-1827</a>] -         InMemorySessionManager must bump session timeout on requestStarted
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1828'>UNDERTOW-1828</a>] -         NullPointerException occurred if a servlet calls …

[14.x] [WFCORE-5251] Upgrade Undertow to 2.2.4.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5251
Release Notes - Undertow - Version 2.2.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1406'>UNDERTOW-1406</a>] -         WebSocketClient13TestCase gets stuck with JDK-11 early build 28
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1824'>UNDERTOW-1824</a>] -         CVE-2020-27782 AJP handler must send AJP responses for bad requests &amp; internal server errors
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1827'>UNDERTOW-1827</a>] -         InMemorySessionManager must bump session timeout on requestStarted
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1828'>UNDERTOW-1828</a>] -         NullPointerException occurred if a servlet calls …

[WFCORE-5251] Upgrade Undertow to 2.2.4.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5282
Release Notes - WildFly Elytron - Version 1.14.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2071'>ELY-2071</a>] -         Upgrade Apache DS to version AM26
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2073'>ELY-2073</a>] -         Upgrade org.apache.directory.api to version 2.0.0
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2043'>ELY-2043</a>] -         Incorrect and confusing trace message
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2053'>ELY-2053</a>] -         key-store-masked-password needs the elytron provider to be manually registered
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2069'>ELY-2069</a>] - …

[WFCORE-5282] Upgrade WildFly Elytron to 1.14.2.Final

---

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java
core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java
core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/servergroup/servergroup.xml
host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootConfiguration.java
host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_16.java
host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
process-controller/src/main/java/org/jboss/as/process/CommandLineConstants.java
server/src/main/java/org/jboss/as/server/CommandLineArgumentUsageImpl.java
server/src/main/java/org/jboss/as/server/Main.java
server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/main/java/org/jboss/as/server/ServerEnvironmentResourceDescription.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/ServerStartTask.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
server/src/main/resources/schema/wildfly-config_16_0.xsd

https://issues.redhat.com/browse/WFCORE-4291
Squashed commit of the following:
commit 874016e
Author: Brian Stansberry <brian.stansberry@redhat.com>
Date:   Mon Jul 29 13:50:48 2019 -0500
[WFCORE-4291] Basic implementation of disabling initial boot-time suspension of a server.
Change name from "graceless" to "graceful-startup" and invert intention
Add support for '--graceful-startup' command line param for server startup
Modify schema to add graceful-startup attribute to server-group for domain mode support
Modify ManagedServerBootCmdFactory to pass arg as needed to managed servers

[WFCORE-4291] Add support for non-graceful startup

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
core-feature-pack/pom.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-5290
https://issues.redhat.com/browse/WFCORE-5291
https://issues.redhat.com/browse/WFCORE-4584
Release Notes - WildFly Elytron - Version 1.15.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2068'>ELY-2068</a>] -         Upgrade to MicroProfile JWT 1.2
</li>
</ul>
<h2>        Requirement
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1842'>ELY-1842</a>] -         Update the tool to support generating and exporting / importing a secret key to the credential store
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2081'>ELY-2081</a>] -         Develop a simple properties based credential store for secret keys
</li>
<li>[<a …

[WFCORE-5290] / [WFCORE-5291] / [WFCORE-4584] Elytron Component Upgrades

---

core-feature-pack/common/src/main/resources/content/bin/add-user.bat
core-feature-pack/common/src/main/resources/content/bin/common.bat
core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/common.sh
core-feature-pack/common/src/main/resources/content/bin/domain.bat
core-feature-pack/common/src/main/resources/content/bin/elytron-tool.bat
core-feature-pack/common/src/main/resources/content/bin/elytron-tool.sh
core-feature-pack/common/src/main/resources/content/bin/jboss-cli.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.bat
core-feature-pack/common/src/main/resources/content/bin/vault.bat
testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptProcess.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/Shell.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java

https://issues.redhat.com/browse/WFCORE-5261
This adds an import for a `common.conf` file in each `common.xx` script. A placeholder file was not created as I see no need to clutter the `bin` directory. A documentation PR will be required for the WildFly docs.
Analysis Doc: https://github.com/wildfly/wildfly-proposals/pull/369
Docs and Full PR: https://github.com/wildfly/wildfly/pull/13989

[WFCORE-5261] Add the ability to use a common script configuration file.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5309
https://issues.redhat.com/browse/WFCORE-5310
Release Notes - WildFly Elytron - Version 1.15.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2090'>ELY-2090</a>] -         Evidence is not used when getting the realm mapping in ServerAuthenticationContext#assignName 
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2091'>ELY-2091</a>] -         The error message from import-secret-key on (secret-key-)credential-store should be more helpful
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2092'>ELY-2092</a>] -         Removal of credential store entry resulting in invalid alias list.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2095'>ELY-2095</a>] -         PropertiesCredentialStore …

[WFCORE-5309] / [WFCORE-5310] Elytron Component Upgrades

---

elytron/src/main/java/org/wildfly/extension/elytron/expression/ElytronExpressionResolver.java

https://issues.redhat.com/browse/WFCORE-5301

[WFCORE-5301] Use a descriptive error message if the secret key is not available from the credential store.

---

cli/src/main/java/org/jboss/as/cli/handlers/ReadAttributeHandler.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5247

WFCORE-5247 IllegalArgumentException and CLI crash with read-attribute in /system-property

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java

https://issues.redhat.com/browse/WFCORE-5226
Requires: https://issues.redhat.com/browse/ELY-2057
Elytron PR: https://github.com/wildfly-security/wildfly-elytron/pull/1473
To pass CI, this will require an Elytron upgrade.

[WFCORE-5226] No acceptedIssuers is sent when CRLs are configured

---

core-feature-pack/common/src/main/resources/content/bin/jboss-cli.sh
testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5241
[WFCORE-5241] in jboss-cli.sh enclose the JAVA_OPTS with double quote to escape whitespace

[WFCORE-5241] in jboss-cli.sh enclose the JAVA_OPTS with double quote to escape whitespace

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Arguments.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableEnvironment.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Constants.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
bootable-jar/runtime/src/test/java/org/wildfly/core/jar/runtime/ArgumentsTestCase.java
cli/src/main/java/org/jboss/as/cli/impl/BootScriptInvoker.java
cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
cli/src/main/java/org/jboss/as/cli/impl/_private/BootScriptInvokerLogger.java
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
testsuite/elytron/pom.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ifelse/BasicIfElseTestCase.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ManagementClient.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java

Issues:
https://issues.redhat.com/browse/WFCORE-5322
https://issues.redhat.com/browse/WFCORE-5323
https://issues.redhat.com/browse/WFCORE-5324
Community doc PR:
https://github.com/wildfly/wildfly/pull/14069
* Introduce --cli-script=[path to cli script]
* Fix output when error occur during CLI script execution
* Fix ability to set server log config directory
* Evolved ts.bootable profile of elytron tests with CLI configuration applied at runtime.

[WFCORE-5324] Support for CLI script executing at boot for bootable JAR

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5329
(adds OSGi support to Undertow)
**
Release Notes - Undertow - Version 2.2.5.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1845'>UNDERTOW-1845</a>] -         AbstractFramedChannel.FrameReadListener contains incomplete log when invoking listener
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1846'>UNDERTOW-1846</a>] -         Load shedding excessive handshakes
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1847'>UNDERTOW-1847</a>] -         Add script to deploy jakarta EE9 transformed artifacts
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1852'>UNDERTOW-1852</a>] - …

[WFCORE-5329] Upgrade Undertow to 2.2.5.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5327
Release Notes - WildFly Elytron - Version 1.15.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2098'>ELY-2098</a>] -         Webservices client should use currently configured and not previously configured authentication context
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2100'>ELY-2100</a>] -         Release WildFly Elytron 1.15.1.Final
</li>
</ul>

[WFCORE-5327] Upgrade WildFly Elytron to 1.15.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5349
https://github.com/wildfly-security/wildfly-elytron/compare/1.15.1.Final...1.15.2.Final
Release Notes - WildFly Elytron - Version 1.15.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2104'>ELY-2104</a>] -         two calls to introspection endpoint for one request with JWT
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2106'>ELY-2106</a>] -         Release WildFly Elytron 1.15.2.Final
</li>
</ul>

[WFCORE-5349] Upgrade to WildFly Elytron 1.15.2.Final

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java

https://issues.redhat.com/browse/WFCORE-4214

[WFCORE-4214] VaultPasswordsInCLITestCase fails with Elytron profile

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5348
Diff: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/3.0.0.Final...4.0.0.Final

Fix for WFCORE-5348, Upgrade tests to use bootable JAR 4.0.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5331
Fixes:
* [JBMAR-234] Fix JDK11 insufficient privileges issue
* [JBMAR-235] Reinitialize array in IdentityIntMap and IdentityIntSet when array size becomes large

[WFCORE-5331] Upgrading JBoss Marshalling to 2.0.11.Final

---

security-manager/src/main/java/org/wildfly/extension/security/manager/DeferredPermissionFactory.java
security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerSubsystemAdd.java
security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsValidationProcessor.java
security-manager/src/main/java/org/wildfly/extension/security/manager/logging/SecurityManagerLogger.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/secmgr/InvalidPermissionTestCase.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/secmgr/JavaVersionServiceActivator.java

Issue: https://issues.redhat.com/browse/WFCORE-5243
A new deferred factory is used because some permissions cannot be constructed at parsing time (module is not ready at that time, that's why factories are used right now for the deployment). Besides this way a better warn message can be displayed showing what set gave the error (maximum, minimum or deployment).

[WFCORE-5243] NullPointerException when invalid <permission> classes specified

---

elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

No JIRA issue was made due to it being a trivial change. I just happened to notice a typo in an error while using it and figured I'd submit a quick pull request.

Fix typo 'doe' to 'does'

---

core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
pom.xml

Supersedes https://github.com/wildfly/wildfly-core/pull/4534
This PR combines two issues:
Jira: https://issues.redhat.com/browse/WFCORE-5340
Jira: https://issues.redhat.com/browse/WFCORE-5267
It adds a EAP_7_4_0_TEMP model controller version based on WF23. We use the _TEMP suffix to force us to review and replace any uses of it when we get real 7.4.0.GA out and available for this replacement. There are some more advanced subsystem tests that specify additional maven artifacts that could need an additional review once we move out of WF23. Having a _TEMP suffix will allow us to pay attention to them once we are removing this suffix.

[WFCORE-5340][WFCORE-5267] Create model test controller version to test transformers agains EAP 7.4.0 based on WF23

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5355
Upstream PR https://github.com/wildfly/wildfly-core/pull/4543
Release Notes - WildFly Elytron - Version 1.15.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2109'>ELY-2109</a>] -         Upgrade jboss logmanager to 2.1.18.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2108'>ELY-2108</a>] -         Subject private credentials have zeroes when passed to elytron-enabled datasource
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2110'>ELY-2110</a>] -         Release WildFly Elytron 1.15.3.Final
</li>
</ul>

[15.x] [WFCORE-5355] Upgrade WildFly Elytron to 1.15.3.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5355
Release Notes - WildFly Elytron - Version 1.15.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2109'>ELY-2109</a>] -         Upgrade jboss logmanager to 2.1.18.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2108'>ELY-2108</a>] -         Subject private credentials have zeroes when passed to elytron-enabled datasource
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2110'>ELY-2110</a>] -         Release WildFly Elytron 1.15.3.Final
</li>
</ul>

[WFCORE-5355] Upgrade WildFly Elytron to 1.15.3.Final

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5354
Diff: https://github.com/wildfly/galleon/compare/4.2.7.Final...4.2.8.Final

Fix for WFCORE-5354, Upgrade galleon to 4.2.8.Final

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java

Issue: https://issues.redhat.com/browse/WFCORE-5365

Fix for WFCORE-5365, cli-script option help text is missing a placeholder

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5362
Diff: https://github.com/wildfly/galleon-plugins/compare/5.1.1.Final...5.1.2.Final

Fix for WFCORE-5362, Upgrade galleon-plugins to 5.1.2

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5363
Fixes:
* [REM3-377] Use safeClose() in ClientServiceHandle.close()

[WFCORE-5363] Upgrade JBoss Remoting to 5.0.21.Final

---

testsuite/elytron/src/test/java/org/jboss/as/test/shared/CliUtils.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AbstractConfigurableElement.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AbstractConstantHelper.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AbstractUserRolesCapableElement.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/ConstantRealmMapper.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/ConstantRoleMapper.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/DirContext.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/IdentityMapping.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/KeyStoreRealm.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/LdapRealm.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/MechanismRealmConfiguration.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/NameValue.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/OtpCredentialMapper.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleConfigurableSaslServerFactory.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleKeyManager.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleSaslAuthenticationFactory.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleTrustManager.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/UserPasswordMapper.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/UserWithRoles.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/other/ClientMapping.java

Original PR was too big to verify. It has been splitted up, here: testsuite-elytron

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (testsuite-elytron)

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/TestEnvironment.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingAppender.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingFileHandler.java

Original PR was too big to verify. It has been splitted up, here: testsuite-manualmode

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (manualmode)

---

testsuite/test-runner/pom.xml
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java

Original PR was too big to verify. It has been splitted up, here: testsuite - testrunner

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (testrunner)

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/core-security/main/module.xml
core-security/implementation/pom.xml
core-security/implementation/src/main/java/org/jboss/as/core/security/AbstractRealmPrincipal.java
core-security/implementation/src/main/java/org/jboss/as/core/security/SecurityRealmPrincipal.java

Original PR was too big to verify. It has been splitted up, here: security

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (security)

---

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiHandler.java

Original PR was too big to verify. It has been splitted up, here: domain-http

[WFCORE-5285] Utilize org.wildfly.common.Assert for Null-Checks (domainhttp)

---

domain-management/src/main/java/org/jboss/as/domain/management/security/password/simple/SimpleKeyboard.java
domain-management/src/main/java/org/jboss/as/domain/management/security/password/simple/SimplePasswordStrengthChecker.java
domain-management/src/test/java/org/jboss/as/domain/management/security/operations/CacheBuilder.java

Original PR was too big to verify. It has been splitted up, here: domainmanagement

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (domain-management)

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/security/manager/main/module.xml
security-manager/pom.xml
security-manager/src/main/java/org/wildfly/extension/security/manager/DeferredPermissionFactory.java

Original PR was too big to verify. It has been splitted up, here: securitymanager

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (securitymanager)

---

process-controller/src/main/java/org/jboss/as/process/stdin/BaseNCodecInputStream.java
process-controller/src/main/java/org/jboss/as/process/stdin/BaseNCodecOutputStream.java

Original PR was too big to verify. It has been splitted up, here: process-controller

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (process-controller)

---

server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayIndex.java

Original PR was too big to verify. It has been splitted up, here: server

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (server)

---

protocol/pom.xml
protocol/src/test/java/org/jboss/as/protocol/mgmt/support/ChannelServer.java

Original PR was too big to verify. It has been splitted up, here: protocol

[WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (protocol)

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/httpcomponents/core/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/jgit/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml

Fixes https://issues.redhat.com/browse/WFCORE-5286

[WFCORE-5286] Remove deprecated javax.api usage from modules

---

testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java

Jira: https://issues.redhat.com/browse/WFCORE-5372
Use absolute path in permissions.xml in JMX test. Relative path in permissions.xml file doesn't work on JDK11, see:
* https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8164705
* https://bugs.openjdk.java.net/browse/JDK-8165836

[WFCORE-5372] Use absolute path in permissions.xml in JMX test

---

cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java

Issue: https://issues.redhat.com/browse/WFCORE-5384
On some platform, we can enter the case where a read for input is attempted again (in the reload loop) although the console has been closed by a Ctrl-C. The closed state must be checked prior to attempt a read.

Fix for WFCORE-5384, RemoveManagementRealmTestCase tests intermittently fail

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
controller/src/main/java/org/jboss/as/controller/registry/RuntimePackageDependency.java
controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java

* Logging a warning if a runtime dependency is added several times.
* If the extension package is added as an additional runtime dependecy,
protecting the read-feature operation form this duplication.
Jira: https://issues.redhat.com/browse/WFCORE-5382

[WFCORE-5382]: The same Additional Runtime Dependency can be added several times for a single resource definition.

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authentication/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml

I am just starting off on hold whilst I complete some more steps but this should be ready to go.
Two new modules have been added to make it easier to replace them with Jakarta EE 9 implementations for WildFly Preview.
The Jakarta implementations needed a dependency on some WildFly Elytron artifacts so they have been moved to a base module allowing Jakarta EE to sit in the middle.
https://issues.redhat.com/browse/WFCORE-5389

[WFCORE-5389] Split out Jakarta Authentication and Authorization implementation modules.

---

elytron/pom.xml
pom.xml
remoting/tests/pom.xml
testbom/pom.xml
testsuite/pom.xml
testsuite/shared/pom.xml

Issue: https://issues.redhat.com/browse/WFLY-14431
That this PR does:
* Create a new module called: `testbom` which holds all test dependencies in core but are production dependencies in WildFly
* Added the dependency of `testbom` to modules that need it as `import` scope
* Move `commons-io`, `xalan`, `jackson-databind` from top level pom to `testbom/pom.xml` because they are test only dependencies in core, but they are production dependencies in WildFly.

[WFLY-14431] Do not use WildFly Core dependency management for dependencies that are test-only in core

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5414
https://issues.redhat.com/browse/WFCORE-5415
Elytron 1.15.4.Final
https://github.com/wildfly-security/wildfly-elytron/compare/1.15.3.Final...1.15.4.Final
Release Notes - WildFly Elytron - Version 1.15.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2111'>ELY-2111</a>] -         JwkManager uses incorrect non url-safe Base64 to load the jwks endpoint
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2118'>ELY-2118</a>] -         Elytron tool command execution fails with java.lang.UnsupportedOperationException on AIX OS.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2125'>ELY-2125</a>] -         Release WildFly Elytron 1.15.4.Final
</li>
</ul>
<h2> …

[WFCORE-5414] / [WFCORE-5415] WildFly Elytron and Elytron Web Upgrades

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5412
https://github.com/wildfly-security/wildfly-openssl/compare/2.1.3.Final...2.1.4.Final
Release Notes - WildFly OpenSSL - Version 2.1.4.Final
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-70'>WFSSL-70</a>] -         update license name to match SPDX license list and also Wildfly
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-71'>WFSSL-71</a>] -         OpenSSlSession.initPeerChain() fails on JDK 15+
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-73'>WFSSL-73</a>] -         OpenSSLEngine shuts down too early
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-72'>WFSSL-72</a>] -         Investigate failures in …

[WFCORE-5412] Upgrade WildFly OpenSSL to 2.1.4.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml

* Removing jgit from org.jboss.as.controller module
* Adding jgit as a dependency of org.jboss.as.server module.
Issue: https://issues.redhat.com/browse/WFCORE-5416

[WFCORE-5416]: Jgit incorrect reference in org.jboss.as.controller module.

---

pom.xml
protocol/pom.xml

Jiras
https://issues.redhat.com/browse/WFCORE-5423 (see release notes below for further info on dependency upgrade)
https://issues.redhat.com/browse/WFCORE-5424
Fixes CVE-2020-35510
Release Notes - JBoss Remoting (3+) - Version 5.0.23.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-381'>REM3-381</a>] -         Revert REM3-378 in Remoting 5.0.x
</li>
</ul>
Release Notes - JBoss Remoting (3+) - Version 5.0.22.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-379'>REM3-379</a>] -         CVE-2020-35510 Threads hold up forever in the EJB server by suppressing the ack from an EJB client
</li>
<li>[<a href='https://issues.redhat.com/browse/REM3-380'>REM3-380</a>] -         Add OutboundMessage info to messages logged by …

[WFCORE-5423][WFCORE-5424] Upgrade jboss-remoting to 5.0.23.Final and add test dependency from protocol to wildfly-elytron-security-manager

---

pom.xml

Jira: https://issues.redhat.com/browse/WFLY-14815
Requires https://github.com/wildfly/wildfly/pull/14314 (https://issues.redhat.com/browse/WFLY-14815) or else WildFly testsuite won't pass.
I'll be submitting another PR later today for WFLY-14815 with a proper fix for the tests. That PR will only pass with the Undertow upgrade.
Release Notes - Undertow - Version 2.2.7.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1837'>UNDERTOW-1837</a>] -         ServletRequest#getLocalPort(), getLocalAddr() and getLocalName() can return wrong information when ProxyPeerAddressHandler or ForwardedHandler is enabled
</li>
</ul>
Release Notes - Undertow - Version 2.2.8.Final
</h2>
<ul>
<li>[<a …

[WFCORE-5425] Upgrade Undertow to 2.2.8.Final

---

bootable-jar/boot/pom.xml
core-feature-pack/common/src/main/resources/content/bin/common.sh

Issue: https://issues.redhat.com/browse/WFCORE-5453
The set of add-opens and add-exports used in bin/common.sh launch script is added to Bootable JAR manifest file.
Having them in all cases for all JDK doesn't appear to be an issue. On JDK8, these entries are ignored.
Users can still add their own --add-opens --add-exports to the command line and both sources of options are honored.

Fix for WFCORE-5453, Include add-opens and add-exports to Bootable JAR runtime manifest

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5462

Fix for WFCORE-5462, Upgrade to Bootable JAR plugin 5.0.0.Beta1

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5396

WFCORE-5396 Remove the wildlfy-elytron-http-deprecated dependency module to no longer rely on deprecated classes

---

testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java

https://issues.redhat.com/browse/WFCORE-5457

[WFCORE-5457] Add missing permission for JmxControlledStateNotificationsTestCase on J9

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5496
Brings in:
* [MSC-256] Fix ServiceBuilder javadoc
* [MSC-257] Unregistering container's WeakReference from shutdown hook containers set on container shutdown
* [MSC-258] Use one shutdown hook per container and let JVM keep track of them

[WFCORE-5496] Upgrading JBoss MSC from 1.4.12.Final to 1.4.13.Final

---

testbom/pom.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java

Replace its use in ModuleTestCase as it was not able
to delete directory with recursive symlinks

[WFLY-5498] Upgrade commons-io to 2.10.0

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-5482

[WFCORE-5482] Bouncycastle bcpkix module requires a dependency on java logging and java.naming

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5510
Release Notes - WildFly Elytron - Version 1.16.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2137'>ELY-2137</a>] -         Possible NullPointerException in AuthenticationConfiguration
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2140'>ELY-2140</a>] -         Elytron Tool: Mask command will fail when secret is not provided.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2141'>ELY-2141</a>] -         Elytron Tool: Default platform encoding used in Command.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2142'>ELY-2142</a>] -         Elytron Tool: Default platform encoding used in VaultCommand.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2143'>ELY-2143</a>] - …

[WFCORE-5510] Upgrade WildFly Elytron to 1.16.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5510
Upstream: https://github.com/wildfly/wildfly-core/pull/4664

[16.x][WFCORE-5510] Upgrade WildFly Elytron to 1.16.1.Final

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcprov/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcutil/main/module.xml
elytron/pom.xml
pom.xml
server/pom.xml
testbom/pom.xml
testsuite/standalone/pom.xml

* [WFCORE-5461] Upgrade bouncycastle to 1.69
* JIRA https://issues.redhat.com/browse/WFCORE-5461
* `main` https://github.com/wildfly/wildfly-core/pull/4628
* [WFCORE-5480] Bouncyclastle provider module requires a dependency on java.sql and java.naming
* JIRA https://issues.redhat.com/browse/WFCORE-5480
* `main` https://github.com/wildfly/wildfly-core/pull/4648 (I just realised that the commit message references WFCORE-5495 instead of WFCORE-5480)
* WFCORE-5482 Bouncycastle bcpkix module requires a dependency on java.logging and java.naming
* JIRA https://issues.redhat.com/browse/WFCORE-5482
* `main` PR https://github.com/wildfly/wildfly-core/pull/4654

[16.x][WFCORE-5461] Upgrade bouncycastle to 1.69 + module dependencies

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5515
Diff: https://github.com/jboss-logging/log4j-jboss-logmanager/compare/1.2.0.Final...1.2.2.Final

[WFCORE-5515] Upgrade log4j-jboss-logmanager to 1.2.2.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5517
Release Notes - Undertow - Version 2.2.9.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1471'>UNDERTOW-1471</a>] -         Websocket client redirection issue using SSL
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1601'>UNDERTOW-1601</a>] -         Max request size from multipart config is applied to all requests irrespective of content type
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1842'>UNDERTOW-1842</a>] -         HTTP2SourceChannel fails to write final frame if flow control window is not big enough
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1856'>UNDERTOW-1856</a>] -         Undertow read-timeout can cause closing a connection for long …

[WFCORE-5517] Upgrade Undertow to 2.2.9.Final

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat

https://issues.redhat.com/browse/WFCORE-2592

[WFCORE-2592] Special characters escaping in service.bat

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat

https://issues.redhat.com/browse/WFCORE-2592
Addition of procrun syntax characters ( ; and # ) escaping

[WFCORE-2592] Procrun syntax characters escaping

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java

Jira issue: https://issues.redhat.com/browse/WFCORE-5528

[WFCORE-5528] Missing EAP 7.4 host exclusion as a known release

---

core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
pom.xml

Jira Issue: https://issues.redhat.com/browse/WFCORE-5347
Jira Issue: https://issues.redhat.com/browse/WFCORE-5529
Replaces the temporal WF23 model controller version used for the transformer tests and fixes its uses in Elytron tests

[WFCORE-5347][WFCORE-5529] Replace WF23 ModelTestControllerVersion by 7.4.0.GA and correct it on Elytron transformer tests

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-debian.sh
core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh

https://issues.redhat.com/browse/WFCORE-5516

[WFCORE-5516] If JBOSS_BASE_DIR variable is empty -Djboss.server.base.dir is not added in wildfly-init-redhat.sh and wildfly-init-debian.sh scripts.

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5541
Release Notes - Undertow - Version 2.2.10.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1929'>UNDERTOW-1929</a>] -         Several tests fail with SocketTimeoutException: Read timed out
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1940'>UNDERTOW-1940</a>] -         BindException Address already in use in SSL tests
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1941'>UNDERTOW-1941</a>] -         At Http2ClientTestCase prevent suppressing of original failure by NPE in afterClass
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1946'>UNDERTOW-1946</a>] -         DefaultServletCachingListenerTestCase.testWelcomePages fails sporadically with File was …

[WFCORE-5541] Upgrade Undertow to 2.2.10.Final

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java

Follow up on https://issues.redhat.com/browse/WFLY-15061

Deprecate ModelTestControllerVersion-s older than EAP_7_4_0

---

core-feature-pack/common/src/main/resources/content/bin/common.bat
core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/common.sh
host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java

https://issues.redhat.com/browse/WFCORE-5406
Further opens clauses are needed after recent upstream changes.

[WFCORE-5406] Add --add-opens to the SE 9+ VM launch for expected reflective access by the server (round 2)

---

host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/DirectoryGrouping.java

[WFCORE-5520] Avoid Nullpointer (host-controller)

---

cli/src/main/java/org/jboss/as/cli/Util.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/HTTPServer.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/HTTPServerDisableSSLCommand.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/HTTPServerEnableSSLCommand.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/OptionActivators.java
cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/ssl/command_resources.properties

Issue: https://issues.redhat.com/browse/WFCORE-5522
This is the security-realm removal impact on WildFly CLI specified in: https://github.com/wildfly/wildfly-proposals/pull/418

[Security Realm Removal] Fix for WFCORE-5522, CLI security SSL commands are too tied to the default config

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5567
Release Notes - WildFly Elytron - Version 1.17.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2034'>ELY-2034</a>] -         Native support for OpenID Connect
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2153'>ELY-2153</a>] -         Add parameter validation to LdapSecurityRealm
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2156'>ELY-2156</a>] -         Add parameter validation for FailoverSecurityRealm
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2157'>ELY-2157</a>] -         Add parameter validation for AggregateSecurityRealm
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2193'>ELY-2193</a>] -         Broken pipe …

[WFCORE-5567] Upgrade WildFly Elytron to 1.17.0.Final

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5585
Diff: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/5.0.0.Beta1...5.0.2.Final

Fix for WFCORE-5585, Upgrade bootable jar to 5.0.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5593
Release Notes - WildFly Elytron - Version 1.17.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2070'>ELY-2070</a>] -         CredentialStore is not able to get data from credential storage in file on IBM JDK 8
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2197'>ELY-2197</a>] -         Close resource - potential resource leak
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2198'>ELY-2198</a>] -         Remove old unused private code
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2215'>ELY-2215</a>] -         Release WildFly Elytron 1.17.1.Final
</li>
</ul>

[WFCORE-5593] Upgrade WildFly Elytron to 1.17.1.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml

https://issues.redhat.com/browse/WFCORE-5597

[WFCORE-5597] Remove references to the security-integration module as it is being removed from WildFly.

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5598
Release Notes - Undertow - Version 2.2.12.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1969'>UNDERTOW-1969</a>] -         Cannot create certificate from header on SE17
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1972'>UNDERTOW-1972</a>] -         InMemorySessionManager can mistake PLACE_HOLDER_SESSION with a real session
</li>
</ul>
Release Notes - Undertow - Version 2.2.11.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1959'>UNDERTOW-1959</a>] -         DefaultServletCachingListenerTestCase.testWelcomePages still fails sporadically with File was not refreshed
</li>
<li>[<a …

[WFCORE-5598] Upgrade Undertow to 2.2.12.Final

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-5603
---
Dev tag: https://github.com/wildfly/jandex/releases/tag/2.3.1.Final
Diff to previous Jandex version without regression: https://github.com/wildfly/jandex/compare/2.2.3.Final...2.3.1.Final

[WFCORE-5603] Downgrade Jandex to 2.3.1.Final

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java

The name of the operation is held by the `OP` constant (`"operation"`)
and not by the `NAME` constant (that would contain an eventual `"name"`
parameter of the given operation).
JIRA: https://issues.redhat.com/browse/WFCORE-5609

[WFCORE-5609] Fix AbstractOperationContext#getCurrentOperationName()

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosHttpMgmtSaslTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosNativeMgmtSaslTestCase.java

Of 3 tests in full WildFly mentioned in the WFCORE-4532 description, two no longer exist and HTTPSWebConnectorTestCase is covered by WFLY-15177
https://issues.redhat.com/browse/WFCORE-4532

[WFCORE-4532] Enable tests on JDK14+ since they  no longer fail

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-debian.sh

Issue: https://issues.redhat.com/browse/WFCORE-5497

WFCORE-5497 Multiple syntax issues with 'wildfly-init-debian.sh'

---

elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java

https://issues.redhat.com/browse/WFCORE-5566

[WFCORE-5566] Use com.sun.net.ssl.internal.ssl.Provider.isFIPS() method for FIPS detection if it exists

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5704
Diff: https://github.com/wildfly/galleon-plugins/compare/5.2.5.Final...5.2.6.Final

Fix for WFCORE-5704, Upgrade galleon plugins to 5.2.6.Final

---

host-controller/src/main/java/org/jboss/as/host/controller/Main.java

Fixes https://issues.redhat.com/browse/WFCORE-5700

[WFCORE-5700] "StandardCharsets" constants (host-controller)

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5717
Release Notes - Undertow - Version 2.2.13.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1993'>UNDERTOW-1993</a>] -         AbstractLoadBalancingProxyTestCase.teardown can throw NPE
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1409'>UNDERTOW-1409</a>] -         sendRedirect to relative urls does not properly encode the current path
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1459'>UNDERTOW-1459</a>] -         ProxyHandler returns status code 503 instead of 504
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1739'>UNDERTOW-1739</a>] -         Sub groups don&#39;t work with nested predicate
</li>
<li>[<a …

[WFCORE-5717] Upgrade Undertow version to 2.2.13.Final

---

bootable-jar/boot/pom.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5722
* The Bootable JAR boot artifact is no more shading org.jboss:jboss-modules. It is expected that this assembly is done by the Bootable JAR maven plugin.
* The Bootable JAR Maven plugin used by tests is updated to the latest version (required upgrade).
Diff: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/5.0.2.Final...6.1.1.Final

Fix for WFCORE-5722, Can't upgrade JBoss Modules artifact

---

testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/AbstractKrb5ConfServerSetupTask.java
testsuite/elytron/src/test/resources/org/wildfly/test/security/common/kerberos/krb5.conf

Issue: https://issues.redhat.com/browse/WFCORE-5685
The ldap/kerberos tests now also add all the enc-types defined in the keytab to the `permitted_enctypes` option in the `krb5.conf` file. This way the allowed enc-types don't depend on the default JDK values. Besides, previously the enc-types selected by the tests were different for ibm and non-ibm JDKs, this part has been also changed (don't know why but with non-ibm only two types were selected, this was done since the creation of the file).
Both tests pass for me with for jdk-18 and the current JDKs (I tried with a lot of versions and vendors).

[WFCORE-5685] KerberosHttpMgmtSaslTestCase & KerberosNativeMgmtSaslTestCase tests fail on JDK 18 EA

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5727
Release Notes - XNIO - Version 3.8.5.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-386'>XNIO-386</a>] -         XNIO001009 logging does not include a stack trace
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-388'>XNIO-388</a>] -         IOException Broken pipe error on JsseSslConduitEngine.doFlush when closing connection
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-394'>XNIO-394</a>] -         Broken pipe errors and premature closes show up intermitently when closing SSL connections
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-395'>XNIO-395</a>] -         Close listener invocation can be skipped
</li>
</ul>
</h2>
<ul>
<li>[<a …

[WFCORE-5727] Upgrade XNIO to 3.8.5.Final

---

pom.xml
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java

https://issues.redhat.com/browse/WFCORE-5728
https://issues.redhat.com/browse/WFCORE-5729
Release Notes - WildFly Elytron - Version 1.18.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2254'>ELY-2254</a>] -         Provide a LoginModule compatible security realm.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1850'>ELY-1850</a>] -         CredentialStore API missing ability to check alias types
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2162'>ELY-2162</a>] -         Add parameter validation to the builder setters in JdbcSecurityRealmBuilder
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2200'>ELY-2200</a>] -         Update org.apache.sshd:sshd-common:2.3.0 to 2.7.0 to …

[WFCORE-5728] Upgrade WildFly Elytron to 1.18.0.Final

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/http/sfbasic/main/module.xml
pom.xml
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java

Added the hold label as this will require an update of WildFly Elytron but I need an upstream PR.
https://issues.redhat.com/browse/WFCORE-5708

[WFCORE-5708] Add a new "org.wildfly.security.http.sfbasic" module.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5731
Release Notes - Elytron Web - Version 1.10.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-163'>ELYWEB-163</a>] -         Update ElytronHttpExchange#getRequestURI to no longer use the 7 argument URI constructor
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-161'>ELYWEB-161</a>] -         Update branches in pr-ci.yaml
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-166'>ELYWEB-166</a>] -         Release Elytron Web 1.10.1.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-168'>ELYWEB-168</a>] -         Upgrade WildFly Elytron to 1.18.0.Final
</li> …

[WFCORE-5731] Upgrade Elytron Web to 1.10.1.Final

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/content/bin/elytron-tool.bat
core-feature-pack/common/src/main/resources/content/bin/elytron-tool.ps1
core-feature-pack/common/src/main/resources/content/bin/elytron-tool.sh
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/cli/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/lang3/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-tool/main/module.xml
core-feature-pack/galleon-common/src/main/resources/packages/tools/pm/wildfly/tasks.xml
elytron-tool-wrapper/pom.xml
elytron-tool-wrapper/src/main/java/org/wildfly/core/elytron/tool/wrapper/ElytronToolScriptWrapper.java
elytron-tool-wrapper/src/main/java/org/wildfly/core/elytron/tool/wrapper/_private/ElytronToolWrapperMessages.java
pom.xml
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
testsuite/scripts/src/test/java/org/wildfly/common/test/ServerConfigurator.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java

https://issues.redhat.com/browse/WFCORE-5712
https://issues.redhat.com/browse/WFCORE-5720
https://issues.redhat.com/browse/WFCORE-5730
Depends on https://github.com/wildfly/wildfly-core/pull/4878 (I've included those commits in this PR to also un-ignore `ElytronToolScriptTestCase`)

[WFCORE-5712] Update elytron-tool scripts to make use of jboss-modules

---

bootable-jar/boot/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5732

Fix for WFCORE-5732, Missing modular options in bootable JAR manifest

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5741
Release Notes - WildFly Elytron - Version 1.18.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2195'>ELY-2195</a>] -         Use daemon threads in default ScheduledExecutorService
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2263'>ELY-2263</a>] -         Release WildFly Elytron 1.18.1.Final
</li>
</ul>

[WFCORE-5741] Upgrade WildFly Elytron to 1.18.1.Final

---

core-feature-pack/galleon-common/src/main/resources/layers/standalone/management/layer-spec.xml
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java

https://issues.redhat.com/browse/WFCORE-5651

[WFCORE-5651] Remove management identity's default security domain configuration

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

The XSD version stays at urn:jboss:domain:19.0 until there is an actual
change change in the XML schema.
JIRA: https://issues.redhat.com/browse/WFCORE-5746

[WFCORE-5746] Bump Management API to 20.0.0

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
pom.xml

https://issues.redhat.com/browse/WFCORE-5751
https://issues.redhat.com/browse/WFCORE-5752

Add ModelTestControllerVersion for XP 4

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5754
Release tags:
- https://github.com/jboss-logging/log4j2-jboss-logmanager/releases/tag/1.1.0.Final 
- https://github.com/jboss-logging/log4j2-jboss-logmanager/releases/tag/1.1.1.Final
Diff: https://github.com/jboss-logging/log4j2-jboss-logmanager/compare/1.0.0.Final...1.1.1.Final

[WFCORE-5754] Upgrade log4j2-jboss-logmanager to 1.1.1.Final.

---

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-4867
related to PR https://github.com/wildfly/wildfly-core/pull/4719

[WFCORE-4867] Highlight the config name in start message

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5767
Moving the Elytron OIDC Client related dependencies from WildFly to Core. The modules that actually make use of these dependencies will remain in WildFly.

[WFCORE-5767] Add the Elytron OIDC Client related dependencies to Core

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5767
Upstream: https://github.com/wildfly/wildfly-core/pull/4917

[18.x][WFCORE-5767] Add the Elytron OIDC Client related dependencies to Core

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5756
Diff: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/6.1.1.Final...7.0.0.Final

Fix for WFCORE-5756, Upgrade bootable jar to 7.0.0.Final

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5756
Diff: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/compare/6.1.1.Final...7.0.0.Final

[18.x] Fix for WFCORE-5756, Upgrade bootable jar to 7.0.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5772
Release Notes - WildFly Elytron - Version 1.18.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2284'>ELY-2284</a>] -         Wildfly OIDC secured App generates a lot of keycloak requests
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2286'>ELY-2286</a>] -         OIDC-Adapter should support multi tenancy
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2288'>ELY-2288</a>] -         Release WildFly Elytron 1.18.2.Final
</li>
</ul>

[WFCORE-5772] Upgrade WildFly Elytron to 1.18.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5776
Release Notes - WildFly Elytron - Version 1.18.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2290'>ELY-2290</a>] -         Update OidcClientConfiguration#resetUrls to handle the case where the provider-url or auth-server-url isn&#39;t valid
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2291'>ELY-2291</a>] -         Release WildFly Elytron 1.18.3.Final
</li>
</ul>

[WFCORE-5776] Upgrade WildFly Elytron to 1.18.3.Final

---

launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java

https://issues.redhat.com/browse/WFCORE-5778
Supersedes https://github.com/wildfly/wildfly-core/pull/4934 which I closed by mistake :(

[WFCORE-5778] Reset 'java.security.manager' default value back to "allow" by default in launcher

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5785

Fix for WFCORE-5785, Upgrade galleon plugins to 5.2.10.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5783
Note this upgrade removes the following:
* `org.apache.log4j.chainsaw.*`
* `org.apache.log4j.jdbc.JDBCAppender`
* `org.apache.log4j.net.JMSAppender`
* `org.apache.log4j.net.JMSSink`
Diff: https://github.com/jboss-logging/log4j-jboss-logmanager/compare/1.2.2.Final...1.3.0.Final
Tag: https://github.com/jboss-logging/log4j-jboss-logmanager/releases/tag/1.3.0.Final

[WFCORE-5783] Upgrade log4j-jboss-logmanager to 1.3.0.Final.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5786
https://issues.redhat.com/browse/WFCORE-5787
Release Notes - WildFly OpenSSL - Version 2.2.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-81'>WFSSL-81</a>] -         Ensure the project is buildable on JDK 17
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-84'>WFSSL-84</a>] -         Add JDK 17 build to Github Actions
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-88'>WFSSL-88</a>] -         Upgrade WildFly OpenSSL Natives to 2.2.0.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-89'>WFSSL-89</a>] -         Release WildFly OpenSSL 2.2.0.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-90'>WFSSL-90</a>] -         Add repositories section to pom.xml …

[WFCORE-5786] / [WFCORE-5787] WildFly OpenSSL Component Upgrades

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5797
Release Notes - XNIO - Version 3.8.6.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-391'>XNIO-391</a>] -         PushBackStreamSourceConduit/Channel leaks pushed back buffer
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-392'>XNIO-392</a>] -         StreamConnection should shutdown reads and writes on notify operation closed
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-398'>XNIO-398</a>] -         JsseSslConduitEngine.isDataAvailable tests for readBuffer.hasRemaining()
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-397'>XNIO-397</a>] -         Remove indirect wildfly-common dependency via widlfy-client-config dependency
</li>
</ul> …

[WFCORE-5797] Upgrade XNIO to 3.8.6.Final

---

pom.xml

Jira https://issues.redhat.com/browse/WFCORE-5801
Fix: CVE-2021-3859
Release Notes - Undertow - Version 2.2.15.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1986'>UNDERTOW-1986</a>] -         Buffer leak errors involving buffer allocated by ChunkedStreamSourceConduit
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1979'>UNDERTOW-1979</a>] -         CVE-2021-3859 Continuation frames are not read correctly 
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1994'>UNDERTOW-1994</a>] -         Method declareRoles not implemented in ServletContextImpl
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2002'>UNDERTOW-2002</a>] - …

[WFCORE-5801] Upgrade Undertow to 2.2.15.Final

---

pom.xml
testbom/pom.xml
testsuite/client-old-server/pom.xml
testsuite/elytron/pom.xml
testsuite/embedded/pom.xml
testsuite/manualmode/pom.xml
testsuite/standalone/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5804
Upstream: https://github.com/wildfly/wildfly-core/pull/4959

[18.x][WFCORE-5804] Move test dep from log4j:log4j to ch.qos.reload4j:reload4j and move it to testbom

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5801
18.x PR: #4963 
Release Notes - Undertow - Version 2.2.16.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2026'>UNDERTOW-2026</a>] -         Do not create a session on DigestAuthenticationMechanism.sendChallenge (reverts UNDERTOW-2007)
</li>
</ul>

[WFCORE-5801] Upgrade Undertow to 2.2.16.Final

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

https://issues.redhat.com/browse/WFCORE-5813

[WFCORE-5813] Eliminating unused CapabilityServiceBuilder.addInjection() method

---

testsuite/embedded/pom.xml

https://issues.redhat.com/browse/WFCORE-5807

[WFCORE-5807] Update logback test dependency to 1.2.9 (CVE-2021-42550)

---

testsuite/embedded/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5807
Upstream: #4967

[18.x][WFCORE-5807] Update logback test dependency to 1.2.9 (CVE-2021-42550)

---

controller/src/main/java/org/jboss/as/controller/operations/global/QueryOperationHandler.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
controller/src/test/java/org/jboss/as/controller/SimpleAttributeDefinitionUnitTestCase.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/access/PrincipalResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/controller/ActiveOperationResourceDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/DomainControllerWriteAttributeHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/RemoteDomainControllerAddHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/AsyncHandlerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/ConsoleHandlerResourceDefinition.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/CommonAttributes.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/MemoryPoolResourceDefinition.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java
server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java
threads/src/main/java/org/jboss/as/threads/KeepAliveTimeAttributeDefinition.java

https://issues.redhat.com/browse/WFCORE-5760 
Changes made for equivalent results:
Constructors:
```java
EnumValidator(Class, boolean, E...) --> EnumValidator(Class, E...)
EnumValidator(Class, boolean, boolean) --> create(Class, E...)
EnumValidator(Class, boolean, boolean, E...) --> EnumValidator(Class, E...)
```
Methods:
```java
create(Class, boolean, E...) --> create(Class, E...)
create(Class, boolean, boolean) --> create(Class, E...)
create(Class, boolean, boolean, E...) --> create(Class, E...)
create(Class, boolean, boolean, E...) --> create(Class, EnumSet)
```

WFCORE-5760 Replace deprecated EnumValidator constructors and methods

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-5766
Based on #4985 as I'd prefer to minimize the number of PRs related to micro component upgrades in 18.x.
See discussion leading up to https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/WFCORE-5777.20JBoss.20Modules.202.2E0.2E2/near/274313586 for why this isn't a move to MSC 2.0.2.

[18.x][WFCORE-5766] Upgrading to JBoss Modules 2.0.1.Final

---

controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java

Issue: [WFCORE-5792](https://issues.redhat.com/browse/WFCORE-5792)

WFLY-5792: ensure configuration files are inside the configuration directory

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/common/main/module.xml

Fixes https://issues.redhat.com/browse/WFCORE-5828

[WFCORE-5828] WildFly-Common 1.6 depends on java.xml

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/common/main/module.xml

Fixes https://issues.redhat.com/browse/WFCORE-5828
Upstream https://github.com/wildfly/wildfly-core/pull/4999

[18.x][WFCORE-5828] WildFly-Common 1.6 depends on java.xml

---

core-feature-pack/galleon-common/src/main/resources/layers/standalone/core-tools/layer-spec.xml

https://issues.redhat.com/browse/WFCORE-5827
Upstream: https://github.com/wildfly/wildfly-core/pull/4996

[18.x][WFCORE-5827] Add elytron-tool to the core-tools layer definition

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java

WFCORE-5798 backporting to 18.x. This issue enables a new test, so it makes sense to me to enable it on 18.x as well.
upstream: https://github.com/wildfly/wildfly-core/pull/4955
Jira issue: https://issues.redhat.com/browse/WFCORE-5798

[18.x][WFCORE-5798] Restore ReloadRedirectTestCase.testReloadwithRedirect

---

elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
elytron/src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java

Issue: https://issues.jboss.org/browse/WFCORE-4314
Related: https://github.com/wildfly/wildfly-core/pull/5008
Improve read commands for elytron keystore.
Resubmit after rebase and few tweaks to doc.
This will require version bump.

[WFCORE-4314] - verbose and recursive parameter in read-alias(es)

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java

Issue: https://issues.redhat.com/browse/WFCORE-5752
Upstream: https://github.com/wildfly/wildfly-core/pull/4899
I'm adding the 'Critical' label for this as it blocks the https://issues.redhat.com/browse/WFLY-15832 feature from being ported to WildFly 26.1.

[WFCORE-5752] Use WildFly 26 as a placeholder for EAP XP 4

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5854
Release Notes - WildFly Elytron - Version 1.19.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2078'>ELY-2078</a>] -         Add encryption support to FileSystemSecurityRealm
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2112'>ELY-2112</a>] -         Automatic registration of client side / JVM wide default SSLContext
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2067'>ELY-2067</a>] -         Elytron tool should log a warning that mask password command is not FIPS compliant 
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2271'>ELY-2271</a>] -         IdentityCredentials should have a verify(Supplier&lt;Provider[]&gt;, evidence, …

[WFCORE-5854] Upgrade WildFly Elytron to 1.19.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5854
Upstream: https://github.com/wildfly/wildfly-core/pull/5026

[18.x][WFCORE-5854] Upgrade WildFly Elytron to 1.19.0.Final

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-5810
https://github.com/wildfly/wildfly-core/pull/4970 backporting to 18.x

[18.x] [WFCORE-5810] Fix license in wildfly-cli jar.

---

elytron/pom.xml
pom.xml
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/JmxRBACProviderHostScopedRolesTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/JmxRBACProviderServerGroupScopedRolesTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/AbstractJmxNonCoreMBeansSensitivityTestCase.java
testsuite/shared/pom.xml
testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ForLoopTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-5563
https://github.com/wildfly/wildfly-core/pull/4723 backporting to 18.x

[18.x][WFCORE-5563] Remove commons-lang(2) usage, use commons-lang3.

---

testbom/pom.xml

Upgrade jackson-databind to 2.12.6.1
Upgrade other jackson components to 2.12.6
Upstream PR: #5040
JIRA: https://issues.redhat.com/browse/WFCORE-5866

[WFCORE-5866] Upgrade Jackson to 2.12.6

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5867
18.x PR: #5043 
Release Notes - Undertow - Version 2.2.17.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1928'>UNDERTOW-1928</a>] -         SimpleSSLTestCase fails on Windows
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2027'>UNDERTOW-2027</a>] -         Spurious buffer leak error in the test-suite (HttpClientTestCase.testReadTimeout)
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2028'>UNDERTOW-2028</a>] -         Buffer leak error involving AjpServerResponseConduit
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1848'>UNDERTOW-1848</a>] - …

[WFCORE-5867] Upgrade Undertow from 2.2.16.Final to 2.2.17.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

Issue: https://issues.redhat.com/browse/WFCORE-5863

[WFCORE-5863] LdapSecurityRealmBuilder should warn that direct verification and user password mapper are incompatible

---

launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java

Issue: https://issues.redhat.com/browse/WFCORE-5880
There is no need to set the modular options, Bootable JAR manifest contains them.

Fix for WFCORE-5880, BootableJarCommandBuilder sets modular options

---

launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java

Jira: https://issues.redhat.com/browse/WFCORE-5881
The details from jira:
JPMS properties are currently [hardcoded in a launcher](https://github.com/wildfly/wildfly-core/blob/main/launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java#L65-L78). Launcher is used by [arquillian container](https://mvnrepository.com/artifact/org.wildfly.arquillian/wildfly-arquillian-container-managed). But latest version of arquillian container uses wf-core 16.0.0.Final. So if we depend on old wf-core launcher, we can't ensure that proper JPMS settings would be used. Fortunately, it's quite easy to propagate correct JPMS properties to arquillian directly. This would be useful only if hard-coded properties from Launcher won't be used. This task adds option to not use hard-coded properties …

[WFCORE-5881] Use JPMS properties from launcher optionally

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5887
18.x PR: #5072 
Release Notes - XNIO - Version 3.8.7.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-403'>XNIO-403</a>] -         Channels/Conduits.drain do not check for -1 when transferring bytes
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-404'>XNIO-404</a>] -         Channels cannot open file &quot;NUL:&quot; on Windows 
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-406'>XNIO-406</a>] -         javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2)
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-409'>XNIO-409</a>] -         Channels.drain(FileChannel, long, long) should …

[WFCORE-5887] Upgrade XNIO to 3.8.7.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5883
This PR will require changes to WildFly first so WildFly can handle it's own dependency management.
This can be merged once https://github.com/wildfly/wildfly/pull/15457 is merged to WildFly.

[WFCORE-5883] Remove wildfly-elytron-jwt from dependency management.

---

cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProviderTestCase.java
cli/src/test/java/org/jboss/as/cli/parsing/test/PropertyReplacementTestCase.java
cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
cli/src/test/java/org/jboss/as/cli/parsing/test/VariablesTestCase.java

Assertion arguments should be passed in the correct order (cli)
Fixes https://issues.redhat.com/browse/WFCORE-5649
Upstream https://github.com/wildfly/wildfly-core/pull/5085

[18.x][WFCORE-5649] Assertion arguments should be passed correct (cli)

---

controller/src/main/java/org/jboss/as/controller/audit/InMemoryAuditLogHandler.java
controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationDomainSlaveConfigHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationProviderWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationUseIdentityRolesWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/RoleIncludeAllWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/RoleMappingResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/InMemoryAuditLogHandlerResourceDefinition.java

Issue: https://issues.redhat.com/browse/WFCORE-5904

[WFCORE-5904] Fix typo in some Handler filenames.

---

controller/src/main/java/org/jboss/as/controller/operations/common/Util.java
controller/src/main/java/org/jboss/as/controller/operations/global/ListOperations.java
controller/src/main/java/org/jboss/as/controller/operations/global/MapOperations.java
controller/src/test/java/org/jboss/as/controller/operations/common/UtilTest.java

https://issues.redhat.com/browse/WFCORE-5906

WFCORE-5906 Expand set of utility methods for creating generic operations

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5909
Release Notes - WildFly OpenSSL - Version 2.2.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-93'>WFSSL-93</a>] -         Set the natives version used to 2.2.0.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-94'>WFSSL-94</a>] -         java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer; on JDK8
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-95'>WFSSL-95</a>] -         Release WildFly OpenSSL 2.2.1.Final
</li>
</ul>

[WFCORE-5909] Upgrade WildFly OpenSSL to 2.2.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5909
Upstream: https://github.com/wildfly/wildfly-core/pull/5099
Release Notes - WildFly OpenSSL - Version 2.2.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-93'>WFSSL-93</a>] -         Set the natives version used to 2.2.0.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-94'>WFSSL-94</a>] -         java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer; on JDK8
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-95'>WFSSL-95</a>] -         Release WildFly OpenSSL 2.2.1.Final
</li>
</ul>

[18.x][WFCORE-5909] Upgrade WildFly OpenSSL to 2.2.1.Final

---

security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java

https://issues.redhat.com/browse/WFCORE-5905

[WFCORE-5905] Don't reject EE 10 permissions.xml files

---

core-feature-pack/common/src/main/resources/content/bin/standalone.bat
testsuite/scripts/src/test/java/org/wildfly/common/test/ServerConfigurator.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java

https://issues.redhat.com/browse/WFCORE-5869

[WFCORE-5869] standalone.bat script does not parse JAVA_OPTS containing '|' symbol properly

---

cli/src/main/resources/help/reload.txt

Issue: https://issues.redhat.com/browse/WFCORE-5841

WFCORE-5841 [primary/secondary] Review the documentation of affected CLI management operations

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5911

Fix for WFCORE-5911, Upgrade to Galleon 5.0.1.Final and Galleon plugins 6.0.0.Alpha2

---

controller/src/main/java/org/jboss/as/controller/operations/global/ReadChildrenNamesHandler.java
controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
logging/src/main/java/org/jboss/as/logging/LoggingExtension.java

* Removing the child names for runtime resource definitions when the
resource is not present for completion.
* Setting the logging deployment submodel to runtime
Jira: https://issues.redhat.com/browse/WFCORE-5852
https://issues.redhat.com/browse/WFCORE-5853

WFCORE-2852/WFCORE-5853: CLI autocomplete suggests non-existent subsystems

---

core-feature-pack/common/src/main/resources/content/bin/common.bat
core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/common.sh
host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5936
The elytron dir-context also needs exports for `com.sun.jndi.url.ldap` in order to follow referrals in JDK-17. There is a exception in `org.jboss.as.naming.context.ObjectFactoryBuilder` when trying to recreate the context for the referral now. Just adding the same exports that were added for `com.sun.jndi.ldap` in WFCORE-5438.
@bstansberry Take a look when you have time. If you want it in another branch (26.x) just let me know.
@fjuma I was thinking about adding a referral and `referral-mode=follow` ldap realm test but I see they are on [wildfly](https://github.com/wildfly/wildfly/blob/main/testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/LdapRealmTestCase.java). I can create a followup JIRA for that …

[WFCORE-5936] Ldap autentication using referrals fails on JDK 17 with ApacheDS

---

core-feature-pack/common/src/main/resources/content/bin/standalone.sh

https://issues.redhat.com/browse/WFCORE-5917

[WFCORE-5917] Duplicating -Djboss.server.base.dir if defined in more than one place

---

pom.xml

These changes resolve convergence errors produced during the
productized build of the server.
Issue: https://issues.redhat.com/browse/WFCORE-5943

[WFCORE-5943] Exclude undertow-servlet transitive dependencies

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5946
Fixes  CVE-2022-1319
18.x PR: #5128 
Release Notes - Undertow - Version 2.2.18.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1945'>UNDERTOW-1945</a>] -         ServletOutputStreamTestCase fails with Premature end of chunk coded message body
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2034'>UNDERTOW-2034</a>] -         Http2StreamSinkChannel.awaitWritable could throw &quot;Out of control window&quot; IOException before awaitWritable timeout has fully ellapsed
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2035'>UNDERTOW-2035</a>] -         Http2StreamSinkChannel overrides awaitWritable() but does not override …

[WFCORE-5946] Upgrade Undertow to 2.2.18.Final (fixes CVE-2022-1319)

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5931
18.x PR: #5130 
Release Notes - JBoss Remoting (3+) - Version 5.0.25.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-391'>REM3-391</a>] -         Remove the lock around Endpoint connection creation
</li>
</ul>

[WFCORE-5931] Upgrade JBoss Remoting to 5.0.25.Final

---

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
domain-management/src/main/java/org/jboss/as/domain/management/controller/ActiveOperationResourceDefinition.java
server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java

Issue: [WFCORE-1960](https://issues.redhat.com/browse/WFCORE-1960)

WFCORE-1960: replace list of properties with map of strings

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-5948
* Upgrading JGit to to 6.2.0.202206071550-r
* Upgrading Apache SSHD to 2.8.0

[WFCORE-5948]: Upgrade JGit to 6.2.0.202206071550-r

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml

Two fixes for YAML Extension: empty resources and list attributes
Jira: https://issues.redhat.com/browse/WFCORE-5953
https://issues.redhat.com/browse/WFCORE-5954

WFCORE-5953/WFCORE-5954: Fixing several YAML extension issues

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/logging/RemotingLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-5958

[WFCORE-5958] The warning message when changing worker of remoting endpoint is not fully correct

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-5975
https://issues.redhat.com/browse/WFCORE-5859
This PR also includes a change from https://github.com/wildfly/wildfly-core/pull/5048 which is needed to pass CI.
Release Notes - WildFly Elytron - Version 1.20.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2320'>ELY-2320</a>] -         Add integrity support to FileSystemSecurityRealm
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2304'>ELY-2304</a>] -         Location is required even for non-filebased type e.g. PKCS11
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2322'>ELY-2322</a>] -         Duplicate dependency in auth/client/pom.xml
</li>
<li>[<a …

[WFCORE-5975] Upgrade WildFly Elytron to 1.20.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5945
https://issues.redhat.com/browse/WFCORE-5941
https://issues.redhat.com/browse/WFCORE-5976
Release Notes - WildFly OpenSSL - Version 2.2.4.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-100'>WFSSL-100</a>] -         Upgrade WildFly OpenSSL Linux Natives to 2.2.2.SP01
</li>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-101'>WFSSL-101</a>] -         Release WildFly OpenSSL 2.2.4.Final
</li>
</ul>
Release Notes - WildFly OpenSSL Natives - Version 2.2.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/SSLNTV-21'>SSLNTV-21</a>] -         Release WildFly OpenSSL Natives 2.2.2.Final
</li>
</ul>
Release Notes - WildFly OpenSSL Natives - Version 2.2.2.SP01
<h2> …

[WFCORE-5945][WFCORE-5941][WFCORE-5976] WildFly OpenSSL Component Upgrades

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5981
Release Notes - WildFly OpenSSL - Version 2.2.5.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-102'>WFSSL-102</a>] -         OpenSSLContextSPI socket factory cannot create unbound server sockets
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFSSL-103'>WFSSL-103</a>] -         Release WildFly OpenSSL 2.2.5.Final
</li>
</ul>

[WFCORE-5981] Upgrade WildFly OpenSSL to 2.2.5.Final

---

controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5970

WFCORE-5970 Server does not start when configuration file is a soft link to a file outside of the server configuration directory

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6024
18.x PR: #5170 
Release Notes - Undertow - Version 2.2.19.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1790'>UNDERTOW-1790</a>] -         UT000010: Session is invalid due to concurrent calls changeSessionId() calls on same session
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1900'>UNDERTOW-1900</a>] -         InMemorySessionManager#SessionImpl.changeSessionId does not check if session exist before replacing
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1934'>UNDERTOW-1934</a>] -         onClose not called when network drops
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1997'>UNDERTOW-1997</a>] -         SecurityPathMatches fails to match default …

[WFCORE-6024]Upgrade Undertow to 2.2.19.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6024
Main PR: #5169 
Release Notes - Undertow - Version 2.2.19.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1790'>UNDERTOW-1790</a>] -         UT000010: Session is invalid due to concurrent calls changeSessionId() calls on same session
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1900'>UNDERTOW-1900</a>] -         InMemorySessionManager#SessionImpl.changeSessionId does not check if session exist before replacing
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1934'>UNDERTOW-1934</a>] -         onClose not called when network drops
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1997'>UNDERTOW-1997</a>] - …

[WFCORE-6024]Upgrade Undertow to 2.2.19.Final  (fixes CVE-2022-1319, CVE-2022-2053)

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

https://issues.redhat.com/browse/WFCORE-6030

[WFCORE-6030] Eliminating deprecated and unused CapabilityServiceTarget.addCapability(RuntimeCapability,Service) method

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyPolicyTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6032
This test case is failing very often and it is making the testsuite to hang. Ignore it temporarily until further investigation

[WFCORE-6032] Ignore AdminOnlyPolicyTestCase

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6033
Release Notes - WildFly Elytron - Version 1.20.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2351'>ELY-2351</a>] -         ScramDigestPasswordImpl fails with PKCS#11 (FIPS)
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2356'>ELY-2356</a>] -         Revisit org.wildfly.security.http.oidc.OidcClientConfigurationBuilder#sanitizeProviderUrl
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2357'>ELY-2357</a>] -         Update the issuer URL for OIDC based on discovery
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2374'>ELY-2374</a>] -         Support forwarding of domain_hint query parameter
</li>
</ul>
</h2>
<ul>
<li>[<a …

[WFCORE-6033] Upgrade WildFly Elytron to 1.20.1.Final

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml

PR combining all the YAML fixes:
- [WFCORE-5953]: List attribute are not properly updated with the YamlConfigurationExtesnion
- [WFCORE-5954]: Yaml Extension doesn't add empty resources.
- [WFCORE-5918]: Adding SSO to application security domain via YamlConfigurationExtesnion
- [WFCORE-5949]: Adding meta-data to json-logger via YamlConfigurationExtesnion
Jira: 
https://issues.redhat.com/browse/WFCORE-5953
https://issues.redhat.com/browse/WFCORE-5954
https://issues.redhat.com/browse/WFCORE-5918
https://issues.redhat.com/browse/WFCORE-5949
Supersedes: 
https://github.com/wildfly/wildfly-core/pull/5134
https://github.com/wildfly/wildfly-core/pull/5135
https://github.com/wildfly/wildfly-core/pull/5145

Yaml backport

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5939
Upstream: https://github.com/wildfly/wildfly-core/pull/5181
Release Notes - WildFly Elytron - Version 1.19.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2304'>ELY-2304</a>] -         Location is required even for non-filebased type e.g. PKCS11
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2326'>ELY-2326</a>] -         Elytron GSSCredentialSecurityFactory does not check validity of KerberosTicket.
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2347'>ELY-2347</a>] -         parseKeyStoreType crashes if type and wrap attributes not set
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2360'>ELY-2360</a>] -         Sporadic &quot;Invalid format of OIDC_STATE cookie&quot; warnings …

[18.x][WFCORE-5939] Upgrade WildFly Elytron to 1.19.1.Final

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

https://issues.redhat.com/browse/WFCORE-6035

[WFCORE-6035] Eliminating deprecated and unused CapabilityServiceBuilder.addDependency(ServiceName,Class,Injector) method

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6041

Fix for WFCORE-6041, Upgrade to Galleon 5.0.5.Final, Galleon plugins 6.0.0.Final and Bootable JAR 8.0.0.Final

---

testsuite/pom.xml

https://issues.redhat.com/browse/WFCORE-6036

[WFCORE-6036] Move the xml-maven-plugin xalan dep to 2.7.1.jbossorg6

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6026
https://issues.redhat.com/browse/WFCORE-6027
https://issues.redhat.com/browse/WFCORE-6049
https://issues.redhat.com/browse/WFCORE-6050
https://issues.redhat.com/browse/WFCORE-6051
Release Notes - WildFly Elytron - Version 2.0.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2413'>ELY-2413</a>] -         Re-authentication after reboot, even though HttpSession are persisted
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2417'>ELY-2417</a>] -         Release WildFly Elytron 2.0.0.Final
</li>
</ul>
Release Notes - Elytron Web - Version 3.0.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-195'>ELYWEB-195</a>] -         Add …

[WFCORE-6026][WFCORE-6027][WFCORE-6049][WFCORE-6050][WFCORE-6051] Elytron component upgrades

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6053
18.x PR: #5209 
Release Notes - XNIO - Version 3.8.8.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-401'>XNIO-401</a>] -         CVE-2022-0084 StreamConnection.notifyRead/WriteClosed() invoke Throwable.printStackTrace()
</li>
</ul>

[WFCORE-6053] Upgrade XNIO to 3.8.8.Final. Fixes CVE-20022-0084.

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6054

Fix for WFCORE-6054, Upgrade Galleon plugins to 6.1.0.Final

---

core-feature-pack/common/assembly.xml
core-feature-pack/ee-10-api/assembly.xml
core-feature-pack/galleon-common/assembly.xml

This change does this by adding the maven module pom to the zip.
A reasonable alternative when we have a bit more time would be to convert these modules jar packaging.
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>
https://issues.redhat.com/browse/WFCORE-6055

[WFCORE-6055] Make Galleon provisioning content zips unique per release

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6056
Release Notes - Undertow - Version 2.3.0.Beta1
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1902'>UNDERTOW-1902</a>] -         Undertow allows session creation and session ID change after response is committed.
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1934'>UNDERTOW-1934</a>] -         onClose not called when network drops
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1997'>UNDERTOW-1997</a>] -         SecurityPathMatches fails to match default path (&#39;/&#39;) 
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2069'>UNDERTOW-2069</a>] -         Filter.destroy can deadlock with running filter on shutdown
</li>
<li>[<a …

[WFCORE-6056] Upgrade Undertow to 2.3.0.Beta1

---

elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java

Issue Link: https://issues.redhat.com/browse/WFCORE-6040

[WFCORE-6040] Update MappersTestCase to use assertNull where appropriate

---

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java

Issue: [WFCORE-5903](https://issues.redhat.com/browse/WFCORE-5903)
Given what is happening in the [registerRemoteHost method](https://github.com/michpetrov/wildfly-core/blob/373c285655e992c5ed857de055735269063d0516/host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java#L390-L398) processing the `slaveHostRegistrations` conditionally seems wrong here.

WFCORE-5903: fix remote host unregistration

---

launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java

Issue: https://issues.redhat.com/browse/WFCORE-6068

Fix for WFCORE-6068, CliCommandBuilder.of method must be added back

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6072

[WFCORE-6072] Upgrade JBoss Marshalling to 2.1.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6076
Release Notes - JBoss Remoting (3+) - Version 5.0.26.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-394'>REM3-394</a>] -         JBoss Remoting must not depend on org.wildfly.security:wildfly-elytron
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-395'>REM3-395</a>] -         Fix the CI and enable it on all branches
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-398'>REM3-398</a>] -         Upgrade dependencies to latest minor versions
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-396'>REM3-396</a>] - …

[WFCORE-6076] Upgrade JBoss Remoting to 5.0.26.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6078
Signed-off-by: James R. Perkins <jperkins@redhat.com>
----
Tag: https://github.com/jboss-logging/jboss-logmanager/releases/tag/2.1.19.Final
Diff: https://github.com/jboss-logging/jboss-logmanager/compare/2.1.18.Final...2.1.19.Final

[WFCORE-6078] Upgrade jboss-logmanager to 2.1.19.Final.

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6057
Release notes containing just the diff between 2.3.0.Beta1 and 2.3.0.Final:
Release Notes - Undertow - Version 2.3.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1818'>UNDERTOW-1818</a>] -         AbstractServletInputStreamTestCase.runTestParallel fails with bytes out of order
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2048'>UNDERTOW-2048</a>] -         CVE-2022-2764 UndertowInputStream.close() blocks waiting to read= -1
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2069'>UNDERTOW-2069</a>] -         Filter.destroy can deadlock with running filter on shutdown
</li>
<li>[<a …

[WFCORE-6057] Upgrade Undertow to 2.3.0.Final (fixes CVE-2022-2764)

---

cli/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6038
Make all dependencies explicit, needed to only shade the set of required dependencies.
@fjuma , I am wandering if some of the elytron dependencies are actually needed for WildFly CLI executable JAR execution.
For example:
* wildfly-elytron-auth-server (dependency of wildfly-protocol)
* wildfly-elytron-auth-server-deprecated (dependency of wildfly-protocol)
* wildfly-elytron-auth-server-http (dependency of wildfly-elytron-auth-server-deprecated)
* wildfly-elytron-auth-server-sasl (transitive of wildfly-elytron-auth-server-deprecated)
Would you mind giving an eye to the list of elytron dependencies?
Thank-you.

Fix for WFCORE-6038, The org.wildfly.core:wildfly-cli:client artifact has unneeded dependencies

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
elytron/pom.xml
jakartaee/elytron-jakarta/pom.xml
pom.xml
testsuite/manualmode/pom.xml
testsuite/shared/pom.xml

https://issues.redhat.com/browse/WFCORE-6091
Drop -jakarta suffix from the transformed artifact and use new suffix for original artifact instead, until it is properly migrated to Jakarta namespace.
This change would require change in wildfly to use the dependency without suffix.

[WFCORE-6091] Drop suffix from transformed wildfly-elytron-integration artifact

---

elytron/pom.xml
jakartaee/elytron-jakarta/pom.xml
model-test/pom.xml
pom.xml
testbom/pom.xml
testsuite/patching/pom.xml
testsuite/standalone/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5979

[WFCORE-5979] Move com.google.guava:guava and com.google.guava:failureaccess to testbom

---

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java

Issue: https://issues.redhat.com/browse/WFCORE-6100
move the `-D[Server:XXX] `parameter ahead of  and `add-opens` modular JVM options

WFCORE-6100 reorder JVM modular options

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6106
The XSD version stays at urn:jboss:domain:20.0 until there is an actual
change change in the XML schema.

[WFCORE-6106] Bump Management API to 21.0.0

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6110

[19.x][WFCORE-6110] Upgrade Jandex to 3.0.3

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6111

[19.x] Fix for WFCORE-6111, Upgrade Bootable JAR to 8.1.0.Final

---

controller/src/main/java/org/jboss/as/controller/PathAddress.java

Issue: https://issues.redhat.com/browse/WFCORE-6127
Remove deprecated PathAddress methods.
Some code improvements suggested by IDE.
Remove unused `toHttpStyleString` method

[WFCORE-6127] Remove deprecated PathAddress methods

---

jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
jmx/src/test/java/org/jboss/as/jmx/PluggableMBeanServerTestCase.java
jmx/src/test/java/org/jboss/as/jmx/auditlog/JmxAuditLogHandlerTestCase.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/OtherServicesSubsystemTestCase.java

Built on top of #5299
Jira issue: https://issues.redhat.com/browse/WFCORE-6144
Ensures the Service is up before initializing the MBeanServer instance value

[WFCORE-6144] JmxFacadeRbacEnabledTestCase tests fail intermittently due to an NPE

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6132

[WFCORE-6132] Upgrade sshd-common to 2.9.2 to address CVE-2022-45047

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6132

[19.x] WFCORE-6132 Upgrade sshd-common to 2.9.2 to address CVE-2022-45047

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
server/src/main/java/org/jboss/as/server/ExternalManagementRequestExecutor.java
server/src/main/java/org/jboss/as/server/ServerService.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/OtherServicesSubsystemTestCase.java

https://issues.redhat.com/browse/WFCORE-6141
https://issues.redhat.com/browse/WFCORE-6156
https://issues.redhat.com/browse/WFCORE-6157
https://issues.redhat.com/browse/WFCORE-6158

[WFCORE-6141][WFCORE-6156][WFCORE-6157][WFCORE-6158] Server Stability Fixes

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointService.java

Issue: https://issues.redhat.com/browse/WFCORE-6166

[WFCORE-6166] max-outbound-channels setting in remoting subsystem is not honored

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6160
Release Notes - JBoss Remoting (3+) - Version 5.0.27.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-393'>REM3-393</a>] -         Endpoint parsing: add support for max-inbound-channels and max-outbound-channels
</li>
</ul>

[WFCORE-6160] Upgrade JBoss Remoting to 5.0.27.Final

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ShutdownRestartTestCase.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java

https://issues.redhat.com/browse/WFCORE-2218

[WFCORE-2218] Ability to ask testrunner ServerController to wait for server process exit and get the exit code

---

model-test/pom.xml
pom.xml
testbom/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6175
related WFLY PR: https://github.com/wildfly/wildfly/pull/16380 Full integration Test failures are expected until WFLY PR is merged.

[WFCORE-6175] move the plexus-utils dependency to testbom and upgrade

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6181

Fix WFCORE-6181, Upgrade to Galleon 5.0.7.Final, Galleon plugins 6.2.2.Final

---

subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java

https://issues.redhat.com/browse/WFCORE-6182

[WFCORE-6182] Await service container stability before KernelServices are provided

---

.github/dependabot.yml

https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
Configures Dependabot to check the GitHub action used on the GithubWorkflows

Keeping the actions up to date with Dependabot

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/systemd/wildfly.service

Issue: https://issues.redhat.com/browse/WFCORE-6155
Thanks for submitting your Pull Request!
Please delete this text, and add a link to the Jira issue solved by this PR.
Remember to use the Jira issue ID in the PR title, and any commits.

[WFCORE-6155] systemd service file - warning PIDFile legacy path used

---

controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemParser_1_0.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/dependent/SubsystemParser.java
threads/src/main/java/org/jboss/as/threads/ThreadsParser2_0.java

Issue: https://issues.redhat.com/browse/WFCORE-6187

[WFCORE-6187] Remove use of deprecated builder methods in PersistentResourceXmlDescription

---

controller-client/src/main/java/org/jboss/as/controller/client/helpers/DelegatingModelControllerClient.java

Issue: https://issues.redhat.com/browse/WFCORE-6198

[WFCORE-6198] DelegatingModelControllerClient.close should handle a missing client

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/slf4j/main/module.xml
pom.xml
testsuite/embedded/pom.xml

https://issues.redhat.com/browse/WFCORE-6204
According to https://www.slf4j.org/manual.html SLF4J should be backwards compatible. This does however require changes to the implementation of `org.jboss.logging:slf4j-jboss-logmanager`. We also need to upgrade logback for testing.
We do not support logback so any user using logback would be required to provide their own version of the `slf4j-api`. We should be able to safely upgrade. Tests passed for me locally and the full test suite of WildFly.

[WFCORE-6204] Upgrade SLF4J from 1.7.36 to 2.0.6.

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6209

Fix for WFCORE-6209, Upgrade galleon-plugins to 6.2.3.Final

---

server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java

https://issues.redhat.com/browse/WFCORE-6211

[WFCORE-6211] Remove ModuleIdentifier from ServiceModuleLoader.preloadModule

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6217
Release Notes - Undertow - Version 2.3.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2054'>UNDERTOW-2054</a>] -         Buffer leak errors involving SslConduit on CI
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2198'>UNDERTOW-2198</a>] -         Add Option to force the SNIHostName 
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1988'>UNDERTOW-1988</a>] -         undertow-servlet-jakartaee9 has a Java EE 8 dependency
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2184'>UNDERTOW-2184</a>] - …

[WFCORE-6217] Upgrade Undertow to 2.3.4.Final

---

subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/TransformerSubsystemTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6226

[WFCORE-6226] Dropping tests for TransformerSubsystemTestCase using deprecated ModelTestControllerVersion and creating test case against EAP_7_4_0

---

core-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6228
Upgrade galleon-plugins and remove the copy of wildfly-config-gen artifact inside the feature-pack. It is now resolved from maven.

Fix for WFCORE-6228, Upgrade galleon-plugins to 6.3.0.Final

---

cli/src/main/java/org/jboss/as/cli/impl/aesh/SynopsisGenerator.java
cli/src/test/java/org/jboss/as/cli/impl/BootScriptInvokerTestCase.java

- This PR fixes the error resulting from two flaky tests:  `org.jboss.as.cli.impl.aesh.HelpSupportTestCase` and  `org.jboss.as.cli.impl.BootScriptInvokerTestCase`
- The mentioned tests may fail or pass without changes made to the source code when it is run in different JVMs due to `HashSet`'s non-deterministic iteration order.
- Test one fails because `HelpSupportTestCase` calls `SynopsisGenerator`, which uses a `HashSet` as its data structure for the conflicts object. As per Java 11 documentation, the ordering of `HashSet` is not constant. So, the test may fail as the given order can be different from the expected order. 
- Test two fails because `BootScriptInvokerTestCase#test` uses a `HashSet` as its data structure for the echos object. As per Java 11 documentation, the ordering of …

[WFCORE-6214] Fixed Flaky Tests in HelpSupportTestCase.testStandalone and BootScriptInvokerTestCase

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
pom.xml
testsuite/elytron/pom.xml

https://issues.redhat.com/browse/WFCORE-6243
This PR also includes the changes from https://github.com/wildfly/wildfly-core/pull/5386 since this is needed to build successfully with Elytron 2.1.0.Final. See https://issues.redhat.com/browse/WFCORE-6239 for more details.
Release Notes - WildFly Elytron - Version 2.1.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-317'>ELY-317</a>] -         OneTimePassword transformer
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2313'>ELY-2313</a>] -         Update the OIDC tests to use the 19.0.1 version of quay.io/keycloak/keycloak
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2383'>ELY-2383</a>] -         KeyStoreCredentialStoreTest fails in Windows without …

[WFCORE-6243] Upgrade WildFly Elytron to 2.1.0.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/security/auth/message/api/main/module.xml
server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
testsuite/shared/src/main/resources/jmx-listener-module.xml
testsuite/shared/src/main/resources/org/jboss/as/test/integration/management/extension/dependent/module.xml
testsuite/shared/src/main/resources/org/wildfly/test/jmx/events/module.xml
testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/booterror/module.xml
testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/remove/module.xml

https://issues.redhat.com/browse/WFCORE-6237

[WFCORE-6237] Eliminating usage of deprecated javax.api aggregation module

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6252

Fix for WFCORE-6252, Upgrade Galleon to 5.0.8.Final and galleon Plugins to 6.3.2.Final

---

testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/security-module.xml

https://issues.redhat.com/browse/WFCORE-6251

[WFCORE-6251] Use standard java.xml JPMS module instead of deprecated javax.xml.stream.api

---

server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java

https://issues.redhat.com/browse/WFCORE-6250

[WFCORE-6250] Don't include org.jboss.vfs module to all deployments by default

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6246 Upgrade snakeyaml from 1.33 to 2.0
cc @ehsavoie @jamezp

[WFCORE-6246] Upgrade snakeyaml from 1.33 to 2.0

---

pom.xml
testsuite/scripts/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6241
My machine:
mvn clean install -DskipTests -> 02:00 min
mvn -Dquickly -> 01:24 min
mvnd -Dquickly -> 46.530 s (7 threads)

[WFCORE-6241] Adding 'quickly' profile for fast maven builds with quick profile

---

core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.bat
core-feature-pack/common/src/main/resources/content/bin/domain.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.sh
core-feature-pack/common/src/main/resources/content/bin/standalone.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.sh

Addresses [WFCORE-6202](https://issues.redhat.com/projects/WFCORE/issues/WFCORE-6202)

[WFCORE-6202] Don't set `-server` option for IBM i

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml

The issue was that while waiting for reload we might not wait until the server had restarted in NORMAL mode thus getting a configuration that could be unfinished.
Jira: https://issues.redhat.com/browse/WFCORE-6261

[WFCORE-6261]: org.jboss.as.test.manualmode.management.persistence.YamlExtensionTestCase is flaky

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/KerberosTestUtils.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/Krb5LoginConfiguration.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5947
Making this Draft because this requires Elytorn upgrade to include fix in https://github.com/wildfly-security/wildfly-elytron/pull/1722. Otherwise,`KerberosNativeMgmtSaslTestCase` and `KerberosHttpMgmtSaslTestCase` fails on IBM JDK.
cc @Skyllarr

[WFCORE-5947] fix test for IBM JDK Semeru 11

---

controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
controller/src/main/java/org/jboss/as/controller/AbstractBoottimeAddStepHandler.java
controller/src/main/java/org/jboss/as/controller/AbstractRemoveStepHandler.java
controller/src/main/java/org/jboss/as/controller/ReloadRequiredAddStepHandler.java
controller/src/main/java/org/jboss/as/controller/operations/common/InterfaceAddHandler.java
controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
elytron/src/main/java/org/wildfly/extension/elytron/BaseAddHandler.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/ProfileAddHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/ServerGroupAddHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerAddHandler.java
jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java
jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorAdd.java
request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemAdd.java
request-controller/src/test/java/org/wildfly/extension/requestcontroller/WFCORE4967_TestCase.java
server/src/main/java/org/jboss/as/server/services/net/InterfaceAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingResourceDefinition.java
server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingResourceDefinition.java
server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingResourceDefinition.java
server/src/main/java/org/jboss/as/server/services/net/SocketBindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/SpecifiedInterfaceAddHandler.java

https://issues.redhat.com/browse/WFCORE-6142
This had been sitting bit-rotting on my laptop for a couple months; I'm not sure why I didn't send it up. We'll see if CI tells me why.
I may have been thinking about doing AbstractRemoveStepHandler in the same PR, but if so a 2 month pointless delay is a good sign that it's better to do things one step at a time.

[WFCORE-6142] Remove deprecated AbstractAddStepHandler methods

---

pom.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java

Also: update WildFly core tests to comply with [CVE-2022-4492](https://issues.redhat.com/browse/UNDERTOW-2212) fix.
Jira: https://issues.redhat.com/browse/WFCORE-6272
Release Notes - Undertow - Version 2.3.5.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2252'>UNDERTOW-2252</a>] -         SslConduit.dataToUnwrap leaks on CI causing intermittent failures
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1875'>UNDERTOW-1875</a>] -         Matrix parameters with comma are not properly handled
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2207'>UNDERTOW-2207</a>] -         IOException thrown by UndertowOutputStream upon flush
</li>
<li>[<a …

[WFCORE-6272] CVE-2022-4492 CVE-2023-1108 Upgrade Undertow to 2.3.5.Final

---

controller/src/main/java/org/jboss/as/controller/operations/validation/EnumValidator.java

... when validator accepts all enum values.
https://issues.redhat.com/browse/WFCORE-6278

WFCORE-6278 Overload EnumValidator.create(...) to avoid redundant set copy

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6280

Fix for WFCORE-6280, Upgrade Galleon to 5.0.9.Final and galleon Plugins to 6.3.3.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6284
Release Notes - XNIO - Version 3.8.9.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-415'>XNIO-415</a>] -         WatchServiceFileSystemWatcher swallows some events
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-417'>XNIO-417</a>] -         Prevent NPEs in ChannelListeners utility methods
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-412'>XNIO-412</a>] -         XnioWorkerTestCase.ChannelListener  and others should be synchronized
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-413'>XNIO-413</a>] -         XnioWorkerTestCase.cancelAcceptTcpStream does not clear listener
</li>
</ul>

[WFCORE-6284] Upgrade XNIO to 3.8.9.Final

---

pom.xml
testsuite/elytron/pom.xml
testsuite/manualmode/pom.xml
testsuite/rbac/pom.xml
testsuite/standalone/pom.xml

https://issues.redhat.com/browse/WFCORE-6287
Use the up-to-date configuration via `systemPropertyVariables` (https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html)

[WFCORE-6287] Replace deprecated systemProperties configuration

---

server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentModulesListTestCase.java

https://issues.redhat.com/browse/WFCORE-6245

[WFCORE-6245] Eliminating deprecated ibm.jdk module usages

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml

https://issues.redhat.com/browse/WFCORE-6308

[WFCORE-6308] Removing unused Jetty ALPN provider - it was targeting JDK8 and below

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml

https://issues.redhat.com/browse/WFCORE-6309

[WFCORE-6309] The license for StaxMapper should be LGPL 2.1 or Later.

---

jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
network/src/main/java/org/jboss/as/network/OutboundSocketBinding.java
network/src/main/java/org/jboss/as/network/SocketBinding.java
server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/subsystem/SubsystemAddWithSocketBindingUserService.java

Issue: https://issues.redhat.com/browse/WFCORE-6124
[WFCORE-6124] Remove deprecated SocketBinding and OutboundSocketBinding members

[WFCORE-6124] Remove deprecated SocketBinding and OutboundSocketBinding members

---

core-feature-pack/galleon-common/src/main/resources/layers/standalone/jmx-remoting/layer-spec.xml

https://issues.redhat.com/browse/WFCORE-6342
This was previously made optional when we had multiple management layers to choose from but now we are back to one so needs to be mandatory.

[WFCORE-6342] The jmx-remoting dependeny on management needs to be mandatory.

---

controller/src/main/java/org/jboss/as/controller/OperationDefinition.java

Issue: https://issues.redhat.com/browse/WFCORE-6336
There are no deprecated methods in SimpleOperationDefinition. Please correct me if I am wrong.

WFCORE-6336 Remove deprecated OperationDefinition and SimpleOperationDefinition API

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml

* Fixing the case when the resource name matches a resource attribute name.
Jira: https://issues.redhat.com/browse/WFCORE-6338

[WFCORE-6338]: A resource name can't match an attribute name of this resource.

---

core-feature-pack/common/src/main/resources/content/bin/common.bat
core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/common.sh
host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6346

[WFCORE-6346] Module java.base must open java.net package to all unnamed modules

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6302
Release Notes - Undertow - Version 2.3.6.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1938'>UNDERTOW-1938</a>] -         MaxRequestSizeTestCase.testMaxRequestHeaderSize fails with 500 on Windows
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2259'>UNDERTOW-2259</a>] -         LoadBalancerConnectionPoolingTestCase fails when system is slow
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2056'>UNDERTOW-2056</a>] -         CVE-2022-1259 Replace AbstractFramedStreamSinkChannel.awaitWritable by a timeout task
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2075'>UNDERTOW-2075</a>] -         AbstractFramedChannel should …

[WFCORE-6302] CVE-2022-1259 Upgrade Undertow to 2.3.6.Final

---

pom.xml

upstream #5507 
Jira issue: https://issues.redhat.com/browse/WFCORE-6302

[20.x][WFCORE-6302] CVE-2022-1259 Upgrade Undertow to 2.3.6.Final

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
controller/src/main/java/org/jboss/as/controller/ModelController.java
controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
controller/src/test/java/org/jboss/as/controller/MetricsRegistrationTestCase.java
controller/src/test/java/org/jboss/as/controller/MetricsUndefinedValueUnitTestCase.java
controller/src/test/java/org/jboss/as/controller/MockModelController.java
controller/src/test/java/org/jboss/as/controller/ModelControllerClientTestCase.java
controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
controller/src/test/java/org/jboss/as/controller/OperationTimeoutUnitTestCase.java
controller/src/test/java/org/jboss/as/controller/TestModelControllerService.java
controller/src/test/java/org/jboss/as/controller/notification/GlobalNotificationsTestCase.java
controller/src/test/java/org/jboss/as/controller/notification/NotificationCompositeOperationTestCase.java
controller/src/test/java/org/jboss/as/controller/notification/OperationWithManyStepsTestCase.java
controller/src/test/java/org/jboss/as/controller/notification/OperationWithNotificationTestCase.java
controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServicesImpl.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
platform-mbean/src/test/java/org/jboss/as/platform/mbean/PlatformMBeanResourceUnitTestCase.java
platform-mbean/src/test/java/org/jboss/as/platform/mbean/PlatformMBeanTestModelControllerService.java
server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java

https://issues.redhat.com/browse/WFCORE-6320
The bulk of the change is cleaning up test use of the deprecated methods.

[WFCORE-6320] Remove deprecated ModelController methods

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/network/main/module.xml
network/pom.xml

https://issues.redhat.com/browse/WFCORE-6354

WFCORE-6354 Remove obsolete org.jboss.msc dependency from org.jboss.as.network

---

server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java

* When pulling from a remote repository the first time we set it to the 'origin' remote name.
Jira: https://issues.redhat.com/browse/WFCORE-6339

[WFCORE-6339]: Define remote name as origin if none is defined.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6363
https://issues.redhat.com/browse/WFCORE-6364
Release Notes - WildFly Elytron - Version 2.2.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2354'>ELY-2354</a>] -         Failing tests on latest IBM Semeru Runtime Certified Edition 11.0.15.0
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2381'>ELY-2381</a>] -         LdapSecurityRealm can return duplicated values for filtered attributes
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2457'>ELY-2457</a>] -         Swallowed exception in KeyStoreCredentialStore.flush
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2475'>ELY-2475</a>] -         Use the primitive boolean expression in DelegatingAuthConfigFactory 
</li>
<li>[<a …

[WFCORE-6364][WFCORE-6363] WildFly Elytron component upgrades

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
server/src/main/java/org/jboss/as/server/controller/git/GitConfigurationPersister.java
server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/GitRepositoryTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6351

[WFCORE-6351] The publish-configuration command doesn't throw an error when the git location is invalid

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/invocation/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authentication/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/security/jacc/api/main/module.xml
core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/javax/interceptor/api/main/module.xml
core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/javax/json/api/main/module.xml
core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/javax/security/auth/message/api/main/module.xml
core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/javax/security/jacc/api/main/module.xml

Jira issues:
https://issues.redhat.com/browse/WFCORE-6367
https://issues.redhat.com/browse/WFCORE-6366

[WFCORE-6366][WFCORE-6367] Deprecate the javax.* alias modules; replace dependencies on them with the jakarta.* ones 

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6373
Release Notes - WildFly Elytron EE - Version 3.0.3.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYEE-36'>ELYEE-36</a>] -         ElytronCallerDetailsResolver.getPrincipalsByType does not include subtypes
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYEE-38'>ELYEE-38</a>] -         Release WildFly Elytron EE 3.0.3.Final
</li>
</ul>

[WFCORE-6373] Upgrade WildFly Elytron EE to 3.0.3.Final

---

discovery/src/test/java/org/wildfly/extension/discovery/DiscoverySubsystemTestCase.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractSubsystemSchemaTest.java

https://issues.redhat.com/browse/WFCORE-6328
Reduces boilerplate code for subsystem parsing tests that enumerate their namespace versions via SubsystemSchema.

WFCORE-6328 Add AbstractSubsystemTest subclass for use with tests parameterized via SubsystemSchema

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6403
Release Notes - WildFly Elytron - Version 2.2.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2564'>ELY-2564</a>] -         Add the ability to disable OIDC access token &quot;typ&quot; claim validation via a system property
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2565'>ELY-2565</a>] -         Update actions/checkout in Elytron website workflow to v3
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2391'>ELY-2391</a>] -         Add a test case to BasicAuthenticationMechanismTest that attempts to use the wrong password for the user
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2558'>ELY-2558</a>] -         Update assertions in …

[WFCORE-6403] Upgrade WildFly Elytron to 2.2.1.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

https://issues.redhat.com/browse/WFCORE-6405
The `org.wildfly.extension.elytron` module was originally public as there were some classes in the Elytron subsystem that custom components needed access to in order to implement them.
There are currently still two Elytron custom components that rely on needing to implement interfaces from the Elytron subsystem:
* `custom-principal-transformer` relies on a `org.wildfly.extension.elytron.capabilities.PrincipalTransformer` implementation
* `custom-credential-security-factory` relies on a `org.wildfly.extension.elytron.capabilities.CredentialSecurityFactory` implementation
This PR updates `custom-principal-transformer` and `custom-credential-security-factory` so they can be used without needing to implement classes from the Elytron subsystem. …

[WFCORE-6405] Make the org.wildfly.extension.elytron module private

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-6408

[WFCORE-6408] Introducing new DEPENDENCIES_JDBC_DRIVER phase

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6305

[WFCORE-6305] Upgrade to Jandex 3.1.1

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6418
Release Notes - Elytron Web - Version 4.0.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-209'>ELYWEB-209</a>] -         Release Elytron Web 4.0.0.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-208'>ELYWEB-208</a>] -         Upgrade Undertow to 2.3.7.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-210'>ELYWEB-210</a>] -         Upgrade Elytron to 2.2.1.Final
</li>
</ul>

[WFCORE-6418] Upgrade Elytron Web to 4.0.0.Final

---

controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java

https://issues.redhat.com/browse/WFCORE-6369
Fix improper use of Set in AbstractAddStepHandler.Parameters, since AttributeDefinition is not hashable.

WFCORE-6369 Eliminate unnecessary collection copying in AbstractAddStepHandler constructors

---

cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueCallbackHandler.java
cli/src/test/java/org/jboss/as/cli/parsing/test/ArgumentValueConverterTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6424

Fix for WFCORE-6424, Generic command argument value issue with List containing Object

---

testsuite/manualmode/pom.xml
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/ProcessUuidTestCase.java

Tests if the server starts when the process UUID is invalid or removed.
Tests if the correct warning messages are logged.
Test case for [WFCORE-6290](https://issues.redhat.com/browse/WFCORE-6290)

[WFCORE-6290] Tests if the server starts when the process UUID is invalid or removed.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6429

[WFCORE-6429] Upgrade Eclipse Parsson from 1.1.2 to 1.1.3.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6427

WFCORE-6427 Upgrade jboss-logging from 3.4.3.Final to 3.5.3.Final

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
controller/src/main/java/org/jboss/as/controller/OperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderAddHandler.java
discovery/src/main/java/org/wildfly/extension/discovery/StaticDiscoveryProviderAddHandler.java

https://issues.redhat.com/browse/WFCORE-6397
Overload CapabilityServiceTarget.addService() to return CapabilityServiceBuilder<?>
Analog of ServiceTarget.addService(). Eliminates need to specify the RuntimeCapability twice when building the service for a capability.
https://issues.redhat.com/browse/WFCORE-6398
Add single argument CapabilityServiceBuilder.provides(...) method - avoiding unnecessary array allocation for most use cases.
https://issues.redhat.com/browse/WFCORE-6399
OperationContext.getServiceTarget() and getCapabilityServiceTarget() return the same object. Deprecate the former in favor of the latter.
~~Requires https://github.com/wildfly/wildfly-core/pull/5546~~ UPDATE: This was merged.  Rebased on main.

WFCORE-6397/WFCORE-6398/WFCORE-6399 CapabilityServiceTarget/CapabilityServiceBuilder enhancements

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/RequirementServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/RequirementServiceTarget.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java

https://issues.redhat.com/browse/WFCORE-6400
N.B. The interfaces extracted from CapabilityServiceTarget/CapabilityServiceBuilder intentionally override only non-deprecated MSC ServiceTarget/ServiceBuilder methods.
Technically, the proposed modification to the DeploymentPhaseContext.getServiceTarget() return type, while source-compatible, is not binary-compatibile.
I assumed this would be an acceptable change, since the org.wildfly.core:wildfly-server module is private, and this would only affect external subsystems that perform service installation from a custom DeploymentUnitProcessor.

WFCORE-6400 Update DeploymentPhaseContext to return a ServiceTarget capable of resolving capability requirements.

---

server/src/main/java/org/jboss/as/server/ServerEnvironmentService.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
server/src/main/java/org/jboss/as/server/deployment/ManagedExplodedContentServitor.java
server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java

Issue: https://issues.redhat.com/browse/WFCORE-6321

WFCORE-6321 Expose ServerEnvironment via a capability

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6444
Upstream: #5596

[WFCORE-6444] Upgrade BouncyCastle to 1.76.

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6448

[WFCORE-6448] Upgrade Eclipse Parsson from 1.1.3 to 1.1.4

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java

Issue: https://issues.redhat.com/browse/WFCORE-6433

[WFCORE-6433] ServerGroupResourceDefinition registered DomainServerLifecycleHandlers in the wrong place

---

core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6435
Adds EAP_8_0_0_TEMP as a temporal Model Controller version for testing and upgrades wildfly.legacy.test to 8.0.0.Final

[WFCORE-6435] Make WildFly 29 available in ModelTestControllerVersion

---

controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java

Issue: https://issues.redhat.com/browse/WFCORE-5305

WFCORE-5305 Response warnings don't propagate up in read-resource response assembly

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java

[https://issues.redhat.com/browse/WFCORE-6349](https://issues.redhat.com/browse/WFCORE-6349)

[WFCORE-6349] Log yaml files used for configuration extension

---

README.md

Issue: https://issues.redhat.com/browse/WFCORE-6460

[WFCORE-6460] Fix the naming of build directory in Readme.md

---

server/src/main/java/org/jboss/as/server/ServerEnvironment.java

* checking for empty string and not just null values
Jira: https://issues.redhat.com/browse/WFCORE-6458

[WFCORE-6458]: $HOSTNAME being set to "" prevents qualified hostname resolution

---

pom.xml
testsuite/pom.xml

https://issues.redhat.com/browse/WFCORE-6454
This change utilizes new TCP/IP communication for surefire execution [1].
By default, the communication writes to STDOUT which may lead to similar messages in the execution output if something else also writes there at wrong time:
```
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1.
See FAQ web page and the dump file ... .dumpstream.
```
This change should mittigate such warnings and also should reduce number of open files during execution which may lead to crash on some systems with `nofile` limit set quite low.
Truth is that this issue hasn't been seen in this upstream WildFly Core project, still I believe this change should be beneficial avoiding eventual issue in the future.
[1] …

[WFCORE-6454] Use TCP/IP process communication for surefire plugin

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6467
Release Notes - XNIO - Version 3.8.10.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-421'>XNIO-421</a>] -         Move failedToCloseSslEngine log message to debug level
</li>
</ul>

[WFCORE-6467] Upgrade XNIO to 3.8.10.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6468
Release Notes - Undertow - Version 2.3.8.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2228'>UNDERTOW-2228</a>] -         [GSS](7.4.z) Undertow write-timeout can cause a truncate response for request coming through keep-alive connection
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2275'>UNDERTOW-2275</a>] -         Undertow read-timeout can close connection unexpectedly before returning response for POST request larger than the default buffer size
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2281'>UNDERTOW-2281</a>] -         Undertow HTTP2 breaks protocol specification when client misbehaves
</li>
<li>[<a …

[WFCORE-6468] Upgrade Undertow to 2.3.8.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6475
Release Notes - WildFly Elytron - Version 2.2.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2550'>ELY-2550</a>] -         Add option to skip certificate verification with the realm when using SASL EXTERNAL
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2587'>ELY-2587</a>] -         Release WildFly Elytron 2.2.2.Final
</li>
</ul>

[WFCORE-6475] Upgrade WildFly Elytron to 2.2.2.Final

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java

add operation.
* If an ADD operation isn't defined and the resource doesn't have attributes then we will get a NPE
Issue: https://issues.redhat.com/browse/WFCORE-6477.

[WFCORE-6477]: Possible NPE in YAMLExtension for some resource without a

---

core-feature-pack/common/src/main/resources/content/bin/common.bat
core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/common.sh
host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
pom.xml

https://issues.redhat.com/browse/WFCORE-4296
https://issues.redhat.com/browse/WFCORE-5406
This PR follows up on:
* https://github.com/wildfly/wildfly-core/pull/4728
* https://github.com/wildfly/wildfly-core/pull/4728
This PR replaces:
* https://github.com/wildfly/wildfly/pull/15208

[WFCORE-4296][WFCORE-5406] Add required --add-opens for java.base/com.sun.net.ssl.internal.ssl when HTTPS is configured

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6495

[WFCORE-6495] Upgrade FasterXML Jackson to 2.15.2

---

core-feature-pack/common/src/main/resources/content/bin/common.bat

Jira issue: https://issues.redhat.com/browse/WFCORE-6502
Remove the usage of setLocal/endLocal on common.bat that makes any variable configuration on common.conf.bat are ignored since the environment is restored to the original one after loading common.conf.bat.

[WFCORE-6502] Fix variable configuration on common.conf.bat are ignored

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-6501
Dev tag: https://github.com/jbossas/staxmapper/releases/tag/1.5.0.Final
Diff to previous integrated release: https://github.com/jbossas/staxmapper/compare/1.4.0.Final...1.5.0.Final
Staxmapper 1.5.0.Final is relicensed with the Apache Software License 2.0.
There are no API changes in that release compared to the previous 1.4.0.Final release.

[WFCORE-6501] Upgrade StAXMapper 1.5.0.Final

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-6500
Dev tag: https://github.com/jbossas/jboss-dmr/releases/tag/1.7.0.Final
Diff to previous integrated release: https://github.com/jbossas/jboss-dmr/compare/1.6.1.Final...1.7.0.Final
JBoss DMR 1.7.0.Final is relicensed with the Apache Software License 2.0.
There are no API changes in that release compared to the previous 1.6.1.Final release.
<details>
<summary>Release Notes - DMR - Version 1.7.0.Final</summary>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/DMR-50'>DMR-50</a>] -         Relicense JBoss DMR with Apache License 2.0
</li>
<li>[<a href='https://issues.redhat.com/browse/DMR-51'>DMR-51</a>] -         Add GitHub action to test JBoss DMR 
</li>
<li>[<a …

[WFCORE-6500] Upgrade JBoss DMR 1.7.0.Final

---

host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java

https://issues.redhat.com/browse/WFCORE-6506

[WFCORE-6506] Initial Java releases contain neither minor nor micro part in the version string - adjusting tests

---

ide-configs/eclipse/wildfly-templates.xml

https://issues.redhat.com/browse/WFCORE-6529

WFCORE-6529 Update Eclipse IDE templates to use new copyright header

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/OpenSslTlsTestCase.java

https://issues.redhat.com/browse/WFCORE-4532

[WFCORE-4532] Enable security tests on JDK14+ since they no longer fail

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/DeploymentDuplicationTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6524

[WFCORE-6524] Do not duplicate managed deployment in content repository in tmp/vfs/temp directory

---

cli/src/main/java/org/jboss/as/cli/gui/JConsoleCLIPlugin.java
controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerAdd.java
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/ProcessControllerConnectionService.java
host-controller/src/main/java/org/jboss/as/host/controller/mgmt/ServerToHostOperationHandlerFactoryService.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java
server/src/main/java/org/jboss/as/server/deployment/module/TempFileProviderService.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainControllerClientConfig.java
threads/src/main/java/org/jboss/as/threads/ThreadFactoryService.java

https://issues.redhat.com/browse/WFCORE-6505
This is wildfly-core part of eliminating duplicate thread groups creation.
I tried to remove the thread groups and instead inject the group name string straight into the name pattern, where it was used by ("%G - ...").

WFCORE-6505 Avoid creating duplicate thread groups on server reload

---

cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java
cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
cli/src/test/java/org/jboss/as/cli/parsing/test/AttributeNamePathCompletionTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java

https://issues.redhat.com/browse/WFCORE-4916
After types List, Object and String are added ",", if there are more attributes to come or ")" if this is the last one. 

[WFCORE-4916] Unclear attribute name completion for LIST type

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6486
The test seems the culprit there, we should introduce some timeout prior to assert that the trace has not been printed.

Fix for WFCORE-6486, CLIEmbedHostControllerTestCase fails randomly with JDK 17 Jobs

---

controller/src/main/java/org/jboss/as/controller/access/constraint/SensitivityClassification.java
controller/src/main/java/org/jboss/as/controller/operations/common/ResolveExpressionHandler.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ResolveExpressionTestCase.java

https://issues.redhat.com/browse/WFCORE-6544
https://access.redhat.com/security/cve/CVE-2023-4061

[WFCORE-6544] CVE-2023-4061 Management RBAC permission allows unexpected reading of system-properties via resolve-expression

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
controller/src/main/java/org/jboss/as/controller/BootErrorCollector.java
core-model-test/tests/src/test/java/org/jboss/as/core/model/test/deployment/StandaloneDeploymentUnicityTestCase.java
core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTestCase.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6383
With this fix the `ModelTestControllerService.boot()` always throws new `BootOperationFailedException` if `super.boot` returns `false`.
Note that a few test-cases had to be changed according to it.
Regarding "BTW, I think the entire class can and should be package protected, but if there's some outside use I've missed, then never mind.", it is not possible as `BootErrorCollector` is also used outside the package.
Note 2: This will need a fix in WildFly code base in two PicketLink Subsystem tests. I will create a separate Jira for it.

[WFCORE-6383] throwing boot errors if super.boot fails

---

pom.xml

* Upgrading jgit version:https://projects.eclipse.org/projects/technology.jgit/releases/6.7.0
* Explicit dependency on common-codec
Issue: https://issues.redhat.com/browse/WFCORE-6527

[WFCORE-6527]: Upgrade JGit from 6.6.0.202305301015-r to 6.7.0.202309050840-r

---

pom.xml

Jira:
https://issues.redhat.com/browse/WFCORE-6555
Release Notes - Undertow - Version 2.3.9.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2072'>UNDERTOW-2072</a>] -         DefaultByteBufferPool.getBuffer() may return null
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2271'>UNDERTOW-2271</a>] -         CVE-2023-3223 Large uploaded file does not persist to disk if the filename is omitted
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2296'>UNDERTOW-2296</a>] -         Wrong type in INCLUDE_MAPPING request attribute
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2305'>UNDERTOW-2305</a>] -         NPE from Http2ClearClientProvider#createSettingsFrame()
</li>
<li>[<a …

[WFCORE-6555] CVE-2023-3223 Upgrade Undertow to 2.3.9.Final

---

elytron/pom.xml

https://issues.redhat.com/browse/WFCORE-6556

[WFCORE-6556] Fixing JDK11 illegal access warnings in Elytron tests

---

elytron/src/test/resources/logging.properties

https://issues.redhat.com/browse/WFCORE-6548

[WFCORE-6548] Unify test logging in elytron module

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6557
See: https://access.redhat.com/security/cve/CVE-2023-44487
This is a test-only dependency
Upstream: #5714

[22.x][WFCORE-6557] CVE-2023-44487 Upgrade Netty to 4.1.100.Final

---

testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java

https://issues.redhat.com/browse/WFCORE-6538

[WFCORE-6538] ClosedChannelException is thrown intermittently instead of SaslException when using GS2_KRB5 with TLS

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6555
Upstream: #5710

[22.x][WFCORE-6555] CVE-2023-3223 Upgrade Undertow to 2.3.9.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6547
Upstream PR: https://github.com/wildfly/wildfly-core/pull/5704

[22.x][WFCORE-6547] Upgrading JBoss Marshalling to 2.1.3.SP1

---

testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java

https://issues.redhat.com/browse/WFCORE-6532

[WFCORE-6532] Add security manager to script tests

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6564

[WFCORE-6564] Upgrade Undertow to 2.3.10.Final (CVE-2023-44487)

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6572
Release Notes - XNIO - Version 3.8.12.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-425'>XNIO-425</a>] -         Use configured client address for secured client connections if it is available
</li>
</ul>

[WFCORE-6572] Upgrade XNIO to 3.8.12.Final

---

elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties

Modify description in elytron of subsystem to its correct sentence.
https://issues.redhat.com/browse/WFCORE-6568

[WFCORE-6568] - Modify description in elytron subsystem 

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6563
[WFCORE-6563] remove obsolete pre-Galleon WildFly build and provisioning tools

[WFCORE-6563] remove obsolete pre-Galleon WildFly build and provisioning tools

---

server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java

Fixes: https://issues.redhat.com/browse/WFCORE-6445

[WFCORE-6445] Update ModuleSpecification.getMutableUserDependencies 

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6590

[WFCORE-6590] Upgrade commons-lang3 from 3.12.0 to 3.13.0

---

core-feature-pack/common/src/main/resources/content/bin/common.ps1

Issue: https://issues.redhat.com/browse/WFCORE-6597
please see more info in the Jira issue.
I will send the fix for WFLY once this is approved. Thanks.

[WFCORE-6597] Fix package availability detection in ps1 script

---

core-feature-pack/common/src/main/resources/content/bin/domain.bat
core-feature-pack/common/src/main/resources/content/bin/domain.conf
core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.sh
core-feature-pack/common/src/main/resources/content/bin/standalone.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.conf
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.sh

Issue: https://issues.redhat.com/browse/WFCORE-6578
Fixes: https://access.redhat.com/security/cve/CVE-2023-3171

[WFCORE-6578] CVE-2023-3171 WildFly heap exhaustion via deserialization

---

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6255

[WFCORE-6255] Deployment scanner did not undeploy failed archives

---

server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java

https://issues.redhat.com/browse/WFCORE-6601
https://issues.redhat.com/browse/WFCORE-6607
https://issues.redhat.com/browse/WFCORE-6608
The expectation is this will also fix https://issues.redhat.com/browse/WFCORE-6606, but resolving that should depend upon a successful TCK run.

[WFCORE-6601][WFCORE-6607][WFCORE-6608] ModuleSpecification dependency tracking fixes

---

elytron/pom.xml
elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SaslTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
pom.xml
testbom/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6609 remove obsolete JMockit

[WFCORE-6609] remove obsolete JMockit

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml

Issue: [WFCORE-6625](https://issues.redhat.com/browse/WFCORE-6625)
The EDL was originally added with PR #4103 but I couldn't find a reason why.

WFCORE-6625: remove org.glassfish:jakarta.json license info

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6618

[WFCORE-6618] Upgrade BouncyCastle from 1.76 to 1.77

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6636

[WFCORE-6636] Upgrade log42-jboss-logmanager to 1.1.2.Final.

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6637

[WFCORE-6637] Upgrade commons-lang3 from 3.13.0 to 3.14.0

---

cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironmentWrapper.java
host-controller/src/main/java/org/jboss/as/host/controller/Main.java
host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostInfo.java
process-controller/src/main/java/org/jboss/as/process/CommandLineArgumentUsageImpl.java
process-controller/src/main/java/org/jboss/as/process/Main.java
server/src/main/java/org/jboss/as/server/CommandLineArgumentUsageImpl.java
server/src/main/java/org/jboss/as/server/Main.java
server/src/main/java/org/jboss/as/server/ServerEnvironment.java
version/src/main/java/org/jboss/as/version/ProductConfig.java

https://issues.redhat.com/browse/WFCORE-6221
This pull request formalizes the concept of a quality level in the WildFly kernel based on the general strategy described in WFCORE-6221.
In general, a subsystem associate features within its management model with a specific Quality.  During management registration, only those features enabled by the quality level of the server will be registered.
See the test case here for an example of how I imagined this might work: https://github.com/pferraro/wildfly-core/tree/WFCORE-6221/subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/quality
Please scrutinize.  Tell me what you like and do not like.

WFCORE-6221 Add formal experimental/preview mode to management model

---

pom.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Log4j2LoggingProfilesTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6644
@yersan Feel free to use this PR or change #5799 if you'd rather have it all in one commit.

[WFCORE-6644] Upgrade log4j2 from 2.19.0 to 2.22.0

---

subsystem/src/main/java/org/wildfly/subsystem/resource/capability/RuntimeCapabilityProvider.java

WFCORE-6347 Drop redundant getCapabity() method.

---

subsystem/src/main/java/org/wildfly/subsystem/service/ResourceServiceConfigurator.java
subsystem/src/main/java/org/wildfly/subsystem/service/ResourceServiceInstaller.java

WFCORE-6347 Add convenience method for generating a composite ResourceServiceConfigurator.

---

controller/src/main/java/org/jboss/as/controller/FeatureRegistry.java
discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
subsystem/src/main/java/org/wildfly/subsystem/SubsystemConfiguration.java
subsystem/src/main/java/org/wildfly/subsystem/SubsystemExtension.java
subsystem/src/main/java/org/wildfly/subsystem/SubsystemPersistence.java

https://issues.redhat.com/browse/WFCORE-6651
Also, removes the default implementation of FeatureRegistry.getStability(), as this should no longer be needed for full-integration tests to pass.

WFCORE-6651 Update generic Extension implemention in wildfly-subsystem to only register parsers for schemas enabled by the current stability level.

---

controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
service/src/main/java/org/wildfly/service/descriptor/BinaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/NullaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/QuaternaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/ServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/TernaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/UnaryServiceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceRecorder.java
subsystem/src/test/java/org/wildfly/subsystem/resource/capabilty/CapabilityReferenceRecorderTestCase.java

Useful when a subsystem needs to interact with a non-public view of the provided service.

WFCORE-6347 Add method to cast service descriptor instance as subtype.

---

controller/src/main/java/org/jboss/as/controller/operations/common/XmlMarshallingHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java

* Making te operation deprecated if run on 'community' stability.
Issue: https://issues.redhat.com/browse/WFCORE-6648

[WFCORE-6648]: Mark "read-config-as-xml" as deprecated on Community stream.

---

cli/pom.xml
testsuite/shared/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6656

Fix for WFCORE-6656, CLI, shaded jar can't start embedded when logging json formater configured

---

testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java

https://issues.redhat.com/browse/WFCORE-6538

[WFCORE-6538] Prepare test suite for upcoming JBoss Remoting & XNIO releases

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6667
Release Notes - WildFly Elytron - Version 2.2.3.Final
Task
*    [ELY-2570](https://issues.redhat.com/browse/ELY-2570) - Add newly added constants for bearer-only support to org.wildfly.security.http.oidc.Oidc
* [ELY-2583](https://issues.redhat.com/browse/ELY-2583) - Make requestURI and Source-Address available from RealmSuccessfulAuthenticationEvent and RealmFailedAuthenticationEvent
Release
*    [ELY-2712](https://issues.redhat.com/browse/ELY-2712) - Release WildFly Elytron 2.2.3.Final

[WFCORE-6667] Upgrade WildFly Elytron to 2.2.3.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java

https://issues.redhat.com/browse/WFCORE-6627
**Requires**: ELY-2583 :  https://github.com/wildfly-security/wildfly-elytron/pull/1952 
so **requires** Elytron 2.2.3.Final component upgrade: https://github.com/wildfly/wildfly-core/pull/5835

[WFCORE-6627] Make use of the SetRequestInformationMechanismFactory to set the request information during HTTP authentication

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6664

[WFCORE-6664] Upgrade SLF4J from 2.0.9 to 2.0.11

---

core-feature-pack/common/src/main/resources/content/bin/domain.sh
core-feature-pack/common/src/main/resources/content/bin/standalone.sh

Jira issue: https://issues.redhat.com/browse/WFCORE-6531
The SERVER_OPTS were being wrapped in single quotes, which does not prevent a misuse using eval. Wrap them in double quotes.

[WFCORE-6531] Wrap server options in double quotes

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6676
Resolves [CVE-2023-48795](https://github.com/advisories/GHSA-45x7-px36-x8w8) / https://github.com/apache/mina-sshd/issues/445

[WFCORE-6676] CVE-2023-48795 Upgrade Apache Mina SSHD to 2.12.0

---

pom.xml

upstream: #5844 
Jira issue: https://issues.redhat.com/browse/WFCORE-6676

[23.x] [WFCORE-6676] CVE-2023-48795 Upgrade SSHD from 2.11.0 to 2.12.0

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6677

[WFCORE-6677] Bump the core management version to version 25

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6692
Release Notes - WildFly Elytron - Version 2.3.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1700'>ELY-1700</a>] -         Intermittently failing AttributeMappingSuiteChild
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2576'>ELY-2576</a>] -         Make it possible to use DigestPasswords when using the DIGEST-SHA-256 and DIGEST-SHA-512-256 HTTP Digest authentication mechanisms
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2658'>ELY-2658</a>] -         Remove the unassigned call to the constructor in X500AttributePrincipalDecoderTest#testDecodeWithConcatenation
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2717'>ELY-2717</a>] -         Ensure that the credential algorithm …

[WFCORE-6692] Upgrade WildFly Elytron to 2.3.0.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6695
Release Notes - Undertow - Version 2.3.11.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2304'>UNDERTOW-2304</a>] -         Prevent repeating SslConduit.doUnwrap under task thread exhaustion conditions
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2309'>UNDERTOW-2309</a>] -         Possible memory leak in DefaultByteBufferPool
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2330'>UNDERTOW-2330</a>] -         &quot;UT000131: Buffer pool is closed&quot; when server is stopping
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2337'>UNDERTOW-2337</a>] -         Multipart form-data larger than 16KiB is not available through Servlet getParameter API
</li> …

[WFCORE-6695] CVE-2023-4639 Upgrade Undertow to 2.3.11.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml
core-feature-pack/galleon-common/src/main/resources/layers/standalone/elytron/layer-spec.xml
elytron/src/main/java/org/wildfly/extension/elytron/JaasCustomSecurityRealmWrapper.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
testsuite/elytron/pom.xml
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/JaasCustomRealmWrapperTest.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TestCallbackHandler.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TestLoginModule.java
testsuite/elytron/src/test/resources/org/wildfly/test/security/common/elytron/jaas-login.config
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java

https://issues.redhat.com/browse/WFCORE-6411
Related PR for wildfly repo : https://github.com/wildfly/wildfly/pull/17077
Supersedes https://github.com/wildfly/wildfly-core/pull/5587
I have made the updates @yersan suggested in https://github.com/wildfly/wildfly-core/pull/5587 to remove the the `javax.xml.stream.api` dependency from `org.wildfly.extension.elytron.jaas-realm` and opened this new PR since @Skyllarr is on PTO.

[WFCORE-6411] Make it possible to use JaasSecurityRealm via a custom-realm resource

---

pom.xml

Backport #5858 to 23.x
Jira issue: https://issues.redhat.com/browse/WFCORE-6695

[23.x] [WFCORE-6695] CVE-2023-4639 Upgrade Undertow to 2.3.11.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6702
https://issues.redhat.com/browse/WFCORE-6703
Release Notes - WildFly Elytron - Version 2.3.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2589'>ELY-2589</a>] -         Elytron SSO does not expire other application sessions for session invalidation like Undertow SSO promptly following sessionid change
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2720'>ELY-2720</a>] -         Release WildFly Elytron 2.3.1.Final
</li>
</ul>
Release Notes - Elytron Web - Version 4.1.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-211'>ELYWEB-211</a>] -         Update branches in pr-ci.yaml to add 4.x
</li>
<li>[<a …

[WFCORE-6702]/[WFCORE-6703] Elytron component upgrades

---

pom.xml

23.x PR: #5876 
Jiras:
https://issues.redhat.com/browse/WFCORE-6707 - relates to CVE-2024-1635
https://issues.redhat.com/browse/WFCORE-6708 - relates to CVE-2024-1635
https://issues.redhat.com/browse/WFCORE-6709 - fixes CVE-2023-5379 CVE-2024-1459 CVE-2024-1635
Release Notes - XNIO - Version 3.8.13.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-427'>XNIO-427</a>] -         ClosedChannelException when NioSocketConduit.handleReady invokes write listener after read listener closes connection
</li>
</ul>
Release Notes - JBoss Remoting (3+) - Version 5.0.28.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-404'>REM3-404</a>] -         Remoting connections closed during greetings exchange after HTTP upgrade are not …

[WFCORE-6707][WFCORE-6708][WFCORE-6709] CVE-2023-5379 CVE-2024-1459 CVE-2024-1635 Upgrade Undertow, XNIO and JBoss Remoting

---

server/src/main/java/org/jboss/as/server/controller/resources/ModuleLoadingResourceDefinition.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ModuleLoadingManagementTestCase.java

Issue: [WFCORE-6697](https://issues.redhat.com/browse/WFCORE-6697)
The operation is deprecated so I don't know if we want to fix this.

WFCORE-6697: fix resource location check

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java

https://issues.redhat.com/browse/WFCORE-6685

[WFCORE-6685] CLIEmbedServerTestCase.testStdOutEcho fails intermittently

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentUnit.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitImpl.java
server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java

https://issues.redhat.com/browse/WFCORE-6650

WFCORE-6650 Expose server stability and allow feature filtering from a DeploymentUnit.

---

server/src/main/java/org/jboss/as/server/Main.java

to start a server.
* If no value is defined for yaml o git command line options we should fail.
Jira: https://issues.redhat.com/browse/WFCORE-6717

[WFCORE-6717]: Incorrectly set options on the command line should fail

---

controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
controller/src/main/java/org/jboss/as/controller/extension/UnstableSubsystemNamespaceParser.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
controller/src/test/java/org/jboss/as/controller/extension/ExtensionRegistryTestCase.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/ApplyExtensionsHandler.java
subsystem/src/main/java/org/wildfly/subsystem/SubsystemExtension.java
subsystem/src/main/java/org/wildfly/subsystem/SubsystemPersistence.java

https://issues.redhat.com/browse/WFCORE-6742
Requires https://github.com/wildfly/wildfly-core/pull/5899

WFCORE-6742 SubsystemExtension needs the ability to define the current model/schema version given the stability level of the process

---

controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
controller/src/main/java/org/jboss/as/controller/extension/UnstableSubsystemNamespaceParser.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
controller/src/test/java/org/jboss/as/controller/extension/ExtensionRegistryTestCase.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/ApplyExtensionsHandler.java

https://issues.redhat.com/browse/WFCORE-6652
https://issues.redhat.com/browse/WFCORE-6741
Rather than skip parser registration of unsupported extensions (or unsupported schemas of a supported extension) entirely, register its namespaces using a placeholder parser throwing an informative message.

[WFCORE-6741] [WFCORE-6652] Improve user experience when using extension or namespace of unsupported stability.

---

installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrInitialization.java
installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrService.java
installation-manager/src/main/java/org/wildfly/core/instmgr/logging/InstMgrLogger.java

https://issues.redhat.com/browse/WFCORE-6560
Draft for now what we log is expected to change. This just dumps what's currently available with no particular attempt at formatting.
@yersan @spyrkob FYI

[WFCORE-6560] Log installation provisioning information at boot

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6758
Depends on https://github.com/wildfly/wildfly/pull/17755
Release Notes - WildFly Elytron - Version 2.4.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2724'>ELY-2724</a>] -         TLS13AuthenticationTest needs to be updated to run with SE 21
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2725'>ELY-2725</a>] -         Update CommunicationSuiteChild so it can run with SE 21
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2726'>ELY-2726</a>] -         Update AlternateSecurityManagerTest to be able to run with SE 21
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2728'>ELY-2728</a>] -         Update japicmp-maven-plugin to a more recent version
</li>
</ul>
<h2>        Feature …

[WFCORE-6758] Upgrade WildFly Elytron to 2.4.0.CR1

---

server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/test/java/org/jboss/as/server/ServerEnvironmentTestCase.java

Issue: [WFCORE-4868](https://issues.redhat.com/browse/WFCORE-4868)
Documentation PR: wildfly/wildfly#17751

WFCORE-4868: implement aliases for standalone configuration files

---

core-feature-pack/galleon-feature-pack/pom.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6762
The reason of this upgrade is the rename of galleon plugins Maven plugin stability options (suffixed with '-level').

Fix for WFCORE-6762, Upgrade to Galleon 6.0.0.Beta5 and Galleon Plugins 7.0.0.Beta6

---

server/src/main/java/org/jboss/as/server/Main.java

Issue: https://issues.redhat.com/browse/WFCORE-6749 Fix incorrect output from standalone.sh -v
This handles the argument `version` late and recreate `productConfig` using updated properties

[WFCORE-6749] Fix incorrect output from standalone.sh -v

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6775

[WFCORE-6775] Upgrade Eclipse Parsson from 1.1.5 to 1.1.6

---

controller/src/main/java/org/jboss/as/controller/xml/SimpleVersionedNamespace.java
controller/src/main/java/org/jboss/as/controller/xml/VersionedFeature.java
controller/src/main/java/org/jboss/as/controller/xml/VersionedNamespace.java
controller/src/main/java/org/jboss/as/controller/xml/VersionedSchema.java
controller/src/main/java/org/jboss/as/controller/xml/VersionedURN.java
controller/src/test/java/org/jboss/as/controller/xml/VersionedNamespaceTestCase.java

https://issues.redhat.com/browse/WFCORE-6765
It's become clear to me that schema namespace comparisons should be stability-aware.
See jira for details.

WFCORE-6765 Schema version comparison should require compatible stability level

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Arguments.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-6776

Fix for WFCORE-6776, Can't specify a stability level when starting a bootable JAR.

---

controller/src/main/java/org/jboss/as/controller/OperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/capability/CapabilityServiceSupport.java
controller/src/test/java/org/jboss/as/controller/SocketCapabilityResolutionUnitTestCase.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java

WFCORE-6347 Add ServiceDescriptor variants of OperationContext.hasOptionalCapability(...) and CapabilityServiceSupport.hasCapability(...)

---

elytron/pom.xml
elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/test/java/org/wildfly/extension/elytron/JwtSecurityRealmTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/jwt-realm-test.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-6780
https://issues.redhat.com/browse/WFCORE-6787
Release Notes - WildFly Elytron - Version 2.4.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2743'>ELY-2743</a>] -         CVE-2023-6236: OIDC app attempting to access the second tenant, the user should be prompted to log in
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2744'>ELY-2744</a>] -         CVE-2024-1233: Validate the jku header parameter during token validation to make sure it exactly matches a value from a configured list of allowed values
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2173'>ELY-2173</a>] -         Add test for the CLIENT_CERT mechanism
</li>
</ul>
</h2>
<ul> …

[WFCORE-6780] Upgrade WildFly Elytron to 2.4.0.Final for CVE-2024-1233 and CVE-2023-6236

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6790

Fix for WFCORE-6790, Upgrade wildfly-maven-plugin to 5.0.0.Final and wildfly-jar-maven-plugin to 11.0.0.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java

https://issues.redhat.com/browse/WFCORE-6756

[WFCORE-6756] Subsystem model bump and transformer adjustments needed for the dynamic SSLContext support

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6774
Artifacts were released but the tag was not provided yet, so adding a hold label until that situation gets resolved:, see https://github.com/bcgit/bc-java/issues/1618
This release comes with the following security advisories, see: https://www.bouncycastle.org/releasenotes.html#r1rv78
CVE-2024-29857 - Importing an EC certificate with specially crafted F2m parameters can cause high CPU usage during parameter evaluation.
CVE-2024-30171 - Possible timing based leakage in RSA based handshakes due to exception processing eliminated.
CVE-2024-30172 - Crafted signature and public key can be used to trigger an infinite loop in the Ed25519 verification code.
CVE-2024-301XX - When endpoint identification is enabled and an SSL socket is not …

[WFCORE-6774][CVE-2024-29857][CVE-2024-30171][CVE-2024-30172] Upgrade BouncyCastle from 1.77 to 1.78

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6794
Release Notes - Undertow - Version 2.3.13.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-1926'>UNDERTOW-1926</a>] -         SenderTestCase fails sporadically with ClosedConnectionException (Premature end of message body)
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2264'>UNDERTOW-2264</a>] -         CVE-2023-1973 SessionImpl objects + location strings are created and not cleaned up on authentication failures
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2347'>UNDERTOW-2347</a>] -         Undertow client must send either http/1.1 or both http/1.1 and h2 in SSL ClientHello handshake message
</li>
<li>[<a …

[WFCORE-6794] CVE-2023-1973 Upgrade Undertow to 2.3.13.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6796
Release Notes - WildFly Elytron - Version 2.4.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2705'>ELY-2705</a>] -         Update SecurityDomain#createAdHocIdentity so that it also calls SecurityDomain#transform to ensure that the securityIdentityTransformer gets used if configured
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2749'>ELY-2749</a>] -         Release WildFly Elytron 2.4.1.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2746'>ELY-2746</a>] -         Change keycloak version in testsuite to 24.0.1
</li>
</ul>

[WFCORE-6796] Upgrade WildFly Elytron to 2.4.1.Final

---

pom.xml
remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java

Built on top of https://github.com/wildfly/wildfly-core/pull/5977, this PR reverts [WFCORE-5922](https://github.com/wildfly/wildfly-core/pull/5112) that was done to ignore the intermittent failures on `RemotingLegacySubsystemTestCase` due to an XNIO issue.
Jira issue: https://issues.redhat.com/browse/WFCORE-5386

[WFCORE-5386] Revert "[WFCORE-5922] Ignore RemotingLegacySubsystemTestCase#testSubsystemWithConnectorPropertyChange test case"

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6738
Release Notes - XNIO - Version 3.8.14.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-385'>XNIO-385</a>] -         Address already in use error is shown if a stream server is closed and created again quickly
</li>
<li>[<a href='https://issues.redhat.com/browse/XNIO-423'>XNIO-423</a>] -         CVE-2023-5685 Replace the recursion in NotifierState by a iteration
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-420'>XNIO-420</a>] -         Add README and other community documents
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-428'>XNIO-428</a>] -         Test XNIO on JDK21
</li>
</ul>

[WFCORE-6738] CVE-2023-5685 Upgrade XNIO to 3.8.14.Final

---

subsystem/src/main/java/org/wildfly/subsystem/service/DeploymentServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-6806

WFCORE-6806 Add method to combine multiple DeploymentServiceInstaller

---

controller/src/main/java/org/jboss/as/controller/RequirementServiceTarget.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-6808

WFCORE-6808 Add capability-resolving variant of child ServiceTarget-based ServiceInstaller.Builder

---

controller/src/main/java/org/jboss/as/controller/ServiceNameFactory.java

https://issues.redhat.com/browse/WFCORE-6824

WFCORE-6824 ServiceNameFactory.resolveServiceName(UnaryServiceDescriptor) throws ISE if resolved to a NullaryServiceDescriptor

---

core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
pom.xml

Jira issues: 
https://issues.redhat.com/browse/WFCORE-6700
https://issues.redhat.com/browse/WFCORE-5753
https://issues.redhat.com/browse/WFCORE-6488

[WFCORE-6700][WFCORE-5753][WFCORE-6488] Introduce new version of WildFly Legacy Tests

---

core-feature-pack/galleon-common/src/main/resources/feature_groups/host-profile.xml

https://issues.redhat.com/browse/WFCORE-6823

[WFCORE-6823] Don't register the Jakarta AuthConfigFactory in the host controller.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6831
Release Notes - WildFly Elytron - Version 2.4.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2723'>ELY-2723</a>] -         Fix failures in SSLAuthenticationTestCase with SE 21
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2340'>ELY-2340</a>] -         Query parameters lost on redirect to keycloak OIDC
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2752'>ELY-2752</a>] -         Ensure it&#39;s possible to make use of a custom principal-attribute value for OIDC 
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2722'>ELY-2722</a>] -         Resolve test failures with SE 21
</li>
<li>[<a …

[WFCORE-6831] Upgrade WildFly Elytron to 2.4.2.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6833
24.x PR: #6008 
Blocks: #6004 / #6003 
Release Notes - XNIO - Version 3.8.15.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-433'>XNIO-433</a>] -         The high and low water mark configuration values have been inverted
</li>
</ul>

[WFCORE-6833] Upgrade XNIO to 3.8.15.Final

---

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/ManagementInterfaceResourcesTestCase.java

Add options to control how many management connections can be accepted and how long until they are closed after the last HTTP request.
https://issues.redhat.com/browse/WFCORE-6825
Testing will also need https://issues.redhat.com/browse/XNIO-433 as high and low watermarks are inverted.
main PR https://github.com/wildfly/wildfly-core/pull/6004

[24.x] [CVE-2024-4029] [WFCORE-6825] Options to control resources used for incomming connections.

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java

Issue: https://issues.redhat.com/browse/WFCORE-6069
@jamezp , what do you think of this possible scenario?

Fix for WFCORE-6069, PermissionsDeploymentTestCase fails intermittently on Windows - Bootable JAR Job

---

server/src/main/java/org/jboss/as/server/deployment/DelegatingSupplier.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java

https://issues.redhat.com/browse/WFCORE-6844

WFCORE-6844 DeploymentPhaseContext is missing wildfly-service integration

---

testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildFlyRunner.java

Issue: https://issues.redhat.com/browse/WFCORE-6732
Not sure if a test case needs to be added and where to add if so, please let me know :)

[WFCORE-6732] WildFlyRunner doesn't call tearDown and completed ServerSetupTasks if a later one fails in setup

---

pom.xml
testsuite/client-old-server/pom.xml
testsuite/elytron/pom.xml
testsuite/embedded/pom.xml
testsuite/manualmode/pom.xml
testsuite/pom.xml
testsuite/rbac/pom.xml
testsuite/standalone/pom.xml

* Excluding the jpda profile surefire parameters from the jmv.args system property so it doesn't interfer with the server args.
Jira: https://issues.redhat.com/browse/WFCORE-3502

[WFCORE-3502]: Fix debug options in test-runner.

---

testsuite/shared/src/main/java/org/jboss/as/test/shared/ModelParserUtils.java

Jira issue: https://issues.redhat.com/browse/WFCORE-4919
In addition, very minor clean ups and improve code readbility

[WFCORE-4919] Add a timeout parameter starting the embedded Server/Host Controller from ModelParserUtils

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6847

[WFCORE-6847] Upgrade io.smallrye:jandex from 3.1.8 to 3.2.0

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6819

[WFCORE-6819] Show current stability level with the server boot message

---

core-feature-pack/galleon-feature-pack/pom.xml
core-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6853
The stability information currently located in the maven plugin configuration has been moved to the wildfly-feature-pack-build.xml file. These are not options you should control from Maven.

Fix for WFCORE-6853, Upgrade to Galleon Plugins 7.1.0.Final

---

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java

WFCORE-6815 (https://github.com/wildfly/wildfly-core/pull/5992) removed an import required by WFCORE-6819 (https://github.com/wildfly/wildfly-core/pull/6000). Since WFCORE-6815 was merged after WFCORE-6819, it broke `main`.
Hence the fix.
Jira issue: https://issues.redhat.com/browse/WFCORE-6815

[WFCORE-6815] Add removed import that is required by WFCORE-6819

---

pom.xml

Jiras:
https://issues.redhat.com/browse/WFCORE-6860
https://issues.redhat.com/browse/WFCORE-6861
https://issues.redhat.com/browse/WFCORE-6862
Release Notes - XNIO - Version 3.8.16.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-434'>XNIO-434</a>] -         Make wakeupReads and wakeWrites invoke listener in closed channels (XNIO-427 Breaks wakeup calls contract)
</li>
</ul>
Release Notes - JBoss Remoting (3+) - Version 5.0.29.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-413'>REM3-413</a>] -         ClosedChannelException when NioSocketConduit.handleReady invokes write listener after read listener closes connection
</li>
</ul>
</h2>
<ul>
<li>[<a …

[WFCORE-6860][WFCORE-6861][WFCORE-6862] CVE-2024-6162 CVE-2024-27316 Upgrade Undertow, XNIO and JBoss Remoting

---

service/src/main/java/org/wildfly/service/Installer.java
subsystem/src/main/java/org/wildfly/subsystem/SubsystemPersistence.java

https://issues.redhat.com/browse/WFCORE-6807

WFCORE-6807 Prune deprecations from wildfly-service and wildfly-subsystem

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6867
Release Notes - WildFly Elytron - Version 2.5.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2584'>ELY-2584</a>] -         Add the ability to specify that the OIDC Authentication Request should include request and request_uri parameters
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2779'>ELY-2779</a>] -         Release WildFly Elytron 2.5.0.CR1
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2773'>ELY-2773</a>] -         After using the CAGenerationTool we should be able to use this to load key and trust managers
</li>
</ul>

[WFCORE-6867] Upgrade WildFly Elytron to 2.5.0.CR1

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
server/src/main/java/org/jboss/as/server/ServerEnvironment.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/yaml/YamlExtensionTestCase.java
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-deployment.yml
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-managed-deployment.yml
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-operations.yml

* checking that the YAML deployment is unmanaged.
* adding the unmanaged deployment to the list of operations
* adding some light esting on this
Jira: https://issues.redhat.com/browse/WFCORE-6503
https://issues.redhat.com/browse/WFLY-19442
Proposal: https://github.com/wildfly/wildfly-proposals/pull/554
Documenation PR: https://github.com/wildfly/wildfly/pull/17970

[WFCORE-6503]:Add support for unmanaged deployments with YAML extension.

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Server.java
embedded/src/main/java/org/wildfly/core/embedded/ChainedContext.java
embedded/src/main/java/org/wildfly/core/embedded/Configuration.java
embedded/src/main/java/org/wildfly/core/embedded/Context.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/Main.java
server/src/main/java/org/jboss/as/server/ApplicationServerService.java
server/src/main/java/org/jboss/as/server/Bootstrap.java
server/src/main/java/org/jboss/as/server/BootstrapImpl.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ElapsedTime.java
server/src/main/java/org/jboss/as/server/Main.java
server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/main/java/org/jboss/as/server/ServerStartTask.java

https://issues.redhat.com/browse/WFCORE-6661
This encapsulates the existing and possible future (WFCORE-6657) behavior around calculating and resetting 'start time' in a class, instead of passing around primitive 'startTime' longs and doing math. It uses RuntimeMXBean for the original 'start time' of a non-embedded process, instead of using Module.getStartTime(), which is a time when JBoss Modules started, not when the JVM did.

[WFCORE-6661] More accurate, resettable start time calculation

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java

https://issues.redhat.com/browse/WFCORE-6870
https://issues.redhat.com/browse/WFCORE-6871
https://issues.redhat.com/browse/WFCORE-6876
Some non-urgent housekeeping.

[WFCORE-6870][WFCORE-6871][WFCORE-6876] ModuleSpecification cleanups

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
controller/src/main/java/org/jboss/as/controller/management/Capabilities.java
core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java
core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/AbstractKernelServicesImpl.java
installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrInitialization.java
installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrOperationStepHandler.java
installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrService.java
io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
io/subsystem/src/main/java/org/wildfly/extension/io/WorkerService.java
subsystem/src/main/java/org/wildfly/subsystem/service/AsyncServiceBuilder.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/RootResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6866
If someone has a better idea of where to locate this service descriptor, let me know.

WFCORE-6866 Create ServiceDescriptor for management executor

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6888
Release Notes - WildFly Elytron - Version 2.5.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2776'>ELY-2776</a>] -         Add tests to the OIDC testsuite to test for cases where request/request_uri parameters are not supported by the OpenID provider
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2782'>ELY-2782</a>] -         Release Elytron 2.5.0.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2774'>ELY-2774</a>] -         Move CAGenerationTool to PKCS#12
</li>
</ul>

[WFCORE-6888] Upgrade WildFly Elytron to 2.5.0.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-6834
Requires [WFLY-19378](https://issues.redhat.com/browse/WFLY-19378) https://github.com/wildfly/wildfly/pull/17928 to pass CI.

[WFCORE-6834] wildfly-elytron-integration jar duplicated in server modules

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-6887

[WFCORE-6887] Introducing new phase STRUCTURE_NAMING_JDK_DEPENDENCIES

---

remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestUtil.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/NewExtension.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/OldExtension.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/TestHostCapableExtension.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/expressions/module/TestSecureExpressionsExtension.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/dependent/RootResourceDefinition.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/optypes/OpTypesExtension.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/extensions/CliExtCommandsSubsystemResourceDescription.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/extensions/DuplicateExtCommandSubsystemResourceDescription.java

https://issues.redhat.com/browse/WFCORE-6914

WFCORE-6914 Remove usage of deprecated AbstractAddStepHandler constructors in tests

---

domain-management/src/main/java/org/jboss/as/domain/management/LegacyConfigurationChangeResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessIdentityResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/AbstractFileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/FileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/InMemoryAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/JsonAuditLogFormatterResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/PeriodicRotatingFileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SizeRotatingFileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogProtocolResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6910

WFCORE-6910 Remove usage of deprecated AbstractAddStepHandler constructors in domain-management

---

subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/NewExtension.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/OldExtension.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/similarity/SessionDefinition.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtensionCommon.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/OrderedChildResourceExtension.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/RootResourceDefinition.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/SubsystemInitialization.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/TestHostCapableExtension.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/dependent/RootResourceDefinition.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/remove/ChildResourceDefinition.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/remove/RootResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6930

WFCORE-6930 Remove usage of deprecated AbstractWriteAttributeHandler constructors in testsuite

---

io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6924

WFCORE-6924 Remove usage of deprecated AbstractWriteAttributeHandler constructors in IO subsystem

---

domain-management/src/main/java/org/jboss/as/domain/management/LegacyConfigurationChangeResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationCombinationPolicyWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationProviderWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationUseIdentityRolesWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/AccessIdentityResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/access/HostScopedRoleWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/RoleIncludeAllWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/access/ServerGroupScopedRoleWriteAttributeHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/AbstractFileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/AuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/AuditLogLoggerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/FileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/InMemoryAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/JsonAuditLogFormatterResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/PeriodicRotatingFileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SizeRotatingFileAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogProtocolResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6921

WFCORE-6921 Remove usage of deprecated AbstractWriteAttributeHandler constructors in domain-management

---

core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ConfigurationChangeResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6919

WFCORE-6919 Remove usage of deprecated AbstractWriteAttributeHandler constructors in core-management

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorChildResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/PropertyResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/SaslPolicyResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/SaslResource.java

https://issues.redhat.com/browse/WFCORE-6927

WFCORE-6927 Remove usage of deprecated AbstractWriteAttributeHandler constructors in remoting subsystem

---

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/UpdateScannerWriteAttributeHandler.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/WritePathAttributeHandler.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/WriteRelativeToAttributeHandler.java

https://issues.redhat.com/browse/WFCORE-6920

WFCORE-6920 Remove usage of deprecated AbstractWriteAttributeHandler constructors in deployment-scanner

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6932
Note: WildFly Core drives the commons-lang3 version used in WildFly Full.

[WFCORE-6932] Upgrade commons-lang3 from 3.15.0

---

logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
logging/src/main/java/org/jboss/as/logging/LoggingSubsystemAdd.java
logging/src/main/java/org/jboss/as/logging/filters/FilterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/CustomFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/StructuredFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/AbstractFileHandlerDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/AbstractHandlerDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
logging/src/main/java/org/jboss/as/logging/handlers/SocketHandlerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/SyslogHandlerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/loggers/LoggerOperations.java
logging/src/main/java/org/jboss/as/logging/loggers/LoggerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/loggers/RootLoggerResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6913

WFCORE-6913 Remove usage of deprecated AbstractAddStepHandler constructors in logging subsystem

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6952
Release Notes - WildFly Elytron - Version 2.5.1.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2789'>ELY-2789</a>] -         OIDCSecurityContext deserialization issue
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2796'>ELY-2796</a>] -         Release WildFly Elytron 2.5.1.Final
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2775'>ELY-2775</a>] -         Rename the wildfly-ssl-test-config-v*.xml Files
</li>
</ul>

[WFCORE-6952] Upgrade WildFly Elytron to 2.5.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6952
Upstream PR: https://github.com/wildfly/wildfly-core/pull/6129

[25.x][WFCORE-6952] Upgrade WildFly Elytron to 2.5.1.Final

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java

https://issues.redhat.com/browse/WFCORE-6946

[WFCORE-6946] Fix word order

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java

https://issues.redhat.com/browse/WFCORE-6948

WFCORE-6948 Add ability for wildfly-subsystem to register an operation transformation for any specific operation (not just add).

---

threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolWriteAttributeHandler.java
threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorAdd.java
threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorWriteAttributeHandler.java
threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolWriteAttributeHandler.java
threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolWriteAttributeHandler.java
threads/src/main/java/org/jboss/as/threads/ThreadFactoryAdd.java
threads/src/main/java/org/jboss/as/threads/ThreadFactoryResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/ThreadFactoryWriteAttributeHandler.java
threads/src/main/java/org/jboss/as/threads/ThreadSubsystemResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/ThreadsWriteAttributeOperationHandler.java
threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolResourceDefinition.java
threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolWriteAttributeHandler.java

https://issues.redhat.com/browse/WFCORE-6931

WFCORE-6931 Remove usage of deprecated AbstractWriteAttributeHandler constructors in threads subsystem

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6968
Release Notes - WildFly Elytron - Version 2.5.2.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2797'>ELY-2797</a>] -         NullPointerException in OidcClientConfiguration.resolveUrls if parameter &quot;request_parameter_supported&quot; is not present in openid-configuration
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2756'>ELY-2756</a>] -         Add tests to the elytron test suite to test to test OCSP with revoked and unknown certificates 
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2799'>ELY-2799</a>] -         Release WildFly Elytron 2.5.2.Final
</li>
</ul>

[WFCORE-6968] Upgrade WildFly Elytron to 2.5.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6968
Upstream PR: https://github.com/wildfly/wildfly-core/pull/6150

[25.x][WFCORE-6968] Upgrade WildFly Elytron to 2.5.2.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6973
Release Notes - Undertow - Version 2.3.17.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2429'>UNDERTOW-2429</a>] -          CVE-2024-7885 undertow: Improper State Management in Proxy Protocol parsing causes information leakage
</li>
</ul>

[WFCORE-6973][CVE-2024-7885] Upgrade Undertow to 2.3.17.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6973
Release notes of the last two releases:
Release Notes - Undertow - Version 2.3.17.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2429'>UNDERTOW-2429</a>] -          CVE-2024-7885 undertow: Improper State Management in Proxy Protocol parsing causes information leakage
</li>
</ul>
Release Notes - Undertow - Version 2.3.16.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2256'>UNDERTOW-2256</a>] -         Resource predicate presentation differs depending on how it is set up
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2312'>UNDERTOW-2312</a>] -         multibytes language in URL request to http/https are broken in EAP access log.
</li>
<li>[<a …

[25.x][WFCORE-6973][CVE-2024-7885] Upgrade Undertow from 2.3.15.Final to 2.3.17.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6973

[WFCORE-6973] Upgrade Undertow to 2.3.17.Final - fixing duplicity

---

service/src/main/java/org/wildfly/service/Dependency.java
service/src/main/java/org/wildfly/service/ServiceDependency.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java

https://issues.redhat.com/browse/WFCORE-6974

WFCORE-6974 Add convenience factory method to create a ServiceDependency from a Supplier.

---

service/pom.xml
service/src/main/java/org/wildfly/service/Dependency.java
service/src/main/java/org/wildfly/service/ServiceDependency.java
subsystem/pom.xml
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java

https://issues.redhat.com/browse/WFCORE-6975
Based on https://github.com/wildfly/wildfly-core/pull/6156 to avoid conflicts.

WFCORE-6975 Add convenience method to combine a ServiceDependency with another.

---

elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java

[[WFCORE-6976]  acmeAccount variable is not being used on CertificateAuthoritiesTestCase.java class](https://issues.redhat.com/browse/WFCORE-6976)

[WFCORE-6976] acmeAccount variable is not being used

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6982

[WFCORE-6982] Turn on compiler annotation processing on SE 23+

---

controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/StringListAttributeDefinition.java
discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderRegistrar.java
io/spi/src/main/java/org/wildfly/io/IOServiceDescriptor.java
io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemRegistrar.java
service/src/main/java/org/wildfly/service/Dependency.java
service/src/main/java/org/wildfly/service/ServiceDependency.java
service/src/main/java/org/wildfly/service/descriptor/BinaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/QuaternaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/TernaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/UnaryServiceDescriptor.java
service/src/test/java/org/wildfly/service/descriptor/ServiceDescriptorTestCase.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceModelResolver.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceResolver.java
subsystem/src/main/java/org/wildfly/subsystem/resource/SimpleResource.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReference.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceAttributeDefinition.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceListAttributeDefinition.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceRecorder.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceResolver.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/NaryServiceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/ResourceCapabilityReference.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/ResourceCapabilityReferenceRecorder.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java
subsystem/src/test/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceAttributeDefinitionTestCase.java
subsystem/src/test/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceListAttributeDefinitionTestCase.java
subsystem/src/test/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceTestCase.java

https://issues.redhat.com/browse/WFCORE-6663
e.g.
```java
static CapabilityReferenceAttributeDefinition<Foo> FOO = new CapabilityReferenceAttributeDefinition.Builder("foo", CapabilityReference.builder(CAPABILITY, Foo.SERVICE_DESCRIPTOR).build()).build();
static CapabilityReferenceListAttributeDefinition<Bar> BAR = new CapabilityReferenceListAttributeDefinition.Builder("bar", CapabilityReference.builder(CAPABILITY, Bar.SERVICE_DESCRIPTOR).build()).build();
```
Within an operation runtime handler, we can use the context of the capability reference to resolve our attribute from the model directly to a ServiceDependency:
```java
ServiceDependency<Foo> foo = FOO.resolve(context, model);
ServiceDependency<List<Bar>> bars = BAR.resolve(context, model);
```
If FOO is not required, the resulting …

WFCORE-6663 Introduce AttributeDefinition implementations to wildfly-subsystem that can resolve directly to a ServiceDependency

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-tool/main/module.xml

https://issues.redhat.com/browse/WFCORE-6103

[WFCORE-6103] Add org.aesh dependency for Elytron Tool

---

controller/src/main/java/org/jboss/as/controller/operations/common/XmlFileMarshallingHandler.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlAsFileTestCase.java

* Adding more test using the CLI.
* Moving from COMMUNITY to DEFAULT
* Renaming the ManagementReadXmlCommunityTestCase to ManagementReadXmlAsFileTestCase.
Jira: https://issues.redhat.com/browse/WFCORE-6960
Proposal: https://github.com/wildfly/wildfly-proposals/pull/594

[WFCORE-6960]: Promote Simple config export for a server as an attachment from COMMUNITY to DEFAULT.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7006
Release Notes - WildFly Elytron - Version 2.6.0.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2704'>ELY-2704</a>] -         Missing keystore password does not throw a meaningful exception
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2767'>ELY-2767</a>] -         CredentialStoreCommandTest.testGenerateKeyPairDSA fails when using Java 22
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2771'>ELY-2771</a>] -         maven-javadoc-plugin version upgrade required
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2780'>ELY-2780</a>] -         Logging in aggregaterealm changes authentication and authorization flow
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2811'>ELY-2811</a> …

[WFCORE-7006] Upgrade WildFly Elytron to 2.6.0.Final

---

server/src/test/java/org/jboss/as/server/ServerEnvironmentTestCase.java

Jira issues:
https://issues.redhat.com/browse/WFCORE-7012
https://issues.redhat.com/browse/WFCORE-7013

[WFCORE-7012][WFCORE-7013] Fix ServerEnvironmentTestCase and ignore when server is running in default stability level

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlAsFileTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlTestCase.java
testsuite/domain/src/test/resources/base-server-config.xml
testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
testsuite/domain/src/test/resources/host-configs/host-primary.xml
testsuite/domain/src/test/resources/host-configs/host-secondary.xml

The use of namespaces for lower stability levels should be reserved for
stability level specific tests.
Jira: https://issues.redhat.com/browse/WFCORE-6972

[WFCORE-6972] The standard configuration files used for testsuite/domain should not include community namespaces.

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6999
Note: WildFly Core drives the commons-lang3 version used in WildFly Full.
The uses of this library are in Artemis, Elytron tool, and the WS stack (CXF and Apache Velocity used by CXF).

[WFCORE-6999] Upgrade commons-lang3 from 3.15.0 to 3.17.0

---

controller/src/main/java/org/jboss/as/controller/AttributeParser.java
controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/elementorder/ElementOrderSubsystemExtension.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/elementorder/ElementOrderSubsystemResourceDefinition.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/elementorder/ElementOrderSubsystemSchema.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/elementorder/ElementOrderSubsystemTestCase.java
subsystem-test/tests/src/test/resources/org/jboss/as/subsystem/test/elementorder/element-order-1.0.xml
subsystem-test/tests/src/test/resources/schema/wildfly-element-order_1_0.xsd

Issue: [WFCORE-7004](https://issues.redhat.com/browse/WFCORE-7004)
The default `parseElement` method should ideally never be accessed after this fix but in case it is I assume it's better to throw an exception rather then having one thrown by the XML reader because that makes it look like something's wrong with the XML file.

WFCORE-7004: use custom parser over default

---

elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
elytron/src/test/java/org/wildfly/extension/elytron/ResolveExpressionAttributesTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-expressions.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-18.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-community-18.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-10.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-11.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-12.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-13.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-14.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-15.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-15.1.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-16.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-17.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-7.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-8.0.xml
elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-9.0.xml

https://issues.redhat.com/browse/WFCORE-4395

[WFCORE-4395] Move the JDBCRealm Mapper validation to model time check

---

controller/src/test/java/org/jboss/as/controller/interfaces/OverallInterfaceCriteriaUnitTestCase.java

Also clean up a bunch of IDE complaints about using 'isEmpty()'
https://issues.redhat.com/browse/WFCORE-6962

[WFCORE-6962] Add another check that candidates exist

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-7030
26.x PR: #6220 
Release Notes - Undertow - Version 2.3.18.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2333'>UNDERTOW-2333</a>] -         Undertow read/write timeout should not apply to WebSockets or SSE
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2412'>UNDERTOW-2412</a>] -         Read stored json with default UTF-8 encoding
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2422'>UNDERTOW-2422</a>] -         Response Status Line protocol is hard-coded to &quot;HTTP/1.1&quot;
</li>
<li>[<a href='https://issues.redhat.com/browse/UNDERTOW-2436'>UNDERTOW-2436</a>] -         Race condition for HttpServerExchange state allows missed FLAG_REQUEST_TERMINATED flag with …

[WFCORE-7030] Upgrade Undertow to 2.3.18.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-7034
Release Notes - JBoss Remoting (3+) - Version 5.0.30.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-417'>REM3-417</a>] -         Typo in jboss-remoting_5_2.xsd
</li>
<li>[<a href='https://issues.redhat.com/browse/REM3-422'>REM3-422</a>] -         Fix thread visibility issue in InboundMessage &amp; OutboundMessage dumpState() methods
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-406'>REM3-406</a>] -         Enable TLS Tests
</li>
<li>[<a href='https://issues.redhat.com/browse/REM3-424'>REM3-424</a>] -         Update CI script with latest versions
</li>
</ul>
<h2>        Issue
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/REM3-419'>REM3-419</a>] …

[WFCORE-7034] Upgrade JBoss Remoting to 5.0.30.Final

---

server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java

Issue: https://issues.redhat.com/browse/WFCORE-6981 
[WFCORE-6981] fix incorrect alternatives in `reply-properties `inherited from basis attribute

[WFCORE-6981] fix incorrect alternatives in reply-properties inherited from basis attribute

---

core-feature-pack/common/src/main/resources/content/bin/systemd/README
core-feature-pack/common/src/main/resources/content/bin/systemd/generate_systemd_unit.sh
core-feature-pack/common/src/main/resources/content/bin/systemd/launch.sh
core-feature-pack/common/src/main/resources/content/bin/systemd/wildfly-domain.conf
core-feature-pack/common/src/main/resources/content/bin/systemd/wildfly-domain.service
core-feature-pack/common/src/main/resources/content/bin/systemd/wildfly-domain.service.template
core-feature-pack/common/src/main/resources/content/bin/systemd/wildfly-standalone.conf
core-feature-pack/common/src/main/resources/content/bin/systemd/wildfly-standalone.service
core-feature-pack/common/src/main/resources/content/bin/systemd/wildfly-standalone.service.template
core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/systemd/README

Jira issue: https://issues.redhat.com/browse/WFCORE-6935

[WFCORE-6935] Improve systemd service units

---

core-management/core-management-subsystem/src/test/java/org/wildfly/extension/core/management/CoreManagementSubsystemTestCase.java
core-management/core-management-subsystem/src/test/resources/org/wildfly/extension/core/management/core-management-1.0.xml
core-management/core-management-subsystem/src/test/resources/org/wildfly/extension/core/management/core-management-preview-1.0.xml

https://issues.redhat.com/browse/WFCORE-7043

[WFCORE-7043] Subsystem-level testing of core-managment is incomplete

---

elytron/src/main/java/org/wildfly/extension/elytron/CachingRealmDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

* updating the start mode to LAZY if the server is in admin-mode
* adding a proper error message if the caching realm service is not UP when the user tries to clear the cache.
Issue: https://issues.redhat.com/browse/WFCORE-7058

[WFCORE-7058]: CachingRealm should start lazily in admin only mode.

---

testsuite/scripts/src/test/java/org/wildfly/launcher/test/LauncherTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java

https://issues.redhat.com/browse/WFCORE-7064

[WFCORE-7064] Do not set SM options on JDK24+

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
host-controller/src/test/java/org/jboss/as/host/controller/model/jvm/JvmOptionsBuilderUnitTestCase.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/RuntimeResourceDefinition.java
platform-mbean/src/test/java/org/jboss/as/platform/mbean/PlatformMBeanResourceUnitTestCase.java

https://issues.redhat.com/browse/WFCORE-7063

[WFCORE-7063] Removing useless code related to JDK version detection

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6904

[WFCORE-6904] Bump the kernel management API version to 28.0.0

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-7067
This PR removes the STRUCTURE_APP_CLIENT constant that is now no longer used by WildFly (see WFLY-19758 for reference).

WFCORE-7067 Remove unused STRUCTURE_APP_CLIENT Phase

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7070

[WFCORE-7070] Fix EAP80 Host Exclude kernelAPIVersion

---

host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostInfo.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/ReadPrimaryDomainModelHandlerTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/SyncModelServerStateTestCase.java
host-controller/src/test/java/org/jboss/as/host/controller/mgmt/HostInfoUnitTestCase.java
server/src/test/java/org/jboss/as/server/ServerEnvironmentTestCase.java
version/src/main/java/org/jboss/as/version/ProductConfig.java

Built on top of https://github.com/wildfly/wildfly-core/pull/6201
Jira issue: https://issues.redhat.com/browse/WFCORE-7011
It is expected that mixed domain tests fail with this change. I opened it as a draft since this change still requires some discussions to decide whether we want to allow DC -- HC mixed domains under community -- default stability levels

[WFCORE-7011] Use 'default' stability level when the remote host controller do not advertise its current stability level

---

controller/src/main/java/org/jboss/as/controller/operations/validation/ModuleNameValidator.java
controller/src/test/java/org/jboss/as/controller/operation/validation/ModuleNameValidatorTestCase.java
controller/src/test/java/org/jboss/as/controller/operations/global/AbstractCollectionOperationsTestCase.java
controller/src/test/java/org/jboss/as/controller/operations/global/CollectionOperationsTestCase.java
controller/src/test/java/org/jboss/as/controller/operations/global/EnhancedSyntaxTestCase.java
controller/src/test/java/org/jboss/as/controller/operations/global/StorageRuntimeCollectionOperationsTestCase.java
controller/src/test/java/org/jboss/as/controller/operations/validation/ModelTypeValidatorUnitTestCase.java
controller/src/test/java/org/jboss/as/controller/operations/validation/ModuleNameValidatorTestCase.java

https://issues.redhat.com/browse/WFCORE-7083

WFCORE-7083 ModuleNameValidator fails if module name contains a dash

---

version/src/main/java/org/jboss/as/version/ProductConfig.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7079

[WFCORE-7079] Remove ModuleIdentifier usage from Version module

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-dynamic-ssl/main/module.xml
core-feature-pack/galleon-common/src/main/resources/layers/standalone/elytron/layer-spec.xml
elytron/src/main/java/org/wildfly/extension/elytron/DynamicSSLContextHelper.java
elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/TrivialResourceDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

Supersedes https://github.com/wildfly/wildfly-core/pull/5947
Jira issue: https://issues.redhat.com/browse/WFCORE-6755
See https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Layers.20and.20optional.20packages.
This PR includes #5947 but removes the community stability property configuration from `org.wildfly.security.elytron-dynamic-ssl` JBoss Modules module and adds its package as required for the Elytron layer. Until getting a better approach for this case, this will fix the issue reported by the test case where this module was not provisioned when using Elytron Galleon Layer and ensure we can use `default` stability level out of the box when the server is built targetting this stability level.

[WFCORE-6755] Move the org.wildfly.security:wildfly-elytron-dynamic-ssl artifact into its own module

---

core-model-test/framework/src/main/java/org/jboss/as/core/model/bridge/impl/ChildFirstClassLoaderKernelServicesFactory.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/bridge/local/ScopedKernelServicesBootstrap.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
core-model-test/tests/src/test/java/org/jboss/as/core/model/test/deployment/DomainDeploymentTransformersTestCase.java
core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/bridge/impl/ChildFirstClassLoaderKernelServicesFactory.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/bridge/local/ScopedKernelServicesBootstrap.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
version/src/main/java/org/jboss/as/version/ProductConfig.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7091
@kabir / @pferraro This is preliminary work to prepare WildFly Core for the usage of the incoming WildFly Legacy Test release. Basically:
- Prepare all the stuff to be able to move the stability level to the classes that will bootstrap the legacy controllers.
- In the case of subsystem-tests, the desired stability level will be driven by the AdditionalInitialization class from the ModelTestControllerVersion in use.
- In the case of the core-tests, the stability will be driven directly
- At the product level, we can control which tests will be executed using the ignored property of the ModelTestControllerVersion, it is not too flexible,but enough to what we need at this moment.
Once this PR gets approved, we will release a WildFly …

[WFCORE-7091] Create the ModelTestModelControllerService variants for the WF 31 controllers

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleExtensionListProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleResolvePhaseService.java
server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java

https://issues.redhat.com/browse/WFCORE-3720

[WFCORE-3720] Update ServiceModuleLoader to use non-deprecated JBoss Modules APIs

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-7101

Fix for WFCORE-7101, Upgrade WildFly Maven Plugin to 5.1.0.Final

---

logging/src/main/java/org/jboss/as/logging/deployments/LoggingDependencyDeploymentProcessor.java

https://issues.redhat.com/browse/WFCORE-7106

[WFCORE-7106] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Logging

---

elytron/src/main/java/org/wildfly/extension/elytron/DependencyProcessor.java
elytron/src/main/java/org/wildfly/extension/elytron/EESecurityDependencyProcessor.java

https://issues.redhat.com/browse/WFCORE-7104

[WFCORE-7104] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Elytron

---

testsuite/unstable-api-annotation/feature-pack/subsystem/src/main/java/org/wildfly/core/test/unstable/api/annotation/classes/subsystem/UnstableApiAnnotationTestDependencyProcessor.java

https://issues.redhat.com/browse/WFCORE-7105

[WFCORE-7105] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Test Suite

---

controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java
controller/src/test/java/org/jboss/as/controller/ModuleIdentifierUtilUnitTestCase.java
security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
server/src/main/java/org/jboss/as/server/deployment/Attachments.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/AdditionalModuleSpecification.java
server/src/main/java/org/jboss/as/server/deployment/module/DeploymentVisibilityProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleAliasChecker.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependency.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleIdentifierProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleDefinition.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleResolvePhaseService.java
server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleDependencyUnitTestCase.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java

This is an aggregate of:
#6282 
#6293
#6298 
#6299 
#6300 
#6302
In total this deals with what I think are all the places where WF Core exposes ModuleIdentifier in API that full WildFly or an external extension might use. It deprecates all such places and provides an alternative for all but two things that I don't think external modules will use.[1]
I realize this is a lot to deal with at the last minute for WF Core 27, and **if it's too much that's ok**. Doing this though will give us more freedom to change things right away in Core 28 / WF 36, and gets the deprecation out of the way for downstream. (These APIs are not supported for external use downstream, but we'd likely want to deprecate them anyway before removing them in some future release.)
#6282 is the most substantive. #6293 is …

[WFCORE-7095][WFCORE-7108][WFCORE-7111][WFCORE-7112][WFCORE-7113][WFCORE-7114] Module identifier in api fixes

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/DeploymentVisibilityProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleAliasChecker.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependency.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleResolvePhaseService.java
server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleDependencyUnitTestCase.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java

https://issues.redhat.com/browse/WFCORE-7095
This builds on #6281

[WFCORE-7095] Deprecate ModuleDependency.getIdentifier() for removal

---

server/src/main/java/org/jboss/as/server/moduleservice/ModuleDefinition.java

https://issues.redhat.com/browse/WFCORE-7114

[WFCORE-7114] Deprecate use of ModuleIdentifier in ModuleDefinition

---

server/src/main/java/org/jboss/as/server/deployment/module/DriverDependenciesProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleClassPathProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleExtensionListProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
server/src/main/java/org/jboss/as/server/deployment/service/ServiceActivatorDependencyProcessor.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java

https://issues.redhat.com/browse/WFCORE-7107

[WFCORE-7105] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Server

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7131

[WFCORE-7131] Upgrading JBoss Marshalling to 2.2.2.Final

---

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java

https://issues.redhat.com/browse/WFCORE-7130

[WFCORE-7130] Enhancing CLI tests to don't fail on JDK24+ when JDK warning is being printed

---

server/src/main/java/org/jboss/as/server/deployment/Attachments.java
server/src/main/java/org/jboss/as/server/deployment/Phase.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleClassPathProcessor.java

https://issues.redhat.com/browse/WFCORE-7127
Note that I added a commit to this to remove a bunch of IDE warns.

[WFCORE-7127] Replace Attachments.CLASS_PATH_ENTRIES

---

server/src/main/java/org/jboss/as/server/deployment/Attachments.java
server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/ModuleStructureSpec.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

https://issues.redhat.com/browse/WFCORE-7118
Also https://issues.redhat.com/browse/WFCORE-7136

[WFCORE-7118] Provide an alternative to Attachments.ADDITIONAL_ANNOTATION_INDEXES

---

testsuite/shared/src/main/java/org/jboss/byteman/ServerReloadHelper.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ModuleInfoTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-7135
[WFCORE-7135] Remove `ModuleIdentifier` use in the testsuite

[WFCORE-7135] Remove ModuleIdentifier use in the testsuite

---

cli/pom.xml
cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
cli/src/main/java/org/jboss/as/cli/embedded/Stability.java
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml

https://issues.redhat.com/browse/WFCORE-7124

[WFCORE-7124] Remove use of server-side Stability type from the CLI

---

elytron/src/main/java/org/wildfly/extension/elytron/ClassLoadingAttributeDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java

Issue: https://issues.redhat.com/browse/WFCORE-7134 
[WFCORE-7134] Remove `ModuleIdentifier` use in the elytron subsystem

[WFCORE-7134] Remove ModuleIdentifier use in the elytron subsystem

---

security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerExtension.java
security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerRootDefinition.java
security-manager/src/main/resources/org/wildfly/extension/security/manager/LocalDescriptions.properties

https://issues.redhat.com/browse/WFCORE-7110

[WFCORE-7110] Deprecate the security manager subsystem and report it will be removed in a future release.

---

cli/src/main/java/org/jboss/as/cli/impl/ExtensionsLoader.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/JBossModulesNameUtil.java
controller-client/src/test/java/org/jboss/as/controller/client/helpers/JBossModulesNameUtilUnitTestCase.java
controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java
controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
controller/src/main/java/org/jboss/as/controller/transform/TransformerRegistry.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/ApplyExtensionsHandler.java

https://issues.redhat.com/browse/WFCORE-7116

[WFCORE-7116] Remove ModuleIdentifier from Extension handling

---

controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFilePersistenceResource.java
controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java

configuration dir.
* Replacing java.io.File.canWrite() by java.nio.file.FIles.isWritable(Path).
Jira: https://issues.redhat.com/browse/WFCORE-7102

[WFCORE-7102]: AccessDeniedException on Windows when using a read-only

---

server/src/main/java/org/jboss/as/server/operations/ServerResumeHandler.java
server/src/main/java/org/jboss/as/server/operations/ServerSuspendHandler.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/StandardRolesBasicTestCase.java

This builds on #6329, adding a commit to allow the tests to work downstream.
https://issues.redhat.com/browse/WFCORE-7153

[WFCORE-7153] Don't test reload-enhanced if it's not an available operation

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6846
Verified that WildFly standalone / WildFly domain can be installed as a Windows Service and started/stopped successfully with commons-daemon updated to 1.4.0

[WFCORE-6846] Upgrade commons-daemon to 1.4.0

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7158
Verified that WildFly standalone / WildFly domain can be installed as a Windows Service and started/stopped successfully with commons-daemon updated to 1.4.1

[WFCORE-7158] Upgrade commons-daemon to 1.4.1

---

core-feature-pack/common/src/main/resources/content/bin/standalone.sh

Starting with version 3.8, grep is more strict about the format of regexp in search pattern. Specifically it now reports unnecessary escaped characters with a warning. And we don't want any unexpected warnings to show up when the server is started up.

[WFCORE-7160] Recent version of grep shows warnings for unnecessary escaping

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7061

[WFCORE-7061] Bump the kernel management API version to 29.0.0

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7180

[WFCORE-7180] Upgrade WildFly Elytron to 2.6.1.Final

---

controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7186

[WFCORE-7186] Mark ModuleIdentifierUtil as deprecated for removal

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesTestCase.java

https://issues.redhat.com/browse/WFCORE-7197
Extracted from https://github.com/wildfly/wildfly-core/pull/6261

WFCORE-7197 IO subsystem requires a worker or a buffer pool.  For purpose of test, use request-controller subsystem instead.

---

controller/src/main/java/org/jboss/as/controller/persistence/xml/NamedResourceRegistrationXMLElement.java
controller/src/main/java/org/jboss/as/controller/persistence/xml/ResourceRegistrationXMLElement.java
controller/src/main/java/org/jboss/as/controller/persistence/xml/ResourceXMLContainer.java
controller/src/main/java/org/jboss/as/controller/persistence/xml/ResourceXMLElement.java
controller/src/main/java/org/jboss/as/controller/persistence/xml/SingletonResourceRegistrationXMLElement.java
controller/src/main/java/org/jboss/as/controller/persistence/xml/SubsystemResourceRegistrationXMLElement.java
controller/src/main/java/org/jboss/as/controller/xml/XMLAll.java
controller/src/main/java/org/jboss/as/controller/xml/XMLAttribute.java
controller/src/main/java/org/jboss/as/controller/xml/XMLAttributeReader.java
controller/src/main/java/org/jboss/as/controller/xml/XMLCardinality.java
controller/src/main/java/org/jboss/as/controller/xml/XMLChoice.java
controller/src/main/java/org/jboss/as/controller/xml/XMLComponent.java
controller/src/main/java/org/jboss/as/controller/xml/XMLComponentFactory.java
controller/src/main/java/org/jboss/as/controller/xml/XMLComponentReader.java
controller/src/main/java/org/jboss/as/controller/xml/XMLContent.java
controller/src/main/java/org/jboss/as/controller/xml/XMLContentWriter.java
controller/src/main/java/org/jboss/as/controller/xml/XMLElement.java
controller/src/main/java/org/jboss/as/controller/xml/XMLElementReader.java
controller/src/main/java/org/jboss/as/controller/xml/XMLParticle.java
controller/src/main/java/org/jboss/as/controller/xml/XMLSequence.java
controller/src/main/java/org/jboss/as/controller/xml/XMLUsage.java
controller/src/test/java/org/jboss/as/controller/xml/XMLAllTestCase.java
controller/src/test/java/org/jboss/as/controller/xml/XMLChoiceTestCase.java
controller/src/test/java/org/jboss/as/controller/xml/XMLElementTestCase.java
controller/src/test/java/org/jboss/as/controller/xml/XMLSequenceTestCase.java

https://issues.redhat.com/browse/WFCORE-7205
Enhances interfaces introduced by WFCORE-6779 adding proper xs:attribute support to a generic XMLElement (for use with creating deployment descriptor schemas, etc.)
This proposal modifies several interfaces introduced in https://github.com/wildfly/wildfly-core/pull/6261 and thus is intended for inclusion in 28.0.0.Final.

WFCORE-7205 Add proper xs:attribute support to generic XMLElement.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7218
https://github.com/wildfly-security/wildfly-elytron/compare/2.6.2.Final...2.6.3.Final
https://issues.redhat.com/browse/WFCORE-7219
https://github.com/wildfly-security/elytron-web/compare/4.1.0.Final...4.1.2.Final
https://issues.redhat.com/browse/WFCORE-7210 can also be resolved with this one.
Upstream PR: https://github.com/wildfly/wildfly-core/pull/6393

[28.x] [WFCORE-7218] / [WFCORE-7219] Upgrade WildFly Elytron to 2.6.3.Final and Elytron Web to 4.1.2.Final

---

service/src/main/java/org/wildfly/service/Installer.java
service/src/main/java/org/wildfly/service/ServiceInstaller.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-7222
Adds javadoc clarifying the default StartWhen semantics of each Installer.builder(...) use case.

WFCORE-7222 Improve service start condition configuration of Installer.Builder

---

controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java

https://issues.redhat.com/browse/WFCORE-7234

WFCORE-7234 ParallelBootOperationContext.getResourceRegistration() can throw OperationFailedRuntimeException during operation rollback

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7248
https://github.com/wildfly-security/wildfly-elytron/compare/2.6.3.Final...2.6.4.Final

[WFCORE-7248] Upgrade WildFly Elytron to 2.6.4.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7248
https://github.com/wildfly-security/wildfly-elytron/compare/2.6.3.Final...2.6.4.Final
Upstream PR: https://github.com/wildfly/wildfly-core/pull/6417

[28.x] [WFCORE-7248] Upgrade WildFly Elytron to 2.6.4.Final

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7274

[WFCORE-7274] Upgrade BouncyCastle from 1.80 to 1.81

---

dco.txt

Commonhaus requires that projects have either a Developer Certificate of Origin system or a CLA system. A dco.txt file is part of adding a Developer Certificate of Origin system. (The other part is linking too it from a CONTRIBUTING.md, which will be a separate commit.)
https://issues.redhat.com/browse/WFCORE-7299

[WFCORE-7299] Add a dco.txt file

---

embedded/src/main/java/org/wildfly/core/embedded/StandaloneSystemPropertyContext.java
testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/SystemPropertyResetTestCase.java

https://issues.redhat.com/browse/WFCORE-7294

[WFCORE-7294] embed-server can delete the same tmp/vfs directory for running server

---

server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteHttpGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java

* Using gitignore rules to define which file/directory to clean
Issue: https://issues.redhat.com/browse/WFCORE-7303

[WFCORE-7303]: GitRepository.clearExistingFiles removes file in the 'ignored' set

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7228

[WFCORE-7228] Bump the kernel management API version to 31.0.0

---

pom.xml

Upstream PR: https://github.com/wildfly/wildfly-core/pull/6463
https://issues.redhat.com/browse/WFCORE-7306

[29.x] [CVE-2025-48924] [WFCORE-7306] Upgrade commons-lang3 to 3.18.0

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7342

[29.x][WFCORE-7342] Upgrade wildfly-bom-builder-plugin to 2.0.10
