wildfly/wildfly-core

- jmx/src/main/java/org/jboss/as/jmx/model/ObjectNameAddressUtil.java
- jmx/src/test/java/org/jboss/as/jmx/model/ObjectNameAddressUtilTestCase.java
The call to registry.getSubmodel() must be done on the childAddress, not
the address of the registry itself
JIRA: https://issues.jboss.org/browse/WFCORE-492
> [WFCORE-492] fix ObjectNameAddressUtil.toPathAddress

- core-feature-pack/src/main/resources/configuration/domain/template.xml
Updating domain.xml to be able to reference other-server-group.
Jira: https://issues.jboss.org/browse/WFCORE-506
> [WFCORE-506] : Incoherence in core dist between domain.xml and  host(-slave).xml

- deployment-scanner/pom.xml
- patching/pom.xml
- patching/src/test/java/org/jboss/as/patching/tests/PatchModuleInvalidationWithRenamingFailureTestCase.java
As ByteMan can't attach itslef to a running process which is what is done when using @BMRule then the test fails.
So the test simply returns when an IBM jvm is used.
Jira: https://issues.jboss.org/browse/WFCORE-507
> [WFCORE-507] :  Unit test FileSystemDeploymentServiceUnitTestCase fails on IBM JDK.

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
This removes the use of SecureRandom and constructs the Random once per instance rather than once (or more) per internalExecute() call, which uses less entropy from /dev/random. As per the jira discussion, I cannot think of a reason why the operation id needs to be secure-random rather than merely pseudo-random, however that should be checked. In JDK 7+ java.util.Random is thread safe, with a small penalty for concurrent use, but that penalty is likely lower than repeatedly constructing SecureRandom instances.
The code was added in https://github.com/wildfly/wildfly-core/commit/d971a7a75bb8196731453c0ecbfa49029c9fec1c (for https://issues.jboss.org/browse/WFLY-4), which has no discussion of why SecureRandom is useful/needed.
On my test server, having 10 threads perform 1000 no-op …
> [WFCORE-490] Do not create SecureRandom instance per operation

- core-feature-pack/src/main/resources/content/bin/init.d/wildfly-init-debian.sh
The init.d script for Debian/Ubuntu can be improved in the way it shutdown the server...
If some process hang up, the actual script don't handle that scenario.
> WFCORE-194 Improve Debian/Ubuntu init.d shutdown process

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- controller/src/main/java/org/jboss/as/controller/operations/global/LocaleResolver.java
- controller/src/test/java/org/jboss/as/controller/operations/global/LocaleResolverTest.java
Also,
- add extra test to ensure provided locale tag string is neither too small or too big
- code cleanup to allow unit test
- create a protected static method implementing the desired Locale resolution, but separated from Wildfly data model
- methods throw exception to be catched by wfly specific code, which handle proper logging/display of format error
- this ultimately allowed to add test case to ensure LocaleResolution behave as desired
- cleanup, extract Locale, low-level parsing to separate utility class
> WFLY-3723: Ensure ROOT Locale (en) is loaded whenever user request for en_* locale

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/Log4jAppenderTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
Fix broken logging manual mode test. The test was attempting to use the `ModelControllerClient` before the server has been started.
Moved the `manualmode` module to run with the `allTests` property.
[WFCORE-524] Send a response to the hanging CLI processes to ensure it terminates.
> [WFCORE-498] Ensure the server has been started before executing operations

- controller/src/main/java/org/jboss/as/controller/AttributeParser.java
- controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/systemproperty/AbstractSystemPropertyTest.java
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/domain-servergroup-systemproperties-with-expressions.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/domain-servergroup-systemproperties.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/domain-systemproperties-with-expressions.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/domain-systemproperties.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/host-server-systemproperties.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/host-systemproperties.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/systemproperty/standalone-systemproperties.xml
When the ModelType is STRING or PROPERTY the attribute value is set without trimming.
Jira: https://issues.jboss.org/browse/WFCORE-309
> [WFCORE-309] : system properties are trim()'d and loose whitespace.

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/host/HostModelTestCase.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/host/host-with-default-interface.xml
- core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/servergroup/servergroup.xml
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerRestartRequiredServerConfigWriteAttributeHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
- host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
- host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
- server/src/main/java/org/jboss/as/server/parsing/CommonXml.java
- server/src/main/resources/schema/wildfly-config_3_0.xsd
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DefaultInterfaceOveridingDomainTestCase.java
- testsuite/domain/src/test/resources/domain-configs/domain-default-interface.xml
- testsuite/domain/src/test/resources/host-configs/host-default-interface.xml
Now you can redefine the default-interface in the socket-bindings element of a server definition in the host.xml like this :
**&lt;socket-bindings socket-binding-group="full-ha-sockets" default-interface="public-two"/&gt;**
Or in the domain.xml you may redefine the default-interface of a socket-binding-group like this:
**&lt;socket-binding-group ref="full-sockets" default-interface="public-two" /&gt;**
Jira: https://issues.jboss.org/browse/WFCORE-325
> [WFCORE-325] : Allow socket-binding-group-refType to override default-interface.

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/operations/common/Util.java
- controller/src/main/java/org/jboss/as/controller/remote/ModelControllerClientOperationHandler.java
- controller/src/test/java/org/jboss/as/controller/ModelControllerClientTestCase.java
- core-model-test/framework/src/main/java/org/jboss/as/core/model/test/MainKernelServicesImpl.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
- protocol/src/main/java/org/jboss/as/protocol/mgmt/ManagementResponseHeader.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
Adding some simple validation on operation before trying to execute it.
Fixing issue in ManagementResponseHeader when the exception has no message.
Jira: https://issues.jboss.org/browse/WFCORE-48
> [WFCORE-48] : EOFException when address of a mgmt operation is of a bad data type.

- controller/src/main/java/org/jboss/as/controller/operations/global/LocaleResolver.java
- controller/src/test/java/org/jboss/as/controller/operations/global/LocaleResolverTest.java
- uses Locale.forLanguageTag instead of custom code to parse locale string
- update unit test accordingly
> WFLY-4239: Add support for Locale.forLanguageTag()

- cli/src/main/java/org/jboss/as/cli/CommandContextFactory.java
- cli/src/main/java/org/jboss/as/cli/gui/ConnectDialog.java
- cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextFactoryImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/ModelControllerClientFactory.java
- cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java
- cli/src/main/resources/help/help.txt
- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClient.java
- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClientConfiguration.java
- controller-client/src/main/java/org/jboss/as/controller/client/impl/ClientConfigurationImpl.java
- controller-client/src/main/java/org/jboss/as/controller/client/impl/ProtocolConfigurationFactory.java
- protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionConfiguration.java
- protocol/src/main/java/org/jboss/as/protocol/logging/ProtocolLogger.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/interfaces/CliManagementInterface.java
Now you can specify the bind address for the ModelControllerClient.
You may set it using  client socket binding config through CLI connect with the --bind= param.
Jira: https://issues.jboss.org/browse/WFCORE-371 and https://issues.jboss.org/browse/WFCORE-419
> [WFCORE-371/WFCORE-419] : Expose mgmt client socket binding config through ModelControllerClient Factory.

- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
- server/src/main/java/org/jboss/as/server/controller/resources/SystemPropertyResourceDefinition.java
- server/src/main/java/org/jboss/as/server/operations/SystemPropertyAddHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
Allowing the boot-time attribute for managed servers.
Jira: https://issues.jboss.org/browse/WFCORE-499
> [WFCORE-499] : System properties are broken in domain mode.

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerAddHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStartHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStopHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResource.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
- host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
- server/src/main/resources/schema/wildfly-config_3_0.xsd
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ServerAutoStartTestCase.java
- testsuite/domain/src/test/resources/host-configs/host-master-auto-start.xml
- testsuite/domain/src/test/resources/host-configs/host-slave-auto-start.xml
- testsuite/shared/src/main/java/org/jboss/as/test/shared/ModelParserUtils.java
Since starting or stopping a server is a read-only operation this can't be done as proposed.
When the update-auto-start-with-server-status attribute is set to true on the server declaration then when the server is started a file servername.started will be created in ${jboss.datahome}/auto-start.
When the server is stopped the servername.started will be deleted and a servername.stopped will be created.
Those files are used at startup to determine the auto-start value : if the  update-auto-start-with-server-status is set then the exisitng file will be used instead of the value of the auto-start attribute in the XML.
Jira: https://issues.jboss.org/browse/WFCORE-297
> [WFCORE-297] : HC should remember the 'run' state of the server instances after crash or shutdown

- pom.xml
Intermediate step related to https://issues.jboss.org/browse/WFCORE-279.
> [WFCORE-279] Update JBoss Remoting from 4.0.5 to 4.0.7.

- domain-management/src/main/java/org/jboss/as/domain/management/security/WrapperSSLContext.java
`HttpsURLConnection` invokes `createSocket(Socket, String, int, boolean)`. Extension modules that use `SSLContextService` to inject an `SSLContext` get an NPE when trying to use the socket factory from the
injected context to open a connection to a URL.
The fix here simply invokes the corresponding method on the wrapped socket factory.
> Minor fixes in WrapperSSLContext

- controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
The comment from PR https://github.com/wildfly/wildfly-core/pull/490 indicated the value should be `false`. Changed to `true` so deployment resources are recursively cloned.
> [WFCORE-539] Set recursive to false for non-runtime only resources.

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHttpHandler.java
- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsUtil.java
- domain-http/interface/src/test/java/org/jboss/as/domain/http/server/cors/CorsUtilTest.java
Sanitizing default port from urls.
Fixing double port issue when defining the default origin.
Jira: https://issues.jboss.org/browse/WFCORE-536
> [WFCORE-536] : Sanitize origins ports in CORS.

- core-feature-pack/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
To improve some error messages Weld attempts to get the line number
associated with a particular class member. Reflection API does not
expose such an info so Weld is analysing the bytecode using the
Apache BCEL inluded in Oracle JDK and OpenJDK.
> WELD-1853 Add path com/sun/org/apache/bcel/internal/classfile to sun-jdk system dependency

- controller/src/main/java/org/jboss/as/controller/CompositeOperationHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainFinalResultHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainSlaveHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationsResolverHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/deployment/broken/ServiceActivatorDeployment.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentRolloutFailureTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java
1) Adds a test of deliberately introducing an inconsistent domain (by using a rollout plan that allows a failure on one server) and then of reverting that change (requiring an equivalent rollout plan.)
2) Fixes a bug that resulted in server results not being included in the overall response when a domain rollout is rolled back.
3) Improved the top level failure description when a domain rollout fails by identifying relevant server-level failure descriptions and incorporating them in the top level message. Clients (e.g. CLI high level commands, or perhaps web console error reporting) may not provide the detail server results to users when a failure occurs, so including the data in the top level failure description is important.
> [WFCORE-488] Better domain rollout failure reporting

- controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java
- controller/src/test/java/org/jboss/as/controller/SimpleListAttributeDefinitionUnitTestCase.java
- domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/KeytabResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml.java
* override their marshallAsAttribute() method instead of their
marshallAsElement()
* extend AttributeMarshaller instead of DefaultAttributeMarshaller to
ensure no other marshallXXX method will be called inadvertently.
* fix misuse of this marshaller for attributes that are marshalled as
XML attributes
JIRA: https://issues.jboss.org/browse/WFCORE-566
> [WFCORE-566] fix AttributeMarshaller.STRING_LIST & COMMA_STRING_LIST

- server/src/main/java/org/jboss/as/server/deployment/DeploymentResourceSupport.java
An addition to #524 to allow deployments to check whether or not resources have been registered to the deployments subsystem.
> [WFCORE-542] Add ability to check for already registered resources.

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
As part of https://issues.jboss.org/browse/WFLY-3174 new runtime resources will be displayed on the deployment. A new priority on the install phase will be used to run the DUP that creates the dynamic resources and registers them on the deployment resource.
> Add a new install phase priority for batch resources.

- controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
- controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java
- controller/src/test/resources/org/jboss/as/controller/persistence/groups-subsystem.xml
- controller/src/test/resources/org/jboss/as/controller/persistence/groups-wrappers-subsystem.xml
- controller/src/test/resources/org/jboss/as/controller/persistence/server-subsystem.xml
- controller/src/test/resources/org/jboss/as/controller/persistence/simple-subsystem.xml
- it now properly supports mixing attribute groups & wrappers
- add support for multiple resources inside wrapper element
- add option to override also marshaller inside parser definition
- add tests to make sure this works properly
rework internals to not use map<attribute-name, attribute> to properly support multiple groups with same xml names for different attributes
> WFCORE-564 Fix PersistentResourceXMLDescription parser

- controller/src/main/java/org/jboss/as/controller/AttributeParser.java
Also split on line feeds, carriage returns and tabs when parsing
StringListAttributeDefinition.
> [WFCORE-588] Extra parser delimiter's for StringListAttributeDefiniton

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
Issue: https://issues.jboss.org/browse/WFCORE-587
> [WFCORE-587] Wildfly does not log stack trace of an exception

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/test/java/org/jboss/as/controller/test/RevertReloadRequiredTestCase.java
Prevent revertReloadRequired (resp. revertRestartReloadRequired) to
throw a NPE if reloadRequired (resp. restartRequired) as not been called
beforehands.
JIRA: https://issues.jboss.org/browse/WFCORE-591
> [WFCORE-591] NPE in revertReloadRequired

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/DelegatingResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/ResourceBuilder.java
- controller/src/main/java/org/jboss/as/controller/ResourceBuilderRoot.java
- controller/src/main/java/org/jboss/as/controller/ResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
- controller/src/main/java/org/jboss/as/controller/descriptions/NonResolvingResourceDescriptionResolver.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/registry/LegacyResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
- controller/src/test/java/org/jboss/as/controller/ListAttributeDefinitionTestCase.java
- controller/src/test/java/org/jboss/as/controller/TestModelControllerService.java
- controller/src/test/java/org/jboss/as/controller/access/rbac/AddResourceTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/RegistryProxyControllerTestCase.java
- core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- jmx/src/test/java/org/jboss/as/jmx/model/ObjectNameAddressUtilTestCase.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
- stop testing for core model transformers for  version <= EAP 6.2
- remove some deprecated APIs
- consolidate DelegatingResourceDefinition
needs https://github.com/wildfly/wildfly/pull/7232 merged otherwise full wont compile with this change in core.
> WFCORE-17 Add proper ResourceDefinition hooks for setting runtime only

- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java
- controller/src/main/java/org/jboss/as/controller/DefaultAttributeMarshaller.java
Other cleanup:
AttributeDefinition.marshallAsElement(...) should defer to the AttributeMarshaller to determine if the value can be marshalled as an element.
Fix return value of DefaultAttributeMarshaller.isMarshallableAsElement().
> Allow list attributes to be marshalled as elements.

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
In PR #582 the resources children are still read which in some cases could be expensive. This stops the resource from being validated as well as being read.
> Skip validation of runtime resources

- pom.xml
Change to "avoid ACE when getting SASL providers" is expected to help with EJB30-SEC TCK failures
> upgrade to XNIO 3.3.1.Final

- process-controller/src/main/java/org/jboss/as/process/ProcessControllerServerHandler.java
Trivial change to trace message to contain the correct message name.
> Fix trace message to use 'kill' rather than 'destroy' for kill_process

- controller/src/main/java/org/jboss/as/controller/operations/global/ListOperations.java
- controller/src/main/java/org/jboss/as/controller/operations/global/MapOperations.java
https://issues.jboss.org/browse/WFCORE-626
> WFCORE-626 Global list-get operation can inadvertently create list elements

- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/ShutdownFileSystemDeploymentServiceUnitTestCase.java
- testsuite/manualmode/pom.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerShutdownTestCase.java
- testsuite/manualmode/src/test/resources/byteman/DeploymentScannerShutdownTestCase.btm
- testsuite/shared/pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/deployment/trivial/ServiceActivatorDeployment.java
- testsuite/shared/src/main/java/org/jboss/byteman/ServerReloadHelper.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Avoiding tracing the exception when the Executor is shutting down.
Adding a test to check that reload does occurs without blocking.
Jira: https://issues.jboss.org/browse/WFCORE-232
> [WFCORE-232] : Unclean shutdown of deployment scanner

- cli/src/main/java/org/jboss/as/cli/impl/ModelControllerClientFactory.java
- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClient.java
- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClientConfiguration.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractRbacTestCase.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/AbstractRbacTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/interfaces/NativeManagementInterface.java
This supercedes #593 by deprecating the overly complex factory methods and adding on a bunch of other minor fixes to how we build MCCs.
> [WFCORE-623] add missing methods to ModelControllerClient.Factory

- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
- pom.xml
Reintroduces ModelTestModelControllerService.DelegatingResourceDefinition removed in commit https://github.com/ctomc/wildfly-core/commit/d313f87c4ff1ea6019aad5f9aebc5734227d3304#diff-8d29306104c6abe7fc7a909ab2803f9d  
of 
https://github.com/wildfly/wildfly-core/pull/535. 
Before merging both the core and the wildfly integration tests should be run with -Djboss.test.transformers.eap
> Fix transformer tests

- controller/src/main/java/org/jboss/as/controller/ProcessType.java
- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/self-contained/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
- pom.xml
- self-contained/pom.xml
- self-contained/src/main/java/org/jboss/as/selfcontained/SelfContainedConfigurationPersister.java
- self-contained/src/main/java/org/jboss/as/selfcontained/SelfContainedContentRepository.java
- self-contained/src/main/java/org/jboss/as/selfcontained/SelfContainedContentService.java
- self-contained/src/main/java/org/jboss/as/selfcontained/SelfContainedContentServiceActivator.java
- server/pom.xml
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/SelfContainedContainer.java
- server/src/main/java/org/jboss/as/server/ServerEnvironment.java
- server/src/main/java/org/jboss/as/server/ServerPathManagerService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- Add a SELF_CONTAINED ProcessType and LaunchType
- Configure ServerEnvironment differently if LaunchType.SELF_CONTAINED is used
- Adjust all path-related operations (properties, ServerPathManagerService) to accomodate
possibly null paths.
- Add a self-contained module
- ConfigurationPersister
- ContentRepository
- Add a SelfContainedContainer to be used by wildfly-boot to launch a self-contained
Wildfly from within an existing and external main().
> Support a SELF_CONTAINED mode of operation:

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/logging/main/module.xml
- logging/pom.xml
- logging/src/main/java/org/jboss/as/logging/LoggingProfileContextSelector.java
- subsystem-test/framework/pom.xml
Also added some explicit dependencies to the subsystem-tests so subsystems could use exclusions.
> [WFCORE-557] Remove usage of common-core in logging.

- testsuite/shared/src/main/java/org/jboss/as/test/shared/ModelParserUtils.java
* this prevents warnings in tests using this class about resource
emitting unregistered notifications.
> register notifications for the ModelController server root resource

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentFullReplaceHandler.java
The server-group reference is now correctly updated.
Jira: https://issues.jboss.org/browse/WFCORE-638
> [WFCORE-638] :Deployment runtime-name mismatch between content repo and server-group and logs

- server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
The commit here enhances the logging to include the original exception that caused the temp file provider creation to fail. This should help in cases like the one reported in the forum thread here https://developer.jboss.org/thread/255634
> Include the original cause for failure to create a temp file provider

- domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinder.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/StateValues.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinderPermissionsTestCase.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinderTestCase.java
Corrected the issue in the unit test case, this is good to go now.
> WFCORE-640 - Add file permissions checks during execution of add-user.bat/add-user.sh

- self-contained/src/main/java/org/jboss/as/selfcontained/ContentProvider.java
- self-contained/src/main/java/org/jboss/as/selfcontained/ContentProviderServiceActivator.java
- self-contained/src/main/java/org/jboss/as/selfcontained/SelfContainedContentRepository.java
- server/src/main/java/org/jboss/as/server/SelfContainedContainer.java
* Adjust how content is provided in order to support multiple deployments.
* Use start() instead of bootstrap() so that quiesence is achieved.
* Rename (simplify) some items.
* Throw exceptions instead of abort()'ing, printing and exiting.
* Do not install StdioContext, to allow user's own
System.err/System.out usage to continue as expected.
> Misc changes for Wildfly Swarm

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/HostProcessReloadHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
I noticed this while looking at the other OSHs in the "deployment" package.
> Move HostProcessReloadHandler to the correct package

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/vfs/main/module.xml
@ctomc I noticed this dependency is still in the module.xml but I don't think it's needed.
> [WFCORE-558] Drop common-core dependency in org.jboss.vfs module.xml

- core-feature-pack/src/main/resources/content/bin/standalone.sh
...on solaris 10 and HP-UX hosts
Solaris sh doesn't seem to support variety of substitutions.
> [WFCORE-659] standalone.sh fails to start server with debug argument

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- server/src/main/java/org/jboss/as/server/services/security/RuntimeVaultReader.java
- server/src/main/resources/META-INF/services/org.jboss.as.server.services.security.AbstractVaultReader
Moving RuntimeVaultReader from WildFly to WildFly-Core
Reopening #620 as having this does good and doesn't mean the picketbox lib must be present in core.
Right now (w/o this PR) the way it works is the service loader is in org.jboss.as.security which is visible because HC and server module.xml optionally depend on org.jboss.as.security, with services=import.
With this PR the service loader is in server, which HC already depends on, but now I added services=import too. So the core modules no longer need to depend on org.jboss.as.security as they get nothing from it.
The vault doesn't actually work in core, because there is no picketbox module but server module has an optional dep on picketbox, so if it is present (i.e. in full) then it just works.
I will need to follow up with a PR for …
> [WFCORE-114] : Get RuntimeVaultReader into WildFly Core

- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
- pom.xml
This pull request is just the first stage to get the project included in the build which will also allow it to trickle into WildFly.
In addition to the core Elytron work the project also includes the SASL mechanisms from JBoss SASL and the WildFly SecurityManager.  
Once this module is included as step 1 we can start to move SecurityManager use to Elytron and then remove the existing module.
> [WFCORE-613] Add the Elytron module to the core feature pack.

- controller/src/main/java/org/jboss/as/controller/transform/description/DiscardPolicy.java
see org.jboss.as.controller.transform.description.ResourceTransformationDescriptionBuilder#addChildResource(org.jboss.as.controller.PathElement, org.jboss.as.controller.transform.description.DynamicDiscardPolicy)
> DiscardPolicy needs to be public as it's used by public API

- controller/src/main/java/org/jboss/as/controller/PathElement.java
- controller/src/test/java/org/jboss/as/controller/PathElementTestCase.java
During benchmarking of our WildFly instance creating the regex matcher for
controller path element validation has popped up.
* implement path element validation using a one pass iteration over all
characters rather than a regex
* do not call #toCharArray as it allocates a new char[]
We did some microbenchmarks with JMH and doing the validation this way
is more than an order of magnitude faster.
Issue: WFCORE-685
https://issues.jboss.org/browse/WFCORE-685
> WFCORE-685 Speed up PathElement Validation

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- controller/src/test/java/org/jboss/as/controller/test/AliasResourceTestCase.java
… if another resource exists with the same key as tje target address of a resource alias.
https://issues.jboss.org/browse/WFCORE-692
> [master] WFCORE-692 read-children-names(include-aliases=true) can return phantom results

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- controller/src/test/java/org/jboss/as/controller/test/AliasResourceTestCase.java
if another resource exists with the same key as tje target address of a resource alias.
https://issues.jboss.org/browse/WFCORE-692
> [1.x] WFCORE-692 read-children-names(include-aliases=true) can return phantom results

- controller/src/main/java/org/jboss/as/controller/access/constraint/AuditConstraint.java
- controller/src/main/java/org/jboss/as/controller/access/constraint/NonAuditConstraint.java
- controller/src/main/java/org/jboss/as/controller/access/permission/ManagementPermissionAuthorizer.java
Kabir counted 30K PathElement creations during a boot of full WildFly. I bet a lot of them come from here, as this creates 2 addresses per authorization, we authorize every attribute, and there are probably on average at least 2 PathElements per attribute.
> [WFCORE-696] Reduce PathAddress creation in access control checks

- server/src/main/java/org/jboss/as/server/deployment/reflect/ClassIndex.java
- server/src/main/java/org/jboss/as/server/deployment/reflect/ClassReflectionIndex.java
- server/src/main/java/org/jboss/as/server/deployment/reflect/DeploymentClassIndex.java
This moves similar functionality found in ClassIndex into DeploymentClassIndex. Once
a core release with these changes has been released then full can remove all references
to ClassIndex, and it can be removed from the code base.
> WFCORE-725 Initial work on removing ClassIndex

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/RealValueExpressionTestCase.java
CLI should show the real value of expression properties in addition to the expression
https://issues.jboss.org/browse/WFCORE-729
> [WFCORE-729] Add smoke test for showing the real value of expression in CLI

- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_0.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_1.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_2.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_3.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_4.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_5.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_2_0.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_3_0.java
This is rather large but only because there's a lot of code duplication now. This will easy any further changes to the logging subsystem schema as a new parser will just need to be added instead of a bunch of name space checks which are easy to forget to add.
I only made a few actual changes to the parsing. The unit tests cover the parsing fairly well.
> [WFCORE-748] Split logging subsystem parser into parsers for each versions

- launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/Arguments.java
- launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/Environment.java
- launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/logger/LauncherMessages.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliScriptTestBase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FileArgumentTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FileWithPropertiesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossclircTestCase.java
Added a `CliCommandBuilder` and converted the CLI tests to use it.
The main idea behind the launcher is to allow consumers like the `wildfly-maven-plugin` to be execute CLI commands in a modular environment. Some CLI commands seem to prefer, maybe require, a modular environment. This just eases the pain of manually launching the process with some defaults.
> [WFCORE-718] Add CLI Command Builder

- controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
- host-controller/src/test/java/org/jboss/as/host/controller/HostControllerEnvironmentTestCase.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/ServerEnvironment.java
- server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- server/src/main/java/org/jboss/as/server/operations/InstanceUuidReadHandler.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
- server/src/test/java/org/jboss/as/server/ServerEnvironmentTestCase.java
- server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
Provides a type 4 UUID for a server instance.
The UUID will be saved in $JBOSS_DATA_DIR/kernel/process-uuid and will be (re)created on server instance startup if it doesn't exist.
This UUID should be accessible through the Management API.
Jira: https://issues.jboss.org/browse/WFCORE-746
> [WFCORE-746] :  [WFCORE-746] : Provides a UUID per server instance

- controller/src/main/java/org/jboss/as/controller/AttributeParser.java
- controller/src/test/java/org/jboss/as/controller/SimpleListAttributeDefinitionUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-763
"" will be parsed as an empty list.  Just as an empty list is marshalled to "".
> WFCORE-763 Persisting an empty list [] gets read as a list with empty string [""] resulting in IllegalArgumentException

- controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
- controller/src/main/java/org/jboss/as/controller/DelegatingResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/ResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/AliasResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingImmutableManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ImmutableManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/LegacyResourceDefinition.java
- controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java
- controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java
- controller/src/test/java/org/jboss/as/controller/ListAttributeDefinitionTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/OrderedChildResourceTestCase.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOrderedChildResourceSyncModelTestCase.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/OrderedChildResourceExtension.java
registration. All that is needed now is to call the SimpleResourceDefinition constructor with ordered=true. This ends up as ResourceDefinition.isOrderedChild() = true, and then the framework can figure out the rest.
~~https://github.com/wildfly/wildfly/pull/7611 needs merging before this can pass the full integration tests.~~ MERGED
https://issues.jboss.org/browse/WFCORE-759
https://issues.jboss.org/browse/WFCORE-764 is for getting rid of the deprecated methods once this is in a release and full can be adjusted to not use them
> [WFCORE-759] Creating ordered child resources driven by resource

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/extensions/CliExtCommandHandler.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/extensions/DuplicateExtCommandHandler.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/extensions/DuplicateExtCommandHandlerProvider.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/extensions/DuplicateExtCommandTestCase.java
- testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/cli/extensions/CliExtCommandsTestCase-module.xml
- testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/cli/extensions/DuplicateExtCommandTestCase-module.xml
- testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/cli/extensions/test-cli-ext-commands.txt
https://issues.jboss.org/browse/WFCORE-732 - Extend tests for CLI commands extensibility
Alexey added test as part of https://issues.jboss.org/browse/WFCORE-582. Adding two more tests.
**command name conflict**
* try to register command with name of some standard CLI command
* command is not registered
**help message for custom command**
* add help message to the command from extension
* verify, that help message is available
Adding tests as part of https://issues.jboss.org/browse/EAP7-91 verification procedure.
> [WFCORE-732] Extend tests for CLI commands extensibility

- launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/Arguments.java
- launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/Environment.java
- launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
- launcher/src/main/java/org/wildfly/core/launcher/logger/LauncherMessages.java
The 2.0 PR has some details about why this is desired https://github.com/wildfly/wildfly-core/pull/764.
This is not required for 1.0, but it would be nice to be able to use it in the `wildfly-maven-plugin` which will target 1.0 to stick with a Java 1.7 requirement.
I did not change bring the change for the tests over to the 1.x PR as I didn't want make potential test breaking changes. For 1.x this API will not be used anywhere only to be consumed from other projects.
> [WFCORE-718] Add CLI command builder.

- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryService.java
Wrong usage of address.getHostName() before formatting address to IPv6.
Jira: https://issues.jboss.org/browse/WFCORE-754
Upstream: https://github.com/wildfly/wildfly-core/pull/820
> [WFCORE-754] : WildFly fails to start with -bmanagement= option and with specific IP settings

- core-feature-pack/src/main/resources/modules/system/layers/base/sun/scripting/main/service-loader-resources/META-INF/services/javax.script.ScriptEngineFactory
since we now have minimum requirement for JDK8 no need to include class name for Rhino
> WFLY-3991 javax.script.ScriptEngineFactory: rhino provider not found

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/BootErrorCollector.java
- controller/src/test/java/org/jboss/as/controller/BootErrorCollectorTest.java
Checking the operation that failed to hide or show failure description.
Jira: https://issues.jboss.org/browse/WFCORE-769
> [WFCORE-769] : Boot errors should hide the failure description if the failing operation is not accessible

- testsuite/client-old-server/pom.xml
- testsuite/client-old-server/server-provisioning.xml
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/ClientAgainstOldServerTestCase.java
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/LargeDeploymentFile.java
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/OldVersionCopier.java
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/OldVersionTestParameter.java
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/OldVersionTestRunner.java
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/Version.java
- testsuite/client-old-server/src/test/resources/mgmt-users.properties
- testsuite/pom.xml
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Refactor the Server in test-runner to not use static fields, so that we
can change the values.
I have set up a job http://brontes.lab.eng.brq.redhat.com/viewType.html?buildTypeId=WildFlyCore_ClientOldServerLinux which passes using my branch. Once merged, that job needs changing to run off master.
> Get framework set up for testing the current client against old versions

- controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
https://issues.jboss.org/browse/WFCORE-770
This is not really necessary yet, but it is currently hard to add more fields to be initialised in constructors due to the wide variety of constructors available in this class. So this is an attempt to pre-empt that.
e.g. when I was working on the ordered child resources, in the first iteration I ended up relying on overriding things from methods rather than adding more constructors due to the complexity.
> [WFCORE-770] Add handler parameters

- controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/WorkerThreadPoolVsEndpointHandler.java
This is a minimal impact workaround to the problem.
In versions prior to the IO subsystem, the "endpoint" element in the remoting subsystem configuration did not exist. So I am using the absence of a configuration=endpoint resource as an indication that the subsystem is meant to be used in a profile that does not support IO. If it doesn't exist, this patch avoids adding the org.wildfly.io.worker.default requirement on an HC. It will still be added on a current version server, so the possibility remains that the profile will validate on the HC but will later fail on a server.
Our standard configs since 8.0 have included the following in the remoting subsystem:
```
<endpoint worker="default"/>
```
That means any config based on those will have the configuration=endpoint resource. So the …
> [WFCORE-778] Don't register a default io worker requirement on an HC if no endpoint was configured

- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerDefinition.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentScanHandler.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
- deployment-scanner/src/main/resources/org/jboss/as/server/deployment/scanner/LocalDescriptions.properties
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/AbstractDeploymentScannerOperationTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerOperationRollbackTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerOperationTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerRedeploymentTestCase.java
Adding a new operation that will run a single scan.
This scan will run asynchronously and its failures won't make a composite op rollback but if the composite op rollback then the result of the scan will rollback too.
Jira: https://issues.jboss.org/browse/WFCORE-353
> [WFCORE-353] : CLI command for executing the deployment scanner.

- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
mostly cleanup, all the real work was done some time ago.
> WFLY-3564 deprecate non supported target controller versions

- controller/src/main/java/org/jboss/as/controller/AbstractRemoveStepHandler.java
- controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
These methods were a bad idea. Capability providers should directly use their RuntimeCapability. We don't provide helper methods like this for add or write-attribute use cases, and these helpers are actually more verbose than using the RuntimeCapability directly.
These were only added a couple days ago and were never in an Alpha. The elytron or datasource work may have used them from a snapshot, but they can adapt once an alpha goes out.
> Remove AbstractRemoveStepHandler.getCapabilityRemoveServiceName()

- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemAdd.java
- logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java
- logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigurationService.java
- logging/src/main/java/org/jboss/as/logging/deployments/LoggingDeploymentResourceProcessor.java
- logging/src/main/java/org/jboss/as/logging/deployments/LoggingProfileDeploymentProcessor.java
- logging/src/main/java/org/jboss/as/logging/deployments/resources/HandlerResourceDefinition.java
- logging/src/main/java/org/jboss/as/logging/deployments/resources/LoggerResourceDefinition.java
- logging/src/main/java/org/jboss/as/logging/deployments/resources/LoggingConfigurationReadStepHandler.java
- logging/src/main/java/org/jboss/as/logging/deployments/resources/LoggingDeploymentResources.java
- logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
- logging/src/main/resources/org/jboss/as/logging/LocalDescriptions.properties
- server/src/main/java/org/jboss/as/server/deployment/Phase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/AbstractLoggingTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/JBossLog4jXmlTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/JBossLoggingPropertiesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/Log4jPropertiesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/Log4jXmlTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/LoggingPropertiesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/LoggingProfilesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/NonExistingProfileTestCase.java
Adds a runtime resource to a deployment in an attempt to display the logging configuration a deployment is using. Note that the resulting configuration may not be used on deployments that provide their own log manager, such as deployments that use logback. The resource displayed for these deployments will likely be the `default` resource.
Example:
```
{
"address" => [
("deployment" => "ear.ear"),
("subdeployment" => "logging-profile.war"),
("subsystem" => "logging")
],
"outcome" => "success",
"result" => {"configuration" => {"ear.ear/META-INF/logging.properties" => {
"error-manager" => undefined,
"filter" => undefined,
"formatter" => {"PATTERN" => {
"class-name" => "org.jboss.logmanager.formatters.PatternFormatter",
"module" => undefined,
"properties" => {"pattern" => "[DEPLOYMENT] …
```
> [WFCORE-690] Add logging configuration information to deployments. This helps show runtime information for the configuration deployments are using.

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CloneProfileTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
Provide profile cloning ability (runtime (CLI)) to create new profiles based on existing JBoss profiles.
https://issues.jboss.org/browse/WFCORE-797
This test is similar as CloneProfileTestCase from WildFly (https://issues.jboss.org/browse/WFLY-4838). WildFly has more complex default profile in domain part of TS than WildFly Core. But there should be a variant of this in WildFly Core too (https://github.com/wildfly/wildfly/pull/7699#issuecomment-118884646).
> [WFCORE-797] Add smoke test for cloning profiles in CLI

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/test/java/org/jboss/as/cli/impl/CommandContextImplTestCase.java
https://issues.jboss.org/browse/WFCORE-774
> [WFCORE-774] Memory leak in JBoss CLI

- pom.xml
Fixes a problem where the ACC of the creator of a thread pool is not properly preserved, especially when a security manager is installed.
> Update to JBoss Threads 2.2.1.Final

- server/src/main/java/org/jboss/as/server/deployment/Attachments.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseBuilder.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseDependency.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- server/src/main/java/org/jboss/as/server/deployment/Phase.java
Introduces configurable strategy for building the next deployment phase service.  A DUP can attach an implementation of DeploymentUnitPhaseBuilder to the DeploymentPhaseContext to manipulate how the service for the next phase is built.
https://issues.jboss.org/browse/WFLY-334
This PR contains requisite changes to wildfly-core for this branch:
https://github.com/pferraro/wildfly/tree/singleton
> Support for WFLY-334 HA Singleton deployer for applications

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/test/java/org/jboss/as/controller/SocketCapabilityResolutionUnitTestCase.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainModelReferenceValidator.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ProfileIncludesHandlerTestCase.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/SocketBindingGroupIncludesHandlerTestCase.java
https://issues.jboss.org/browse/WFCORE-815 / https://issues.jboss.org/browse/JBEAP-401
https://issues.jboss.org/browse/WFCORE-816
> Trigger validation of includes also when a profile/s-g-b is empty

- server/src/main/java/org/jboss/as/server/mgmt/HttpManagementResourceDefinition.java
- server/src/main/java/org/jboss/as/server/mgmt/NativeManagementResourceDefinition.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/operations/NativeManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/AbstractBindingWriteHandler.java
- server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/BindingMetricHandlers.java
- server/src/main/java/org/jboss/as/server/services/net/BindingRemoveHandler.java
- server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingResourceDefinition.java
- server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingWriteHandler.java
- server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingResourceDefinition.java
- server/src/main/java/org/jboss/as/server/services/net/SocketBindingAddHandler.java
- server/src/main/java/org/jboss/as/server/services/net/SocketBindingRemoveHandler.java
- server/src/main/java/org/jboss/as/server/services/net/SocketBindingResourceDefinition.java
Switch these to the capability-based service names.
> Remove uses of the legacy service names for SocketBinding and OutboundSocketBinding

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
- controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/SimpleListAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/StringListAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
I refactored the way CapabilityRecorder is set in builder to have more generic code.
I am also tempted to remove get/setCapabiltyRecorder() as this is impl detail more than anything else.
> WFCORE-804 Display attribute definition's capabilty references

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
commit https://github.com/aeshell/aesh/commit/ab1d8d56cb2db8f45bf8c9801f5b1d4a574892b4 in aesh 0.33.14 is made to avoid CLI freeze if it's no longer connected. blockingQueue.poll() will return null if queue is empty rather than waiting. 
But, unconditional loop in https://github.com/wildfly/wildfly-core/blob/669eef7efc3bc9479e23c3449c5cd2ae903b3189/cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java#L1002 can receive this null before CLI is totally shutdown and print massive prompt messages "Accept certificate? [N]o, [T]emporarily, [P]ermenantly :" as reported in https://bugzilla.redhat.com/show_bug.cgi?id=1238263
Since you don't input null value in console, it should return false in that case.
> stop loop when received response is null

- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/Main.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- host-controller/src/main/java/org/jboss/as/host/controller/ProcessControllerConnectionService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventory.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/StartServersHandler.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
- host-controller/src/test/java/org/jboss/as/host/controller/ServerInventoryImplTestCase.java
- process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
- process-controller/src/main/java/org/jboss/as/process/ProcessController.java
- process-controller/src/main/java/org/jboss/as/process/ProcessControllerClient.java
- process-controller/src/main/java/org/jboss/as/process/ProcessControllerServerHandler.java
- process-controller/src/main/java/org/jboss/as/process/ProcessInfo.java
- process-controller/src/main/java/org/jboss/as/process/logging/ProcessLogger.java
- server/src/main/java/org/jboss/as/server/DomainServerCommunicationServices.java
- server/src/main/java/org/jboss/as/server/DomainServerMain.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerClient.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnection.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
WFCORE-775
Forgot to send-pr.
This changes the authKey generation from a 16 byte array to a base 64 encoded string. The amount  of information present remains the same, the string will be 24 bytes in length, however.
java.utils.Base64 is used, JDK8 only, backports would need to utilize an alternative encoder.
> WFCORE-775 domain mode - server fails to start intermittently

- controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFilePersistenceResource.java
- controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceResource.java
- controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
- controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CloneProfileTestCase.java
Using Nio2 API to try to create the temporary configuration file with the same attributes as the original configuration file.
Jira: https://issues.jboss.org/browse/WFCORE-654
> [WFCORE-654] : Configuration files get default permissions when written.

- patching/src/main/java/org/jboss/as/patching/Constants.java
- patching/src/main/java/org/jboss/as/patching/HashUtils.java
- patching/src/main/java/org/jboss/as/patching/ZipUtils.java
- patching/src/main/java/org/jboss/as/patching/installation/InstallationManagerImpl.java
- patching/src/main/java/org/jboss/as/patching/metadata/PatchMerger.java
- patching/src/main/java/org/jboss/as/patching/metadata/SecurityActions.java
- patching/src/main/java/org/jboss/as/patching/runner/AbstractPatchingTask.java
- patching/src/main/java/org/jboss/as/patching/runner/ModuleRemoveTask.java
- patching/src/main/java/org/jboss/as/patching/runner/ModuleUpdateTask.java
- patching/src/main/java/org/jboss/as/patching/runner/PatchToolImpl.java
- patching/src/main/java/org/jboss/as/patching/runner/PatchUtils.java
- patching/src/test/java/org/jboss/as/patching/cli/RollbackLastUnitTestCase.java
- patching/src/test/java/org/jboss/as/patching/installation/LayerTestCase.java
- patching/src/test/java/org/jboss/as/patching/runner/AbstractTaskTestCase.java
- patching/src/test/java/org/jboss/as/patching/runner/ContentModificationUtils.java
- patching/src/test/java/org/jboss/as/patching/runner/PatchingAssert.java
- patching/src/test/java/org/jboss/as/patching/runner/TestUtils.java
- patching/src/test/java/org/jboss/as/patching/tests/MergingPatchContentTestCase.java
- patching/src/test/java/org/jboss/as/patching/tests/MergingPatchMetadataTestCase.java
An improvement of the patch bundle concept currently used for CPs where a bundle contains a number of CP patches from which only those relevant to the target installation will be applied.
The structure and format of the patched data, checksum verification and all the rest of the mechanism of application the changes stays the same.
This commit introduces support for multiple patch.xml files - one per identity version the patch can be applied to and update that identity to the version of the latest CP included in the patch.
Thanks,
Alexey
> https://issues.jboss.org/browse/WFCORE-838 Decrease Patch Size Per CP

- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
Jira: https://issues.jboss.org/browse/WFCORE-855
> Fixing domain-mode reload

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/HierarchicalCompositionTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
Test for logical hierarchical composition of Profies and Socket Binding Groups.
https://issues.jboss.org/browse/WFCORE-844
This test serves as basic smoke tests to be run within the testsuite.
> [WFCORE-844] Add smoke test for hierarchical composition in CLI

- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/XmlCompletionScannerTest.java
Because of IBM Jdk aggressive gc the logger gets gced so the handler is no longer configured.
keeping a strong reference on the logger did the trick.
Jira: https://issues.jboss.org/browse/WFCORE-849
> [WFCORE-849] : XmlCompletionScannerTest fails with IBM JDK 8.

- logging/src/main/java/org/jboss/as/logging/LoggingResource.java
- logging/src/main/java/org/jboss/as/logging/LoggingResourceDefinition.java
- logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
- logging/src/test/java/org/jboss/as/logging/RootSubsystemOperationsTestCase.java
Currently subdirectories of the `jboss.server.log.dir` are ignored when listing log files as resources. This change allows log files in subdirectories to be listed under the `subsystem=logging/log-file=*` resource. The deprecated `subsystem=logging:list-log-files` and `subsystem=logging:read-log-file` operations do not files in the subdirectories.
> [WFCORE-802] Allow log files in subdirectories of the relative jbossserver.log.dir to be listed as log file resources.

- controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
Catching the exception and creating the file without the ACL attibutes if it fails.
Build : http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=63789&tab=buildResultsDiv&buildTypeId=WildFlyCore_MasterSolaris
Jira: https://issues.jboss.org/browse/WFCORE-870
> [WFCORE-870] :  Seeing frequent "java.lang.UnsupportedOperationException: 'acl:acl' not supported as initial attribute" on Solaris arch

- core-feature-pack/src/main/resources/content/bin/init.d/wildfly-init-debian.sh
- core-feature-pack/src/main/resources/content/bin/init.d/wildfly-init-redhat.sh
- core-feature-pack/src/main/resources/content/bin/init.d/wildfly.conf
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/BootstrapListener.java
https://issues.jboss.org/browse/WFCORE-747
Add a marker file to standalone or domain server tmp directory to record server startup state once server is started. It will be removed when server is stopped.
Inside wildfly-init-redhat.sh and wildfly-init-debian.sh, it will read this temporary marker file to exam server startup result before timeout instead of checking volatile log message from console log(key log id changed, log handler removed, etc.)
> Wfcore 747 master

- controller/src/main/java/org/jboss/as/controller/audit/AuditLogHandler.java
- controller/src/main/java/org/jboss/as/controller/audit/AuditLogger.java
- controller/src/main/java/org/jboss/as/controller/audit/InMemoryAuditLogHander.java
- controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLogger.java
- controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
- domain-management/src/main/java/org/jboss/as/domain/management/audit/InMemoryAuditLogHandlerResourceDefinition.java
Updating ManagedAuditLogger to be able to access the last log entries with only a real implemntation in the InMemoryAuditLogHander.
Jira: https://issues.jboss.org/browse/WFCORE-839
> [WFCORE-839] : Don't store state in InMemoryAuditLogHandlerResourceDefinition.

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentResourceDefinition.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentAddHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentDeployHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentFullReplaceHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUndeployHandler.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/AbstractDeploymentUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerNotificationUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerOperationRollbackTestCase.java
When a deployment is deployed or undeployed from out of a scanner, a notification is sent to the scanner so it can update the status.
Jira: https://issues.jboss.org/browse/WFCORE-860
> [WFCORE-860] : Use notifications to help the scanner get a proper status of all deployments between scans

- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
- pom.xml
This is a slimmed version of the library containing just the security manager implementation.
> [WFCORE-898] Upgrade to WildFly Elytron 1.0.0.CR1.

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
- controller/src/main/java/org/jboss/as/controller/registry/AliasStepHandler.java
- controller/src/main/java/org/jboss/as/controller/registry/WildcardReadResourceDescriptionAddressHack.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsAliasesTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/ExtensionSetup.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/TestAliasReadResourceDescriptionAddressExtension.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ReadAliasResourceDescriptionAddressTestCase.java
- testsuite/domain/src/test/resources/extension/test-read-resource-description-alias-address-module.xml
aliased operation
https://issues.jboss.org/browse/WFCORE-873
Testing with a composite shows that each step gets the correct alias attachment. However, there were some problems with the alias attachment not being removed, hence the hack having RegistrationAddressResolver (currently only used by r-r-d) removing it.
I think this will do for now, since only the top level resource description gets the address. In the recursive case, children don't get the address.
> [WFCORE-873] Add attachment to propagate the original address for an

- core-feature-pack/src/main/resources/content/bin/init.d/wildfly-init-debian.sh
- core-feature-pack/src/main/resources/content/bin/init.d/wildfly-init-redhat.sh
- server/src/main/java/org/jboss/as/server/BootstrapListener.java
https://issues.jboss.org/browse/WFCORE-747
I should have just use 'startup-marker' since this can also be used for EAP code.
> [WFCORE-747], update file name to simple startup-marker

- cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestOperationValidatorFilter.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/logging/RemotingLogger.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestUtil.java
- server/src/main/java/org/jboss/as/server/BootstrapListener.java
- server/src/main/java/org/jboss/as/server/FutureServiceContainer.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- testsuite/shared/src/main/java/org/jboss/as/test/shared/ModelParserUtils.java
Switch ModelParserUtils to use offline CLI to test the provided configs, instead of the complex "mock" model controller setups previously used.
Also includes commits for misc issues that prevented this working or would prevent the tests passing. The first two of these are also in separate PRs #973 and #988.
The tests themselves are in full. See https://github.com/wildfly/wildfly/pull/7985 which depends on this to work. WFLY-5138 is the overall JIRA for this.
@luck3y the 3rd commit is for the issue we were chatting about today.
http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=67269&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments is a custom run showing the combination of this and https://github.com/wildfly/wildfly/pull/7985
> [WFCORE-901] Update the utility to properly test our standard configs and legacy configs

- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStopHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ServerAutoStartTestCase.java
Stopping a server shouldn't fail if the server was removed.
Jira: https://issues.jboss.org/browse/WFCORE-905
> [WFCORE-905] : CLI command "/host=master/server-config=server-one:remove" did not work if used in a batch.

- domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_4.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainServerUtils.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_4.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_4.java
- server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_4.java
https://issues.jboss.org/browse/WFCORE-921
https://issues.jboss.org/browse/WFCORE-922
The first is a big deal in a domain, cutting the time to add 8000 datasources to a config from many 10s of minutes to less than a minute.
> Perf improvements in large configs

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
Manual tests that are using CustomCLIExecutor are failing on IBM JDK 8 due to low timeouts. I have increased timeout for command execution and changed initial value of exitCode to non-zero for better testability.
JIRA: https://issues.jboss.org/browse/WFCORE-892
> [WFCORE-892] Increased timeout for CLI executor to avoid test errors

- model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
WildFly Core testsuite can be run on pure-IPv6 machines. Proxy could be used in that case.
But some tests use MavenUtil class for download some dependencies. And this class can not use proxy server. So these tests fail.
https://issues.jboss.org/browse/WFCORE-925
> [WFCORE-925] Ability to use proxy in MavenUtil

- controller/src/test/java/org/jboss/as/controller/interfaces/IPv6ScopeIdMatchUnitTestCase.java
Improve failure message in test. Don't try and add a scope_id to global IPv6 addresses.
This relates to but isn't expected to correct https://issues.jboss.org/browse/WFCORE-934 I'm trying to get a bit more info to understand the cause, plus fix a flaw in the test that likely is unrelated, but worth fixing anyway.
> Improve IPv6ScopeIdMatchUnitTestCase

- controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinition.java
https://github.com/wildfly/wildfly-core/pull/1011 introduced some changes to the AttributeDefinition super calls which should be reverted
> [WFCORE-831] Revert the changes to the AD super constructor calls

- patching/src/main/java/org/jboss/as/patching/logging/PatchLogger.java
- patching/src/main/java/org/jboss/as/patching/metadata/ContentModification.java
- patching/src/main/java/org/jboss/as/patching/metadata/ModificationBuilderTarget.java
- patching/src/main/java/org/jboss/as/patching/metadata/ModificationCondition.java
- patching/src/main/java/org/jboss/as/patching/metadata/PatchXml.java
- patching/src/main/java/org/jboss/as/patching/metadata/PatchXmlUtils.java
- patching/src/main/java/org/jboss/as/patching/metadata/PatchXml_1_0.java
- patching/src/main/java/org/jboss/as/patching/metadata/RollbackPatchXml_1_0.java
- patching/src/main/java/org/jboss/as/patching/runner/AbstractPatchingTask.java
- patching/src/main/java/org/jboss/as/patching/runner/BundlePatchingTask.java
- patching/src/main/java/org/jboss/as/patching/runner/FileRemoveTask.java
- patching/src/main/java/org/jboss/as/patching/runner/FileUpdateTask.java
- patching/src/main/java/org/jboss/as/patching/runner/IdentityPatchRunner.java
- patching/src/main/java/org/jboss/as/patching/runner/ModuleRemoveTask.java
- patching/src/main/java/org/jboss/as/patching/runner/ModuleUpdateTask.java
- patching/src/main/java/org/jboss/as/patching/runner/PatchingTask.java
- patching/src/main/java/org/jboss/as/patching/runner/PatchingTaskDescription.java
- patching/src/main/resources/patch-config_1_2.xsd
- patching/src/main/resources/patch_1_2.xsd
- patching/src/test/java/org/jboss/as/patching/runner/ContentModificationUtils.java
- patching/src/test/java/org/jboss/as/patching/tests/AbstractPatchTestBuilder.java
- patching/src/test/java/org/jboss/as/patching/tests/ModificationConditionTestCase.java
- patching/src/test/java/org/jboss/as/patching/tests/PatchStepAssertions.java
- patching/src/test/resources/patch-11-CP.xml
- patching/src/test/resources/patch-21-ONE-OFF.xml
This commit introduces a condition for miscellaneous (type of) content modification, meaning that a modification recorded in the patch for a path that represents a MISC content type would be applied only if the condition specified for this modification is satisfied at the time of the patch application. If the condition is not satisfied, the modification will simply be skipped instead of aborting the whole patch. If a modification appears w/o a condition, the modification will be considered as required as it is currently.
There is a new schema for patch.xml and patch-config.xml that support the expression of the conditions. In patch.xml it's a simple (optional) attribute called 'condition' allowed for any MISC content modification element.
In patch-config.xml there is a new optional …
> WFCORE-896 Cannot patch EAP once Docs are excluded from installation

- controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
- controller/src/main/java/org/jboss/as/controller/SimpleMapAttributeDefinition.java
WFCORE-936 PersistentResourceXMLDescription & friends shouldn't use ModelNode#asPropertyList()
also Remove deprecated api that was only used by PermissionsParser.
Make PersistentResourceXMLDescription final as it was originally meant.
> WFCORE-936 PersistentResourceXMLDescription: do not use asPropertyList() & remove deprected methods 

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/IncludingResourceCapabilityScope.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/test/java/org/jboss/as/controller/AbstractCapabilityResolutionTestCase.java
- controller/src/test/java/org/jboss/as/controller/SocketCapabilityResolutionUnitTestCase.java
Avoid an NPE when bogus 'includes' values are used in profiles and socket-binding-groups.
Make sure proper cleanup happens if runtime exceptions like this NPE occur.
> WFCORE-955

- controller/pom.xml
- controller/src/main/java/org/jboss/as/controller/ModelVersion.java
- controller/src/main/java/org/jboss/as/controller/ProxyController.java
- controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java
- controller/src/main/java/org/jboss/as/controller/TransformingProxyController.java
- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- controller/src/main/java/org/jboss/as/controller/remote/RemoteProxyController.java
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
Add special handling when /host=/server= or /host=x/server=* reads are detected on the DC and some of the target hosts are running releases prior to WildFly 9.
The tests for this will be added in full's testsuite/mixed-domain in a separate PR:
wildfly/wildfly#8052
I accidentally closed an early attempt at this, and github won't let me reopen after a forced push after a rebase, so here's a new one.
> [WFCORE-621] Allow multi-process wildcard ops to work with legacy slaves

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentResourceDefinition.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentAddHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentDeployHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentFullReplaceHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUndeployHandler.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/AbstractDeploymentUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerNotificationUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerOperationRollbackTestCase.java
Fix consist in release the lock when the notification is processed.
WFCORE-860: Use notifications to help the scanner get a proper status of all deployments between scans
When a deployment is deployed or undeployed from out of a scanner, a notification is sent to the scanner so it can update the status.
Jira: https://issues.jboss.org/browse/WFCORE-903
Original Issue Jira : https://issues.jboss.org/browse/WFCORE-860
> [WFCORE-903] :  Resubmit fixed version of WFCORE-860 

- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/ImmutableCapabilityRegistry.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/test/java/org/jboss/as/controller/AbstractCapabilityResolutionTestCase.java
- controller/src/test/java/org/jboss/as/controller/CapabilityResolutionErrorTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
messages like this now:
```
WFLYCTL0369: Required capabilities are not available:
cap_a in context 'profile=a'; There are no known registration points which can provide this capability.
```
and
```
WFLYCTL0369: Required capabilities are not available:
cap_a in context 'profile=a'; Possible registration points for this capability:
/subsystem=bah/
```
> WFCORE-807 Improve error reporting for missing capabilties

- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
The issue is not in the rollback itself but in the publish where we don't deep copy the registry content into the publishedRegistry thus sharing references afterwards.
Jira: https://issues.jboss.org/browse/WFCORE-980
> [WFCORE-980]:  The capability registry fails to rollback properly

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/syslog/SyslogHandlerTestCase.java
There have been a couple intermittent failures of this test, and it would be nice to have better data.
http://brontes.lab.eng.brq.redhat.com/project.html?projectId=WildFlyCore_PullRequest&buildTypeId=&tab=testDetails&testNameId=-785501276856468694&order=TEST_STATUS_DESC&branch_WildFlyCore_PullRequest=__all_branches__&itemsCount=50
> Provide a better message if testLog detects an unexpected log level

- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementRemoveHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/NativeManagementRemoveHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/HttpManagementResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/NativeManagementResourceDefinition.java
- jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorResource.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/logging/RemotingLogger.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java
- server/src/main/java/org/jboss/as/server/mgmt/HttpManagementResourceDefinition.java
- server/src/main/java/org/jboss/as/server/mgmt/NativeManagementResourceDefinition.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementRemoveHandler.java
- server/src/main/java/org/jboss/as/server/operations/NativeRemotingManagementRemoveHandler.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HTTPSManagementInterfaceTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/RemoveManagementInterfaceTestCase.java
Removing the management interfaces will put the server in reload mode instead of stopping (and removing) those interfaces at runtime.
Until the introduction a new capability by refactoring the management we check manually if JMX requires a management interface for remoting access and if one is still available after removing.
Fixing the sybsystem test case capability registration so that we may define a serviceValueType.
Jira: https://issues.jboss.org/browse/WFCORE-949
> [WFCORE-949] : Removing http-interface autocompletes but fails.

- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerProxy.java
This commit makes sure that the Future objects added to Sets inside
the ManagedServerProxy.activeRequests Map are also properly removed.
The problem was that a delegating Future calls addListener directly
on the underlying Future, so that the callbacks don't get the original
Future, but the underlying one. And this underlying future was
"removed" from the Set (which is a noop, because the underlying Future
was never in the Set in the first place).
> [WFCORE-992] fix memory leak in host controller

- pom.xml
This reverts commit 613d6f8375b9f2bc006514099376a1cf0de0f623.
With 4.0.11 we've found testsuite hangs a la http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=72351&buildTypeId=WildFlyCore_PullRequest
> Revert "Update Remoting to 4.0.11.Final"

- cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
- cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
- core-feature-pack/src/main/resources/content/domain/configuration/logging.properties
Using `SYSTEM_OUT` as the target ensures that the `embed-host-controller` CLI command will not use the `System.console()` to write log messages.
The second commit just changes the `boot.log` to `server.log` for consistency.
> [WFCORE-937] Ensure that System.out is used instead of System.console() for console logging

- cli/src/main/java/org/jboss/as/cli/embedded/EmbeddedServerLaunch.java
- cli/src/main/java/org/jboss/as/cli/embedded/StopEmbeddedHostControllerHandler.java
- cli/src/main/java/org/jboss/as/cli/embedded/StopEmbeddedServerHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java
Restrict which server stop commands are available based on the type started.
> WFCORE-932 stop-embedded-server stops the embedded host controller and vice versa

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
check that the notification is described by the resource registry at
the time emit(Notification) is called and buffer the eventual
warnings. These warnings will be logged only at the end of the operation
execution if it actually successful.
JIRA: https://issues.jboss.org/browse/WFCORE-1007
> [WFCORE-1007] Warnings about missing notification descriptions

- core-feature-pack/src/main/resources/content/domain/configuration/default-server-logging.properties
- core-feature-pack/src/main/resources/content/standalone/configuration/logging.properties
- logging/src/main/resources/subsystem-templates/logging.xml
- logging/src/test/resources/default-subsystem.xml
- testsuite/domain/src/test/resources/domain-configs/domain-auto-ignore.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
The org.apache.tomcat.util.modeler logger is still configured in
several places. This seems to be a leftover from the days when WildFly
used Tomcat as a servlet implementation.
Issue: WFCORE-1012
https://issues.jboss.org/browse/WFCORE-1012
> WFCORE-1012 Remove Tomcat modeler log configuration

- controller/src/main/java/org/jboss/as/controller/PathElement.java
- controller/src/test/java/org/jboss/as/controller/PathElementTestCase.java
Considering empty string as null.
Jira: https://issues.jboss.org/browse/WFCORE-987
> [WFCORE-987]:  java.lang.StringIndexOutOfBoundsException when empty string is used in a resource address value.

- deployment-scanner/pom.xml
- logging/pom.xml
- patching/pom.xml
Allows tests to run in IPv6 only environments. Used the same `ts.ipv6` profile and `ipv6` property to enable to the profile.
> [WFCORE-935] Allow byteman tests to run on IPv6 addresses.

- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
This introduces a new INFO log message that Security Manager is enabled.
https://issues.jboss.org/browse/WFLY-4959
> WFLY-4959 add a log message at INFO level that SM is enabled

- core-feature-pack/src/main/resources/content/bin/add-user.ps1
- core-feature-pack/src/main/resources/content/bin/common.ps1
- core-feature-pack/src/main/resources/content/bin/domain.conf.ps1
- core-feature-pack/src/main/resources/content/bin/domain.ps1
- core-feature-pack/src/main/resources/content/bin/jboss-cli.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.sh
- core-feature-pack/src/main/resources/content/bin/vault.ps1
- WFCORE-745 Standalone powershell script does't support --debug and -secmgr option
- WFCORE-742 Unify linux and PowerShell scripts for jboss-cli in printing environment information
- WFCORE-744 Unify add-user script functionality in windows (powershell, bat) and linux
- WFCORE-737 PowerShell script "vault.ps1" is missing
- WFCORE-1030 PS1 scripts for standalone and domain do not survive :shutdown(restart=true)
> Add missing powershell scripts & fix existing

- domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/ThreadLocalSSLSocketFactory.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/WrapperSSLContext.java
This enables the use of standard timeout settings for outbound LDAPS connections.
> [WFCORE-997] Override the optional createSocket methods and pass these calls onto the delegate.

- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java
WFCORE-1035 fix typecheck so it returns correctly when running in non-modular
> WFCORE-1035 - fix typecheck so it returns correctly when running non-modular embedded server

- controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/operations/global/QueryOperationHandler.java
- controller/src/main/java/org/jboss/as/controller/transform/OperationResultTransformer.java
- controller/src/main/java/org/jboss/as/controller/transform/TransformationTargetImpl.java
Legacy slaves will not understand the new 'query' operation added in WF 9 / Core 1.0. This PR fixes this by adding a transformer for legacy kernel version prior to major version 3 (i.e. WF 8 and earlier). The transformer converts the query op to a read-resource and then uses an OperationResultTransformer to do the filter and select work on the DC side that the normal query op does on the remote side.
In the description of WFCORE-628 I mentioned an issue with this task is that the 'query' operation is global, so there would need to be some notion of inherited transformers, with the transformer for this registered that way. It looks like there is already some notion of an inherited transformer (see OperationTransformerEntry.isInherited()) but the hooks to register this transformer that way …
> [WFCORE-628] Transform the 'query' operation for use on slaves running < WildFly 9

- controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepository.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentAddHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainDeploymentResourceDefinition.java
- server/src/main/java/org/jboss/as/server/deployment/ContentCleanerService.java
When the HC is in backup mode it needs to reference every content it downloads from the DC otherwise those would get deleted by the GC.
Thus we provide the ContentRepository of the HC in the DeploymentAddHandler with the RemoteFileRepository when we have a backup.
Jira: https://issues.jboss.org/browse/WFCORE-1062
> [WFCORE-1062]:  Deployments from the domain/data/content folder goes missing after few minutes if the Host controller is started with --backup option.

- cli/pom.xml
- cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/report/InstallationReportHandler.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/ClientConstants.java
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
This follows up on #1198 by adding a commit to remove the compile time dep of cli module on process-controller.
The only link dep from the client side modules to the server side ones should be wildfly-embedded, so I want to be really strict about that.
> Pull #1198 plus WFCORE-1080

- domain-management/src/main/java/org/jboss/as/domain/management/ConfigurationChangeResourceDefinition.java
Moving the code in the performRuntime method where it should have been.
Jira: https://issues.jboss.org/browse/WFCORE-1092
https://issues.jboss.org/browse/JBEAP-1748
> [WFCORE-1092]:  ConfigurationChangeResourceRemoveHandler makes its changes in the constructor not in execute.

- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepository.java
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
Checking that the directory is empty before trying to delete it.
Jira: https://issues.jboss.org/browse/WFCORE-1107
EAP: https://issues.jboss.org/browse/JBEAP-1803
> [WFCORE-1107]:  DirectoryNotEmptyException on undeploy of ear.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
Previous commit timeout is too short to have a meaningfull test: moving it back to 30 seconds.
> [WFCORE-1074]: Intermittent failure in DeploymentScannerUnitTestCase.

- network/src/main/java/org/jboss/as/network/ManagedDatagramSocketBinding.java
- network/src/main/java/org/jboss/as/network/ManagedMulticastSocketBinding.java
- network/src/main/java/org/jboss/as/network/ManagedServerSocketBinding.java
- network/src/main/java/org/jboss/as/network/ManagedSocketBinding.java
- network/src/main/java/org/jboss/as/network/SocketBindingManager.java
- network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
Also includes the commit for WFCORE-1119 from #1237 as that commit would conflict with this one.
> [WFCORE-1127] Improve handling of unregistering unnamed socket bindings.

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesProfileCloneTestCase.java
Checking that the slave servers have restarted after reload in IgnoredResourcesProfileCloneTestCase.
Jira: https://issues.jboss.org/browse/WFCORE-1115
https://issues.jboss.org/browse/WFCORE-1089
> [WFCORE-1115]: Intermittent failures of CompositeOperationTestCase & CoreResourceManagementTestCase.

- domain-management/src/main/java/org/jboss/as/domain/management/security/KeytabIdentityFactoryService.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/KeytabIdentityFactoryServiceTestCase.java
https://issues.jboss.org/browse/WFCORE-1091
[WFCORE-1091] Kerberos authentication for remoting on hostname which contains uppercase letter
> [WFCORE-1091] Kerberos authentication for remoting on hostname which contains uppercase letter

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
Default value (5s) is not enough sometimes, especially on java IBM8. Parameter --timeout has to be same as in with waiting mechanism in CustomCLIExecutor.
JIRA: https://issues.jboss.org/browse/WFCORE-892
> [WFCORE-892] Set timeout parameter for cli client

- controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
- controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java
This is a replacement for #1207. The 1207 approach avoided any locking but needed a fair bit of complexity to deal with the situation where while the new but unregistered MRR was being populated via calls to the ResourceDefinition, the ResourceDefinition in turn called into the MRR to get data. The approach worked, but was complex and might not work in some obscure cases.
This approach uses locks instead to prevent other threads reading a new MRR before it is fully populated.
> [WFCORE-1049] Use locking to protect MRR until it is completely initialized

- process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
Jira: https://issues.jboss.org/browse/WFCORE-1144
trims spaces of each line in commands to construct ProcessBuilder
> [WFCORE-1144] Space before JVM argument in <jvm-options> causes failure

- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestParser.java
- subsystem-test/tests/pom.xml
- subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/TransformerAttachmentAndInspectModelSubsystemTestCase.java
probably breaks also with other parsers.
> WFCORE-1136 Subsystem parser tests fail when woodstox parser is on classpath

- network/src/main/java/org/jboss/as/network/OutboundSocketBinding.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java
Remoting Subsystem RemoteOutboundConnectionService is caching ConnectionURI causing issues when DNS changes
Downstream: https://issues.jboss.org/browse/JBEAP-1960
https://github.com/jbossas/wildfly-core-eap/pull/61
> [WFCORE-851] - Remoting Subsystem RemoteOutboundConnectionService is …caching ConnectionURI causing issues when DNS changes

- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/logging/EmbeddedLogger.java
The should help if a user enters an incorrect --jboss-home or restarts with a different --jboss-home.
> WFCORE-950 - allow changing of --jboss-home in non-modular

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
https://issues.jboss.org/browse/WFCORE-1209 "CLI did not throw any error message and just ignored the invalid attribute while using in batch mode.If we use same CLI command in non-batch mode it throws exception."
Move validateRequest() and replaceFilePathsWithBytes() into Util class to allow BatchRunHandler validate operation request in BatchRunHandler as OperationRequestHandler does.
> [WFCORE-1209] validate operation request in BatchRunHandler to fix invalid attribute ignoring in batch

- domain-management/src/main/java/org/jboss/as/domain/management/ConfigurationChangeResourceDefinition.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ConfigurationChangesHistoryTestCase.java
Moving the update of the model to the MODEL phase instead of the RUNTIME one.
Jira: https://issues.jboss.org/browse/WFCORE-1261
> [WFCORE-1261]: Changing the max-history attribute value for configuration-changes fails.

- testsuite/patching/src/test/java/org/jboss/as/test/patching/CliUtilsForPatching.java
- testsuite/patching/src/test/java/org/jboss/as/test/patching/MergedPatchesTestCase.java
- testsuite/patching/src/test/java/org/jboss/as/test/patching/PatchingTestUtil.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLIWrapper.java
Test merged patches (introduced by https://issues.jboss.org/browse/WFCORE-838) in addition to the old patch-bundles. Also made CLIWrapper implement AutoCloseable to shorten some pieces of code.
https://issues.jboss.org/browse/WFCORE-1232
> [WFCORE-1232] adjust patching testsuite after WFCORE-838

- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepository.java
- deployment-repository/src/main/java/org/jboss/as/repository/HashUtil.java
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
https://issues.jboss.org/browse/WFCORE-1304
Mac OS can add a hidden file .DS_Store to deployment content repository. This causes an unexpected StringIndexOutOfBoundsException when it calls HashUtil.hexStringToByteArray() to clean obsolete content.
It should exam each char inside hexString is among 0 to f for such system added file, in this case ".DS.Store".
As reported, It's also reproducible in Linux by creating a file under the content dir, but I think it's incorrect behavior to manually create any customer file in this directory.
> [WFCORE-1304] fix StringIndexOutOfBoundsException when clean an obsolete system added content

- core-feature-pack/src/main/resources/configuration/host/host-master.xml
- core-feature-pack/src/main/resources/configuration/host/host-slave.xml
- core-feature-pack/src/main/resources/configuration/host/host.xml
- core-feature-pack/src/main/resources/content/bin/standalone.conf
- core-feature-pack/src/main/resources/content/bin/standalone.conf.bat
- core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
Initial change for standalone, possibly another change to follow for jvm defaults (currently 256m).
> WFCORE-1319 - Defaults for Metasize and Java 8

- domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapGroupSearcherFactory.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/realms/LdapTestSuite.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/realms/PrincipalToGroupMissingNameLdapSuiteTest.java
- domain-management/src/test/resources/org/jboss/as/domain/management/security/realms/principal-to-group.ldif
Check that the simple name attribute can be loaded for the group and if it is required, not loaded and missing group skipping disabled - log an error.
> [WFCORE-1281] NPE in LDAP principal to group loading

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/PrepareStepHandler.java
This stops the logging of the host controller not being registered during polling by ReloadHandler.ensureServerRebootComplete(). I'm not sure if this is actually correct in all cases, @bstansberry thoughts? Is this too broad here or are their other things that could fail to report errors during boot because of this?
> WFCORE-1229 - Reloading the embed host controller logs ERROR messages

- core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/log4j/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/log4j/logmanager/main/module.xml
In an effort to make the the `org.jboss.log4j.logmanager` a private module the `org.apache.log4j` module is no longer aliased. It now delegates to the `org.jboss.log4j.logmanager` my export the packages.
> [WFCORE-1322] Make the org.jboss.log4j.logmanager module private

- patching/src/main/java/org/jboss/as/patching/cli/PatchHandler.java
Jira: https://issues.jboss.org/browse/WFCORE-1316
BZ 6.4.z : https://bugzilla.redhat.com/show_bug.cgi?id=1290290
It the host option is specified it shouldn't allow the command to be
executed unless the CLI is online and running in domain mode.
> [WFCORE-1316] patch apply command not working as expected in non-interactive mode in domain mode

- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java
This can go in 2.0.8 or in 3.x; I'm fine either way.
WFCORE-963 added registration of an io subsystem by the parser if a legacy remoting xsd version was used. That's a migration aid, but it breaks mixed domain use cases by introducing a subsystem that legacy slaves can't understand to profiles meant for legacy.
This PR limits this migration behavior to servers to avoid this problem.
@dmlloyd made a good point in a discussion suggesting that in new releases capabilities should not add new *hard* requirements, but only optional ones, and if the optional capability is not present fall back on some non-capability based mechanism for getting required services. I agree with this. But digging into this issue I saw that with WFCORE-778, we already largely have this kind of behavior. The presence …
> [WFCORE-1311] Limit the WFCORE-1311 assistance to the server case

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
The new phase is used to register a DUP in the security manager subsystem that validates the configured permissions (both subsystem and deployment permissions) against the maximum set.
Link to the upstream Jira:
https://issues.jboss.org/browse/WFLY-4882
Link to the WildFly PR that adds the new validator DUP:
https://github.com/wildfly/wildfly/pull/8612
> [WFLY-4882] Add a phase for the permissions validation.

- core-feature-pack/src/main/resources/content/bin/domain.sh
- core-feature-pack/src/main/resources/content/bin/standalone.sh
Checking if the directory exists and avoiding verifying it if not.
Jira: https://issues.jboss.org/browse/WFCORE-1066
> [WFCORE-1066]: Parameter -Djboss.domain.log.dir does not have effect on HP-UX when directory does not exist.

- patching/src/main/java/org/jboss/as/patching/HashUtils.java
- patching/src/main/java/org/jboss/as/patching/IoUtils.java
- patching/src/main/java/org/jboss/as/patching/ZipUtils.java
- patching/src/main/java/org/jboss/as/patching/installation/InstallationManagerImpl.java
- patching/src/main/java/org/jboss/as/patching/logging/PatchLogger.java
- patching/src/main/java/org/jboss/as/patching/metadata/PatchMerger.java
- patching/src/main/java/org/jboss/as/patching/runner/IdentityPatchContext.java
- patching/src/main/java/org/jboss/as/patching/runner/ModuleRemoveTask.java
- patching/src/main/java/org/jboss/as/patching/runner/ModuleUpdateTask.java
- patching/src/main/java/org/jboss/as/patching/runner/PatchToolImpl.java
- patching/src/test/java/org/jboss/as/patching/cli/CLIPatchInfoUtil.java
- patching/src/test/java/org/jboss/as/patching/installation/BaseLayerTestCase.java
- patching/src/test/java/org/jboss/as/patching/metadata/PatchBundleXmlUnitTestCase.java
- patching/src/test/java/org/jboss/as/patching/metadata/PatchXmlUnitTestCase.java
- patching/src/test/java/org/jboss/as/patching/runner/AbstractTaskTestCase.java
- patching/src/test/java/org/jboss/as/patching/runner/PatchingAssert.java
- patching/src/test/java/org/jboss/as/patching/runner/TestUtils.java
- patching/src/test/java/org/jboss/as/patching/tests/MergingPatchContentTestCase.java
- patching/src/test/java/org/jboss/as/patching/tests/MergingPatchMetadataTestCase.java
- patching/src/test/java/org/jboss/as/patching/tests/ModificationConditionTestCase.java
- patching/src/test/java/org/jboss/as/patching/tests/MultipleStreamsPatchingTestCase.java
superceeds https://github.com/wildfly/wildfly-core/pull/1368
it adds NIO methods usage for copying which produce better error messages.
Also fixes lots of file leaks in the patching / patching ts.
> [WFCORE-1309] Applying patch - "no space available" not specific enough

- host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmElement.java
Note, we should probably add support for MetaSpacesize here too so we can get the current value from /host=foo/jvm, I experimented with this earlier, looks easy enough, I'll open as a separate Jira.
> WFCORE-1394 remove permgen defaults when started with no jvm configured

- cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/UndeployHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java
- cli/src/main/resources/help/deploy.txt
- cli/src/main/resources/help/module.txt
- cli/src/main/resources/help/undeploy.txt
Now covers --properties option in ASModuleHandler and the --server-groups options in DeployHandler and UndeployHandler.
JIRA: https://issues.jboss.org/browse/WFCORE-1360
> [WFCORE-1360] CLI Options missed in WFCORE-1199

- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/OldVersionTestRunner.java
https://issues.jboss.org/browse/WFCORE-1442
This only affects the client old server tests which have been failing for a while.
This branch now passes the test: https://ci.wildfly.org/viewLog.html?buildId=13333&tab=buildResultsDiv&buildTypeId=WildFlyCore_ClientOldServerLinux
> [WFCORE-1442] Remove -XX:MaxMetaspaceSize=256m

- controller/src/test/java/org/jboss/as/controller/OperationTimeoutUnitTestCase.java
Minor cleanup for something I noticed when working on a different thing. This "setup" op always fails due to no MRR being registered for the "child" resource type. It's a Stage.MODEL failure and hence the op is 100% rolled back and has no effect but the failure doesn't affect the test at all. Hence the op is just cruft. Its use was copied over from a different test.
> Prune unneeded and broken 'setup' op from OperationTimeoutUnitTestCase

- jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
If management operations are flagged with RUNTIME_ONLY, expose them in
JMX even when the resource is not mutable (as is the case for
resources hosted on domain servers).
JIRA: https://issues.jboss.org/browse/WFCORE-1111
> [WFCORE-1111] Exporse RUNTIME_ONLY methods in JMX

- server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
Fix for ticket https://issues.jboss.org/browse/WFCORE-1112
org.jboss.logging.BasicLogger#debugf allow not replace template if debug level not available
> WFCORE-1112 use logger.debugf instead of manual string concatenation

- network/src/main/java/org/jboss/as/network/ManagedDatagramSocketBinding.java
- network/src/main/java/org/jboss/as/network/ManagedMulticastSocketBinding.java
- network/src/main/java/org/jboss/as/network/ManagedServerSocketBinding.java
- network/src/main/java/org/jboss/as/network/ManagedSocketBinding.java
- network/src/main/java/org/jboss/as/network/SocketBindingManager.java
- network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
This builds on #1239 but adds an additional commit for https://issues.jboss.org/browse/WFCORE-1029.
I'm using separate PRs for these because the different related issues have, IMO, different degrees of acceptability for inclusion in EAP 7. I believe including the WFCORE-1029 fix is the correct ultimate solution, but having added bake time makes sense to me.
> [WFCORE-1029] Stop using InetSocketAddress as map key in UnnamedBindingRegistry

- controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
The first alternative option is do nothing, side effect of this is any resource that extends PersistentResourceDefinition will need to keep casting the Parameters back.
The other extreme is to re-design the Parameters hierarchy - if we do that however we need to do it before WildFly Core 2.0.0.Final is tagged as any subsystem developed externally is going to be sensitive to changes here.
> [WFCORE-1193] Override all methods of Parameters so that the child type can be returned.

- controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
Fixing how the filename is computed.
Jira: https://issues.jboss.org/browse/WFCORE-991
> [WFCORE-991]: Starting server with config that doesn't end with .xml fails

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
The original service.bat stripped out special characters like '!' in passwords. This was due to the delayed expansion of variables which is only necessary to determine JBOSS_HOME.
> modified script to allow special characters in username and Password

- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRemoveHandler.java
Catching the IllegalStateException and transforming it into an OperationFailedException.
Jira: https://issues.jboss.org/browse/WFCORE-1042
> [WFCORE-1042]: ExtensionRemoveHandler logs client mistakes.

- cli/src/main/resources/help/connect.txt
- cli/src/main/resources/help/help.txt
> WFCORE-1361 Update the command synopsis for jboss-cli

- cli/src/main/java/org/jboss/as/cli/handlers/ResourceCompositeOperationHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/jca/DataSourceAddCompositeHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
> WFCORE-1362 Add --connection-properties to datasource add command

- controller/src/test/java/org/jboss/as/controller/interfaces/IPv6ScopeIdMatchUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-794 - IPv6ScopeIdMatchUnitTestCase fails if some IPv6 subinterface exists
InetAddress.getByName(subInterface.getName()) returns null for virtual interfaces making the IPv6ScopeIdMatchUnitTestCase fail on servers with link-local IPv6 addressed sub-interfaces
> WFCORE-794 IPv6ScopeIdMatchUnitTestCase fails with link-local subinterfaces

- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/operations/NativeManagementAddHandler.java
- server/src/main/java/org/jboss/as/server/operations/NativeManagementServices.java
This commit resolves a problem found with wildfly-core in standalone mode if http-upgrade-enabled configuration is false.
Jira issue link:
https://issues.jboss.org/browse/WFCORE-1397
> [WFCORE-1397] Fixed XnioWorker service installation in HttpManagementAddHandler for standalone mode

- controller-client/src/main/java/org/jboss/as/controller/client/helpers/ClientConstants.java
The `@Deprecated` annotation appears to have been mistakenly added to the `ClientConstants.AUTO_START` constants. This just simply removes the `@Deprecated` annotation.
> Remove deprecated annotation that appears to have been mistakenly added.

- controller-client/src/main/java/org/jboss/as/controller/client/helpers/Operations.java
Removes the `recursive` attribute being defined on a `read-resource` operation if the `createReadResourceOperation(ModelNode address)` is used.
> [WFCORE-1419] Do not set the recursive attribute on the read-resource operation if not explicitly defined.

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ProfileIncludesHandlerTestCase.java
I also enabled a test that I noticed was disabled when I was playing with testing this.
Note that this PR doesn't change any of the usage of setCapabilityReference in core. That's because this method of determining the dependent is more expensive, so I didn't want to change working code to something more expensive.
> [WFCORE-1161] Provide an MRR-driven CapabilityReferenceRecorder

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/AuditLogTestCase.java
Just noticed this test isn't doing what it says because it never executes this op.
> Execute the server reload op that the test creates

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainControllerLockIdUtils.java
- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
- host-controller/src/main/java/org/jboss/as/host/controller/mgmt/MasterDomainControllerOperationHandlerService.java
This slave-controller-lock-id has never done anything since my first commit where it appeared. Javadoc says it "is used to group several slave requuests onto one DC request" but there aren't several slave requests.
Given the javadoc on slave-controller-lock-id, I didn't believe my original addition of that had anything to do with the following, but before deciding to remove this cruft I was concerned about a missing "lock". So I analyzed what happens, and it looks ok, details as follows:
If a slave request comes in without a domain-controller-lock-id, that means the user op went directly to the slave, e.g. a direct CLI connection to the slave adding a new server-config requiring a pull down of data. In that case domain-controller-lock-id will be null on the master, and it will drop into …
> Clean some cruft

- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
When server is shutting down we are setting the scanEnabled to false and ignore errors on ScanContext creation since the scan doesn't make any sense.
> [WFCORE-1430]: Deployment scanner logs ERROR when server is shutting down.

- cli/src/main/resources/help/module.txt
Removing reference to AS7 and indicating that the module command only works locally.
Jira: https://issues.jboss.org/browse/WFCORE-1376
> [WFCORE-1376]:  Update the module cli command help text

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
To test, try to execute `service.bat install` when wildfly is under Program Files (x86)
> [WFLY-6119] Fix service.bat execution when JBOSS_HOME contains spaces

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
- service.bat points user to wrong directory
- service.bat fails when wildfly folder path contains spaces
- Service can't be installed if the path contains a closed bracket
- few other problems community found
no need for downstream PR / JIRA as we use different scripts there.
> WFCORE-1380 WFCORE-1177 WFCORE-1379 fix most common service.bat issues

- controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
- controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFilePersistenceResource.java
- controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
Server is unable to start if it is started with --read-only-domain-config or --read-only-server-config using a folder unwritable by the Wildfly process. This commit resolves this issue using the configuration dir to create the configuration file backup
Jira issue:
https://issues.jboss.org/browse/WFCORE-515
> [WFCORE-515] Unable to create create backup copies of configuration file if main file folder is unwritable by the WildFly process.

- server/src/main/resources/schema/wildfly-config_4_0.xsd
- server/src/main/resources/schema/wildfly-config_4_1.xsd
Adding minOccurs="0" for native-interface.
Jira: https://issues.jboss.org/browse/WFCORE-1444
> [WFCORE-1444]: Fix schema as native-interface shouldn't be mandatory for host-management-interfaces

- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
The status reported by the HC's view of server management lifecycle is different from the status reported by the server's itself. This commit tries to avoid that discrepancy if the server was stopped by an action, which wasn't initialized by the HC. In that case instead of report FAILED from the HC's view, now STOPPED is reported if the server was successful stopped.
Jira issue:
https://issues.jboss.org/browse/WFCORE-701
> [WFCORE-701] Apply changes to get a consistence between the HC's view state and server's own view state when the server process is stopped

- controller/src/main/java/org/jboss/as/controller/ResourceBuilderRoot.java
Also includes a commit converting some classes to nested classes of the main class in the file.
> [WFCORE-1450] Use a copy constructor instead of a subclass

- controller/src/main/java/org/jboss/as/controller/CompositeOperationHandler.java
- controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java
Also removes the 'forceDefaultDescriptionProvider' logic from SimpleAttributeDefinition(Builder) as this was only configurable via a package protected method and the only use of that method is now gone from CompositeOperationHandler.
> [WFCORE-403] Make 'composite' op public

- server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
- server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
- server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
Bit of a convenience in case DUPs don't undo in undeploy what the do in deploy and then the deployment unit service gets bounced due to some MSC dependency bouncing, e.g. WFLY-4908.
@scottmarlow not critical but I'm curious if this fixes PR the WFLY-4908 issue without the need for your patch. Your patch is still correct though as a DUP should undo in undeploy what it does in deploy; this PR is just a 2nd line of defense.
> [WFCORE-1272] Clean up the deployment resource on deployment unit service stop

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/Console.java
- pom.xml
> [WFCORE-1315] CLI Double prompt when connecting to a new HC

- domain-management/src/main/java/org/jboss/as/domain/management/security/FileKeystore.java
Using a KeyStore provider that does not allow or returns empty from getEncoded() on private keys causes a KeyStoreException at SSL startup. This is common in HSM-backed key operations.
When creating a reduced KeyStore, use the same provider as the source KeyStore to
minimize incompatibilities.
While it's still not guaranteed to work with all KeyStore providers, switching `KeyStore.getInstance("JKS")` to `KeyStore.getInstance(provider)` fixes the issue for SafeNet "Luna" and SunPKCS11 "PKCS11" KeyStore implementations while not breaking the "PKCS12" and "JKS" cases.
> Fix HSM-based SSL

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventory.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerSuspendHandler.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
Attempt at following Brian's suggestions on https://github.com/wildfly/wildfly-core/pull/1489.
I wasn't familiar with BlockingQueueOperationListener, but hopefully if something needs tweaking this will help.
https://issues.jboss.org/browse/WFCORE-1467
> WFCORE 1467 Avoids calling suspend twice when a timeout is used with suspend.

- controller/src/main/java/org/jboss/as/controller/access/constraint/ApplicationTypeConstraint.java
- controller/src/main/java/org/jboss/as/controller/access/constraint/SensitiveTargetConstraint.java
- controller/src/main/java/org/jboss/as/controller/access/management/ApplicationTypeAccessConstraintDefinition.java
- controller/src/main/java/org/jboss/as/controller/access/management/SensitiveTargetAccessConstraintDefinition.java
- controller/src/test/java/org/jboss/as/controller/access/rbac/FilteredReadResourceTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/LoggingPreferencesTestCase.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ApplicationTypeTestCase.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ConfigurationChangesHistoryTestCase.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/StandardExtensionSetupTask.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/extension/ConstrainedResource.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/extension/ExtensionSetup.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/extension/RootResourceDefinition.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/extension/SensitiveResource.java
- testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/extension/TestExtension.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/streams/LogStreamExtension.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/ServerReload.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/operations/CustomFormattersTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/operations/CustomHandlerOperationsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/LoggingProfilesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/syslog/SyslogHandlerTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GlobalOpsTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/remove/ChildResourceDefinition.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/remove/RootResourceDefinition.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ConfigurationChangesHistoryTestCase.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildflyTestRunner.java
These changes are part of #1475 since they are required to make the main code change there pass CI, but I decided to submit them separately as well. These are useful on their own and I figure #1475 is a big chunk to review, while these should be more digestible. If they get merged, then #1475 will become more digestible too.
The commits do 3 things:
1) Change some tests such that they don't trigger reload-required.
2) Add a SetupTask that triggers reload in tearDown, and then use it in tests that really need to trigger reload required
3) Change the test runner such that it fails in non-manual control tests that leave the server in reload-required.
> [WFCORE-1460] Ensure tests don't leave a running server in reload-required state

- cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CLITestCase.java
This fix allows to use the class in offline mode and connected mode. Furthermore these changes cover the issue reported in WFCORE-1417 ( CLI was not usable after a failing connect and error was wrongly reported).
CLI class has been refactored in order to reduce code replication and remove some formatting issues.
The existing API and expected behaviour has been preserved:
CLI cli = CLI.newInstance();
cli.connect(....);
The new behaviour:
CLI cli = CLI.newInstance();
cli.cmd("embed-server");
cli.connect(...);
cli.disconnect();
cli.cmd("embed-server"); || cli.connect(...);
cli.disconnect();
...
> [WFCORE-1456] Allow CLI class to support offline mode

- cli/src/main/java/org/jboss/as/cli/handlers/ifelse/ConditionArgument.java
- cli/src/main/java/org/jboss/as/cli/handlers/ifelse/MatchOperation.java
- cli/src/test/java/org/jboss/as/cli/parsing/ifelse/test/MatchTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ifelse/BasicIfElseTestCase.java
Introduced regex based match comparison-operation for if-commands.
The match operation is denoted by the symbol `~=`.
The left operand is a string to match against the right operand
which is a regex string.
This enables a simple way to do feature flag detection
via partial regex matches.
E.g. given the system property "features" which contains a space
separated list of enabled "features".
```
-Dfeatures="activemq jgroups"
```
One could conditionally configure wildfly components via CLI
in one generic CLI script, e.g.:
```
if (features ~= ".*activemq.*") of /:resolve-expression(expression=${features})
echo configuring activemq
end-if
if (features ~= ".*jgroups.*") of /:resolve-expression(expression=${features})
echo configuring jgroups
end-if
if (features ~= ".*postgres.*") of …
```
> WFCORE-1469 - Support match-comparison operation for if-command

- controller/src/main/java/org/jboss/as/controller/access/rbac/RoleMapper.java
- controller/src/main/java/org/jboss/as/controller/access/rbac/UnknowRoleException.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerManagementTestCase.java
Getting the authorization error passed to the handler so it can get back cleanly.
Jira: https://issues.jboss.org/browse/WFCORE-1028
> [WFCORE-1028]: Poor handling of invalid roles.

- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
Making the resetEmbeddedServerProperties a little more selective to enable some configuration params on first usage of the embedded server.
Jira: https://issues.jboss.org/browse/WFCORE-1373
> [WFCORE-1373]: Unable to specify custom configuration directory via -Djboss.server.config.dir

- cli/src/main/java/org/jboss/as/cli/CommandContext.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIScriptSupportTestCase.java
[WFCORE-1456]
Approach is to make this change compliant with existing CLI class behaviour.
The class can now handle offline mode commands.
[WFCORE-1471]
The test added for WFCORE-1456 has shown that the CLI class was mixing operations and commands. Furthermore Batch and workflow features were not supported.
Although all could be routed to CommandContext.handle, this fix does its best to allow CLI.cmd to return a response when doable.
> [WFCORE-1456] [WFCORE-1471] CLI class to handle offline mode and commands

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/Console.java
make sure the prompt is always displayed
if the console is started from other methods than CommandContextImpl.interact
we need to make sure that we redisplay the prompt when interact is eventually
called.
> [WFCORE-1508]

- pom.xml
- testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnHttpTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/adminonly/auditlog/AdminOnlyAuditLogTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerShutdownTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractLoggingTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/ReconnectSyslogServerTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadOpsTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/RemoveManagementInterfaceTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GlobalOpsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpPostMgmtOpsTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/ReloadWithConfigTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/suspend/web/SuspendResumeTestCase.java
- testsuite/test-runner/pom.xml
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Reverts wildfly/wildfly-core#1227
Reverting as we are finding other issues like the one discussed yesterday. We need some sort of cleanup or a way to avoid this problem.
A quick check for scope:
```
git grep "static ManagementClient"
protocol/src/main/java/org/jboss/as/protocol/mgmt/ManagementClientChannelStrategy.java:    public static ManagementClientChannelStrategy create(final Channel channel) {
protocol/src/main/java/org/jboss/as/protocol/mgmt/ManagementClientChannelStrategy.java:    public static ManagementClientChannelStrategy create(final ProtocolChannelClient setup,
protocol/src/main/java/org/jboss/as/protocol/mgmt/ManagementClientChannelStrategy.java:    public static ManagementClientChannelStrategy create(final ProtocolConnectionConfiguration configuration, final …
```
> Revert "Improve test runner to allow few more things when running in manual s…"

- controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java
PersistanceResourceTestCase fails on Windows 10 (out-of-box configuration), where
defaultPermissins list contain only groups, ownerPermissions is empty set thus assertion fail
This is a follow-up to https://github.com/wildfly/wildfly-core/pull/1513
Jira:
https://issues.jboss.org/browse/WFCORE-1522
> [WFCORE-1522] PersistanceResourceTestCase fails if defaultPermissions contain only groups

- pom.xml
- testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnHttpTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/adminonly/auditlog/AdminOnlyAuditLogTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerShutdownTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractLoggingTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/ReconnectSyslogServerTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadOpsTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/RemoveManagementInterfaceTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GlobalOpsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpPostMgmtOpsTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/ReloadWithConfigTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/suspend/web/SuspendResumeTestCase.java
- testsuite/test-runner/pom.xml
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildflyTestRunner.java
fixed version of #1227 
- allows us to not use arquillian in manual tests in full.
- adds support for deploy/undeploy operations on container.
- adds reload() method on server
> Improve test runner to allow few more things when running in manual server mode

- controller/src/main/java/org/jboss/as/controller/BlockingTimeout.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventory.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerSuspendHandler.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
This issue has been created from @bstansberry comments on https://github.com/wildfly/wildfly-core/pull/1490. 
It adds a blocking timout for the calls done by the HC when :suspend-servers operation is executed.
Jira issue is:
https://issues.jboss.org/browse/WFCORE-1473
> [WFCORE-1473] Improve inter-process handling for suspend servers operation using a blocking timeout

- logging/src/main/java/org/jboss/as/logging/LoggingResource.java
- logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
If several file handlers are defined with several associated files traversing the log directory can be slow. This keeps walking the file tree to a minimum to improve performance.
> [WFCORE-1503] Improve performance of the dynamic log files on the logging subsystem resource.

- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/OldVersionTestRunner.java
- testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/Version.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Use core dist where appropriate to save space
Clear the legacy jdk version property if we are using the current jdk
> Client old server

- cli/src/main/java/org/jboss/as/cli/CommandCompleter.java
- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/operation/CommandLineParser.java
- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/ParsedCommandLine.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultCallbackHandler.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/RolloutPlanCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/SingleRolloutPlanGroup.java
- cli/src/main/java/org/jboss/as/cli/parsing/ParserUtil.java
- cli/src/test/java/org/jboss/as/cli/completion/address/test/AbstractAddressCompleterTest.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/OperationNameCompletionTestCase.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/PropertiesCompletionTestCase.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/PropertiesWithIndexCompletionTestCase.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/CommandLineArgumentsTestCase.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/CommandTestCase.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/OperationParsingTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Added support for the "!" operator for operation. 
Removed remote call to retrieve operation description, boolean values are set according to command syntax (implicit value == true, ! == false)
> [WFCORE-1514] Add '!' operator for operation arguments

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventory.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerResumeHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerSuspendHandler.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
Basically this PR continues previous changes done in WFCORE-1473 applying them to other suspend and resume operations in ManagedServer.
Jira issue is: https://issues.jboss.org/browse/WFCORE-1535
Implementation note:
It looks like that ServerInventory#suspendServer(String serverName) does 99% the same as ServerInventory#awaitServerSuspend(Set<String> waitForServers, int timeoutInSeconds, BlockingTimeout blockingTimeout) using a timeoutInSeconds = 0. So in this issue there is a proposal to simplifying them.
The small difference is the following. Internally ServerInventory#suspendServer(String serverName) is executing this operation using the ManagedServer#suspend():
```
final ModelNode operation = new ModelNode();
operation.get(OP).set(SUSPEND);
operation.get(OP_ADDR).setEmptyList();
``` …
> [WFCORE-1535] Avoid a potential blocking forever for ManagedServer suspend() and resume()

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
https://issues.jboss.org/browse/WFCORE-1554
> [2.x] WFCORE-1554 Building an attribute based on another attribute does not copy CapabilityReferenceRecorder

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/WildCardReadsTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
For a global operation check that if the address doesn't resolve in the middle of it we fail.
Jira: https://issues.jboss.org/browse/WFCORE-857
> [WFCORE-857]: A read-resource on a subsystem resource of a missing deployment returns a successful completion

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/ParsedBootOp.java
- controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
- core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
- jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java
- jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/HierarchicalCompositionTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/AuditLogTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ServerRestartRequiredTestCase.java
Changing the way a server boots by moving all management and socket related operations to a first batch that will stop the boot process if there is an error.
The other operations subsystems mostly) are in a second batch that won't stop the server from booting.
Fixing some tests according to this new paradigm.
Adding a hack in the ModelControllerImpl for Core Model Tests as we don't have services ready in those tests and they would be breaking with this change.
Jira: https://issues.jboss.org/browse/WFCORE-307
> [WFCORE-307]: When Wildfly fails with JBAS015810: failed to resolve interface management, it should terminate.

- domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_4.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
The commit here implements the enhancement noted in https://issues.jboss.org/browse/WFCORE-1597 to be a bit lenient while checking if the configured truststore's keystore provider type is JKS, to avoid running into hard to debug SSL issues as noted in the forum thread here https://developer.jboss.org/message/958142#958142
> [master] Enhancement WFCORE-1597

- domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_4.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
The commit here implements the enhancement noted in https://issues.jboss.org/browse/WFCORE-1597 to be a bit lenient while checking if the configured truststore's keystore provider type is JKS, to avoid running into hard to debug SSL issues as noted in the forum thread here https://developer.jboss.org/message/958142#958142
> [2.x branch] Enhancement WFCORE-1597 

- cli/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
- core-model-test/pom.xml
- host-controller/src/main/java/org/jboss/as/host/controller/Main.java
- logging/pom.xml
- patching/pom.xml
- patching/src/main/java/org/jboss/as/patching/metadata/PatchMerger.java
- patching/src/main/java/org/jboss/as/patching/metadata/PatchXml.java
- patching/src/test/java/org/jboss/as/patching/metadata/PatchXmlUnitTestCase.java
- patching/src/test/java/org/jboss/as/patching/tests/PatchModuleInvalidationWithRenamingFailureTestCase.java
- pom.xml
- remoting/tests/pom.xml
- server/pom.xml
- testsuite/domain/pom.xml
- testsuite/manualmode/pom.xml
- testsuite/patching/src/test/java/org/jboss/as/test/patching/CumulativePatchingScenariosTestCase.java
- testsuite/pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/interfaces/JmxManagementInterface.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
- Update compiler config for JDK9 b118+
- WFCORE-1374 - make code work with jdk9b115 and newer
- upgrade jboss-modules to 1.5.2.Final
- upgrade jboss-marshalling to 1.4.11.Final
- [WFCORE-1490] JDK9 doesn't provide sun.boot.class.path attribute
- [WFCORE-1491] Don't rely on default (JDK) JAXP providers - specify explicit ones
- [WFCORE-1493] Fix proper -Djdk.launcher.addexports.%d JVM property values propagation
- [WFCORE-1431] Define and propagate ${modular.jdk.args} property where necessary
- Properly create writers with charset and cleanup resources
> [2.x] WFCORE-1374 - backport jdk9 related changes from master

- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
This is a large rewrite of the ValueTypeCompleter class in order to replace the usage of stack and list with an object model of the parsed instances relationships.
The ValueCompleter used to support a syntax that looked invalid. Inside a List, one could type the properties of a complex object without the '{' and '}' characters. I really didn't see the point and Alexey confirmed that it was not a supported syntax. As soon as we have more than an item in the list, this is broken. I have removed this completion behavior.
In addition, support for List of complex types has been added.
> Fix for WFCORE-1599

- cli/src/main/java/org/jboss/as/cli/impl/CliShutdownHook.java
https://issues.jboss.org/browse/WFCORE-1611
Fix a potential deadlock on _handlers_ in issue reported scenario.
> [WFCORE-1611] fix CLI stuck if SIGINT is send during authentication dialogue.

- pom.xml
This is opened against 2.x as well because https://github.com/wildfly/wildfly-core/pull/1517 was also in 2.x. The log manager will fail to boot a custom handler without the fix for https://issues.jboss.org/browse/LOGMGR-127.
> [2.x] [WFCORE-1624] Upgrade jboss-logmanager from 1.0.3.Final to 1.0.4.Final

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleMode.java
modulePath is null when executed inside WildFly Swarm, therefore causing a NPE in this method
> [WFCORE-1629] Fixed potential NPE

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadOperationDescriptionHandler.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
* in ReadResourceDescriptionHandler, delegate to
ReadOperationDescriptionHandler's DescribedOp to ensure a consistent
operation description in both :read-resource-description and
:read-operation-descripion
JIRA: https://issues.jboss.org/browse/WFCORE-1625
> [WFCORE-1625] Fix operations output in :read-resource-description

- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultCallbackHandler.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/VariablesTestCase.java
https://issues.jboss.org/browse/WFCORE-1617
DefaultCallbackHandler sets "lastChunkIndex" during every necessary validation (validatedNodeType, validatedNodeName, validatedOperationName, etc) which is based on resolved value. This gives an incorrect offset value in case of variable or property substitution is applied.
> [WFCORE-1617] fix tab completion for cli variables and properties.

- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/descriptions/DefaultOperationDescriptionProvider.java
- controller/src/main/java/org/jboss/as/controller/descriptions/StandardResourceDescriptionResolver.java
- controller/src/test/java/org/jboss/as/controller/OperationDefinitionTestCase.java
- controller/src/test/resources/org/jboss/as/controller/OperationDefinitionTestCase.properties
Adding support for reply parameter description using a different text from the parameter.
Jira: https://issues.jboss.org/browse/WFCORE-313
https://github.com/wildfly/wildfly/pull/8440 is needed to have integration builds green.
http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=80520&tab=buildResultsDiv&buildTypeId=WildFlyCore_PullRequest_WildFlyCoreFullIntegration
http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=80523&tab=buildResultsDiv&buildTypeId=WildFlyCore_PullRequest_WildFlyCoreFullIntegration
> [WFCORE-313]: DefaultOperationDescriptionProvider uses incorrect call  to create reply parameter description.

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-debian.sh
- core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
- core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly.conf
Now that WildFly creates an startup-marker we can detect an error before timeout of the init.d startup scripts.
I also change tabs for spaces, but the real change is in the start() section on:
grep -i 'error:' "$JBOSS_MARKERFILE"
> WFCORE-1604 Fail-fast start up init.d scripts on error / WFCORE-1615 Make wildfly-init-redhat.sh consistent with wildfly-init-debian.sh

- cli/src/main/java/org/jboss/as/cli/CliConfig.java
- cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/Namespace.java
- cli/src/main/resources/help/help.txt
- cli/src/main/resources/schema/wildfly-cli_3_1.xsd
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockCliConfig.java
- core-feature-pack/src/main/resources/content/bin/jboss-cli.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
In addition to allow for echoing the command in non interactive mode, the CLI XSD config file has been upgraded to release 3.1. Although the latest XSD was 3.0, the shipped xml config file was still 2.0. I have upgraded the shipped XML file to release 3.1.
The test that was conflicting with WFCORE-1590 has been fixed.
> Fix for WFCORE-1614

- cli/src/main/java/org/jboss/as/cli/CommandCompleter.java
- cli/src/main/java/org/jboss/as/cli/impl/Console.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/CommandCompletionTestCase.java
- cli/src/test/java/org/jboss/as/cli/completion/operation/test/DeployCompletionTestCase.java
…rompt. Enable DeployCompletionTestCase.
https://issues.jboss.org/browse/WFCORE-1627 
1. fix a tab completion issue when cursor moves.
2. DeployCompletionTest is never running, rename it to match *TestCase pattern. Also enable an ignored test.
> [WFCORE-1627] CLI tab comple should reflect current position of prompt. Enable DeployCompletionTestCase.

- cli/src/main/resources/help/module.txt
Upstream issue:
https://issues.jboss.org/browse/WFCORE-1645
> [WFCORE-1645] Missing whitespace indent in module command help message

- pom.xml
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestUtil.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformersTestCase.java
- upgrade wildfly-legacy-test 2.0.1.Final to address additional capability registration in subsystem tests
> EAP7 remoting transformers test

- controller/src/main/java/org/jboss/as/controller/ProxyOperationAddressTranslator.java
- controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java
- controller/src/test/java/org/jboss/as/controller/ProxyOperationAddressTranslatorTestCase.java
This restores the ProxyAddressTranslated address for a result by providing a method in ProxyAddressTranslater to merge the original op address, and the result. Thoughts / comments appreciated, as always.
> WFCORE-1561 restore truncated result address

- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/remote/ModelControllerClientOperationHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/resources/StoppedServerResource.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/PreparedResponseTestCase.java
- testsuite/shared/src/main/java/org/wildfly/test/shutdown/SlowStopService.java
- testsuite/shared/src/main/java/org/wildfly/test/shutdown/SlowStopServiceActivator.java
Shutdown and reload are now treated in the same 'way', sending a prepared response before the services are stopped effectively.
Jira: https://issues.jboss.org/browse/WFCORE-1008
> [WFCORE-1008]: Treat ":shutdown" requests similarly to ":reload" in the server-side operation handler.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/AbstractDeploymentUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
Closing the client when the container stops.
Jira: https://issues.jboss.org/browse/WFCORE-1640
CI : https://ci.wildfly.org/viewType.html?buildTypeId=WildFlyCore_MasterWindowsOpenJDK8&branch_WildFlyCore=%2FWFCORE-1640%3B%2Fehsavoie&tab=buildTypeStatusDiv
The only failure doesn't seem related to it as it looks like a server process went wild.
> [WFCORE-1640]: Intermittent failure in DeploymentScannerUnitTestCase.

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHttpHandler.java
https://issues.jboss.org/browse/WFCORE-1672
> WFCORE-1672: Add 'Vary: Origin' header for CORS responses

- core-feature-pack/src/main/resources/content/bin/common.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.bat
- core-feature-pack/src/main/resources/content/bin/standalone.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.sh
require env var "GC_LOG" to enable it.
to enable it:
- in linux `export GC_LOG=true`
- in powershell `$env:GC_LOG=$true`
- in cmd `set GC_LOG=true`
> WFCORE-1665 Enable GC logging function in startup scripts

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
Jira: https://issues.jboss.org/browse/WFCORE-1671
Another related PR: https://github.com/wildfly/wildfly/pull/9067 to remove the AbstractVaultReader services file from full's security module, there is one in core already.
> [WFCORE-1671] security-realms that defer to jaas cannot load login-modules from org.jboss.as.security

- core-feature-pack/src/main/resources/content/bin/common.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.bat
- core-feature-pack/src/main/resources/content/bin/standalone.conf
- core-feature-pack/src/main/resources/content/bin/standalone.conf.bat
- core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
- core-feature-pack/src/main/resources/content/bin/standalone.sh
Mostly improve usabilty for enabling/disabling GC_LOG so you can also configure it in .conf/.conf.ps1/.conf.bat config file.
With this change changing default for gc logging is one simpler, so downstream project doesn't need to do lots of changes to whole script.
> WFCORE-1665 Improve usability on default value for gc logging

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
Added tests for 'alias' and 'unalias' commands in interactive jboss-cli mode. 
JIRA: https://issues.jboss.org/browse/WFCORE-1674
> [WFCORE-1674] integration tests for alias/unalias commands in interactive mode

- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironmentWrapper.java
- host-controller/src/main/java/org/jboss/as/host/controller/Main.java
- server/src/main/java/org/jboss/as/server/Main.java
- server/src/main/java/org/jboss/as/server/ServerEnvironmentWrapper.java
- server/src/main/java/org/jboss/as/server/SystemExiter.java
please see https://issues.jboss.org/browse/WFCORE-1686
As suggested in Jira above, this differentiates between "real" abort and "harmless" abort. In case of  parameter -v and --help, it does not show any fatal message. For other incomplete server environment cases, it adds the message into log.
> [WFCORE-1686] distinguish abort reason in order to log message properly.

- cli/src/main/resources/help/connect.txt
Help message for connect command refers to old default protocol.
https://issues.jboss.org/browse/WFCORE-1704
> [WFCORE-1704] Update the default protocol in connect command help message

- cli/src/main/java/org/jboss/as/cli/gui/JConsoleCLIPlugin.java
Issue: https://issues.jboss.org/browse/WFCORE-1015
initialize the jpanel once the connection is established.
added error for https://github.com/wildfly/wildfly-core/pull/1123
> [WFCORE-1015] jconsole Wildfly CLI tab not loading when using remote

- cli/src/main/java/org/jboss/as/cli/CommandCompleter.java
- cli/src/main/java/org/jboss/as/cli/handlers/DeploymentOverlayHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/EchoDMRHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchEditLineHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/ifelse/IfHandler.java
- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
Cursor is now used to allow for completion in the middle of a line.  Some completers were passing 0 as a cursor value, this has now to be replaced by the buffer size.
New unit tests added. CliCompletionTestCase (that was not run in the TestSuite) has been also updated. It has been added to the TestSuite.
> Fix for WFCORE-1680

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
@jfdenise @schvarc FYI. WFCORE-1729 is to fix the test or fix the bug that causes the failure.
> Ignore intermittently failing test

- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
The log manager may be wrapped which shouldn't stop the subsystem from working as long as it's a JUL based log manager.
This is a fix for https://issues.jboss.org/browse/WFCORE-1429. I've tried to think of the consequences of wrapping the log manager. The only possible issues I could come up with MDC and NDC. However the jboss-logging binding provider does seem to be the JBoss Log Manager provider. This should work as should the logging subsystem configuration. Since the configuration doesn't directly use the `org.jboss.logmanager.LogManager` directly. 
One cause for concern would be boot strap logging might not be configured correctly. This is likely okay though as care was taken to get around using the correct log manager and allowing WildFly to boot with the logging subsystem and not …
> [WFCORE-1429] Allow the log manager check to skipped

- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/ConfigurationPersisterFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- keep the remote file repository so it's available when the DC becomes available again
- parse domain.cached-remote.xml to a temporary file until boot is successful to prevent any boot errors leaving it in a clobbered state
- if any remote content is unavailable from an offline DC during boot, and not present in the local repository, abort the boot.
> WFCORE-316: --cached-dc additional fixes

- domain-management/src/main/java/org/jboss/as/domain/management/ConfigurationChangeResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/CoreManagementResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
- domain-management/src/main/resources/org/jboss/as/domain/management/_private/LocalDescriptions.properties
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ConfigurationChangesTestCase.java
- testsuite/domain/src/test/resources/domain-configs/domain-config-changes.xml
- testsuite/domain/src/test/resources/host-configs/host-master-config-changes.xml
- testsuite/domain/src/test/resources/host-configs/host-slave-config-changes.xml
Calling /core-service=management/service=configuration-changes:add() will only return a warning and nothing happen on DC or HC.
Activating configuration-changes on DC/HC will propagate to its managed servers.
Starting a managed server on a HC with configuration-changes enabled will enable it on the maanged server.
Jira: https://issues.jboss.org/browse/WFCORE-1642
Analysis Document: https://developer.jboss.org/wiki/DesignNotesForConfigurationChangesInDomainMode
EAP7 issue: https://issues.jboss.org/browse/EAP7-575
> [WFCORE-1642]: Fix domain mode for configuration changes.

- deployment-repository/pom.xml
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
- pom.xml
The zip FileTime(s)depend on the local timezone so the hash will change according to the timezone.
Setting the user timezone when running surefire.
Jira: https://issues.jboss.org/browse/WFCORE-1748
> [WFCORE-1748]: Failure in ContentRepositoryTest.testExplodeSubContent

- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/jvm/AbstractJvmModelTest.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/JvmXml.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/operations/CustomFormattersTestCase.java
It wouldn't surprise me if this requires changes in full, as I had to fix some stuff in core to avoid failures due to incorrectly formatted params being compared to the resulting model. That's what the last 3 commits are.
Update: I was right. PR to fix test failures is https://github.com/wildfly/wildfly/pull/8957 . CI job to test this in combo with that PR is https://ci.wildfly.org/viewLog.html?buildId=18356&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments
> [WFCORE-1581] Convert LIST of PROPERTY to OBJECT for attributes of type OBJECT

- host-controller/src/main/java/org/jboss/as/host/controller/operations/StartServersHandler.java
Issue is described in https://issues.jboss.org/browse/WFCORE-1715
Due to StartServersHandler L99, it is not possible reset the HostRunningModeControl.RestartMode to its default in doReload() of HostProcessReloadHandler, because the RestartMode.HC_ONLY is used out of the scope of doReload().
The simplest change to resolve this issue is reset it after a HC reload, for this reason I propose add it to StartServersHandler. More elaborated solutions can be done instead, for example maybe use the hostControllerEnvironment.isRestart() flag only for the if in StartServersHandler L99 (but it seems this flag is for a for a different purpose, changed only if the HC has been respawned by process controller) or use a specific flag for this if as a new instance variable in HostRunningModeControl, …
> WFCORE-1715: Reset HostRunningModeControl.RestartMode to its RestartMode.SERVERS default value once the HC has been restarted

- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-web/undertow-server/main/module.xml
- pom.xml
This pull request is a foundation for making it possible to enable Elytron backed security for the EJB and Undertow subsystems for in-VM invocations and invocations over HTTP.  
Although the Elytron web module is not used directly by core as a result of this pull request it will be in a subsequent pull request where it will be used for management HTTP authentication so the module is added here rather than to WildFly.
This pull request will break the WildFly build, I will follow up with two pull requests to the WildFly repository: -
1 - A minimal PR that makes WildFly compatible with this PR.
https://github.com/wildfly/wildfly/pull/9160
2 - A more complete …
> [WFCORE-673] Elytron Core Integration

- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
Taking overwrite into account when adding content.
Jira: https://issues.jboss.org/browse/WFCORE-1756
> [WFCORE-1756]: Adding content to an exploded deployment with overwrite to false should fail if file already exists

- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
This occurs when the list of operations to be run on boot after adding the subsystem is empty.
Jira: https://issues.jboss.org/browse/WFCORE-1765
> [WFCORE-1765]: unclear NullPointerException if the deployment-scanner element is removed from the configuration.

- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Fixed the problem highlighted by the jgroup protocol complex type. A property named type was part of the set of valid properties. It revealed incorrect piece of code.
- Found an issue during testing with List of simple types.
- Added new unit tests for jgroups and list of simple types.
> Fix for WFCORE-1767. Exception on ValueType completion

- deployment-scanner/src/main/resources/schema/jboss-as-deployment-scanner_1_0.xsd
- deployment-scanner/src/main/resources/schema/jboss-as-deployment-scanner_1_1.xsd
- deployment-scanner/src/main/resources/schema/jboss-as-deployment-scanner_2_0.xsd
Just typo mistakes found in jboss-as-deployment-scanner .xsd documentation files
There is no jira issue related.
> Typo mistakes in jboss-as-deployment-scanner_x_y.xsd files

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ExplodedDeploymentReadContentHandler.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
- server/src/main/java/org/jboss/as/server/deployment/ExplodedDeploymentReadContentHandler.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java
Adding the stream uuid in the reponse node.
Jira: https://issues.jboss.org/browse/WFCORE-1741
> [WFCORE-1741]:  read-content operation does not return the uuid of thstream as the operation result

- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Fixed the exception in the case where the List is a List of OBJECT (no specified value type).
Fixed the completion of "[<TAB>" in this case. It was not proposing "{".
> Fix for WFCORE-1771, exception in :composite completion.

- cli/src/main/java/org/jboss/as/cli/gui/OperationDialog.java
JIRA: [WFCORE-1783](https://issues.jboss.org/browse/WFLY-6739)
Use default value when boolean attribute is an expression.
Remove duplicated if condition.
> [WFCORE-1783] CLI GUI throws exception when editing boolean attribute

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/test/java/org/jboss/as/cli/AttachmentTestCase.java
Fixed the case where the Value-type advertise an OBJECT type, with Value-Type being a String although the actual content is an Object.
> Fix for WFCORE-1787. Exception when traversing complex Objects

- cli/src/main/java/org/jboss/as/cli/handlers/AttachmentHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AttachmentTestCase.java
Batch step index was not incremented. Reject options that are invalid with display.
> Fix for WFCORE-1794. Attachment, option and batch issues

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Configure the test to use a temporary home dir.
> Fix for WFCORE-1803. Fix test to not change user history

- .gitignore
- pom.xml
- zanata.xml
The first commit just upgrades the Zanata plugin to align with the version the server is on as well as make the configuration changes necessary for the 3.0 repository.
The second commit is not required, but help help reduce the size of the final distribution a bit. It simply just excludes the files needed for the logging tooling to generate the i18n loggers and message bundles. These files are only required at compile time and not used at run time.
If the second commit is not desirable I can remove it.
Just to keep things linked together https://github.com/wildfly/wildfly-checkstyle-config/pull/8 will be needed once we start pulling down translations. Some of the files pulled down have trailing spaces which fails the build. Previously I just went through and fixed them, but I think this …
> [i18n] Updates to the Zanata plugin and configuration

- cli/src/main/java/org/jboss/as/cli/impl/VaultConfig.java
https://issues.jboss.org/browse/WFCORE-1807 https://issues.jboss.org/browse/JBEAP-5690
Trimmed vault-option _name_ and _value_ makes problem when custom vault implementation which prepends string to an executable command.
Notice that the [VaultXml.java](https://github.com/wildfly/wildfly-core/blob/bc4988960e9bd245318321a06ae3d001ec661bc5/server/src/main/java/org/jboss/as/server/parsing/VaultXml.java#L172) does not do this trim() call for any vault-option _name_ and _value_.
> [WFCORE-1807] fix trimmed vault-option name and value.

- server/src/main/java/org/jboss/as/server/deployment/ExplodedDeploymentAddContentHandler.java
The bug was in 2 parts : path wasn't a correct attribute, and overwrite wasn't looked in the correct part of the operation.
The overwrite is part of the operation, not of the content node.
> [WFCORE-1793]: add-content operation fails to overwrite existing content with overwrite=true set when passing content by file path.

- deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
- deployment-repository/src/test/java/org/jboss/as/repository/PathUtilTest.java
Without this changes certain windows systems would get this failures:
```
ContentRepositoryTest.testChangeExplodedContent:228 » ExplodedContent WFLYDR00...
ContentRepositoryTest.testExplodeContent:133 » ExplodedContent WFLYDR0018: Err...
ContentRepositoryTest.testExplodeSubContent:155 » ExplodedContent WFLYDR0018: ...
ContentRepositoryTest.testListContents:279 » ExplodedContent WFLYDR0018: Error...
DeletionCollisionTest.testFileLockByReadContent:77 » ExplodedContent WFLYDR002...
DeletionCollisionTest.testFileLockByRemoveContent:100 » ExplodedContent WFLYDR...
PathUtilTest.testReadFile:141 » AccessDenied target\temp\pathutil\unarchive148...
```
Which is result of "wrongly" setting permissions when creating temporary directory.
> fix deployment repository test failures on windows

- jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
JMX tests was using port 12345, which caused unexplainable "random" JMX tests failing - tests failed when HipChat was running.
Changed to (hopefuly) less used port 27258 and extracted to constant.
> Change port used by JMX/remoting tests to prevent collisions

- server/src/main/java/org/jboss/as/server/SelfContainedContainer.java
- server/src/main/java/org/jboss/as/server/ServerEnvironment.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
The temp files created in `LaunchType.SELF_CONTAINED` are now managed by the `SelfContainedContainer`.  Alongside I've added a `SelfContainedContainer#stop()` to explicitly manage the teardown lifecycle.
> WFCORE-1797: Move temp file handling to SelfContainerServer

- controller/pom.xml
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
- controller/src/main/java/org/jboss/as/controller/security/CredentialStoreClient.java
- controller/src/main/java/org/jboss/as/controller/security/CredentialStoreURIParser.java
- server/src/main/resources/schema/wildfly-config_5_0.xsd
This is initial commit that introduces:
- CredentialReference class unifying access to credentials defined through CredentialStore or holding simple secret value. It defines credential reference attribute that other subsystems can use to reference external credentials of various types.
- CredentialStoreClient class used to talk to CredentialStore to obtain secret value (credential) from it.
- CredentialStoreURIParser class that parses configuration or reference URIs for easier parameter marshaling
These changes are tracked under the following Jira issue: -
https://issues.jboss.org/browse/WFCORE-1547
This Jira issue can be closed once the PR is merged.
If …
> [WFCORE-1547] Iniital CredentialStore Integration

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/AttributeTypeDescrValueCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/CapabilityReferenceCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
- controller/src/main/java/org/jboss/as/controller/PathAddress.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/ImmutableCapabilityRegistry.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/PossibleCapabilityRegistry.java
- controller/src/test/java/org/jboss/as/controller/SuggestCapabilitiesTestCase.java
- server/src/main/java/org/jboss/as/server/controller/resources/CapabilityRegistryResourceDefinition.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCapabilityCompletionTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCapabilityCompletionTestCase.java
This change incorporates cli, controller and server changes.
Something to mention is that I am using the Java FileSystem glob pattern matcher to match the capabilities registration points with the possible registration points. Looking at the /xxx/* kind of syntax, it is compliant with the Filesystem matcher (and avoid to create a special Java Pattern for these paths).
A controller unit test has been added to cover the main combinations of capability resolution according to the existing scopes.
This test is quite long and it could be reduced to cover fewer nominal cases. Let me know if you are OK to keep it or would like it to be reduced even removed if it goes too far in the knowledge of scopes.
> Fix for WFCORE-1774. Suggest capabilities and CLI capability completion.

- controller/src/main/java/org/jboss/as/controller/AttributeParser.java
- controller/src/main/java/org/jboss/as/controller/AttributeParsers.java
- controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
- controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java
- controller/src/test/resources/org/jboss/as/controller/persistence/core-subsystem.xml
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemParser_1_0.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemParser_1_1.java
- WFCORE-1831 Build XML parser from a resource's pathElement
- update io subsystem parsers to use non deprecated api
- WFCORE-1824 Can not parse object list attributes that contains a complex attribute
> WFCORE-1831 / WFCORE-1824 Few parser fixes & improvments

- server/src/main/java/org/jboss/as/server/deployment/service/ServiceActivatorProcessor.java
[WFCORE-1235] : https://issues.jboss.org/browse/WFCORE-1235
> [WFCORE-1235] : Multiple triggers of each activator service when there are multiple modules with different service activator files in an ear.

- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DeploymentTransformers.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayContentDefinition.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentOverlayTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java
Adding a new stream attribute to access the content as a stream.
Jira: https://issues.jboss.org/browse/WFCORE-1778
> [WFCORE-1778]: Deprecate /deployment-overlay=*/content=*:read-content replace with a response stream variant.

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AttachmentTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
@jfdenise, fyi, I think this only shows up if the test order is randomly different.
> fix AttachmentTestCase leaving a deployment around causing BasicOperationsUnitTestCase#testPathInfo to measure size of the content dir > 0b

- controller/pom.xml
- controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
- controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/projectodd/vdx/main/module.xml
- logging/pom.xml
- pom.xml
This includes the following changes:
- brings in VDX (https://github.com/projectodd/vdx) as a private module
- wraps the XMLStreamExceptions created by ParseUtils with a
VDX-provided XMLStreamException subclass that holds more context about
the failure
- catches XMLStreamExceptions when reading configuration in
XmlConfigurationPersister, and hands off the exception to VDX's
printer
VDX needs the schemas from `$JBOSS_HOME/docs/schema`. If those aren't
available (or VDX fails to print the failure due to an internal error),
XmlConfigurationPersister will fall back to the old behavior of throwing
ControllerLogger.ROOT_LOGGER.failedToParseConfiguration with the
original exception.
> [WFCORE-1728] Use VDX to pretty-print config errors

- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
- host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentExplodeHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentExplodeHandler.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
If the target path of an 'explode' operation doesn't exist we now fail.
Jira: https://issues.jboss.org/browse/WFCORE-1846
> [WFCORE-1846]: Exploding subdeployment of an unexploded deployment should fail.

- controller/src/main/java/org/jboss/as/controller/remote/RemoteProxyController.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainSlaveHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/HostControllerUpdateTask.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerProxy.java
- server/src/main/java/org/jboss/as/server/DomainServerMain.java
If the reason we are cancelling is because the remote process is not responding, waiting for a remote response to the cancellation request will result in uninterruptible blocking.
Also incorporates fix for WFCORE-1848 which relates to the same general area of better behavior of domain servers in the presence of java.lang.Error.
> [WFCORE-1844] Avoid blocking cancellation in intra-domain communications

- deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
Wrong relative path computed for zip browse operation.
Jira: https://issues.jboss.org/browse/WFCORE-1851
> [WFCORE-1851]: Inconsistent behaviour with browse-content(depth=1) operation between archived and exploded deployments

- cli/pom.xml
- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/codehaus/woodstox/main/module.xml
- core-model-test/pom.xml
- logging/pom.xml
- patching/pom.xml
- pom.xml
- remoting/tests/pom.xml
- server/pom.xml
- subsystem-test/framework/pom.xml
- subsystem-test/tests/pom.xml
- testsuite/pom.xml
This will come handy in future wrt JDK9
Changelist vs 4.4.x we ware using before 
5.0.3 (23-Aug-2016)
- 13: `BasicStreamReader.getElementText()` behavior doesn't match Java documentation
- 15: `BasicStreamReader` should use `WstxUnexpectedCharException` instead of WstxParsingException
- 16: Incorrect validation error(s) only using Stax2 writer
- 21: 500 characters limit when calling XMLStreamReader#getText() after CDATA event
5.0.2 (10-Dec-2015)
- 10: Stax 4.0.0 is not compatible with Woodstox 5.0.1
5.0.1 (02-Apr-2015)
- 3: Initial 5.0.0 release did not contain class files (d'oh!)
- 4: Fix validation of text for an XMLStreamWriter
5.0.0 
- Attempted initial release under new home on github with new GAV
> WFCORE-1814 Move to woodstox 5.0.3

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
This was causing an extra pair of double quotes to appear in the call to wildfly-service.exe, breaking the installation for domain mode.
> service.bat - fix quotes around domain BASE path

- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
When the candidates provider returns an empty list of arguments it can be caused by:
- No arguments in the operation
- An error occurred (invalid operation)
If the provider returns an empty list BUT the user has typed some content, then there is a mismatch. The empty list must have been caused by an error, so do not complete.
> Fix for WFCORE-1857. No completion for invalid operation

- controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerExtension.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerParser_1_0.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerParser_1_1.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerParser_2_0.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOExtension.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemParser_1_0.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemParser_1_1.java
- jmx/src/main/java/org/jboss/as/jmx/JMXExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- pom.xml
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
- introduces parser providers (via staxmapper 1.3)
- migrates core subsystems to use it
- should reduce memory usage down a bit
> WFCORE-1841 lazy subsystem parser support

- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
Added minor comment about the uses of operation-id in reload operation in domain mode.
Jira issue is:
https://issues.jboss.org/browse/WFCORE-1791
> [WFCORE-1791] Added minor comments about uses of operation-id in reload operation

- cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
- cli/src/main/resources/help/deploy.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllDomainTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeployTestCase.java
Replace '<all>' with '*'. '<' and '>' characters could conflict with future CLI developments.
> Fix for WFCORE-1878. Use * to identify all disabled deployments.

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java
- controller/src/main/java/org/jboss/as/controller/registry/Resource.java
- logging/src/main/java/org/jboss/as/logging/LoggingResource.java
- logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
During boot runtime resources should be ignored for validation. This also expands the resource to allow for a shallow copy of the resource. This is useful when child values may not be important, but the child key is important.
> [WCFORE-1845] During boot skip validating/verifying runtime resources

- controller/src/main/java/org/jboss/as/controller/descriptions/DeprecatedResourceDescriptionResolver.java
this class is used to help with deprecating subsystems, but itself is not really deprecated, it was just producing useless warnings in all subsystems that are using it
> un-deprecate DeprecatedResourceDescriptionResolver

- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java
- controller/src/main/java/org/jboss/as/controller/registry/Resource.java
- logging/src/main/java/org/jboss/as/logging/LoggingResource.java
- logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
During boot runtime resources should be ignored for validation. This also expands the resource to allow for a shallow copy of the resource. This is useful when child values may not be important, but the child key is important.
Master PR https://github.com/wildfly/wildfly-core/pull/1870
> [2.x] [WCFORE-1845] During boot skip validating/verifying runtime resources

- core-feature-pack/src/main/resources/content/bin/standalone.bat
- core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
- WFCORE-1905 windows service (service.bat) failed to install if the value of /serviceuser has a white space inside
- WFCORE-1906 standalone.bat is unable to start from directory "jboss(eap)"
- WFCORE-1907 Win Service Script: Revise help for /host
> WFCORE-1905 WFCORE-1906 WFCORE-1907 minor script fixes

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/handlers/trycatch/TryCatchFinallyControlFlow.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/TryCatchFinallyTestCase.java
I am proposing to use the "suppressed Exception" feature of the Exception class.
When the Finally exception is thrown, it is suppressing the try or catch exception that could have been previously thrown.
When an Exception is printed to the console, the suppressed exceptions are also printed.
Added unit tests to cover this feature.
> Fix for WFCORE-1901. Don't swallow exception in try/catch/finally

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/AttributeNamePathCompletionTestCase.java
https://issues.jboss.org/browse/WFCORE-1908
METRIC is read-only attribute https://github.com/wildfly/wildfly-core/blob/master/controller/src/main/java/org/jboss/as/controller/registry/AttributeAccess.java#L44
> WFCORE-1908 Metric attribute is not writable.

- cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/RemoveManagementRealmTestCase.java
This is a change in the locking strategy of CLIModelControllerClient. It has been observed that the CLI could deadlock in case one abort (Ctrl-C) an already connected CLI that ts getting reloaded after a removal of the local auth authentication with default user $local-user. This could occur using shutdown --restart, reload or any command issued from an already connected CLI to a reconfigured server.
The connection is now done unlocked, allowing the close method to change the state of the ControllerClient to MUST_CLOSE in a locked block. 
The validity of the checks 'strategy == null' that are done in locked blocks has been preserved. strategy is set to a non null strategy in a locked block at the end of the connection. strategy != null still means "connection is done".
A simpler fix would …
> Fix for WFCORE-1919. CLI frozen after removal of local auth

- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/CapabilityReferenceCompleter.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Enhanced ValueTypeCompleter with support for list of Capability references. Only propose what the user has not already provided, propose ',' and ']' when appropriate.
Redesigned lightly ValueTypeCompleter/CapabilityReferenceCompleter to be testable without capabilities retrieved from server capability registry.
Fixed a ValueTypeCompleter issue that was making the OperationRequestCompleter to not complete the operation (with ')' character) when all arguments were present and the last one was associated to the ValueTypeCompleter.
> Fix for WFCORE-1920. Completion for list of capability references

- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-1931
Extra commas in descriptions of *-outbound-socket-binding CLI resources
> WFCORE-1931 fix typo in resource description.

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandler.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/SyncModelServerStateTestCase.java
Updating the SyncModelOperationHandler to synchronize the Master root attributes on the Slaves.
Can't use write attribute operations as those attributes are read-only.
Jira: https://issues.jboss.org/browse/WFCORE-1552
Jira: https://issues.jboss.org/browse/JBEAP-4591
> [WFCORE-1552]:  Slaves should report the master's version in the domain model.

- logging/src/main/resources/org/jboss/as/logging/LocalDescriptions.properties
[WFCORE-1949] : https://issues.jboss.org/browse/WFCORE-1949
> [WFCORE-1949]: Typos in /subsystem=logging resource descriptions.

- deployment-repository/src/main/java/org/jboss/as/repository/ContentFilter.java
- deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
- deployment-repository/src/test/java/org/jboss/as/repository/PathUtilTest.java
Checking if archived file is of type archive when browsing archive content.
Jira: https://issues.jboss.org/browse/WFCORE-1896
JBEAP issue: https://issues.jboss.org/browse/JBEAP-6632
> [WFCORE-1896]: Deployment operation browse-content(archive=true) does not return archives in archived deployments.

- launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
- pom.xml
This way launcher doesn't choke on parameters and most of testsuite runs.
> WFCORE-1374 - use posix syntax for --add-exports that works with launcher

- controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
- pom.xml
VDX 1.1.1 includes changes that will make it possible for WildFly Swarm
to use it.
The only visible change for WildFly is a wording change in the output when the schemas can't be found:
```
-no_schemas_available=%s: No schemas available at %s - disabling validation error pretty printing
+no_schemas_available=%s: No schemas available from %s - disabling validation error pretty printing
```
> Update to VDX 1.1.1

- cli/src/main/java/org/jboss/as/cli/impl/Console.java
Remove the stack printed when the prompt is interrupted.
> Fix for WFCORE-1969. Removed printStackTrace

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
This eliminates a NullPointerException calling connection-info when running an embedded server.
> [WFCORE-1731] Where we bind an existing client to the CommandContext create a ConnectionInfoBean to track the time.

- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACSensitivityConstraintUtilizationTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/FullRbacProviderTestSuite.java
Propagate the sensitive-classification and the application-classification to the managed servers.
JBEAP: https://issues.jboss.org/browse/JBEAP-6281
Jira: https://issues.jboss.org/browse/WFCORE-1899
> [WFCORE-1899-2.x]: Sensitive data can be exposed at the server level in domain mode.

- cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueCallbackHandler.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ArgumentValueConverterTestCase.java
Empty Object nested in Object was parsed as an UNDEFINED value.
> Fix for WFCORE-1992, undefined empty object

- deployment-repository/pom.xml
- deployment-scanner/pom.xml
- logging/pom.xml
- patching/pom.xml
- pom.xml
- testsuite/manualmode/pom.xml
Moving the Byteman port configuration to the parent pom.xml.
Changing the value from 9091 to 17091.
Jira: https://issues.jboss.org/browse/WFCORE-1952
> [WFCORE-1952]: Change byteman listening port to avoid conflicts with TeamCity.

- controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
https://issues.jboss.org/browse/WFLY-7432
https://issues.jboss.org/browse/JBEAP-6748
> [WFLY-7432] Elytron key-store requires set credential-reference which is wrongly marked as optional

- cli/src/main/java/org/jboss/as/cli/Util.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Applying replacements could fail for invalid arguments/properties and break the validate/not validate operation feature.
> Fix for WFCORE-1982. Invalid argument/property handling.

- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BatchTestCase.java
Compose an error message that contains the operation(s) that is(are) causing the exception.
> Fix for WFCORE-1902. More informative batch error

- cli/src/main/java/org/jboss/as/cli/handlers/FilenameTabCompleter.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Fix for --file and --properties options to support '~' character.
> Fix for WFCORE-2002. Handle '~' in options

- cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/AttributeNamePathCompletionTestCase.java
Don't propose attributes that can't be a map or a list. In some cases we don't know (map or list hidden in complex data structure). In these case, propose the candidates.
Take into account access-type and only expose mutable attributes for muting operations (add,remove,clear,put).
> Fix for WFCORE-1961. Fix lst/map operations completion.

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
sun.net.spi.nameservice.NameService can be customize via system property "sun.net.spi.nameservice.provider.<n>" but it was not working on WildFly. To make it work, module classloader "org.jboss.as.server:main" need to export module "sun.jdk:main".
Some <path> are added in "sun.jdk:main" to be able to use the original implementation as well.
> [WFCORE-1998] Support NameService customization via system property

- domain-management/src/main/java/org/jboss/as/domain/management/access/AccessIdentityResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-2017
> [WFCORE-2017] Don't enable the access=identity service if running in embedded admin only mode.

- controller/src/main/java/org/jboss/as/controller/registry/Resource.java
- network/src/main/java/org/jboss/as/network/OutboundSocketBinding.java
- server/src/main/resources/schema/jboss-as-config_1_1.xsd
- server/src/main/resources/schema/jboss-as-config_1_2.xsd
- server/src/main/resources/schema/jboss-as-config_1_3.xsd
- server/src/main/resources/schema/jboss-as-config_1_4.xsd
- server/src/main/resources/schema/jboss-as-config_1_5.xsd
- server/src/main/resources/schema/jboss-as-config_1_6.xsd
- server/src/main/resources/schema/jboss-as-config_1_7.xsd
- server/src/main/resources/schema/jboss-as-config_1_8.xsd
- server/src/main/resources/schema/jboss-as-config_2_0.xsd
- server/src/main/resources/schema/jboss-as-config_2_1.xsd
- server/src/main/resources/schema/jboss-as-config_2_2.xsd
- server/src/main/resources/schema/wildfly-config_3_0.xsd
- server/src/main/resources/schema/wildfly-config_4_0.xsd
- server/src/main/resources/schema/wildfly-config_4_1.xsd
- server/src/main/resources/schema/wildfly-config_4_2.xsd
- server/src/main/resources/schema/wildfly-config_5_0.xsd
Jira
https://issues.jboss.org/browse/WFCORE-2026
Causes 
https://issues.jboss.org/browse/WFLY-6915
> WFCORE-2026 source-port is wrongly offsetted when configured to 0, i.e. ephemeral port; results in "Permission denied (Bind failed)"

- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
- cli/src/main/resources/help/reload.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
--start-mode for reload command.
--admin-only has been deprecated. No more proposed by completion but still usable.
Added unit test and updated help.
Follows up on #1841
https://issues.jboss.org/browse/WFCORE-1829
> Fix for WFCORE-1829, added CLI reload support

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliSpecialCharactersTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1709
Description: Added tests for special characters in resource values for interactive and non-interactive CLI modes
> [WFCORE-1709] Added tests for special character resource values

- cli/src/main/java/org/jboss/as/cli/handlers/UndeployHandler.java
- cli/src/main/resources/help/undeploy.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/UndeployTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
My understanding is that, in domain mode, user can provide a subset of serverGroup at undeploy time.
If --keep-content is not set, then the artefact will be not undeployed because still deployed in other serverGroup. 
The change is as follow:
- If keep-content has not been set, we check that all server groups have been listed. If that is not the case, then we keep the content.
Unit test added.
> Fix for WFCORE-2054. keep-content if not all groups are listed

- jmx/src/main/java/org/jboss/as/jmx/AuthorizingMBeanServer.java
- jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java
- jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorService.java
- jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
- testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeployment.java
At a later point we can probably add a Handler / Filter / Interceptor for deployments to also switch authorization checking back on for the identity calling the deployment.
https://issues.jboss.org/browse/WFCORE-2035
> [WFCORE-2035] Switch off JMX authorization by default and switch it back on for remote access.

- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
https://issues.jboss.org/browse/WFCORE-2080
> [WFCORE-2080] Instantiating the WildFlyElytronProvider is an expensive operation so only do it once.

- core-feature-pack/src/main/resources/content/standalone/deployments/README.txt
- deployment-scanner/src/main/resources/schema/jboss-as-deployment-scanner_2_0.xsd
[WFCORE-2082]: Outdated deployment-scanner xml snippet in deployments readme.txt.
Updating the comments for a better UX.
Jira: https://issues.jboss.org/browse/WFCORE-2081
Jira: https://issues.jboss.org/browse/WFCORE-2082
> [WFCORE-2081]: Confusing description of scan-enabled attribute in deployment scanner XSD.

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainRolloutStepHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
Also fixes the test that would have caught this regression.
https://issues.jboss.org/browse/WFCORE-2055
https://issues.jboss.org/browse/WFCORE-2053
> [WFCORE-2055] Preserve any caller-type header associated with domain composite op steps

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/remote/BlockingQueueOperationListener.java
- controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClient.java
- controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClientImpl.java
- host-controller/src/main/java/org/jboss/as/domain/controller/DomainController.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainRolloutStepHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/plan/AbstractServerGroupRolloutTask.java
- host-controller/src/main/java/org/jboss/as/domain/controller/plan/ServerTaskExecutor.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- host-controller/src/main/java/org/jboss/as/host/controller/MasterDomainControllerClient.java
- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventory.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/mgmt/DomainControllerProtocol.java
- host-controller/src/main/java/org/jboss/as/host/controller/mgmt/MasterDomainControllerOperationHandlerImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/mgmt/ServerToHostProtocolHandler.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/DomainServerProtocol.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerClient.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/OperationTimeoutTestCase.java
This commit introduces a notification mechanism via which a listener for "controller instability" notifications can be created and wired into the ModelController.
In a domain server, such a listener is registered. In this case it's an additional function of HostControllerClient, which responds to notifications by asynchronously sending a message back to the managing HC.
Currently the managing HC simply logs a WARN when receiving such a message. In the future it could also do something else with the data, e.g. expose it over the management API for use by the admin console.
Notifications are currently sent in two cases:
1) An OperationContext is interrupted or times out waiting for MSC stability during operation finalization. This means MSC was not stable at the time of finalization and the …
> [WFCORE-2094] Domain server notifies HC upon controller instability

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCommentsTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Some tests require the output to be cleared prior to actually do testing.
> Fix for WFCORE-2107. Clear output prior to start testing

- pom.xml
- remoting/subsystem/src/main/java/org/jboss/as/remoting/Attribute.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/CommonAttributes.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem40Parser.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemExtensionTransformerRegistration.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemXMLPersister.java
- remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties
- remoting/subsystem/src/main/resources/schema/wildfly-remoting_4_0.xsd
- server/src/main/java/org/jboss/as/server/deployment/Phase.java
:bangbang:  Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :bangbang:
https://issues.jboss.org/browse/WFCORE-2134 Upgrade to WildFly Common 1.2.0.Beta3
https://issues.jboss.org/browse/WFCORE-2095 Add ability to use a reference to an AuthenticationContext for the outbound remote connection.
https://issues.jboss.org/browse/WFCORE-2138 Upgrade to JBoss Marshalling 2.0.0.Beta4
https://issues.jboss.org/browse/WFCORE-2140 Add two priorities for the Elytron AuthenticationContext deployment phases.
> Latest Incremental Merge of WildFly Elytron Integration Changes to WildFly Core

- cli/src/main/java/org/jboss/as/cli/handlers/DeploymentOverlayHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeploymentOverlayTestCase.java
Check the overlay name prior to make a request. In batch mode the name is only checked for actions that are not added to the batch (list-links, list-content).
The side effect is that upload action can now be added to a batch if the overlay doesn't exist (overlay could be added in the same batch, in a previous step).
Unit tests added.
> Fix for WFCORE-2142. Fix unknown overlay error messages.

- cli/src/main/java/org/jboss/as/cli/handlers/SetVariableHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
set command completion should only propose commands/operations if value starts with ` character.
Unit tests added.
> Fix for WFCORE-1856. Fix for set command completion.

- core-feature-pack/src/main/resources/content/bin/jboss-cli.sh
This fix allows to call kill -9 on the CLI java process without breaking the user shell (tty).
> Fix for WFCORE-2153. CLI, cleanup tty on Kill -9

- server/src/main/java/org/jboss/as/server/deployment/DeploymentFullReplaceHandler.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentRollbackFailureTestCase.java
Fixing rollback of full-replace-deployment in domain mode.
Jira: https://issues.jboss.org/browse/WFCORE-2157
JBEAP: https://issues.jboss.org/browse/JBEAP-8111
> [WFCORE-2157]: Full-replace rollback is failing with java.util.NoSuchElementException: No child 'name' exists.

- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
Cancelling task when Timeout is reached.
Jira: https://issues.jboss.org/browse/WFCORE-2176
JBEAP: https://issues.jboss.org/browse/JBEAP-8184
> [WFCORE-2176]:  ProcessStateListener execution isn't cancelled when timeout is reached.

- cli/pom.xml
Make log manager dependency an hard one. Required by embedded-server commands.
> Fix for WFCORE-1580. CLI dependency on logmanager is an hard one

- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Disable validation of the node path completer. Added unit tests to complete deployment-<TAB>
> Fix for WFCORE-2123. node path completion

- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentOperationsTestCase.java
* Adding browse-content and read-content operations to workflow of DeploymentTestCase and ExplodedDeploymentTestCase.
* Adding negative tests for browse-content and read-content operations to DeploymentOperationsTestCase.
> [WFCORE-379 WFCORE-380] Operations to browse and read content from the content repository

- core-feature-pack/src/main/resources/content/bin/vault.sh
Upstream Issue: https://issues.jboss.org/browse/WFCORE-2160
EAP Issue: https://issues.jboss.org/browse/JBEAP-8135
No downstream to EAP required as the branch (in core) related to 7.1.x has not been created (AFAIU).
> WFCORE-2160 - Incorrect JBOSS_HOME warning in vault.sh

- controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
I think we should use deprecation to drive users into using a more efficient @ctomc 's version of registering XML mappings to readers. Given that this can be easily overlooked and also easily fixed in many cases with just adding "() ->". Is there any reason not to?
> Deprecate old setSubsystemXmlMapping(..) method to drive users to a Supplier-based version instead

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
Base path is not resolved in the same way as with the Oracle JDK.
Jira: https://issues.jboss.org/browse/WFCORE-2189
IBM build: https://ci.wildfly.org/viewLog.html?buildId=40845
> [WFCORE-2189]: JmxControlledStateNotificationsTestCase fails on IBM JDK (domain module).

- pom.xml
This fixes a regression under Oracle/OpenJDK introduced when fixing
WFCORE-2172.
> Update to VDX 1.1.3

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java
- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
- domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
- domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_5.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapGroupSearcherFactory.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PrincipalToGroupResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
- server/src/main/resources/schema/wildfly-config_5_0.xsd
Making the parseGroupNameFromDn available through the DMR.
The legacy System property still works.
Jira: https://issues.jboss.org/browse/WFCORE-1228
> [WFCORE-1228]: Follow up on WFCORE-1202 and make the configuration available in the management model.

- cli/src/main/java/org/jboss/as/cli/AwaiterModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
Second attempt to fix this issue. We were not too far in the previous fix but we were wrongly exiting the reload waiting logic too early.
For reload, when redirect occurs, attempt to reconnect the client. If failure occurs, ignore it (could be caused by exotic Redirect sent during server startup) and carry-on the reload loop. If reconnect succeeds, exit the reload loop.
For shutdown, if IOException occurs, CLIModelControllerClient waits the end of the waiting time then propagate the RedirectException (if any). In turn the shutdown handler catchs the RedirectException and attempt to reconnect. If it fails, it disconnects the client.
Unit test added (the one from reverted commit).
> Fix for WFCORE-2216. Handle redirect in reload and shutdown

- controller/src/main/java/org/jboss/as/controller/operations/CompositeOperationAwareTransformer.java
Not cloning the returned operation will make any change to it affect future transformations.
Jira: https://issues.jboss.org/browse/WFCORE-2215
JBEAP: https://issues.jboss.org/browse/JBEAP-8376
> [WFCORE-2215]: Unable to force replacement of deployment in domain with deploy <path> --force high level command

- domain-management/src/main/java/org/jboss/as/domain/management/access/PrincipalResourceDefinition.java
- domain-management/src/main/resources/org/jboss/as/domain/management/_private/LocalDescriptions.properties
- server/src/main/resources/schema/wildfly-config_5_0.xsd
https://issues.jboss.org/browse/WFCORE-2231
> [WFCORE-2231] Deprecate the 'realm' attribute for 'role-mapping' definitions.

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-management/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jmx/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/logging/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/network/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/patching/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/platform-mbean/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/process-controller/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/protocol/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/remoting/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/standalone/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/threads/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/remoting-jmx/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/remoting/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/embedded/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/request-controller/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-web/undertow-server/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/manager/main/module.xml
:warning: The excludes in the elytron module are currently commented out, this is to allow time for Wildfly to be updated to a core release containing these changes so module references in wildfly can be updated and then the filtering can be applied.
This PR resolves: -
https://issues.jboss.org/browse/WFCORE-2240
The following issue should be left open so the second stage of change can be applied: -
https://issues.jboss.org/browse/WFCORE-1891
> [WFCORE-1891] / [WFCORE-2240] Elytron module private API flags.

- cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIScriptSupportTestCase.java
CLI class command context needs to be terminated otherwise, it stays referenced from shutdown hook.
> Fix for WFCORE-2241. Memory leak in CLI class

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/StartSuspendedTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-2194
This PR depends on #2049 to be merged first.
> [WFCORE-2194] StartSuspendedTestCase fails with security manager in WF core

- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- server/src/main/java/org/jboss/as/server/ServerEnvironment.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
https://issues.jboss.org/browse/WFCORE-2223
The only use of this system property is to drive the value of a deprecated attribute in the core-service=[server|host]-environment resource. There is no good reason to validate it and doing so breaks some embedded use cases.
> [WFCORE-2223] Drop pointless validation of jboss.modules.dir

- cli/src/main/java/org/jboss/as/cli/AwaiterModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/ConnectionInfo.java
- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
- cli/src/main/java/org/jboss/as/cli/impl/ConnectionInfoBean.java
- cli/src/test/java/org/jboss/as/cli/completion/mock/ConnectionInfoBeanMock.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
Support for RedirectException when redirect is caused by an http to https upgrade. Other cases are ignored.
> Fix for WFCORE-2216. Handle redirect during reload/shutdown

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ClientCompatibilityUnitTestBase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/api/ClientCompatibilityUnitTestCase.java
Make most of the functionality available in a shared base class so that
full an also use this test without duplicating code.
https://issues.jboss.org/browse/WFCORE-2196
> [WFCORE-2196] Copy ClientCompatibilityTestCase into core

- controller/src/main/java/org/jboss/as/controller/access/Caller.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/access/RoleMappingTestCase.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/WhoAmIOperation.java
https://issues.jboss.org/browse/WFCORE-2230
> [WFCORE-2230] Associate the SecurityRealm name with the Principal of the SecurityIdentity for legacy realm integration and use for role mapping.

- testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
Issue: https://issues.jboss.org/browse/WFCORE-2193
> [WFCORE-2193] JmxControlledStateNotificationsTestCase fails with security manager in WF core

- core-feature-pack/src/main/resources/content/bin/jboss-cli.sh
The CLI exit code was lost, returning it.
> Fix for WFCORE-2268. Returns actual CLI exit code.

- controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalInstallationReportHandler.java
- controller/src/test/java/org/jboss/as/controller/PropertiesAttributeDefinitionUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/StringListAttributeDefinitionUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/notification/GlobalNotificationsTestCase.java
- controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/controller/CancelNonProgressingOperationHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/controller/FindNonProgressingOperationHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/UserSearchResourceDefintion.java
- jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/CommonAttributes.java
https://issues.jboss.org/browse/WFCORE-2253
No transformers required. Attributes are either not related to domain wide resources or for the two that are, the fix is to remove meaningless default values
> [WFCORE-2253] Fix attributes that have a default value but also say the user must configure them

- pom.xml
This improves the handling of an empty configuration file. VDX will now
print:
14:17:33,783 INFO  [org.jboss.as.controller] (Controller Boot Thread) OPVDX004: Failed to pretty print validation error: standalone.xml has no content
instead of:
14:17:33,783 INFO  [org.jboss.as.controller] (Controller Boot Thread) OPVDX001: Failed to pretty print validation error: Index: 0, Size: 0
> Update to VDX 1.1.5

- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
- cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProviderTestCase.java
write-attribute value completion takes into account names containing a path to an attribute.
Unit test added.
> Fix for WFCORE-2264. Handle attribute path in write-attribute

- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemTransformers.java
- io/subsystem/src/main/java/org/wildfly/extension/io/OptionAttributeDefinition.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerService.java
- io/subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
- io/subsystem/src/main/resources/org/wildfly/extension/io/LocalDescriptions.properties
- io/subsystem/src/main/resources/schema/wildfly-io_1_1.xsd
- io/tests/src/test/java/org/wildfly/extension/io/IOSubsystemTestCase.java
- io/tests/src/test/java/org/wildfly/extension/io/IOSubsystemTransformerTestCase.java
- io/tests/src/test/resources/org/wildfly/extension/io/io-1.1-reject.xml
- io/tests/src/test/resources/org/wildfly/extension/io/io-1.1-transformer.xml
- io/tests/src/test/resources/org/wildfly/extension/io/io-1.1.xml
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
- WFCORE-2187 Description of IO worker task-max-threads attribute is inaccurate
- WFCORE-1622 Worker section in IO subsystem does not allow expressions for io-threads and task-max-threads attributes
- WFCORE-2159 worker=default:read-resource(include-runtime) wrong values in domain mode
- WFCORE-2188 IO subsystem requires reload when increasing size of io-threads or task-max-threads
- WFCORE-2195 XSD of IO subsystem should contain description of all resources and attributes
- fix how undefined metrics
-  WFCORE-2269 Add transformers for IO subsystem
> WFCORE-2188 WFCORE-2159 WFCORE-2187 WFCORE-1622 WFCORE-2195 IO subsystem fixes

- controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_5.java
Also, aliases this value to the /host= read, which was always unset.
> WFCORE-2139 domain-organization attribute causes error when starting domain

- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/PreparedResponseTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/ServerReload.java
Issue: https://issues.jboss.org/browse/WFCORE-1789
* Adding an expected exception after server reload to reloadServer test.
> [WFCORE-1789] PreparedResponseTestCase from wf-core-eap fails intermittently

- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
Resolves https://issues.jboss.org/browse/WFCORE-2280
> [WFCORE-2280] Ensure format of HTTP authentication mechanism names matches names used by WildFly Elytron.

- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
Fixed error message in case of Host Controller.
> Fix for WFCORE-2285. Wrong error message for reload with hc

- cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/ModelControllerClientFactory.java
- protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionConfiguration.java
- protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
- protocol/src/main/java/org/jboss/as/protocol/logging/ProtocolLogger.java
The SSLContext priority order becomes: -
1. The SSLContext from jboss-cli.xml
2. An SSLContext from wildfly-config.xml
3. The default SSLContext that can prompt for trust decisions.
The following issue can be resolved with this PR: -
https://issues.jboss.org/browse/WFCORE-2025
> [WFCORE-2025] Correct the priority when selecting the SSLContext to use with the CLI.

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessWrapper.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/suspend/web/SuspendResumeTestCase.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Improve timeouts in WF-CORE TS
* SuspendResumeTestCase.java should use TimeoutUtil for timeout
* Parametrize timeouts in TestRunner 
* CliProcessWrapper.java should use TimeoutUtil for timeout
This stabilizes TS on slower machines.
> [WFCORE-2294] Improve timeouts in WF-CORE TS

- controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
https://issues.jboss.org/browse/WFCORE-1529
1) Bump managment-handler-thread pool thread timeout from 1 to 10 mins to retain threads during active CLI sessions (see https://issues.jboss.org/browse/WFCORE-2282 for proposed future work related to this.)
2) ServerService pool on a standalone server keeps 1 core thread
3) On a domain server, it keeps 3, as comms with the HC involve more async tasks
4) ServerService core pool size can be set via system property
5) HostControllerService pool keeps 1 core thread
With these settings light CLI activity doesn't produce pool churn. The management-handler-thread pool will still churn if activity is infrequent, with gaps longer than 10 mins.
Repeated complex tasks like deploy ops will still produce churn in ServerService thread pool.
In both cases …
> [WFCORE-1529] Tweak management thread pools to decrease thread churn

- domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java
Resolves https://issues.jboss.org/browse/WFCORE-2258
> [WFCORE-2258] If the identity is not found within LDAP return the EMPTY identity instead of causing an internal server error.

- pom.xml
https://issues.jboss.org/browse/WFCORE-2305
This upgrade has just two fixes. The most important being one that corrects the formatting of the stack traces with suppressed exceptions, https://issues.jboss.org/browse/LOGMGR-146.
> [WFCORE-2305] Upgrade JBoss Log Manager from 2.0.4.Final to 2.0.5.Final

- cli/src/main/resources/help/help.txt
Fixed timeout option description. This timeout is unrelated to the time to wait for a command to return. That is a connection timeout.
> Fix for WFCORE-2306. Fixed timeout description

- pom.xml
This seems to have been accidentally introduced by https://github.com/wildfly/wildfly-core/commit/37b8668cd98cdea280858fa24c2abbe9d0506ab5#diff-600376dffeb79835ede4a0b285078036L117 when releasing core
> Downgrade remoting jmx snapshot

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
- host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainDeploymentOverlayRedeployLinksHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainDeploymentOverlayDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
- host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
- server/src/main/java/org/jboss/as/server/deploymentoverlay/AffectedDeploymentOverlay.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayContentDefinition.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayDefinition.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayDeploymentDefinition.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayDeploymentRemoveHandler.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayIndex.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayModel.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayRedeployLinksHandler.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestSupport.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentOverlayTestCase.java
Adding support for a new redeploy-affected method on deployment-overlays.
Adding a flag to redeploy affected when removing an overlay link.
Jira: https://issues.jboss.org/browse/WFCORE-2229
This is blocking https://issues.jboss.org/browse/WFCORE-1752
> [WFCORE-2229]: Create serverside operations to redeploy deployments affected by an overlay.

- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/events/JmxControlledStateNotificationsTestCase.java
Over eager deletion of files causes the test to fail.
> Over eager deletion of files causes the test to fail.

- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
- host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveSynchronizationTestCase.java
- testsuite/domain/src/test/resources/domain-configs/domain-synchronization.xml
- testsuite/domain/src/test/resources/host-configs/host-synchronization-hc1.xml
- testsuite/domain/src/test/resources/host-configs/host-synchronization-hc2.xml
- testsuite/domain/src/test/resources/host-configs/host-synchronization-master.xml
- testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestSupport.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/error/ErrorExtension.java
The synchronization model operation after an operation  between the HC and the DC shouldn't use the current operation's response.
Jira: https://issues.jboss.org/browse/WFCORE-2203
> [WFCORE-2203]: Outcome from /host=x/server-config=y:remove() operation in managed domain with multiple hosts lists out all the steps in result

- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClient.java
- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/LocalModelControllerClient.java
- controller/src/main/java/org/jboss/as/controller/ModelController.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactory.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DefaultDeploymentOperations.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerAdd.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
- deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/ShutdownFileSystemDeploymentServiceUnitTestCase.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- server/src/main/java/org/jboss/as/server/ApplicationServerService.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/deployment/ContentCleanerService.java
- server/src/main/java/org/jboss/as/server/deployment/ContentRepositoryCleaner.java
- server/src/main/java/org/jboss/as/server/deployment/client/ModelControllerServerDeploymentManager.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
https://issues.jboss.org/browse/WFCORE-1507
https://issues.jboss.org/browse/WFCORE-2327
[WFCORE-1507] Expose in-vm ModelControllerClient creation via a capability
Also addresses [WFCORE-2327] by creating a standardized way of establishing a client that acts as SuperUser.
The real driver here was WFCORE-2327 but it seemed obvious the right way to fix that was by doing what was needed for WFCORE-1507.
I also added a commit that cleans up some unrelated stuff in one of the test classes touched by the main WFCORE-2327 work
> [WFCORE-1507][WFCORE-2327] Clean up in VM ModelControllerClient handling

- cli/src/main/java/org/jboss/as/cli/handlers/DeploymentHandler.java
https://issues.jboss.org/browse/WFCORE-2330
DeploymentHandler.listDeployments() should not always throw CommandFormatException.
> [WFCORE-2330] JBoss-CLI "deploy -l" always returns exit code 1

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
cliProcess.destroy() does stuck on HP-UX if cliProcess is waiting for input from user (accept certificate dialogue)
https://issues.jboss.org/browse/WFCORE-2332 - ReloadRedirectTestCase stuck on HP-UX
> [WFCORE-2332] ReloadRedirectTestCase stuck on HP-UX

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FileArgumentTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FileWithPropertiesTestCase.java
The test that is failing in the bug report is FileArgumentTestCase.java but FileWithPropertiesTestCase.java could be affected by the same problem. Both tests have been refactored similarly.
I suspect that using commonly used CliProcessWrapper to interact with the CLI would make these intermitent failures to vanish. This would have to be validated over time in QA context.
This fix is an attempt.
> Fix for WFCORE-2347. Intermittent failure of some CLI tests.

- core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
- core-feature-pack/src/main/resources/content/bin/jboss-cli.sh
In .bat script, force load of commands in memory.
In .sh script, use exec instead of eval making the script to be replaced by java process.
> Fix for WFCORE-2338. Allow to patch CLI scripts from CLI.

- host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveSynchronizationTestCase.java
If we already have a failure-description then te synchronization failure isn't meaningful.
Jira: https://issues.jboss.org/browse/WFCORE-2360
JBEAP: https://issues.jboss.org/browse/JBEAP-9296
> [WFCORE-2360]:  Outcome from /host=x/server-config=y:remove() operation in managed domain with multiple hosts lists out all the steps in result.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java
Reverts wildfly/wildfly-core#2218
The test is failing intermittently so it seems reenabling it was premature.
> Revert "Reenable last remaining test disabled with WFCORE-1958 comment"

- pom.xml
The root cause of this problem has been fixed in aesh 0.66.15. This PR is an upgrade of aesh.
> Fix for WFCORE-1684. Empty lines in completion

- host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainDeploymentOverlayRedeployLinksHandler.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/AffectedDeploymentOverlay.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayRedeployLinksHandler.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentOverlayTestCase.java
It was first thought that if the deployment didn't exist we should fail. It appears we were wrong so now we just ignore those deployments.
Jira: https://issues.jboss.org/browse/WFCORE-2511
> [WFCORE-2511]: overlay, redeploy-links should ignore unknown deployments.

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/handlers/DeploymentOverlayHandler.java
- cli/src/main/resources/help/deployment-overlay.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeploymentOverlayTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/DeploymentOverlayTestCase.java
Fix overlay support to deal with runtime-name instead of name.
DeploymentOverlayHandler relies on server side operations to handle redeployment of linked deployments.
Help clean-up.
Added new unit tests.
> Fix for WFCORE-1752. deployment-overlays relies on runtime-name

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/operations/validation/SubnetValidator.java
- controller/src/main/java/org/jboss/as/controller/resource/InterfaceDefinition.java
- controller/src/test/java/org/jboss/as/controller/InterfaceAttributeDefinitionUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-1932
> WFCORE-1932 validate resource subset-match in interface definition

- testsuite/domain/pom.xml
- testsuite/domain/src/test/resources/host-configs/host-slave-failure.xml
I have included test/integration/domain/management/*TestCase.java in surefire to enable the missing tests for this issue.
Additionally, it was necessary to change host-slave-failure.xml XSD version from 3.0 to 5.0, due to an error in ServerStartFailureTestCase parsing this file. The file was using the element `<http-upgrade enabled="true" />` which was invalid for its XSD version.
Jira issue is:
https://issues.jboss.org/browse/WFCORE-2329
> WFCORE-2329: Include ServerAutoStartTestCase and ServerStartFailureTestCase tests in surefire

- core-feature-pack/src/main/resources/content/docs/contrib/scripts/systemd/launch.sh
In RedHat-based distributions sh is a symbolic link to `bash`, but in Debian-based distributions it points to `dash`.
I have been maintaining a Puppet Module [1] to manage Wildfly and this change was enough to make it work with debian-based distributions with systemd.
[1] https://github.com/biemond/biemond-wildfly/
> Change shebang to work with debian-based distributions

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
The root cause seems to have been WFCORE-2250 that has already been fixed.
> Unignore test failing due to WFCORE-1853 that should be fixed.

- pom.xml
https://issues.jboss.org/browse/WFCORE-2543
> [WFCORE-2543] Upgrade jboss-logging from 3.3.0.Final to 3.3.1.Final

- logging/src/main/java/org/jboss/as/logging/HandlerOperations.java
- pom.xml
[WFCORE-1585] Ensure the async-handler does not close children handlers.
https://issues.jboss.org/browse/WFCORE-2519
https://issues.jboss.org/browse/WFCORE-1585
The fix for WFCORE-1585 requires the jboss-logmanager upgrade.
> [WFCORE-2519] Upgrade jboss-logmanager from 2.0.5.Final to 2.0.6.Final.

- core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
Delayed evaluation of variables, removed if/else block in .bat script file.
> Fix for WFCORE-2561. .bat script to handle ) character in arguments

- testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
Fixes also WFCORE-2537: ModelControllerMBeanTestCase fails with security manager in WF core
Jira: https://issues.jboss.org/browse/WFCORE-2536
Jira: https://issues.jboss.org/browse/WFCORE-2537
> [WFCORE-2536]: JmxSensitiveTestCase fails with security manager in WF core.

- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BatchFileTestCase.java
batch --file and run-batch --file should better resist to comments, empty lines and lines with whitespace only.
Updated unit tests.
> Fix for WFCORE-2554. CLI Batch file with comments and empty lines

- server/src/main/java/org/jboss/as/server/BootstrapImpl.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
SuspendController resume was called on bott when it received a BOOT_COMPLETE_NOTIFICATION.
But notifications are non deterministic so we could get a ControlledServerState change (which relies on the same notification) while the resume hasn't been called yet.
This should fix all the intermittent failures with server state listeners.
> [deterministic-resume]: SuspendController resume is called properly on boot end without relying on notifications.

- core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
Delaying variable resolution means that variables accessed with %x% have their '!' characters removed.
This patch move delaying expansion when required (just prior to call JVM). All variables after this point are resolved at execution time (!x! instead of %x%).
With this fix we have:
- support for CLI script patching from CLI.
- support for ')' character in commands passed to CLI.
- support for '!' in file paths.
> Fix for WFCORE-2582. ! in file paths

- controller/src/main/java/org/jboss/as/controller/operations/CompositeOperationAwareTransmuter.java
- controller/src/main/java/org/jboss/as/controller/operations/DomainOperationTransmuter.java
- controller/src/main/java/org/jboss/as/controller/operations/OperationAttachments.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainSlaveHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentUploadUtil.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/AffectedDeploymentOverlay.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayContentAdd.java
Renaming DomainOperationTransformer as DomainOperationTransmuter.
Jira: https://issues.jboss.org/browse/WFCORE-2616
> [WFCORE-2616]: Rename DomainOperationTransformer to avoid confusion with the mixed domain transformers.

- server/src/main/java/org/jboss/as/server/deploymentoverlay/AffectedDeploymentOverlay.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestSupport.java
* The transformation should happen to avoid being redistributed to slaves.
* Fixing the root case which was missing for operation transformation.
Jira: https://issues.jboss.org/browse/WFCORE-2608
JBEAP: https://issues.jboss.org/browse/JBEAP-10035
Once this has been merged and released, please consider https://github.com/wildfly/wildfly/pull/9880
> [WFCORE-2608]: /deployment-overlay=test:redeploy-links doesn't work in mixed domain.

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Fixed the tests that were consuming time due to badly designed test. 
Other CLI tests are consuming time due to (mainly) CLI JVM processes launch.
> Fix for WFCORE-2627, CLI slow tests

- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/DeploymentPlanBuilder.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/AbstractServerDeploymentManager.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentActionImpl.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentPlanBuilderImpl.java
Adding an operation to be able to explode sub-content as only the root deployment could be exploded.
Jira: https://issues.jboss.org/browse/WFCORE-2628
JBEAP: https://issues.jboss.org/browse/JBEAP-10161
> [WFCORE-2628]:  DeploymentPlan doesn't have an operation to explode content.

- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentScannerTestCase.java
Test failed in an unexplainable manner so try to get more data by avoiding hiding problems.
> Don't suppress cleanup problems in DeploymentScannerTestCase

- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Handle the special case of un-named option value completer completing option name.
> Fix for WFCORE-2637. Invalid completion for cd,ls,read-op/attr

- pom.xml
- subsystem-test/framework/pom.xml
- subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SchemaValidator.java
This avoids the need for EAP productization to upgrade core any time we want to update jboss-metadata in full.
> [WFCORE-2595] Use core expression resolution in subsystem testsuite SchemaValidator; remove jboss-metadata-common dependency

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
WFCORE issue: https://issues.jboss.org/browse/WFCORE-2465
JBEAP issue: https://issues.jboss.org/browse/JBEAP-7444
> WFCORE-2465 key-manager for server-ssl-context should be required.

- pom.xml
This fixes the following error, that occurs if you have default methods in resteasy interfaces:
java.lang.VerifyError: Expecting a stackmap frame at branch target 13
> update classfilewriter to 1.2.1.Final

- server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- server/src/main/java/org/jboss/as/server/deployment/FunctionalVoidService.java
https://issues.jboss.org/browse/WFLY-8540
Currently, deployment unit phase services do not support restarts.  Rather than decorating a specific phase service as a singleton service, we decorate a service that installs the initial phase.  Once a deployment is detected to be a singleton service, the requisite DeploymentUnitPhaseBuilder is attached to the deployment unit, and the deployment unit service is restarted.  We retain the reference to the DeploymentUnitPhaseBuilder and build the initial phase within a service decorated with that builder.  This service can be restarted without issue - and singleton deployments work as expected.
Integration CI runs are here:
https://ci.wildfly.org/viewLog.html?buildId=54928
https://ci.wildfly.org/viewLog.html?buildId=55066
> WFLY-8540 Former singleton provider node leaving cluster after re-election causes another re-election

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
- controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
Also, tighten up in general the logic around publishing / rolling back the capability registry
https://issues.jboss.org/browse/WFCORE-2656
> [WFCORE-2656] Operations that didn't modify the capability registry or the resource registration tree should not roll back the capability registry

- core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
This issue is revealed by usage of cmd /C. error level vraiable was not properly evaluated.
> Fix for WFCORE-2667. Invalid CLI exit code on Windows

- domain-management/src/main/java/org/jboss/as/domain/management/security/KeystoreAttributes.java
Reverts wildfly/wildfly-core#2360
Need to revert because I messed up and did the 3.0.0.Beta17 release without pulling this one down first. So I'll reapply once I get the release commits into master.
> Revert "WFCORE-2720 Adding keystore with generate-self-signed-certificate-hos…"

- cli/src/main/java/org/jboss/as/cli/handlers/trycatch/TryCatchFinallyControlFlow.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/TryCatchFinallyTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-2717
> [WFCORE-2717] try-catch block doesn't work if catch block doesn't contains anything

- server/src/main/java/org/jboss/as/server/deployment/SubDeploymentProcessor.java
- server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
Jiras
https://issues.jboss.org/browse/WFCORE-2738
https://issues.jboss.org/browse/WFCORE-2750
blocks singleton deployments
https://issues.jboss.org/browse/JBEAP-10593
> WFCORE-2750 ModuleSpecProcessor + WFCORE-2738 SubDeploymentProcessor undeploy() leaks

- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
The issue only describes an error on configurable-sasl-server-factory description, but configurable-http-server-mechanism-factory had the same problem. Single commit to fixing both.
Jira Issues:
https://issues.jboss.org/browse/WFCORE-2443
https://issues.jboss.org/browse/JBEAP-6798
> WFCORE-2443: Fix wrong description in configurable-sasl-server-factory and configurable-http-server-mechanism-factory

- domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationCallbackHandler.java
Due to the fact there's a ton of classes named PasswordCredential,
it appears that this assignability check simply checked the wrong
one, resulting in PlugIn credentials being never considered valid
during the getCredentials() code path, all resulting in an early
return.
> Fix assignability check in legacy security-realm plugin-in handler.

- controller-client/pom.xml
- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClient.java
- controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClientConfiguration.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/ContextualModelControllerClient.java
- controller-client/src/main/java/org/jboss/as/controller/client/impl/ClientConfigurationImpl.java
- controller-client/src/main/java/org/jboss/as/controller/client/logging/ControllerClientLogger.java
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/controller-client/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/ElytronModelControllerClientTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/PreparedResponseTestCase.java
- testsuite/manualmode/src/test/resources/test-wildfly-config.xml
- testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
The first commit adds a new `ContextualModelControllerClient` which allows a context to be used when executing operations. It also adds a dependency to `org.wildfly.common:wildfly-common` and `org.wildfly.elytron:wildfly-elytron`. Both of these were already transitive dependencies from the `org.wildfly.protocol:wildfly-protocol` dependency. It also adds an option to the client builder to allow a `wildfly-config.xml` to be defined for authentication.
The second commit enables the usage of authentication options for the `ModelControllerClient` so that an Elytron authentication configuration can be used to authentication the management client.
The next two could likely be squashed. I just left them separate for now.
> [WFCORE-2747 & WFCORE-2769]

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
- server/src/main/java/org/jboss/as/server/BootstrapListener.java
- server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
When specifying that Wildfly should bind the management console to an ephemeral port (by specifying the port number as 0), Wildfly logs that the management console is not enabled. In fact, this is not correct as can be verified with lsof (or any other tool that enables seeing the sockets that Wildfly has bound). The networking layer determined an actual port number when binding the socket. Instead, Wildfly should log the actual port that it is bound to. This commit causes this to be the case.
Relates https://issues.jboss.org/browse/WFCORE-2771
> [WFCORE-2771] Console should log bound ports

- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java
In a managed domain a custom vault implementation doesn't work because the module name is not sent to the managed servers by the HC. This issue resolve it.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2741
https://issues.jboss.org/browse/JBEAP-10646
> WFCORE-2741: Add missing vault module attribute to the model boot updates sent by a HC

- cli/src/main/java/org/jboss/as/cli/handlers/LsHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/PrefixHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CdTestCase.java
Filter out options present in arguments. Added unit test.
> Fix for WFCORE-2798. CLI, cd command --no-validation handling

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
Added a custom validator for cipher-suite-filters attribute in ssl-context definitions.
Although the EAP issue recommends implementing a cache to avoid the same value validation at Stage.RUNTIME, I couldn't find a simple way to do it without hackering over WriteAttributeHandler. 
Jira issues:
https://issues.jboss.org/browse/WFCORE-2795
https://issues.jboss.org/browse/JBEAP-7422
> WFCORE-2795: Added a custom validator for Cipher Suites filter in Elytron

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml
use-cipher-suites-order, maximum-session-cache-size, session-timeout attributes are relevant only for server side, so removing from client-ssl-context
https://issues.jboss.org/browse/WFCORE-2807
(no PR deps)
> [WFCORE-2807] removed server-side attributes from client-ssl-context

- server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
- server/src/main/java/org/jboss/as/server/deployment/SimpleAttachable.java
https://issues.jboss.org/browse/WFCORE-2791
> WFCORE-2791 Auto-remove lingering deployment unit attachments following singleton deployment primary->backup transition

- controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
- controller/src/main/java/org/jboss/as/controller/ContainerStateVerificationHandler.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/InterdependentDeploymentTestCase.java
https://issues.jboss.org/browse/WFCORE-1762 -- fail ops that break services even if Service
VerificationHelper and ServiceRemovalVerificationHandler don't detect the problem
https://issues.jboss.org/browse/WFCORE-2351 --correct the timing and content of messages about MSC status. Reporting is at op completion and this fix ensures that it reports the state as of op completion, not what the state was midway through. This plus WFCORE-1762 should result in such messages being rare, as only rollback-on-runtime=failure=true, a rollback problem or a later op correcting one of the above will result in these messages. Most other cases are corrected because of rollback.
Also fixes minor issue https://issues.jboss.org/browse/WFCORE-2558 by specifically reporting that rollback didn't occur in cases …
> [WFCORE-1762][WFCORE-2351] Improve handling of ops that result in broken services

- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/operations/common/ProcessReloadHandler.java
- core-management/core-management-client/src/main/java/org/wildfly/extension/core/management/client/RunningStateChangeEvent.java
- core-management/core-management-client/src/main/java/org/wildfly/extension/core/management/client/RuntimeConfigurationStateChangeEvent.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/logging/CoreManagementLogger.java
- host-controller/src/main/java/org/jboss/as/host/controller/operations/NativeManagementServices.java
- server/src/main/java/org/jboss/as/server/operations/NativeManagementServices.java
- server/src/main/java/org/jboss/as/server/operations/NativeRemotingManagementAddHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/ProcessStateListenerTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/events/ProcessStateListenerTestCase.java
- testsuite/shared/src/main/java/org/wildfly/test/events/provider/ListenerFailureException.java
- testsuite/shared/src/main/java/org/wildfly/test/events/provider/TestListener.java
Executing stopping of the server out of the management-thread for a reload.
Preventing the ProcessStateListenerService from stopping while it is notifying its listener.
Cleaning the code :
* making the test code more usable
* using capability name for dependencies
Jira: https://issues.jboss.org/browse/WFCORE-2828
JBEAP: https://issues.jboss.org/browse/JBEAP-10998
> [WFCORE-2828]: org.wildfly.core.test.standalone.mgmt.events.ProcessStateListenerTestCase from wf-core fails intermittently

- elytron/pom.xml
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
- pom.xml
- testsuite/domain/pom.xml
- testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/vault/module/CustomVaultInModuleTestCase-module.xml
- fix elytron integration module to have same surefire settings as others
- fix elytron test to properly bootstrap to management only
- update jboss-parent to 23
- update jboss-logging-tools to latest version that works with all "versions" of @Generated annotation
- update maven compiler config after logging-tools updated as we don't need to fork anymore
- update jmockit test dependency (only used by elytron) to one that works also with jdk9
> WFCORE-1374 JDK9u166+ updates

- cli/src/main/java/org/jboss/as/cli/Util.java
- cli/src/main/java/org/jboss/as/cli/gui/metacommand/ScriptAction.java
- cli/src/main/java/org/jboss/as/cli/handlers/ArchiveHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/UndeployHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Revert UTF-8 constraints added when reading files from CLI. Redirected output is also not constrained by UTF-8 encoding. Encoding exception message is now clearer.
> Fix for WFCORE-2782. CLI, advertise character encoding issues

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
Although the issue is talking about concurrency problems adding aliases, those problems have been fixed with the work done in https://issues.jboss.org/browse/WFCORE-2777. Together with that issue, credential store service is being correctly retrieved using a lock at the operation level. 
The changes in this commit allow the read_aliases operation to work without acquiring the lock retrieving the credential store service because it is a read-only operation.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2768
https://issues.jboss.org/browse/JBEAP-10749
> WFCORE-2768: Read aliases operation should use read only credential store service

- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/javax/json/api/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/glassfish/javax/json/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
- pom.xml
Thanks to @jamezp for the assistance with the maven version-fu.
The elytron module had an optional dependency on javax.json, but was failing as audit logging actually required this module.
FYI @bstansberry @darranl
> WFCORE-2844 Move javax.json module to WildFly Core

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessWrapper.java
process.destroy() doesn't kill the CLI process completely on HP-UX and Solaris boxes
Jira:
https://issues.jboss.org/browse/WFCORE-2855 - CLIProcessWrapper - destroy the CLI process forcibly
> [WFCORE-2855] CLIProcessWrapper - destroy the CLI process forcibly

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HTTPSManagementInterfaceTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
Renabling tests as they are now executing properly
Jira: https://issues.jboss.org/browse/WFCORE-2068
> [WFCORE-2068]:  HTTPSConnectionWithCLITestCase and HTTPSManagementInterfaceTestCase Failing Due To Native Protocol Issue

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
This issue removes some minor changes already in the master branch because it was decided to move the behaviour to wildfly-elytron. 
Jira Issues
https://issues.jboss.org/browse/WFCORE-2478
https://issues.jboss.org/browse/JBEAP-9211
depends on: https://github.com/wildfly-security/wildfly-elytron/pull/837
> WFCORE-2478: Reverted allow creation of empty credential stores. The fix is implemented in wildfly-elytron

- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
1. Use standard Process.waitFor() instead of custom polling mechanism
2. Use standard CLI option --error-on-interact instead of custom
answering "Accept Certificate?" prompt
3. Always log CLI output
> [WFCORE-2851] Stabilise CLIExecutor

- elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
Elytron Subsystem: https://issues.jboss.org/browse/WFCORE-2712
JBEAP: https://issues.jboss.org/browse/JBEAP-10481
> [WFCORE-2712] Elytron - predefined-filter must have flag required in configurable-sasl-server-factory

- core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
- core-feature-pack/src/main/resources/content/bin/jboss-cli.ps1
- core-feature-pack/src/main/resources/content/bin/jboss-cli.sh
Updated scripts with ibm JRE system property. This will also be documented in release notes.
> Fix for WFCORE-2832. CLI on IBM JRE connects with TLS v1.2

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/cacheddc/CachedDcDomainTestCase.java
reloadAdvertisedAfterDcModelChangeWithShutdown was the culprit this time. It looks like the same issue, waiting for the slave to actually unregister.
> More cached DC flaky tests & some additional cleanup.

- cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Handle special case of object being complete and lastStateChar being a separator.
> Fix for WFCORE-2878, CLI complete empty complex object

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
Added the possibility to set OTP configurations for an identity using the file system realm
Jira Issues:
https://issues.jboss.org/browse/WFCORE-2722
https://issues.jboss.org/browse/JBEAP-10532
> WFCORE-2722: Add OTP support for identity set-password operation using filesystem-realm

- elytron/src/main/resources/subsystem-templates/elytron.xml
This reverts commit c7fa07b6fe767137afa1a51545f15234c9ed8094.
This is causing failures in 'org.jboss.as.test.integration.web.security.tg.TransportGuaranteeTestCase' - we suspect that the test case is passing on CI as OpenJDK may be failing to load for some reason (Possibly 32Bit JVM with 64Bit OpenSSL) and so is falling back to JDK Providers.
> Revert "[WFCORE-1802] Ensure the providers are registered first so they have priority."

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/RemoveManagementRealmTestCase.java
It happens that trying to fix this issue highlight the fact that CLI/aesh close sequence is difficult to maintain/evolve. 
I managed to reduce the occurrence of the problem with an ultra complex fix that is not appropriate for this problem (that only occurs during tests). To summarise, attempt to fix this problem is not safe, it will reveal other issues unseen until now.
I ran the same reproducer with CLI based on aesh-readline and didn't experience any failure.
So I propose to ignore this test for now, log a JIRA issue to un-ignore it once we have switched to aesh-readline.
> Fix for WFCORE-2679. CLI, ignore failing test

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-2792
> [WFCORE-2792-fix]: Fix for WFCORE-2792 which reverted back the "disallowed-providers" attribute parsing

- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DeploymentOverlayTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayContentRemove.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayDeploymentRemoveHandler.java
- server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayModel.java
Attaching the removed contents and links to deployments so that those are added to the operation to be executed on old slaves.
Jira: https://issues.jboss.org/browse/WFCORE-2899
JBEAP: https://issues.jboss.org/browse/JBEAP-10720
Please note that the test is in FULL (https://github.com/wildfly/wildfly/pull/10139)
Experimental build https://ci.wildfly.org/viewType.html?buildTypeId=WF_WildFlyCoreIntegrationExperiments&branch_WF=%2FWFCORE-2899%3B%2Fehsavoie
> [WFCORE-2899]: not possible to remove deployment-overlay in mixed domain when slave host is EAP 6.3. or older

- controller/src/main/java/org/jboss/as/controller/audit/SyslogAuditLogHandler.java
- controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
- domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogProtocolResourceDefinition.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/auditlog/AbstractAuditLogHandlerTestCase.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/auditlog/AuditLogHandlerBootEnabledTestCase.java
Adding support for CredentialReferenceSupplier in SyslogAuditLogHandler.
Jira: https://issues.jboss.org/browse/WFCORE-2923
JBEAP: https://issues.jboss.org/browse/JBEAP-11363
> [WFCORE-2923]:  Credential reference integration with client-certificate-store does not work.

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialSecurityFactoryParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
- elytron/src/test/resources/org/wildfly/extension/elytron/credential-security-factories.xml
https://issues.jboss.org/browse/WFCORE-2891
https://issues.jboss.org/browse/JBEAP-10653
**Depends on** https://github.com/wildfly-security/wildfly-elytron/pull/849
> [WFCORE-2891] attribute "required" into elytron kerberos-security-factory

- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java
This is a clean up PR following Elytron API changes, ideally we need to get this removed soon so we can upgrade to an Elytron version without the compatibility stubs.
https://issues.jboss.org/browse/WFCORE-2934
> [WFCORE-2934] Remove 'purpose' from call to getAuthenticationConfiguration()

- cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java
CLI class connect method should set ignoreOnInteract to false.
In addition I added a connect method to allow to provide a CommandContextConfiguration. This class is in an impl package but has already been exposed as a public API in the CommandContextFactory. I wanted to move it to public API, but being already exposed we can't change its location.
> Fix for WFCORE-2926. Disable error-on-interract for CLI.connect.

- domain-management/src/main/java/org/jboss/as/domain/management/security/AbstractPlugInAuthResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/JaasAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/KerberosAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/KerberosServerIdentityResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/KeytabResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapAuthorizationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LdapResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LocalAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthorizationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesAuthorizationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesFileResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/PropertyResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SSLServerIdentityResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecretServerIdentityResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmChildAddHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmChildRemoveHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/TruststoreAuthenticationResourceDefinition.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/XmlAuthenticationResourceDefinition.java
Updating metadata and handlers to require for server reload as restarting the SecurityRealm is not sufficient.
Jira: https://issues.jboss.org/browse/WFCORE-1606
JBEAP: https://issues.jboss.org/browse/JBEAP-5073
Full 'fix':  https://github.com/wildfly/wildfly/pull/10097 
Experimental build https://ci.wildfly.org/viewType.html?buildTypeId=WF_WildFlyCoreIntegrationExperiments&branch_WF=%2Fpre-WFCORE-1606%3B%2Fehsavoie%3A%2FWFCORE-1606%3B%2Fehsavoie
> [WFCORE-1606]: Server reload is needed for modified security-realm even if {allow-resource-service-restart=true} is used

- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerAdd.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/JmxAuditLogFieldsOfLogTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/AbstractDeploymentUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerNotificationUnitTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
The runtime-failure-causes-rollback wasn't properly propagated to the boot scanner.
If runtime-failure-causes-rollback is set to 'false' then failed deployments added at boot shouldn't be undeployed.
Jira: https://issues.jboss.org/browse/WFCORE-2876
> [WFCORE-2876]: Runtime-failure-causes-rollback does not seem to have effect when configured in model

- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
Revert back incorrect change part in previous PR https://github.com/wildfly/wildfly-core/pull/2542
As David's explanation in https://issues.jboss.org/browse/WFCORE-2410 and https://github.com/wildfly-security/wildfly-elytron/pull/879
> The practice of using initial characters for directory levels like we are is commonly known as hashing.
> Don't remove directory hashing as David's expalination in WFCORE-2410.

- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
There is an inconsistency between the xsd file and model definition for key-store element in key-manager and trust-manager 
Jira issues:
https://issues.jboss.org/browse/WFCORE-2446
https://issues.jboss.org/browse/JBEAP-7401
> WFCORE-2446: Use required attribute for Elytron key-store element in xsd file

- controller-client/src/main/java/org/jboss/as/controller/client/OperationBuilder.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/impl/DeploymentPlanBuilderImpl.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/DeploymentPlanBuilder.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/AbstractServerDeploymentManager.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentActionImpl.java
- controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentPlanBuilderImpl.java
- controller-client/src/main/java/org/jboss/as/controller/client/impl/InputStreamEntry.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java
Modifying the API so that we may use a java.nio.file.Path instead of a InputStream thus removing the need to read the full input to get its length.
Jira: https://issues.jboss.org/browse/WFCORE-2946
JBEAP: https://issues.jboss.org/browse/JBEAP-11513
> [WFCORE-2946]:  Errors publishing a large deployment to a remote server.

- cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeployTestCase.java
Make executor to use a cachedThreadPool. Added unit tests.
> Fix for WFCORE-2956. CLI deploy archive stuck when command timeout set

- cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueCallbackHandler.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/ArgumentValueConverterTestCase.java
Handle "" in complex objects expressed with non DMR syntax. Added unit test.
> Fix for WFCORE-2936. Handle empty string in complex object

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveSynchronizationTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ValidateAddressOperationTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ValidateAddressOperationTestCase.java
The changes where the message bundle interface was used may not be needed if the same locale is used for tests and the server boot. However testing with `-Djvm.args.other=-Duser.language=de` only boots the server with the locale and the test itself will still run under the users default locale.
This is a test run with translated messages added https://ci.wildfly.org/viewLog.html?buildId=63595&.
> Fix tests that rely on English messages.

- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/Constants.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/config/realm/CredentialReference.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/config/realm/RealmKeystore.java
Controversy of this PR is reload is needed during each test method. This is because reload is needed to change security realm on management interface.
Reload optimalization can be performed, if it would be possible to define order of test methods. But as this is not possible I have to ensure correct security realm is configured before each test method.
Locally this test takes 1.5 sec
> WFCORE-2483 Extend HTTPSManagementInterfaceTestCase tests with usage of CR

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
Improve charset usage in CLI tests
* https://issues.jboss.org/browse/JBEAP-11291
* https://issues.jboss.org/browse/WFCORE-2901
> [WFCORE-2901] Improve charset usage in CLI tests

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
This PR finishes the work done in JBEAP-10168, setting the correct restart-required attribute flags for some pending Elytron resources.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2426
https://issues.jboss.org/browse/JBEAP-6922
> WFCORE-2426: Use correct restart-required attribute access flag in Elytron resources

- pom.xml
https://issues.jboss.org/browse/WFCORE-2975
> Fix for WFCORE-2975. CLI, NPE in Ctrl-S. Upgrade aesh to 0.66.19

- elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/java/org/wildfly/extension/elytron/validators/SizeValidator.java
- elytron/src/main/java/org/wildfly/extension/elytron/validators/SuffixValidator.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
- elytron/src/test/resources/org/wildfly/extension/elytron/audit-logging.xml
Now there are two different rotating file logs in Elytron:
- periodic-rotating-file-audit-log: Which rotates based on a suffix in DateTimeFormatter format. Similar behaviour than /core-service=management/access=audit/periodic-rotating-file-handler. The suffix is mandatory here.
- size-rotating-file-audit-log: which rotates in size and can use a suffix in DateTimeFormatter format appended to each file rotation. Similar behaviour than /subsystem=logging/size-rotating-file-handler. The suffix is optional here.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2756
https://issues.jboss.org/browse/JBEAP-10700
Depends on: https://github.com/wildfly-security/wildfly-elytron/pull/845
> WFCORE-2756: Added periodic-rotating and size-rotating audit logs for Elytron audit

- elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
Default values were already being correctly used in LdapKeyStore. The only advantage I can see setting default values on LdapKeyStoreDefinition is LdapKeyStoreService will end up with those defaults instead of nulls, and any class using the service will get the "real" defaults, so I created this PR instead of solving the issue directly. 
Jira issues:
https://issues.jboss.org/browse/WFCORE-2929
https://issues.jboss.org/browse/JBEAP-7487
> WFCORE-2929: Added missing default values in management model for Elytron ldap-key-store

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-2880
https://issues.jboss.org/browse/JBEAP-11189
> [WFCORE-2880] The remove-alias operation should fail when attempting to remove a non-existing alias from a credential store

- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
- controller/src/test/java/org/jboss/as/controller/AbstractCapabilityResolutionTestCase.java
- controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
- controller/src/test/java/org/jboss/as/controller/CapabilityResolutionErrorTestCase.java
if no possible registration point exists, looks for dynamic capabilities that might be a candidate and returns those registration points.
Jira: https://issues.jboss.org/browse/WFCORE-2359
> [WFCORE-2359]: Failure message when an op requires a non-existent capability doesn't list registration points for dynamic caps

- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/CapabilityResolutionContext.java
ResolutionContext need to be copied onto the parent repository when copy of CapabilityRegistry occurs.
Test will come as a PR for Wildfly full.
> Fix for WFCORE-2993. NPE in CapabilityRegitry when retrieving capability names

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
https://issues.jboss.org/browse/WFCORE-3004
read-alias, read-aliases and read-identity are read-only operations.
Operations:
/subsystem=elytron/key-store=test:read-operation-description(name=read-alias)
/subsystem=elytron/credential-store=test:read-operation-description(name=read-aliases)
/subsystem=elytron/security-domain=ApplicationDomain:read-operation-description(name=read-identity)
> [WFCORE-3004] read-alias, read-aliases and read-identity are read-only operations.

- core-feature-pack/src/main/resources/content/bin/elytron-tool.bat
- core-feature-pack/src/main/resources/content/bin/elytron-tool.ps1
- core-feature-pack/src/main/resources/content/bin/elytron-tool.sh
wildfly-core: https://issues.jboss.org/browse/WFCORE-2966
JBEAP: https://issues.jboss.org/browse/JBEAP-11591
> [WFCORE-2966] WildFly Elytron tool script has to pass the command name from the script to the tool.

- elytron/src/main/java/org/wildfly/extension/elytron/CachingRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
- elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
https://issues.jboss.org/browse/WFCORE-3007
Also https://issues.jboss.org/browse/WFCORE-3012
Corrects:
cache-manager:clear-cache
key-store:load
key-store:store
key-store:read-aliases
key-store:read-alias
key-store:remove-alias
ldap-key-store:read-aliases
ldap-key-store:read-alias
ldap-key-store:remove-alias
filtering-key-store:read-aliases
filtering-key-store:read-alias
filtering-key-store:remove-alias
properties-realm:load
key-manager:init
trust-manager:reload-certificate-revocation-list
> [WFCORE-3007] Add missing setRuntimeOnly() to runtime-only elytron operations

- elytron/src/main/java/org/wildfly/extension/elytron/AvailableMechanismsRuntimeResource.java
- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- elytron/src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderAttributeDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
https://issues.jboss.org/browse/WFCORE-3013
Attributes that require a runtime should not be available on a profile=* resource.
> [WFCORE-3013] Confirm the registration is not for a domain profile resource before registering storage=runtime attributes

- elytron/src/main/java/org/wildfly/extension/elytron/AvailableMechanismsRuntimeResource.java
- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- elytron/src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
- elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderAttributeDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
Based on https://github.com/wildfly/wildfly-core/pull/2582
(brien's commits will disapper after merging of ^^)
https://issues.jboss.org/browse/WFCORE-3017
https://issues.jboss.org/browse/JBEAP-11785
> [WFCORE-3017] removing runtime-only operations from profile resources

- elytron/src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
Jira: https://issues.jboss.org/browse/WFCORE-3035
EAP 7.1 Jira: https://issues.jboss.org/browse/JBEAP-11901
> [WFCORE-3035] x509-credential-mapper in ldap-realm tries to verify Subject DN even if it is not configured

- pom.xml
https://issues.jboss.org/browse/WFCORE-3050
This only contains two fixes. The fix for [LOGMGR-163](https://issues.jboss.org/browse/LOGMGR-163) may be needed as if weekly log rotation is used log messages will be lost.
> [WFCORE-3050] Upgrade jboss-logmanager from 2.0.6.Final to 2.0.7.Final.

- elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
https://issues.jboss.org/browse/WFCORE-3063
https://issues.jboss.org/browse/JBEAP-12068
> [WFCORE-3063] Fix the delegate HttpServerAuthenticationMechanismFactory that gets passed to PropertiesServerMechanismFactory

- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
Unignore (Remove assumption from) test which checks Exception type when wrong credentials are used in SASL mechanisms.
Related JIRAs (already fixed):
https://issues.jboss.org/browse/JBEAP-11643
https://issues.jboss.org/browse/REM3-290
https://issues.jboss.org/browse/ELY-1203
> [ELY-1203] unignore PLAIN SASL mechanism test

- domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderKeyManagerService.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderTrustManagerService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
Synchronization issue when using FIPS enabled NSS DB as PKCS11 keystore.
https://issues.jboss.org/browse/WFCORE-3070
https://issues.jboss.org/browse/JBEAP-11693
> [WFCORE-3070] Found multiple secret keys sharing same CKA_LABEL

- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
- controller/src/test/java/org/jboss/as/controller/SuggestCapabilitiesTestCase.java
Replace ':' character with _ when converting into Path. Modified unit test to make some values to contain ':' character.
> Fix for WFCORE-3072. Fix CapabilityRegistry.suggest-capabilities on Windows

- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/DefaultRealmDigestMgmtSaslTestCase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/ExternalMgmtSaslTestCase.java
- testsuite/elytron/src/test/java/org/wildfly/test/security/common/other/TrustedDomainsConfigurator.java
This commit adds regression tests for Elytron SASL mechanism improvements.
JIRAs
* upstream: https://issues.jboss.org/browse/WFCORE-3065
* downstream: https://issues.jboss.org/browse/JBEAP-12125
The original issues (already fixed):
* https://issues.jboss.org/browse/ELY-982
* https://issues.jboss.org/browse/ELY-1186
> [WFCORE-3065] Add regression tests for ELY-982 and ELY-1186

- controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
- controller/src/main/java/org/jboss/as/controller/audit/SyslogAuditLogHandler.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- domain-management/src/main/java/org/jboss/as/domain/management/audit/AuditLogLoggerResourceDefinition.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
Changing the AuditLogger in the ResultHandler of AuditLogLoggerAddHandler instead of as a RUNTIME step.
Clearing the queue when writting log entries after the ManagedAuditLogger change status to LOGGING.
Jira: https://issues.jboss.org/browse/WFCORE-3078
JBEAP: https://issues.jboss.org/browse/JBEAP-11387
> [WFCORE-3078]: Intermittent failure in AuditLogBootingSyslogTest shows that WFCORE-2923 doesn't cover every case

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
Enable the use of a pass phrase for OTP file system realm set-password operation instead of using hash directly on this operation.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2722
https://issues.jboss.org/browse/JBEAP-10532
It depends on https://github.com/wildfly-security/wildfly-elytron/pull/895
> WFCORE-2722: Remove hash attribute from OTP set-pasword for Elytron filesystem realm

- domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/ValidateUserState.java
https://issues.jboss.org/browse/WFCORE-3087
https://issues.jboss.org/browse/JBEAP-6638
> [WFCORE-3087] Ensure that attempting to add a username with accented characters results in an error

- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
Elytron ldap-realm.identity-mapping.filter-name default value gets its default depending on the value of "rdn-identifier" attribute. Since we cannot represent it using set-default, this issue adds the information in the attribute description.
Its default value is assigned in LdapSecurityRealmBuilder.IdentityMappingBuilder#build method.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2368
https://issues.jboss.org/browse/JBEAP-7336
> [WFCORE-2368] Add description of Elytron ldap-realm.identity-mapping.filter-name default value

- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/OauthbearerMgmtSaslTestCase.java
* upstream: https://issues.jboss.org/browse/WFCORE-3092
* downstream: https://issues.jboss.org/browse/JBEAP-12295
Copy/paste issue fix - wrong JWT token value was used in the test.
> [WFCORE-3092] fix JWT token without signature value in OauthbearerMgmtSaslTestCase

- controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
- controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/StringListAttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/operations/validation/IntRangeValidator.java
- controller/src/main/java/org/jboss/as/controller/operations/validation/ListValidator.java
- controller/src/main/java/org/jboss/as/controller/operations/validation/LongRangeValidator.java
- controller/src/main/java/org/jboss/as/controller/operations/validation/StringLengthValidator.java
- controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/WildcardReadResourceDescriptionUnitTestCase.java
- controller/src/test/java/org/jboss/as/controller/test/WildcardReadResourceUnitTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
- management-client-content/src/main/java/org/jboss/as/management/client/content/ManagedDMRContentResourceDefinition.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
- subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/validation/ValidateOperationsTestCase.java
- subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/validation/subsystem/ValidateSubsystemExtension.java
https://issues.jboss.org/browse/WFCORE-3010
Also includes the commit from #2637 for https://issues.jboss.org/browse/WFCORE-3091. It was the work on this PR (reworking ValidateOperationsTestCase) that revealed to me that we're not outputting the min/max-length metadata for lists. Without that commit the test won't pass.
> [WFCORE-3010] Deprecate the non-builder SimpleOperationDefinition constructors; eliminate their use

- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
Some ldap-key-store default values get their defaults depending on the value of other attributes. Since we cannot represent them using set-default, this issue adds the information in the attribute descriptions.
Jira issues:
https://issues.jboss.org/browse/WFCORE-2929
https://issues.jboss.org/browse/JBEAP-7487
> [WFCORE-2929] Add description of default values in some Elytron ldap-key-store attributes

- pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-3106
Contains only a fix for the license changes required plus a small fix to calculate the correct caller.
Diff https://github.com/jboss-logging/commons-logging-jboss-logmanager/compare/1.0.1.Final...1.0.2.Final
> [WFCORE-3106] Upgrade commons-logging-jboss-logmanager from 1.0.1.Final to 1.0.2.FInal

- domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/DomainManagedServerCallbackHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/LocalCallbackHandlerService.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
FYI @darranl @bstansberry 
This has all of the needed bits I think. Only one DomainManagedServerCallbackHandler is created and used as backing credentials for all domain server authentication.
> WFCORE-2968 - domain server auth for legacy auth-realms

- controller/src/main/java/org/jboss/as/controller/SubsystemRegistration.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/persistence/AbstractConfigurationPersister.java
- controller/src/main/java/org/jboss/as/controller/persistence/SubsystemXmlWriterRegistry.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/CoreManagementExtension.java
- deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerExtension.java
- discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
- discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- host-controller/src/main/java/org/jboss/as/host/controller/ConfigurationPersisterFactory.java
- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerConfigurationPersister.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOExtension.java
- io/subsystem/src/main/java/org/wildfly/extension/io/IOSubsystemParser_2_0.java
- jmx/src/main/java/org/jboss/as/jmx/JMXExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingSubsystemWriter.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemXMLPersister.java
- request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerExtension.java
- request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemParser_1_0.java
- security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerExtension.java
- threads/src/main/java/org/jboss/as/threads/ThreadsExtension.java
- threads/src/main/java/org/jboss/as/threads/ThreadsParser.java
- threads/src/main/java/org/jboss/as/threads/ThreadsParser2_0.java
add option to register xml writers on-demand, this reduces creation of xml writers during boot.
In common scenarios when user runs application server in production for longer period also allows that xml writers are never created or after creation (usage) they are able to be GC-ed.
With this change also registration of writer suppliers is now more concurrency friendly and does no longer block in synchronized block.
> WFCORE-3097 add support for on-demand creation of xml writers

- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepository.java
- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
- deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryService.java
- deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
- deployment-repository/src/test/java/org/jboss/as/repository/DeletionCollisionTest.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/RemoteFileRepositoryService.java
ContentRepository is readonly when its service is stopped.
The content repository is now cleanly managed by a service.
Jiira: https://issues.jboss.org/browse/WFCORE-1330
> [WFCORE-1330]: Deployment error after reboot [WFLYSRV0137]

- controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
- controller/src/test/java/org/jboss/as/controller/test/WildcardReadResourceDescriptionUnitTestCase.java
Constrain the check for WFCORE-948 by checking if the base path
corresponds to a /host=xxx/ in executeMultiTargetChildren to avoid
breaking the loop if the address contains a resource whose key is server
(e.g. /subsystem=undertow/server=*/http-listener=*)
JIRA: https://issues.jboss.org/browse/WFCORE-2022
> [WFCORE-2022] fix read-resource-description for multitarget address

- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
Jira issues:
https://issues.jboss.org/browse/WFCORE-3066
https://issues.jboss.org/browse/JBEAP-12137
> [WFCORE-3066] Elytron subsystem - wrong description of ldap-realm.otp-credential-mapper.hash-from attribute

- testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
Extend API for getting node's IP address and allows to specify node address and port for management connection.
WFCORE-3098: https://issues.jboss.org/browse/WFCORE-3098
> Extend Management Client API in TestSuite

- controller/src/main/java/org/jboss/as/controller/ReloadRequiredWriteAttributeHandler.java
This exception is thrown by the AbstractWriteAttributeHandler.revertUpdateToRuntime(...), but not the overriden implementation.
> Allow ReloadRequiredWriteAttributeHandler subclasses overriding revertUpdateToRuntime(...) to throw OperationFailedException

- domain-management/src/main/java/org/jboss/as/domain/management/security/DomainManagedServerCallbackHandler.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnection.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerAuthenticationTestCase.java
This uncouples the domain server auth service from the realm add handler, and insteads starts it from DomainModelControllerService. This will allow the service to start if no realms are present.
> WFCORE-2968 Domain server auth service cleanup

- core-feature-pack/src/main/resources/content/bin/domain.sh
- core-feature-pack/src/main/resources/content/bin/standalone.sh
Solaris 10 requires export and env assignment on separate lines.
Fixes https://issues.jboss.org/browse/WFCORE-3126
> [WFCORE-3126] export and env assignment must be on separate lines

- pom.xml
https://issues.jboss.org/browse/WFCORE-3138
The changes mainly include the license updates and internationalized messages.
https://github.com/projectodd/vdx/compare/1.1.5...1.1.6
> [WFCORE-3138] Upgrade VDX from 1.1.5 to 1.1.6

- domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderKeyManagerService.java
- domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderTrustManagerService.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
KeyStoreSevice is affected as well and load can happen in Elytron's CredentialStore so need to sync on different instance.
https://issues.jboss.org/browse/WFCORE-3070
https://issues.jboss.org/browse/JBEAP-11693
> [WFCORE-3070] syncing FIPS mode KeyStore loads on EmptyProvider as the same issue exists Elytron module

- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/ExternalMgmtSaslTestCase.java
https://issues.jboss.org/browse/WFCORE-3171
https://issues.jboss.org/browse/JBEAP-12616
> [WFCORE-3171] test fix: accepting Broken pipe as equivalent of SSLException

- pom.xml
https://issues.jboss.org/browse/WFCORE-3176
> [WFCORE-3176] Upgrade jboss-logging-tools to version 2.1.0.Final

- checkstyle-suppressions.xml
- pom.xml
- zanata.xml
This changes the zanata configuration to point to the new server.
This allows properties files downloaded from zanata to not be processed by the checkstyle plugin.
This allows entries that are no longer required to be deleted when the base properties files are uploaded.
> [I18n] Prepare for internationalization

- pom.xml
https://issues.jboss.org/browse/WFCORE-3191
https://issues.jboss.org/browse/WFCORE-3170
https://issues.jboss.org/browse/JBEAP-12750
https://issues.jboss.org/browse/JBEAP-12618
> [WFCORE-3191] / [WFCORE-3170] Upgrade WildFly Elytron to 1.1.0.CR6 and Elytron Web to 1.0.0.CR2

- elytron/src/main/resources/subsystem-templates/elytron.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogToTLSElytronSyslogSetup.java
Also adjust the AuditLogBootingSyslogTest to take into account the reduced size of the composite operation to boot the server.
https://issues.jboss.org/browse/WFCORE-3182
This is the main fix for https://issues.jboss.org/browse/JBEAP-12631 - however a minor optimisation is still going to be applied to Elytron to minimise the steps within the synchronized block.
> [WFCORE-3182] Remove audit logging from default security domain definitions.

- security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerSubsystemAdd.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/secman/PermissionsDeploymentTestCase.java
The commit here fixes the issue reported in https://issues.jboss.org/browse/WFLY-6657
The issue is a bit involved (which I explain below) but the gist of the issue is that the processing of `permissions.xml` and its associated security semantics, within a deployment, are completed skipped and ignored, because the deployment unit processor(s) responsible for setting up these security constraints never get triggered. That's because they get added by the `SecurityManagerSubsystemAdd` too late in the game after the `RUNTIME` step of `DeployerChainAddHandler` has already formalized deployment unit processors that are enrolled with it and has created a "final view" of those processors. 
The reason why this shows up only when the `org.jboss.server.bootstrap.maxThreads` system property is set, is …
> Fix for WFCORE-3199 - Make sure the security permissions.xml DUPs are registered before the deployment chain is frozen

- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
https://issues.jboss.org/browse/WFCORE-3184
removal of unused controllingThread after https://github.com/wildfly/wildfly-core/pull/2694
Trivial stuff, ready for 4.x label ;)
> [WFCORE-3184] removal of unused controllingThread

- elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
wildfly-elytron-integration: https://issues.jboss.org/browse/WFCORE-2565
JBEAP: https://issues.jboss.org/browse/JBEAP-9726
> [WFCORE-2565] Incorrect permission class-name should throw exception at runtime

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLIWrapper.java
https://issues.jboss.org/browse/WFCORE-3239
> [WFCORE-3239] CLIWrapper does not allow for use in multinode tests

- controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
https://issues.jboss.org/browse/WFCORE-3258
> WFCORE-3258 ServiceRemoveStepHandler fails to remove services if any associated capabilities use a dynamic name mapper

- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
@ctomc fix of your failure for JDK9
For IBM there is also second failure, but it is already reported and tracked JDK bug - see jira:
https://issues.jboss.org/browse/WFCORE-3209
> [WFCORE-3209] Adding doAs blocks into KerberosHttpMgmtSaslTestCase for JDK9

- elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
wildfly-elytron-integration: https://issues.jboss.org/browse/WFCORE-3064
JBEAP: https://issues.jboss.org/browse/JBEAP-12106
> [WFCORE-3064] Suffix in Elytron periodic-rotating-file-audit-log cannot include 's' or 'S' in text

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/logmanager/main/module.xml
- logging/pom.xml
- pom.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractLoggingTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/ReconnectSyslogServerTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/SyslogIsNotAvailableDuringServerBootTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/syslog/SyslogHandlerTestCase.java
https://issues.jboss.org/browse/WFCORE-3218
I don't think the custom byteman settings are required any longer. They passed for me locally without them.  This was done to fix some kind of issue with running on IPv6. Locally this seemed to work so it may not be required any longer.
> [WFCORE-3218] Upgrade jboss-logmanager from 2.0.7.Final to 2.1.0.Alpha4.

- controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
- controller/src/main/java/org/jboss/as/controller/PathAddress.java
- controller/src/main/java/org/jboss/as/controller/PathElement.java
- controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
- controller/src/test/java/org/jboss/as/controller/PathAddressTestCase.java
Replaced Filesystem based matching with PathAddress/PathElement based matching.
Added unit test for path matching. Added unit test to cover the case that was failing with Filesystem based matching (with a possible provider address's value containing a ":" character).
> Fix for WFCORE-3074, replaced Path matching

- domain-management/src/main/java/org/jboss/as/domain/management/security/FileKeyManagerService.java
Setting the permissions.
Jira: https://issues.jboss.org/browse/WFCORE-3287
JBEAP: https://issues.jboss.org/browse/JBEAP-13150
> [WFCORE-3287]: Generated keystore file permissions should be 600 instead of 664.

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/InterdependentDeploymentTestCase.java
Reverts wildfly/wildfly-core#2773
The test still intermittently fails despite this change, so it wasn't helping with that and we should restore the original version.
I'm tempted to @ Ignore the entire test but it covers an important scenario. Perhaps the issue isn't the "optional" bit but rather the chained dependencies. That's still an important scenario but less so than the test overall and maybe disabling that bit will avoid the intermittent issue. 
@ropalka FYI
> Revert "Work around the WFCORE-2235 problem to avoid intermittent failures fo…"

- elytron/pom.xml
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/resources/schema/wildfly-elytron_2_0.xsd
- elytron/src/main/resources/subsystem-templates/elytron-empty.xml
- elytron/src/main/resources/subsystem-templates/elytron.xml
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemBaseParsingTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/audit-logging.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/authentication-client.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/credential-security-factories.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/credential-stores.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/domain.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/http.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/identity-management.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/jacc-with-providers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/providers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/sasl-test.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/sasl.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/security-properties.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/security-realms.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/transformers-1.0.xml
This change just bumps the model and schema version, multiple engineers are now starting to work on new model changes for WildFly Core 4 and this will also enable migration to persistent resource definitions to commence.
> [WFCORE-3234] Add Elytron model and schema version 2.

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- patching/src/test/java/org/jboss/as/patching/cli/ContentConflictsUnitTestCase.java
Throw a new CommandlineException to wrap the ExecutionException. Cleanup the exception prior to print the error message.
Fixed unit test that strictly relied on content of the thrown exception.
> Fix for WFCORE-3225. CLI exception, keep calling stack

- cli/src/main/java/org/jboss/as/cli/handlers/AttachmentHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/EchoDMRHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchEditLineHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/ifelse/IfHandler.java
- cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
- cli/src/main/java/org/jboss/as/cli/operation/ParsedCommandLine.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultCallbackHandler.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
- cli/src/main/java/org/jboss/as/cli/parsing/ParserUtil.java
- cli/src/main/java/org/jboss/as/cli/parsing/StateParser.java
- cli/src/test/java/org/jboss/as/cli/parsing/test/VariablesTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Handling variable substitution:
- fixed operation completion in commands (echo-dmr, if, edit-batch-line, attachment)
- support for multiple variables in a path
Added new completion unit tests.
> Fix for WFCORE-3289, variable substitution completion issue

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
- controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
- controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLParser.java
- controller/src/main/java/org/jboss/as/controller/ServiceNameFactory.java
- controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
- controller/src/main/java/org/jboss/as/controller/persistence/AbstractConfigurationPersister.java
- controller/src/main/java/org/jboss/as/controller/registry/AttributeAccess.java
- controller/src/main/java/org/jboss/as/controller/registry/OperationEntry.java
- controller/src/main/java/org/jboss/as/controller/services/path/PathInfoHandler.java
- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/CoreManagementExtension.java
- discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
- logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java
- request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerExtension.java
- security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerExtension.java
This PR includes a couple different types of optimizations related to boot perf:
1) Small improvements to some object interning logic that I'd added to cut down on the WF memory footprint. (2nd and 3rd commits.)
2) A lot of management code (classloading and initialization of constants like AttributeDefinition FOO or XXXResourceDefinition.INSTANCE) is happening when xml parsers are invoked, which is a single-threaded part of boot meaning it all happens in series on one CPU core. All but one of the other commits here aim at pushing this work into the calls to Extension.initializeParsers, which happen concurrently for each extension.
There's also a trivial cleanup commit.
> Boot optimizations

- cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
The CommandContextBuilder allows to redefine the validate-operation-requests configuration.
Jira: https://issues.jboss.org/browse/WFCORE-3118
> [WFCORE-3118]: Allow to override the validation of operation request in CommandContext.

- elytron/pom.xml
remove licenses tag from pom.xml to inherit project dual license
issue: https://issues.jboss.org/browse/WFCORE-3331
> [WFCORE-3331] license of org.wildfly.core:wildfly-elytron-integration

- pom.xml
This contains a fix for [WFCORE-3311](https://issues.jboss.org/browse/WFCORE-3311) which logs messages to stdout on offline CLI regardless of the `--stdout=discard` setting.
JIRA: https://issues.jboss.org/browse/WFCORE-3313
> [WFCORE-3313] Upgrade jboss-logmanager from 2.1.0.Alpha4 to 2.1.0.Alpha5

- elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
Attribute is still marshalled even if its value is the default one.
Jira: https://issues.jboss.org/browse/WFCORE-3323
JBEAP: https://issues.jboss.org/browse/JBEAP-13303
> [WFCORE-3323]:  Initial Elytron configuration includes mapping-mode="first" in simple-permission-mapper

- elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
Attribute is still marshalled even if its value is the default one.
Jira: https://issues.jboss.org/browse/WFCORE-3323
JBEAP: https://issues.jboss.org/browse/JBEAP-13303
Upstream PR: https://github.com/wildfly/wildfly-core/pull/2860
> [WFCORE-3323-3.x]:  [WFCORE-3323]:  Initial Elytron configuration includes mapping-mode="first" in simple-permission-mapper

- pom.xml
https://github.com/wildfly/wildfly-core/pull/2876
:exclamation: The WildFly Elytron Tool component upgrade is only included here so it can include the next .Final tag of WildFly Elytron, as the upstream PR only updates to a Beta version of WildFly Elytron no tool update is within the upstream PR.
https://issues.jboss.org/browse/WFCORE-3343
https://issues.jboss.org/browse/WFCORE-3346
> [WFCORE-3343] / [WFCORE-3346] WildFly Elytron Component Upgrades

- cli/src/main/java/org/jboss/as/cli/handlers/AttachmentHandler.java
- cli/src/main/resources/help/attachment.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AttachmentTestCase.java
Creating the directories before saving the attachment to file.
Jira: https://issues.jboss.org/browse/WFCORE-3208
> [WFCORE-3208]: Saving an attachement should create the specified path  if it doesn't exist.

- pom.xml
No WildFly Elytron Tool component upgrade in this PR as we are only updating to a Beta.
https://issues.jboss.org/browse/WFCORE-3356
> [WFCORE-3356] Upgrade WildFly Elytron to 1.2.0.Beta7

- elytron/pom.xml
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/PolicyParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/PolicyParserTemp.java
- elytron/src/test/java/org/wildfly/extension/elytron/ElytronSubsystem12TestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/custom-policies.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-1.2.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/jacc-with-providers.xml
Goes beyond #2886 to add a commit dropping the custom policy element parsing we used in WildFly Core 3.0.6 for the 1.1 and 1.0 xsds and instead use PersistentResourceXmlDescription.
This is meant to make it easier to merge the WFCORE-2882 work (see #2852 ) on top of the WFCORE-3041 work. To this end the policy parsing logic has been moved to a temporary new class 'PolicyParserTemp' and the legacy 'PolicyParser' class which is no longer used, has been restored to its state prior to any WFCORE-3041 changes. (This avoid difficult to untangle merge conflicts with the WFCORE-2882 work.) The PolicyParserTemp temp class shows the proper configuration of the PersistentResourceXmlDescriptions that are needed to parse the policy resource, both for 1.0/1.1 xsds and for 1.2/2.0 xsds. WFCORE-2882 …
> WFCORE-3041 helper for WFCORE-2882

- pom.xml
https://issues.jboss.org/browse/WFCORE-3368
As this is only an update to a Beta release there is no corresponding tool update.
> [WFCORE-3368] Upgrade WildFly Elytron to 1.2.0.Beta8

- threads/src/main/java/org/jboss/as/threads/ThreadFactoryAdd.java
- threads/src/main/java/org/jboss/as/threads/ThreadFactoryService.java
* do not use the values of group-name and thread-name-pattern if the
attibutes are not defined in the model.
JIRA: https://issues.jboss.org/browse/WFCORE-3377
> [WFLY-3377] thread-factory resource creation

- logging/src/main/java/org/jboss/as/logging/validators/SuffixValidator.java
- logging/src/test/java/org/jboss/as/logging/validators/SuffixValidatorTestCase.java
wildfly-core: https://issues.jboss.org/browse/WFCORE-3231
JBEAP: https://issues.jboss.org/browse/JBEAP-12952
> [WFCORE-3231] Logging subsystem: Fix SuffixValidator to allow 's' or 'S' symbols in text quoted using single quotes in suffix.

- domain-management/src/main/java/org/jboss/as/domain/management/audit/validators/SuffixValidator.java
- domain-management/src/test/java/org/jboss/as/domain/management/security/auditlog/AuditLogPeriodicRotatingFileHandlerTestCase.java
wildfly-core: https://issues.jboss.org/browse/WFCORE-3230
JBEAP: https://issues.jboss.org/browse/JBEAP-12951
> [WFCORE-3230] Domain management audit logging: Fix SuffixValidator to allow 's' or 'S' symbols in text quoted using single quotes in suffix.

- pom.xml
No WildFly Elytron Tool upgrade as this is only to a Beta.
https://issues.jboss.org/browse/WFCORE-3399
> [WFCORE-3399] Upgrade WildFly Elytron to 1.2.0.Beta9

- domain-management/src/main/java/org/jboss/as/domain/management/controller/FindNonProgressingOperationHandler.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/OperationCancellationTestCase.java
issue: https://issues.jboss.org/browse/WFCORE-3405
1. Set runtime-only and read-only for find-non-progressing-operation and add some tests with domain server address as recommended in WFCORE-3405
2. Acquire exclusive lock for standalone server in BlockerExtension, which I think is the reason why find-non-progressing-operation does not work for standalone in manual test with BlockerExtension. Please see my examples in https://issues.jboss.org/browse/WFCORE-3406
> Fix for WFCORE-3405 and WFCORE-3406 on find-non-progressing-operation

- cli/src/main/java/org/jboss/as/cli/handlers/loop/DoneHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/loop/ForControlFlow.java
- cli/src/main/java/org/jboss/as/cli/handlers/loop/ForHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/resources/help/done.txt
- cli/src/main/resources/help/for.txt
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIScriptSupportTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CommandTimeoutHandlerTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ForLoopTestCase.java
Introduce ability to iterate over DMR collections and execute commands for each item.
Added new unit tests.
> Fix for WFCORE-3236, iteration of collections for CLI

- cli/src/main/java/org/jboss/as/cli/CliConfig.java
- cli/src/main/java/org/jboss/as/cli/CommandContext.java
- cli/src/main/java/org/jboss/as/cli/handlers/EchoDMRHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java
- cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
- cli/src/main/java/org/jboss/as/cli/impl/Namespace.java
- cli/src/main/resources/help/help.txt
- cli/src/main/resources/schema/wildfly-cli_3_2.xsd
- cli/src/test/java/org/jboss/as/cli/completion/mock/MockCliConfig.java
- core-feature-pack/src/main/resources/content/bin/jboss-cli.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
- New option, XML element and unit test.
> Fix for WFCORE-3363, CLI to output JSON

- controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
https://issues.jboss.org/browse/WFCORE-3347
Fix wrong string comparison as pointed out in previous https://github.com/wildfly/wildfly-core/pull/2900#pullrequestreview-76091139 It should compare string content instead of object reference.
> Fix string comparison made in WFCORE-3347

- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java
https://issues.jboss.org/browse/WFCORE-3406
It explicitly gets the exclusive lock for standalone server by calling acquireControllerLock(). JavaDoc on Method states:
> The lock is automatically released when the execute method of the handler that invoked this method returns.
I have manually added new BlockerExtension to test with standalone server as "steps to reproduce" in issue WFCORE-3406. It returns back correct locked time and operation.
> [WFCORE-3406] explicitly get the exclusive lock for standalone server in BlockerExtension

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- pom.xml
Automatic paging of output longer than terminal height. Only applies in interactive mode when CLI runs in a terminal.
Evolves dependency to aesh-readline 1.1. Manual testing only.
> Fix for WFCORE-426, CLI, automatic long output pause

- controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
- controller/src/main/java/org/jboss/as/controller/registry/DelegatingResource.java
- controller/src/main/java/org/jboss/as/controller/registry/PlaceholderResource.java
- controller/src/main/java/org/jboss/as/controller/registry/Resource.java
- controller/src/main/java/org/jboss/as/controller/registry/ResourceProvider.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
- jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanServerPlugin.java
- jmx/src/main/java/org/jboss/as/jmx/model/RootResourceIterator.java
- jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
- logging/src/main/java/org/jboss/as/logging/LoggingResource.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/LeafPlatformMBeanResource.java
The biggest thing this does is eliminate RBAC checks as a factor in determining whether a resource appears in the count. Which means, in the case of non-addressable resources the total number of mbeans a user could "see", for example via MBeanServerConnection.queryNames, could be less than the number returned by a simultaneous call to getMBeanCount().
The other big thing this does is avoiding doing two complete counts for the jboss.as and jboss.as.expr JMX domains. There should be no difference in counts between those so if both are installed it just counts one and doubles the result.
I have a variant of this that retains the old getMBeanCount logic plus adds a simpler optimization of what's already there, and then adds this, and then times all 3, logging the times and the mbean counts. …
> [WFCORE-3415] Faster resource tree size calculation for getMBeanCount()

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java
- host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
- server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
- server/src/main/java/org/jboss/as/server/operations/ServerDomainProcessShutdownHandler.java
This issue adds Kill and Destroy operations at server-group level. It adds some refactored code in ManagedServer#ServerStopTask and removes an unused operation-id from it.
Jira issue is:
https://issues.jboss.org/browse/WFCORE-2066
> WFCORE-2066  Kill and destroy operations on the server-group

- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/DefaultRealmDigestMgmtSaslTestCase.java
- testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/DigestSha384MgmtSaslTestCase.java
This issue depends on https://github.com/wildfly-security/wildfly-elytron/pull/1021 and has to be merged with that one. 
Tests will fail if it is merged with the incorrect Elytron version.
Issue: https://issues.jboss.org/browse/WFCORE-3116
JBEAP issue: https://issues.jboss.org/browse/JBEAP-12316
> [WFCORE-3116] Add support for digest-sha-384 for Elytron set-password operation

- controller/src/main/java/org/jboss/as/controller/extension/ExtensionResourceDefinition.java
- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
Redefining the ADD operation to deprecated the module parameter that is not used anymore.
Jira: https://issues.jboss.org/browse/WFCORE-3430
> [WFCORE-3430]: The module parameter of the add extension operation should be deprecated.

- pom.xml
This increase of aesh-readline releases fixes solaris broken terminal, it also fixes HPUX interactive mode (completion and characters handling) reported in JBEAP-3724.
> Fix for WFCORE-3437, solaris and hpux CLI terminal issues

- pom.xml
includes https://issues.jboss.org/browse/JANDEX-41 fix for running on JDK9
> WFCORE-3445 Update jandex to 2.0.4.Final

- cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ReloadSASLFactoryTestCase.java
- testsuite/standalone/src/test/resources/mgmt-users-foo.properties
- testsuite/standalone/src/test/resources/mgmt-users-other.properties
Makes the reload handler to attempt a reconnect if authentication failed. This will give a change to provide new credentials.
> Fix for WFCORE-3442, reload with changed authentication configuration

- server/src/main/java/org/jboss/as/server/operations/ServerSuspendHandler.java
Issue: https://issues.jboss.org/browse/WFCORE-3476
> [WFCORE-3476] Avoid to wait for timeout suspending a server already suspended

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
Fixes of:
- errors occurred during reload not visible as operation result
- reload flag is shared across individual TrustManagers (first used TrustManager is reloaded instead of the chosen one)
https://issues.jboss.org/browse/WFCORE-3151
https://issues.jboss.org/browse/JBEAP-11225
> [WFCORE-3151] TrustManager - non-lazy CRL reload

- controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistryType.java
- controller/src/main/java/org/jboss/as/controller/transform/CompositeOperationTransformer.java
- io/subsystem/src/main/java/org/wildfly/extension/io/OptionList.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointConfigFactory.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointRemove.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointResource.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem10Parser.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem20Parser.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemRootResource.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemXMLPersister.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingTransformers.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/WorkerThreadPoolVsEndpointHandler.java
- remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestUtil.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformersTestCase.java
https://issues.jboss.org/browse/WFCORE-3327
Also includes required fix to 
https://issues.jboss.org/browse/WFCORE-3332
The /subsystem=remoting resource always installs an endpoint. It has a configuration=endpoint child resource that lets the user configure the endpoint, but even if not configured, the endpoint is installed, and with a lot of default values used. If the user doesn't add the configuration=endpoint child, the parent adds it anyway. There are a lot of problems with this:
1) The child resource does not provide any services but is only used to configure services provided by its parent. This is a fairly common pattern, but it's suboptimal.
2) The child resource is kind of a "default value" for its parent, providing config data even if not added by the user, in a similar way to …
> [WFCORE-3327] Convert remoting subsystem configuration=endpoint resource into just an alias exposing attributes on its parent

- pom.xml
Upgraded to aesh-readline 1.3 in which the issue is fixed.
> Fix for WFCORE-3480, ls output is unfriendly if any element in return contents is longer than terminal width

- cli/src/main/java/org/jboss/as/cli/handlers/ifelse/IfElseControlFlow.java
- cli/src/main/java/org/jboss/as/cli/handlers/trycatch/TryCatchFinallyControlFlow.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultCallbackHandler.java
- cli/src/main/java/org/jboss/as/cli/parsing/ParserUtil.java
- cli/src/main/java/org/jboss/as/cli/parsing/StateParser.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ForLoopTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/TryCatchFinallyTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ifelse/BasicIfElseTestCase.java
Disable variable resolution exception when done inside a block (if, try for). The variable could be not existing yet. Added unit test. 
Added check that if can't be called inside an if blocks and try can't be called inside try blocks.
> Fix for WFCORE-3484, variable resolution in blocks, better error message

- cli/src/main/java/org/jboss/as/cli/handlers/loop/ForControlFlow.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ForLoopTestCase.java
Catch asList exception and throw better message. Added unit test.
> Fix for WFCORE-3490, better message for non iterable operations

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
upstream jira: https://issues.jboss.org/browse/WFCORE-3520
Better naming in tests for WFCORE-3363 (give them better names instead of testXXX1, testXXX2); two indentation fixes
> [WFCORE-3520] Better naming in tests for WFCORE-3363

- controller/src/test/java/org/jboss/as/controller/support/ChannelServer.java
- controller/src/test/java/org/jboss/as/controller/test/TransactionalProtocolClientTestCase.java
- protocol/src/test/java/org/jboss/as/protocol/mgmt/support/ChannelServer.java
- protocol/src/test/java/org/jboss/as/protocol/mgmt/support/RemoteChannelPairSetup.java
Really ugly but timing on ci.wildfly.org seems to have changed recently such that these failures are pretty common again, plus they've always been common on brontes and there's a Critical JBEAP to make that go away. The failures are common enough that I can't really argue with the Critical designation.
Workaround for https://issues.jboss.org/browse/WFCORE-3302.  Doesn't really resolve it, although it's ok to resolve the issue since we have REM3-303 for the basic problem.
> Work around WFCORE-3302 / REM3-303 by sleeping

- cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
Make the created threads to be daemon. Manually tested with a standalone client application calling into CLI class:
CLI cli = CLI.newInstance();
cli.cmd("version");
==> process can exit.
This doesn't mean that terminate() (or disconnect if connected) shouldn't be called, that is still the way to go. It seems cleaner to have this thread a daemon.
This behaviour has been introduced in 7.1, older CLI class was not able to execute command if not connected (so no way, for example, to handle embedded nor version command without connecting).
> Fix for WFCORE-3548, CLI, Command executor should create daemon thread

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
- elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/RealmMapperDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/TrivialResourceDefinition.java
Also update the XML reader and writer to be supplied using Lambda expressions, this avoids those classes being loaded when not used i.e. subsystem extension installed but no subsystem in config or domain mode servers.
> [WFCORE-3457] Make 'TrivialResourceDefinition' final and use a Builder instead of extending each time.

- pom.xml
https://issues.jboss.org/browse/WFCORE-3549
We should be keeping components as final. An alpha version of the log manager was added so the [`json-formatter`](https://github.com/wildfly/wildfly-core/pull/2872) could be added. However this should only be done once the log manager itself is final.
> [WFCORE-3549] Downgrade jboss-logmanager to a final version, 2.0.9.Final

- cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIScriptSupportTestCase.java
The current context can only be terminated if connection succeeds.
Added test to mimic jdr script logic.
> Fix for WFCORE-3575, CLI, failed connect side effect

- server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
- server/src/main/java/org/jboss/as/server/deployment/Attachments.java
- server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
- server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
There are some use cases (e.g. shared java:global bindings) that result in services being installed outside of a deployments ServiceTarget. This means that are not added to the stability monitor, which results in intermittent test failures due to a false stability being achieved before all services have come up.
At present it is not possible to access this stability monitor, so there is no way to fix this issue.
> WFCORE-3584 Stability monitor should be exposed to DUP's

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/AbstractCommaCompleter.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/AbstractCompleter.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractDeployCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractUndeployCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/EnableCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/InfoCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/security/OptionActivators.java
- cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/deployment/command_resources.properties
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Completion in domain mode had been overlooked for the new deployment actions.
Fix for WFCORE-3564 server-groups completion. Refactored completion and introduced Abstract completers. Added unit tests.
Fix for WFCORE-3567 option completion. Added unit tests.
> CLI deployment command completion issues in domain mode

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/ListCommand.java
upstream jira: https://issues.jboss.org/browse/WFCORE-3571
Minor improvement: Improve CLI error handling in ListCommand class. If management operation doesn't return correct results, CLI throw correct error message.
@jfdenise please check
> [WFCORE-3571] Improve CLI error handling in ListCommand

- logging/pom.xml
This change makes every byteman scanner use a different port. If a test is slow to release
a port for some reason it will not interfere with subsequent tests.
> WFCORE-3588 Intermittent failures in LoggingSubsystemRollbackTestCase

- pom.xml
This is a delta between 4.x and other branches that I want to make go away. It's easier for me to make it go away in favor of what's in the other branches.  The change should have no functional impact.
> allow to specify version of org.wildfly.openssl.wildfly-openssl native bits

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
Elytron security:
Adding scram password support into set-password operation of modifiable security realms.
https://issues.jboss.org/browse/WFCORE-3541
> [WFCORE-3541] ScramDigestPassword into set-password operation

- elytron/pom.xml
- pom.xml
- testsuite/client-old-server/pom.xml
- testsuite/pom.xml
Add JaCoCo profile to wf-core TS
PR adds new profile, current default behaviour is not changed.
JBEAP jira: https://issues.jboss.org/browse/JBEAP-12795
WFCORE jira: https://issues.jboss.org/browse/WFCORE-3201
WF-CORE 3.0.x PR: https://github.com/jbossas/wildfly-core-eap/pull/406
> [WFCORE-3201] Add JaCoCo profile

- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/deployment/Attachments.java
This ServiceTarget can be used to install services outside the scope of a deployment, while still being monitored by the container state monitor.
> WFCORE-3592 Expose external ServiceTarget to DUP processing

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
The issue is that TestUndertowService is designed for testing suspend/resume rather than an actual graceful shutdown. Because it attempts to perform a dispatch() and queue a task rather than just immediately setting a 503 response it is possible that this request will fail with a 500 response if the XNIO executor is in the process of shutting down.
It would be better if this test checked for a 503 before the skip-graceful request is made.
> WFCORE-3595 SuspendOnSoftKillTestCase can fail intermittently

- controller/src/main/java/org/jboss/as/controller/operations/common/ProcessReloadHandler.java
Presently when issuing a reload operation the process state is updated asyncrounously,
which means that it is possible for a subsequent read of the process-state to return
a state of 'running' even though the server is actually in the process of reloading.
This can cause intermittent failures in any tests that perform a reload, as the general
pattern followed by these tests is to do a reload and then check the process state in a
loop until it is back to 'running'.
> WFCORE-3594 Reload is racey with regard to reading the process state

- controller/src/main/java/org/jboss/as/controller/PathAddress.java
- controller/src/main/java/org/jboss/as/controller/RestartParentResourceHandlerBase.java
- controller/src/main/java/org/jboss/as/controller/RestartParentWriteAttributeHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ServerGroupDeploymentReplaceHandler.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java
https://issues.jboss.org/browse/WFCORE-3483
Minor thing to help make it easier to move to a cleaner exception model in future management code.
> [WFCORE-3483] Deprecate PathAddress.navigate and remove, replace controller catches of NoSuchElementException with Resource.NoSuchResourceException

- elytron/src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
- elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
REQUIRED_OIDS attribute unwrap returns an immutable array throwing an UnsupportedOperationException when new elements are added. This patch fixes this situation.
Jira issue: https://issues.jboss.org/browse/WFCORE-3604
> [WFCORE-3604] Attribute required-attributes of Elytron x500-attribute-principal-decoder cannot be added to configuration

- controller/src/main/java/org/jboss/as/controller/ConfigurationChangesCollector.java
Displaying always the milliseconds for configuration changes operation dates
Jira: https://issues.jboss.org/browse/WFCORE-3609
> [WFCORE-3609]:Fix milliseconds format in configuration changes operation date

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling/river/main/module.xml
- deployment-scanner/pom.xml
- pom.xml
WFCORE-3607 [jdk10] upgrade jboss-marshalling to make remoting work on JDK10
WFCORE-3606 [jdk9+] use release=8 for compiling deployment scanner
With this jboss-marshalling upgrade our testsuite will start working on JDK10. which will allow us to see how well do we pass it.
Without this all remoting invocations are broken on JDK 10.
superceeds #3104
> WFCORE-3607 WFCORE-3606 [JDK9 & 10] marshalling upgrade & fixes

- pom.xml
This is wildfly-core part of https://github.com/wildfly/wildfly/pull/10796
jira: https://issues.jboss.org/browse/WFCORE-3618
https://issues.jboss.org/browse/EAP7-431
https://issues.jboss.org/browse/WFLY-9736
> WFCORE-3618 JDK9+ add Automatic-Module-Name to all spec_api deps

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
Check that the console is started prior to reset collected output.
Manual testing of the fix.
> Fix for WFCORE-3640, CLI output swallowed with script + prompting

- pom.xml
This upgrade brings in [MSC-204] fixes for container shutdown
freeze regressions. See [WFCORE-3590] for more information.
> [WFCORE-3641] Upgrading JBoss MSC to 1.3.1.Final.

- server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
Reverts wildfly/wildfly-core#3082
https://issues.jboss.org/browse/WFCORE-3522
This is causing issues with module linking where service loaders are being discovered twice for EAR deployments.
> Revert "[WFCORE-3522] Partial workaround: allow user services to take precedence for JAX-RS client builders"

- cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractDeployContentCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/DeployFileCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/DeployUrlCommand.java
Jira: https://issues.jboss.org/browse/WFCORE-3649
The wrong option is advertised by the error message. In case of legacy deploy command it must be --force instead of --replace.
Done manual testing of the error case.
> Fix for WFCORE-3649. CLI, --replace advertised for legacy command

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-3637
Although we observe 1% failure, the highlighted problem when run manually occurs much more often.
> Fix for WFCORE-3637, upgrade to aesh-readline 1.5

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/security/OptionActivators.java
Jira
https://issues.jboss.org/browse/WFCORE-3648
The problem is that activators are establishing expected attributes to be present and passing empty String value (`DependOptionActivator.ARGUMENT_NAME`).
Also, cleans up unnecessary modifiers.
> WFCORE-3648 Options --disabled/--enabled/--replace are missing in CLI code completion

- testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
1) Don't close client immediately after reload; it's redundant as it's closed again when checking for running status and doing it so quickly risks interrupting the reload in progress
2) Delay 100 ms before the first status check. It takes at least that long to do a reload anyway. This aligns behavior with the ServerReload util.
https://issues.jboss.org/browse/WFCORE-3646
> [WFCORE-3646] Improve reload handling in WildFly Core test runner

- controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
- controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
This changes the error reporting on failure to only report on services
that are missing direct dependencies. Services which did not start
due to indirect problems are no longer reported.
> WFCORE-3614 Only report on directly missing deps

- core-feature-pack/pom.xml
- core-feature-pack/src/license/core-feature-pack-licenses.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/commons/logging/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/logging/commons/logging/main/module.xml
- pom.xml
- testsuite/shared/pom.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/AbstractLoggingProfilesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/CommonsLoggingProfilesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/CommonsLoggingServiceActivator.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Log4jLoggingProfilesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Slf4jLoggingProfilesTestCase.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Slf4jServiceActivator.java
https://issues.jboss.org/browse/WFCORE-3656
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/29
The first commit simply adds tests for each supported logging API to test against logging profiles. The initial change of the Apache Commons Logging implementation to a new which delegates to JBoss Log Manager was initiated by commons-logging not working with logging profiles.
The next commit replaces the `org.jboss.logmanager:commons-logging-jboss-logmanager` implementation with `org.jboss.logging:commons-logging-jboss-logging` which delegates to JBoss Logging. There was an issue using the embedded API with Artemis if the JBoss Log Manager was not the default log manager. This prompted a change to delegate commons-logging to JBoss Logging instead which allows for common log …
> [WFCORE-3656] Replace commons-logging implementation.

- cli/src/main/java/org/jboss/as/cli/handlers/PrefixHandler.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CdTestCase.java
- Fixed handler to not send a request to validate an empty address or an address containing only a type.
- Added unit test.
> Fix for WFCORE-3671, fixed cd command path validation

- cli/src/main/resources/help/done.txt
- cli/src/main/resources/help/for.txt
Help change only.  The example was missing in 'for' command. Added an example in 'done' command too.
> Fix for WFCORE-3673, CLI, add examples in for/done command help

- core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
Moved the args variable definition before to enable delayed expansion.
Manual testing of '!' contained in cli script paths/arguments (passwords and commands). 
Didn't find regressions for WFCORE-2561, WFCORE-2582, WFCORE-2338.
> Fix for WFCORE-3674, CLI fix .bat file to not strip out ! from arguments

- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/commons/codec/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/httpcomponents/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/james/mime4j/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/standalone/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/url/http/wildfly-url-http/main/module.xml
- pom.xml
This PR introduce new component into WildFly (as discussed with @dmlloyd):
https://github.com/wildfly/wildfly-url-http
URL handler should ensure using correct Elytron AuthenticationContext for authentication/identity propagation/ssl by URL calls.
As it requires apache httpclient and it should be in wildfly-core (as discussed),
dependencies was moved into wildfly-core too.
https://issues.jboss.org/browse/WFCORE-3658
> [WFCORE-3658] Introducing wildfly-url-http component

- core-feature-pack/src/license/core-feature-pack-licenses.xml
This is a forward port of an EAP productization fix.
> add missing licenses for aesh-readline and aesh-extensions

- core-management/core-management-client/pom.xml
- deployment-repository/pom.xml
- deployment-scanner/pom.xml
- discovery/pom.xml
- domain-management/pom.xml
- embedded/pom.xml
- host-controller/pom.xml
- remoting/subsystem/pom.xml
- request-controller/pom.xml
- server/pom.xml
- version/pom.xml
This follows up #3129 with a commit that removes unneeded maven deps that correspond to the unneeded module deps.
This also helps validate the #3129 change by proving that the removed runtime deps aren't need at compile time either.
> [WFCORE-3587] Remove maven deps corresponding to the unneeded module deps

- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron-subsystem: https://issues.jboss.org/browse/WFCORE-3458
JBEAP: https://issues.jboss.org/browse/JBEAP-13978
Removing the requirement "if location is not set in CLI, default
credential-store name is used as location"
When location is not set for most common filebased keystore types (JKS,
JCEKS and PKCS12), Elytron will throw exception.
Elytron PR: https://github.com/wildfly-security/wildfly-elytron/pull/1051
> [WFCORE-3458] External CS, PKCS11 can't be configured with externalPath

- core-feature-pack/pom.xml
- core-feature-pack/src/license/core-feature-pack-licenses.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/ch/qos/cal10n/main/module.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/org/slf4j/ext/main/module.xml
- pom.xml
* move the org.slf4j.ext module (and its ch.qos.cal10n dependency) to
core-feature-pack
* add dependency to jcl-over-slf4j. It is not directly required for
WildFly but this allows to have all SLF4J dependencies in Core and
have a single authoritative version for them.
JIRA: https://issues.jboss.org/browse/WFCORE-3703
> [WFCORE-3703] Move all SLF4J dependencies to Core

- controller/src/test/java/org/jboss/as/controller/persistence/ConfigurationFileUnitTestCase.java
Link to JIRA [https://issues.jboss.org/browse/WFCORE-3513](https://issues.jboss.org/browse/WFCORE-3513)
Description: In case a file not named as yyyyMMdd-HHmmssSSSname.xml is present in the snapshot folder, the server start abort with a StringIndexOutOfBoundsException.
Original pull request with manual mode integration test [https://github.com/wildfly/wildfly/pull/11035](https://github.com/wildfly/wildfly/pull/11035)
> [WFCORE-3513] Add unit test

- controller/src/main/java/org/jboss/as/controller/OperationDefinition.java
https://issues.jboss.org/browse/WFCORE-3761
Minor. These methods are unused and there's no plan to use them.
I expect we'll at some point deprecate this maven module's OperationDefinition altogether as part of creating a new Extension API module, but this is just being proactive in case we don't or it takes a long time.
> [WFCORE-3761] Deprecate unused OperationDefinition methods

- host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyModeTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-3758
It verifies the current running mode before starting any servers with `:start-servers` or `/server-group=*:start-servers`
> [WFCORE-3758] Do not start servers if the host is in admin-only mode

- component-matrix/pom.xml
https://issues.jboss.org/browse/WFCORE-3764
Release Notes - WildFly Elytron - Version 1.3.0.Final
** Enhancement
* [ELY-1067] - Add support to use default GSSCredential CredentalSource with AuthenticationConfiguration from XML
** Bug
* [ELY-534] - Some tests fail with ExceptionInInitializerError with JMockit 1.22 for IBM JDK
* [ELY-1436] - Log jdbc-realm key-mapper processing
* [ELY-1503] - SPNEGO fails on <distributable/> deployment
* [ELY-1521] - Coverity, SpnegoContext is Serializable; consider declaring a serialVersionUID
* [ELY-1550] - Performance issue in audit endpoints
* [ELY-1552] - Coverity, Reliance on default encoding in DigestAuthenticationMechanism.
* [ELY-1553] - ElytronXmlParser.parseAuthenticationClientConfiguration() requires additional Permission when runs with Security …
> [WFCORE-3764] Upgrade WildFly Elytron to 1.3.0.Final

- jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRootResource.java
- jmx/src/main/resources/org/jboss/as/jmx/LocalDescriptions.properties
This is the first step in order to remove the `show-model` attribute from jmx subsystem.
Jira issue: https://issues.jboss.org/browse/WFCORE-3776
CC @kabir
> [WFCORE-3776] Deprecate attribute 'show-model' in jmx subsystem

- core-feature-pack/src/main/resources/configuration/domain/subsystems.xml
https://issues.jboss.org/browse/WFCORE-3784
> [WFCORE-3784] Add missing subsystems to WildFly Core domain.xml profile

- core-feature-pack/src/main/resources/content/bin/jboss-cli.ps1
Introduce a new variable to contain IBM specific option. Manual testing on windows platform.
> Fix for WFCORE-3789, CLI, powershell option handling

- component-matrix/pom.xml
https://issues.jboss.org/browse/WFCORE-3798
Release Notes - WildFly Elytron - Version 1.3.1.Final
** Bug
* [ELY-1480] - Coverity, Explicit null dereferenced in FileSystemSecurityRealm
* [ELY-1536] - DigestSaslClient parse but ignore "stale" param
* [ELY-1547] - SPNEGO: missing negstat field in the first reply for expired token
* [ELY-1549] - IBM JDK, SPNEGO + FORM; with invalid ticket 401 status code is returned
* [ELY-1564] - In PasswordKeyMapper an exception is logged with a wrong algorithm name.
** Task
* [ELY-1532] - Deprecate AuthConf setHost, setProtocol, setPort properties
** Release
* [ELY-1575] - Release WildFly Elytron 1.3.1.Final
> [WFCORE-3798] Upgrade WildFly Elytron to 1.3.1.Final

- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
https://issues.jboss.org/browse/WFCORE-3765
Follows up on #3229 to declare remove `org.jboss.msc` from the modular system class path.
> [WFCORE-3765] Remove org.jboss.msc from the modular system class path

- jmx/src/main/resources/subsystem-templates/jmx.xml
Further removal of comments from our standard config files.
> Remove comment from jmx subsystem template for domain

- core-galleon-pack/pom.xml
- core-galleon-pack/wildfly-feature-pack-build.xml
- pom.xml
This change eliminates the need for the commit in WFCORE-3808.
Also removes properties from the configs that are matching the defaults, so not effective.
> [WFCORE-3811] Upgrade to WildFly Galleon Plugins 1.0.0.Alpha20

- cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
- component-matrix/pom.xml
Upgrade aesh dependencies:
aesh 1.4,
aesh-extensions 1.3
aesh-realine 1.7
Workaround AESH-463 by entering in raw mode during the whole CLI process life time.
> Fix for WFCORE-3732, aesh 1.4 upgrade, terminal in raw mode by default

- controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
https://issues.jboss.org/browse/WFCORE-3813
> [WFCORE-3813] Eliminating usages of deprecated SC.getImmediateUnavailableDependencies() method.

- pom.xml
https://issues.jboss.org/browse/WFCORE-3820
> [WFCORE-3820] Upgrade jboss-logmanager from 2.1.1.Final to 2.1.2.Final

- pom.xml
These component updates are just to synchronize the latest fixes from the maintenance branches.
The tool is also required as it includes the WildFly Elytron classes.  Although the tool has had a minor version increment this is just to leave the 1.1.x release stream free should WildFly 12 require a further release.
https://issues.jboss.org/browse/WFCORE-3837
https://issues.jboss.org/browse/WFCORE-3838
> [WFCORE-3837] / [WFCORE-3838] WildFly Elytron Component Upgrades

- pom.xml
https://issues.jboss.org/browse/WFCORE-3841
Galleon 1.0.0.CR2 fixes an issue of adding features with list-add operation with the setting config.branch-per-spec disabled, which is the default now.
Galleon Plugins 1.0.0.CR3 fixes an issue when jboss-modules might not be able to resolve artifacts with hardcoded versions in module.xml during feature spec generation.
> [WFCORE-3841] Upgrade to Galleon 1.0.0.CR2 and Galleon Plugins 1.0.0.CR3

- core-feature-pack/src/main/resources/content/bin/common.ps1
https://issues.jboss.org/browse/WFLY-10209
In addition PR https://github.com/wildfly/wildfly/pull/11114 is dependent on this PR.
appclient.ps1 calls the function provided here in common.ps1.
> WFLY-10209] added a function for appclient.ps1 usage

- server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
https://issues.jboss.org/browse/WFCORE-3816 ExtensionIndexService throws NPE while reading extensions on the IBM jdk   
IBM jdk contains 
```
ibm-java-8.0-5.11/jre/lib/ext/traceformat.jar: java.lang.NullPointerException
ibm-java-8.0-5.11/jre/lib/ext/dtfj.jar: java.lang.NullPointerException
ibm-java-8.0-5.11/jre/lib/ext/dtfjview.jar: java.lang.NullPointerException
``` 
where `manifest.getMainAttributes();` throws NPE.
causes ->
https://issues.jboss.org/browse/WFLY-10349 WeldBundledLibraryDeployment Test cases fail on IBM jdk
> [WFCORE-3816] ExtensionIndexService throws NPE while reading extensions on the IBM jdk

- pom.xml
https://issues.jboss.org/browse/WFCORE-3857
This upgrade contains support for colon as a separator between module name and slot in module.xml module dependencies. It still supports the legacy way of specifying the slot using an attribute.
> WFCORE-3857 Upgrade to WildFly Galleon plugins 1.0.0.CR6

- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
https://issues.jboss.org/browse/WFLY-10394
> [WFLY-10394] Workaround wrong TCCL issue in naming subsystem by restoring lost (otherwise unused) dependency

- pom.xml
https://issues.jboss.org/browse/WFCORE-3883
https://issues.jboss.org/browse/WFCORE-3890
Release Notes - WildFly Elytron - Version 1.3.3.Final
** Bug
* [ELY-1568] - elytron-client-1.1.xsd xsd:all minOccurs="0"
* [ELY-1589] - elytron-client-1_1.xsd is invalid
* [ELY-1592] - CLI + Kerberos authentication fails in CD13
** Release
* [ELY-1594] - Release WildFly Elytron 1.3.3.Final
> [WFCORE-3883] / [WFCORE-3890] WildFly Elytron Component Upgrades

- controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
- controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
Adding required capabilities in features for Object attributes.
Jira: https://issues.jboss.org/browse/WFCORE-3795
> [WFCORE-3795]: ReadFeatureDescription doesn't return ObjectAttributeDefinition capabilities

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/ManagementDisableSSLCommand.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
The root cause of the reported problem is tha tthe property com.ibm.jsse2.overrideDefaultTLS=true is missing.
I ran into other cases when the :reload operation is canceled although the operation is not yet done. Fixed this case too.
> Fix for WFCORE-3829, ReloadRedirectTestCase failing with ibm jdk

- model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
* add staging repository to MavenUtil
If the jboss.staging.repository.group System property is present, adds
JBoss staging repository to the remote repositories used to download
artifacts from MavenUtil.
JIRA: https://issues.jboss.org/browse/WFCORE-3902
> [WFCORE-3902] Support Maven staged repositories

- server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
- server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
If a ManagerExecutor is executing a task which is re-scheduling a new instance of itself just before exiting then the domain cannot be stopped when the timeout of stop operation is 0.
The problem is the listener is not notified when the user uses 0 as a timeout.
Since EE subsystem is not available in wildfly-core, I will add a test case in wildfly once this patch is merged and available from wildfly.
Jira issue: https://issues.jboss.org/browse/WFCORE-3868
> [WFCORE-3868] Notify the suspend listener when timeout is 0

- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FilePermissionTestCase.java
Removal of badly designed test. The user may have set different umask.
> [WFCORE-3559] Remove FilePermissionTestCase.testFileDefaultPermissions

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
Fix for WFCORE-3910: https://issues.jboss.org/browse/WFCORE-3910
Has been introduced due to jdeps advertising jdk.jconsole as a dependency. But this dependency is only present in a jconsole context, outside jboss modules.
> Fix for WFCORE-3910, CLI remove dependency on jdk.jconsole

- component-matrix-builder/pom.xml
wildfly-core-component-matrix-builder to be able to import it into
Eclipse
https://issues.jboss.org/browse/WFCORE-3907
@jmesnil could you please review?
> [WFCORE-3907] Rename wildfly-component-matrix-builder to

- controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
Closing the LocalClient will interrupt running operations.
Jiira: https://issues.jboss.org/browse/WFCORE-3102
> [WFCORE-3102]: CloseableLocalClient

- pom.xml
This reverts commit 28afc6ce73c17c3975b30701a44813d02471e79c.
https://issues.jboss.org/browse/WFCORE-3921
The bug fix brought in via the component upgrade needs to be revisited under https://issues.jboss.org/browse/SECURITY-991
> Revert "[WFCORE-3898] Upgrade PicketBox to 5.1.0.Final"

- testsuite/shared/pom.xml
- testsuite/test-runner/pom.xml
- testsuite/vault-test-feature-pack/pom.xml
Some testsuite do not use wildfly-core-testsuite as their parent.
Flag those to skip Maven deployments (testsuite modules are not part of
a release).
JIRA: https://issues.jboss.org/browse/WFCORE-3915
> [WFCORE-3915] Do not deploy testsuite modules

- cli/src/main/java/org/jboss/as/cli/impl/CLICommandCompleter.java
- pom.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/MoreTestCase.java
- Aesh upgrade.
- Includes fixes for WFCORE-3545, uncomment test with multiple chars
- Includes fixes for WFCORE-3904, NPE at Tab completion
> Fix for WFCORE-3903, upgrade aesh 1.6, readline 1.9 and extensions 1.5

- testsuite/shared/pom.xml
Revert change for wildfly-core-testsuite-shared as it is a dependency of
wildfly-testsuite-shared in WildFly Full codebase.
JIRA: https://issues.jboss.org/browse/WFCORE-3915
> [WFCORE-3915] Do not deploy testsuite modules

- cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
- cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
- cli/src/main/java/org/jboss/as/cli/embedded/EmbeddedControllerHandlerRegistrar.java
- cli/src/main/java/org/jboss/as/cli/impl/SecurityActions.java
This is an attempt to simplify modular context detection. @bstansberry @jamezp this is a follow-up for WFCORE-3866.
> Fix for WFCORE-3935, CLI, revisit modular context detection

- pom.xml
https://issues.jboss.org/browse/WFCORE-3951
> [WFCORE-3951] Upgrade jboss-logmanager from 2.1.2.Final to 2.1.3.Final.

- pom.xml
https://issues.jboss.org/browse/WFCORE-3954
There was an issue with 2.1.3.Final which causes the https://issues.jboss.org/browse/WFCORE-3407 to not work correctly. An upgrade which includes https://issues.jboss.org/browse/LOGMGR-198 is required.
> [WFCORE-3954] Upgrade jboss-logmanager from 2.1.3.Final to 2.1.4.Final.

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractDisableAuthenticationCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractEnableAuthenticationCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractMgmtDisableAuthenticationCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractMgmtEnableAuthenticationCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/HTTPServerDisableAuthCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/HTTPServerEnableAuthCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementDisableHTTPCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementDisableSASLCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementEnableHTTPCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementEnableSASLCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ApplicationSecurityDomain.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthSecurityBuilder.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/HTTPServer.java
- cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/auth/command_resources.properties
- core-galleon-pack/src/main/resources/feature_groups/elytron-app.xml
- core-galleon-pack/src/main/resources/packages/misc.common/pm/wildfly/tasks.xml
- elytron/src/main/resources/subsystem-templates/elytron.xml
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
This pull request is 2 of 3 and can be merged after https://github.com/wildfly/wildfly/pull/11400
https://issues.jboss.org/browse/WFCORE-3945
This pull request removes the application-http-authentication http-authentication-factory from the default configuration, it also contains updates to the JBoss CLI to use the new attribute added under https://github.com/wildfly/wildfly/pull/11400 and to no longer depend on the removed default configuration.
> [WFCORE-3945] Remove the application-http-authentication http-authentication-factory from the default configuration.

- pom.xml
- aesh upgrade required by installer.
> Fix for WFCORE-3968, Upgrade CLI to use aesh 1.7 and aesh-readline 1.10

- pom.xml
Upgrade required to remove javafx dependency introduced by aesh-extensions
> Fix for WFCORE-3973, Upgrade CLI to use aesh-extensions 1.6

- controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcess.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
- embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
It was found that the embedded server was not using a consistent class loader when it was invoked via Galleon, jboss-cli-client.jar or standard jboss-cli.sh. 
This patch sets a specific class loader when the embedded server starts/stops and when its operations are executed in order to have a consistent class loader across all uses.
Jira issue: https://issues.jboss.org/browse/WFCORE-3943
> [WFCORE-3943] Use specific class loaders for embedded servers

- elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/Configurable.java
- elytron/src/main/java/org/wildfly/extension/elytron/CustomComponentDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser3_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser4_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_4_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/audit-logging.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
https://issues.jboss.org/browse/WFCORE-3819 (custom audit, https://issues.jboss.org/browse/EAP7-1007, analysis: https://github.com/wildfly/wildfly-proposals/pull/68)
https://issues.jboss.org/browse/WFCORE-3877 (Configurable optional, https://issues.jboss.org/browse/EAP7-1005, analysis: https://github.com/wildfly/wildfly-proposals/pull/69)
test + doc of this: https://github.com/wildfly/wildfly/pull/11367 (https://issues.jboss.org/browse/WFLY-10611)
* added custom-security-event-listener
* reworked CustomComponentDefinition to allow passing wrapper (to allow custom-security-event-listener to implement Consumer<SecurityEvent> and not to depend on subsystem-specific SecurityEventListener)
* as requested by @darranl, removed need to implement Configurable interface requirement - method …
> [WFCORE-3819][WFCORE-3877] added custom-security-event-listener into Elytron

- pom.xml
https://issues.jboss.org/browse/WFCORE-3990
This is the root cause of at least these issues:
* https://issues.jboss.org/browse/WFCORE-3869
* https://issues.jboss.org/browse/WFCORE-3874
* https://issues.jboss.org/browse/WFCORE-3875
> [WFCORE-3990] Upgrade to Byteman version 4.0.4 for better JDK9+ support.

- core-feature-pack/pom.xml
- core-feature-pack/src/main/resources/modules/system/layers/base/javax/security/auth/message/api/main/module.xml
- core-galleon-pack/pom.xml
- pom.xml
:warning: Do not Rebase this PR, the commits in this PR are contained in further topic branches. :warning: 
This is just a small sub-step as the WildFly Elytron subsystem will depend on this module in a similar way it already does for JACC, as this is a move from WildFly to WildFly Core it is better to split it out and get it included on it's own.
https://issues.jboss.org/browse/WFCORE-3519
> [WFCORE-3519] Add JASPI module to core-feature-pack.

- pom.xml
- testsuite/domain/pom.xml
- testsuite/elytron/pom.xml
- testsuite/manualmode/pom.xml
- testsuite/standalone/pom.xml
https://issues.jboss.org/browse/WFCORE-3984
--add-modules java.se for modular.jdk.args for Java 11 ea improvements
> [WFCORE-3984] --add-modules java.se for modular.jdk.args

- pom.xml
https://issues.jboss.org/browse/WFCORE-3981
The only difference between 3.3.1.Final and 3.3.2.Final is the addition of the `Automatic-Module-Name` to the manifest.
https://github.com/jboss-logging/jboss-logging/compare/3.3.1.Final...3.3.2.Final
> [WFCORE-3981] Upgrade jboss-logging from 3.3.1.Final to 3.3.2.Final.

- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/JdkModuleDependencyTestCase.java
* Adding a simple test case with tests deploying applications depending on JDK8+ API modules iteratively checking for success and functionality.
> [WFCORE-3705] Allow dependencies on JDK modules

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
https://issues.jboss.org/browse/WFCORE-3970
https://issues.jboss.org/browse/EAP7-1052
Analysis Document: https://github.com/wildfly/wildfly-proposals/pull/115
Documentation PR: https://github.com/wildfly/wildfly/pull/11496
> [WFCORE-3970] Add a management operation to allow an Elytron trust-manager to be re-initialized

- pom.xml
This is a release containing the following bug fixes, some of which are required to fix issues identitfied in current RFEs
https://issues.jboss.org/browse/WFCORE-4011
Release Notes - WildFly Elytron - Version 1.5.2.Final
** Bug
* [ELY-1616] - ldap-key-store requires attribute userPKCS12 on ldap entry, even if it should be mandatory
* [ELY-1618] - TLS with BCJSSE Provider does not work
* [ELY-1622] - BC FIPS with CLI: SunX509 KeyManagerFactory not available
** Task
* [ELY-787] - SASL mechanisms are not IANA registered and specifications are not provided
* [ELY-1625] - Fix ECPublicKey import in testsuite
** Release
* [ELY-1628] - Release WildFly Elytron 1.5.2.Final
> [WFCORE-4011] Upgrade WildFly Elytron to 1.5.2.Final

- pom.xml
This release is a bug fix release only.
https://issues.jboss.org/browse/WFCORE-4013
Release Notes - Elytron Web - Version 1.2.1.Final
** Bug
* [ELYWEB-6] - Coverity, Dereference null return value ElytronHttpServletExchange
* [ELYWEB-8] - constraint drive authentication method in undertow doesn't work with elytron
** Release
* [ELYWEB-10] - Release Elytron Web 1.2.1.Final
> [WFCORE-4013] Upgrade Elytron Web to 1.2.1.Final

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
- server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/ExtensibleHttpManagement.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/CustomContextExtension.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/testbase/CustomManagementContextTestBase.java
* add addManagementHandler(String, boolean, HttpHandler) method to the
ExtensibleHttpManagement API
JIRA: https://issues.jboss.org/browse/WFCORE-3999
Proposal: https://github.com/wildfly/wildfly-proposals/pull/117
> [WFCORE-3999] Allow registering a custom HTTP handler for management interface

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- controller/src/main/java/org/jboss/as/controller/operations/PathAddressFilter.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadConfigAsFeaturesOperationHandler.java
- controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
- controller/src/test/java/org/jboss/as/controller/test/ReadConfigAsFeaturesTestCase.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/GenericModelDescribeOperationHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainOperationsHandler.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-3991
This is a read-only and hidden operation which reads the management model and represents it in terms of provisioning features. This operation is used by Galleon provisioning plugins to generate configuration diffs.
> [WFCORE-3991] read-config-as-features management operation

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ReadConfigAsFeaturesDomainTestCase.java
- testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ReadConfigAsFeaturesTestBase.java
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
https://issues.jboss.org/browse/WFCORE-3991
This is additional test coverage for the `read-config-as-features` operation. Covers both standalone and domain mode. The difference between these tests and the tests in #3438 is that these make changes on real subsystems, then expect the operation output to change accordingly. The changes made were chosen fairly arbitrarily, but the idea is that each change is done on a different part of the model.
Depends on #3438  
Cc @aloubyansky
> [WFCORE-3991] Test coverage for read-config-as-features

- pom.xml
WildFly Elytron Tool is a shaded jar containing amongst other things WildFly Elytron, this release is just to update the versions of the components it contains to match those either already in WildFly Core or about to merged to WildFly Core shortly.
https://issues.jboss.org/browse/WFCORE-4021
> [WFCORE-4021] Upgrade WildFly Elytron Tool to 1.3.0.Final

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-4014
> [WFCORE-4014] Using DelegatingTrustManager correctly to ensure new TrustManager will be used on re-initialization by existing SSLContexts

- pom.xml
Bug fix release of WildFly Elytron
https://issues.jboss.org/browse/WFCORE-4016
Release Notes - WildFly Elytron - Version 1.5.3.Final
** Enhancement
* [ELY-1632] - Fix compiler warnings
** Bug
* [ELY-1630] - Ignore any blank lines in between the certificates in the certificate chain returned by an ACME server to avoid parsing issues on IBM JDK
* [ELY-1633] - Incorrect double checked locking in AuthenticationConfiguration
** Release
* [ELY-1635] - Release WildFly Elytron 1.5.3.Final
> [WFCORE-4061] Upgrade WildFly Elytron to 1.5.3.Final

- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/GitRepositoryTestCase.java
- testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteGitRepositoryTestCase.java
Trying to test the default Snapshot name in a more robust way.
Jira: https://issues.jboss.org/browse/WFCORE-4025
> [WFCORE-4025]:  Intermittent errors on RemoteGitRepositoryTestCase.historyAndManagementOperationsTest

- pom.xml
https://issues.jboss.org/browse/WFCORE-4028
Release Notes - WildFly Elytron - Version 1.5.4.Final
** Bug
* [ELY-1636] - Update AcmeChallenge.Type to be able to handle unknown challenge types
** Release
* [ELY-1638] - Release WildFly Elytron 1.5.4.Final
> [WFCORE-4028] Upgrade to WildFly Elytron 1.5.4.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4030
> [WFCORE-4030] Upgrade to Galleon and WildFly Galleon Plugins 2.0.0.Beta1

- core-feature-pack/src/main/resources/content/bin/jboss-cli.ps1
Makes the ps1 script to return the exit code of java process execution.
Manual testing of return value:
Inside a bach: echo %ERRORLEVEL% displays 0 or 1
Inside a powershell console: echo $? display True or False
> Fix for WFCORE-3831, jboss-cli.ps1 return value

- pom.xml
https://issues.jboss.org/browse/WFCORE-4038
Release Notes - WildFly Elytron - Version 1.5.5.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1629'>ELY-1629</a>] -         Let&#39;s Encrypt: Upcoming ACME v2 Key Rollover breaking change
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1641'>ELY-1641</a>] -         Release WildFly Elytron 1.5.5.Final
</li>
</ul>
> [WFCORE-4038] Upgrade WildFly Elytron to 1.5.5.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4052
https://issues.jboss.org/browse/WFCORE-4053
https://issues.jboss.org/browse/WFCORE-4054
The WildFly Elytron minor version bump is due to adding a new version of the client side schema to address the bug reported in ELY-1639.
The WildFly Elytron Tool minor version bump was due to including a version of WildFly Elytron that bumped the minor version.  No other changes made to WildFly Elytron Tool.
Release Notes - WildFly Elytron - Version 1.6.0.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1639'>ELY-1639</a>] -         FIPS PKCS11 Client side: only SunJSSE KeyManagers may be used
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1647'>ELY-1647</a>] -         Add some TRACE …
> [WFCORE-4052] / [WFCORE-4053] / [WFCORE-4054] WildFly Elytron Component Upgrades

- server/src/main/resources/schema/wildfly-config_5_0.xsd
- server/src/main/resources/schema/wildfly-config_6_0.xsd
- server/src/main/resources/schema/wildfly-config_7_0.xsd
- server/src/main/resources/schema/wildfly-config_8_0.xsd
https://issues.jboss.org/browse/WFCORE-4059
This attribute was added in the PR https://github.com/wildfly/wildfly-core/pull/2331 but the schema was not updated.
> [WFCORE-4059] Add missing attribute 'always-send-client-cert' to configuration schemas.

- controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-4062
Avoid Errors if code that used this constructor call if without first having been recompiled to the current WF Core.
> [WFCORE-4062] Restore legacy constructor, deprecated

- core-galleon-pack/pom.xml
- core-galleon-pack/wildfly-feature-pack-build.xml
- pom.xml
- testsuite/vault-test-feature-pack/wildfly-feature-pack-build.xml
https://issues.jboss.org/browse/WFCORE-4063
This release simplifies the configurations required to build feature-packs. Specifically:
- feature-packs element is not required any more in generate-feature-specs goal;
- the list of extensions from generate-feature-specs maven goal config moved to wildfly-feature-pack-build.xml and includes only the extensions that the feature-pack contains (i.e. no need to duplicate extensions from feature-pack dependencies, e.g. from core);
- producer attributes are not anymore needed for feature-pack dependencies in wildfly-feature-pack-build.xml
Also in this commit:
- explicit dependency on WFGP *-gen artifacts previously resolved from the Maven plugin at runtime
> [WFCORE-4063] Upgrade to Galleon and WildFly Galleon Plugins 2.0.0.Final

- core-galleon-pack/src/main/resources/packages/docs.licenses/pm/wildfly/tasks.xml
Do not override the feature pack properties for this task so we can get the correct wildfly-core version in the core-feature-pack-licenses.html file when the server is provisioned in wildfly-full.
Jira issue: https://issues.jboss.org/browse/WFCORE-4066
cc: @aloubyansky
> [WFCORE-4066] Avoid overriding galleon pack properties when core-feature-pack-licenses.html is created

- core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
- pom.xml
7.2.0. Once EAP 7.2.0 is released there is a follow up task to switch it
to use EAP 7.2.0 proper in WFCORE-4089
https://issues.jboss.org/browse/WFCORE-4085
> [WFCORE-4085] Temporarily use WF14 as the transformation target for EAP

- pom.xml
Brings in merged service builder implementations. 
Since now on ServiceBuilder methods never throw UnsupportedOperationException.
This pull request addresses the following issues:
* https://issues.jboss.org/browse/WFCORE-4090
* https://issues.jboss.org/browse/WFCORE-4101
> [WFCORE-4101][WFCORE-4090][JBEAP-15382] Upgrading MSC to 1.4.4.Final

- domain-management/src/test/java/org/jboss/as/domain/management/security/SecurityRealmServiceUtilTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
- server/src/test/java/org/jboss/as/server/AddServerExecutorDependencyTestCase.java
https://issues.jboss.org/browse/WFCORE-4099
The actual fix here was MSC-240.
This PR includes the commits from #3512 and #3508. I expect to merge #3512 independently, and then this will basically be test coverage for the critical cases.
> [WFCORE-4099] Add tests of widely usable utility methods that take a ServiceBuilder param

- model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
- model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
Follow-up on https://issues.jboss.org/browse/WFCORE-4085
Also https://issues.jboss.org/browse/WFCORE-4114 ‼️ DO NOT RESOLVE ‼️ - it is preparation for something I need to update in wildfly-legacy-test
> [WFCORE-4085] EAP_7_2_0_TEMP should use 14.0.0.Final as the version

- pom.xml
https://issues.jboss.org/browse/WFCORE-4111
Release Notes - WildFly Elytron - Version 1.6.1.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1640'>ELY-1640</a>] -         Update AcmeClientSpi.changeAccountKey() to no longer send the newKey once the new ACME v2 changes are in production
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1664'>ELY-1664</a>] -         Trace logging in SSLUtils
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1665'>ELY-1665</a>] -         Release WildFly Elytron 1.6.1.Final
</li>
</ul>
> [WFCORE-4111] Upgrade WildFly Elytron to 1.6.1.Final

- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-3180
> [WFCORE-3180] ElytronSubsystemMessages and LocalDescriptions.properties use double quotes within strings

- elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
- pom.xml
https://issues.jboss.org/browse/WFCORE-4118
Also small test fix for https://issues.jboss.org/browse/WFCORE-3971
The test that has been changed was changed as comparison fails once re-marshalled and compared to the original, both upper and lower case still parse successfully.
Release Notes - WildFly Elytron - Version 1.7.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1637'>ELY-1637</a>] -         Change ReferralMode.toString to return value
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-793'>ELY-793</a>] -         Using @STRENGTH keyword in CipherSuiteSelector.fromString should cause descending sorting
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1595'>ELY-1595</a>] -         Reenable source …
> [WFCORE-4118] Upgrade WildFly Elytron to 1.7.0.CR1

- pom.xml
The productized version of picketbox will include some libraries that must be excluded. Although those libraries are not in the community version, add the exclusions here is harmless and will minimize the required stuff for the product conversion. 
Alternatively, we could have this change in a specific eap-ization commit, but initially, it sounds better to me to have it directly in the upstream.
Jira issue: https://issues.jboss.org/browse/WFCORE-4119
> [WFCORE-4119] Add exclusions for org.picketbox

- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HTTPSManagementInterfaceTestCase.java
- testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
https://issues.jboss.org/browse/WFCORE-4002
JBEAP: https://issues.jboss.org/browse/JBEAP-15400
JBEAP PR: https://github.com/jbossas/wildfly-core-eap/pull/590
SocketException in SSL are in JDK-11 packed as cause into SSLException - SSLException with appropriate cause was allowed where SocketException was allowed before.
> [WFCORE-4002] JDK-11 - testsuite - tolerate SocketException packed into SSLException

- host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
* add WILDFLY14 to the HostExcludeResourceDefinition.KnownRelease enum
that corresponds to the WildFly14.0 value added to host-release XML
definition.
JIRA: https://issues.jboss.org/browse/WFCORE-4137
> [WFCORE-4137] Add missing KnownRelease for WildFly 14

- pom.xml
https://issues.jboss.org/browse/WFCORE-4133
https://issues.jboss.org/browse/WFCORE-4134
Release Notes - WildFly Elytron - Version 1.7.0.CR2
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1676'>ELY-1676</a>] -         Add missing ARIA encryption to CipherSuiteSelector
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1425'>ELY-1425</a>] -         Add support for JASPIC / JSR-196
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1427'>ELY-1427</a>] -         Credential store type PKCS12 works fine when using OracleJDK and OpenJDK but doesn&#39;t work using IBM JDK.
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1535'>ELY-1535</a>] - …
> [WFCORE-4133] / [WFCORE-4134] Upgrade WildFly Elytron to 1.7.0.CR2 and Elytron Web to 1.3.0.CR1

- elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
- elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser5_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_5_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/audit-logging.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
This is a re-submission of https://github.com/wildfly/wildfly-core/pull/3186 ported to version 5 of the WildFly Elytron subsystem's model and schema.
https://issues.jboss.org/browse/WFCORE-3404
Analysis document: wildfly/wildfly-proposals#112
Community documentation https://github.com/wildfly/wildfly/pull/11649
> [WFCORE-3404] Elytron audit performance - separated sync and flushing

- elytron/src/main/java/org/wildfly/extension/elytron/JaspiDefinition.java
Minor clean op following code review of merged PR: -
https://issues.jboss.org/browse/WFCORE-4146
> [WFCORE-4146] Remove redundant calls to .setXmlName().

- pom.xml
https://issues.jboss.org/browse/WFCORE-4151
<h1>Release Notes for JBoss Log Manager</h1>
<h3>Version 2.1.5.Final</h3>
<hr />
<h2>Bug</h2>
<ul>
<li>[ <a href="https://issues.jboss.org/browse/LOGMGR-200">LOGMGR-200</a> ] SSLProtocolException: Connection reset on JDK11</li>
<li>[ <a href="https://issues.jboss.org/browse/LOGMGR-201">LOGMGR-201</a> ] SysLogHandler doesn't log null or empty message</li>
<li>[ <a href="https://issues.jboss.org/browse/LOGMGR-202">LOGMGR-202</a> ] Some fields are not copied by the copy constructor of ExtLogRecord</li>
<li>[ <a href="https://issues.jboss.org/browse/LOGMGR-203">LOGMGR-203</a> ] LogManager stops any logging output after changing "encoding" attribute to file-handler</li>
<li>[ <a href="https://issues.jboss.org/browse/LOGMGR-204">LOGMGR-204</a> ] Short …
> [WFCORE-4151] Upgrade jboss-logmanager from 2.1.4.Final to 2.1.5.Final

- host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
* Add missing VERSION_7 and VERSION_8 to KernelAPIVersion so that domain transformers are
properly setup for WildFly 13 & 14.
* Use KernelAPIVersion in KnownRelease enum instead of ints so that
KernelAPIVersion is the only authoritative sources of Kernel versions.
* Fix inconsistency in KernelAPIVersion that was listing VERSION_4_1 for
WildFly 10.1 while the correct version was VERSION_4_2 (info in
KnownRelease was correct).
JIRA: https://issues.jboss.org/browse/WFCORE-4156
> [WFCORE-4156] Add missing KernelAPIVersion for WildFly 14

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
- controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- server/src/main/java/org/jboss/as/server/ServerService.java
Also, register the core capabilities with the root MRR so Galleon will know they are provided when it sees requirements for them.
https://issues.jboss.org/browse/WFCORE-4164
> [WFCORE-4164] Add fixed requirements to the read-feature-description output

- controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
- controller/src/main/java/org/jboss/as/controller/OperationContext.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
- controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/RegistrationPoint.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/RequirementRegistration.java
- controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
- host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
- jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorResource.java
- logging/src/main/java/org/jboss/as/logging/capabilities/LoggingProfileCapabilityRecorder.java
This patch adds the possibility to deregister an attribute reference capability for a specific attribute. Before this it was not possible, so undefine an attribute reference capability completely removes the capability from the resource, even if there were other attributes referring to it.
Jira issue: https://issues.jboss.org/browse/WFCORE-3039
> [WFCORE-3039] Capability requirement can be lost if two attributes on same resource reference the same capability

- testsuite/standalone/enable-elytron.cli
- testsuite/standalone/pom.xml
Upstream: https://issues.jboss.org/browse/WFCORE-3952
standalone/enable-elytron.cli is copied from shared/enable-elytron.cli but without domain part.
This reveales test fails, which rely on default configuration. Set of WFCORE issues should be created to fix this test cases. Later in future, once legacy security will be removed, they will have to be fixed anyway.
So far, these tests were identified
```
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java
testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSConnectionWithCLITestCase.java
testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt …
```
> [WFCORE-3952] Do not bother with host controllers in standalone module

- controller-client/src/main/java/org/jboss/as/controller/client/impl/ModelControllerProtocol.java
- controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClient.java
- controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClientImpl.java
- controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolOperationHandler.java
- host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerClient.java
- server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnection.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/DeploymentOverlayScenario.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/DeploymentScenario.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/OrderedChildResourceScenario.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/RBACModelOutOfSyncScenario.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/ReconnectTestScenario.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/SlaveReconnectTestCase.java
- testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/UnaffectedScenario.java
Some operations cannot be applied to the affected servers when the HC reconnects when RBAC is used. The problem is the principal used for the reconnection is anonymous and that user does not have elevated privileges to reconnect, so In-VM style call should be performed to address it and allow the reconnection.
Jira issue: https://issues.jboss.org/browse/WFCORE-4152
> [WFCORE-4152] HC cannot connect to DC after lost connect if models are out of sync and RBAC is enabled

- core-feature-pack/src/main/resources/content/bin/standalone.conf
- core-feature-pack/src/main/resources/content/bin/standalone.conf.bat
- core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
https://issues.jboss.org/browse/WFCORE-4113
> [WFCORE-4113] Add a commented line to standalone.conf to show how to use a custom java.security file to override all the Java security properties

- pom.xml
https://issues.jboss.org/browse/WFCORE-4168
https://issues.jboss.org/browse/WFCORE-4169
This component upgrade by itself does not activate any of the included RFEs so is ready to go in immediately provided we get clean CI runs.
I will update the SNI PR to also include these commits so we can get CI going on that one.
I have spoken to QE and they approved ELY-1551 being included in this component upgrade.
Release Notes - WildFly Elytron - Version 1.7.0.CR3
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1551'>ELY-1551</a>] -         JwtValidator jku and kid header parameters
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1661'>ELY-1661</a>] -         Add SNI SSLContext
</li>
</ul> …
> [WFCORE-4168] / [WFCORE-4169] WildFly Elytron Component Upgrades

- controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
It was possible to add extensions for modules that do not contain an extension. This patch validates that the module has an extension before adding it.
Jira issue: https://issues.jboss.org/browse/WFCORE-4120
> [WFCORE-4120] Do not allow adding a module as extension when the module does not contain an extension

- host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/Capabilities.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpListenerRegistryService.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
- remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemRootResource.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
- remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestUtil.java
- server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
- Add a capability for HttpListenerRegistryService and change the old service references to use the service exposed by the new capability 
- Move existing remoting capability names to the Capabilities class
- Expose the capability service name via RemotingServices
Jira issue: https://issues.jboss.org/browse/WFCORE-4166
> [WFCORE-4166] HttpListenerRegistryService is not exposed via a capability

- core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
- request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemAdd.java
- request-controller/src/test/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemTestCase.java
- server/src/main/java/org/jboss/as/server/BootstrapImpl.java
- server/src/main/java/org/jboss/as/server/ServerService.java
- server/src/main/java/org/jboss/as/server/Services.java
- server/src/main/java/org/jboss/as/server/operations/ServerDomainProcessShutdownHandler.java
- server/src/main/java/org/jboss/as/server/operations/ServerResumeHandler.java
- server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
- server/src/main/java/org/jboss/as/server/operations/ServerSuspendHandler.java
- server/src/main/java/org/jboss/as/server/operations/SuspendStateReadHandler.java
- server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
Expose SuspendController via a capability and remove old service references to use the service exposed by the capability
Jira issue: https://issues.jboss.org/browse/WFCORE-4165
> [WFCORE-4165] Expose SuspendController via a capability

- server/src/main/java/org/jboss/as/server/services/net/BindingRuntimeHandlers.java
- server/src/main/java/org/jboss/as/server/services/net/SocketBindingResourceDefinition.java
bound, bound-port and bound-address are not registered as runtime
read-only attribute as they do not qualify as metrics.
Rename BindingMetricHandlers to BindingRuntimeHandlers to avoid any
confusion.
JIRA: https://issues.jboss.org/browse/WFCORE-4173
> [WFCORE-4173] Register socket-binding bound attributes as read-only

- core-feature-pack/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser5_0.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
- elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_5_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-5.0.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- pom.xml
- testsuite/shared/src/main/java/org/wildfly/test/undertow/UndertowSSLService.java
- testsuite/shared/src/main/java/org/wildfly/test/undertow/UndertowSSLServiceActivator.java
- testsuite/shared/src/main/java/org/wildfly/test/undertow/UndertowServiceActivator.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
https://issues.jboss.org/browse/WFCORE-3873
This pull request follows up on the following PR and ports the changes on top of version 5 of the WildFly Elytron subsystem's model and schema: -
https://github.com/wildfly/wildfly-core/pull/3424
Additionally the WildFly Elytron subsystem follows a flat model hierarchy without parents depending on their children so I have flattened the model.
I did also have a general chat with Brian if we should be using alternative capability names to avoid circular referencing and in the end decided we didn't need to go to that level of enforcement in the model - we also have other resources that could potentially be configured with impossible cycles so this resource is not unique.
Finally the original discussion that we had regarding this feature was that we …
> WFCORE-3873 Support for SNI for server side SSLContext

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
- elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
- elytron/src/main/resources/schema/wildfly-elytron_5_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
This pull request supersedes https://github.com/wildfly/wildfly-core/pull/3501 which can be closed.
https://issues.jboss.org/browse/WFCORE-3966
https://issues.jboss.org/browse/EAP7-1068
Requires ELY-1551
https://issues.jboss.org/browse/ELY-1551
> [WFCORE-3966] JwtValidator jku and kid header parameters

- model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java
https://issues.jboss.org/browse/WFCORE-4184
@jmesnil I broke this one out from #3572 as it's a minor thing that doesn't have any of the bigger implications of the rest of the stuff in that PR.
> [WFCORE-4184] Don't lose track of what object's fields are all undefined

- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
* shutdown-requested is a runtime readonly attribute, not a metric
* remove "undefined metric value" from the attribute definitions as the
metric values can always be computed and will never be undefined.
* remove unnecessary calls to `setStorageRuntime()` from the metrics definition.
JIRA: https://issues.jboss.org/browse/WFCORE-4191
> [WFCORE-4191] Fix IO metrics registration

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/log4j/logmanager/main/module.xml
https://issues.jboss.org/browse/WFCORE-4198
> [WFCORE-4198] Remove unneeded org.dom4j module dependency.

- pom.xml
https://issues.jboss.org/browse/WFCORE-4208
https://issues.jboss.org/browse/WFCORE-4209
https://issues.jboss.org/browse/WFCORE-4210
No changes were made to WildFly Elytron Tool other than component upgrades to bring dependencies in-line with WildFly Core versions, including the upgrade to WildFly Elytron 1.7.0.Final.
Release Notes - WildFly Elytron - Version 1.7.0.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1680'>ELY-1680</a>] -         IBM, failing KeyStoreSuiteChild.testGetCertificateChainBinary
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1709'>ELY-1709</a>] -         Release WildFly Elytron 1.7.0.Final
</li>
</ul>
Release Notes - Elytron Web - Version 1.3.0.Final
</h2> …
> [WFCORE-4208] / [WFCORE-4209] / [WFCORE-4210] WildFly Elytron Component Upgrades

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/msc/main/module.xml
- `org.jboss.threads` is required by `ServiceContainerImpl` by the class constructor. This constructor is always called in wildfly-core by `BootstrapImpl` and by `HostControllerBootstrap` to register the shutdownhook. 
That means, when wildfly starts an embedded server, standalone instance or a domain, the shutdownhook is always registered, and that makes `org.jboss.threads` mandatory in `org.jboss.msc` from the point of view of wildfly. We can argue that the org.jboss.msc.Version main class declared in the module does not need it, but I think, it is irrelevant in this context.
- `javax.inject.api` and `org.jboss.vfs` are not used by jboss-msc.jar, so we can remove them
Jira issue: https://issues.jboss.org/browse/WFCORE-4202
> [WFCORE-4202] org.jboss.msc module optional dependencies issues

- core-galleon-pack/pom.xml
- core-galleon-pack/src/main/resources/configs/domain/domain.xml/config.xml
- core-galleon-pack/src/main/resources/configs/domain/model.xml
- core-galleon-pack/src/main/resources/configs/host/host-master.xml/config.xml
- core-galleon-pack/src/main/resources/configs/host/host-slave.xml/config.xml
- core-galleon-pack/src/main/resources/configs/host/host.xml/config.xml
- core-galleon-pack/src/main/resources/configs/host/model.xml
- core-galleon-pack/src/main/resources/configs/standalone/model.xml
- core-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
- core-galleon-pack/src/main/resources/feature_groups/base-security-realms.xml
- core-galleon-pack/src/main/resources/feature_groups/elytron-common.xml
- core-galleon-pack/src/main/resources/packages/cleanup.domain.data.dir/pm/wildfly/tasks.xml
- core-galleon-pack/src/main/resources/packages/cleanup.standalone.data.dir/pm/wildfly/tasks.xml
- core-galleon-pack/wildfly-feature-pack-build.xml
- pom.xml
https://issues.jboss.org/browse/WFCORE-4212
Key changes here are:
* generate-feature-specs goal merged into build-feature-pack;
* default config definitions moved from wildfly-feature-pack-build.xml to their own files (and from the generated feature-pack.xml to their own files).
> [WFCORE-4212] Upgrade to Galleon and WildFly Galleon Plugins 3.0.0.CR1

- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
Minor fixes for SuspendController
1. The Timer allocated at L103 is pointless unless timeoutMillis > 0
2. activityPaused() and timeout() can be private
3. The logging message L80-L82 is incorrect if timeoutMillis == 0
Jira issue: https://issues.jboss.org/browse/WFCORE-3905
> [WFCORE-3905] Improve SuspendController code

- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/InteractiveSecurityBuilder.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/SSLSecurityBuilder.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
- Force reload when removing key-store.
- Added test.
> Fix for WFCORE-4240, CLI, failed interactive enable-ssl commands put the server in reload state

- server/src/main/java/org/jboss/as/server/deployment/Attachments.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
- server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
https://issues.jboss.org/browse/WFCORE-4233
WARN if jboss-deployment-structure.xml excludes non-existent subsystem
> [WFCORE-4233] WARN if jboss-deployment-structure.xml excludes non-existent subsystem

- elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
https://issues.jboss.org/browse/WFCORE-4223
> [WFCORE-4223] IllegalArgumentException when add a server-ssl-sni-context with no host-context-map

- core-feature-pack/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml
Jira: https://issues.jboss.org/browse/WFCORE-4265
`<path name="com/ibm/dataaccess"/>` needs to be exported from `ibm.jdk` module, so that deployed DB2 JDBC driver can access needed classes.
In case the DB2 JDBV driver is a separate JBoss module, I think the only way to do is to add dependency to `ibm.jdk` in the module definition.
> [WFCORE-4265] Latest DB2 11.1 JDBC driver requires additional IBM JDK system dependency

- host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
- io/subsystem/src/main/java/org/wildfly/extension/io/WorkerService.java
- server/src/main/java/org/jboss/as/server/ServerService.java
https://issues.jboss.org/browse/WFCORE-1632
@gaol @dmlloyd @stuartwdouglas 
This is a continuation of the discussion of #1654, converting my experimental branch that was being looked at there into a PR.
This implements the approach discussed in the other PR of doing a shutdownNow on the xnio worker. It addresses, at least somewhat, the concern that tasks already assigned to the worker should be run by passing them off to the management executor to run.
In the end though the management executor needs to ensure tasks are finished too, so the stop logic for it also eventually does a shutdownNow, and it just discards any returned tasks. So, it's possible some tasks won't run.
The shutdown stuff is a bit kludgy in that a simple shutdown() is performed, and then a wait up to magic number 100ms …
> [WFCORE-1632] Interrupt Xnio worker tasks when the worker is stopped

- server/src/main/java/org/jboss/as/server/deployment/module/VFSResourceLoader.java
https://issues.jboss.org/browse/WFCORE-4266
> [WFCORE-4266] Support MR JAR resource loading from VFSResourceLoader

- controller/src/main/java/org/jboss/as/controller/registry/AttributeAccess.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/ClassLoadingResourceDefinition.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/GarbageCollectorResourceDefinition.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/MemoryPoolResourceDefinition.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/RuntimeResourceDefinition.java
- platform-mbean/src/main/java/org/jboss/as/platform/mbean/ThreadResourceDefinition.java
Add the COUNTER_METRIC and GAUGE_METRIC flags to AttributeAccess.Flag
enum to further specify the type of metrics when an AttributeDefinition
is registered as a Metric.
Specify the COUNTER_METRIC flag for attributes representing counters (if
the flag is absent, the metric is considered as a gauge).
JIRA: https://issues.jboss.org/browse/WFCORE-4238
> [WFCORE-4238] Add flags to categorize numerical metrics

- host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_10.java
* Do not allow more than one <socket> child in the <http-interface>
element.
* idem for <http-upgrade>
JIRA: https://issues.jboss.org/browse/WFCORE-4269
> [WFCORE-4269] Fix socket parser

- pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java
https://issues.jboss.org/browse/WFCORE-4271
Added exclusion of jboss-servlet-api_3.1 which seems not needed in wildfly-core; also this aligns it with other places in wildfly-core project (details in jira).
related wildfly PR: https://github.com/wildfly/wildfly/pull/11986
> [WFCORE-4271] Exclude transitive jboss-servlet-api_3.1 dependency

- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/suspend/web/SuspendResumeTestCase.java
We could get the server in SUSPENDING state just after unlocking the web application, which in turns makes the test fails. This patch gives the oportunity to wait a bit longer in that case to get the SUSPENDED state.
Jira issue: https://issues.jboss.org/browse/WFCORE-4274
It supersedes https://github.com/wildfly/wildfly-core/pull/3641
> [WFCORE-4274] SuspendResumeTestCase fails sometimes

- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/capability/CapabilityServiceSupport.java
- Required changes in wildfly core for WFLY-11186
- Add additional method signature to allow get an optional capability API
Jira issue: https://issues.jboss.org/browse/WFCORE-4228
> [WFCORE-4228] Add methods to the management API to get Capability Runtime API as an Optional object

- io/tests/src/test/java/org/wildfly/extension/io/IOSubsystemTestCase.java
- pom.xml
Fix for https://issues.jboss.org/browse/WFCORE-4281, upgrade threads to 2.3.3.Final in order to fix 
CLI issue with jconsole: https://issues.jboss.org/browse/WFCORE-4199
> Fix for WFCORE-4281, upgrade threads to 2.3.3.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4284
Release Notes - Elytron Web - Version 1.4.0.CR1
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELYWEB-38'>ELYWEB-38</a>] -         Upgrade WildFly Elytron to 1.8.0.CR1
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELYWEB-36'>ELYWEB-36</a>] -         ElytronHttpExchange.getRequestParameters() is prematurely readying the request.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELYWEB-37'>ELYWEB-37</a>] -         Release Elytron Web 1.4.0.CR1
</li>
</ul>
> [WFCORE-4284] Upgrade Elytron Web to 1.4.0.CR1

- server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.jboss.org/browse/WFCORE-4297 
https://issues.jboss.org/browse/WFLY-11651 depends on this PR being
merged first.  [WFLY-11651] will not compile successfully without 
the constant added in Phase.java.  JaxrsSubsystemAdd in wfly uses 
this constant.
> [WFCORE-4297] added constant for jaxrs use in deployment process

- build/pom.xml
- dist/pom.xml
- pom.xml
- testsuite/domain/pom.xml
- testsuite/elytron/pom.xml
- testsuite/layers/pom.xml
- testsuite/manualmode/pom.xml
- testsuite/patching/pom.xml
- testsuite/rbac/pom.xml
- testsuite/standalone/pom.xml
https://issues.jboss.org/browse/WFCORE-4304
In addition to upgrading the versions, in this PR I am taking the opportunity to optimize provisioning in various modules according to what is required.
In most of the provisioning configurations I am adding:
- `<record-state>false</record-state>` which indicates to galleon that the provisioning state should not be persisted in .galleon dir (simply to save a bit of time);
- `<log-time>${galleon.log.time}</log-time>` to log provisioning time which is controlled by the property and set to true. It's not a lot of noise but helps tracking how provisioning time changes over the course of development and galleon upgrades (as discussed with @bstansberry);
- `<jboss-maven-dist/>` simply to avoid unnecessary file copying while provisioning distributions …
> [WFCORE-4304] Upgrade Galleon to 3.0.1.CR2 and WFGP to 3.0.1.CR3

- elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
- elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
- elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
- elytron/src/main/resources/schema/wildfly-elytron_6_0.xsd
- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
- pom.xml
https://issues.jboss.org/browse/WFCORE-4307
https://issues.jboss.org/browse/WFCORE-4308
This PR also incorporates the changes from https://github.com/wildfly/wildfly-core/pull/3626 for a related RFE:
https://issues.jboss.org/browse/WFCORE-4058
Release Notes - WildFly Elytron - Version 1.8.0.CR2
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1650'>ELY-1650</a>] -         Automatic detection of file based KeyStore types.
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1686'>ELY-1686</a>] -         Utility to port legacy properties files into a FileSystemRealm
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1696'>ELY-1696</a>] -         Dead code in …
> [WFCORE-4307] / [WFCORE-4308] / [WFCORE-4058] WildFly Elytron Component Upgrades and related RFE

- pom.xml
The sole intention of this upgrade is to include WFMP-88 fix in wildfly core. We have some Jenkins jobs for eap-ization commits running on uppercase folder names, and we have to do some workarounds to make the job running. This upgrade will facilitate this issue.
notice the following; wildfly-full is already using 1.2.1.Final
Jira issue: https://issues.jboss.org/browse/WFCORE-4315
cc: @jamezp
> [WFCORE-4315] Upgrade the wildfly-maven-plugin to 1.2.1.Final

- controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
- server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
- server/src/main/java/org/jboss/as/server/controller/resources/ServerDeploymentResourceDefinition.java
- server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
- server/src/main/java/org/jboss/as/server/controller/resources/ServerSubDeploymentResourceDefinition.java
- server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
- server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
- server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
- server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
- server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
- testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentModulesListTestCase.java
A feature that enables a command to list the module dependencies of a specific deployment and subdeployments. 
It is included only a test case for non ear deployments. Ear deployment processors are in wildfly-full, so a new PR will be added by @zhantemirov to cover this section of the test plan.
Jira issue: https://issues.jboss.org/browse/WFCORE-4251
Analysis doc: https://github.com/wildfly/wildfly-proposals/pull/159
Community doc: https://github.com/wildfly/wildfly/pull/12041
> [WFCORE-4251] Provide ability to list module dependencies for a deployment and subdeployment

- pom.xml
- testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/LoggingTestCase.java
https://issues.jboss.org/browse/WFCORE-4317
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-213'>LOGMGR-213</a>] -         Add a System.LoggerFinder for Java 9+
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-218'>LOGMGR-218</a>] -         JBoss Logmanager is incompatibile with -Xbootclasspath and JDK 11
</li>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-236'>LOGMGR-236</a>] -         java.lang.ArrayIndexOutOfBoundsException: 76 	at org.jboss.logmanager.JDKSpecific.calculateCaller(JDKSpecific.java:112)
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/LOGMGR-210'>LOGMGR-210</a>] -         Use the StackTraceFormatter to render the stack trace for structured …
> [WFCORE-4317] Upgrade jboss-logmanager from 2.1.5.Final to 2.1.7.Final

- testsuite/layers/pom.xml
- testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
Fix for : https://issues.jboss.org/browse/WFCORE-4311
- Layers execution testing.
- Check for WFLYSRV0025 ==> success, WFLYSRV0026 ==> failure
- Other errors that could occur during startup (eg: UT005041: Cannot send advertise message on un-configured macOSX) are not checked.
- Maximum server start timeout is 1 minute (should be enough to protect us against slow test env).
- Introduce LayersTest.testExecution that will be used by Wildfly full layers test.
- Disabled maven resolution of module artefacts at runtime. Servers are now provisioned with module resources.
> Fix for WFCORE-4311, Testing of layer execution

- host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
- host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
- version/src/main/java/org/jboss/as/version/Version.java
[WFLY-4322] Bump domain management version to 10.0.0  …
* Set Version to 10.0.0 to prepare WildFly 16 release
* add KnownRelease.WILDFLY15 based on Kernel API version 9.0.0
JIRA: https://issues.jboss.org/browse/WFCORE-4322
---
[WFCORE-3997] Add HostExcludeResourceDefinition.KnownRelease items for EAP 7.2
JIRA: https://issues.jboss.org/browse/WFCORE-3997
>  [WFLY-4322][WFCORE-3997] Bump domain management version to 10.0.0

- server/src/main/java/org/jboss/as/server/deployment/module/VFSResourceLoader.java
The commit here fixes the issue noted in https://issues.jboss.org/browse/WFCORE-4298 by checking for the value of `Multi-Release` manifest attribute to be `true`.
> WFCORE-4298 Consider the value of "Multi-Release" manifest attribute

- server/src/main/resources/schema/wildfly-config_10_0.xsd
It will allow adding EAP7.2 host exclusion in the product branches
Jira issue: https://issues.jboss.org/browse/WFCORE-4328
> [WFCORE-4328] Add EAP 7.2 host exclusion enum type in Wildfly config xsd

- build/pom.xml
- dist/pom.xml
- pom.xml
- testsuite/domain/pom.xml
- testsuite/elytron/pom.xml
- testsuite/layers/pom.xml
- testsuite/manualmode/pom.xml
- testsuite/patching/pom.xml
- testsuite/rbac/pom.xml
- testsuite/standalone/pom.xml
https://issues.jboss.org/browse/WFCORE-4334
The `offline=true` added to `provision` goal is not changing anything for our builds, since all the artifacts needed to produce the dist have already been built and/or installed in the local repo by the Maven build process. This option simply makes sure that if one day Galleon needs to resolve something from a remote repo, it will fail.
> [WFCORE-4334] Upgrade to Galleon and WFGP 3.0.1.Final

- pom.xml
https://issues.jboss.org/browse/WFCORE-4343
https://issues.jboss.org/browse/WFCORE-4344
https://issues.jboss.org/browse/WFCORE-4345
No changes were made to WildFly Elytron Tool other than component upgrades to bring dependencies in-line with WildFly Core versions, including the upgrade to WildFly Elytron 1.8.0.Final.
Release Notes - WildFly Elytron - Version 1.8.0.Final
</h2>
<ul>
<li>[<a href='https://issues.jboss.org/browse/ELY-1464'>ELY-1464</a>] -         Programatic authentication should be caching the SecurityIdentity not the name of the identity
</li>
<li>[<a href='https://issues.jboss.org/browse/ELY-1677'>ELY-1677</a>] -         Elytron Bearer Token Authentication - Return a 401 on Invalid Token
</li>
<li>[<a …
> [WFCORE-4343] / [WFCORE-4344] / [ WFCORE-4345] WildFly Elytron Component Upgrades

- pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-4347
> WFCORE-4347: upgrade WildFly Maven Plugins to 2.0.0.Final

- testsuite/scripts/pom.xml
- testsuite/scripts/src/test/java/org/wildfly/scripts/test/Environment.java
- testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptProcess.java
- testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptTestCase.java
The first commit just adds a command to make the Windows PowerShell scripts more generally work. I had a case where I had an update on my local VM that broke the tests because of the execution policy.
This commit increases the timeout to 2 minutes. There was also a change to hopefully help the destroy wait to move on until the process is destroyed.
> [WFCORE-4348] Re-enable and fix Windows script tests

- pom.xml
Jira: https://issues.jboss.org/browse/WFCORE-4341
> [WFCORE-4341] Upgrade Undertow version

- core-galleon-pack/src/main/resources/layers/standalone/secure-management/layer-spec.xml
- Set elytron http-authentication factory.
- Tested with private branch org.wildfly.test.integration.microprofile.metrics.secured.MicroProfileMetricsSecuredEndpointTestCase and org.wildfly.test.integration.microprofile.health.MicroProfileHealthSecuredHTTPEndpointTestCase
> Fix for WFCORE-4354, secure-management layer doesn't secure direct http access

- server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
This fix corrects the order of some method arguments used by ModuleLoadService to follow always the pattern System, local, user dependencies.
Jira issue: https://issues.jboss.org/browse/WFCORE-4327
> [WFCORE-4327] Use correct order of method arguments in ModuleLoadService

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/AeshCommands.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandContainer.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandInvocationBuilder.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandInvocationImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandRegistry.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/HelpSupport.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/DeploymentCommand.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/operation/LegacyCommandContainer.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/operation/OperationCommandContainer.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
- cli/src/test/java/org/jboss/as/cli/impl/aesh/HelpSupportTestCase.java
- patching/src/test/java/org/jboss/as/patching/cli/PatchHelpTestCase.java
- pom.xml
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GrepTestCase.java
- Changes in CommandBuilder API.
- Commands are populated at execution time, impact legacy commands, raw operations and Command to DMR translation (for aesh based commands).
- Updated test due to change of exception message.
> Fix for WFCORE-4372, Upgrade CLI to use aesh 2.0

- core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/log4j/logmanager/main/module.xml
https://issues.jboss.org/browse/WFCORE-4373
Adding java.sql module dependency to logmanager.
> [WFCORE-4373] org.jboss.log4j.logmanager module requires java.sql module

- cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
- cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
- cli/src/main/resources/help/help.txt
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
Fix for CLI, new option to enable properties resolution, EAP7-1190
Analysis: https://github.com/wildfly/wildfly-proposals/pull/173/
No community doc,  help contains documentation of new option.
Added new option --resolve-parameter-values and test.
https://issues.jboss.org/browse/WFCORE-4305
> Fix for WFCORE-4305, CLI, new option to enable properties resolution

- cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
- cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractDeployContentCommand.java
- testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeployTestCase.java
Fix for https://issues.jboss.org/browse/WFCORE-4389
- Fixed DMR not compliant with operation-description and CLI validation rules (request must have an address).
- Added unit tests for adding and replacing deployments in batch.
- Fixed an issue discovered during testing with aesh2.0
> Fix for WFCORE-4389, CLI, deploy fails in batch when operation is validated

- domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
https://issues.jboss.org/browse/WFCORE-4363
It's unnecessary to add ErrorContextHandler for http://localhost:9990/error/ if the console is disabled.
> WFCORE-4363 No need to handle error page request if console is disabled

- remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties
Issue: https://issues.jboss.org/browse/WFCORE-4387
> [WFCORE-4387] Fix typo in remoting descriptions

- cli/src/main/java/org/jboss/as/cli/embedded/ThreadLocalContextSelector.java
- logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelector.java
- logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
- pom.xml
This commit just upgrades the log manager with a single commit to expose the [`LogContext.getLogContextSelector()`](https://issues.jboss.org/browse/LOGMGR-241) which is required for the second commit.
This commit fixes the issue where the incorrect log context could be used when creating CLI loggers and the incorrect `StdioContext` being used when CLI writes log messages.
Instead of just wrapping the current `LogContext` this wraps the CLI `ThreadLocalContextSelector` instead to ensure the correct contexts are used. I tested both the `embed-server` and `embed-host-controller` with the `jboss-cli.sh` script and the `jboss-cli-client.jar`. Log messages from CLI will now use the `jboss-cli-logging.properties` configuration (assuming that's used) and log messages from the server us the …
> [WFCORE-4359] Ensure the CLI embedded stdio and log contexts are used for CLI loggers.

- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
- controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/CapabilityRegistration.java
- controller/src/main/java/org/jboss/as/controller/capability/registry/RuntimeCapabilityRegistration.java
- controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
https://issues.jboss.org/browse/WFCORE-4376
AbstractCapability was deprecated a little over a year ago. However, because RuntimeCapability inherits most of its Capability method implementations from it, users of RuntimeCapability encounter lots of inappropriate deprecation warnings when referencing many of the non-deprecated methods from the Capability interface. This PR fixes that and any compilation errors resulting from the invocation of these methods from a raw-typed RuntimeCapability.
> WFCORE-4376 Fix deprecation warnings resulting from the improper deprecation of AbstractCapability.

- core-feature-pack/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
- elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/JdkUtils.java
- elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
- elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
- elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
https://issues.jboss.org/browse/WFCORE-4369
> [WFCORE-4369] Fixing JDK 13 test issue

- controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
- controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
https://issues.jboss.org/browse/WFCORE-4392
> [WFCORE-4392] Migrating CapabilityServiceTarget to new MSC API

- controller/src/main/java/org/jboss/as/controller/extension/ExtensionResource.java
- controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
- controller/src/main/java/org/jboss/as/controller/registry/PlaceholderResource.java
- controller/src/main/java/org/jboss/as/controller/transform/description/TransformationRule.java
https://issues.jboss.org/browse/WFCORE-4399
> WFCORE-4399 ResourceEntry implementations to not implement equals/hashCode()

- core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
This is an existing API that should have been public to allow users to populate their security realms: -
https://issues.jboss.org/browse/WFCORE-4401
> [WFCORE-4401] Make the 'org.wildfly.security.password.util' package public.

- testsuite/domain/enable-elytron.cli
- testsuite/domain/pom.xml
https://issues.jboss.org/browse/WFCORE-4325
> [WFCORE-4325] Unable to run testsuite/domain tests with -Delytron

- controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
- controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
- controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
- controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
- controller/src/main/java/org/jboss/as/controller/extension/ParallelExtensionAddHandler.java
- controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
- controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
- controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
- host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
- host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
- host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
- server/src/main/java/org/jboss/as/server/ServerService.java
https://issues.jboss.org/browse/WFCORE-3185
Instead of doing parallel boot with 1 task per extension (during extension initialization) and then 1 per subsystem (during subsystem op handling) this instead groups work into coarser grained chunks, with the number of chunks based on the number of available processors. Default setting is 1 subsystem chunk per processor, and 2 extension chunks per processor. This can be tweaked via **unsupported** system properties, _which only exist to allow us WildFly devs to experiment with different values and on different types of systems_.
On my 4-5 year old laptop this results in 8 chunks for subsystem work and 16 for extensions.
The number of threads used will be 2x the number of subsystem chunks, as the subsystem work needs separate chunks for …
> [WFCORE-3185] Run parallel boot tasks in coarser grained chunks
