domain-management/src/main/java/org/jboss/as/domain/management/audit/FileAuditLogHandlerResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/HandlerUtil.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerResourceDefinition.java
While at it I made a couple minor changes to how data is obtained during validation.
=> [WFCORE-497] Do cross-model validation in a separate step

host-controller/pom.xml, host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java, host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmOptionsBuilderFactory.java, host-controller/src/test/java/org/jboss/as/host/controller/model/jvm/JvmOptionsBuilderUnitTestCase.java, platform-mbean/src/main/java/org/jboss/as/platform/mbean/PlatformMBeanUtil.java, pom.xml, server/pom.xml
Changes apply to older JDKs as well.
=> Few JDK9 related & general build fixes

controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
1) General housekeeping -- comments and such
2) WFCORE-513 -- use the correct boot file in reload in the special cases
3) WFCORE-514 -- use the correct file for taking snapshots when we don't persist changes to the main file
=> ConfigurationFile fixes

controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
Removes the need for taking the audit logging configuration lock when
audit logging is disabled. Since that is a fair lock, it is heavy weight
when under high contention.
=> [WFCORE-491] Add fast path for disabled audit logging

server/src/main/java/org/jboss/as/server/deployment/DeploymentFullReplaceHandler.java
https://issues.jboss.org/browse/WFCORE-495
The PERSISTENT checking was removed in https://github.com/wildfly/wildfly-core/commit/673ada6dbfbf4341acff29f80772d053612343cc which fixed incorrect isRuntime() return value.
=> [WFCORE-495] don't write to config file if attribute PERSISTENT is false

server/src/main/java/org/jboss/as/server/logging/ServerLogger.java, server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
https://issues.jboss.org/browse/WFCORE-525
=> [WFCORE-525] Ability to mark a module as deprecated

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java, controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/LegacyKernelServicesImpl.java, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/host.xml, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/standalone.xml, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHeaders.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHttpHandler.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsUtil.java, host-controller/src/main/java/org/jboss/as/domain/controller/LocalHostControllerInfo.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementRemoveHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/LocalHostControllerInfoImpl.java, host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml.java, host-controller/src/main/java/org/jboss/as/host/controller/resources/HttpManagementResourceDefinition.java, host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/ReloadRequiredServerTestCase.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java, server/src/main/java/org/jboss/as/server/mgmt/HttpManagementResourceDefinition.java, server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java, server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java, server/src/main/java/org/jboss/as/server/parsing/StandaloneXml.java, server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties, server/src/main/resources/schema/wildfly-config_3_0.xsd, testsuite/shared/src/main/java/org/jboss/as/test/shared/ModelParserUtils.java
List of allowed-origins is parametrable and is filtering requests.
Security headers are set to enable authentication for all CORS requests.
Jira: https://issues.jboss.org/browse/WFCORE-302
=> [WFCORE-302] : Enable CORS

server/src/main/java/org/jboss/as/server/services/net/AbstractBindingWriteHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingFixedPortHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingInterfaceHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingMulticastAddressHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingMulticastPortHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingPortHandler.java, server/src/main/java/org/jboss/as/server/services/net/ClientMappingsHandler.java
[WFLY-4188] resolve expression values for client-mapping
"source-network" "destination-address" and "destination-port" are expression allowed attributes.
client-mappings change requires a reload operation as well.
=> [WFLY-4188] resolve expression values for client-mapping

controller/src/main/java/org/jboss/as/controller/AbstractBoottimeAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/PathAddress.java
- Add shortcut .getParent() to PathAddress
- allow also sub types of AttributeDefinition as paramter to AbstractBoottimeAddStepHandler ctor
=> Small API usabilty improvments

controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
=> [WFCORE-539] Avoid clones in read ops

server/src/main/java/org/jboss/as/server/deployment/reflect/ClassIndex.java
https://issues.jboss.org/browse/WFLY-4354
=> Wfly 4354 default ejb methods

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java
https://issues.jboss.org/browse/WFCORE-538
=> WFCORE-538: Add GZIP handler for the management endpoint

pom.xml
common-core also got new home https://github.com/jboss/jboss-common-core
=> Upgrade to jboss-common-core 2.5 series licenced under ASL

controller/src/main/java/org/jboss/as/controller/PathAddress.java, controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/operations/common/Util.java, controller/src/test/java/org/jboss/as/controller/PathAddressTestCase.java, controller/src/test/java/org/jboss/as/controller/operations/common/UtilTest.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
Allow the use of String to pass an operation address.
Jira: https://issues.jboss.org/browse/WFCORE-537
=> [WFCORE-537] : Add path support into the management API.

server/src/main/java/org/jboss/as/server/operations/SystemPropertyRemoveHandler.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
Moving SystemPropertyRemoveHandler from a RUNTIME operation to a MODEL operation to be coherent with SystemPropertyAddHandler and SystemPropertyValueWriteAttributeHandler.
Jira: https://issues.jboss.org/browse/WFCORE-545
=> [WFCORE-545] : Inconsistent stage for adding/updating/removing system properties.

core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/ExcludeCommonOperations.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java, pom.xml
Updating wildfly-legacy-test version.
Updating transformers for new versions.
Fixing some legacy transformers issues
Jira: https://issues.jboss.org/browse/WFCORE-293
=>  [WFCORE-293] : Add EAP 6.2 and 6.3 to versions tested in core-model-test.

core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/ExcludeCommonOperations.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java, pom.xml
This reverts commit c0ab0ab182eb2d3b1282c0ed96b46e6ae48bb941, reversing
changes made to 42eefaa822190c6130eeb72c4068fee6c19b685f.
=> Revert "Merge pull request #515 from ehsavoie/WFCORE-293"

core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/ExcludeCommonOperations.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java, pom.xml
Revert the #519  revert of #515 then upgrade to a fixed up legacy-test release.
=> Fix up the legacy tests stuff

core-feature-pack/src/main/resources/content/bin/jboss-cli.xml, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
BZ: https://issues.jboss.org/browse/WFCORE-562
=> [WFCORE-562] Wrong order of elements in jboss-cli.xml

controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java, controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java, controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java, controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java, controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java, controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java, controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java, controller/src/test/java/org/jboss/as/controller/test/CastAttributeOperationTestCase.java, controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsAliasesTestCase.java, controller/src/test/java/org/jboss/as/controller/test/ReadAttributeGroupTestCase.java, controller/src/test/java/org/jboss/as/controller/test/Subsystem1RootResource.java, controller/src/test/java/org/jboss/as/controller/test/TestUtils.java, controller/src/test/java/org/jboss/as/controller/test/WriteAttributeOperationTestCase.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestParser.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/access/HostAccessControlTestCase.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/host/HostModelTestCase.java, core-model-test/tests/src/test/java/org/jboss/as/core/model/test/shipped/ShippedConfigurationsModelTestCase.java, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HostModelRegistrationHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/LocalDomainControllerAddHandler.java, logging/src/main/java/org/jboss/as/logging/AsyncHandlerResourceDefinition.java, logging/src/main/java/org/jboss/as/logging/CommonAttributes.java, logging/src/main/java/org/jboss/as/logging/PatternFormatterResourceDefinition.java, logging/src/main/java/org/jboss/as/logging/SizeRotatingHandlerResourceDefinition.java, testsuite/shared/src/main/java/org/jboss/as/test/shared/ModelParserUtils.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-543
Also fix the tests affected by the improved validation. I pushed a few fixes to wildfly already, so hopefully this should pass there as well.
=> Move model validation into controller

pom.xml
https://issues.jboss.org/browse/WFCORE-563
=> WFCORE-563: Upgrade to xerces 2.11.0.SP1

pom.xml
=> Update JBoss Modules to 1.4.2.Final

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
BZ: https://issues.jboss.org/browse/WFCORE-120
=> Default File History Permissions

pom.xml
fixes WFCORE-487 Instability in RespawnHttpTestCase
=> WFCORE-487 WFCORE-576 Upgrade jboss-remoting to 4.0.8

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Since #428 seems to be rotting away ignored, I'll pull out this trivial side commit and hope it has a better fate.
=> [WFCORE-489] Use correct var

cli/src/main/resources/schema/jboss-as-cli_1_0.xsd, cli/src/main/resources/schema/jboss-as-cli_1_1.xsd, cli/src/main/resources/schema/jboss-as-cli_1_2.xsd, cli/src/main/resources/schema/jboss-as-cli_1_3.xsd, server/src/main/resources/schema/jboss-as-config_1_6.xsd
The purpose of this commit is to spot when genine differences have crept in.
=> [WFCORE-646] Cosmetic updates to schemas to bring them in-line with EAP.

controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java, controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/operations/global/AbstractCollectionHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/EnhancedSyntaxSupport.java, controller/src/main/java/org/jboss/as/controller/operations/global/ListOperations.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/WriteAttributeHandler.java, controller/src/main/java/org/jboss/as/controller/registry/AliasResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java, controller/src/test/java/org/jboss/as/controller/InterleavedSubsystemTestCase.java, controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java, controller/src/test/java/org/jboss/as/controller/operation/global/CollectionOperationsTestCase.java, controller/src/test/java/org/jboss/as/controller/operation/global/EnhancedSyntaxTestCase.java, controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java, controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java, controller/src/test/java/org/jboss/as/controller/test/ReadResourceChildOrderingTestCase.java, controller/src/test/java/org/jboss/as/controller/test/TestUtils.java, controller/src/test/java/org/jboss/as/controller/test/WildcardUnitTestCase.java, jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
https://issues.jboss.org/browse/WFCORE-460
=> [WFCORE-460 Enhanced syntax support

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerRedeploymentTestCase.java
https://issues.jboss.org/browse/WFCORE-505
I found that previous fix I made in WFCORE-505 is incomplete.
Add a test to cover the scenario.
=> Wfcore 505 test

cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/java/org/jboss/as/cli/impl/ExtensionsLoader.java, cli/src/main/resources/help/extension-commands.txt
This supercedes #599 with an additional fix to resolve a problem with the CLI embedded server that testing of 599 revealed.
=> [WFCORE-625] Error message in CLI if extension existing on the server is not present in the CLI installation

launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java, launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java, launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java, launcher/src/main/java/org/wildfly/core/launcher/VersionComparator.java
Some general clean up and checking before adding the `XX:MaxPermSize` by default.
=> Launcher changes

controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java, controller/src/main/java/org/jboss/as/controller/extension/AbstractLegacyExtension.java, controller/src/main/java/org/jboss/as/controller/interfaces/InetAddressMatchInterfaceCriteria.java, controller/src/main/java/org/jboss/as/controller/interfaces/LoopbackAddressInterfaceCriteria.java, controller/src/main/java/org/jboss/as/controller/interfaces/ParsedInterfaceCriteria.java, controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/operations/global/EnhancedSyntaxSupport.java, controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java, domain-management/src/test/java/org/jboss/as/domain/management/security/realms/InMemoryDirectoryServiceFactory.java, domain-management/src/test/java/org/jboss/as/domain/management/security/realms/InMemorySchemaPartition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractChannelOpenListenerService.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractStreamServerService.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementChannelOpenListenerService.java, server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Various updates to logger categories and use static loggers where necessary.
=> [WFCORE-656] Category and logger updates

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java, host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerManagementTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ServerAutoStartTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ServerStartFailureTestCase.java, testsuite/domain/src/test/resources/domain-configs/domain-minimal.xml, testsuite/domain/src/test/resources/domain-configs/domain-standard.xml, testsuite/domain/src/test/resources/host-configs/host-slave-failure.xml
Tracing such failures.
Jira: https://issues.jboss.org/browse/WFCORE-230
=> [WFCORE-230] : Failure by ProcessController to launch a server vm is not logged

controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java
This reverts commit f65bfc8eaf9af2c082f2277a6f17fb0da01907b3.
needs https://github.com/wildfly/wildfly/pull/7397 to be merged first
=> Revert "Add backward compatibilty for wildfly full"

server/src/main/java/org/jboss/as/server/deployment/Phase.java
I'm sorry. I copied the wrong line the first time and didn't catch the `REGISTER` part of the name.
=> Use the correct name for the JBoss all batch priority.

core-feature-pack/src/main/resources/content/bin/domain.ps1, core-feature-pack/src/main/resources/content/bin/jboss-cli.ps1, core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1, core-feature-pack/src/main/resources/content/bin/standalone.ps1
far from perfect, but on a good way to replace our ratchet .bat scripts
It does passes much better chunk of scripts testsuite than batch scripts do.
=> update powershell scripts to be more in line of others

server/src/main/java/org/jboss/as/server/deployment/service/ServiceActivatorProcessor.java
=> Set the TCCL during ServiceActivatorProcessor.

controller/src/main/java/org/jboss/as/controller/transform/description/AbstractTransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/ChainedTransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/DiscardTransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/DynamicDiscardPolicy.java, controller/src/main/java/org/jboss/as/controller/transform/description/RejectTransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/ResourceTransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/ResourceTransformationDescriptionBuilderImpl.java, controller/src/main/java/org/jboss/as/controller/transform/description/TransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/TransformingDescription.java, controller/src/test/java/org/jboss/as/controller/transform/description/BasicResourceTestCase.java
should be discarded or rejected.
https://issues.jboss.org/browse/WFCORE-679
=> [WFCORE-679] Be able to check at runtime whether resource transformation

remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformersTestCase.java
I did this with the github editor, let's hope it works!
=> WFCORE-674 ignore RemotingSubsystemTransformersTestCase.java

host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementRemoveHandler.java, server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Updated with context.getServiceRegistry(true)
=> WFCORE-678 console-enabled="false" does not work in domain mode

core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, server/src/main/java/org/jboss/as/server/ApplicationServerService.java, server/src/main/java/org/jboss/as/server/logging/ServerLogger.java, server/src/main/java/org/jboss/as/server/services/security/RuntimeVaultReader.java, server/src/main/resources/META-INF/services/org.jboss.as.server.services.security.AbstractVaultReader
Moving RuntimeVaultReader from WildFly to WildFly-Core
1.x variant of #679
=> [WFCORE-114] : Get RuntimeVaultReader into WildFly Core

cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerFactory.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandAloneServerFactory.java
=> [WFCORE-677] Tighten up the EmbeddedServerFactory API

domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesFileLoader.java
Upstream PR https://github.com/wildfly/wildfly-core/pull/692
=> [WFCORE-675] Prevent existing disabled accounts from being dropped from the properties file.

pom.xml
=> [WFCORE-689] Upgrade to Remoting JMX 2.0.1.Final

pom.xml
This version was built with JDK7
=> Upgrade PicketBox to 4.9.1.Final

controller-client/src/main/java/org/jboss/as/controller/client/helpers/Operations.java
Just a minor update to the `Operations` helper to create operation addresses.
=> Add the ability to create addresses with the operations helper.

remoting/subsystem/src/main/java/org/jboss/as/remoting/Namespace.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem12Parser.java, remoting/subsystem/src/main/resources/schema/jboss-as-remoting_1_2.xsd, remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java, remoting/tests/src/test/resources/org/jboss/as/remoting/remoting12-with-connector.xml
Porting jboss-as-remoting_1_2.xsd to WildFly Core plus providing test case
=> [WFCORE-651] Porting jboss-as-remoting_1_2.xsd to WildFly Core

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java, controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java, controller/src/main/java/org/jboss/as/controller/operations/global/QueryOperationHandler.java, controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties, controller/src/test/java/org/jboss/as/controller/access/rbac/FilteredReadResourceTestCase.java, controller/src/test/java/org/jboss/as/controller/access/rbac/ReadOperationNamesRbacTestCase.java, controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java, controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java, controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsTestCase.java, host-controller/src/main/java/org/jboss/as/host/controller/HostModelUtil.java, server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
Also includes:
- https://issues.jboss.org/browse/WFCORE-510 
- https://issues.jboss.org/browse/WFCORE-612
- https://issues.jboss.org/browse/WFCORE-287
=> WFCORE-287: Provide an operation to execute domain wide queries on the server side

controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java, logging/src/main/java/org/jboss/as/logging/CommonAttributes.java
I'm going to add a "Hold" label to this as it should have some unit tests added. But I want to see the pull player test results.
=> [WFCORE-703] Properly resolve fields of OBJECT attributes and elements of complex LIST attributes

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/transform/TransformersLogger.java, controller/src/main/java/org/jboss/as/controller/transform/description/TransformingDescription.java
Kabir, maybe something like this then?
=> DISCARD_AND_WARN claims to reject instead of discard

controller/src/main/java/org/jboss/as/controller/transform/ContextAttachments.java, controller/src/main/java/org/jboss/as/controller/transform/TransformerOperationAttachment.java
Kabir, one more minor thing (i don't need to use detach).
=> fix infinite recursion on TransformerOperationAttachment#detach; cleaup

server/src/main/java/org/jboss/as/server/deployment/jbossallxml/JBossAllXmlParserRegisteringProcessor.java
Useful when registering parsers for multiple versions of a particular schema
=> Add builder for JBossAllXmlParserRegisteringProcessor

server/src/main/java/org/jboss/as/server/ServerService.java
=> WFCORE-749 Add SELF_CONTAINED to ServerService.getProcessType()

controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
=> minor AttributeDefinition#marshallAsElement() javadoc fix

host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-762
=> [WFCORE-762] Proper descriptions for clone operation

controller/src/main/java/org/jboss/as/controller/AttributeParser.java, controller/src/test/java/org/jboss/as/controller/SimpleListAttributeDefinitionUnitTestCase.java
https://issues.jboss.org/browse/WFCORE-763
Upstream PR: https://github.com/wildfly/wildfly-core/pull/812
=> [1.x] WFCORE-763 Persisting an empty list [] gets read as a list with empty string [""] resulting in IllegalArgumentException

pom.xml
Already merged to master https://github.com/wildfly/wildfly-core/pull/806
=> [1.x] Upgrade jboss-classfilewriter to 1.1.2.Final

README.md
current build need java 8, rather than java 7
=> Update README.md (current build need java 8)

controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java, controller/src/test/java/org/jboss/as/controller/test/OrderedChildResourceTestCase.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOrderedChildResourceSyncModelTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/OrderedChildResourceExtension.java
As Brian points out on the PR comment referenced in the description of https://issues.jboss.org/browse/WFCORE-767.
=> [WFCORE-767] Introduce parameters object for SimpleResourceDefinition

controller/src/main/java/org/jboss/as/controller/OperationContext.java, controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java, controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java, controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java, host-controller/src/main/java/org/jboss/as/host/controller/resources/HttpManagementResourceDefinition.java, host-controller/src/main/java/org/jboss/as/host/controller/resources/NativeManagementResourceDefinition.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java, io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java, io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java, io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java, jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRootResource.java, jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorResource.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemRootResource.java, server/src/main/java/org/jboss/as/server/mgmt/HttpManagementResourceDefinition.java, server/src/main/java/org/jboss/as/server/mgmt/NativeManagementResourceDefinition.java
This also includes the commit from #803 as this change is to code modified by that commit.
=> [WFCORE-772] Rename capabilities provided by extensions

controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java, controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/capability/registry/CapabilityContext.java, controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/test/java/org/jboss/as/controller/SocketCapabilityResolutionUnitTestCase.java, host-controller/src/main/java/org/jboss/as/domain/controller/resources/SocketBindingResourceDefinition.java, network/src/main/java/org/jboss/as/network/OutboundSocketBinding.java, network/src/main/java/org/jboss/as/network/SocketBinding.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractOutboundConnectionResourceDefinition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorAdd.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorRemove.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionAdd.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionResourceDefinition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java, server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java, server/src/main/java/org/jboss/as/server/services/net/BindingRemoveHandler.java, server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java, server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingResourceDefinition.java, server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingResourceDefinition.java, server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java, server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingResourceDefinition.java, server/src/main/java/org/jboss/as/server/services/net/SocketBindingAddHandler.java, server/src/main/java/org/jboss/as/server/services/net/SocketBindingRemoveHandler.java
This also includes the commit from #803 and the commit from #824.
=> [WFCORE-750] Capabilities/requirements for socket bindings

controller/src/main/java/org/jboss/as/controller/OperationContext.java, controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java, controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java, controller/src/main/java/org/jboss/as/controller/capability/CapabilityServiceSupport.java, controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java, server/src/main/java/org/jboss/as/server/deployment/Attachments.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java, server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java, server/src/main/java/org/jboss/as/server/deployment/SubDeploymentProcessor.java, server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
This builds on #856, which resolves some of the issues discussed at http://lists.jboss.org/pipermail/wildfly-dev/2015-June/004159.html.
=> [WFCORE-781] Add ability to use capability-provided integrations from… … services and DUPs

cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
https://issues.jboss.org/browse/WFCORE-783
Also fixed a problem with the timeout argument not overriding the default or file config timeout value.
=> Errors on CLI server reload reconnection

server/src/main/java/org/jboss/as/server/deployment/Phase.java, server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java, server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java, server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java, server/src/main/java/org/jboss/as/server/deployment/module/descriptor/ParseResult.java, server/src/main/resources/schema/jboss-deployment-structure-1_3.xsd
Within jboss-deployment-structure.xml, add a convenient way to cascade ear deployment exclusions to sub-deployments.  This is the initial commit.
=> WFCORE-648 Ear exclusions cascaded to sub-deployments

pom.xml, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
=> Use jboss parent 19 & newer checkstyle to make build work on JDK9

host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java, server/src/main/java/org/jboss/as/server/controller/descriptions/ServerDescriptions.java, server/src/main/java/org/jboss/as/server/controller/resources/ModuleInfoHandler.java, server/src/main/java/org/jboss/as/server/controller/resources/ModuleLoadingResourceDefinition.java, server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java, server/src/main/java/org/jboss/as/server/logging/ServerLogger.java, server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-570
=> WFCORE-570 Provide ability to display module dependencies via mgmt API

controller/src/main/java/org/jboss/as/controller/transform/description/AttributeConverter.java
this is just copy of org.jboss.as.clustering.controller.transform.DefaultValueAttributeConverter 
tnx to @pferraro
=> Add DefaultValueAttributeConverter to core

cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
https://issues.jboss.org/browse/WFCORE-755
=> [WFCORE-755] correctly parse --timeout on embed-server

server/src/main/java/org/jboss/as/server/services/security/RuntimeVaultReader.java
Adapted for WildFly Core from https://github.com/martinschaef/wildfly/commit/37cdbad3e8194334ebb01301cc703039b96d806a
=> Fix wrong index. Thanks, Martin Schaef.

controller/src/main/java/org/jboss/as/controller/AbstractBoottimeAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/ModelOnlyAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/ReloadRequiredAddStepHandler.java
https://issues.jboss.org/browse/WFCORE-824
=> [WFCORE-824] Add parameters object constructor to more add handlers

server/src/main/java/org/jboss/as/server/SelfContainedContainer.java
additional ServiceActivators to the SelfContainedContainer.
=> Add parameter (with another method signature matching original) to pass

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
tnx @heiko-braun for spotting this one.
=> WFCORE-805 fix typo

controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java, controller/src/main/java/org/jboss/as/controller/AttributeMarshallers.java, controller/src/main/java/org/jboss/as/controller/AttributeParser.java, controller/src/main/java/org/jboss/as/controller/AttributeParsers.java, controller/src/main/java/org/jboss/as/controller/DefaultAttributeMarshaller.java, controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java, controller/src/main/java/org/jboss/as/controller/PropertiesAttributeDefinition.java, controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java, controller/src/test/resources/org/jboss/as/controller/persistence/elements.xml, controller/src/test/resources/org/jboss/as/controller/persistence/mail-parser.xml, controller/src/test/resources/org/jboss/as/controller/persistence/orb-subsystem.xml, controller/src/test/resources/org/jboss/as/controller/persistence/server-complex-attribute.xml, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemXMLPersister.java, remoting/subsystem/src/main/resources/subsystem-templates/remoting.xml
WFCORE-809 Can not parse an ObjectListAttributeDefinition of a PersistentResourceDefinition
WFCORE-691 introduce general parsing support for attributes that marshall as elements
WFCORE-691 Can not parse a wrapped properties attribute inside a group
needs https://github.com/wildfly/wildfly/pull/7790 to be merged first
=> Improve parser to support properly persiting / parsing of multi element attributes

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Jira: https://issues.jboss.org/browse/WFCORE-854
=> CLI 'set' variables fix

pom.xml
Reverts wildfly/wildfly-core#930
=> Revert "XNIO 3.4.0.Beta1"

testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ConfigurationChangesHistoryTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ConfigurationChangesHistoryTestCase.java
update Configuration change notification tests - add some read operations, write operation with FAILED status, invalid write operation
https://issues.jboss.org/browse/WFCORE-671
=> WFCORE-671 - update tests for RFE ConfigurationChangeNotifications

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
https://issues.jboss.org/browse/WFCORE-863
=> Removing repeated disconnected messages.

cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java, cli/src/main/java/org/jboss/as/cli/embedded/EmbeddedControllerHandlerRegistrar.java, cli/src/main/java/org/jboss/as/cli/embedded/EmbeddedServerLaunch.java, cli/src/main/java/org/jboss/as/cli/embedded/StopEmbeddedHostControllerHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java, controller/src/main/java/org/jboss/as/controller/ProcessType.java, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/embedded/main/module.xml, embedded/pom.xml, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerFactory.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java, embedded/src/main/java/org/wildfly/core/embedded/HostController.java, host-controller/pom.xml, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/Main.java, host-controller/src/main/java/org/jboss/as/host/controller/ProcessControllerConnectionNoop.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementRemoveHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/NativeManagementAddHandler.java
Provides embed-host-controller command in CLI to start an offline host controller. (Supercedes #948)
=> WFCORE-585 Offline CLI for a Host Controller

patching/src/main/resources/help/patch.txt
=> cli --help content for https://issues.jboss.org/browse/WFCORE-830

cli/src/main/java/org/jboss/as/cli/embedded/StopEmbeddedHostControllerHandler.java
Embedded server gets broken after operation on embedded host controller
=> WFCORE-881

io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
- no transformers and model version bump, as attribute was unable to be set in current scenario
=> Remove unused attribute in IO subsystem

pom.xml
=> Upgrade PicketBox to 4.9.3.Final

pom.xml
Reverts wildfly/wildfly-core#981
=> Revert "Undertow update requires 3.4.0.Beta1"

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, pom.xml
History File: https://issues.jboss.org/browse/WFCORE-791
Redirection: https://issues.jboss.org/browse/WFCORE-877
The minor CLI change is associated with the redirection handling change in AESH.
=> Upgrading AESH to solve issues with the history file and redirection handling

controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
This is an alternative to https://github.com/wildfly/wildfly-core/pull/982. If this one is merged, that one should be closed.
=> [WFCORE-873] Remove unused checkAlias

server/src/main/java/org/jboss/as/server/ServerEnvironment.java
Remoting services require it to be set
=> Set the controllerTempDir for Self Contained mode

pom.xml
- Apache http client
- common-metadata
=> Sync component version with wildfly full

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java, controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java, controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java, controller/src/test/java/org/jboss/as/controller/MetricsUndefinedValueUnitTestCase.java, controller/src/test/java/org/jboss/as/controller/test/TestUtils.java, server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java, threads/src/main/java/org/jboss/as/threads/PoolAttributeDefinitions.java, threads/src/main/java/org/jboss/as/threads/ThreadPoolMetricsHandler.java, threads/src/main/java/org/jboss/as/threads/ThreadsExtension.java
=> Rebased version of pull request #1000

remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java, remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformersTestCase.java
https://issues.jboss.org/browse/WFCORE-943
=> [WFCORE-943] Add remoting transformers for EAP 6.4.0

pom.xml
This PR also contains commits to bring logging tools and wildfly common up to the versions Elytron was built against.
=> [WFCORE-947] Upgrade to WildFly Elytron 1.0.0.Final

pom.xml
- it includes improvments for loading from maven repository
=> Update jboss-modules to 1.4.4.Final

controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java, controller/src/main/java/org/jboss/as/controller/capability/registry/CapabilityId.java, controller/src/main/java/org/jboss/as/controller/capability/registry/CapabilityRegistration.java, host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HostModelRegistrationHandler.java, server/src/main/java/org/jboss/as/server/ServerService.java, server/src/main/java/org/jboss/as/server/controller/resources/CapabilityRegistryResourceDefinition.java, server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
1) WFCORE-961 -- get stable sorting of the data
2) Disable exposing this for WF 10, pending fix of WFCORE-960 and API discussions with the HAL team.
=> CapabilityRegistry management view fixes

controller/src/main/java/org/jboss/as/controller/operations/global/AbstractCollectionHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/WriteAttributeHandler.java, controller/src/test/java/org/jboss/as/controller/operation/global/CollectionOperationsTestCase.java
Make sure the correct data is used, and that the steps occur at the correct time.
=> [WFCORE-967][WFCORE-968] Data visibility fixes in composite ops

controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java, controller/src/main/java/org/jboss/as/controller/AttributeParser.java, threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolResourceDefinition.java, threads/src/main/java/org/jboss/as/threads/KeepAliveTimeAttributeDefinition.java, threads/src/main/java/org/jboss/as/threads/Namespace.java, threads/src/main/java/org/jboss/as/threads/PoolAttributeDefinitions.java, threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolResourceDefinition.java, threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolResourceDefinition.java, threads/src/main/java/org/jboss/as/threads/ThreadFactoryAdd.java, threads/src/main/java/org/jboss/as/threads/ThreadFactoryResourceDefinition.java, threads/src/main/java/org/jboss/as/threads/ThreadSubsystemResourceDefinition.java, threads/src/main/java/org/jboss/as/threads/ThreadsExtension.java, threads/src/main/java/org/jboss/as/threads/ThreadsParser.java, threads/src/main/java/org/jboss/as/threads/ThreadsParser2_0.java, threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolResourceDefinition.java, threads/src/main/resources/schema/wildfly-threads_2_0.xsd, threads/src/test/java/org/jboss/as/threads/ThreadsSubsystem11TestCase.java, threads/src/test/java/org/jboss/as/threads/ThreadsSubsystemParsingTestCase.java, threads/src/test/resources/org/jboss/as/threads/threads-subsystem-2_0.xml
this makes it easier for inclusion by other subsystems that use resources from threads.
this version doesn't break wildfly-full
=> Introduce threads xsd 2.0 which is using PRDefinition and new parsers

controller/src/main/java/org/jboss/as/controller/transform/TransformationTarget.java, controller/src/main/java/org/jboss/as/controller/transform/TransformationTargetImpl.java, controller/src/test/java/org/jboss/as/controller/test/OperationTransformationTestCase.java, controller/src/test/java/org/jboss/as/controller/transform/description/AttributesTestCase.java, controller/src/test/java/org/jboss/as/controller/transform/description/BasicResourceTestCase.java, controller/src/test/java/org/jboss/as/controller/transform/description/ChainedOperationBuilderTestCase.java, controller/src/test/java/org/jboss/as/controller/transform/description/ChainedResourceBuilderTestCase.java, controller/src/test/java/org/jboss/as/controller/transform/description/ChildRedirectTestCase.java, controller/src/test/java/org/jboss/as/controller/transform/description/RecursiveDiscardAndRemoveTestCase.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/MainKernelServicesImpl.java, host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/FetchMissingConfigurationHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/ProfileCloneHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainModelHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainModelUtil.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncDomainModelOperationHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncServerGroupOperationHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java, host-controller/src/main/java/org/jboss/as/domain/controller/resources/ProfileResourceDefinition.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryImpl.java, host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOrderedChildResourceSyncModelTestCase.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/ReadMasterDomainModelHandlerTestCase.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/ReadTransformedResourceOperation.java
Replaces #1063 fixing the issue in my comment there.
=> Tweak to pull request #1063

controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
Adding a simple test to check that all is now clear.
Jira: https://issues.jboss.org/browse/WFCORE-980
=> [WFCORE-980]:  The capability registry fails to rollback properly

embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java, host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/Main.java
@bstansberry please let me know if this isn't what you had in mind. This just keeps the change contained to the host-controller.
=> [WFCORE-939] Use appropriate launch-type value for the embedded-host-controller

server/src/main/java/org/jboss/as/server/logging/ServerLogger.java, server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
=> Log given timeout when server is suspended

cli/src/main/resources/help/embed-host-controller.txt, cli/src/main/resources/help/embed-server.txt, cli/src/main/resources/help/stop-embedded-host-controller.txt
Add help files for embed-host-controller and stop-embedded-host-controller CLI commands.
=> WFCORE-930 help files for embedded host controller

pom.xml
Fixes possible deadlock condition on shutdown.
=> Remoting 4.0.14.Final

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DefaultDeploymentOperations.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/logging/DeploymentScannerLogger.java
https://issues.jboss.org/browse/WFCORE-1014
=> [WFCORE-1014] ensure model operation is a success before using its result in a deployment scan

pom.xml
=> https://issues.jboss.org/browse/WFCORE-751 jansi upgrade to 1.11

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HcExtensionAndSubsystemManagementTestCase.java
1) Remove IDE warns
2) Always clean up
3) Make test's reload of HC's more robust
=> Tighten up HcExtensionAndSubsystemManagementTestCase

host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/OperationSlaveStepHandler.java
https://issues.jboss.org/browse/WFCORE-1034 (blocks https://issues.jboss.org/browse/WFLY-5290)
=> [WFCORE-1034]  get proper alias entry for 2-step operations

controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
https://issues.jboss.org/browse/WFCORE-832
=> [WFCORE-832] Add access control exceptions for non-existent resources

network/src/main/java/org/jboss/as/network/ManagedDatagramSocketBinding.java, network/src/main/java/org/jboss/as/network/ManagedMulticastSocketBinding.java
https://issues.jboss.org/browse/WFCORE-1033
which blocks https://issues.jboss.org/browse/WFLY-5449
=> WFCORE-1033 NPE in ManagedDatagramSocketBinding & ManagedMulticastSocketBinding

cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java
This reverts the validation that was added in commit e594336c25290fca12eff08be562b5c1e7b26e17
=> [WFCORE-1038] Remove required parameter validation as that is handled server side.

controller/src/main/java/org/jboss/as/controller/audit/SyslogAuditLogHandler.java, domain-management/src/test/java/org/jboss/as/domain/management/security/auditlog/AbstractAuditLogHandlerTestCase.java, pom.xml
Contains only a few minor changes. Two bug fixes and two performance changes. https://github.com/jboss-logging/jboss-logmanager/compare/2.0.0.Final...jamezp:2.0.2.Final
=> [WFCORE-1026] Upgrade jboss-logmanager from 2.0.0.Final to 2.0.3.Final

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
Taking advantage of notifications to have a coherent state of deployments using scanner and the CLI.
Jira: https://issues.jboss.org/browse/WFLY-5474
=> [WFLY-5474]: exploded jsp is not deployed after server reload.

controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
- takes capabilites defined on resource into account
=> Minor api improvment for working with capabilites

embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java, embedded/src/test/java/org/wildfly/core/embedded/EmbeddedServerFactorySetupUnitTestCase.java
- also use as much Path api as possible to make sure none of file IO errors are hidden.
=> WFCORE-1048 IOException from EmbeddedServerFactorySetupUnitTestCase on windows

domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesFileLoader.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserPropertiesFileLoader.java
=> [WFCORE-1071] Clean up the username when manually parsed from the properties file to compensate for escaped characters.

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
Since I couldn't find anything in the logs except that the failing deployment still exists i've added more traces and set the deployment logger to debug for this test.
Jira: https://issues.jboss.org/browse/WFCORE-1074
=> [WFCORE-1074]:  Intermittent failure in DeploymentScannerUnitTestCase.

cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java, cli/src/main/resources/help/reload.txt, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
Caused by reload dropping --admin-only
=> WFCORE-993 fix embedded HC crash 

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
=> Only validateCapabilites() after a write has occured, not on a read

controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/AliasResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java, controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java
This also includes the WFCORE-1086 commit from #1209. They are really kind of a pair, but I believe WFCORE-1087 is a less critical issue so I'm submitting this separate PR in case we only want 1086.
=> [WFCORE-1087] Resolve ordered child types properly from override MRRs

pom.xml
https://issues.jboss.org/browse/WFCORE-1118
https://issues.jboss.org/browse/ELY-354
https://issues.jboss.org/browse/JBEAP-714
=> [WFCORE-1118] Upgrade to WildFly Elytron 1.0.2.Final

deployment-repository/src/main/java/org/jboss/as/repository/ContentRepository.java, deployment-repository/src/main/java/org/jboss/as/repository/logging/DeploymentRepositoryLogger.java
Checking that the array is not null.
Jira: https://issues.jboss.org/browse/WFCORE-1138
=> [WFCORE-1138]: Operation ("clean-obsolete-content") failed NPE.

pom.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1223081
=> Upgrade to vfs 3.2.10.Final to address BZ#1223081

core-feature-pack/src/main/resources/configuration/host/host-master.xml, core-feature-pack/src/main/resources/configuration/host/host-slave.xml, core-feature-pack/src/main/resources/configuration/host/host.xml
EAP variant: https://issues.jboss.org/browse/JBEAP-1970
=> [WFCORE-1151] Remove ineffective permgen settings

server/src/main/java/org/jboss/as/server/deployment/module/TempFileProviderService.java
https://issues.jboss.org/browse/WFCORE-1093
=> [WFCORE-1093] TempFileProviderService threads consume high CPU

cli/src/main/java/org/jboss/as/cli/gui/ConnectDialog.java
Downstream: https://issues.jboss.org/browse/JBEAP-1801
=> WFCORE-1143 Cancel button in JConsole do nothing

pom.xml
https://issues.jboss.org/browse/WFLY-3909
=> [WFLY-3909] PicketBox upgrade to 4.9.4.Final

controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
Downstream: https://issues.jboss.org/browse/JBEAP-2069
=> [WFCORE-1168] Use the correct var in null check

controller/src/main/java/org/jboss/as/controller/transform/CompositeOperationTransformer.java, controller/src/test/java/org/jboss/as/controller/transform/description/ChildRedirectTestCase.java
addresses the same as TransformersImpl.transformOperation()
https://issues.jboss.org/browse/WFCORE-1166
Once tests pass, I will create the downstream PR
Downstream JIRA: https://issues.jboss.org/browse/JBEAP-2029
=> [WFCORE-1166] Make composite operation transformer transform path

controller/src/main/java/org/jboss/as/controller/transform/description/ResourceTransformationDescriptionBuilder.java, controller/src/main/java/org/jboss/as/controller/transform/description/ResourceTransformationDescriptionBuilderImpl.java, controller/src/test/java/org/jboss/as/controller/transform/description/BasicResourceTestCase.java
https://issues.jboss.org/browse/WFCORE-1162
Apparently this is needed for JBEAP, but @pferraro needs to shed some light on that
=> [WFCORE-1162] DynamicDiscardPolicy for child redirection

pom.xml
https://issues.jboss.org/browse/WFCORE-1036
=> Update XNIO and Remoting

pom.xml
Downstream: https://issues.jboss.org/browse/JBEAP-1899
=> WFCORE-1181 Upgrade VFS to 3.2.11.Final

pom.xml, testsuite/shared/pom.xml, testsuite/shared/src/main/java/org/jboss/as/test/syslogserver/TLSSyslogServer.java
JIRA: https://issues.jboss.org/browse/WFCORE-1095
EAP JIRA: https://issues.jboss.org/browse/JBEAP-1760
=> [WFCORE-1095] Remove bouncycastle dependency

domain-management/src/main/java/org/jboss/as/domain/management/security/LdapGroupSearcherFactory.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityActions.java
upstream: Wildfly: https://issues.jboss.org/browse/WFCORE-1202
wildfly/wildfly-core#1306
downstream: EAP 7: https://issues.jboss.org/browse/JBEAP-2320
way-downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1196343
https://github.com/jbossas/jboss-eap/pull/2654
=> [bz-1196343] LDAP authentication/authorization fails due to making unneeded role lookup requests

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, server/src/main/java/org/jboss/as/server/parsing/ExtensionHandler.java, server/src/main/java/org/jboss/as/server/parsing/StandaloneXml.java, server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_4.java, server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_Legacy.java
Replaces #1273 just to fix a merge confilct in ControllerLogger that I get when trying to merge this together with a bunch of other PRs.
=> WFCORE-1163: Introduce ExtensionHandler API

network/src/main/java/org/jboss/as/network/SocketBindingManager.java, network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
https://issues.jboss.org/browse/WFCORE-1292
See jira for details.
=> WFCORE-1292 SocketBindingManager.createMulticast/DatagramSocket(...) variants needed for unbound sockets

logging/src/main/java/org/jboss/as/logging/CustomFormatterResourceDefinition.java
Checking the effective used class before updating the runtime configuration from the model.
Jira: https://issues.jboss.org/browse/WFCORE-1273
=> [WFCORE-1273]: Can not add property after change of class in custom log formatter.

pom.xml
Upgrade aesh to 0.66.3
https://issues.jboss.org/browse/WFCORE-1277
=> Upgrade aesh to 0.66.3 to fix WFCORE-1277

cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
JIRA: https://issues.jboss.org/browse/WFCORE-1297
=> [WFCORE-1297] deploy --url command creates invalid deployment

pom.xml
JIRA: https://issues.jboss.org/browse/WFCORE-1390
comp. JIRA: https://issues.jboss.org/browse/JBEAP-364
=> [WFCORE-1390]  upgrade PicketBox to 4.9.5.Final

host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/SocketBindingGroupTransformers.java, host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_Legacy.java, server/src/main/resources/schema/jboss-as-config_1_8.xsd
:warning: As this is a forward port it should only be merged once included in a previous product release.
=> [WFCORE-1378] Forward port version 1.8 of the management schema.

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
=> WFCORE-1406 CLI client freezes for undefined security realm

domain-management/src/main/java/org/jboss/as/domain/management/ConfigurationChangeResourceDefinition.java, testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ConfigurationChangesHistoryTestCase.java
Checking read-access to the operation address parent
Jira: https://issues.jboss.org/browse/WFCORE-1435
=> [WFCORE-1435]:  Users with low privileges can see logged operations they shouldn't be able to see

domain-management/src/main/java/org/jboss/as/domain/management/security/FileTrustManagerService.java
@darranl please approve. I'll backport to EAP now just to save time in case this looks ok.
I have no strong feeling about the property name, other than it should start with jboss.as.
=> [WFCORE-1437] Allow disabling dynamic trustmanager via system property

core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
Note that this issue also related to the [BZ1265740](https://bugzilla.redhat.com/show_bug.cgi?id=1265740)
=> WFLY-5645 - Use script name for file related to Wildfly to allow multiple instances easily

controller/src/test/java/org/jboss/as/controller/ModelControllerClientTestCase.java, controller/src/test/java/org/jboss/as/controller/test/RemoteProxyControllerProtocolTestCase.java, platform-mbean/src/test/java/org/jboss/as/platform/mbean/PlatformMBeanResourceUnitTestCase.java, server/src/test/java/org/jboss/as/server/deployment/DeploymentAddHandlerTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadsTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerShutdownTestCase.java, testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/Jmx2ndInterfaceStandardRolesBasicTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpPostMgmtOpsTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ValidateOperationOperationTestCase.java
Drop some tests, fix some, improve the description on why some are ignored.
=> Do some housekeeping on @Ignored tests in core

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
Adding a simple test to cover this.
Jira: https://issues.jboss.org/browse/WFCORE-1156
=> [WFCORE-1156]: Coverage of the fact that adding a scanner results in a scan run.

host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
Put the call where people looking for it will find it.
=> Move platform mbean resource registration to registerChildren

controller/src/main/java/org/jboss/as/controller/transform/ResourceTransformationContextImpl.java
=> [WFCORE-1270] Get some more information|

host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ServerGroupDeploymentAddHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ServerGroupDeploymentDeployHandler.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
Checking the unicity of the runtime name when deploying a deployment.
Jira: https://issues.jboss.org/browse/WFCORE-1246
=> [WFCORE-1246]: System allows enabling two applications with same runtime-name

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/SlaveReconnectTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1306
=> [WFCORE-1306] SlaveReconnectTestCase fails on slow systems

cli/src/main/java/org/jboss/as/cli/Util.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadChildrenNamesHandler.java, controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties, controller/src/test/java/org/jboss/as/controller/test/SingletonResourceTestCase.java
Adding option to have the allowed names of singletons for read-children-names operation.
Jira: https://issues.jboss.org/browse/WFCORE-971
=> [WFCORE-971]: Autocomplete not working for ha-policy names

controller/src/main/java/org/jboss/as/controller/ConfigurationChangesCollector.java
Fixing bug by using the stored date.
Jira: https://issues.jboss.org/browse/WFCORE-1370
=> [WFCORE-1370]: All configuration changes have the same operation date.

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerProxy.java
https://issues.jboss.org/browse/WFCORE-1343 - Fix for memory leak in HostController.
=> WFCORE-1343 HostController memory leak fix; back port of WFCORE-992

core-feature-pack/src/main/resources/configuration/host/host-master.xml, core-feature-pack/src/main/resources/configuration/host/host-slave.xml, core-feature-pack/src/main/resources/configuration/host/host.xml, core-feature-pack/src/main/resources/configuration/standalone/template.xml
Note this has no impact on full, which overrides these files. For full see https://issues.jboss.org/browse/WFLY-5828
=> [WFCORE-1342] Fix attribute order in templates

server/src/main/java/org/jboss/as/server/controller/resources/ModuleInfoHandler.java, server/src/main/java/org/jboss/as/server/controller/resources/ModuleLoadingResourceDefinition.java
Jira issue https://issues.jboss.org/browse/WFCORE-683
=> [WFCORE-683]: Wrong exception handling in ModuleLoadingResourceDefinition and use of jboss-module instead of reflection to get resource paths 

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractSyslogReconnectionTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/ReconnectSyslogServerTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/SyslogIsNotAvailableDuringServerBootTestCase.java, testsuite/shared/src/main/java/org/jboss/as/test/syslogserver/BlockedAllProtocolsSyslogServerEventHandler.java
Jira: https://issues.jboss.org/browse/WFCORE-1407
Test cases for: https://issues.jboss.org/browse/LOGMGR-123
=> [WFCORE-1407] Added test coverage for syslog reconnection

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/XmlCompletionScanner.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/logging/DeploymentScannerLogger.java, deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/XmlCompletionScannerTest.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ResponseStreamTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ManagementOpTimeoutTestCase.java, testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ConfigurationChangesHistoryTestCase.java, testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ValidateAddressOrOperationTestCase.java
Fixing tests not to check for i18n content in description.
Jira: https://issues.jboss.org/browse/WFCORE-1439
=> [WFCORE-1439]:  Allow for testsuite to pass on French OS.

core-feature-pack/src/main/resources/configuration/host/host-master.xml, core-feature-pack/src/main/resources/configuration/host/host-slave.xml, core-feature-pack/src/main/resources/configuration/host/host.xml
Jira: https://issues.jboss.org/browse/WFCORE-1182
=> [WFCORE-1182]: Update default domain configuration to use http-remoting

controller/src/main/java/org/jboss/as/controller/operations/common/ResolveExpressionHandler.java
The handler doesn't fail but returns a failure instead.
Jira: https://issues.jboss.org/browse/WFCORE-149
=> [WFCORE-149]:  Failures in 'resolve-expression" op appear in server log.

controller/src/main/java/org/jboss/as/controller/extension/ExtensionRemoveHandler.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/remove/ExtensionRemoveTestCase.java
If no extension exists throwing an OperationFailedException
Jira: https://issues.jboss.org/browse/WFCORE-1346
=> [WFCORE-1346]: Extension remove reports sucess even if the extension does not exist.

remoting/subsystem/src/main/java/org/jboss/as/remoting/Namespace.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem40Parser.java, remoting/subsystem/src/main/resources/schema/wildfly-remoting_4_0.xsd, remoting/subsystem/src/main/resources/subsystem-templates/remoting.xml, remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java, remoting/tests/src/test/resources/org/jboss/as/remoting/remoting.xml
=> [WFCORE-958] Add version 4 of the Remoting subsystem schema.

deployment-repository/src/main/java/org/jboss/as/repository/ContentRepository.java
Taking the rights from the repository folder.
Jira: https://issues.jboss.org/browse/WFCORE-1348
=> [WFCORE-1348]: Specify filesystem rights for deployment content

controller/src/main/java/org/jboss/as/controller/ExpressionResolverImpl.java, controller/src/test/java/org/jboss/as/controller/ExpressionResolverUnitTestCase.java
Checking if we are at the end of an expression.
=> [WFCORE-1399]: Failure when resolving an expression with the default value containing a '$' at the end.

embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java, host-controller/src/main/java/org/jboss/as/host/controller/Main.java
This also removes the embedded specific environment setup in favor of the existing determineEnvironment / HostControllerEnvironment.
=> WFCORE-1425 embedded slave started with host-slave.xml has incorrect hostname

pom.xml, testsuite/patching/pom.xml, testsuite/patching/src/test/java/org/jboss/as/test/patching/BasicOneOffPatchingScenariosTestCase.java, testsuite/patching/src/test/java/org/jboss/as/test/patching/CliUtilsForPatching.java, testsuite/patching/src/test/java/org/jboss/as/test/patching/NativeApiPatchingTestCase.java, testsuite/patching/src/test/java/org/jboss/as/test/patching/NonStandardSituationsTestCase.java, testsuite/patching/src/test/java/org/jboss/as/test/patching/OverridePreserveTestCase.java, testsuite/patching/src/test/java/org/jboss/as/test/patching/PatchingTestUtil.java, testsuite/patching/src/test/java/org/jboss/as/test/patching/RemotePatchInfoPatchIdUnitTestCase.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java
- to make build work on recent JDK9 builds
- upgrade byteman to 3.0.3
=> WFCORE-1375 upgrade jboss-parent to 20 making build work on JDK9

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java, controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java, controller/src/main/java/org/jboss/as/controller/ModelControllerLock.java, controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java, controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java, controller/src/test/java/org/jboss/as/controller/ModelControllerLockTestCase.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/MainKernelServicesImpl.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/FetchMissingConfigurationHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadDomainModelHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainModelHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelHandlerBase.java, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java, host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java, host-controller/src/test/java/org/jboss/as/host/controller/util/TestModelControllerService.java
Also updates ModelControllerLock to use a bitmask internally for state. I closed the previous one by mistake :-1:
=> WFCORE-915 allow concurrent registration of slave hosts

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/ExtensibleFilter.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/logging/DeploymentScannerLogger.java, deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java, deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/ListFileHelper.java
Using java.nio.file.Files to get better exceptions thus understand this kind of strange behaviour.
Jira: https://issues.jboss.org/browse/WFCORE-1108
=> [WFCORE-1108]:  Wildfly 9.0.1 Final fails next day with WFLYDS0032: Failed to list files in directory.

testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/HttpMgmtProxy.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpPostMgmtOpsTestCase.java
Reenabling the test using the logging subsystem.
Jira: https://issues.jboss.org/browse/WFCORE-1123
=> [WFCORE-1123]:  Recreate HttpPostMgmtOpsTestCase.testAddRemove

controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java, controller/src/main/java/org/jboss/as/controller/AttributeMarshallers.java, controller/src/main/java/org/jboss/as/controller/AttributeParser.java, controller/src/main/java/org/jboss/as/controller/AttributeParsers.java, controller/src/main/java/org/jboss/as/controller/ExpressionResolverImpl.java, controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java, controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java, controller/src/test/resources/org/jboss/as/controller/persistence/mail-parser.xml, controller/src/test/resources/org/jboss/as/controller/persistence/server-subsystem.xml
These are some changes to #1470 that I want. He's AFK right now so I've put up a separate PR.
=> [WFCORE-1448] Parsing and marshalling for map and list attributes don't differentiate between empty and absent object lists

controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java, controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
https://issues.jboss.org/browse/WFCORE-1245
=> WFCORE-1245 Always report the root cause of deployment failure

host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java, host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java, server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java, server/src/main/java/org/jboss/as/server/operations/WriteConfigHandler.java, server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
Jira issue:
https://issues.jboss.org/browse/WFCORE-340
=> [WFCORE-340] Added a write-config operation to force the server to write its config file

cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
This is a possible fix for https://issues.jboss.org/browse/WFCORE-1462
=> cli, ssl config issue with vault in wildfly-core context

logging/src/main/java/org/jboss/as/logging/deployments/AbstractLoggingDeploymentProcessor.java
https://issues.jboss.org/browse/WFCORE-1464
=> [WFCORE-1464] ensure LogContexts for sub deployments are unregistered

deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerDefinition.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/WritePathAttributeHandler.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/WriteRelativeToAttributeHandler.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/logging/DeploymentScannerLogger.java
https://issues.jboss.org/browse/WFCORE-1333
validate attribute path and relative-to path, checking directory exists and it is an writable directory.
=> [WFCORE-1333] validate path and relative-to attributes value.

controller/src/main/java/org/jboss/as/controller/audit/FileAuditLogHandler.java, controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java, controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java, controller/src/test/java/org/jboss/as/controller/audit/FileAuditLogHandlerUnitTestCase.java, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/auditlog/host.xml, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/auditlog/standalone.xml, domain-management/src/main/java/org/jboss/as/domain/management/audit/AbstractFileAuditLogHandlerResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/FileAuditLogHandlerResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/PeriodicRotatingFileAuditLogHandlerResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/SizeRotatingFileAuditLogHandlerResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/AuditLogXml.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/AuditLogXml_4.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/AuditLogXml_5.java, domain-management/src/main/resources/org/jboss/as/domain/management/_private/LocalDescriptions.properties, domain-management/src/test/java/org/jboss/as/domain/management/security/auditlog/AuditLogFileHandlerTestCase.java, server/src/main/resources/schema/wildfly-config_5_0.xsd
https://issues.jboss.org/browse/WFCORE-1334
=> [WFCORE-1334] Allow disabling audit log rotation

pom.xml
https://issues.jboss.org/browse/JBEAP-4205
upstream: https://issues.jboss.org/browse/SECURITY-941
=> [JBEAP-4205] component upgrade to fix empty rolesCtxDN search in LdapExtLoginModule

controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java
PersistanceResourceTestCase could fail on the servers with multiple acl entries for file owner. Weaken the assertion of the test to pass in case that at least one principlal.equals(owner) acl entry contain WRITE_OWNER permission.
JIRA: 
https://issues.jboss.org/browse/WFCORE-1486 - PersistanceResourceTestCase fails on some windows machines
=> [WFCORE-1486] PersistanceResourceTestCase fails on some windows machines

host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java, server/src/main/java/org/jboss/as/server/controller/resources/ServiceContainerResourceDefinition.java, server/src/main/java/org/jboss/as/server/operations/DumpServicesHandler.java
https://issues.jboss.org/browse/WFCORE-1504
=> [WFCORE-1504] Enable core-service=service-container on host

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironmentService.java
https://issues.jboss.org/browse/WFCORE-1506
=> [WFCORE-1506] Add a service for the host controller environment

cli/pom.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml, core-model-test/pom.xml, host-controller/src/main/java/org/jboss/as/host/controller/Main.java, logging/pom.xml, patching/pom.xml, patching/src/main/java/org/jboss/as/patching/metadata/PatchMerger.java, patching/src/main/java/org/jboss/as/patching/metadata/PatchXml.java, patching/src/test/java/org/jboss/as/patching/metadata/PatchXmlUnitTestCase.java, patching/src/test/java/org/jboss/as/patching/tests/PatchModuleInvalidationWithRenamingFailureTestCase.java, pom.xml, remoting/tests/pom.xml, server/pom.xml, testsuite/domain/pom.xml, testsuite/manualmode/pom.xml, testsuite/patching/src/test/java/org/jboss/as/test/patching/CumulativePatchingScenariosTestCase.java, testsuite/pom.xml, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/interfaces/JmxManagementInterface.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java, testsuite/shared/src/main/resources/picketbox-module.xml, testsuite/standalone/pom.xml, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
this supersedes https://github.com/wildfly/wildfly-core/pull/1508
it is rebased and adds one extra commit that fixes failures on windows.
=> JDK9 Support

cli/src/main/java/org/jboss/as/cli/CommandContext.java, cli/src/main/java/org/jboss/as/cli/Util.java, cli/src/main/java/org/jboss/as/cli/batch/BatchedCommand.java, cli/src/main/java/org/jboss/as/cli/batch/impl/DefaultBatch.java, cli/src/main/java/org/jboss/as/cli/batch/impl/DefaultBatchedCommand.java, cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ifelse/IfElseControlFlow.java, cli/src/main/java/org/jboss/as/cli/handlers/trycatch/TryCatchFinallyControlFlow.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java, cli/src/main/java/org/jboss/as/cli/operation/impl/RolloutPlanCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/SingleRolloutPlanGroup.java, cli/src/main/java/org/jboss/as/cli/parsing/operation/PropertyState.java, cli/src/main/java/org/jboss/as/cli/parsing/operation/header/RolloutPlanHeaderCallbackHandler.java, cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java, cli/src/test/java/org/jboss/as/cli/completion/operation/test/PropertiesCompletionTestCase.java, cli/src/test/java/org/jboss/as/cli/parsing/test/OperationParsingTestCase.java, cli/src/test/java/org/jboss/as/cli/parsing/test/RolloutPlanParsingTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLITestUtil.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CommandSubstitutionTestCase.java
- CLI parsing and completion changes to handle implicit values.
- Introduce CommandContext.Scope to formalise context storage duration.
- New unit tests
=> [WFCORE-1472] Boolean value could become optional

cli/src/main/java/org/jboss/as/cli/handlers/ReadAttributeHandler.java, cli/src/main/java/org/jboss/as/cli/impl/ArgumentWithValue.java, cli/src/main/java/org/jboss/as/cli/impl/ArgumentWithoutValue.java, cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
This is mainly new tests for command completion and fixes for bugs that the tests highlighted.
=> [WFCORE-1516] fix some completion issues

deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
Not really an ideal fix, but if files are checkout out on Windows replacing the '\n` with `\r\n` the tests will fail as the hash won't match. This is replaces the input stream with one that strips out all the '\r` bytes.
It's possible you're not supposed to use the line separator replacement when setting up git. If that's the case this can just be rejected.
=> Strip carriage returns from content files to ensure the SHA-1 matches.

cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Fixed parser to handle non attribute compliant character when parsing attribute names. Added unit test.
=> [WFCORE-1520] fixed AttributeName parser used at completion time

controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
Update isRuntimeOnlyRegistrationValid documentation after WFCORE-831 changes
=> Fix documentation

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java, testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ManagementClient.java, testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java, testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java, testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildflyTestRunner.java
- use junit api instead of pure reflection for injection
- make ManagmentClient final in server
- use client delegate to reduce injection and "stale" clients
=> Improve test runner to be more resiliant

cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
https://issues.jboss.org/browse/WFCORE-1563
=> [WFCORE-1563] Fix replace deployment fail on CLI batch mode

cli/src/main/java/org/jboss/as/cli/operation/impl/RolloutPlanCompleter.java, cli/src/main/java/org/jboss/as/cli/parsing/operation/header/RolloutPlanHeaderCallbackHandler.java, cli/src/main/java/org/jboss/as/cli/parsing/operation/header/RolloutPlanState.java, cli/src/test/java/org/jboss/as/cli/completion/operation/test/DeployCompletionTest.java
JIRA: https://issues.jboss.org/browse/WFCORE-1570
=> WFCORE-1570 Adding 'name' as alternative to 'id' for rollout header

cli/src/main/java/org/jboss/as/cli/parsing/DefaultStateWithEndCharacter.java, cli/src/main/java/org/jboss/as/cli/parsing/ParserUtil.java, cli/src/main/java/org/jboss/as/cli/parsing/command/ArgumentValueNotFinishedException.java, cli/src/test/java/org/jboss/as/cli/parsing/test/CommandTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1572
=> WFCORE-1572 Fixed parsing of argument value with a whitespace

deployment-repository/src/main/java/org/jboss/as/repository/LocalDeploymentFileRepository.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java, embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java, patching/src/main/java/org/jboss/as/patching/management/DeleteOp.java
Protecting loop against File.list() that may return a null array.
Jira: https://issues.jboss.org/browse/WFCORE-1536
=> [WFCORE-1536]:  NPE thrown during application redeployment, slaves taken offline

pom.xml
=> [WFCORE-1589] Upgrade to WildFly Common 1.2.0.Beta1

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
https://issues.jboss.org/browse/WFCORE-1554
=> [master] WFCORE-1554 Building an attribute based on another attribute does not copy CapabilityReferenceRecorder

core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
JIRA: https://issues.jboss.org/browse/WFCORE-1550
=> [WFCORE-1550]: wildfly-init-redhat.sh script does not work on RHEL 5 OS

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java, controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java, controller/src/main/java/org/jboss/as/controller/parsing/Namespace.java, controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties, core-feature-pack/src/main/resources/configuration/standalone/template.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-management/main/module.xml, domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_4.java, domain-management/src/main/java/org/jboss/as/domain/management/security/AbstractKeyManagerService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/FileKeyManagerService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/KeystoreAttributes.java, domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderKeyManagerService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SSLContextService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SSLServerIdentityResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/X509CertificateBuilder.java, server/src/main/resources/schema/wildfly-config_4_2.xsd, server/src/main/resources/schema/wildfly-config_5_0.xsd
=> WFCORE-1576 Allow the server to auto generate self signed certificates

cli/pom.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml, core-model-test/pom.xml, host-controller/src/main/java/org/jboss/as/host/controller/Main.java, logging/pom.xml, patching/pom.xml, patching/src/main/java/org/jboss/as/patching/metadata/PatchMerger.java, patching/src/main/java/org/jboss/as/patching/metadata/PatchXml.java, patching/src/test/java/org/jboss/as/patching/metadata/PatchXmlUnitTestCase.java, patching/src/test/java/org/jboss/as/patching/tests/PatchModuleInvalidationWithRenamingFailureTestCase.java, pom.xml, remoting/tests/pom.xml, server/pom.xml, testsuite/domain/pom.xml, testsuite/manualmode/pom.xml, testsuite/patching/src/test/java/org/jboss/as/test/patching/CumulativePatchingScenariosTestCase.java, testsuite/pom.xml, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/interfaces/JmxManagementInterface.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
Fix a couple issues I mentioned on #1609 so I can get another 2.2 CR out.
=> Tweak pull request 1609

core-feature-pack/src/main/resources/content/bin/.jbossclirc
https://issues.jboss.org/browse/WFCORE-1593
downstream issue: https://issues.jboss.org/browse/JBEAP-4951
=> [WFCORE-1593] Update the default variable value in .jbossclirc file.

cli/src/main/resources/help/help.txt
https://issues.jboss.org/browse/WFCORE-1591
=> [WFCORE-1591] add missing help message for --properties argument.

cli/src/main/java/org/jboss/as/cli/CliConfig.java, cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java, cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/java/org/jboss/as/cli/impl/Namespace.java, cli/src/main/resources/help/help.txt, cli/src/main/resources/schema/wildfly-cli_3_1.xsd, cli/src/test/java/org/jboss/as/cli/completion/mock/MockCliConfig.java, core-feature-pack/src/main/resources/content/bin/jboss-cli.xml, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
In addition to allow for echoing the command in non interactive mode, the CLI XSD config file has been upgraded to release 3.1. Although the latest XSD was 3.0, the shipped xml config file was still 2.0. I have upgraded the shipped XML file to release 3.1.
=> Fix for WFCORE-1614

controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
https://issues.jboss.org/browse/WFCORE-1568
N.B. This commit will cause the core+full integration tests to fail until https://github.com/wildfly/wildfly/pull/8914 is merged.
=> [master] WFCORE-1568 AttributeDefinition should defer handling of undefined values to CapabilityReferenceRecorder

controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
https://issues.jboss.org/browse/WFCORE-1568
=> [2.x] WFCORE-1568 AttributeDefinition should defer handling of undefined values to CapabilityReferenceRecorder

host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandler.java, pom.xml, subsystem-test/framework/pom.xml, testsuite/domain/pom.xml, testsuite/pom.xml, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
- upgrade jboss-modules
- WFCORE-1290 upgrade jboss-marshalling
=> WFCORE-1374 - make code work with jdk9b112 and newer

host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandler.java
for master it is part of #1608
=> [2.x]Properly handle :undefine-attribute in domain sync-model

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleMode.java
modulePath is null when executed inside WildFly Swarm, therefore causing a NPE in this method
=> WFCORE-1629: Fixed potential NPE

pom.xml, testsuite/domain/pom.xml
=> [2.x] WFCORE-1374 Make domain testsuite work on JDK9

controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java, controller/src/main/java/org/jboss/as/controller/ParsedBootOp.java, controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java, jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java, jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java, jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java, server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/HierarchicalCompositionTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/AuditLogTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ServerRestartRequiredTestCase.java
Revert "[WFCORE-307]: When Wildfly fails with JBAS015810: failed to resolve interface management, it should terminate."
This reverts commit 13d8f51b79c8b976ec7a5489c94f0e8a8bda998d.
=> [WFCORE-1639] Revert changes for WFCORE-307 as the side effect is management can no longer depend on a subsystem.

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
=> @Ignore failing DeploymentScannerUnitTestCase

cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java, cli/src/main/resources/help/module.txt, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
Introduce --module-paths and associated doc and testing.
=> Fix for WFCORE-1626

cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultCallbackHandler.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java, cli/src/main/java/org/jboss/as/cli/operation/impl/RolloutPlanCompleter.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Fixing headers completion:
- NPE introduced by WFCORE-1617
- Proper completion of header name and value.
- A set of new test cases.
- Limitation introduced by AESH-386 can't be fixed, will be addressed once AESH is fixed.
=> Fix WFCORE-1637

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliVariablesTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1654
Tests for 'set' and 'unset' commands in JBoss-CLI
=> [WFCORE-1654] Added integration tests for set and unset commands in CLI

logging/src/main/resources/subsystem-templates/logging.xml
(cherry picked from commit 1a9873e949f816368f95d8a7070086f8233b6ebc)
JIRA: https://issues.jboss.org/browse/WFCORE-1658
=> [WFCORE-1658] Disable console logging for standalone-full-ha.xml

controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/AbstractCollectionHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/WriteAttributeHandler.java, controller/src/test/java/org/jboss/as/controller/operation/global/AbstractCollectionOperationsTestCase.java, controller/src/test/java/org/jboss/as/controller/operation/global/EnhancedSyntaxTestCase.java, controller/src/test/java/org/jboss/as/controller/operation/global/StorageRuntimeCollectionOperationsTestCase.java
=> [WFCORE-1481] list-add operation doesn't work on login-modules attribute

host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java, pom.xml
=> [2.x] WFCORE-1669 / WFCORE-1663

server/src/main/java/org/jboss/as/server/deployment/DeferredDeploymentOverlayDeploymentUnitProcessor.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentOverlayDeploymentUnitProcessor.java, server/src/main/java/org/jboss/as/server/deployment/SubExplodedDeploymentMarker.java
Jira: https://issues.jboss.org/browse/WFCORE-761
This is part of the fix on the overlay issues, the second part of fix and the test cases PR is at: https://github.com/wildfly/wildfly/pull/8528
=> [WFCORE-761] Not possible to overlay non existing file in WAR

cli/src/main/java/org/jboss/as/cli/handlers/LsHandler.java
JIRA: https://issues.jboss.org/browse/WFCORE-1699
=> [WFCORE-1699] Inefficient usage of map iterators

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/operations/validation/StringBytesLengthValidator.java
https://issues.jboss.org/browse/WFCORE-1702
=> [WFCORE-1702] new error messages for StringBytesLengthValidator.

cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
Fixing how the CLI create the replace deployment operation to take unmanaged deployment into account.
Jira: https://issues.jboss.org/browse/WFCORE-1706
=> [WFCORE-1706]: Deploying with force an unmanaged deployment makes it managed

domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_5.java
=> [WFCORE-1700] Add ManagementXml_5 in preperation for changes being made to version 5 of the management schema.

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractSyslogReconnectionTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-1708
=> [WFCORE-1708] Fix for ReconnectSyslogServerTestCase fails intermittently

testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/WildFlyManagedConfiguration.java
- this will enable assertions for domain mode tests
=> Enable assertions in by default

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIScriptSupportTestCase.java
Update the test to use the right IP address on the client and the server side.
=> Fix for WFCORE-1712

cli/src/main/java/org/jboss/as/cli/handlers/ReadAttributeHandler.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java
Removed the isValueComplete check, it was not right. Added nodded logic to properly handle address during completion. Added new unit tests.
=> Fix for WFCORE-1676

host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironmentWrapper.java, ide-configs/eclipse/wildfly-templates.xml, server/src/main/java/org/jboss/as/server/ServerEnvironmentWrapper.java
follow up  https://github.com/wildfly/wildfly-core/pull/1731
=> better Controlling Access and ASL copyright

testsuite/standalone/pom.xml, testsuite/standalone/src/test/java/org/jboss/as/test/integration/jmx/ModelControllerMBeanTestCase.java
Migrating the test from full using ServiceActivator.
Jira:https://issues.jboss.org/browse/WFCORE-1713
=> [WFCORE-1713]: Migrate ModelControllerMBeanTestCase from wildfly test suite to core test suite.

server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
please see https://issues.jboss.org/browse/WFCORE-1687
=> [WFCORE-1687] fix warning on undeploying any deployment due to empty address.

cli/src/main/java/org/jboss/as/cli/CliConfig.java, cli/src/main/java/org/jboss/as/cli/CommandContext.java, cli/src/main/java/org/jboss/as/cli/handlers/CommandTimeoutHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ifelse/IfElseControlFlow.java, cli/src/main/java/org/jboss/as/cli/impl/AwaiterModelControllerClient.java, cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java, cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java, cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java, cli/src/main/java/org/jboss/as/cli/scriptsupport/CLI.java, cli/src/main/resources/help/command-timeout.txt, cli/src/main/resources/help/help.txt, cli/src/test/java/org/jboss/as/cli/completion/mock/MockCliConfig.java, cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java, core-feature-pack/src/main/resources/content/bin/jboss-cli.xml, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CommandTimeoutHandlerTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/LongOperationProvider.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ShutdownTestCase.java, testsuite/manualmode/src/test/resources/META-INF/services/org.jboss.as.cli.CommandHandlerProvider, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
A new command to get/set/reset the command timeout. XML+option to provide a timeout via configuration. Actual implementation of timeout for low level operation and CommandHandlers.
=> Fix for WFCORE-923

cli/src/main/java/org/jboss/as/cli/Util.java, cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/UndeployHandler.java, cli/src/main/resources/help/deploy.txt, pom.xml, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllDomainTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeployTestCase.java
Deploying all inactive deployments. This is an attempt to run all tests on all platforms with latest Aesh 0.66.9 branch.
=> Deploy all

cli/src/main/java/org/jboss/as/cli/Attachments.java, cli/src/main/java/org/jboss/as/cli/CommandContext.java, cli/src/main/java/org/jboss/as/cli/RequestWithAttachments.java, cli/src/main/java/org/jboss/as/cli/Util.java, cli/src/main/java/org/jboss/as/cli/batch/Batch.java, cli/src/main/java/org/jboss/as/cli/batch/impl/DefaultBatch.java, cli/src/main/java/org/jboss/as/cli/handlers/BaseOperationCommand.java, cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/WindowsFilenameTabCompleter.java, cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java, cli/src/main/java/org/jboss/as/cli/impl/DeploymentItemCompleter.java, cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java, cli/src/test/java/org/jboss/as/cli/AttachmentTestCase.java, cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ExplodedDeploymentTestCase.java
Support for streams in the CLI. Warning, some unit tests are based on Incremental/exploded deployment, so mut be merged once the exploded deployments is in.
=> Fix for WFCORE-1594

domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java, domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/AddUser.java
WildFly Core: https://issues.jboss.org/browse/WFCORE-1747
WildFly Core EAP: https://issues.jboss.org/browse/JBEAP-5759
=> [WFCORE-1747] add-user.sh script should have better help message

domain-management/src/main/java/org/jboss/as/domain/management/audit/AccessAuditResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/AuditLogHandlerReferenceResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/audit/AuditLogLoggerResourceDefinition.java
Also, don't modify runtime in the HC's server-logger resources
=> [WFCORE-1718] Do recursive deletes

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractSyslogReconnectionTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-1708
=> [WFCORE-1708] Fix for failing ReconnectSyslogServerTestCase on Solaris

domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java, domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/AddUser.java, domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/AddUserState.java, domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/RuntimeOptions.java, domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/StateValues.java, domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/UpdateUser.java
JIRA: https://issues.jboss.org/browse/WFCORE-1759
=> [WFCORE-1759] secret value in non-interactive mode

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
https://issues.jboss.org/browse/WFCORE-1768
https://issues.jboss.org/browse/JBEAP-5877
=> [WFCORE-1768] Update the _private exclusions for the Elytron module definition.

cli/src/main/java/org/jboss/as/cli/OperationCommand.java, cli/src/main/java/org/jboss/as/cli/Util.java, cli/src/main/java/org/jboss/as/cli/batch/impl/DefaultBatchedCommand.java, cli/src/main/java/org/jboss/as/cli/handlers/AttachmentHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ResponseHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/resources/help/attachment.txt, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AttachmentTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ExplodedDeploymentTestCase.java
A new attachment command to download/display attachments. Evolved a batch command with an optional ResponseHandler that is called for each step once the composite reply has been received.
=> Fix for WFCORE-1726. Support for attachments in Response.

pom.xml
=> WFCORE-1753 Upgrade Aesh to 0.66.10

server/src/main/java/org/jboss/as/server/deployment/DeploymentFullReplaceHandler.java
Fix https://issues.jboss.org/browse/WFCORE-1569 caused by https://issues.jboss.org/browse/WFCORE-495
=> [WFCORE-1569] verify resource existance before removing it

pom.xml
https://issues.jboss.org/browse/WFCORE-1766
=> WFCORE-1766 Undertow 1.4.2.Final

testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/PreparedResponseTestCase.java
=> [WFCORE-1789]: Ingoring intermittent failure test case

core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
=> [WFCORE-1719][2.x] Wildfly does not start as a windows service

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ConfigurationChangesTestCase.java
Analysis document: https://polarion.engineering.redhat.com/polarion/#/project/EAP7/wiki/RFEs_7_1/EAP7-575
EAP7 issue: https://issues.jboss.org/browse/EAP7-575
=> [EAP7-575]: Test development

testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
https://issues.jboss.org/browse/WFCORE-1788
=> WFCORE-1788 ability to get address of node1 in testsuite

controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java, controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
- implement recursive remove of resource registration
=> WFCORE-1785 Extension remove is not cleaning out provided capabilities

pom.xml
- upgrade jboss-modules to 1.6.0.Beta3
=> WFCORE-1374 Make build work on JDK9 b135+

pom.xml
These issues may be resolved at the point of merging: -
https://issues.jboss.org/browse/WFCORE-1763
https://issues.jboss.org/browse/WFCORE-1764
=> [WFCORE-1763] and [WFCORE-1764] WildFly Elytron and Elytron Web Component Upgrades

server/src/main/java/org/jboss/as/server/mgmt/NativeManagementResourceDefinition.java
https://issues.jboss.org/browse/WFCORE-1761
=> [WFCORE-1761] Remove bogus alternative

deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java, deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java, deployment-repository/src/main/java/org/jboss/as/repository/logging/DeploymentRepositoryLogger.java, deployment-repository/src/test/java/org/jboss/as/repository/PathUtilTest.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ManagedDeploymentBrowseContentHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ManagedDeploymentReadContentHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainDeploymentResourceDefinition.java, server/src/main/java/org/jboss/as/server/controller/resources/ServerDeploymentResourceDefinition.java, server/src/main/java/org/jboss/as/server/deployment/ManagedDeploymentBrowseContentHandler.java, server/src/main/java/org/jboss/as/server/deployment/ManagedDeploymentReadContentHandler.java
Adding browse and read content for any type of managed deployment (archives are now supported).
Jira: https://issues.jboss.org/browse/WFCORE-379
https://issues.jboss.org/browse/WFCORE-380
=> Adding browse and read content for any type of managed deployment

host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java, host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
https://issues.jboss.org/browse/WFCORE-1769
=> [WFCORE-1769] Use assert, not OFE

server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
Updating the operation description with was wrong and adding a new validator.
Jira: https://issues.jboss.org/browse/WFCORE-1793
=> [WFCORE-1793]: add-content operation fails to overwrite existing content with overwrite=true set when passing content by file path

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
=> @Ignore intermittently failing test

cli/src/main/java/org/jboss/as/cli/handlers/ModuleNameTabCompleter.java, cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java, cli/src/test/java/org/jboss/as/cli/completion/modules/test/ModuleNameTabCompleterTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleOpsCompletionTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1657
=> WFCORE-1657 Confusing tab completion for adding a module dependencies

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/BasicOperationsUnitTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-1805
=> [WFCORE-1805]:  Re-enabming the test and trying to get an error cause.

pom.xml
https://issues.jboss.org/browse/WFCORE-1817
=> WFCORE-1817 upgrade Xerces to 2.11.0.SP5

cli/src/main/java/org/jboss/as/cli/handlers/BaseOperationCommand.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeploymentInfoTestCase.java
https://issues.jboss.org/browse/WFCORE-1739
=> [WFLY-7001][WFCORE-1739] purge deployment-info headers if wrong value is set

host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/ConfigurationPersisterFactory.java
https://issues.jboss.org/browse/WFCORE-1773
=> WFCORE-1773 Fix domain backup copy persistence when using --backup or --cached-dc.

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, pom.xml, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCommentsTestCase.java
Ash is now 0.66.11. Configuring Aesh to not take into account ' and "
=> Fix for WFCORE-1804. CLI comments are not ended

controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java, controller/src/main/java/org/jboss/as/controller/management/BaseHttpInterfaceAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/management/BaseHttpInterfaceResourceDefinition.java, controller/src/main/java/org/jboss/as/controller/management/BaseNativeInterfaceAddStepHandler.java, controller/src/main/java/org/jboss/as/controller/management/BaseNativeInterfaceResourceDefinition.java, controller/src/main/java/org/jboss/as/controller/management/ManagementInterfaceAddStepHandler.java, server/src/main/java/org/jboss/as/server/operations/HttpManagementRemoveHandler.java
Also includes WFCORE-1819 fix that this fix relies upon.
=> [WFCORE-1820] Use MRR-driven capability registration for the management interface capabilities

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleOpsCompletionTestCase.java
Cleaning modules directory before and after the test.
Jira: https://issues.jboss.org/browse/WFCORE-1812
=> [WFCORE-1812]: Makes ModuleOpsCompletionTestCase more resilient.

cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java, cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Took the opportunity of this change to fixe various issues:
- Nested lists
- Completed objects (propose })
- Completed values (propose ,)
- Resist to some user invalid syntaxes
- Add new unit tests
Side effect is to fix WFCORE-1825
=> Fix for WFCORE-1826. CLI value-type completion fixes.

controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
jira: https://issues.jboss.org/browse/WFCORE-1815
=> WFCORE-1815 It's not possible to re-add extension

pom.xml
https://issues.jboss.org/browse/WFCORE-1830
=> WFCORE-1830 upgrade MSC to 1.2.7.Final

cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java, cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Minimal completion, open the Map '{' for value of type Map.
=> Fix for WFCORE-1839. Map completion.

pom.xml
The following issues can be resolved once merged: -
https://issues.jboss.org/browse/WFCORE-1837
https://issues.jboss.org/browse/WFCORE-1838
=> [WFCORE-1837] / [WFCORE-1838] WildFly Elytron and Elytron Web Upgrades

server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
JIRA: https://issues.jboss.org/browse/WFCORE-1479
EAP 7.1 Jira: https://issues.jboss.org/browse/JBEAP-5267
=> [WFCORE-1479]: Jar sub deployment has as first dependency parent ear

pom.xml
https://issues.jboss.org/browse/WFCORE-1849
=> WFCORE-1849 wildfly-openssl 1.0.0.Alpha2

pom.xml
Once merged the following issue can be closed: -
https://issues.jboss.org/browse/WFCORE-1858
=> [WFCORE-1858] Upgrade to Elytron Web 1.0.0.Beta5

server/src/main/java/org/jboss/as/server/SelfContainedContainer.java, server/src/main/java/org/jboss/as/server/ServerEnvironment.java, server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
- https://issues.jboss.org/browse/WFCORE-1797
- https://issues.jboss.org/browse/WFCORE-1786
=> Backport of WFCORE-1797, WFCORE-1786

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliAliasTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1729
=> [WFCORE-1729] Bugfix for CliAliasTestCase.testAliasPersistence

cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/module/ModuleConfigImpl.java, cli/src/main/java/org/jboss/as/cli/handlers/module/ModuleDependency.java, cli/src/main/resources/help/module.txt, cli/src/test/java/org/jboss/as/cli/handlers/module/ModuleConfigTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleOpsCompletionTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
New option for the module command and associated unit tests.
=> Fix for WFCORE-1843. module command to export dependencies.

pom.xml
Weld 2.4 that is already in WildFly, is complaining it would like to have fixes that are part of 2.0.3
=> WFCORE-1860 Upgrade to jandex 2.0.3

pom.xml
The following issue can be resolved once merged: -
https://issues.jboss.org/browse/WFCORE-1867
=> [WFCORE-1867] Upgrade to WildFly Elytron 1.1.0.Beta11

core-feature-pack/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
https://issues.jboss.org/browse/WFCORE-1874
https://issues.jboss.org/browse/JBEAP-6473
=> WFCORE-1874 HTTP/2 does not work with OpenSSL

pom.xml
https://issues.jboss.org/browse/WFCORE-1893
=> WFCORE-1893 Wildfly build tools 1.1.7.Final

pom.xml
https://issues.jboss.org/browse/WFCORE-1895
=> WFCORE-1895 Undertow 1.4.4.Final

model-test/src/main/java/org/jboss/as/model/test/FailedOperationTransformationConfig.java
Based on @kabir 's work which needed bit more tweaking. 
https://issues.jboss.org/browse/WFCORE-1836
=> WFCORE-1836 Rejection-style transformer tests assume each operation generated by parser has distinct PathAddress

cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1864
=> [WFCORE-1864] Trim dependcies names in module add command

pom.xml
https://issues.jboss.org/browse/WFCORE-1889
=> WFCORE-1889 upgrade xnio to 3.4.1.Final

cli/src/main/java/org/jboss/as/cli/operation/impl/HeadersCompleter.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Fix headers completion, propose "{" if headers content is empty.
=> Fix for WFCORE-1876. headers completion.

controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java, controller/src/main/java/org/jboss/as/controller/AttributeMarshallers.java, controller/src/main/java/org/jboss/as/controller/AttributeParser.java, controller/src/main/java/org/jboss/as/controller/AttributeParsers.java, controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java, controller/src/main/java/org/jboss/as/controller/SimpleMapAttributeDefinition.java, controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java, controller/src/test/resources/org/jboss/as/controller/persistence/core-subsystem.xml, controller/src/test/resources/org/jboss/as/controller/persistence/server-complex-attribute.xml
- parser can now handle "unlimited" complex attribute nesting
- introduced UNWRAPPED_OBJECT_LIST parser
- fixes for overriding parsers with attribute groups
- few general bug fixes
mostly done to support elytron subsystem parsing, see https://github.com/wildfly-security/elytron-subsystem/pull/277 for details
=> WFCORE-1834 General parser improvements around complex attributes

testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLITestUtil.java, testsuite/shared/src/main/java/org/wildfly/test/api/Authentication.java
https://issues.jboss.org/browse/WFLY-7309
=> [WFCORE-1865] - Make the authentication configurable in the testsuite

testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/testbase/CustomManagementContextTestBase.java
Some additional testing for https://issues.jboss.org/browse/EAP7-614 / https://issues.jboss.org/browse/WFCORE-1742
=> WFCORE-1742: enhance tests a bit

pom.xml
This addresses JBEAP-6628, JBEAP-6665, JBEAP-6670, JBEAP-6740
=> Update to VDX 1.1.0

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
making CredentialReference thread safe as per comment in https://github.com/wildfly/wildfly-core/pull/1816
https://issues.jboss.org/browse/WFCORE-1863
=> [WFCORE-1863] Make CredentialReference thread safe

pom.xml
https://issues.jboss.org/browse/WFCORE-1933
=> WFCORE-1933 Wildfly OpenSSL 1.0.0.Alpha4

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
Wildfly Issue: https://issues.jboss.org/browse/WFCORE-1911
EAP 7.1 Issue: https://issues.jboss.org/browse/JBEAP-6722
=> WFCORE-1911 Port DeploymentScannerTestCase from EAP 6.4

host-controller/src/main/java/org/jboss/as/host/controller/HostModelUtil.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/DomainControllerWriteAttributeHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/LocalDomainControllerAddHandler.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/RemoteDomainControllerAddHandler.java
The original WFCORE-1262 work duplicated some complex logic, which will likely lead to future bugs as only one of the duplicates picks up some change. This PR shares the logic.
=> [WFCORE-1262] Share logic between the legacy and standard handlers

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiHandler.java, server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpDeploymentUploadUnitTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpGetMgmtOpsTestCase.java
Adding read-content to the list of allowed GET operations.
Jira: https://issues.jboss.org/browse/WFCORE-1951
=> [WFCORE-1951]: Expose content repository read-content as a GET operation

host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java
When routing to managed servers, remove the EMPTY content if the hash is correctly filled.
Jira: https://issues.jboss.org/browse/WFCORE-1959
JBEAP: https://issues.jboss.org/browse/JBEAP-6977
=> [WFCORE-1959]: Deploying an empty managed exploded deployment to server group in domain fails.

core-feature-pack/pom.xml, core-feature-pack/src/main/resources/configuration/standalone/subsystems.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/discovery/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/discovery/main/module.xml, discovery/pom.xml, discovery/src/main/java/org/wildfly/extension/discovery/AggregateProviderAddHandler.java, discovery/src/main/java/org/wildfly/extension/discovery/AggregateProviderDefinition.java, discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java, discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemAddHandler.java, discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemDefinition.java, discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemParser.java, discovery/src/main/java/org/wildfly/extension/discovery/Messages.java, discovery/src/main/java/org/wildfly/extension/discovery/StaticProviderAddHandler.java, discovery/src/main/java/org/wildfly/extension/discovery/StaticProviderDefinition.java, discovery/src/main/java/org/wildfly/extension/discovery/TrivialRemoveStepHandler.java, discovery/src/main/resources/META-INF/services/org.jboss.as.controller.Extension, discovery/src/main/resources/org/wildfly/extension/discovery/LocalDescriptions.properties, discovery/src/main/resources/schema/wildfly-discovery_1_0.xsd, discovery/src/main/resources/subsystem-templates/discovery.xml, discovery/src/test/java/org/wildfly/extension/discovery/DiscoverySubsystemTestCase.java, discovery/src/test/resources/org/wildfly/extension/discovery/discovery-1.0.xml, pom.xml
Supercedes #1866 with a minor pom merge conflict fixed.
=> Rebase Pull request 1866

testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/PreparedResponseTestCase.java
Jira: https://issues.jboss.org/browse/WFCORE-1789
=> [WFCORE-1789]: Ignoring intermittent failing test

controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
https://issues.jboss.org/browse/WFCORE-1931
=> WFCORE-1931 remove another extra comma in description.

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
[WFCORE-1988] : https://issues.jboss.org/browse/WFCORE-1988
[JBEAP-7113] : https://issues.jboss.org/browse/JBEAP-7113
=> [WFCORE-1988]: /host-exclude=XX:add(management-minor-version=1) produces java.lang.IllegalArgumentException.

testsuite/shared/pom.xml, testsuite/shared/src/main/java/org/wildfly/test/mixed/domain/TestParserUtils.java
https://issues.jboss.org/browse/WFCORE-1966
=> [WFCORE-1966] Move util to create test xml parser into core from full

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACSensitivityConstraintUtilizationTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/FullRbacProviderTestSuite.java
Propagate the sensistive-classification and the application-classification to the managed servers.
Jira: https://issues.jboss.org/browse/WFCORE-1899
JBEAP: https://issues.jboss.org/browse/JBEAP-6281
=> [WFCORE-1899]: Sensitive data can be exposed at the server level in domain mode.

controller/src/main/java/org/jboss/as/controller/operations/global/AbstractCollectionHandler.java
https://issues.jboss.org/browse/WFCORE-1997
=> WFCORE-1997 avoid NPE in list-add operation.

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
=> [WFCORE-2013] Correct the mechanism name comparison for HTTP Basic authentication.

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java, controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/PropertiesAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinitionBuilder.java, controller/src/main/java/org/jboss/as/controller/SimpleMapAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java, controller/src/main/java/org/jboss/as/controller/operations/common/InterfaceCriteriaWriteHandler.java, controller/src/main/java/org/jboss/as/controller/operations/validation/StringLengthValidator.java, controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/transform/SimilarityIndex.java, domain-management/src/main/java/org/jboss/as/domain/management/security/LdapAuthenticationResourceDefinition.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java
https://issues.jboss.org/browse/WFCORE-1556
Also https://issues.jboss.org/browse/WFCORE-1761
=> [WFCORE-1556] Correct the handling of required vs nillable

pom.xml
https://issues.jboss.org/browse/WFCORE-2014
=> WFCORE-2014 Undertow 1.4.6.Final

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
JIRA
* https://issues.jboss.org/browse/WFCORE-2024
=> [WFCORE-2024] - Optional JACC dependency to org.wildfly.security.elytron

host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
Upstream: https://issues.jboss.org/browse/WFCORE-311
EAP 7.x: https://issues.jboss.org/browse/JBEAP-49
Upstream: https://github.com/wildfly/wildfly-core/pull/1957
EAP 7.x: https://github.com/jbossas/wildfly-core-eap/pull/272
=> [WFCORE-311] use @Cause instead of toString()

cli/src/main/resources/help/connect.txt
Trivial fix, document https protocol in connect --help
=> Fix for WFCORE-2051. Mention https in connect help

controller/src/main/java/org/jboss/as/controller/access/AuthorizerConfiguration.java, controller/src/main/java/org/jboss/as/controller/access/management/WritableAuthorizerConfiguration.java, controller/src/main/java/org/jboss/as/controller/access/rbac/StandardRoleMapper.java, controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java, controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/access/domain-all.xml, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/access/standalone.xml, domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationUseIdentityRolesWriteAttributeHander.java, domain-management/src/main/java/org/jboss/as/domain/management/access/RbacSanityCheckOperation.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/AccessControlXml.java, domain-management/src/main/resources/org/jboss/as/domain/management/_private/LocalDescriptions.properties, host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml.java, host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_5.java, server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_5.java, server/src/main/resources/schema/wildfly-config_5_0.xsd
https://issues.jboss.org/browse/WFCORE-1842
=> [WFCORE-1842] Add a use-identity-roles attribute to enable the roles from the identity to be used directly.

cli/src/main/java/org/jboss/as/cli/gui/ConnectDialog.java
This is just a rebased version of #1956 which for some reason github shows as including an unrelated commit.
=> [WFCORE-1823] remove JDK specific method call

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Calling continuous too early breaks redirection. Due to some change in the way Auth callbacks are received, the console is put in an invalid state.
I have tried to simplify the general logic, this does fixes the problem and doesn't seem to introduce regression. Only manual testing required there.
=> Fix for WFCORE-2049. Prompting for username/password breaks redirection.

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java, process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
Make domain server termination more robust.
https://issues.jboss.org/browse/WFCORE-2065
https://issues.jboss.org/browse/WFCORE-2072
=> Managed process termination fixes

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java, controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java, controller/src/main/java/org/jboss/as/controller/AttributeMarshallers.java, controller/src/main/java/org/jboss/as/controller/ResourceBuilderRoot.java, controller/src/main/java/org/jboss/as/controller/SimpleListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java, controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java, controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java, controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java, security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerExtension.java, security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerExtensionTransformerRegistration.java, security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerSubsystemParser_1_0.java, security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerSubsystemParser_3_0.java, security-manager/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration, testsuite/pom.xml
WFCORE-2083 reduce memory footprint and number of allocations
WFCORE-2083 Only register transformers when needed
WFCORE-2083 Use serviceTarget from deployment phase context
WFCORE-2083 Builder inner class should be static
=> WFCORE-2083  Reduce number of object allocations and memory footprint

controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
https://issues.jboss.org/browse/WFCORE-2083
@ctomc Please approve.
=> [WFCORE-2083] Don't allocate 2 lists to wrap an empty array

pom.xml
https://issues.jboss.org/browse/WFCORE-2103
=> WFCORE-2103 Undertow 1.4.7.Final

cli/src/main/resources/help/deployment-overlay.txt, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCommentsTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
=> Update deployment-overlay help

network/src/main/java/org/jboss/as/network/ManagedServerSocketBinding.java, protocol/src/main/java/org/jboss/as/protocol/GeneralTimeoutHandler.java
https://issues.jboss.org/browse/WFCORE-2112
=> [WFCORE-2112] Non atomic updates

pom.xml
:christmas_tree: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :christmas_tree:
https://issues.jboss.org/browse/WFCORE-2110
=> [WFCORE-2110] Upgrade to Remoting JMX 3.0.0.Beta2

cli/src/main/java/org/jboss/as/cli/handlers/DefaultFilenameTabCompleter.java, cli/src/test/java/org/jboss/as/cli/parsing/test/FileCompletionTestCase.java
A complex logic hiding uncovered case. Simplified and added unit test.
=> Fix for WFCORE-2120. Simplified FileCompleter escaping logic.

server/src/main/java/org/jboss/as/server/jmx/RunningStateJmx.java
Removing unused code that creates duplicate notifications.
Jira: https://issues.jboss.org/browse/WFCORE-2119
=> [WFCORE-2119]: JMX notifications are duplicated on startup when registering the listener throught an agent.

cli/src/main/java/org/jboss/as/cli/CommandCompleter.java, cli/src/main/java/org/jboss/as/cli/handlers/EchoVariableHandler.java, cli/src/test/java/org/jboss/as/cli/parsing/test/VariablesTestCase.java
Reworked echo command variable completion. Any variable located in the line to echo is completed.
=> Fix for WFCORE-1695, echo command, variable completion.

controller/src/main/java/org/jboss/as/controller/registry/AtomicMapFieldUpdater.java, controller/src/main/java/org/jboss/as/controller/registry/GlobalTransformerRegistry.java, controller/src/main/java/org/jboss/as/controller/registry/NotificationHandlerNodeRegistry.java, controller/src/main/java/org/jboss/as/controller/registry/OperationTransformerRegistry.java
https://issues.jboss.org/browse/WFCORE-2111
https://issues.jboss.org/browse/WFCORE-1270
=> Fix NPEs in mixed domain by adjusting use of AtomicMapFieldUpdater.putAtomic()

core-feature-pack/src/main/resources/content/bin/standalone.sh
Jira: https://issues.jboss.org/browse/WFCORE-2007
=> [WFCORE-2007] standalone.sh fails to backup gc.log.#.current file silently.

cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/SegmentParsingInitialState.java, cli/src/main/java/org/jboss/as/cli/parsing/ParserUtil.java, cli/src/test/java/org/jboss/as/cli/completion/address/test/CompletionWithQuotesTestCase.java, cli/src/test/java/org/jboss/as/cli/operation/impl/SegmentParsingInitialStateTestCase.java
https://issues.jboss.org/browse/WFCORE-1971
https://issues.jboss.org/browse/JBEAP-6872
=> WFCORE-1971 Incorrect address completion when node starts with quote

pom.xml, protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
:christmas_tree: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :christmas_tree:
The following PR contains the WildFly side of the changes: -
https://github.com/wildfly/wildfly/pull/9500
=> Incremental Merge of Elytron progress from incubator

pom.xml
https://issues.jboss.org/browse/WFCORE-2135
Prerequisite for https://github.com/wildfly/wildfly-core/pull/1990
=> [WFCORE-2135] Upgrade xnio to 3.4.3.Final

server/src/main/java/org/jboss/as/server/jmx/RunningStateJmx.java
Keeping a reference to RunningModeControl instead of the RunningMode so that we have an updated RunningMode after a reload.
Jira: https://issues.jboss.org/browse/WFCORE-2141
JBEAP: https://issues.jboss.org/browse/JBEAP-7979
=> [WFCORE-2141]: JMX notifications for ControlledProcessState changes are not updated when the running mode changes.

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
EAP 7.1 Jira: https://issues.jboss.org/browse/JBEAP-6722
WFLY Jira: https://issues.jboss.org/browse/WFCORE-1911
Fixing intermittent failures.
=> JBEAP-6722 DeploymentScannerTestCase intermittently failing

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/operations/validation/ModelTypeValidator.java, controller/src/test/java/org/jboss/as/controller/operation/validation/ModelTypeValidatorUnitTestCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCommentsTestCase.java
Not loosing the parsing root exception in the failure description.
Jira: https://issues.jboss.org/browse/WFCORE-1983
JBEAP: https://issues.jboss.org/browse/JBEAP-6915
=> [WFCORE-1983]:  Root cause of failing parsing should be used as failure description

pom.xml
https://issues.jboss.org/browse/WFCORE-2166
https://issues.jboss.org/browse/JBEAP-8140
=> WFCORE-2166 JBEAP-8140 Wildfly OpenSSL 1.0.0.Beta2

pom.xml
This addresses message parsing issues under IBM JDK (see JBEAP-8139).
=> [WFCORE-2172] Update to VDX 1.1.2

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LsTestCase.java
Prepare tests for WFCORE-2021
Jira: https://issues.jboss.org/browse/WFCORE-2173
JBEAP: https://issues.jboss.org/browse/JBEAP-8204
=> [WFCORE-2173] Prepare tests for WFCORE-2021

pom.xml, request-controller/pom.xml, self-contained/pom.xml, server/pom.xml, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ModuleInfoTestCase.java
- jboss-module 1.6.0.Beta4 - also fix on test to match new behavior
- Update org.apache.httpcomponents* to latest
- jboss-parent 22
- byteman 4.0-BETA2 - only for JDK9 profile
- shrinkwrap 1.3.6
- mockito 2.5.5
- checkstyle 1.0.5
Also preform minor cleanup of poms.
- remove deps to mockito in modules that dont need it
=> WFCORE-2170 WFCORE-1374 Component upgrades and cleanup

core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java, core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/logging/CoreManagementLogger.java
https://issues.jboss.org/browse/WFCORE-2184
=> WFCORE-2184 differentiate log messages from various exceptions.

controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
If the list is empty don't report it.
Jira: https://issues.jboss.org/browse/WFCORE-1937
=> [WFCORE-1937]: Unneeded part of failure-description is printed in CLI for Elytron subsystem.

cli/src/main/java/org/jboss/as/cli/impl/BytesCompleter.java, cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java, cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java, cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueCallbackHandler.java, cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueState.java, cli/src/main/java/org/jboss/as/cli/parsing/arguments/BytesValueState.java, cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProviderTestCase.java, cli/src/test/java/org/jboss/as/cli/parsing/test/ArgumentValueParsingTestCase.java, cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Evolved parser and completer to support bytes syntax. Added unit test.
=> Fix for WFCORE-2186. Handle bytes type in completion and execution.

controller/src/main/java/org/jboss/as/controller/services/path/PathRemoveHandler.java
please see https://issues.jboss.org/browse/WFCORE-2201
=> WFCORE-2201 fix server side exception when remove read-only /path=<x>

server/src/main/java/org/jboss/as/server/deployment/Phase.java
https://issues.jboss.org/browse/WFCORE-2204
=> WFCORE-2204 Phase definitions for wildfly-nosql subsystems

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java, domain-management/src/main/java/org/jboss/as/domain/management/SecurityRealm.java, domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java, domain-management/src/main/java/org/jboss/as/domain/management/security/CallbackHandlerService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/KerberosCallbackHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java, pom.xml
:zap: Commits in this PR are included in topic branches under active development, please do not cherry-pick or rebase. :zap:
https://issues.jboss.org/browse/WFCORE-1955
https://issues.jboss.org/browse/WFCORE-2161
https://issues.jboss.org/browse/WFCORE-2222
https://issues.jboss.org/browse/WFCORE-2211
https://issues.jboss.org/browse/WFCORE-2220
https://issues.jboss.org/browse/WFCORE-2221
Experimental Builds: -
https://ci.wildfly.org/viewLog.html?buildId=42312&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments
https://ci.wildfly.org/viewLog.html?buildId=42314&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperimentsWindows
=> [WFCORE-2220] Upgrade to WildFly Elytron 1.1.0.Beta20 and Ongoing Integration

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
https://issues.jboss.org/browse/WFCORE-2210
https://issues.jboss.org/browse/WFCORE-2211
Fixed issues of credential-reference marshalling using standard marshaller.
Removed Destroyable interface implementation as it is not needed any more.
=> credential-reference changes with regards to mail subsystem integration

cli/src/main/java/org/jboss/as/cli/AwaiterModelControllerClient.java, cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java, cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
Update #2102 with a commit to ensure its new test cleans up after itself
=> Pull request 2102 update

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ConfigurationChangesTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/LegacyConfigurationChangesTestCase.java
Analysis document: https://polarion.engineering.redhat.com/polarion/#/project/EAP7/wiki/RFEs_7_1/EAP7-575
EAP7 issue: https://issues.jboss.org/browse/EAP7-575
=> [WFCORE-1642]: Test development

cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java, cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Swallow exceptions thrown during completion. Avoid to complete some obvious invalid structures. Added unit test.
=> Fix for WFCORE-2205. NPE in completion with invalid command

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java, pom.xml
Also includes https://github.com/wildfly/wildfly-core/pull/2108
=> [WFCORE-2227 Upgrade WildFly Elytron to 1.1.0.Beta21

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
Forgotten existence check fixed.
https://issues.jboss.org/browse/WFCORE-2211
=> [WFCORE-2211] fix credential-reference def. check

server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java
When replacing a scanner deployment using the (web) console won't create the undeployed marker file in the scanner.
Using notifications to make sure of that.
Jira: https://issues.jboss.org/browse/WFCORE-1890
JBEAP: https://issues.jboss.org/browse/JBEAP-7992
=> [WFCORE-1890]: Replacing a scanner deployment throught the web console will crash the next server reboot.

pom.xml, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ExplodedDeploymentTestCase.java, testsuite/domain/src/test/resources/domain-configs/domain-standard.xml, testsuite/pom.xml, testsuite/shared/pom.xml, testsuite/shared/src/main/java/org/jboss/as/test/deployment/trivial/ServiceActivatorDeploymentUtil.java, testsuite/shared/src/main/java/org/jboss/as/test/shared/PermissionUtils.java, testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentOperationsTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-846
=> [WFCORE-846] Some tests throws "Permission check failed" while run with security manager

remoting/subsystem/src/main/resources/subsystem-templates/remoting.xml
https://issues.jboss.org/browse/WFCORE-2177
=> [WFCORE-2177] Remove the 'elytron' supplement from the Remoting subsystem template.

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java, host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
Filtering host  properties starting with jboss.server. when creating the server launch command line.
Jira: https://issues.jboss.org/browse/WFCORE-350
=> [WFCORE-350]: Domain reflects jboss.server.xy properties

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
Resolves https://issues.jboss.org/browse/WFCORE-2242
=> [WFCORE-2242] Always add the LogoutHandler.

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suspendresume/DomainGracefulShutdownTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suspendresume/DomainSuspendResumeTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/suspend/web/SuspendResumeTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-848
This PR depends on https://github.com/wildfly/wildfly-core/pull/2049 to be merged first.
=> [WFCORE-848] "XNIO001001: No XNIO provider found" by some tests running with security manager

server/src/main/java/org/jboss/as/server/deployment/Phase.java
Resolves https://issues.jboss.org/browse/WFCORE-2244
=> [WFCORE-2244] Add a dependencies phase for Elytron.

pom.xml
This addresses JBEAP-8526, JBEAP-8539, JBEAP-8540.
=> Update to VDX 1.1.4

pom.xml
https://issues.jboss.org/browse/WFCORE-2255
=> [WFCORE-2255] Upgrade to WildFly Common 1.2.0.Beta5

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/ProcessStateListenerTestCase.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractLoggingTestCase.java, testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/events/ProcessStateListenerTestCase.java, testsuite/shared/src/main/java/org/wildfly/test/events/provider/TestListener.java
* tests for more transitions (reload-required, ....)
* test for execution timetout
* test  for listener that raises exception
https://issues.jboss.org/browse/WFCORE-2233
=> [WFCORE-2233] extend tests for ProcessStateListener

core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/invocation/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/discovery/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml, domain-management/src/main/java/org/jboss/as/domain/management/security/WhoAmIOperation.java, pom.xml, remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractOutboundConnectionResourceDefinition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractOutboundConnectionService.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionResourceDefinition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionService.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionResourceDefinition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionService.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java, remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties, remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java, server/src/main/java/org/jboss/as/server/deployment/Phase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ConfigurationChangesTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/AuditLogTestCase.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ConfigurationChangesHistoryTestCase.java
The following issues are resolved by this PR: -
https://issues.jboss.org/browse/WFCORE-1984
https://issues.jboss.org/browse/WFCORE-2078
https://issues.jboss.org/browse/WFCORE-2115
https://issues.jboss.org/browse/WFCORE-2239
https://issues.jboss.org/browse/WFCORE-1891
https://issues.jboss.org/browse/WFCORE-2261
https://issues.jboss.org/browse/WFCORE-2262
https://issues.jboss.org/browse/WFCORE-2263
WildFly PR https://github.com/wildfly/wildfly/pull/9595
Experimental Builds: -
Linux https://ci.wildfly.org/viewLog.html?buildId=44066&
Windows https://ci.wildfly.org/viewLog.html?buildId=44068&
Linux experimental build with disabled tests enabled: - …
=> [WFCORE-2262] Latest WildFly Elytron and Invocation Changes

cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
Added missing @Test annotation.
=> Fix for WFCORE-2205. Added missing Test annotation

core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/xnio/main/module.xml, domain-management/src/main/java/org/jboss/as/domain/management/security/JaasCallbackHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationCallbackHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInSubjectSupplemental.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserDomainCallbackHandler.java, pom.xml
A coordinated WildFly PR is to follow.
https://issues.jboss.org/browse/WFCORE-2266
https://issues.jboss.org/browse/WFCORE-2273
https://issues.jboss.org/browse/WFCORE-2274
https://issues.jboss.org/browse/WFCORE-2275
https://issues.jboss.org/browse/WFCORE-2276
=> [WFCORE-2276] Merge Latest WildFly Elytron Integration Changes

domain-management/src/main/java/org/jboss/as/domain/management/security/JaasCallbackHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationCallbackHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInSubjectSupplemental.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserDomainCallbackHandler.java
Resolves https://issues.jboss.org/browse/WFCORE-2266
=> [WFCORE-2266] Wrap remaining legacy security realm components with Elytron wrappers.

controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java, server/src/main/java/org/jboss/as/server/AbstractDeploymentChainStep.java
=> [WFCORE-1870][WFCORE-1871] Better handling of reload-required with ops that modify the DUP chain

controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
https://issues.jboss.org/browse/WFCORE-2183
=> [WFCORE-2183] Roll back the entire op if any parallel tasks roll back

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiHandler.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainUtil.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/StreamReadLimitHandler.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ResponseAttachmentTestCase.java
https://issues.jboss.org/browse/WFCORE-1777
=> [WFCORE-1777] Limit concurrency of stream responses via HTTP GET

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiHandler.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainUtil.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java, domain-http/interface/src/main/java/org/jboss/as/domain/http/server/StreamReadLimitHandler.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ResponseAttachmentTestCase.java
https://issues.jboss.org/browse/WFCORE-1777
=> [2.x][WFCORE-1777] Limit concurrency of stream responses via HTTP GET

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
https://issues.jboss.org/browse/WFCORE-2278
upstream issue: https://issues.jboss.org/browse/JBEAP-8544
=> [WFCORE-2278] use PicketBox compatible masked passwords

controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformationUtils.java
https://issues.jboss.org/browse/WFCORE-2279
https://issues.jboss.org/browse/WFCORE-2265
=> WFCORE-2265/WFCORE-2279 Fixes for override models

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/InterdependentDeploymentTestCase.java
Issue: https://issues.jboss.org/browse/WFCORE-2254
=> [WFCORE-2254] InterdependentDeploymentTestCase fails with security manager

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, pom.xml
https://issues.jboss.org/browse/WFCORE-2289
https://issues.jboss.org/browse/WFCORE-2290
A related  Wildfly PR will be linked shortly.
=> [WFCORE-2290] Merge latest WildFly Elytron Integration Changes

controller/src/main/java/org/jboss/as/controller/access/constraint/SensitivityClassification.java, controller/src/main/java/org/jboss/as/controller/access/management/SensitiveTargetAccessConstraintDefinition.java, controller/src/main/java/org/jboss/as/controller/management/BaseHttpInterfaceResourceDefinition.java, controller/src/main/java/org/jboss/as/controller/management/BaseNativeInterfaceResourceDefinition.java, controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java, domain-management/src/main/java/org/jboss/as/domain/management/access/AccessIdentityResourceDefinition.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ManagementTransformers.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/Capabilities.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorResource.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AccessConstraintUtilizationTestCase.java
Resolves https://issues.jboss.org/browse/WFCORE-2293
=> [WFCORE-2293] Add sensitivity classifications for attributes referencing Elytron capabilities.

pom.xml
Resolves https://issues.jboss.org/browse/WFCORE-2299
=> [WFCORE-2299] Merge Latest WildFly Elytron Integration Changes

testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliControllerConfigTestCase.java
JIRA: https://issues.jboss.org/browse/WFCORE-1673
JBEAP: https://issues.jboss.org/browse/JBEAP-5432
Added integration tests for server aliases defined in jboss-cli.xml
=> [WFCORE-1673] Integration tests for controller configuration+aliases

controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/operations/validation/NillableOrExpressionParameterValidator.java, controller/src/main/java/org/jboss/as/controller/operations/validation/ParameterValidator.java, controller/src/main/java/org/jboss/as/controller/operations/validation/ParametersOfValidator.java, controller/src/main/java/org/jboss/as/controller/operations/validation/ParametersValidator.java
https://issues.jboss.org/browse/WFCORE-1962
=> [WFCORE-1962] Deprecate ParameterValidator.validateResolvedParameter

pom.xml
Resolves: -
https://issues.jboss.org/browse/WFCORE-2303
https://issues.jboss.org/browse/WFCORE-2304
=> [WFCORE-2303] / [WFCORE-2304] Elytron and Elytron Web Component Upgrades

controller/src/main/java/org/jboss/as/controller/remote/IdentityAddressProtocolUtil.java
https://issues.jboss.org/browse/WFCORE-2312
=> [WFCORE-2312] Don't assume itemCount is always at least 2

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
Fixing the test.
Jira: https://issues.jboss.org/browse/WFCORE-2248
=> [WFCORE-2248]: DeploymentTestCase fails intermittently

server/src/main/resources/schema/wildfly-config_5_0.xsd
https://issues.jboss.org/browse/WFCORE-2313
=> [WFCORE-2313] Add EAP 7.0 and WF 10.1 to host-releaseType

pom.xml
https://issues.jboss.org/browse/WFCORE-2308
https://issues.jboss.org/projects/DMR/versions/12331273
=> [WFCORE-2308] Move to JBoss DMR 1.4.0.Beta2

core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java, testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/events/JmxControlledStateNotificationsTestCase.java, testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/events/ProcessStateListenerTestCase.java
The future is canceled in case of error.
Jira: https://issues.jboss.org/browse/WFCORE-2321
JBEAP: https://issues.jboss.org/browse/JBEAP-8595
=> [WFCORE-2321]: ProcessStateListenerTestCase from wf-core fails intermittently

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java, controller/src/main/java/org/jboss/as/controller/OperationContext.java, controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java, controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java, controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/DomainFinalResultHandler.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointResource.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/logging/RemotingLogger.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/OperationWarningTestsCase.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/warning/OperationWarningTestCase.java
WFCORE: https://issues.jboss.org/browse/WFCORE-1987
=> [WFCORE-1987] - add warning capability to core.

protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
same issue as WFCORE-2292. After testing and looking at the code again, we'll need these here to allow things to work out of the box (or until some other change is in place to supply them).
=> WFCORE-2342 Add back defaults for SSL / TLS connections

core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-management/main/module.xml, domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java, pom.xml, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java
The following can be resoled with this PR: -
https://issues.jboss.org/browse/WFCORE-2355
https://issues.jboss.org/browse/WFCORE-2354
https://issues.jboss.org/browse/WFCORE-2353
=> [WFCORE-2353] WildFly Elytron Component Upgrade and additional integration changes.

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/VaultPasswordsInCLITestCase.java
Seems to pass now, so I'm enabling it.
=> Reenable last remaining test disabled with WFCORE-1958 comment

cli/src/main/resources/help/deployment-overlay.txt
Help changes only, align doc with behaviour.
=> Fix for WFCORE-2358. Fix CLI deployment-overlay help.

pom.xml
Upstream https://github.com/wildfly/wildfly-core/pull/2036
=> [WFCORE-2116 2.x] Update xnio to 3.4.3.

host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainDeploymentOverlayRedeployLinksHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java, server/src/main/java/org/jboss/as/server/deploymentoverlay/AffectedDeploymentOverlay.java, server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayDeploymentRemoveHandler.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DeploymentOverlayTestCase.java
Fixing the way the resource is removed.
Jira: https://issues.jboss.org/browse/WFCORE-2337
=> [WFCORE-2337]: Removal of overlay in a server group fails inside a composite.

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/openssl/main/module.xml
https://issues.jboss.org/browse/WFCORE-2498
https://issues.jboss.org/browse/JBEAP-8543
=> WFCORE-2498 org.wildfly.openssl module should be private

core-feature-pack/src/main/resources/content/bin/standalone.sh
https://issues.jboss.org/browse/WFCORE-2514
=> [WFCORE-2514] add -f flag to gc log mv

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, elytron/pom.xml, elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/IdentityResourceDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/SecurityRealmResourceDecorator.java, elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml, elytron/src/test/resources/org/wildfly/extension/elytron/security-realms.xml, pom.xml
https://issues.jboss.org/browse/WFCORE-2369
https://issues.jboss.org/browse/WFCORE-2393
https://issues.jboss.org/browse/WFCORE-2364
https://issues.jboss.org/browse/WFCORE-2463
https://issues.jboss.org/browse/WFCORE-2539
=> [WFCORE-2539] Upgrade to WildFly Elytron 1.1.0.Beta31 and Latest Integration Work

controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
Fixing wrong attribute names.
Jira: https://issues.jboss.org/browse/WFCORE-2530
=> [WFCORE-2530]: :read-boot-errors() operation does not follow its operation description.

cli/src/main/java/org/jboss/as/cli/handlers/CommandCommandHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/GenericTypeOperationHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Fix generic command generated help to expose the command name.
=> Fix for WFCORE-1534. Generic command name issue

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java, controller/src/main/java/org/jboss/as/controller/services/path/PathAddHandler.java, controller/src/main/java/org/jboss/as/controller/services/path/PathManagerService.java, controller/src/main/java/org/jboss/as/controller/services/path/PathRemoveHandler.java, controller/src/main/java/org/jboss/as/controller/services/path/PathResourceDefinition.java, controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostPathManagerService.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/SyncModelServerStateTestCase.java, host-controller/src/test/java/org/jboss/as/host/controller/util/AbstractControllerTestBase.java, server/src/main/java/org/jboss/as/server/ApplicationServerService.java, server/src/main/java/org/jboss/as/server/ServerPathManagerService.java, server/src/main/java/org/jboss/as/server/ServerService.java
https://issues.jboss.org/browse/WFCORE-1337
=> [WFCORE-1337] Expose paths and the PathManager as capabilities

cli/src/main/java/org/jboss/as/cli/operation/impl/RolloutPlanCompleter.java
Reworked part of completion. The completion content contained some duplications and wrong cases that were making understanding rollout syntax quite challenging.
=> Fix for WFCORE-1496. Fixed rollout completion

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentOperationsTestCase.java
Adding the required permissions.
Jira: https://issues.jboss.org/browse/WFCORE-2538
=> [WFCORE-2538]: DeploymentOperationsTestCase fails with security manager in WF core.

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java, elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java, elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/DomainService.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreService.java, elytron/src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/capabilities/_private/CredentialSecurityFactory.java, elytron/src/main/java/org/wildfly/extension/elytron/capabilities/_private/DirContextSupplier.java, elytron/src/main/java/org/wildfly/extension/elytron/capabilities/_private/SecurityEventListener.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/test/java/org/wildfly/extension/elytron/LdapTestCase.java, pom.xml
:warning: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :warning:
https://issues.jboss.org/browse/WFCORE-2551
https://issues.jboss.org/browse/WFCORE-2461
https://issues.jboss.org/browse/WFCORE-2425
https://issues.jboss.org/browse/WFCORE-2500
https://issues.jboss.org/browse/WFCORE-2542
https://issues.jboss.org/browse/WFCORE-2540
=> [WFCORE-2551] Upgrade to WildFly Elytron 1.1.0.Beta32 and backport latest integration changes.

elytron/src/main/java/org/wildfly/extension/elytron/CredentialSecurityFactoryParser.java, elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java, elytron/src/test/resources/org/wildfly/extension/elytron/credential-security-factories.xml
This pull request resolves the following issue: -
https://issues.jboss.org/browse/WFCORE-2549
=> [WFCORE-2549] Elytron - Unable to configure Kerberos credential factory.

core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
Delayed evaluation and removal of if/else block.
=> Fix for WFCORE-2561. .bat script to handle ) character in arguments

.gitignore, testsuite/domain/pom.xml, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/autoignore/AutoIgnoredResourcesDomainTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/cacheddc/CachedDcDomainTestCase.java, testsuite/domain/src/test/resources/host-configs/host-master-cacheddc.xml, testsuite/domain/src/test/resources/host-configs/host-slave-cacheddc.xml, testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/WildFlyManagedConfiguration.java
Adding testcase for EAP 7.1 RFE EAP7-496
https://issues.jboss.org/browse/EAP7-496
https://issues.jboss.org/browse/WFCORE-316
https://issues.jboss.org/browse/JBEAP-8605
=> [WFCORE-316] adding testcase to check functionality of --cached-dc parameter

controller/src/main/java/org/jboss/as/controller/services/path/ResolvePathHandler.java
add checkAbsolutePath option to the resolve-path builder so that a
resource can customize the operation to ignore the relative-to value if
the path value corresponds to an absolute path.
The default builder does not check the absolute path (no changes to
current behaviour by default).
JIRA: https://issues.jboss.org/browse/WFCORE-2564
=> [WFCORE-2564] Customize resolve-path to handle absolute paths

controller/src/main/java/org/jboss/as/controller/access/rbac/DefaultPermissionFactory.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialSecurityFactoryParser.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreAliasDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResource.java, elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java, elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/IdentityResourceDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/ProviderParser.java, elytron/src/main/java/org/wildfly/extension/elytron/RealmDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java, elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/credential-security-factories.xml, elytron/src/test/resources/org/wildfly/extension/elytron/identity-management.xml, elytron/src/test/resources/org/wildfly/extension/elytron/providers.xml, elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml, pom.xml, remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractStreamServerService.java, server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
:warning: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :warning:
This PR resolves the following issues: -
https://issues.jboss.org/browse/WFCORE-2550
https://issues.jboss.org/browse/WFCORE-2549 (Officially)
https://issues.jboss.org/browse/WFCORE-2546
https://issues.jboss.org/browse/WFCORE-2399
https://issues.jboss.org/browse/WFCORE-2455
https://issues.jboss.org/browse/WFCORE-2163
https://issues.jboss.org/browse/WFCORE-2384
https://issues.jboss.org/browse/WFCORE-2383
https://issues.jboss.org/browse/WFCORE-2071
https://issues.jboss.org/browse/WFCORE-2570
https://issues.jboss.org/browse/WFCORE-2560
https://issues.jboss.org/browse/WFCORE-2572
https://issues.jboss.org/browse/WFCORE-2573
=> [WFCORE-2572] Upgrade WildFly Elytron to 1.1.0.Beta33 and Additional Backports

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java, controller/src/main/java/org/jboss/as/controller/ModelController.java, controller/src/main/java/org/jboss/as/controller/notification/NotificationHandlerRegistry.java, controller/src/main/java/org/jboss/as/controller/registry/NotificationHandlerRegistration.java, controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java, controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java, core-model-test/framework/src/main/java/org/jboss/as/core/model/test/AbstractKernelServicesImpl.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java, host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java, jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java, jmx/src/main/java/org/jboss/as/jmx/MBeanServerService.java, jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanServerPlugin.java, request-controller/src/test/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemTestCase.java, server/src/main/java/org/jboss/as/server/ServerService.java, server/src/main/java/org/jboss/as/server/Services.java, server/src/main/java/org/jboss/as/server/suspend/SuspendController.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractKernelServicesImpl.java
Finish up on https://issues.jboss.org/browse/WFCORE-1507 by exposing a NotificationHandlerRegistry
Now also includes the https://issues.jboss.org/browse/WFCORE-2340 work previously in #2258
=> [WFCORE-1507] Expose NotificationHandler registration via a capability

server/src/main/java/org/jboss/as/server/DomainServerCommunicationServices.java, server/src/main/java/org/jboss/as/server/Services.java, server/src/main/java/org/jboss/as/server/deployment/ContentCleanerService.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java, server/src/main/java/org/jboss/as/server/deployment/ManagedExplodedContentServitor.java
=> [WFCORE-2589][WFCORE-2590] Deprecating org.jboss.as.server.Services

server/src/main/java/org/jboss/as/server/deployment/reflect/DeploymentReflectionIndex.java
https://issues.jboss.org/browse/WFCORE-2593
=> WFCORE-2593 added privileged block to construct ClassReflectionIndex

controller/src/main/java/org/jboss/as/controller/services/path/PathManagerService.java, host-controller/src/main/java/org/jboss/as/host/controller/HostPathManagerService.java, server/src/main/java/org/jboss/as/server/ServerPathManagerService.java
https://issues.jboss.org/browse/WFCORE-2597
=> WFCORE-2597 PathManager not available at ServiceName indicated by its capability

pom.xml
https://issues.jboss.org/browse/WFCORE-2604
=> [WFCORE-2604] Upgrade JBoss DMR to 1.4.0.Final

pom.xml
WFCORE Jira: https://issues.jboss.org/browse/WFCORE-2596
Related JBEAP Jira: https://issues.jboss.org/browse/JBEAP-10000 (really, 10 thousand)
=> [WFCORE-2596] Upgrade PicketBox to 5.0.1.Final

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/DeploymentOverlayScenario.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/DeploymentScenario.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/deployment/ServiceActivatorBaseDeployment.java, testsuite/domain/src/test/resources/domain-configs/domain-rbac.xml, testsuite/domain/src/test/resources/domain-configs/domain-standard.xml, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractLoggingTestCase.java, testsuite/shared/src/main/java/org/jboss/as/test/deployment/trivial/ServiceActivatorDeploymentUtil.java, testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
Fixing all failures due to security manager in core for now.
Jira: https://issues.jboss.org/browse/WFCORE-2534
=> [WFCORE-2534]: SlaveReconnectTestCase fails with security manager in WF core

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java, elytron/pom.xml, elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java, pom.xml
:warning: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :warning:
This PR resolves the following issues: -
https://issues.jboss.org/browse/WFCORE-2571
https://issues.jboss.org/browse/WFCORE-2563
https://issues.jboss.org/browse/WFCORE-2579
https://issues.jboss.org/browse/WFCORE-2393
https://issues.jboss.org/browse/WFCORE-2486
https://issues.jboss.org/browse/WFCORE-2398
https://issues.jboss.org/browse/WFCORE-2433
https://issues.jboss.org/browse/WFCORE-2309
https://issues.jboss.org/browse/WFCORE-2471
https://issues.jboss.org/browse/WFCORE-2602
https://issues.jboss.org/browse/WFCORE-2603
=> [WFCORE-2602] Upgrade WildFly Elytron to 1.1.0.Beta34 and latest integration backport.

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
https://issues.jboss.org/browse/WFCORE-2382
https://issues.jboss.org/browse/JBEAP-8212
=> [WFCORE-2382] credential reference with {EXT} command ignores parameters

elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreAliasDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreParser.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResource.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/PolicyParser.java, elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java, elytron/src/main/java/org/wildfly/extension/elytron/capabilities/CredentialSecurityFactory.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/tls-test.xml, elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml, pom.xml
:warning: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :warning:
This PR resolves the following issues: -
https://issues.jboss.org/browse/WFCORE-2553
https://issues.jboss.org/browse/WFCORE-2574
https://issues.jboss.org/browse/WFCORE-2517
https://issues.jboss.org/browse/WFCORE-2371
https://issues.jboss.org/browse/WFCORE-2556
https://issues.jboss.org/browse/WFCORE-2482
https://issues.jboss.org/browse/WFCORE-2614
https://issues.jboss.org/browse/WFCORE-2625
https://issues.jboss.org/browse/WFCORE-2474
https://issues.jboss.org/browse/WFCORE-2581
https://issues.jboss.org/browse/WFCORE-2635
https://issues.jboss.org/browse/WFCORE-2636
=> [WFCORE-2635] Upgrade WildFly Elytron to 1.1.0.Beta35 and Backport Latest Changes

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Disable history/completion in all "user prompt" scenarii.
=> Fix for WFCORE-2642. CLI History exposed when prompting user

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
https://issues.jboss.org/browse/WFCORE-2659
https://issues.jboss.org/browse/JBEAP-10253
=> [WFCORE-2659] masked password compatibility from previous versions broken

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-web/undertow-server/main/module.xml, elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, pom.xml
⚠️ Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. ⚠️
https://issues.jboss.org/browse/WFCORE-2653
https://issues.jboss.org/browse/WFCORE-2660
https://issues.jboss.org/browse/WFCORE-2661
https://issues.jboss.org/browse/WFCORE-2445
https://issues.jboss.org/browse/WFCORE-2570
=> [WFCORE-2660] Upgrade WildFly Elytron to 1.1.0.Beta36 and backport latest fixes.

controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/AbstractServerDeploymentManager.java, testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentOperationsTestCase.java
The operation wasn't properly executed
Adding some tests
Jira: https://issues.jboss.org/browse/WFCORE-2668
JBEAP: https://issues.jboss.org/browse/JBEAP-10161
=> [WFCORE-2668]: Explode content with DeploymentPlan doesn't work properly

controller/src/main/java/org/jboss/as/controller/operations/validation/EnumValidator.java
Also, deprecate the constructor variants where there user pointlessly configures nullable and allowExpressions
https://issues.jboss.org/browse/WFCORE-2651
=> [WFCORE-2651] Let users pass an EnumSet to the EnumValidator constructor

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
https://issues.jboss.org/browse/JBEAP-9307
https://issues.jboss.org/browse/WFCORE-2475
=> [WFCORE-2475] adding restart-required flag to default-authentication-context attribute

pom.xml
https://issues.jboss.org/browse/WFCORE-2700
=> WFCORE-2700 Wildfly OpenSSL 1.0.0.CR2

pom.xml
https://issues.jboss.org/browse/WFCORE-2698
=> WFCORE-2698 Undertow 1.4.13.Final

testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLIWrapper.java
JBEAP jira: https://issues.jboss.org/browse/JBEAP-10456
WFCORE jira: https://issues.jboss.org/browse/WFCORE-2702
=> [WFCORE-2702] Improve error message in CLI Wrapper in testsuite

controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java, controller/src/test/java/org/jboss/as/controller/ValidateModelTestCase.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentAddHandler.java, host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentUploadUtil.java, host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DeploymentTransformers.java, server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java, server/src/main/java/org/jboss/as/server/controller/resources/DeploymentResourceDefinition.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentAddHandler.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentDeployHandler.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentRedeployHandler.java, server/src/main/java/org/jboss/as/server/deployment/DeploymentRemoveHandler.java, server/src/main/java/org/jboss/as/server/deployment/ExplodedDeploymentAddContentHandler.java
1) https://issues.jboss.org/browse/WFCORE-2317 fix from #2219 
2) https://issues.jboss.org/browse/WFCORE-2674 -- deal with requires + alternatives properly
3) https://issues.jboss.org/browse/WFCORE-2676 -- fix the deployment metadata
=> ValidateModelStepHandler fixes

pom.xml
Kabir:
~Experimental builds:
https://ci.wildfly.org/viewLog.html?buildId=55693&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments
https://ci.wildfly.org/viewLog.html?buildId=55695&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperimentsWindows~
~Replacement experimental builds (had to replace -Dversion.org.wildfly.core=%wildfly.core.version% in the parameters with -Dversion.org.wildfly.core=3.0.0.Beta16 since the full PR has already upgraded to Beta16 which is not released yet)
https://ci.wildfly.org/viewLog.html?buildId=55725&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments 
https://ci.wildfly.org/viewLog.html?buildId=55723&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments …
=> [WFCORE-2696 and others] Multiple component updates

server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
=> Remove unused variable.

domain-management/src/main/java/org/jboss/as/domain/management/security/KeystoreAttributes.java
Reverts wildfly/wildfly-core#2366
=> Revert "Revert "WFCORE-2720 Adding keystore with generate-self-signed-certificate-hos…""

controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java, controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/security/ldap-host-noforce.xml, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/security/ldap-host.xml, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/security/ldap-standalone-noforce.xml, core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/security/ldap-standalone.xml, domain-management/src/main/java/org/jboss/as/domain/management/ModelDescriptionConstants.java, domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionAddHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionManagerService.java, domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionResourceDefinition.java, domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_5.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/config/realm/LdapAuthentication.java
LDAP server
https://issues.jboss.org/browse/WFCORE-2647
=> [WFCORE-2647] Add an option to always send the client SSL certificate to

server/src/main/java/org/jboss/as/server/deployment/jbossallxml/JBossAllXmlParserRegisteringProcessor.java
https://issues.jboss.org/browse/WFCORE-2733
Causes https://issues.jboss.org/browse/JBEAP-10593
=> WFCORE-2733 JBossAllXmlParserRegisteringProcessor leaks deployment unit attachments on undeploy

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java, domain-management/src/main/java/org/jboss/as/domain/management/security/ClientCertCallbackHandler.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java, elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java, pom.xml
The following Jiras can be resolved with this PR: -
https://issues.jboss.org/browse/WFCORE-2478
https://issues.jboss.org/browse/WFCORE-2646
https://issues.jboss.org/browse/WFCORE-2718
https://issues.jboss.org/browse/WFCORE-2716
https://issues.jboss.org/browse/WFCORE-2736
https://issues.jboss.org/browse/WFCORE-2725
=> [WFCORE-2736] Upgrade WildFly Elytron to 1.1.0.Beta39 and backport latest integration changes.

domain-management/src/main/java/org/jboss/as/domain/management/security/LdapGroupSearcherFactory.java
referrals=ignore
https://issues.jboss.org/browse/WFCORE-2341
Related issues:
WF https://issues.jboss.org/browse/WFLY-8231
EAP 7.1 https://issues.jboss.org/browse/JBEAP-9188
EAP 7.0 https://issues.jboss.org/browse/JBEAP-9189
EAP 6.4 https://bugzilla.redhat.com/show_bug.cgi?id=1418685
=> [WFCORE-2341] ldap role should ignore PartialResultException when

elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
Jira issues:
https://issues.jboss.org/browse/WFCORE-2755
https://issues.jboss.org/browse/JBEAP-10708
=> WFCORE-2755: Change Elytron Rotate File Audit log event format to use seconds

elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
https://issues.jboss.org/browse/WFCORE-2614
https://issues.jboss.org/browse/JBEAP-9332
Add test coverage for checking duplicate realm references from Elytron security domain.
=> [WFCORE-2614] add regression test to check adding duplicate realms into an Elytron domain

controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
https://issues.jboss.org/browse/WFCORE-2740
=> [WFCORE-2740] Avoid noChildRegistry failure

pom.xml
https://issues.jboss.org/browse/WFCORE-2773
https://issues.jboss.org/browse/JBEAP-10625
=> [WFCORE-2773] Upgrade Wildfly-Elytron-Tool to 1.0.0.Beta5

elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
https://issues.jboss.org/browse/WFCORE-2772
I don't know if this is right, as I don't know what this service is for but it's the obvious naive fix and it allows the tests failing at https://github.com/wildfly/wildfly/pull/10021 and https://github.com/wildfly/wildfly/pull/10023 to pass.
=> [WFCORE-2772] Remove the 'initial' service too

elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
https://issues.jboss.org/browse/WFCORE-2783
=> [WFCORE-2783] Fix init circularity problem on IBM JDK

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java, pom.xml, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SSLMasterSlaveOneWayTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SSLMasterSlaveTwoWayTestCase.java, testsuite/domain/src/test/resources/host-configs/host-slave-ssl-1way.xml, testsuite/domain/src/test/resources/host-configs/host-slave-ssl-2way.xml
https://issues.jboss.org/browse/WFCORE-2521 and https://issues.jboss.org/browse/JBEAP-8147
https://issues.jboss.org/browse/WFCORE-2781 and https://issues.jboss.org/browse/JBEAP-10809
This pull request is dependent on a tag of JBoss Remoting containing this PR https://github.com/jboss-remoting/jboss-remoting/pull/110
=> [WFCORE-2521] Enable one way and two way SSL test cases in domain mode.

controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ObjectMapAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java, controller/src/main/java/org/jboss/as/controller/operations/global/AbstractCollectionHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/EnhancedSyntaxSupport.java, controller/src/main/java/org/jboss/as/controller/operations/global/ListOperations.java, controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java, controller/src/test/java/org/jboss/as/controller/operation/global/EnhancedSyntaxTestCase.java
https://issues.jboss.org/browse/WFCORE-2670
=> [WFCORE-2670] Deal with undefined values for the final part of enhanced syntax expressions

elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
https://issues.jboss.org/browse/WFCORE-2672
https://issues.jboss.org/browse/JBEAP-10321
=> [WFCORE-2672] JDBC Realm Validation

elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
https://issues.jboss.org/browse/WFCORE-2730
https://issues.jboss.org/browse/JBEAP-10874
=> [WFCORE-2730] allow empty target-name and action in permission

core-feature-pack/src/main/resources/content/bin/elytron-tool.bat, core-feature-pack/src/main/resources/content/bin/elytron-tool.ps1, core-feature-pack/src/main/resources/content/bin/elytron-tool.sh
https://issues.jboss.org/browse/WFCORE-2790
https://issues.jboss.org/browse/JBEAP-10232
=> [WFCORE-2790] WildFly Elytron Tool scripts

cli/src/main/resources/help/module.txt
https://issues.jboss.org/browse/WFCORE-2779
=> [WFCORE-2779] Improve help message in module CLI operation

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java, controller/src/main/java/org/jboss/as/controller/capability/CapabilityServiceSupport.java
https://issues.jboss.org/browse/WFCORE-2810
=> [WFCORE-2810] Let CapabilityServiceSupport users check for caps

cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java, cli/src/main/resources/help/module.txt, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
evolve module add to copy directories or create empty directory if resource doesn't exist.
=> Fix for WFCORE-2765. CLI copy directories when adding modules.

pom.xml
Includes fixes for:
- https://issues.jboss.org/browse/WFCORE-2639
- https://issues.jboss.org/browse/JBEAP-10191
Jiras tracking the component upgrade:
Upstream - https://issues.jboss.org/browse/WFCORE-2835
JBEAP - https://issues.jboss.org/browse/JBEAP-11017
=> [WFCORE-2835] Upgrade PicketBox to 5.0.2.Final

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/cacheddc/CachedDcDomainTestCase.java
Test for CI & flaky logger add.
=> WFCORE-2836 CachedDcDomainTestCase flakyness

elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
https://issues.jboss.org/browse/WFCORE-2852
Partially covers: -
https://issues.jboss.org/browse/JBEAP-9871
=> [WFCORE-2852] Ensure the default cipher suite filter is defined in the model.

pom.xml
https://issues.jboss.org/browse/WFCORE-2854
https://issues.jboss.org/browse/JBEAP-11056
=> [WFCORE-2854] Upgrade Remoting JMX to 3.0.0.Beta5

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/DefaultSaslConfigTestCase.java
https://issues.jboss.org/browse/WFCORE-2834
https://issues.jboss.org/browse/JBEAP-11003
=> [WFCORE-2834] SASL tests for default management interface configuration

pom.xml
https://issues.jboss.org/browse/WFCORE-2856
https://issues.jboss.org/browse/JBEAP-11068
=> [WFCORE-2856] Upgrade WildFly Elytron to 1.1.0.Beta45

controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java, controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/DelegatingImmutableManagementResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ImmutableManagementResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java, controller/src/main/java/org/jboss/as/controller/registry/NodeSubregistry.java, controller/src/test/java/org/jboss/as/controller/registry/ProxyControllerRegistrationUnitTestCase.java, host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
https://issues.jboss.org/browse/WFCORE-2829
Also fixes related issue https://issues.jboss.org/browse/WFCORE-2831
=> [WFCORE-2829] Provide the ProcessType via the ManagementResourceRegistration

pom.xml
https://issues.jboss.org/browse/WFCORE-2866
https://issues.jboss.org/browse/JBEAP-11101
=> [WFCORE-2866] Upgrade WildFly Elytron to 1.1.0.Beta46

pom.xml
https://issues.jboss.org/browse/WFCORE-2871
https://issues.jboss.org/browse/JBEAP-11130
=> [WFCORE-2871] Upgrade WildFly Elytron to 1.1.0.Beta47

pom.xml
https://issues.jboss.org/browse/WFCORE-2868
https://issues.jboss.org/browse/JBEAP-11127
=> [WFCORE-2868] Upgrade Wildfly-Elytron-Tool to 1.0.0.Beta6

testsuite/domain/pom.xml, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AbstractSSLMasterSlaveTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/elytron/SSLElytronMasterSlaveOneWayTestCase.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/elytron/SSLElytronMasterSlaveTwoWayTestCase.java, testsuite/domain/src/test/resources/host-configs/host-master-ssl-1way-elytron.xml, testsuite/domain/src/test/resources/host-configs/host-master-ssl-2way-elytron.xml, testsuite/domain/src/test/resources/host-configs/host-slave-ssl-1way-elytron.xml, testsuite/domain/src/test/resources/host-configs/host-slave-ssl-2way-elytron.xml, testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java
Project Jira: https://issues.jboss.org/browse/WFCORE-2787
Product Jira: https://issues.jboss.org/browse/JBEAP-10826
Planning Jira: https://issues.jboss.org/browse/EAP7-632
Adds two test cases, first for one-way SSL, second for two-way SSL between master and slave.
I run the whole TS before PR, everything looks OK.
=> [WFCORE-2787] SSL+Elytron slave connecting to master tests

cli/src/main/java/org/jboss/as/cli/handlers/BaseOperationCommand.java, cli/src/main/java/org/jboss/as/cli/handlers/ConnectionInfoHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/DeploymentInfoHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/GenericTypeOperationHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/LsHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ReadAttributeHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/ReadOperationHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/jca/JDBCDriverInfoHandler.java, cli/src/main/java/org/jboss/as/cli/util/SimpleTable.java, patching/src/main/java/org/jboss/as/patching/cli/PatchHandler.java, pom.xml
https://issues.jboss.org/browse/WFCORE-2812
Make sure column value is shorter than terminal width in SimpleTable. Check it with terminalWidth from SimpleTable.addLine method while adding a new line.
AESH upgrade issue https://issues.jboss.org/browse/WFCORE-2840 and https://issues.jboss.org/browse/JBEAP-11013
Jansi has been moved back to 1.11 as prod team preference.
~~Please HOLD. After a discussion with Jean-François by email, more work is required for non interactive mode.~~
Decided to not fix the non interactive mode in current release. it will be tracked in https://issues.jboss.org/browse/JBEAP-11048
=> [WFCORE-2812] make sure column value is shorter than terminal width in SimpleTable.

controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientParser.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser.java
* fixing parsing
* fixing typo
Jira: https://issues.jboss.org/browse/WFCORE-2792
=> [WFCORE-2792]: AttributeDefinition.parser is not consistently used in subclasses.

elytron/src/main/resources/subsystem-templates/elytron.xml
https://issues.jboss.org/browse/WFCORE-1802
https://issues.jboss.org/browse/JBEAP-8673
=> [WFCORE-1802] Ensure the providers are registered first so they have priority.

controller/src/main/java/org/jboss/as/controller/operations/global/AbstractCollectionHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/ListOperations.java, core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/CoreManagementExtension.java, core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/CoreManagementSubsystemParser_1_0.java, io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java, logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java, model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingExtension.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem10Parser.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem11Parser.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem12Parser.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem20Parser.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem30Parser.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem40Parser.java, remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemXMLPersister.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractSubsystemTest.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformationUtils.java, subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/extrasubsystem/subsystem/main/MainSubsystemExtension.java, subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/OldExtension.java, subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/TransformerSubsystemTestCase.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/error/ErrorExtension.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/streams/LogStreamExtension.java
- remove long deprecated transformer controllers
=> WFCORE-1237 transformers api cleanup & deprecated usage removal

pom.xml
https://issues.jboss.org/browse/WFCORE-2887
https://issues.jboss.org/browse/JBEAP-11223
=> [WFCORE-2887] Upgrade WildFly Elytron to 1.1.0.Beta48

domain-management/src/main/java/org/jboss/as/domain/management/security/AbstractKeyManagerService.java, domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
https://issues.jboss.org/browse/WFCORE-2879
https://issues.jboss.org/browse/JBEAP-11181
=> [WFCORE-2879][JBEAP-11181] key-password-credential-reference fix

domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserPropertiesFileLoader.java
https://issues.jboss.org/browse/WFCORE-2877
=> [WFCORE-2877] users loading for add-user script fix

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/cacheddc/CachedDcDomainTestCase.java
I've used a JUnit @Rule to run this multiple times in succession both locally and in CI. Seems better now.
=> WFCORE-2836 - better version of verifying the slave has actually deregistered before continuing tests

cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
Fixed recursive link. Added new unit tests. Clean-up files created by test.
=> Fix for WFCORE-2796. CLI, handle symlinks, cover missing cases.

elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/authentication-client.xml, elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
https://issues.jboss.org/browse/WFCORE-2897
https://issues.jboss.org/browse/JBEAP-11236
Need to be merged BEFORE or in coordination with https://github.com/wildfly-security/wildfly-elytron/pull/852
=> [WFCORE-2897] remove match-purpose from Elytron

domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
The password was supposed to be base64 which would break if undefined.
Jira: https://issues.jboss.org/browse/WFCORE-2905
JBEAP: https://issues.jboss.org/browse/JBEAP-11302
=> [WFCORE-2905]: Server-identity/secret integration with credential reference is not correct.

core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml, core-feature-pack/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml, elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
https://issues.jboss.org/browse/WFCORE-2907
https://issues.jboss.org/browse/JBEAP-11259
=> [WFCORE-2907] Ensure the KeyManager is unwrapped if we detect the JVM is running with FIPS enabled.

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
https://issues.jboss.org/browse/WFCORE-2867
https://issues.jboss.org/browse/JBEAP-10650
=> [WFCORE-2867] Credential store reload operation doesn't have effect on dependent resources

pom.xml
https://issues.jboss.org/browse/WFCORE-2910
https://issues.jboss.org/browse/JBEAP-11206
=> [WFCORE-2910] Upgrade Remoting JMX to 3.0.0.Beta6

host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java, testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/LegacySecurityRealmPropagationTestCase.java
Propagating the security realm operations to the running servers on a host.
Jiira: https://issues.jboss.org/browse/WFCORE-2236
JBEAP: https://issues.jboss.org/browse/JBEAP-5963
=> [WFCORE-2236]: Reload required while enabling HTTPS in domain mode.

pom.xml
https://issues.jboss.org/browse/WFCORE-2914 / https://issues.jboss.org/browse/JBEAP-11261
=> [WFCORE-2914] Upgrade undertow to 1.4.16.Final

pom.xml
https://issues.jboss.org/browse/WFCORE-2915
https://issues.jboss.org/browse/JBEAP-11342
=> [WFCORE-2915] Upgrade Wildfly-Elytron-Tool to 1.0.0.Beta7

pom.xml
https://issues.jboss.org/browse/WFCORE-2909
https://issues.jboss.org/browse/JBEAP-11304
=> [WFCORE-2909] Upgrade WildFly Elytron to 1.1.0.Beta50

elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml
https://issues.jboss.org/browse/WFCORE-2898
https://issues.jboss.org/browse/JBEAP-11177
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/853 (required for green build) = upgrade to elytron Beta51
=> [WFCORE-2898] realm-mapper and principal rewritter into server-ssl-context

pom.xml
https://issues.jboss.org/browse/WFCORE-2937
https://issues.jboss.org/browse/JBEAP-11433
=> [WFCORE-2937] Upgrade to WildFly Elytron 1.1.0.Beta52

pom.xml
https://issues.jboss.org/browse/WFCORE-2949
https://issues.jboss.org/browse/JBEAP-11524
=> [WFCORE-2949] Upgrade JBoss Remoting to 5.0.0.CR1

deployment-scanner/src/main/resources/schema/jboss-as-deployment-scanner_1_1.xsd, jmx/src/main/resources/schema/jboss-as-jmx_1_2.xsd, jmx/src/main/resources/schema/jboss-as-jmx_1_3.xsd, remoting/subsystem/src/main/resources/schema/jboss-as-remoting_1_1.xsd, threads/src/main/resources/schema/jboss-as-threads_1_1.xsd
https://issues.jboss.org/browse/WFCORE-2893
=> [WFCORE-2893] Wrong schema version in several xsd files

cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java, cli/src/main/resources/help/deploy.txt, testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeployTestCase.java
Adding enabled flag to be able to distinguish between disabled, enabled or leave as it is.
Jira: https://issues.jboss.org/browse/WFCORE-2939
=> [WFCORE-2939]:  Disabled deployments in server group enabled after WAR is updated

elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
https://issues.jboss.org/browse/WFCORE-2751
=> [WFCORE-2751] Typo aggregateProivdersType in wildfly-elytron_1_0.xsd

controller/src/main/java/org/jboss/as/controller/audit/SyslogAuditLogHandler.java, domain-management/src/main/java/org/jboss/as/domain/management/security/UserDomainCallbackHandler.java
The password resolution using the credential reference wasn't done for DIGEST authentication thus the login failure.
Jira: https://issues.jboss.org/browse/WFCORE-2963
JBEAP: https://issues.jboss.org/browse/JBEAP-11568
=> [WFCORE-2963]: Management/security-realm/authentication/users integration with credential reference is not correct.

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java, controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java, controller/src/main/java/org/jboss/as/controller/ExtensionContext.java, controller/src/main/java/org/jboss/as/controller/OperationContext.java, controller/src/main/java/org/jboss/as/controller/ProcessType.java, controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java, controller/src/main/java/org/jboss/as/controller/RestartParentResourceHandlerBase.java, controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java, controller/src/main/java/org/jboss/as/controller/extension/RuntimeHostControllerInfoAccessor.java, controller/src/main/java/org/jboss/as/controller/operations/global/GlobalInstallationReportHandler.java, controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java, controller/src/test/java/org/jboss/as/controller/ExtensionContextProcessTypeTestCase.java, core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java, deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerExtension.java, host-controller/src/main/java/org/jboss/as/host/controller/operations/HostSpecifiedInterfaceAddHandler.java, jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java, jmx/src/main/java/org/jboss/as/jmx/JmxAuditLogHandlerReferenceResourceDefinition.java, jmx/src/main/java/org/jboss/as/jmx/MBeanServerService.java, jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorAdd.java, jmx/src/main/java/org/jboss/as/jmx/model/MutabilityChecker.java, server/src/main/java/org/jboss/as/server/operations/AbstractInstallationReporter.java, subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java, testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/error/ErrorExtension.java
Also resolves:
WFLY-8923
JBEAP-11489
=> WFCORE-2945 - Code is using ProcessType.HOST_CONTROLLER to identify HC, ignoring EMBEDDED_HOST_CONTROLLER

cli/src/main/java/org/jboss/as/cli/gui/CommandExecutor.java, cli/src/main/java/org/jboss/as/cli/gui/ConnectDialog.java, cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java, cli/src/main/java/org/jboss/as/cli/handlers/UndeployHandler.java, cli/src/main/java/org/jboss/as/cli/impl/CliShutdownHook.java, cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
=> Fix for WFCORE-2962. Name some CLI threads

core-feature-pack/src/main/resources/content/bin/elytron-tool.bat, core-feature-pack/src/main/resources/content/bin/elytron-tool.ps1, core-feature-pack/src/main/resources/content/bin/elytron-tool.sh
https://issues.jboss.org/browse/WFCORE-2976
https://issues.jboss.org/browse/JBEAP-10801
=> [WFCORE-2976] WildFly Elytron Tool, Credential-store command has to have way how to set security provider for custom credential store implementation

domain-management/pom.xml, domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheService.java, domain-management/src/test/java/org/jboss/as/domain/management/security/LdapCacheServiceMockTest.java
WFCORE: https://issues.jboss.org/browse/WFCORE-2502
Downstream (7.2): https://issues.jboss.org/browse/JBEAP-9542
Downstream (7.1): https://issues.jboss.org/browse/JBEAP-9391
Downstream (7.0): https://issues.jboss.org/browse/JBEAP-11350
=> [WFCORE-2502] - Legacy ldap realm,entry for non existing user are cached

pom.xml
https://issues.jboss.org/browse/WFCORE-2986
https://issues.jboss.org/browse/WFCORE-2987
https://issues.jboss.org/browse/WFCORE-2988
https://issues.jboss.org/browse/WFCORE-2989
https://issues.jboss.org/browse/WFCORE-2990
=> Component updates

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Issue: https://issues.jboss.org/browse/JBEAP-11490
Upstream Issue: https://issues.jboss.org/browse/WFCORE-2971
No downstream PR required.
=> WFCORE-2971 - Typo in deprecation warning when adding a deprecated property resource on JGroups protocol

elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java, elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreParser.java, elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java, elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java, elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/RealmDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java, elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java, elytron/src/main/java/org/wildfly/extension/elytron/validators/SizeValidator.java, elytron/src/main/java/org/wildfly/extension/elytron/validators/SuffixValidator.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/audit-logging.xml, elytron/src/test/resources/org/wildfly/extension/elytron/identity-management.xml, elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml, elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml, elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml, elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml, pom.xml
https://issues.jboss.org/browse/WFCORE-2972
https://issues.jboss.org/browse/JBEAP-11459
Also Resolves: -
https://issues.jboss.org/browse/JBEAP-11653
=> [WFCORE-2972] Upgrade WildFly Elytron to 1.1.0.Beta54 and Related PRs

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
https://issues.jboss.org/browse/wildfly-core
Follow-up for #2570
=> [WFCORE-2997] Loop before failing AuditLogBootingSyslogTest

elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java, elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
Jira issues:
https://issues.jboss.org/browse/WFCORE-2928
https://issues.jboss.org/browse/JBEAP-11404
=> WFCORE-2928: Fix error message when a non existing keystore is saved

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveHostControllerAuthenticationTestCase.java, testsuite/domain/src/test/resources/host-configs/host-secrets-elytron-subsystem.xml
tests where server-identity/secret has set credential reference.
Jira: https://issues.jboss.org/browse/WFCORE-2483
JBEAP: https://issues.jboss.org/browse/JBEAP-9321
=> [WFCORE-2483] add test where server-identity/secret is obtained from credential store

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
Touching the the updated deployment file to make sure that the scanner picks it up.
Jira: https://issues.jboss.org/browse/WFCORE-2248
JBEAP: https://issues.jboss.org/browse/JBEAP-8568
=> [WFCORE-2248-bis]: Intermiitent failure in QA

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java, elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java, elytron/src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd, elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml, pom.xml, testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/ExternalMgmtSaslTestCase.java
https://issues.jboss.org/browse/WFCORE-3015
https://issues.jboss.org/browse/WFCORE-3016
https://issues.jboss.org/browse/JBEAP-11801
https://issues.jboss.org/browse/JBEAP-11084
=> [WFCORE-3015] / [WFCORE-3016] Upgrade WildFly Elytron to 1.1.0.Beta55 and Expose principal-decoder as principal-transformer

core-feature-pack/pom.xml, core-feature-pack/src/license/core-feature-pack-licenses.xml, core-feature-pack/src/main/resources/content/docs/licenses/apache software license, version 2.0 - apache-2.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/bouncy castle licence - licence.html, core-feature-pack/src/main/resources/content/docs/licenses/common development and distribution license - cddl.txt, core-feature-pack/src/main/resources/content/docs/licenses/common public license, version 1.0 - cpl-1.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/creative commons attribution 2.5 - jcip-cc-by-2.5.txt, core-feature-pack/src/main/resources/content/docs/licenses/eclipse distribution license, version 1.0 - edl-1.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/eclipse public license, version 1.0 - epl-1.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/gnu general public license, version 2 with the classpath exception - gpl-2.0-ce.txt, core-feature-pack/src/main/resources/content/docs/licenses/gnu lesser general public license, version 2.1 - lgpl-2.1.txt, core-feature-pack/src/main/resources/content/docs/licenses/gnu lesser general public license, version 3 - lgpl-3.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/h2 license, version 1.0 - h2.txt, core-feature-pack/src/main/resources/content/docs/licenses/jdom license - jdom-1.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/licenses.css, core-feature-pack/src/main/resources/content/docs/licenses/licenses.xsl, core-feature-pack/src/main/resources/content/docs/licenses/mozilla public license, version 1.1 - mpl-1.1.txt, core-feature-pack/src/main/resources/content/docs/licenses/public domain - cc0-1.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/the apache software license, version 2.0 - license-2.0.txt, core-feature-pack/src/main/resources/content/docs/licenses/the bsd license - bsd.txt, core-feature-pack/src/main/resources/content/docs/licenses/the jaxen license - license.html, core-feature-pack/src/main/resources/content/docs/licenses/the jsoup mit license - license.html, core-feature-pack/src/main/resources/content/docs/licenses/the mit license - mit.txt
https://issues.jboss.org/browse/WFCORE-3021
=> [WFCORE-3021] Add licenses to the core-feature-pack

logging/src/main/java/org/jboss/as/logging/KnownModelVersion.java, logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
https://issues.jboss.org/browse/WFCORE-2999
=> [WFCORE-2999] Bump the logging subsystem model version.

remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java
* https://issues.jboss.org/browse/WFCORE-3024
* https://issues.jboss.org/browse/JBEAP-11377
=> [WFCORE-3024] - SecurityDomain is lost when setting up remote outbound connections

pom.xml
https://issues.jboss.org/browse/WFCORE-3030
https://issues.jboss.org/browse/WFCORE-3031
https://issues.jboss.org/browse/WFCORE-3032
https://issues.jboss.org/browse/WFCORE-3033
https://issues.jboss.org/browse/JBEAP-11865
https://issues.jboss.org/browse/JBEAP-11869
https://issues.jboss.org/browse/JBEAP-11783
https://issues.jboss.org/browse/JBEAP-11878
=> [WFCORE-3030] WildFly Elytron and related components candidate releases.

cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java, cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java, cli/src/main/java/org/jboss/as/cli/impl/ModelControllerClientFactory.java, controller-client/src/main/java/org/jboss/as/controller/client/ModelControllerClientConfiguration.java, controller-client/src/main/java/org/jboss/as/controller/client/impl/ClientConfigurationImpl.java
https://issues.jboss.org/browse/WFCORE-3034
https://issues.jboss.org/browse/JBEAP-11744
=> [WFCORE-3034] Delay the default SSLContext initialisation until we know it is required.

pom.xml
https://issues.jboss.org/browse/WFCORE-3036
=> [WFCORE-3036] Upgrade JBoss Remoting to 5.0.0.CR4

elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java, pom.xml
https://issues.jboss.org/browse/WFCORE-3037
https://issues.jboss.org/browse/WFCORE-3038
https://issues.jboss.org/browse/JBEAP-11914
https://issues.jboss.org/browse/JBEAP-11916
=> [WFCORE-3037] WildFly Elytron 1.1.0.CR2

domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesFileLoader.java, domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyPatternTestCase.java
https://issues.jboss.org/browse/WFCORE-3053
https://issues.jboss.org/browse/JBEAP-12003
=> [WFCORE-3053] Prevent existing disabled users from being removed when other updates are made to the properties file

domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionAddHandler.java
https://issues.jboss.org/browse/WFCORE-3057
https://issues.jboss.org/browse/JBEAP-12046
required by https://issues.jboss.org/browse/EAP7-724
=> WFCORE-3057

testsuite/domain/src/test/resources/host-configs/host-master-ssl-1way-elytron.xml, testsuite/domain/src/test/resources/host-configs/host-master-ssl-2way-elytron.xml, testsuite/domain/src/test/resources/host-configs/host-slave-ssl-1way-elytron.xml, testsuite/domain/src/test/resources/host-configs/host-slave-ssl-2way-elytron.xml
Upstream issue: https://issues.jboss.org/browse/WFCORE-2787
Downstream issue: https://issues.jboss.org/browse/JBEAP-10826
=> [WFCORE-2787] Fixed bad algorithm for IBM JDK

domain-management/src/main/java/org/jboss/as/domain/management/security/LdapUserSearcherFactory.java
https://issues.jboss.org/browse/WFCORE-1332
=> WFCORE-1332 fixed exception handling for ldap referrals throw scenario

elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
https://issues.jboss.org/browse/JBEAP-11078
https://issues.jboss.org/browse/WFCORE-2932
(no deps)
=> [WFCORE-2932] Elytron tests fix for IBM JDK

elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java, elytron/src/main/java/org/wildfly/extension/elytron/ProviderUtil.java
https://issues.jboss.org/browse/WFCORE-3079
https://issues.jboss.org/browse/JBEAP-12216
=> [WFCORE-3079] fix of Provider loading

testsuite/manualmode/pom.xml, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryImpl.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryTestCase.java
add test for custom-credential-security-factory integration
https://issues.jboss.org/browse/WFLY-8835
=> [WFLY-8835] add test for custom-credential-security-factory integration

elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
https://issues.jboss.org/browse/WFCORE-3076
https://issues.jboss.org/browse/JBEAP-12214
=> [WFCORE-3076] audit endpoints closing on stop

core-feature-pack/src/main/resources/content/bin/domain.bat, core-feature-pack/src/main/resources/content/bin/standalone.bat
Jira: https://issues.jboss.org/browse/WFCORE-3086
=> [WFCORE-3086] standalone.bat restart EAP unexpectedly

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java, elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java, elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties, elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java, elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java, pom.xml
https://issues.jboss.org/browse/WFCORE-3089
https://issues.jboss.org/browse/JBEAP-12265
=> [WFCORE-8089] Upgrade WildFly Elytron to 1.1.0.CR3 and Related PRs

elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/914 (reason of current build failures)
https://issues.jboss.org/browse/WFCORE-3069
https://issues.jboss.org/browse/JBEAP-12113
=> [WFCORE-3069] More digest algorithms into OneTimePassword

elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
Requested trace logging for CredentialStore initialization for better troubleshotting
problems like JBEAP-11821 (WFCORE-3088) and JBEAP-11387
(Fix of reported bug not included)
https://issues.jboss.org/browse/WFCORE-3088
https://issues.jboss.org/browse/JBEAP-11821
=> [WFCORE-3088] CredentialStore initialization trace logging

core-feature-pack/src/main/resources/content/bin/elytron-tool.ps1
https://issues.jboss.org/browse/WFCORE-3080
https://issues.jboss.org/browse/JBEAP-11376
=> [WFCORE-3080] fix t o PS1 script: proper append of script name to the first parameter in the list

pom.xml
https://issues.jboss.org/browse/WFCORE-3101
https://issues.jboss.org/browse/JBEAP-12266
=> Upgrade Wildfly-Elytron-Tool to 1.0.0.CR4

server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
Reverting change that is not needed any more.
https://issues.jboss.org/browse/JBEAP-11693
https://issues.jboss.org/browse/WFCORE-3070
=> [WFCORE-3070] reverting commit 018c775: get standard TrustManager to work in FIPS mode

pom.xml
https://issues.jboss.org/browse/WFCORE-3112
=> [WFCORE-3112] Upgrade DMR to 1.4.1.Final

controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java, testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
The queue should be cleared out of the loop.
Fixes the failing test in #2656
=> [WFCORE-3109]: Only one AuditLogItem is written

version/src/main/java/org/jboss/as/version/ProductConfig.java
https://issues.jboss.org/browse/WFCORE-3115
=> [WFCORE-3115] Close the stream used to read the manifest

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerAuthenticationTestCase.java
=> Ignore intermittently failing test
