elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml

https://issues.redhat.com/browse/WFCORE-5450

[WFCORE-5450] TlsTestCase is failing on IBM JDK

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5495

[WFCORE-5495] Upgrade jboss-invocation from 1.6.0.Final to 1.6.1.Final

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcutil/main/module.xml
elytron/pom.xml
pom.xml
server/pom.xml
testbom/pom.xml
testsuite/standalone/pom.xml

https://issues.redhat.com/browse/WFCORE-5461
Please find release notes and git diff in the JIRA.

[WFCORE-5461] Upgrade bouncycastle to 1.69

---

core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.ps1

https://issues.redhat.com/browse/WFCORE-3825
https://issues.redhat.com/browse/JBEAP-15433

[WFCORE-3825] Unify "-server" option usage for HostController and DomainController in domain.ps1

---

controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java
controller/src/main/java/org/jboss/as/controller/ReloadRequiredWriteAttributeHandler.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/operations/global/WriteAttributeHandler.java
jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-3467

[WFCORE-3467] Require existence of the AttributeDefinition in AbstractWriteAttributeHandler

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh

Issue: https://issues.redhat.com/browse/WFCORE-5353

WFCORE-5353 Multiple syntax issues with 'wildfly-init-redhat.sh'

---

controller/src/main/java/org/jboss/as/controller/access/constraint/SensitiveVaultExpressionConstraint.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/VaultExpressionSensitivityTestCase.java

https://issues.redhat.com/browse/WFCORE-5511

[WFCORE-5511] wildfly-core: Invalid Sensitivity Classification of Vault Expression

---

controller/src/main/java/org/jboss/as/controller/access/constraint/SensitiveVaultExpressionConstraint.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/VaultExpressionSensitivityTestCase.java

https://issues.redhat.com/browse/WFCORE-5511
Upstream PR https://github.com/wildfly/wildfly-core/pull/4668

[16.x] [WFCORE-5511] wildfly-core: Invalid Sensitivity Classification of Vault Expression

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5509

[WFCORE-5509] Upgrade to Byteman 4.0.16

---

domain-management/src/main/java/org/jboss/as/domain/management/access/RbacSanityCheckOperation.java
domain-management/src/main/java/org/jboss/as/domain/management/parsing/AuditLogXml_5.java
domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_4.java
domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_5.java
domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_Legacy.java
domain-management/src/main/java/org/jboss/as/domain/management/security/AuthenticationValidatingHandler.java
domain-management/src/main/java/org/jboss/as/domain/management/security/LdapAuthorizationResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/security/LdapSubjectSupplementalService.java
domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInLoaderService.java
domain-management/src/main/java/org/jboss/as/domain/management/security/SSLServerIdentityResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/PromptPasswordState.java
domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/StateValues.java

PRs split by components, here domain-management
Fixes https://issues.redhat.com/browse/WFCORE-5504

[WFCORE-5504] Check emptiness with Collection.isEmpty() (domain-mng)

---

controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
controller/src/main/java/org/jboss/as/controller/ExpressionResolverImpl.java
controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
controller/src/main/java/org/jboss/as/controller/PathAddress.java
controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java
controller/src/main/java/org/jboss/as/controller/access/management/AccessConstraintDescriptionProviderUtil.java
controller/src/main/java/org/jboss/as/controller/audit/AuditLogHandler.java
controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
controller/src/main/java/org/jboss/as/controller/extension/ExtensionResource.java
controller/src/main/java/org/jboss/as/controller/interfaces/NotInterfaceCriteria.java
controller/src/main/java/org/jboss/as/controller/interfaces/OverallInterfaceCriteria.java
controller/src/main/java/org/jboss/as/controller/interfaces/ParsedInterfaceCriteria.java
controller/src/main/java/org/jboss/as/controller/operations/common/OrderedChildTypesAttachment.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
controller/src/main/java/org/jboss/as/controller/remote/BlockingQueueOperationListener.java
controller/src/main/java/org/jboss/as/controller/services/path/PathManagerService.java
controller/src/main/java/org/jboss/as/controller/transform/RejectExpressionValuesTransformer.java
controller/src/main/java/org/jboss/as/controller/transform/TransformersLogger.java

Fixes https://issues.redhat.com/browse/WFCORE-5504

[WFCORE-5504] Check emptiness with Collection.isEmpty() (Controller)

---

controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/impl/DeploymentSetPlanImpl.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentPlanBuilderImpl.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/bridge/impl/ChildFirstClassLoaderKernelServicesFactory.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainUtil.java

Fixes https://issues.redhat.com/browse/WFCORE-5504

[WFCORE-5504] Check emptiness with Collection.isEmpty() (misc)

---

cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
cli/src/main/java/org/jboss/as/cli/gui/component/StandaloneDeploymentTableModel.java
cli/src/main/java/org/jboss/as/cli/handlers/DeploymentOverlayHandler.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/HelpSupport.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/InteractiveSecurityBuilder.java

Fixes https://issues.redhat.com/browse/WFCORE-5504

[WFCORE-5504] Check emptiness with Collection.isEmpty() (CLI)

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-5513

[WFCORE-5513] Manage the BouncyCastle Jakarta Mail dependency with WildFly Core

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5518
Contains fix for https://issues.redhat.com/browse/WFLY-15041

[WFCORE-5518] Upgrade JBoss Invocation to 1.6.2.Final

---

controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadChildrenTypesHandler.java
controller/src/main/java/org/jboss/as/controller/services/path/PathManagerService.java

[WFCORE-5520] Avoid Nullpointer (Controller)

---

cli/src/main/java/org/jboss/as/cli/handlers/ArchiveHandler.java
cli/src/main/java/org/jboss/as/cli/util/SimpleTable.java

Fixes https://issues.redhat.com/browse/WFCORE-5521

[WFCORE-5521] Close Resource (CLI)

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5534

[WFCORE-5534] Upgrade wildfly-galleon-plugin to 5.2.2.Beta2

---

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/security/RealmIdentityManager.java

[WFCORE-5520] Avoid Nullpointer (domain-http)

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5535

[WFCORE-5535] Upgrade JBoss Invocation to 1.6.3.Final

---

server/src/main/java/org/jboss/as/server/controller/git/ElytronClientSshdSessionFactory.java

[WFCORE-5520] Avoid Nullpointer (Server)

---

io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-4035

[WFCORE-4035] operation-requires-reload message is missing

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java

Fixes https://issues.redhat.com/browse/WFCORE-5521

[WFCORE-5521] Close Resource (Controller)

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java

Fixes https://issues.redhat.com/browse/WFCORE-5521

[WFCORE-5521] Close Resource (bootable-jar)

---

controller/src/main/java/org/jboss/as/controller/ConfigurationChangesCollector.java

Issue: https://issues.redhat.com/browse/WFCORE-5524
The `TreeSet` in `ConfigurationChangesCollector` has issues if there are changes in the same timestamp (this seems to happen more on windows). The [TreeSet](https://docs.oracle.com/javase/8/docs/api/java/util/TreeSet.html) needs the class that implements `Comparable` to be consistent with equals to work properly (and the `ConfigurationChange` class does not fulfill this statement).
The PR substitutes the `TreeSet` with a `Deque` (insertion order). The operation time is assigned when the change is added to the queue to maintain the time coherence in the list. If you prefer something different please let me know.
All tests pass OK in my windows env now.
@ehsavoie Can you please review this PR when you have time?

[WFCORE-5524] *ConfigurationChangesHistoryTestCase fails on Windows

---

server/src/main/java/org/jboss/as/server/deployment/Attachments.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/annotation/AnnotationIndexSupport.java
server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
testsuite/shared/src/main/java/org/jboss/as/test/shared/logging/LoggingUtil.java
testsuite/shared/src/main/java/org/jboss/as/test/shared/logging/TestLogHandlerSetupTask.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/JandexIndexCachingTestCase.java

https://issues.redhat.com/browse/WFCORE-5543

[WFCORE-5543] Operation-scoped caching of static module Jandex indices

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-5547

WFCORE-5547 DistributableWebDeploymentProcessor should run before ModuleSpecProcessor

---

jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
server/src/main/java/org/jboss/as/server/ApplicationServerService.java
threads/src/main/java/org/jboss/as/threads/ThreadFactoryWriteAttributeHandler.java

Issue: https://issues.redhat.com/browse/WFCORE-5502

WFCORE-5502 Fix deprecated constructors

---

server/src/main/java/org/jboss/as/server/deployment/annotation/AnnotationIndexSupport.java
server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java

https://issues.redhat.com/browse/WFCORE-5545
Builds on #4708

[WFCORE-5545] Include module indices computed via class scanning in the ADDITIONAL_ANNOTATION_INDEXES attachment

---

elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java

https://issues.redhat.com/browse/WFCORE-5566

[WFCORE-5566] Fix FIPS detection so that it also works with Java 17

---

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/JandexIndexCachingTestCase.java

* Removing the deployments after running the test.
Jira: https://issues.redhat.com/browse/WFCORE-5568
Supersedes https://github.com/wildfly/wildfly-core/pull/4725#pullrequestreview-741714562

[WFCORE-5568]: Cleaning up deployments after running the test.

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-5565
---
Dev tag: https://github.com/qos-ch/slf4j/releases/tag/v_1.7.32
Diff to previous integrated release: https://github.com/qos-ch/slf4j/compare/v_1.7.30...v_1.7.32

[WFCORE-5565] Upgrade SLF4J 1.7.32

---

core-feature-pack/common/src/main/resources/content/bin/standalone.bat

Issue: https://issues.redhat.com/browse/WFCORE-5546

WFCORE-5546 JAVA_OPTS is not correctly set in standalone.bat

---

elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/WildFlyAcmeClient.java

[WFCORE-5520] Avoid Nullpointer (Elytron)

---

cli/src/main/java/org/jboss/as/cli/gui/component/DomainDeploymentTableModel.java
cli/src/main/java/org/jboss/as/cli/gui/component/StandaloneDeploymentTableModel.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java

[WFCORE-5520] Avoid Nullpointer (CLI)

---

patching/src/main/java/org/jboss/as/patching/runner/PatchModuleInvalidationUtils.java

[WFCORE-5520] Avoid Nullpointer (Patching)

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/invocation/main/module.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-5573
https://issues.redhat.com/browse/WFLY-15023

[WFLY-15023][WFCORE-5573] Upgrade to JBoss Invocation 1.7.0.Final - supports both Javax & Jakarta based artifacts

---

server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
server/src/test/java/org/jboss/as/controller/persistence/GitPersistenceResourceTestCase.java
server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/GitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteHttpGitRepositoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java

https://issues.redhat.com/browse/WFCORE-5465
https://issues.redhat.com/browse/WFCORE-5523

[WFCORE-5465][WFCORE-5523] Git tests fail if git init.defaultBranch is not master

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5574

[WFCORE-5574] Upgrade JBoss Modules from 1.11.0.Final to 1.12.0.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5581

WFCORE-5581 Upgrade Jandex to 2.4.0.Final

---

host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandler.java

[WFCORE-5580] Fix conditional structure (host-controller)

---

server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java

Fixes https://issues.redhat.com/browse/WFCORE-5579

[WFCORE-5579] Fix ModelNode AttributeDefinition equal (server)

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5583
Diff with previous version: https://github.com/wildfly/galleon-plugins/compare/5.2.2.Beta2...5.2.2.Final

Fix for WFCORE-5583, Upgrade galleon-plugins to 5.2.2.Final

---

server/src/main/java/org/jboss/as/server/BootstrapImpl.java

Fixes https://issues.redhat.com/browse/WFCORE-5578

[WFCORE-5578] Avoid unnecessary number boxing (server)

---

host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
process-controller/src/main/java/org/jboss/as/process/ProcessControllerClient.java
process-controller/src/main/java/org/jboss/as/process/ProcessControllerServerHandler.java

Fixes https://issues.redhat.com/browse/WFCORE-5578

[WFCORE-5578] Avoid unnecessary number boxing (process-controller)

---

controller/src/main/java/org/jboss/as/controller/transform/TransformerRegistry.java

Fixes https://issues.redhat.com/browse/WFCORE-5578

[WFCORE-5578] Avoid unnecessary number boxing (Controller)

---

cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestAddress.java

Fixes https://issues.redhat.com/browse/WFCORE-5577

[WFCORE-5577] Iterator next must check end (cli)

---

cli/src/main/java/org/jboss/as/cli/handlers/GenericTypeOperationHandler.java
cli/src/main/java/org/jboss/as/cli/handlers/ResourceCompositeOperationHandler.java
cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/ManagementDisableSSLCommand.java

[WFCORE-5580] Fix conditional structure (cli)

---

controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java

[WFCORE-5580] Fix conditional structure (controller)

---

controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/impl/DeploymentSetPlanImpl.java

[WFCORE-5580] Fix conditional structure (controller-client)

---

subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/xml/JBossEntityResolver.java

[WFCORE-5580] Fix conditional structure (subsystem-test)

---

subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/xml/JBossEntityResolver.java

[WFCORE-5575] Refactor Boolean parsing, Bool object use (subsystem-test)

---

server/src/main/java/org/jboss/as/server/ServerService.java

[WFCORE-5575] Refactor Boolean parsing and Bool object use (server)

---

process-controller/src/main/java/org/jboss/as/process/Main.java

[WFCORE-5575] Refactor Boolean parsing, Bool object use (process-controller)

---

patching/src/main/java/org/jboss/as/patching/installation/LayersConfig.java

[WFCORE-5575] Refactor Boolean parsing and Bool object use (patching)

---

logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser.java

[WFCORE-5575] Refactor Boolean parsing and Bool object use (logging)

---

jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java

[WFCORE-5575] Refactor Boolean parsing and Boolean object usage (jmx)

---

host-controller/src/main/java/org/jboss/as/host/controller/Main.java
host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/parsing/JvmXml.java

[WFCORE-5575] Refactor Boolean parsing and Bool object use (host-controller)

---

domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/AddUser.java
domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/PropertiesFileLoader.java

[WFCORE-5575] Refactor Boolean parsing and Bool object use (domain-management)

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java

[WFCORE-5575] Refactor Boolean parsing and Boolean object use (controller)

---

cli/src/main/java/org/jboss/as/cli/gui/component/DomainDeploymentTableModel.java
cli/src/main/java/org/jboss/as/cli/handlers/ifelse/AndOperation.java
cli/src/main/java/org/jboss/as/cli/handlers/ifelse/OrOperation.java

[WFCORE-5575] Refactor Boolean parsing and Boolean object usage (cli)

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/ee-8-api/src/main/resources/license/core-feature-pack-ee-8-api-licenses.xml

Issue: https://issues.redhat.com/browse/WFCORE-5588

[WFCORE-5588] Synchronize GNU GPL 2 license name with the name used in Wildfly

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

Depends on https://github.com/wildfly/wildfly/pull/14714
https://issues.redhat.com/browse/WFCORE-5589

[WFCORE-5589] Comment out phases used by the legacy security subsystem.

---

elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java

Fixes https://issues.redhat.com/browse/WFCORE-5647
as part of https://issues.redhat.com/browse/WFCORE-5644

[WFCORE-5647] Assertion arguments correct order (elytron)

---

testsuite/domain/pom.xml
testsuite/manualmode/pom.xml

https://issues.redhat.com/browse/WFCORE-5682

[WFCORE-5682] Fix testsuite failures on SE17 when byteman is used

---

elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5694
Test {{RealmsTestCase.testPropertyRealm}} failed in macos because it seems that the FS sets the modification timestamp with second precision. Just adding a loop to wait two seconds for the time change.

[WFCORE-5694] RealmsTestCase fails on Mac

---

server/src/main/java/org/jboss/as/server/DomainServerMain.java

Fixes https://issues.redhat.com/browse/WFCORE-5702

[WFCORE-5702] "StandardCharsets" constants (server)

---

process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
process-controller/src/main/java/org/jboss/as/process/ProcessController.java
process-controller/src/main/java/org/jboss/as/process/ProcessControllerClient.java
process-controller/src/main/java/org/jboss/as/process/ProcessControllerServerHandler.java

Fixes https://issues.redhat.com/browse/WFCORE-5701

[WFCORE-5701] "StandardCharsets" constants (process-controller)

---

controller/src/main/java/org/jboss/as/controller/TemporaryModuleLayer.java

Fixes https://issues.redhat.com/browse/WFCORE-5699

[WFCORE-5699] "StandardCharsets" constants (controller)

---

host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java

Jira issue: https://issues.redhat.com/browse/WFCORE-2806
Test cases are included in https://issues.redhat.com/browse/WFLY-15095

[WFCORE-2806] Global domain config for unique GC log file name and path

---

controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java

Issue: [WFCORE-5676](https://issues.redhat.com/browse/WFCORE-5676)
This code doesn't seem to serve a purpose, the relevant data are always defined on the ObjectList proper while the valueType is a bare-bones definition so we shouldn't be trying to extract data from it.

WFCORE-5676: remove incorrect description resolution

---

elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java

https://issues.redhat.com/browse/WFCORE-5715
https://github.com/wildfly/wildfly-core/pull/4821 updated the Elytron properties realm to check the last modified time of the properties files to see if they need to be reloaded. This PR fixes the WildFly test failures that started occurring with this change.

[WFCORE-5715] Fix permission check failures that occur in the properties realm with the security manager enabled

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5725

[WFCORE-5725] Upgrade to Byteman 4.0.18

---

cli/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5726

Fix for WFCORE-5726, CLI client shaded JAR doesn't aggregate services

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5733
This PR have to be merged after https://github.com/wildfly/wildfly/pull/14993 otherwise WildFly build issues will pop up in CI.

[WFCORE-5733] Upgrade Undertow version to 2.2.14.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5742

[WFCORE-5742] Upgrade WildFly Galleon Plugin to 5.2.7.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5745

[WFCORE-5745] Upgrade JBoss VFS to 3.2.16.Final

---

testsuite/domain/enable-elytron.cli
testsuite/shared/enable-elytron.cli
testsuite/standalone/enable-elytron.cli

https://issues.redhat.com/browse/WFCORE-5651

[WFCORE-5651] Remove management identity's default security domain configuration from testsuite

---

jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerBuilder.java

https://issues.redhat.com/browse/WFCORE-5601

[WFCORE-5601] Update class javadoc for PluggableMBeanServerBuilder

---

pom.xml
testsuite/pom.xml

https://issues.redhat.com/browse/WFCORE-5734

[WFCORE-5734] Set java.io.tmpdir for surefire

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-5750
---
Dev tag: https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.16.0
Diff since previous integrated release: https://github.com/apache/logging-log4j2/compare/rel/2.15.0...rel/2.16.0

[WFCORE-5750] Upgrade log4j to 2.16.0

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFCORE-5750
---
Upstream PR: #4898

[18.x] [WFCORE-5750] Upgrade log4j to 2.16.0

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-5766

[WFCORE-5766] Upgrading to JBoss Modules 2.0.1.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-tool/main/module.xml

Thanks for submitting your Pull Request!
Please delete this text, and add a link to the Jira issue solved by this PR.
Remember to use the Jira issue ID in the PR title, and any commits.
Issue: https://issues.redhat.com/browse/WFCORE-5764

[WFCORE-5764] Can't write/acquire credentials from a store using the elytron-tool script

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5768

[WFCORE-5768] Change default behaviour to resolve jboss parent pom

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5770
Upstream: #4913

[18.x][WFCORE-5770] Upgrade log4j 2 to 2.17.1

---

elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java

https://issues.redhat.com/browse/WFCORE-5758

[WFCORE-5758] Fix RealmsTestCase & TlsTestCase on IBM JDK8

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5771
Diff: https://github.com/jboss-logging/jboss-logging/compare/3.4.2.Final...3.4.3.Final
Tag: https://github.com/jboss-logging/jboss-logging/releases/tag/3.4.3.Final
Upstream #4926

[WFCORE-5771] Upgrade jboss-logging to 3.4.3.Final.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5772
Upstream: https://github.com/wildfly/wildfly-core/pull/4929

[18.x][WFCORE-5772] Upgrade WildFly Elytron to 1.18.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5776
Upstream: https://github.com/wildfly/wildfly-core/pull/4931

[18.x][WFCORE-5776] Upgrade WildFly Elytron to 1.18.3.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5779

WFCORE-5779 Upgrade jandex to 2.4.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5777

[WFCORE-5777] Upgrading to JBoss Modules 2.0.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5786
https://issues.redhat.com/browse/WFCORE-5787
Upstream: https://github.com/wildfly/wildfly-core/pull/4945

[18.x][WFCORE-5786] / [WFCORE-5787] WildFly OpenSSL Component Upgrades

---

cli/pom.xml
component-matrix-builder/pom.xml
core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-add-user/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/process-controller/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/standalone/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/msc/main/module.xml
deployment-scanner/pom.xml
elytron/src/test/java/org/wildfly/extension/elytron/JdkUtils.java
elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
pom.xml
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/OpenSslTlsTestCase.java
testsuite/pom.xml
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/JdkModuleDependencyTestCase.java

https://issues.redhat.com/browse/WFCORE-5788
https://issues.redhat.com/browse/WFCORE-5790
This should not be merged before https://github.com/wildfly/wildfly/pull/15178

[WFCORE-5788] Require a minimum of Java 11

---

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java

https://issues.redhat.com/browse/WFCORE-5800

WFCORE-5800 Remove unused Charset Map Variable and Method in ManagementHttpServer class

---

pom.xml
testbom/pom.xml
testsuite/client-old-server/pom.xml
testsuite/elytron/pom.xml
testsuite/embedded/pom.xml
testsuite/manualmode/pom.xml
testsuite/standalone/pom.xml

https://issues.redhat.com/browse/WFCORE-5804
Requires https://github.com/wildfly/wildfly/pull/15194 to be merged first.

[WFCORE-5804] Move the log4j 1 test dependency to testbom

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5806

[WFCORE-5806] Remove maven.repository.redhat.com repository.

---

controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java

https://issues.redhat.com/browse/WFCORE-5812

[WFCORE-5812] Removing dead code in PathsTestCase

---

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java

https://issues.redhat.com/browse/WFCORE-5814

WFCORE-5814 Use EnumMap in place of HashMap for enum keys; code cleanup

---

cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java

https://issues.redhat.com/browse/WFCORE-5815

WFCORE-5815 StringBuilder op in CommandContextImpl is created and updated but never used

---

controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_parent_remove.yml

*  Fixing YAML remove operation: instead of appending a detele operation we are deleting all the
operations on the resource and sub-resources from the boot operations.
Jira: https://issues.redhat.com/browse/WFCORE-5818

[WFCORE-5818]:  !remove might not work properly with some resources

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5768
Upstream
https://github.com/wildfly/wildfly-core/pull/4920

[18.x][WFCORE-5768] Change default behaviour to resolve jboss parent pom

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5745
https://issues.redhat.com/browse/WFCORE-5751
https://issues.redhat.com/browse/WFCORE-5779
https://issues.redhat.com/browse/WFCORE-5785
https://issues.redhat.com/browse/WFCORE-5797

WFCORE-5745 WFCORE-5751 WFCORE-5779 WFCORE-5785 WFCORE-5797 Port component upgrades from main to 18.x

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5824

[WFCORE-5824] Upgrade log4j2 2.17.2

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5826

[WFCORE-5826] Upgrade WildFly Common to 1.6.0.Final

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5824
Upstream
https://github.com/wildfly/wildfly-core/pull/4990

[18.x][WFCORE-5824] Upgrade log4j2 2.17.2

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5825

[WFCORE-5825] Upgrade slf4j 1.7.36

---

pom.xml

Signed-off-by: James R. Perkins <jperkins@redhat.com>
https://issues.redhat.com/browse/WFCORE-5790

[WFCORE-5790] Upgrade jboss-parent from 37 to 39

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5825
Upstream
https://github.com/wildfly/wildfly-core/pull/4992

[18.x][WFCORE-5825] Upgrade slf4j 1.7.36

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5826
Upstream: #4994

[18.x][WFCORE-5826] Upgrade WildFly Common to 1.6.0.Final

---

core-feature-pack/galleon-common/src/main/resources/layers/standalone/core-tools/layer-spec.xml

https://issues.redhat.com/browse/WFCORE-5827

[WFCORE-5827] Add elytron-tool to the core-tools layer definition

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java

Also update the @Ignore handling for things left for WFCORE-5522 to reflect that WFCORE-5799 now tracks their resolution
https://issues.redhat.com/browse/WFCORE-5798

[WFCORE-5798] Restore ReloadRedirectTestCase.testReloadwithRedirect

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/XmlCompletionScanner.java
host-controller/src/main/java/org/jboss/as/host/controller/discovery/S3Util.java
model-test/src/main/java/org/jboss/as/model/test/MavenSettings.java
security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SchemaValidator.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java

Fixes https://issues.redhat.com/browse/WFCORE-5594
Upstream https://github.com/wildfly/wildfly-core/pull/4772

[18.x][WFCORE-5594] Restriction of XML External Entity Reference (XXE)

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/XmlCompletionScanner.java
host-controller/src/main/java/org/jboss/as/host/controller/discovery/S3Util.java
model-test/src/main/java/org/jboss/as/model/test/MavenSettings.java
security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SchemaValidator.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java

Fixes https://issues.redhat.com/browse/WFCORE-5594

[WFCORE-5594] Restriction of XML External Entity Reference (XXE)

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml

* adding 'org.wildfly.common' to the deployment scanner module.xml
Jira: https://issues.redhat.com/browse/WFCORE-5834

[WFCORE-5834]: The deployent-scanner needs org.wildfly.common

---

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-4867
Upstream: https://github.com/wildfly/wildfly-core/pull/4747

[WFCORE-4867] Highlight the config name in start message

---

elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java

https://issues.redhat.com/browse/WFCORE-5858

[WFCORE-5858] Move away from the deprecated GSSCredentialSecurityFactory.

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
controller/src/main/java/org/jboss/as/controller/ExpressionResolver.java
controller/src/main/java/org/jboss/as/controller/ExpressionResolverExtension.java
controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
controller/src/main/java/org/jboss/as/controller/extension/ExpressionResolverExtension.java
controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
controller/src/main/java/org/jboss/as/controller/extension/ResolverExtensionRegistry.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
elytron/src/main/java/org/wildfly/extension/elytron/ExpressionResolverResourceDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/expression/DeploymentExpressionResolverProcessor.java
elytron/src/main/java/org/wildfly/extension/elytron/expression/ElytronExpressionResolver.java
elytron/src/main/java/org/wildfly/extension/elytron/expression/ExpressionResolverRuntimeHandler.java
elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
server/src/main/java/org/jboss/as/server/RuntimeExpressionResolver.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/operations/SystemPropertyAddHandler.java
server/src/main/java/org/jboss/as/server/operations/SystemPropertyDeferredProcessor.java
server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
server/src/test/java/org/jboss/as/server/operations/SystemPropertyAddHandlerUnitTestCase.java
server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractKernelServicesImpl.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/expression/SystemPropertyExpressionTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-5490
Upstream: https://github.com/wildfly/wildfly-core/pull/4925

[18.x][WFCORE-5490] Integrate Elytron credential expressions into system-property resource handling

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser15_1.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_15_1.xsd
elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-expressions.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/M/MF2HI4TJMJ2XIZKVONSXE.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4Q.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4RR.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4SFOZSXE6LUNBUW4ZY.xml
elytron/src/test/resources/org/wildfly/extension/elytron/mycredstore.cs
elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml

Jira: https://issues.redhat.com/browse/WFCORE-5530
To pass CI, this will require an Elytron upgrade.
Analysis document: https://github.com/wildfly/wildfly-proposals/pull/421
Requires: https://issues.redhat.com/browse/ELY-2078
Elytron PR with tests: https://github.com/wildfly-security/wildfly-elytron/pull/1676
WildFly PR with tests and documentation updates: https://github.com/wildfly/wildfly/pull/15269

[WFCORE-5530] Add encryption support to FilesystemSecurityRealm

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser15_1.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/main/resources/schema/wildfly-elytron_15_1.xsd
elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-expressions.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/M/MF2HI4TJMJ2XIZKVONSXE.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4Q.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4RR.xml
elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4SFOZSXE6LUNBUW4ZY.xml
elytron/src/test/resources/org/wildfly/extension/elytron/mycredstore.cs
elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml

https://issues.redhat.com/browse/WFCORE-5530
Upstream: https://github.com/wildfly/wildfly-core/pull/4983

[18.x][WFCORE-5530] Add encryption support to FilesystemSecurityRealm 

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5777
Upstream
https://github.com/wildfly/wildfly-core/pull/4933

[18.x][WFCORE-5777] Upgrading to JBoss Modules 2.0.2.Final

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml

Issue: https://issues.redhat.com/browse/WFCORE-5810

WFCORE-5810 Fix license in wildfly-cli jar.

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5759
Please find release notes and diff link in the Jira.

[WFCORE-5759] Upgrade bouncycastle from 1.69 to 1.70

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-5829

[WFCORE-5829] Upgrade JBoss Remoting to 5.0.24.Final

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-5829
https://github.com/wildfly/wildfly-core/pull/5030 backporting to 18.x
@fl4via , could you approve? thanks!

[18.x][WFCORE-5829] Upgrade JBoss Remoting to 5.0.24.Final

---

.gitleaks.toml

https://issues.redhat.com/browse/WFCORE-5865

[WFCORE-5865] Add .gitleaks.toml file with allowlist

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5877

Fix for WFCORE-5877, Upgrade galleon plugins to 5.2.11.Final

---

core-feature-pack/common/src/main/resources/content/bin/standalone.sh

https://issues.redhat.com/browse/WFCORE-5871

WFCORE-5871 Invalid operator error launching the server in dash

---

.github/workflows/dep-diff-pull_request.yml

https://issues.redhat.com/browse/WFCORE-5862

WFCORE-5862 Excessive output regarding downloads when project built

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5888

[WFCORE-5888] Upgrade httpcore to 4.4.15

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5888
Upstream https://github.com/wildfly/wildfly-core/pull/5073

[18.x][WFCORE-5888] Upgrade httpcore to 4.4.15

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcprov/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcutil/main/module.xml
elytron/pom.xml
pom.xml
server/pom.xml
testsuite/standalone/pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-5874

[WFCORE-5874] Upgrade bouncycastle to 1.71

---

server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/deployment/module/ClassTransformerProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/DelegatingClassTransformer.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/ModuleStructureSpec.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

fixes https://issues.redhat.com/browse/WFCORE-3685

[WFCORE-3685] switch_to_using_org.jboss.modules.ClassTransformer

---

controller/src/main/java/org/jboss/as/controller/capability/registry/RequirementRegistration.java

https://issues.redhat.com/browse/WFCORE-5892

WFCORE-5892 IndexOutOfBoundsException in RequirementRegistration.getOldestRegistrationPoint() during sequence of resource removals

---

cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProviderTestCase.java
cli/src/test/java/org/jboss/as/cli/parsing/test/PropertyReplacementTestCase.java
cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
cli/src/test/java/org/jboss/as/cli/parsing/test/VariablesTestCase.java

Assertion arguments should be passed in the correct order (cli)
Fixes https://issues.redhat.com/browse/WFCORE-5649

[WFCORE-5649] Assertion arguments should be passed correct (cli)

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

https://issues.redhat.com/browse/WFCORE-5896

[WFCORE-5896] Remove AuthConfigFactory wrapping, this was used to co-exist with PicketBox.

---

core-feature-pack/galleon-common/src/main/resources/feature_groups/host-profile.xml
testsuite/domain/src/test/resources/host-configs/host-master-elytron-no-legacy-realms.xml
testsuite/domain/src/test/resources/host-configs/host-master-ssl-1way-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-master-ssl-2way-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-slave-elytron-no-legacy-realms.xml
testsuite/domain/src/test/resources/host-configs/host-slave-ssl-1way-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-slave-ssl-2way-elytron.xml
testsuite/domain/src/test/resources/host-configs/respawn-master-http.xml
testsuite/domain/src/test/resources/host-configs/respawn-master.xml

Issue: https://issues.redhat.com/browse/WFCORE-5890

[WFCORE-5890] There is a possible typo in Management Realm definition in default host.xml configuration

---

core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
core-model-test/tests/src/test/java/org/jboss/as/core/model/test/boot/StandaloneBootErrorsTestCase.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServices.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java

Issue: https://issues.redhat.com/browse/WFCORE-5320

[WFCORE-5320] ModelTestKernelServices providing BootErrorCollector info

---

elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/SecretKeyCredentialStoreDefinition.java

Issue: [WFCORE-5907](https://issues.redhat.com/browse/WFCORE-5907)

WFCORE-5907: fix runtime handling of secret-key-credential-store

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5915

[WFCORE-5915] Upgrading to JBoss Modules 2.0.3.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5916

[WFCORE-5916] Upgrade JBoss VFS to 3.2.17.Final

---

testsuite/domain/src/test/resources/mgmt-users/mgmt-groups.properties

Issue: https://issues.redhat.com/browse/WFCORE-5919

WFCORE-5919 Duplicate Properties in mgmt-user

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5926

[WFCORE-5926] Upgrade to Byteman 4.0.19

---

controller/src/main/java/org/jboss/as/controller/operations/validation/IntAllowedValuesValidator.java
elytron/src/main/java/org/wildfly/extension/elytron/SecretKeyCredentialStoreDefinition.java

https://issues.redhat.com/browse/WFCORE-5914

[WFCORE-5914] Elytron - key-size of secret-key-credential-store is not validated

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml

https://issues.redhat.com/browse/WFCORE-5929

[WFCORE-5929] Prepare io.undertow.core module for upcoming upgrade of Undertow in WildFly preview

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java

* Fixing issue with placeholder resources that should be added instead
of written.
Jira: https://issues.redhat.com/browse/WFCORE-5918

[WFCORE-5918]: Adding SSO to application security domain via YamlConfigurationExtension doesn't work.

---

core-management/core-management-subsystem/src/main/resources/org/wildfly/extension/core/management/LocalDescriptions.properties
server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties

https://issues.redhat.com/browse/WFCORE-5932

WFCORE-5932 Incorrect values for keys in LocalDescriptions.properties files

---

deployment-repository/src/test/resources/lockDeployment.btm

https://issues.redhat.com/browse/WFCORE-5934

[WFCORE-5934] Fixing DeletionCollisionTest byteman rule file to properly match method signature

---

controller/src/test/java/org/jboss/as/controller/ModelControllerLockTestCase.java

Fixes https://issues.redhat.com/browse/WFCORE-5933

[WFCORE-5933] JUnit assertions should not be used in "run" methods

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java

* Adding support for MapAttributeDefinition in YamlConfigurationExtension
Jira: https://issues.redhat.com/browse/WFCORE-5949

[WFCORE-5949]: Adding meta-data to json-logger via YamlConfigurationExtension results in ClassCastException.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5951

[WFCORE-5951] Upgrade JBoss Marshalling to 2.1.0.Final

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java

Issue: https://issues.redhat.com/browse/WFCORE-5927

WFCORE-5927 Misleading message for embedded server configuration file.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5959

[WFCORE-5959] Upgrade Jandex to 2.4.3.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java

https://issues.redhat.com/browse/WFCORE-5969

[WFCORE-5969] Add more descriptive message for Elytron key-store generate-key-pair X.500 distinguished name related failure

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-5971
[WFCORE-5971] Upgrade commons-lang3 from 3.11 to 3.12.0

[WFCORE-5971] Upgrade commons-lang3 from 3.11 to 3.12.0

---

core-feature-pack/galleon-common/src/main/resources/feature_groups/io.xml

https://issues.redhat.com/browse/WFCORE-5973
Remove declaration of buffer-pool

[WFCORE-5973] Update BufferPool to use Undertow's

---

host-controller/src/main/java/org/jboss/as/host/controller/HostPathManagerService.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java

jira issue: https://issues.redhat.com/browse/WFCORE-5960

[WFCORE-5960] Fix bug initializing Domain Base Dir for path Manager

---

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java
controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
controller/src/main/java/org/jboss/as/controller/registry/AttributeAccess.java
controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java

https://issues.jboss.org/browse/WFCORE-4611

WFCORE-4611 Complete AttributeDefinition.getImmutableFlags() -> getFlags() transition

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java

https://issues.redhat.com/browse/WFCORE-6029

[WFCORE-6029] Eliminating deprecated and unused DeploymentPhaseContext.addDependency(ServiceName,Class,Injector) method

---

controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java
domain-management/src/test/java/org/jboss/as/domain/management/security/util/ManagementControllerTestBase.java
jmx/src/test/java/org/jboss/as/jmx/auditlog/JmxAuditLogHandlerTestCase.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java

https://issues.redhat.com/browse/WFCORE-5986

[WFCORE-5986] Fixing StabilityMonitor usages in tests

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyPolicyTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java

Jira issue: https://issues.redhat.com/browse/WFCORE-5987
In addition, removed old code commented

[WFCORE-5978] Mitigate issues getting the process exist code on AdminOnlyPolicyTestCase

---

jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java

Fixes https://issues.redhat.com/browse/WFCORE-5851

[WFCORE-5851] Null pointers should not be dereferenced (jmx)

---

pom.xml

https://issues.redhat.com/browse/WFCORE-5916
In relation to https://issues.redhat.com/browse/WFLY-16322, particularly https://issues.redhat.com/browse/WFLY-16322?focusedCommentId=20678937&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20678937

[18.x][WFCORE-5916] Upgrade JBoss VFS to 3.2.17.Final

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyPolicyTestCase.java

Upstream: #5179
See https://issues.redhat.com/browse/WFCORE-6032

[WFCORE-6032] Ignore AdminOnlyPolicyTestCase

---

pom.xml

Jira Issue: https://issues.redhat.com/browse/WFCORE-6042

[WFCORE-6042] Upgrade to Elytron EE 3.0.0.Beta4

---

pom.xml

Built on top of https://github.com/wildfly/wildfly-core/pull/5198
Jira issue: https://issues.redhat.com/browse/WFCORE-6043

[WFCORE-6043] Use WildFly Core to distribute all the elytron-ee dependencies required in WildFly

---

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ThreadDumpUtil.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java

https://issues.redhat.com/browse/WFCORE-5968

[WFCORE-5968] log thread dump upon management timeout

---

pom.xml

*  Upgrading Snakeyaml to 1.31
Jira: https://issues.redhat.com/browse/WFCORE-6046

[WFCORE-6046]: Upgrading Snakeyaml to 1.31

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/io/smallrye/jandex/main/module.xml
pom.xml
server/pom.xml
testsuite/shared/pom.xml

https://issues.redhat.com/browse/WFCORE-6037

[WFCORE-6037] Upgrade to Jandex 3.0.0

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-6034

[WFCORE-6034] Upgrade log4j2 2.19.0

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6059

[WFCORE-6059] Upgrade Jandex to 3.0.1

---

core-feature-pack/galleon-common/src/main/resources/feature_groups/core-host-secondary.xml

https://issues.redhat.com/browse/WFCORE-6058

[WFCORE-6058] The host-secondary.xml should also contain an example specifying the username and password.

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFLY-14947
Allocate Phase ID for new module in WFLY

[WFLY-14947] Implement the Observability policy - Metrics

---

server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java

https://issues.redhat.com/browse/WFCORE-6064

[WFCORE-6064] SubDeploymentUnitService wasn't intended to be a public class

---

server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentProcessor.java

https://issues.redhat.com/browse/WFCORE-6065

[WFCORE-6065] Eliminating unused AbstractDeploymentUnitService.deployerChainsInjector field

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyModeTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ReadOnlyModeTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SimpleDomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/SlaveReconnectTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HcExtensionAndSubsystemManagementTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HostLifecycleWithRolloutPlanTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesProfileCloneTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/OutboundLdapConnectionTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java

https://issues.redhat.com/browse/WFCORE-3373
Changes in tests are here as proof of functionality and will be removed later.

[WFCORE-3373] DomainLifecycleUtil HC reload API

---

pom.xml

* upgrade snakeyaml to 1.33
Jira: https://issues.redhat.com/browse/WFCORE-6071

[WFCORE-6071]: Upgrade snakeyaml to 1.33.

---

server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentProcessor.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java

https://issues.redhat.com/browse/WFCORE-6066

[WFCORE-6066] Rewriting DeploymentUnitServices to use MSC values API

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-6083

[WFCORE-6083] Upgrade Google guava to 31.1-jre

---

testbom/pom.xml

https://issues.redhat.com/browse/WFCORE-6085

[WFCORE-6085] Upgrade the Jackson test dependency to 2.13.4

---

bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
cli/src/main/java/org/jboss/as/cli/handlers/ArchiveHandler.java
patching/src/main/java/org/jboss/as/patching/ZipUtils.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6082

[WFCORE-6082] Verify the path when unzipping zip files

---

testbom/pom.xml

https://issues.redhat.com/browse/WFCORE-6088

[WFCORE-6088] Upgrade Jackson databind to 2.13.4.1.

---

server/src/main/java/org/jboss/as/server/mgmt/domain/ExtensibleHttpManagement.java

https://issues.redhat.com/browse/WFCORE-6092

[WFCORE-6092] Remove deprecation of ExtensibleHttpManagement

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6039

[WFCORE-6039] Upgrading JBoss MSC to 1.5.0.Beta3

---

pom.xml

Fixes https://issues.redhat.com/browse/WFCORE-6084

[WFCORE-6084] Upgrade bouncycastle from 1.71 to 1.72

---

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/ObjectMapAttributeDefinition.java
controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
logging/src/main/java/org/jboss/as/logging/PropertyObjectTypeAttributeDefinition.java

Issue: https://issues.redhat.com/browse/WFCORE-6080

WFCORE-6080 Remove AttributeDefinition.isAllowNull

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcprov/main/module.xml
pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6105
built on top of #5261

[WFCORE-6105] Upgrade Bouncycastle OpenPGP from 1.72 to 1.72.1

---

SECURITY.md

Add security instructions

---

testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java

https://issues.redhat.com/browse/WFCORE-6094
PR depends on https://github.com/wildfly/wildfly/pull/16242

[WFCORE-6094] Increase LayersTest timeout

---

core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/classfilewriter/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/invocation/main/module.xml
pom.xml
server/pom.xml

https://issues.redhat.com/browse/WFCORE-6097
https://issues.redhat.com/browse/WFCORE-6098

[WFCORE-6097][WFCORE-6098] Upgrade JBoss Class File Writer to 1.3.0.Final and JBoss Invocation to 2.0.0.Final

---

testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/handlers/RotatingFileHandlerTestCase.java

Issue: [WFCORE-5955](https://issues.redhat.com/browse/WFCORE-5955)

WFCORE-5955: fix periodic log test case

---

controller-client/src/main/java/org/jboss/as/controller/client/impl/RemotingModelControllerClient.java

https://issues.redhat.com/browse/WFCORE-6119

[WFCORE-6119] Make the RemotingModelControllerClient constructor private

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6123

[WFCORE-6123] Upgrading JBoss MSC to 1.5.0.Beta4

---

server/src/main/java/org/jboss/as/server/AbstractDeploymentChainStep.java
server/src/main/java/org/jboss/as/server/DeploymentProcessorTarget.java

https://issues.redhat.com/browse/WFCORE-6112

[WFCORE-6112] Remove deprecated DeploymentProcessorTarget method

---

subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractSubsystemBaseTest.java

https://issues.redhat.com/browse/WFCORE-5980
PR depends on https://github.com/wildfly/wildfly/pull/16252

[WFCORE-5980] Deprecate / disable AbstractSubsystemBaseTest 'subsystem template' handling

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6110

[WFCORE-6110] Upgrade Jandex to 3.0.3

---

deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java

https://issues.redhat.com/browse/WFCORE-6121
https://issues.redhat.com/browse/WFCORE-6122

[WFCORE-6121][WFCORE-6122] Various ContentRepositoryImpl fixes

---

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-4902

[WFCORE-4902] Console availability message printing always before the boot statistics

---

elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SecurityDomainLockReleaseTest.java

https://issues.redhat.com/browse/WFCORE-6125

[WFCORE-6125] Stuck server after invoking update-key-pair on filesystem-realm

---

controller/src/main/java/org/jboss/as/controller/CurrentOperationIdHolder.java

https://issues.redhat.com/browse/WFCORE-6139

[WFCORE-6139] Minor CurrentOperationIdHolder cleanups

---

request-controller/src/test/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemTestCase.java
server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/Services.java
server/src/main/java/org/jboss/as/server/suspend/SuspendController.java

https://issues.redhat.com/browse/WFCORE-6140

[WFCORE-6140] SuspendController service name cleanup

---

subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/OtherServicesSubsystemTestCase.java

https://issues.redhat.com/browse/WFCORE-6141

[WFCORE-6141] Fixing transient test failures

---

network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
server/src/main/java/org/jboss/as/server/services/net/BindingRuntimeHandlers.java

https://issues.redhat.com/browse/WFCORE-6145
https://issues.redhat.com/browse/WFCORE-6146

WFCORE-6145/WFCORE-6146  SocketBindingManager fixes wrt socket channels

---

controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
controller/src/main/java/org/jboss/as/controller/SubsystemRegistration.java
controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/transform/description/ChainedTransformationDescriptionBuilder.java
controller/src/main/java/org/jboss/as/controller/transform/description/ChainedTransformationDescriptionBuilderImpl.java
controller/src/main/java/org/jboss/as/controller/transform/description/TransformationDescription.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/NewExtension.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/OldExtension.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/TransformerSubsystemTestCase.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtension2.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtensionCommon.java
subsystem-test/tests/src/test/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/ExtensionSetup.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/VersionedExtension2.java

https://issues.redhat.com/browse/WFCORE-6133

[WFCORE-6133] Remove deprecated Extension API members

---

host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
server/src/main/java/org/jboss/as/server/BootstrapListener.java
server/src/main/java/org/jboss/as/server/ServerService.java

Fixes https://issues.redhat.com/browse/WFCORE-6130

[WFCORE-6130] Bootstrap Exceptions unchained

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-6108

[WFCORE-6108] Add a new Phase constant to install global EJB client interceptors

---

network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
server/src/main/java/org/jboss/as/server/services/net/BindingRuntimeHandlers.java

https://issues.redhat.com/browse/WFCORE-6145
https://issues.redhat.com/browse/WFCORE-6146

WFCORE-6145/WFCORE-6146 SocketBindingManager fixes wrt socket channels

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-6152
Add Phase constants for MP Telemetry

[WFCORE-6152] Implement Support for MicroProfile Telemetry

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java

* snakeyaml: Constructor Deserialization Remote Code Execution.
* Removing the code that would try the deserialization
Jira: https://issues.redhat.com/browse/WFCORE-6169

[WFCORE-6169]: Disable YAML deserialization in the YAML Configuration Extension

---

pom.xml
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
testsuite/domain/src/test/resources/byteman-scripts/byteman.policy

Fixes https://issues.redhat.com/browse/WFCORE-6099
Upstream https://github.com/wildfly/wildfly-core/pull/5253

[WFCORE-6099] Upgrade Byteman to 4.0.20

---

server/src/main/java/org/jboss/as/server/parsing/CommonXml.java

https://issues.redhat.com/browse/WFCORE-6150

[WFCORE-6150] Remove deprecated CommonXml methods

---

controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/InitialDeploymentPlanBuilder.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/InitialDeploymentSetBuilder.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/impl/InitialDeploymentSetBuilderImpl.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/DeploymentPlanBuilder.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/InitialDeploymentPlanBuilder.java
controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentPlanBuilderImpl.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6174

[WFCORE-6174] Remove deprecated deployment plan builder methods

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

Issue: https://issues.redhat.com/browse/WFCORE-6116

WFCORE-6116 Remove deprecated Phase constants.

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/EncodingPersistenceTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6177

[19.x][WFCORE-6177] Remove test property added by EncodingPersistenceTestCase

---

controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java

Issue: https://issues.redhat.com/browse/WFCORE-6183

[WFCORE-6183] Remove PersistentResourceDefinition.Parameters

---

testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/InterdependentDeploymentTestCase.java

https://issues.redhat.com/browse/WFCORE-2209

[WFCORE-2209] Rework InterdependentDeploymentTestCase once special system prop enablement of WFCORE-2192 fix isn't needed

---

.github/workflows/dep-diff-pull_request.yml
.github/workflows/dep-diff-workflow_run.yml
.github/workflows/stale.yml

https://issues.redhat.com/browse/WFCORE-6185

WFCORE-6185 Upgrade github actions to avoid github action warnings

---

server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java

https://issues.redhat.com/browse/WFCORE-6188

[WFCORE-6188] Eliminating useless locking in ServiceModuleLoader causing performance degradation

---

core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ConfigurationChangeResourceDefinition.java
server/src/main/java/org/jboss/as/server/deployment/ContentServitor.java
server/src/main/java/org/jboss/as/server/deployment/PathContentServitor.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/dependent/RootResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6193

[WFCORE-6193] Eliminating usage of deprecated org.jboss.msc.service.AbstractService

---

host-controller/pom.xml
host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryService.java
host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java
protocol/src/main/java/org/jboss/as/protocol/mgmt/ActiveOperationImpl.java
server/src/main/java/org/jboss/as/server/BootstrapImpl.java
server/src/main/java/org/jboss/as/server/FutureServiceContainer.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/mgmt/domain/ServerBootOperationsService.java

Fixes https://issues.redhat.com/browse/WFCORE-6131

[WFCORE-6131] AsyncFutureTask fail ensure Exception presence

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AbstractConfigurationChangesTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyModeTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/OperationTimeoutTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ProductInfoUnitTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerManagementTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SimpleDomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/elytron/SSLElytronPrimarySecondaryOneWayTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/elytron/SSLElytronPrimarySecondaryTwoWayTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ReadConfigAsFeaturesDomainTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ServerAutoStartTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ServerStartFailureTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingLogTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogFieldsOfLogTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/expressions/AbstractSecureExpressionsTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/LoggingPreferencesTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/PerDeployLoggingTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/SizeAppenderRestartTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/AbstractCustomModuleTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ServerServiceThreadPoolTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CommandTimeoutHandlerTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ManagementOpTimeoutTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/RemoveManagementRealmTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/StartSuspendedTestCase.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/AbstractPropertiesRoleMappingTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestSupport.java

Fixes https://issues.redhat.com/browse/WFCORE-6135

[WFCORE-6135] TestSuite - NPE fastfail and safe tearDown

---

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/AbstractKernelServicesImpl.java
host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
request-controller/src/test/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemTestCase.java
server/src/main/java/org/jboss/as/server/ApplicationServerService.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
server/src/test/java/org/jboss/as/server/AddServerExecutorDependencyTestCase.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractKernelServicesImpl.java

https://issues.redhat.com/browse/WFCORE-6191

[WFCORE-6191] Eliminating usage of deprecated org.jboss.msc.service.ValueService

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6195

[WFCORE-6195] Upgrade Jandex to 3.0.5

---

server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java

https://issues.redhat.com/browse/WFCORE-6199

[WFCORE-6199] avoid duplicate module dependencies

---

core-feature-pack/common/src/main/resources/content/bin/common.sh

JIRA: https://issues.redhat.com/browse/WFCORE-6213

[WFCORE-6213] Fix grep warning with grep 3.8

---

server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
server/src/test/java/org/jboss/as/controller/persistence/GitPersistenceResourceTestCase.java
server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java

https://issues.redhat.com/browse/WFCORE-6208

[WFCORE-6208] Set signing of tags to the same value as signing commits.

---

controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java

https://issues.redhat.com/browse/WFCORE-6218

WFCORE-6218 Add Stream variant to PersistentResourceXMLDescription.PersistentResourceXMLBuilder

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6178

[WFCORE-6178] Upgrading JBoss MSC to 1.5.0.Beta5

---

server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java

https://issues.redhat.com/browse/WFCORE-6232

[WFCORE-6232] Eliminating ModuleSpecification deprecated methods

---

controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java

https://issues.redhat.com/browse/WFCORE-5557

[WFCORE-5557] Remove setAllowNull deprecated API

---

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6233

[WFCORE-6233] Upgrading JBoss MSC to 1.5.0.CR1

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentUnit.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitImpl.java

https://issues.redhat.com/browse/WFCORE-6234

[WFCORE-6234] Eliminating deprecated DeploymentUnit methods

---

cli/src/main/java/org/jboss/as/cli/impl/SecurityActions.java

https://issues.redhat.com/browse/WFCORE-6238

[WFCORE-6238] Eliminating dead code in org.jboss.as.cli.impl.SecurityActions class

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6240

[WFCORE-6240] Upgrade Bouncycastle OpenPGP from 1.72.1 to 1.72.2

---

controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-785

[WFCORE-785] Improving capability related error messages

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

https://issues.redhat.com/browse/WFCORE-6254

[WFCORE-6254] Eliminating deprecated CapabilityServiceBuilder.addCapabilityRequirement(String,Class) method

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6256

WFCORE-6256 Upgrade staxmapper to 1.4.0.Final

---

testsuite/shared/src/main/java/org/jboss/as/test/module/util/TestModule.java

Issue: https://issues.redhat.com/browse/WFCORE-6260
Thanks for submitting your Pull Request!
Please delete this text, and add a link to the Jira issue solved by this PR.
Remember to use the Jira issue ID in the PR title, and any commits.

[WFCORE-6260] TestModule should check the path in consistent manner

---

controller/src/main/java/org/jboss/as/controller/SubsystemModel.java
discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtensionTransformerRegistration.java
discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemModel.java
discovery/src/test/java/org/wildfly/extension/discovery/DiscoveryTransformersTestCase.java

https://issues.redhat.com/browse/WFCORE-6258

WFCORE-6258 Refactor Model interface from wildfly-clustering-common into wildfly-controller

---

controller/pom.xml
controller/src/main/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolver.java
controller/src/main/java/org/jboss/as/controller/descriptions/ParentResourceDescriptionResolver.java
controller/src/main/java/org/jboss/as/controller/descriptions/SubsystemResourceDescriptionResolver.java
controller/src/test/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolverTestCase.java
discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderDefinition.java
discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemDefinition.java
discovery/src/main/java/org/wildfly/extension/discovery/StaticDiscoveryProviderDefinition.java

https://issues.redhat.com/browse/WFCORE-6259

WFCORE-6259 Refactor SubsystemResourceDescriptionResolver implementation from wildfly-clustering-common to wildfly-controller

---

controller/src/main/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolver.java
controller/src/main/java/org/jboss/as/controller/descriptions/ParentResourceDescriptionResolver.java
controller/src/main/java/org/jboss/as/controller/descriptions/SubsystemResourceDescriptionResolver.java
controller/src/test/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolverTestCase.java

https://issues.redhat.com/browse/WFCORE-6262

WFCORE-6262 Enhance ParentResourceDescriptionResolver to support nested children and arbitrary keys

---

controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java

https://issues.redhat.com/browse/WFCORE-6263

WFCORE-6263 Add ExtensionParsingContext convenience method for registering a set of schemas

---

core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-host-excludes.xml

Reverts wildfly/wildfly-core#5416
@bstansberry Adding a revert commit here since I mistakenly merged it assuming the test passed. Tests were not executed at all due to our current pull request issue. I'll take care of the issue.

Revert "[WFCORE-6267] Remove domain.xml host-exclude entries for releases pri…"

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6273

[WFCORE-6273] Upgrade SLF4J to 2.0.7

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java

Issue: https://issues.redhat.com/browse/WFCORE-6270

Fix for WFCORE-6270, Bootable JAR, Security providers are not registered during boot

---

controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java
controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java

https://issues.redhat.com/browse/WFCORE-5553

[WFCORE-5553] Prune ProxyStepHandler and GlobalOperationHandlers isWFCORE621Needed and executeWFCORE621 logic

---

logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6281

[WFCORE-6281] Explicitly close log Context on LoggingSubsystemTestCase

---

testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/RegexRoleMapperTest.java

Issue: https://issues.redhat.com/browse/WFCORE-6276

[WFCORE-6276] RegexRoleMapperTest does not clean up resources

---

testsuite/shared/src/main/java/org/jboss/as/test/module/util/TestModule.java

Issue: https://issues.redhat.com/browse/WFCORE-6283

[WFCORE-6283] Make TestModule.getModulesDirectory public

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml

Issue: https://issues.redhat.com/browse/WFCORE-6277

[WFCORE-6277] adds wildflyee.api module dependency to java.se

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0-reject.xml
elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0.xml
testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/MappedRoleMapperTest.java

https://issues.redhat.com/browse/WFCORE-6244
Rebased onto #5347 to include upgrade to Elytron model version 17

[WFCORE-6244] Elytron mapped-role-mapper does not support expressions

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java

https://issues.redhat.com/browse/WFCORE-6157

[WFCORE-6157] Partial revert - enabling failing tests

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6289

[WFCORE-6289] Upgrading JBoss MSC to 1.5.0.Final

---

controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java

Also adds an another assert, and cleans up a bunch of IDE warns in the class.

[WFCORE-6157] Allow OperationCancellationUnitTestCase to complete in a reasonable time.

---

elytron/src/main/java/org/wildfly/extension/elytron/EESecurityDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/DriverDependenciesProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleAliasChecker.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

And take into account if the user is adding aliases as exclusions and warn if a user dependency has been added via a module-alias
Jira issue: https://issues.redhat.com/browse/WFCORE-6279

[WFCORE-6279] Replace Deployment Processors Javax dependencies with Jakarta modules

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml
elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6291
https://issues.redhat.com/browse/WFCORE-6298
https://issues.redhat.com/browse/WFCORE-6299

[WFCORE-6291] Obtain the complete set of PolicyContextHandler implementations from the Elytron EE module.

---

controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CompositeOperationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/WildcardOperationsTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/testbase/CustomManagementContextTestBase.java

https://issues.redhat.com/browse/WFCORE-2957

[WFCORE-2957] read-resource without include-runtime shows runtime-only resources

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml
elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6291
https://issues.redhat.com/browse/WFCORE-6298
https://issues.redhat.com/browse/WFCORE-6299

[20.x] [WFCORE-6291] Obtain the complete set of PolicyContextHandler implementations from the Elytron EE module.

---

server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6279
upstream PR: #5453

[20x][WFCORE-6279] Fix minor bug displaying exclusion warnings

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/test-secure-expressions-module.xml
testsuite/shared/src/main/resources/jmx-listener-module.xml
testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/operations/CustomFormattersTestCase.java

https://issues.redhat.com/browse/WFCORE-6249

[WFCORE-6249] Eliminating deprecated sun.jdk module usages

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6310

[WFCORE-6310] Upgrade Byteman to 4.0.21

---

host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6196

[WFCORE-6196] Reject host registrations before WildFly 23

---

controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServicesImpl.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java

https://issues.redhat.com/browse/WFCORE-6322

[WFCORE-6322] Remove deprecated AbstractControllerService APIs

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContext.java
controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/ProfileIncludesHandlerTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/ReloadRequiredServerTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerGroupOperationsTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/SocketBindingGroupIncludesHandlerTestCase.java

https://issues.redhat.com/browse/WFCORE-6297
https://issues.redhat.com/browse/WFCORE-6318

[WFCORE-6318][WFCORE-6297] OperationContext API cleanups

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6324

[WFCORE-6324] Upgrade bouncycastle from 1.72 to 1.73

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

https://issues.redhat.com/browse/WFCORE-6306

[WFCORE-6306] Bump the core management version to version 22.

---

core-feature-pack/common/pom.xml
core-feature-pack/ee-10-api/pom.xml

https://issues.redhat.com/browse/WFCORE-6293

[WFCORE-6293] Partial revert of 'Removing JDK 8 specific excludes from maven enforcer plugin configurations'

---

controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
controller/src/test/java/org/jboss/as/controller/InterleavedSubsystemTestCase.java
controller/src/test/java/org/jboss/as/controller/RemoveNonExistingResourceTestCase.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOrderedChildResourceSyncModelTestCase.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/SyncModelServerStateTestCase.java
jmx/src/main/java/org/jboss/as/jmx/MBeanServerService.java
jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java
jmx/src/test/java/org/jboss/as/jmx/auditlog/JmxAuditLogHandlerTestCase.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
server/src/main/java/org/jboss/as/server/Bootstrap.java
server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
testsuite/shared/src/main/java/org/wildfly/test/mixed/domain/TestParserUtils.java

https://issues.redhat.com/browse/WFCORE-6325

WFCORE-6325 Replace ExtensionRegistry constructor bloat with builder pattern

---

controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
host-controller/src/main/java/org/jboss/as/host/controller/discovery/DiscoveryOptionResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/discovery/StaticDiscoveryResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/ignored/IgnoredDomainTypeResourceDefinition.java
management-client-content/src/main/java/org/jboss/as/management/client/content/ManagedDMRContentResourceDefinition.java
management-client-content/src/main/java/org/jboss/as/management/client/content/ManagedDMRContentTypeResourceDefinition.java
subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtensionCommon.java

Issue: https://issues.redhat.com/browse/WFCORE-6316

[WFCORE-6316] Remove deprecated SimpleResourceDefinition elements

---

controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/HostProcessReloadHandler.java

Issue: https://issues.redhat.com/browse/WFCORE-6315

[WFCORE-6315] Remove deprecated SimpleOperationDefinition elements

---

server/src/main/java/org/jboss/as/server/deployment/module/MountHandle.java

https://issues.redhat.com/browse/WFCORE-6330

[WFCORE-6330] Make deprecated MountHandler constructor private and undeprecate it

---

controller/src/main/java/org/jboss/as/controller/services/path/PathAddHandler.java
controller/src/main/java/org/jboss/as/controller/services/path/PathRemoveHandler.java
controller/src/main/java/org/jboss/as/controller/services/path/PathResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6333

[WFCORE-6333] Remove deprecated Path resource API elements

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java

https://issues.redhat.com/browse/WFCORE-6290
https://issues.redhat.com/browse/JBEAP-24716

[WFCORE-6290] Failure to handle errors loading process-uuid file

---

server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/main/java/org/jboss/as/server/ServerEnvironmentResourceDescription.java
server/src/main/java/org/jboss/as/server/ServerStartTask.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java

https://issues.redhat.com/browse/WFCORE-6329
Requires https://github.com/wildfly/wildfly/pull/16796 first

[WFCORE-6329] Remove deprecated ServerEnvironment API

---

testsuite/patching/src/test/java/org/jboss/as/test/patching/ProductInfo.java
version/src/main/java/org/jboss/as/version/ProductConfig.java

Issue: https://issues.redhat.com/browse/WFCORE-6331

WFCORE-6331 Remove deprecated ProductConfig constructor

---

core-feature-pack/common/src/main/resources/content/bin/common.bat
core-feature-pack/common/src/main/resources/content/bin/common.ps1
core-feature-pack/common/src/main/resources/content/bin/common.sh
host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6346
Upstream PR: https://github.com/wildfly/wildfly-core/pull/5498

[WFCORE-6346] Module java.base must open java.net package to all unnamed modules

---

core-model-test/framework/src/main/java/org/jboss/as/core/model/test/LegacyKernelServicesImpl.java
core-model-test/framework/src/main/java/org/jboss/as/core/model/test/MainKernelServicesImpl.java
jmx/src/test/java/org/jboss/as/jmx/PluggableMBeanServerTestCase.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServices.java
model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/bridge/impl/LegacyControllerKernelServicesProxy.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/KernelServices.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/KernelServicesBuilder.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/LegacyKernelServicesImpl.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformerAttachmentGrabber.java

https://issues.redhat.com/browse/WFCORE-6334

[WFCORE-6334] Remove deprecated management model test framework API

---

controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml

* A MapAttributeDefinition or an ObjectAttributeDefinition wasn't
properly handled.
Jira: https://issues.redhat.com/browse/WFCORE-6341
Please note that this commit also integrates https://github.com/wildfly/wildfly-core/pull/5489

[WFCORE-6341]: YAML: MapAttributeDefinition not properly processed for existing resources.

---

controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_child.yml
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_child_error.yml
controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_error.yml

* If the YAML doesn't match a resource we are now failing.
Jira: https://issues.redhat.com/browse/WFCORE-6348

[WFCORE-6348]: Invalid YAML configuration fails silently.

---

server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
server/src/main/java/org/jboss/as/server/security/AdvancedSecurityMetaData.java
server/src/main/java/org/jboss/as/server/security/SecurityMetaData.java
server/src/main/java/org/jboss/as/server/security/VirtualDomainMarkerUtility.java
server/src/main/java/org/jboss/as/server/security/VirtualDomainUtil.java

https://issues.redhat.com/browse/WFCORE-6352

[WFCORE-6352] Add the ability to secure the management interface using a virtual HTTP authentication factory if available

---

controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
controller/src/main/java/org/jboss/as/controller/RestartParentResourceHandlerBase.java
controller/src/main/java/org/jboss/as/controller/RestartParentResourceRemoveHandler.java

https://issues.redhat.com/browse/WFCORE-6365
This builds on #5517 but tweaks where in the step queue the added steps are inserted.

[WFCORE-6365] RestartParent OperationStepHandler implementations are incompatible with service built via CapabilityServiceTarget

---

controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
controller/src/main/java/org/jboss/as/controller/RestartParentResourceHandlerBase.java
controller/src/main/java/org/jboss/as/controller/RestartParentResourceRemoveHandler.java
controller/src/main/java/org/jboss/as/controller/RestartParentWriteAttributeHandler.java
jmx/src/main/java/org/jboss/as/jmx/ExposeModelResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorAdd.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorChildResource.java

https://issues.redhat.com/browse/WFCORE-6365

WFCORE-6365 RestartParent OperationStepHandler implementations are in compatible with service built via CapabilityServiceTarget

---

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6368

[WFCORE-6368] Upgrading JBoss MSC to 1.5.1.Final

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/CompositeOperationHandler.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java
controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java

https://issues.redhat.com/browse/WFCORE-6386
https://issues.redhat.com/browse/WFCORE-6380
https://issues.redhat.com/browse/WFCORE-6381

[WFCORE-6386][WFCORE-6380][WFCORE-6381] Reduce peak memory use during recursive read-resource operations

---

controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

https://issues.redhat.com/browse/WFCORE-6392

[WFCORE-6392] Eliminating deprecated and unused CapabilityServiceBuilder.addCapabilityRequirement() methods

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6390
clones https://issues.redhat.com/browse/WFLY-18118

[WFCORE-6390] Removing the victims-scan profile

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java

Reverts wildfly/wildfly-core#5542
Breaks some domain mode use cases, so needs more work.

Revert "[WFCORE-6386] Ensure that read-only op handlers that incorrectly do w…"

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java

Reverts wildfly/wildfly-core#5549

Revert "Revert "[WFCORE-6386] Ensure that read-only op handlers that incorrectly do w…""

---

controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6395

[WFCORE-6395] Clean up Operation Context only for server processes

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java

https://issues.redhat.com/browse/WFCORE-6096

[WFCORE-6096] ModelTestModelControllerService does not set error when init capabilities are missing

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml

https://issues.redhat.com/browse/WFCORE-6409

[WFCORE-6409] Make org.jboss.marshalling module private

---

pom.xml

* Updating jgit
* Update Apache SSHD to 2.10.0
* Update javaewah to 1.2.3
Release notes:
https://projects.eclipse.org/projects/technology.jgit/releases/6.6.0/
https://projects.eclipse.org/projects/technology.jgit/releases/6.5.0/
https://projects.eclipse.org/projects/technology.jgit/releases/6.4.0/
https://projects.eclipse.org/projects/technology.jgit/releases/6.3.0/
Jira: https://issues.redhat.com/browse/WFCORE-6412

[WFCORE-6412]: Update JGit to 6.6.0.202305301015-r

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6413

[WFCORE-6413] Upgrade JBoss VFS to 3.3.0.Final

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6414

[WFCORE-6414] Upgrade bouncycastle from 1.73 to 1.75

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6417

[WFCORE-6417] Upgrade Jandex to 3.1.2

---

server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependency.java

Issue: https://issues.redhat.com/browse/WFCORE-6154
Related to issue: https://issues.redhat.com/browse/WFLY-2297

[WFCORE-6154] Log reasons for implicit module dependencies

---

core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
pom.xml

And update the license to the Apache license.
https://issues.redhat.com/browse/WFCORE-6426
https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12311922&version=12335393
https://github.com/jbossas/remoting-jmx/compare/3.0.4.Final...3.1.0.Final

[WFCORE-6426] Upgrade to Remoting JMX 3.1.0.Final.

---

testsuite/domain/src/test/resources/domain-configs/domain-config-changes.xml
testsuite/domain/src/test/resources/domain-configs/domain-standard.xml

https://issues.redhat.com/browse/WFCORE-6425

WFCORE-6425 Domain testsuite uses invalid remoting configuration

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/api/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/xml/stream/api/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/scripting/main/module.xml

https://issues.redhat.com/browse/WFCORE-6285
Is related to: https://github.com/wildfly/wildfly-core/pull/5575

[WFCORE-6285] Document how to move off remaining deprecated modules in their module.xml files

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6428

WFCORE-6428 Error occurred in starting fork when running with jacoco profile

---

SECURITY.md

https://issues.redhat.com/browse/WFCORE-6430

[WFCORE-6430] Update the SECURITY.md document

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java
controller/src/main/java/org/jboss/as/controller/services/path/PathAddHandler.java
controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/InjectedSocketBindingStreamServerService.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentStatusHandler.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentProcessor.java
server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java

https://issues.redhat.com/browse/WFCORE-6371
https://issues.redhat.com/browse/WFCORE-6393
https://issues.redhat.com/browse/WFCORE-6394

[WFCORE-6371][WFCORE-6393][WFCORE-6394] Adding support for o.j.m.s.ServiceTarget.addService() method plus deprecated methods cleanup

---

deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
deployment-repository/src/main/java/org/jboss/as/repository/ExplodedContent.java
deployment-repository/src/main/java/org/jboss/as/repository/HashUtil.java
deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java

* Cleaning up the code a bit by removing the emptyStream implementation.
Jira: https://issues.redhat.com/browse/WFCORE-6431

[WFCORE-6431]: Use InputStream.nullInputStream.

---

host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java

https://issues.redhat.com/browse/WFCORE-6440

WFCORE-6440 HttpManagementAddHandler references ServerEnvironment incorrectly

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6439

[WFCORE-6439] Upgrade JBoss Modules to 2.1.2.Final

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6441

[WFCORE-6441] Bump the core management version to version 23

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6444

[WFCORE-6444] Upgrade BouncyCastle to 1.76.

---

controller/src/main/java/org/jboss/as/controller/ControlledProcessState.java
controller/src/test/java/org/jboss/as/controller/ControlledProcessStateUnitTestCase.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailabilityService.java
domain-http/interface/src/test/java/org/jboss/as/domain/http/server/ConsoleAvailabilityUnitTestCase.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncServerStateOperationHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/secondaryreconnect/DeploymentScenario.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6375
Jira issue: https://issues.redhat.com/browse/WFCORE-6434

[WFCORE-6375][WFCORE-6434] Do not synchronize stopped servers when a HC reconnects and allow reload/restart required when starting

---

controller/src/main/java/org/jboss/as/controller/ControlledProcessState.java
controller/src/test/java/org/jboss/as/controller/ControlledProcessStateUnitTestCase.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailabilityService.java
domain-http/interface/src/test/java/org/jboss/as/domain/http/server/ConsoleAvailabilityUnitTestCase.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncServerStateOperationHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/secondaryreconnect/DeploymentScenario.java

This is just a draft to get CI on a proposed change to #5589.

WFCORE-6375 / WFCORE-6434

---

controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java

Jira issue: https://issues.redhat.com/browse/WFCORE-5305
FYI @parsharma

[WFCORE-5305] Fix import order in ReadResourceHandler

---

testsuite/manualmode/pom.xml
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryImpl.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryTestCase.java

https://issues.redhat.com/browse/WFCORE-6464
This PR is also required by #5561

[WFCORE-6464] Update CustomCredentialSecurityFactoryImpl to no longer rely on private Elytron API

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6462

[WFCORE-6462] Upgrade xom to version 1.3.9

---

pom.xml
testbom/pom.xml
testsuite/shared/pom.xml
testsuite/shared/src/main/java/org/jboss/as/test/shared/PermissionUtils.java

https://issues.redhat.com/browse/WFCORE-6461

[WFCORE-6461] Replace PermissionUtils use of xom with staxmapper

---

model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java

Issue: https://issues.redhat.com/browse/WFCORE-5753

[WFCORE-5753] Update ModelTestControllerVersion.EAP_XP_4 to use proper EAP XP4 artifacts

---

.github/workflows/build-manual.yml

https://issues.redhat.com/browse/WFCORE-6478

WFCORE-6478 Enable manual start of github actions CI workflow

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6471

[WFCORE-6471] Upgrade FasterXML Jackson to 2.14.3

---

elytron/pom.xml
pom.xml
testsuite/domain/pom.xml

https://issues.redhat.com/browse/WFCORE-6480

[WFCORE-6480] Upgrade xml-maven-plugin to 1.1.0

---

testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java

JIRA: https://issues.redhat.com/browse/WFCORE-6466

[WFCORE-6466] Split LayersTest#test into two separate methods

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-6469

[WFCORE-6469] Upgrade JBoss Marshalling to 2.1.2.SP1

---

testsuite/domain/pom.xml
testsuite/standalone/pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6493

[WFCORE-6493] Add Guava as a test dependency to the Test Suite.

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
testsuite/domain/src/test/resources/host-configs/host-secondary-main-three-without-jvm.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6491

[WFCORE-6491] Fix HostControllerBootOperationsTestCase random failures

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6515

[WFCORE-6515] Upgrade Jandex from 3.1.3 to 3.1.5

---

core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat

https://issues.redhat.com/browse/WFCORE-1386

[WFCORE-6512] Reimplement WFCORE-1386

---

remoting/subsystem/src/main/resources/schema/wildfly-remoting_6_0.xsd

Jira issue: https://issues.redhat.com/browse/WFCORE-6510
Follows up on #5683

[WFCORE-6510] Update wildfly-remoting_6_0.xsd copyright header

---

elytron/src/test/java/org/wildfly/extension/elytron/JdkUtils.java
host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmElement.java
host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/PlatformMBeanUtil.java
server/src/main/java/org/jboss/as/server/deployment/module/VFSResourceLoader.java
server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/shared/AssumeTestGroupUtil.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/JdkModuleDependencyTestCase.java

https://issues.redhat.com/browse/WFCORE-6520
https://issues.redhat.com/browse/WFCORE-6521

[WFCORE-6520][WFCORE-6521] Further JDK11 Cleanup - removing unused code plus using new API to improve performance

---

remoting/subsystem/src/main/java/org/jboss/as/remoting/InsecureOutboundConnection.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemModel.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemSchema.java
remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformerTestCase.java

Follows up on https://issues.redhat.com/browse/WFCORE-6472

Fix license headers introduced by WFCORE-6472

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6528

[WFCORE-6528] Upgrading JBoss MSC to 1.5.2.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6516

[WFCORE-6516] Upgrading JBoss Marshalling to 2.1.3.Final

---

pom.xml

Jira: https://issues.redhat.com/browse/WFCORE-6551
Release Notes - XNIO - Version 3.8.11.Final
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-419'>XNIO-419</a>] -         Wrap JDK Security Exceptions and provide a easily understandable message
</li>
</ul>
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/XNIO-422'>XNIO-422</a>] -         Add information about remote connection address to the Exception when connection fails
</li>
</ul>

[WFCORE-6551] Upgrade XNIO to 3.8.11.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6547

[WFCORE-6547] Upgrading JBoss Marshalling to 2.1.3.SP1

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6551
Upstream: #5708

[22.x][WFCORE-6551] Upgrade XNIO to 3.8.11.Final

---

pom.xml
testsuite/shared/src/main/java/org/wildfly/test/installationmanager/TestInstallationManager.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6567

[WFCORE-6567] Upgrade Installation Manager API to 1.0.2.Final

---

core-feature-pack/common/pom.xml
core-feature-pack/galleon-feature-pack/pom.xml
pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6574

[WFCORE-6574] Upgrade JBoss Parent to 40

---

pom.xml

This just aggregates the 2 JSON-related dependabot PRs for combined CI:
#5742 (API)
#5736 (Impl)

[WFCORE-6573][WFCORE-6575] Json upgrades

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6584

WFCORE-6584 Upgrade wildfly-common to 1.7.0.Final

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6586

[WFCORE-6586] Upgrade SSHD from 2.10.0 to 2.11.0

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6587

[WFCORE-6587] Upgrade Apache Commons CLI from 1.5.0 to 1.6.0

---

pom.xml

* Upĝrade snakeyaml from 2.0 to 2.2
Issue: https://issues.redhat.com/browse/WFCORE-6585

[WFCORE-6585]:   Upgrade snakeyaml to 2.2

---

threads/src/main/java/org/jboss/as/threads/ThreadFactoryService.java

https://issues.redhat.com/browse/WFCORE-6592
22.x PR: https://github.com/wildfly/wildfly-core/pull/5758

WFCORE-6592 Fix NPE in ThreadFactoryService

---

core-feature-pack/common/src/main/resources/content/bin/domain.bat
core-feature-pack/common/src/main/resources/content/bin/domain.conf
core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.ps1
core-feature-pack/common/src/main/resources/content/bin/domain.sh
core-feature-pack/common/src/main/resources/content/bin/standalone.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.conf
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.sh

Issue: https://issues.redhat.com/browse/WFCORE-6578
Upstream: https://github.com/wildfly/wildfly-core/pull/5760
Fixes: https://access.redhat.com/security/cve/CVE-2023-3171

[WFCORE-6578] CVE-2023-3171 WildFly heap exhaustion via deserialization

---

jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java

https://issues.redhat.com/browse/WFCORE-6604
There are no tests but this issue was identified in the tests for https://github.com/wildfly/wildfly/pull/17330

[WFCORE-6604] Avoid default value for arrays and TabularType

---

core-feature-pack/galleon-common/src/main/resources/feature_groups/logging.xml
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml

Issue: https://issues.redhat.com/browse/WFCORE-6600

[WFCORE-6600] Create logging category for com.networknt.schema

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

https://issues.redhat.com/browse/WFCORE-6620

[WFCORE-6620] Bump the core management version to version 24

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6621

[WFCORE-6621] Upgrade Byteman to 4.0.22

---

controller/src/main/java/org/jboss/as/controller/SecurityActions.java
controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolOperationHandler.java
deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DefaultDeploymentOperations.java
host-controller/src/main/java/org/jboss/as/host/controller/SecurityActions.java
server/src/main/java/org/jboss/as/server/deployment/ContentRepositoryCleaner.java
server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerClient.java

https://issues.redhat.com/browse/WFCORE-6638

[WFCORE-6638] Local variables referenced from a lambda expression must be final or effectively final

---

model-test/src/test/resources/org/jboss/as/model/test/settings-empty-local-repo.xml

Issue: https://issues.redhat.com/browse/WFCORE-6642 [WFCORE-6642] Remove obsolete eap-repo profile in test

[WFCORE-6642] Remove obsolete eap-repo profile in test

---

controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
controller/src/main/java/org/jboss/as/controller/operations/common/AbstractXmlMarshallingHandler.java
controller/src/main/java/org/jboss/as/controller/operations/common/XmlFileMarshallingHandler.java
controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/HostXmlFileMarshallingHandler.java
server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ManagementReadXmlTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/AuditLogTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/FullReplaceUndeployTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadsTestCase.java
testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
testsuite/domain/src/test/resources/expected-main-one.xml
testsuite/domain/src/test/resources/expected-main-three.xml
testsuite/domain/src/test/resources/host-configs/host-primary.xml
testsuite/domain/src/test/resources/host-configs/host-secondary.xml
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml
testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/StandardRolesBasicTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpGetMgmtOpsTestCase.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/CoreServerTestCase.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ProductInfoUnitTestCase.java

* Adding a new read-config-as-xml-file to replace read-config-as-xml.
* Adding more tests
* 'Fixing' some tests that aren't cleaning up their changes.
Jira: https://issues.redhat.com/browse/WFCORE-4758
Analysis: https://github.com/wildfly/wildfly-proposals/pull/428

[WFCORE-4758]: Community - Simple config export for a domain server.

---

service/src/main/java/org/wildfly/service/Installer.java
service/src/test/java/org/wildfly/service/DefaultServiceInstallerTestCase.java
service/src/test/java/org/wildfly/service/DefaultServiceTestCase.java

WFCORE-6347 Create better distinction between start task, and service value captor.

---

service/src/main/java/org/wildfly/service/ServiceInstaller.java
service/src/main/java/org/wildfly/service/capture/FunctionExecutor.java
service/src/main/java/org/wildfly/service/capture/FunctionExecutorRegistry.java
service/src/main/java/org/wildfly/service/capture/ServiceValueExecutorRegistry.java
service/src/main/java/org/wildfly/service/capture/ServiceValueRegistry.java
service/src/main/java/org/wildfly/service/capture/ValueExecutorRegistry.java
service/src/main/java/org/wildfly/service/capture/ValueRegistry.java
service/src/test/java/org/wildfly/service/capture/ServiceValueExecutorRegistryTestCase.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
subsystem/src/main/java/org/wildfly/subsystem/service/capture/FunctionExecutorRegistry.java
subsystem/src/main/java/org/wildfly/subsystem/service/capture/ServiceValueExecutorRegistry.java

WFCORE-6347 Generalize service capture abstractions for use in wildfly-service.

---

service/src/main/java/org/wildfly/service/Installer.java
service/src/main/java/org/wildfly/service/ServiceInstaller.java
service/src/test/java/org/wildfly/service/DefaultServiceTestCase.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java

WFCORE-6347 Refine installer Builder/Configuration interfaces.

---

controller/src/main/java/org/jboss/as/controller/capability/BinaryCapabilityNameResolver.java
controller/src/main/java/org/jboss/as/controller/capability/UnaryCapabilityNameResolver.java
controller/src/test/java/org/jboss/as/controller/capability/CapabilityNameResolverTestCase.java
service/src/main/java/org/wildfly/service/descriptor/BinaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/NullaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/QuaternaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/ServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/TernaryServiceDescriptor.java
service/src/main/java/org/wildfly/service/descriptor/UnaryServiceDescriptor.java

WFCORE-6347 Add provider interfaces per service descriptor.

---

controller/src/main/java/org/jboss/as/controller/capability/BinaryCapabilityNameResolver.java
controller/src/main/java/org/jboss/as/controller/capability/UnaryCapabilityNameResolver.java
discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderRegistrar.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceRecorder.java
subsystem/src/main/java/org/wildfly/subsystem/resource/capability/ResourceCapabilityReferenceRecorder.java
subsystem/src/test/java/org/wildfly/subsystem/resource/capabilty/CapabilityReferenceRecorderTestCase.java

WFCORE-6347 Misc API cleanup of capability reference recorder interfaces in wildfly-subsystem

---

service/src/main/java/org/wildfly/service/Dependency.java
service/src/main/java/org/wildfly/service/ServiceDependency.java
service/src/test/java/org/wildfly/service/ServiceDependencyTestCase.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java
subsystem/src/test/java/org/wildfly/subsystem/service/ServiceDependencyTestCase.java

WFCORE-6347 Add convenience method to map a dependency to an alternate type.

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandler.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/OperationStepHandlerDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/RemoveResourceOperationStepHandler.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/WriteAttributeOperationStepHandler.java

Expands context of capability filter in wildfly-subsystem to support more complex use cases, e.g. https://github.com/wildfly/wildfly/blob/30.0.1.Final/undertow/src/main/java/org/wildfly/extension/undertow/ServerAdd.java#L78
https://issues.redhat.com/browse/WFCORE-6176

WFCORE-6176 Generalize capability filter to cover more complex scenarios.

---

testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java

https://issues.redhat.com/browse/WFCORE-6669

WFCORE-6669 Various tests fail when env specifies JDK_JAVA_OPTIONS or JAVA_TOOL_OPTIONS

---

pom.xml

Issue: [WFCORE-6687](https://issues.redhat.com/browse/WFCORE-6687)
WFLY PR: wildfly/wildfly#17571

WFCORE-6687: bump licenses-plugin to 2.4.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6701

[WFCORE-6701] Upgrade JBoss VFS to 3.3.1.Final

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6699

[WFCORE-6699] Add EAP 8.0 as known host exclude release version

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6698

[WFCORE-6698] Upgrade SSHD from 2.12.0 to 2.12.1

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6696

[WFCORE-6696] Upgrade SLF4J from 2.0.11 to 2.0.12

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6706

[WFCORE-6706] Upgrading JBoss MSC to 1.5.3.Final

---

embedded/src/main/java/org/wildfly/core/embedded/LoggerContext.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6710

[WFCORE-6710] Upgrade JBoss Modules to 2.1.3.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6714

[WFCORE-6714] Upgrading JBoss Marshalling to 2.1.4.SP1

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6720

[WFCORE-6720] Upgrade JBoss Class File Writer to 1.3.1.Final

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java

https://issues.redhat.com/browse/WFCORE-6167

[WFCORE-6167] Workaround for known issue (enabled on JDK22+)

---

pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6729

Fix for WFCORE-6729, Upgrade Galleon to 6.0.0.Beta3, Galleon plugins to 7.0.0.Beta4, and provisioning tooling

---

domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainUtil.java
domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java

Issue: https://issues.redhat.com/browse/WFCORE-6723
[WFCORE-6723] Add header 'X-Content-Type-Options' to http management handlers

[WFCORE-6723] Add header 'X-Content-Type-Options' to http management handlers

---

core-feature-pack/galleon-feature-pack/pom.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-6747
Align with Stability handling in provisioning as specified in https://github.com/wildfly/wildfly-proposals/pull/555

Fix for WFCORE-6747, Upgrade to Galleon 6.0.0.Beta4 and WFGP 7.0.0.Beta5

---

embedded/src/main/java/org/wildfly/core/embedded/LoggerContext.java
pom.xml

https://issues.redhat.com/browse/WFCORE-6746

[WFCORE-6746] Upgrade JBoss Modules to 2.1.4.Final

---

controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java
controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
controller/src/main/java/org/jboss/as/controller/registry/OperationEntry.java
controller/src/test/java/org/jboss/as/controller/registry/CoreManagementResourceRegistrationUnitTestCase.java

https://issues.redhat.com/browse/WFCORE-6730

WFCORE-6730 A registered operation should never contain parameters or reply parameters not enabled by stability-level of process

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6743

[WFCORE-6743] Upgrade io.smallrye:jandex from 3.1.6 to 3.1.7

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/WriteAttributeTranslationOperationStepHandler.java

https://issues.redhat.com/browse/WFCORE-6768
Thankfully, nobody references this class just yet.

WFCORE-6768 Fix goofy WriteAttributeTranslationOperationStepHandler class name

---

subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java

https://issues.redhat.com/browse/WFCORE-6767

WFCORE-6767 ServiceDependency interface is missing QuaternaryServiceDescriptor factory method

---

controller/src/main/java/org/jboss/as/controller/ServiceNameFactory.java

https://issues.redhat.com/browse/WFCORE-6769

WFCORE-6769 Port NaryServiceNameFactory logic from wildfly-clustering-common to ServiceNameFactory

---

core-feature-pack/common/src/main/resources/content/bin/installation-manager.sh

Issue: https://issues.redhat.com/browse/WFCORE-6772

[WFCORE-6772] Make the installation-manager script POSIX compatable

---

server/src/main/java/org/jboss/as/server/ServerEnvironment.java
server/src/main/java/org/jboss/as/server/ServerEnvironmentAwareProcessReloadHandler.java
server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java

https://issues.redhat.com/browse/WFCORE-6753
Alternative to #5936

[WFCORE-6753] Make ServerEnvironment.setStability() package protected

---

subsystem/src/main/java/org/wildfly/subsystem/resource/operation/ResourceOperationRuntimeHandler.java

https://issues.redhat.com/browse/WFCORE-6781

WFCORE-6781 Port composite ResourceOperationServiceHandler logic from wildfly-clustering-common

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6783

[WFCORE-6783] Upgrade JBoss VFS to 3.3.2.Final

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/msc/main/module.xml
pom.xml

https://issues.redhat.com/browse/WFCORE-6784

[WFCORE-6784] Upgrading JBoss MSC to 1.5.4.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6785

[WFCORE-6785] Upgrade JBoss Modules to 2.1.5.Final

---

elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java

https://issues.redhat.com/browse/WFCORE-6757

[WFCORE-6757] Clean up ServiceBuilder references in AuthenticationClientDefinitions#performRuntime

---

controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
service/src/main/java/org/wildfly/service/ServiceDependency.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java

https://issues.redhat.com/browse/WFCORE-6786

WFCORE-6786 Port CredentialSourceDependency from wildfly-clustering-common

---

service/src/main/java/org/wildfly/service/Installer.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-6792

WFCORE-6792 Rename Installer.Builder.async() -> Installer.Builder.blocking()

---

testsuite/manualmode/pom.xml

Just fix https://github.com/wildfly/wildfly-core/pull/5967#discussion_r1570310154

[WFCORE-6560] Remove test exclusion cruft

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6795

[WFCORE-6795] Upgrade wildfly-discovery to 1.3.0.Final

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6797

[WFCORE-6797] Upgrade BouncyCastle from 1.78 to 1.78.1

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6799

[WFCORE-6799] Upgrade SLF4J from 2.0.12 to 2.0.13

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6803

[WFCORE-6803] Bump the kernel management API version to 26.0.0

---

subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java

Thanks to @ehsavoie for spotting this!
https://issues.redhat.com/browse/WFCORE-6792

WFCORE-6792 Fix missing CapabilityServiceInstaller.Builder.async() -> blocking().

---

subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-6792
Backports: https://github.com/wildfly/wildfly-core/pull/5983

WFCORE-6792 Fix missing CapabilityServiceInstaller.Builder.async() ->blocking().

---

deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java

https://issues.redhat.com/browse/WFCORE-6814

[WFCORE-6814] Adjusting ContentRepositoryTest to be functional on all JDKs on Fedora 40

---

controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java

https://issues.redhat.com/browse/WFCORE-6817

WFCORE-6817 Operation parameters and reply attributes not enabled by the current stability level still appear in the resource description

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java

https://issues.redhat.com/browse/WFCORE-6816

WFCORE-6816 A resource with a deployment chain contributor should require restarting all services on removal

---

elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6700

[WFCORE-6700] Minor Java Doc fix

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6831
Upstream PR: https://github.com/wildfly/wildfly-core/pull/6001

[WFCORE-6831] Upgrade WildFly Elytron to 2.4.2.Final

---

server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java

Issue: https://issues.redhat.com/browse/WFCORE-6832

[WFCORE-6832] Wrong arguments to standalone.sh may lead to server content removal

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6835

[WFCORE-6835] Upgrading JBoss MSC to 1.5.5.Final

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyModeTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SimpleDomainControllerMigrationTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/secondaryreconnect/SecondaryReconnectTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HcExtensionAndSubsystemManagementTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HostLifecycleWithRolloutPlanTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesProfileCloneTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/IgnoredResourcesTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/OutboundLdapConnectionTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java

https://issues.redhat.com/browse/WFCORE-6821

[WFCORE-6821] Use a builder to construct the different attributes for the domain mode reload test suite operation

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceModelResolver.java

https://issues.redhat.com/browse/WFCORE-6836

WFCORE-6836 Port ResourceModelResolver<T> from wildfly-clustering-common to wildfly-subsystem

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6839

[WFCORE-6839] Upgrade Byteman to 4.0.23

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6845

[WFCORE-6845] Upgrade Apache Commons CLI from 1.6.0 to 1.8.0

---

subsystem/src/main/java/org/wildfly/subsystem/resource/operation/ResourceOperationRuntimeHandler.java

https://issues.redhat.com/browse/WFCORE-6840

WFCORE-6840 Restart parent/ancestor ResourceOperationRuntimeHandler throws NoSuchResourceException if ancestor resource was created in same batch

---

deployment-repository/src/main/java/org/jboss/as/repository/RemoteFileRequestAndHandler.java

Issue: https://issues.redhat.com/browse/WFCORE-6848

[WFCORE-6848] Fix remote deployment distribution double scheduling

---

bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java

https://issues.redhat.com/browse/WFCORE-6850

[WFCORE-6850] Set a JDKModuleLogger after the log manager is configured.

---

controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceAddDescriptionProvider.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java

https://issues.redhat.com/browse/WFCORE-6865

WFCORE-6865 DefaultResourceAddDescriptionProvider omits the stability of the operation from its generated description

---

pom.xml
testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/OpenSslTlsTestCase.java

https://issues.redhat.com/browse/WFCORE-6868
This PR does also include the commit from https://github.com/wildfly/wildfly-core/pull/6050 but it is expected that PR will go in first.

[WFCORE-6868] Use the Defined*Identity Types to get the Key and Trust Manager.

---

subsystem/src/main/java/org/wildfly/subsystem/SubsystemPersistence.java
subsystem/src/test/java/org/wildfly/subsystem/SubsystemPersistenceTestCase.java

https://issues.redhat.com/browse/WFCORE-6877

WFCORE-6877 SubsystemPersistence factory method for manual parser/writer cannot find writer

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6886

[WFCORE-6886] Update unstable API scanner to 1.0.0.Final

---

testsuite/unstable-api-annotation/feature-pack/feature-pack/pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6892

[WFCORE-6892] Remove duplicate plugin declaration

---

core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6834

[WFCORE-6834] wildfly-elytron-integration jar duplicated in server modules

---

testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/JaasCustomRealmWrapperTest.java
testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ResolveExpressionTestCase.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildflyTestRunner.java

Resolves 
https://issues.redhat.com/browse/WFCORE-6897

WFCORE-6897 Remove usage of deprecated WildflyTestRunner class

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-6901
Add new ids

[WFCORE-6901] Create Phase IDs for OpenTelemetry

---

testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlCommunityTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlTestCase.java

- And ensure the domain is running in and supports community stability before running the test
Jira issue: https://issues.redhat.com/browse/WFCORE-6813

[WFCORE-6813] Extract read-config-as-xml-file tests in individual class

---

testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/OpenSslTlsTestCase.java

https://issues.redhat.com/browse/WFCORE-6869
Also incorporates https://github.com/wildfly/wildfly-core/pull/6062

[WFCORE-6869] Get the KeyStore File and type from the Defined id entities for the OpenSslTlsTestCase

---

pom.xml

* Upgrading JGit to 6.10
Jira: https://issues.redhat.com/browse/WFCORE-6855
https://projects.eclipse.org/projects/technology.jgit/releases/6.10.0/

[WFCORE-6855]: Upgrade JGit from 6.8.0.202311291450-r to 6.10.0.202406032230-r

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6906

[WFCORE-6906] Upgrade Installation Manager API to 1.0.3.Final

---

request-controller/src/main/java/org/wildfly/extension/requestcontroller/MaxRequestsWriteHandler.java
request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerRootDefinition.java

https://issues.redhat.com/browse/WFCORE-6929

WFCORE-6929 Remove usage of deprecated AbstractWriteAttributeHandler constructors in request-controller subsystem

---

server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
server/src/main/java/org/jboss/as/server/controller/resources/SystemPropertyResourceDefinition.java
server/src/main/java/org/jboss/as/server/operations/SystemPropertyValueWriteAttributeHandler.java
server/src/main/java/org/jboss/as/server/services/net/AbstractBindingWriteHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingFixedPortHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingInterfaceHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingMulticastAddressHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingMulticastPortHandler.java
server/src/main/java/org/jboss/as/server/services/net/BindingPortHandler.java
server/src/main/java/org/jboss/as/server/services/net/ClientMappingsHandler.java
server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingResourceDefinition.java
server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingWriteHandler.java
server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingResourceDefinition.java
server/src/main/java/org/jboss/as/server/services/net/SocketBindingGroupResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6928

WFCORE-6928 Remove usage of deprecated AbstractWriteAttributeHandler constructors in wildfly-server

---

threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorAdd.java
threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolAdd.java
threads/src/main/java/org/jboss/as/threads/ThreadFactoryAdd.java
threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolAdd.java

https://issues.redhat.com/browse/WFCORE-6917

WFCORE-6917 Remove usage of deprecated AbstractAddStepHandler constructors in threads subsystem

---

request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerRootDefinition.java
request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemAdd.java

https://issues.redhat.com/browse/WFCORE-6915

WFCORE-6915 Remove usage of deprecated AbstractAddStepHandler constructors in request-controller subsystem

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6885

[WFCORE-6885] Upgrade Apache Mina SSHD to 2.13.1

---

host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainIncludesValidationWriteAttributeHandler.java
host-controller/src/main/java/org/jboss/as/domain/controller/operations/SocketBindingGroupResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/ProfileResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/SocketBindingResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/discovery/DiscoveryOptionResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/discovery/StaticDiscoveryResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/DiscoveryWriteAttributeHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/DomainControllerWriteAttributeHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerRestartRequiredServerConfigWriteAttributeHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/operations/StaticDiscoveryWriteAttributeHandler.java
host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
host-controller/src/main/java/org/jboss/as/host/controller/resources/SslLoopbackResourceDefinition.java
host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOrderedChildResourceSyncModelTestCase.java

https://issues.redhat.com/browse/WFCORE-6923

WFCORE-6923 Remove usage of deprecated AbstractWriteAttributeHandler constructors in host-controller

---

security-manager/src/main/java/org/wildfly/extension/security/manager/DeploymentPermissionsResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6916

WFCORE-6916 Remove usage of deprecated AbstractAddStepHandler constructors in security-manager subsystem

---

core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ConfigurationChangeResourceDefinition.java
core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6909

WFCORE-6909 Remove usage of deprecated AbstractAddStepHandler constructors in core-management subsystem

---

host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
version/src/main/java/org/jboss/as/version/Version.java

Jira issue: https://issues.redhat.com/browse/WFCORE-6880

[WFCORE-6880] Bump the kernel management API version to 27.0.0

---

jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRootResource.java
jmx/src/main/java/org/jboss/as/jmx/JmxAuditLoggerResourceDefinition.java
jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorResource.java
jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java

https://issues.redhat.com/browse/WFCORE-6925

WFCORE-6925 Remove usage of deprecated AbstractWriteAttributeHandler constructors in jmx subsystem

---

jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java
jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorAdd.java

https://issues.redhat.com/browse/WFCORE-6912

WFCORE-6912 Remove usage of deprecated AbstractAddStepHandler constructors in jmx subsystem

---

logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
logging/src/main/java/org/jboss/as/logging/LoggingResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/filters/FilterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/CustomFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/formatters/StructuredFormatterResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/AbstractHandlerDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
logging/src/main/java/org/jboss/as/logging/handlers/SocketHandlerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/handlers/SyslogHandlerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/loggers/LoggerOperations.java
logging/src/main/java/org/jboss/as/logging/loggers/LoggerResourceDefinition.java
logging/src/main/java/org/jboss/as/logging/loggers/RootLoggerResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6926

WFCORE-6926 Remove usage of deprecated AbstractWriteAttributeHandler constructors in logging subsystem

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java

https://issues.redhat.com/browse/WFCORE-6940

WFCORE-6940 Allow null ManagementResourceRegistrar.register(...)

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java

https://issues.redhat.com/browse/WFCORE-6954

WFCORE-6954 (wildfly-subsystem) Do not auto-register add/remove resource operations for runtime resources.

---

controller/src/main/java/org/jboss/as/controller/ResourceRegistration.java
controller/src/test/java/org/jboss/as/controller/ResourceRegistrationTestCase.java
subsystem/src/main/java/org/wildfly/subsystem/resource/PathElementProvider.java
subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandler.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandlerDescriptor.java

https://issues.redhat.com/browse/WFCORE-6945

WFCORE-6945 Required child resource logic in wildfly-subsystem is not stability-level aware

---

controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java

https://issues.redhat.com/browse/WFCORE-6963

[WFCORE-6963] improve AbstractModelResource.hasChildren efficiency

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6978

[WFCORE-6978] Upgrading JBoss Marshalling to 2.2.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-6983

[WFCORE-6983] Upgrade JBoss Logging to 3.6.1.Final.

---

controller/src/main/java/org/jboss/as/controller/operations/validation/IntRangeValidator.java
controller/src/main/java/org/jboss/as/controller/operations/validation/LongRangeValidator.java
elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/MemoryPoolMXBeanAttributeHandler.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/MemoryPoolResourceDefinition.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/ThreadMXBeanCpuTimeHandler.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/ThreadMXBeanThreadInfoHandler.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/ThreadMXBeanThreadInfosHandler.java
platform-mbean/src/main/java/org/jboss/as/platform/mbean/ThreadMXBeanUserTimeHandler.java
server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java

https://issues.redhat.com/browse/WFCORE-6993

WFCORE-6993 Add constants for common int/long range validators

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-6996

[WFCORE-6996] Upgrade Apache Commons CLI from 1.8.0 to 1.9.0

---

controller/src/main/java/org/jboss/as/controller/parsing/ManagementSchema.java
controller/src/main/java/org/jboss/as/controller/parsing/ManagementSchemas.java
controller/src/main/java/org/jboss/as/controller/parsing/ManagementXmlReaderWriter.java
controller/src/main/java/org/jboss/as/controller/parsing/UnstableManagementReaderWriter.java
host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml.java
host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml.java
host-controller/src/test/java/org/jboss/as/domain/controller/parsing/SupportedNamespaceParsingTestCase.java
host-controller/src/test/java/org/jboss/as/host/controller/parsing/SupportedNamespaceParsingTestCase.java
server/src/main/java/org/jboss/as/server/parsing/StandaloneXml.java
server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_20.java
server/src/main/resources/schema/wildfly-config_community_20_0.xsd
server/src/test/java/org/jboss/as/server/parsing/SupportedNamespaceParsingTestCase.java
testsuite/domain/src/test/resources/base-server-config.xml
testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
testsuite/domain/src/test/resources/host-configs/host-primary.xml
testsuite/domain/src/test/resources/host-configs/host-secondary.xml

Also update the SupportedNamespaceParsingTestCases to include stability level tests.
https://issues.redhat.com/browse/WFCORE-6829
I will close after CI and submit along with the PR that adds new attributes, first I want to check if there are any unintended consequences across the wider testsuites - a simple local build passes fine.

[WFCORE-6829] Add a new 'urn:jboss:domain:community:20.0' schema.

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7009

[WFCORE-7009] Upgrade SLF4J from 2.0.13 to 2.0.16

---

.github/workflows/check_logging.yml
check_logging.sh

Issue: https://issues.redhat.com/browse/WFCORE-6955
WildFly Core part of https://github.com/wildfly/wildfly/pull/18116

WFCORE-6955 Add a CI job to check for non-i18n INFO/WARN/ERROR logging

---

cli/assembly.xml
cli/pom.xml
core-feature-pack/galleon-common/src/main/resources/packages/core.misc.common/package.xml
core-feature-pack/galleon-common/src/main/resources/packages/tools/package.xml
core-feature-pack/galleon-common/src/main/resources/packages/tools/pm/wildfly/tasks.xml
core-feature-pack/galleon-feature-pack/pom.xml
elytron-tool-wrapper/assembly.xml
elytron-tool-wrapper/pom.xml
pom.xml

Issue: https://issues.redhat.com/browse/WFCORE-7019
WARNING: Full Integration tests will fail until this wildfly PR: https://github.com/wildfly/wildfly/pull/18289 is merged.

Fix for WFCORE-7019, Delay the construction of shaded jars at provisioning time

---

service/src/main/java/org/wildfly/service/Installer.java
service/src/main/java/org/wildfly/service/capture/FunctionExecutor.java
service/src/main/java/org/wildfly/service/capture/FunctionExecutorRegistry.java
service/src/test/java/org/wildfly/service/DefaultServiceInstallerTestCase.java

https://issues.redhat.com/browse/WFCORE-7039

WFCORE-7039 Add Installer.Builder methods to run arbitrary tasks on service start/stop/removal.

---

core-feature-pack/common/src/main/resources/content/bin/domain.conf
core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
core-feature-pack/common/src/main/resources/content/bin/standalone.conf
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
core-feature-pack/galleon-common/src/main/resources/feature_groups/host-jvm.xml
pom.xml
testsuite/client-old-server/src/test/java/org/wildfly/client/old/server/util/OldVersionTestRunner.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnHttpTestCase.java
testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnTestCase.java
testsuite/domain/src/test/resources/host-configs/host-primary-elytron-no-legacy-realms.xml
testsuite/domain/src/test/resources/host-configs/host-primary-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-primary-ssl-1way-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-primary-ssl-2way-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-secondary-elytron-no-legacy-realms.xml
testsuite/domain/src/test/resources/host-configs/host-secondary-ssl-1way-elytron.xml
testsuite/domain/src/test/resources/host-configs/host-secondary-ssl-2way-elytron.xml
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/cli/boot/ops/CliBootOperationsTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/WildFlyManagedConfiguration.java
testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java

https://issues.redhat.com/browse/WFCORE-7049

[WFCORE-7049] Remove MaxMetaspaceSize settings

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7057

[WFCORE-7057] Upgrade JBoss Parent to 47

---

pom.xml

* Upgrading snakeyaml from 2.2 to 2.3
Issue: https://issues.redhat.com/browse/WFCORE-6997

[WFCORE-6997]: Upgrade snakeyaml to 2.3

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7068

[WFCORE-7068] Upgrade JBoss Modules to 2.1.6.Final

---

pom.xml

Jira Issue: https://issues.redhat.com/browse/WFCORE-7054

[WFCORE-7054] Upgrade BouncyCastle from 1.78.1 to 1.79

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7056

[WFCORE-7056] Upgrade SSHD from 2.13.2 to 2.14.0

---

elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
pom.xml

https://issues.redhat.com/browse/WFCORE-7071
https://github.com/wildfly-security/wildfly-elytron-ee/compare/3.0.3.Final...3.1.1.Final
https://issues.redhat.com/browse/WFCORE-7072

[WFCORE-7071] / [WFCORE-7072] Elytron EE 3.1.1.Final and use the new PolicyUtil to manage the java.security.Policy object

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7084

[WFCORE-7084] Upgrade Installation Manager API to 1.1.0.Final

---

core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7093

[WFCORE-7093] Upgrade WildFly Legacy Tests to 9.0.0.Final

---

testsuite/embedded/pom.xml

https://issues.redhat.com/browse/WFCORE-7109

[WFCORE-7109] Upgrade Logback to 1.5.13

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7128

[WFCORE-7128] Upgrade Byteman to 4.0.24

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7131
Upstream PR: https://github.com/wildfly/wildfly-core/pull/6316

[WFCORE-7131] Upgrading JBoss Marshalling to 2.2.2.Final

---

testsuite/server-provisioning.xml

https://issues.redhat.com/browse/WFCORE-7126

[WFCORE-7126] Remove cruft testsuite/server-provisioning.xml

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7151

[WFCORE-7151] Upgrade WildFly Galleon Plugins to 7.3.1.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7168
Diff: https://github.com/wildfly-security/wildfly-elytron-ee/compare/3.1.1.Final...3.1.3.Final

[WFCORE-7168] Upgrade Elytron EE to 3.1.3.Final

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7174

[WFCORE-7174] Upgrade the JBoss Logging Tools to 3.0.4.Final.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7179
https://github.com/wildfly-security/wildfly-elytron-ee/compare/3.1.3.Final...3.1.4.Final
https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12323427&version=12446699

[WFCORE-7179] Upgrade Elytron EE to 3.1.4.Final

---

server/src/main/java/org/jboss/as/server/BootstrapImpl.java
server/src/main/java/org/jboss/as/server/DomainServerMain.java
server/src/main/java/org/jboss/as/server/controller/resources/ModuleInfoHandler.java
server/src/main/java/org/jboss/as/server/controller/resources/ModuleLoadingResourceDefinition.java
server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
server/src/main/java/org/jboss/as/server/deployment/module/DeploymentVisibilityProcessor.java
server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7170

[WFCORE-7170] Reduce ModuleIdentifier usage from Server module

---

server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7170

[WFCORE-7170] Remove unnesesary .toString() call

---

host-controller/src/main/java/org/jboss/as/host/controller/operations/DiscoveryOptionAddHandler.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7171

[WFCORE-7171] Remove ModuleIdentifier usage from Host Controller module

---

controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java

https://issues.redhat.com/browse/WFCORE-7176
Whoops.

WFCORE-7176 PersistentResourceXMLDescription created via PersistentResourceXMLDescription.Factory is not wrappable

---

server/src/main/java/org/jboss/as/server/ServerService.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleExtensionListProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleExtensionNameProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndex.java
server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModule.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7175

[WFCORE-7175] Remove ModuleIdentifier usage from server/moduleservice

---

security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleAliasChecker.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleClassPathProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleIdentifierProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
server/src/main/java/org/jboss/as/server/deployment/module/descriptor/ModuleStructureSpec.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7184

[WFCORE-7184] Remove ModuleIdentifier usage from server/deployment

---

jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractStreamServerService.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorAdd.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/InjectedNetworkBindingStreamServerService.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/InjectedSocketBindingStreamServerService.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/Protocol.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemModel.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemSchema.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemTransformationDescriptionFactory.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingTransformerRegistration.java
remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java
remoting/subsystem/src/main/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties
remoting/subsystem/src/main/resources/schema/wildfly-remoting_8_0.xsd
remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformerTestCase.java
remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-8.0.xml
remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-transform-6.0.0.xml
remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-transform-rejects.xml
server/src/main/java/org/jboss/as/server/operations/NativeManagementAddHandler.java

Built on top of #6360
Jira issue: https://issues.redhat.com/browse/WFCORE-5718

[WFCORE-5718] Test rejects against legacy versions and transformers tests against EAP 8.0.0

---

controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java

https://issues.redhat.com/browse/WFCORE-7195
Extracted from https://github.com/wildfly/wildfly-core/pull/6261

WFCORE-7195 Fix inconsistencies between model and schema in PersistentResourceXMLParserTestCase

---

subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandler.java
subsystem/src/main/java/org/wildfly/subsystem/resource/operation/DescribedOperationStepHandler.java

https://issues.redhat.com/browse/WFCORE-7188

WFCORE-7188 Fix required child detection.

---

elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
elytron/src/main/java/org/wildfly/extension/elytron/PolicyParser.java
elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java

https://issues.redhat.com/browse/WFCORE-7196
Extracted from https://github.com/wildfly/wildfly-core/pull/6261

WFCORE-7196 Fix illegal duplicate children/attributes in XML descriptions of elytron subsystem.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7204

[WFCORE-7204] Upgrade to unstable-api-annotation-utils 1.0.2.Final

---

server/src/main/java/org/jboss/as/server/suspend/SuspendController.java

https://issues.redhat.com/browse/WFCORE-7178
Fixes intermittent test failures in SuspendControllerTestCase.

WFCORE-7178 Fix race condition in SuspendController resume/suspend that can cause CompletionStage to finish before its state changes.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7212

[WFCORE-7212] Upgrading JBoss Marshalling to 2.2.3.Final

---

controller/src/main/java/org/jboss/as/controller/xml/XMLContent.java

https://issues.redhat.com/browse/WFCORE-7217

WFCORE-7217 Defer to AttributeMarshaller.marshallElementContent(..) for writing element content

---

subsystem/src/main/java/org/wildfly/subsystem/service/ResourceServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-7221

WFCORE-7221 Add resuable empty ResourceServiceInstaller implementation

---

controller/src/main/java/org/jboss/as/controller/interfaces/LoopbackAddressInterfaceCriteria.java
controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ConfigurationChangeResourceDefinition.java
domain-management/src/main/java/org/jboss/as/domain/management/LegacyConfigurationChangeResourceDefinition.java
testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/yaml/YamlExtensionTestCase.java

https://issues.redhat.com/browse/WFCORE-7224

WFCORE-7224 LoopbackAddressInterfaceCriteria needs to be more robust

---

service/src/main/java/org/wildfly/service/ServiceInstaller.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java

https://issues.redhat.com/browse/WFCORE-7226

WFCORE-7226 Add convenience ServiceInstaller.Builder.provides(...) methods accepting ServiceDescriptors

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7230

[WFCORE-7230] Upgrade JBoss Parent to 49

---

elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java

https://issues.redhat.com/browse/WFCORE-7233

[WFCORE-7233] Remove unused AuthConfigFactory delegation code.

---

pom.xml

https://issues.redhat.com/browse/WFCORE-7245

[WFCORE-7245] Upgrading JBoss MSC to 1.5.6.Final

---

controller/src/main/java/org/jboss/as/controller/audit/AuditLogItem.java
controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7246

[WFCORE-7246] Remove unused AuditLogItem.getResultantModel

---

service/src/main/java/org/wildfly/service/ServiceInstaller.java
subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java

Fixes whoopsie in https://github.com/wildfly/wildfly-core/pull/6400
https://issues.redhat.com/browse/WFCORE-7226

WFCORE-7226 Fix generic type parameter for service descriptor in ServiceInstaller.provides(...)

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7227

[WFCORE-7227] Update Jandex to 3.3.0

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-5898

[WFCORE-5898] Intermittent failures in DeploymentScannerUnitTestCase

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/deployment/DeploymentScannerUnitTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7271

[WFCORE-7271] Fix DeploymentScannerUnitTestCase intermittent failures

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7183

[WFCORE-7183] Upgrade SLF4J from 2.0.16 to 2.0.17

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/provisioning/ProvisioningConsistencyTestCase.java
testsuite/shared/src/main/java/org/jboss/as/test/shared/FileUtils.java

ISSUE: https://issues.redhat.com/browse/WFCORE-7269
A CI [run on s390](https://ci.wildfly.org/buildConfiguration/WildFlyCore_MainNightlyJobs_MainLinuxS390OpenJ917/505102) of this fix passed.

Fix for WFCORE-7269, ProvisioningConsistencyTestCase failures with s390 Semeru

---

pom.xml
testsuite/pom.xml

https://issues.redhat.com/browse/WFCORE-7280

[WFCORE-7280] Use org.wildfly:wildfly-maven-gpg-plugin for GPG signing

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7279

[WFCORE-7279] Upgrade WildFly Galleon Plugins to 7.4.0.Final

---

platform-mbean/src/main/java/org/jboss/as/platform/mbean/ExtendedGarbageCollectorMBean.java
testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/ReadResourceTestCase.java

https://issues.redhat.com/browse/WFCORE-7281

[WFCORE-7281] Work with JDK versions with differing CompositeData structures for GarbageCollectorMXBean lastGcInfo

---

testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/yaml/YamlExtensionTestCase.java

Jira issue: https://issues.redhat.com/browse/WFCORE-7262

[WFCORE-7262] Refactor YamlExtensionTestCase Assertions

---

controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContext.java
controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java

... and harmless code cleanup and fix typos
Jira issue: https://issues.redhat.com/browse/WFCORE-7152

[WFCORE-7152] Add RBAC enforcement information to the OperationContext javadoc

---

component-matrix-builder/pom.xml
core-model-test/test-controller-optional/pom.xml
core-model-test/tests/pom.xml
domain-http/error-context/pom.xml
io/tests/pom.xml
pom.xml
remoting/tests/pom.xml
subsystem-test/tests/pom.xml
testsuite/pom.xml

https://issues.redhat.com/browse/WFCORE-7263

[WFCORE-7263] Prepare for deployment to the Nexus 3 JBoss Nexus

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7314

[WFCORE-7314] Upgrade io.smallrye:jandex from 3.3.2 to 3.4.0

---

core-model-test/tests/pom.xml
io/tests/pom.xml
remoting/tests/pom.xml
subsystem-test/tests/pom.xml

https://issues.redhat.com/browse/WFCORE-7315

[WFCORE-7315] Convert disabling of nxrm3-maven-plugin deploy to using skipNexusStagingDeployMojo

---

installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrPrepareRevertHandler.java

Issue: [WFCORE-7328](https://issues.redhat.com/browse/WFCORE-7328)

WFCORE-7328: add missing attribute

---

server/src/main/java/org/jboss/as/server/deployment/Phase.java

https://issues.redhat.com/browse/WFCORE-7346

[WFCORE-7346] Introducing new INSTALL_WS_VERIFICATION phase

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7357

[WFCORE-7357] Upgrade SSHD from 2.15.0 to 2.16.0

---

elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
pom.xml

https://issues.redhat.com/browse/WFCORE-7366
https://issues.redhat.com/browse/WFCORE-7367
https://issues.redhat.com/browse/WFCORE-7322

[WFCORE-7366] / [WFCORE-7367] / [WFCORE-7322] Elytron Component Upgrades and Jakarta Authorization Activation

---

pom.xml

Jira issue: https://issues.redhat.com/browse/WFCORE-7324

[WFCORE-7324] Upgrade Apache Commons CLI from 1.9.0 to 1.10.0

---

cli/pom.xml
core-feature-pack/common/pom.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/io/smallrye/common/expression/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/io/smallrye/common/net/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/io/smallrye/common/os/main/module.xml
core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/common/main/module.xml
logging/src/test/modules/org/wildfly/common/main/module.xml
pom.xml

built on https://github.com/wildfly/wildfly-core/pull/6482
Jira issue: https://issues.redhat.com/browse/WFCORE-7337

[WFCORE-7337] Upgrade wildfly-common to 2.0.1
